### ISSUE TITLE
Typos and content on the website is misleading some users

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1001]
_Typos and content on the website is misleading some users_

## Description

As a visitor to the GC Notify website, I need to be able to quickly and easily get accurate information about limits and constraints so that I can decide whether or not GC Notify will meet my needs or pass along the correct information to a decision maker on my team. 

WHY are we building?
There are some typos or errors on the GC Notify website

WHAT are we building?
Some small content changes in FR and EN

![Screen Shot 2022-11-21 at 1.25.45 PM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/8bcd86a3-e54b-4ed8-aa5d-8a2337150832)

![Screen Shot 2022-11-21 at 1.26.20 PM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/42ff6bff-d387-4b0b-b2b5-68f65d6b8051)

VALUE created by our solution
Less confusion when we demo, do usability testing and when someone new goes to the GC notify website
Fewer questions coming into Support about our limits 
Better expectations set right from the first time a user visits our website

- [x] Review by Phil C on GC Articles
- [x] Yedida to publish
- [x] Yedida to clear cache

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [x] Changes made in prod in both EN and FR 
- [x] Should say 25,000 text message fragments a year
- [x] Should say schedule and send up to 50,000 messages at once, or something like that to indicate this is our max batch size

**Comment by YedidaZalik** [comment]
Seems to be on Why GC Notify page but not on home page

**Comment by adriannelee** [comment]
they still have daily limits of 1000 SMS and 9000 email

**Comment by adriannelee** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1001?planning-poker) with Zenhub @YedidaZalik

**Comment by yaelberger-commits** [comment]
Yedida did the changes in [Figma](https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?node-id=129%3A981&t=FqKfg0bJVuQB8HLX-0) and Yael reviewed the EN before sent to translation for FR

**Comment by jimleroyer** [comment]
Went to translation!

**Comment by jimleroyer** [comment]
Back from translation. Content was updated. We need a review once the content is in GCArticles. @amazingphilippe to review it! Thank you Phil!

**Comment by amazingphilippe** [comment]
Translations in this document: https://docs.google.com/document/d/1GSd3O2sPdznWMys9JK3ZrGO_eqMgdwFqgagWY6xHUlk/edit

**Comment by amazingphilippe** [comment]
Every fixes are showing on the production site! In both languages

**Comment by jimleroyer** [comment]
Reviewed and published, done!
