### ISSUE TITLE
Notifications stuck in Redis and causing constant celery errors

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1004]
## Describe the bug 

https://docs.google.com/document/d/1EsF2_hiTo8juIC2L3jpvnZ45FEfUZMgRWbSqS_T8jXg

Somehow we have notifications in Redis that are already in the database, and we keep trying to resave them. This causes celery errors.

The reason is that when we try to remove them (the bad inflight) we try to remove it from the wrong queue. This fails silently, and eventually the inflight is expired and goes back to the inbox, where the situation repeats.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major?

## To Reproduce

It happens on its own!

## Expected behavior

No stuck inflights

## Impact

- constant celery errors so that we don't know if there are real errors happening as well.
- see incident report for more details

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1004?planning-poker) with Zenhub @andrewleith @jimleroyer @jzbahrai @Pensai @sastels @smcmurtry

**Comment by andrewleith** [comment]
This has stopped the constant celery errors 🎉
