### ISSUE TITLE
Week 4: Risk mapping

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1005]
Our research has surfaced some of the risks involved in expanding to PTMs.
It can also be helpful to use the hive mind of the Notify team to identify risks.
We will do a team activity to list risks in expanding to PTMs, identify those risks that are critical and determine which risks it's necessary to address in an MVP.

**Comment by YedidaZalik** [comment]
Important to get input from all disciplines, so Sharly has added some cards asynchronously and she may add more later

[Easy retro board](https://easyretro.io/publicboard/iUmqYz4p77WjleoPhkk32N3AeXx2/b8e2d0ab-5db9-4837-912c-5f3c6bc68f54)
Password

Shows risks that we would need to address in an MVP risks in column 3. Each card gives mitigation strategy in a comment.
Risks that could be addressed later are in columns 1 & 2.  Even though these are not necessary to address in an MVP, it's important to surface these risks in our documentation. 
Red cards are risks that have potential to cause harm to anyone (one of us, a public servant, a recipient or anyone else).

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1005?planning-poker) with Zenhub @YedidaZalik

**Comment by YedidaZalik** [comment]
Sharly added her input

**Comment by andrewleith** [comment]
Activity completed, critical risks identified, mitigations identified.

**Comment by andrewleith** [comment]
cc: @josh-cds

**Comment by andrewleith** [comment]
- retro has been shared with Josh for review; findings will be included in discovery report
