### ISSUE TITLE
Test sends are incorrectly counted towards SMS limits

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1006]
## Describe the bug 

When sending messages using a test key, we are incrementing the counter that keeps track of daily SMS fragments.  We should not increment in this case.

Scenarios that should not count towards limits:
- API one-off, API BULK for :
   - Sending using TEST API key
   - Sending using LIVE API key with TEST phone numbers (i.e. `+16132532222`)
   - Sending using TEAM API key with TEST phone numbers (i.e. `+16132532222`)
- ADMIN one-off, ADMIN CSV for:
   - Sending using TEST phone numbers (i.e. `+16132532222`) 

Scenarios that should not be allowed:
- API BULK that mixes test/non-test numbers
- ADMIN CSV that mixes test/non-test numbers

Note: see [documentation](https://documentation.notification.canada.ca/en/testing.html) for info on test phone numbers.

## [Bug Severity]
SEV-3 Minor (https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

## To Reproduce

1. Check redis counter for your service 
2. Send an SMS using a test key
3. Check the redis counter for that service
4. See that it has incremented

## Expected behavior
- Counter should not increment

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team:

**Comment by jimleroyer** [comment]
Andrew investigated the issue and uncovered more. He will update the card and write tests around these.

**Comment by andrewleith** [comment]
@whabanks is reviewing the PR

**Comment by jimleroyer** [comment]
It has been reviewed but not merged yet due to code freeze.

**Comment by yaelberger-commits** [comment]
Merged last week, either has been released or will be released today

**Comment by jimleroyer** [comment]
| Notification Type | Mode   | Key Type | Pass | Notes                                                                                                                                                                                  |
|-------------------|--------|----------|------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Email             | Atomic | Test     | Yes  | Sending **does not** show in the dashboard but **does** show in the API message log.                                                                                                   |
| Email             | Atomic | Team     | Yes  | Sending **does** show in the dashboard and API message logs.                                                                                                                           |
| Email             | Atomic | Live     | Yes  | Sending **does** show in the dashboard and API message logs.                                                                                                                           |
| Email             | Bulk   | Test     | Yes  | Sending **does** show in the API message logs and bulk sends dashboard. The bulk send dashboard reports an always sending notification.                                                |
| Email             | Bulk   | Team     | Yes  | Sending **does** show in the API message logs and bulk sends dashboard. The bulk send dashboard reports an always sending notification.                                                |
| Email             | Bulk   | Live     | Yes  | Sending appears **does** show in API message logs and in bulk sends dashboard.                                                                                                         |
| SMS               | Atomic | Test     | Yes  | Sending with test numbers **do not** show in the dashboard or API message logs. Sending with real number **does not** show in the dashboard but **does** show in the API message logs. |
| SMS               | Atomic | Team     | Yes  | Sending with test numbers **do not** show in the dashboard or the API message logs.                                                                                                    |
| SMS               | Atomic | Live     | Yes  | Sending with test numbers **do not** show in the dashboard or API message logs.                                                                                                        |
| SMS               | Bulk   | Test     | Yes  | Sending with test numbers **does** show in the API message logs and the bulk sends dashboard. Sending with real number shows in both too.                                              |
| SMS               | Bulk   | Team     | Yes  | Cannot send with test numbers as this is not part of the team. Sending with real number shows in both API Key message logs and bulk sends dashboard.                                   |
| SMS               | Bulk   | Live     | Yes  | Sending with test numbers **does** show in the API message logs and bulk sends dashboard. The bulk send dashboard reports an always sending notification.                              |

**Comment by andrewleith** [comment]
- This has been QA'd; need to create card about other issues found

**Comment by jimleroyer** [comment]
New issues created under #1076
