### ISSUE TITLE
SMS limits v2 story mapping

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1008]
## Description

Building a journey map to understand all the touchpoints caused by text messages fragments

WHY are we building? To align on an V2 experience for the Notify team and our clients. Notify needs to have a reference to build prototypes, and test the prototypes, and move forward with this new sms limit feature
WHAT are we building? A journey map with the team. We want to include as many people as possible. 
VALUE created by our solution. We'll have a reference for creating prototypes and move forward. 

Journey map will be done in Miro: https://miro.com/app/board/uXjVO6TPyIs=/?moveToWidget=3458764536162991339&cot=14

## Acceptance Criteria** (Definition of done) 

- [ ] We have a journey map as a reference.
- [ ] We draw a line for V2. The journey map may contain more than we actually want to build

---

- [ ] Can misuse of this feature cause harm? If yes, create an alert

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by amazingphilippe** [comment]
Setting up Miro and Figma for future team work

**Comment by andrewleith** [comment]
@amazingphilippe looking for volunteers for this effort

**Comment by jimleroyer** [comment]
Phil will created an event for people to join as volunteers.

**Comment by jimleroyer** [comment]
Finished mapping yesterday. Moving to done!

**Comment by jimleroyer** [comment]
Dropped the Miro board link in the Slack team channel for the team to review and Phil will present in a meeting.
