### ISSUE TITLE
Delete logged PII

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1010]
_Delete the logged PII_

## Description

We need to delete PII that was incorrectly dumped and logged following the celery error incident

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1010?planning-poker) with Zenhub @sastels @sharlychan-cds @jimleroyer

**Comment by smcmurtry** [comment]
We have had a group discussion on slack and made a decision:
- we will temporarily change the celery log retention period to 4 weeks 

That will give us enough history that we should be covered for incidents. Soon the fix to mask PII in the logs will be in production. Sometime in January, the last PII will fall outside the 4 week window and be deleted. Then we can change the retention period back to "indefinite". 

Next step: I will open a terraform PR to change the retention period.

**Comment by jimleroyer** [comment]
We won't change via TF but rather with clickops, this will be faster for a temporary modification.

**Comment by smcmurtry** [comment]
I have now changed the retention period to 30 days for the log group:
`/aws/containerinsights/notification-canada-ca-production-eks-cluster/application`
I verified that log data older than 30 days has been deleted.

**Comment by andrewleith** [comment]
- Change has been made to delete PII
- Needs to be reviewed/QA'd short term for settings - @andrewleith 
- Needs to be checked in a month to make sure all PII has been deleted - @yaelberger-commits  should we keep this card around or create a new one?

**Comment by yaelberger-commits** [comment]
@andrewleith I would recommend keeping the card in blocked with a date on it when we need to check after a month

**Comment by andrewleith** [comment]
Card moved to blocked; to be re-checked Jan 19.

**Comment by andrewleith** [comment]
✅  Qa'd to check that the log retention setting is now 1 month.

**Comment by YedidaZalik** [comment]
Will continue as blocked for around 2 more weeks

**Comment by sastels** [comment]
We are still occasionally logging errors when there's an accent in the email address, for example
```
{"log":"[2023-01-09 17:37:42,740: INFO/ForkPoolWorker-3] Cannot send notification 0b1de14a-f264-4f52-b06e-672ac23f4a13, got an invalid email address: email: \"*******.gaspésie@gmail.com
```
We could (in order of increasing work):
- just not log the error message here (that includes the email address)
- delete the email address from the error message (if it's there) before logging
- check ourselves if there's unicode in the `to` field and throw our own error saying that but not saying the email address
- possibly encode the email addresses so they work with SES - see the discussion [here](https://github.com/cds-snc/notification-planning/issues/898)

Note that this one log is the only PII I can see in the logs using the query
```
fields @timestamp, @message, @logStream
| filter kubernetes.container_name like /^celery/
| filter @message like /'to':|personalisation':|gmail|rogers|yahoo/
| limit 200
```
with log groups api lambda and k8s application. Other logged PII has been redacted as expected.

**Comment by sastels** [comment]
It turns out we added code on our end to accept accents in email addresses:
https://github.com/cds-snc/notification-utils/pull/60
However, SES is returning an error for this gaspésie email, which we change slightly and return here:
https://github.com/cds-snc/notification-api/blob/main/app/clients/email/aws_ses.py#L108

**Comment by sastels** [comment]
For now: stopped logging the email address when there's an error

**Comment by andrewleith** [comment]
- Ready for QA
- We should re-run the query every now and again to ensure no new PII is logged
- @sastels to delete the log chunk that contains the email address, and then reset retention period
-

**Comment by sastels** [comment]
Still to do:
- [ ] delete the logstream for the one PII
- [ ] set the retention back to keep forever

**Comment by sastels** [comment]
- I wrote a better query and found 44 of these email addresses containing accents. Deleted the relevant logstreams manually.
- set log retention back to never expire

**Comment by sastels** [comment]
For QA we can run the PII cloudwatch query in a week or so and verify that there is no PII in the logs.

**Comment by andrewleith** [comment]
- @sastels found one other place that logged email addresses; PR to fix this has been done, log messages with emails have been cleared
- Ready for QA

**Comment by smcmurtry** [comment]
Completed the QA steps, looks good!
