### ISSUE TITLE
Communicate privacy retention with OCIO PDPD, and share report with them

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1012]
_Communicate privacy retention with OCIO PDPD, and share report with them_

## Description

Write to PDPD about the incident and attach incident report with it.

**Comment by andrewleith** [comment]
- has been reviewd by Josh, Nisa and Yael
- @sharlychan-cds to send this off this morning

**Comment by sharlychan-cds** [comment]
Sent! Will update them when we fix the bug fully
