### ISSUE TITLE
Document retention decisions and inform TBS ATIP

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1013]
## Description
Email here: https://docs.google.com/document/d/1_vtPxDeKcVRuDDQMMEs5SEyqX9O29xjeOykjKMMqS9g/edit

Decision/ thread saved here: https://docs.google.com/document/d/175RhD5_oApC4sl9jJrnwc_86foYXgwrV1uZqsrHpSDw/edit#
As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

- [x] Draft email written to TBS ATIP
- [x] Reviewed by @yaelberger-commits 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by jimleroyer** [comment]
Working on this today.

**Comment by jimleroyer** [comment]
Sharly to update document with information in the thread. Sending to OCIO/PDPD.

**Comment by andrewleith** [comment]
- @sharlychan-cds to look at this today and prepare draft for tomorrow

**Comment by sharlychan-cds** [comment]
Draft ready for review @yaelberger-commits https://docs.google.com/document/d/1_vtPxDeKcVRuDDQMMEs5SEyqX9O29xjeOykjKMMqS9g/edit

**Comment by yaelberger-commits** [comment]
@sharlychan-cds I have reviewed. Good to go

**Comment by sharlychan-cds** [comment]
Sent email to TBS ATIP and OCIO PDPD
