### ISSUE TITLE
Bug: Fix permissions around template preview

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1019]
## Describe the bug 

There is a bug where a user has team permissions but can not save/ edit templated

 
## [Bug Severity]

SEV-3 Minor

## To Reproduce

1. You add a new team member - you can give them permissions to one folder of templates
2. The new team member goes to the template page - they can view templates that are not in any folder (# BUG 1)
3. They click on a template outside of a folder and can edit (# BUG 2 - 403) but “preview” returns a 403 error
4. They can save the template that they shouldn’t have permissions to view in the first place ( #BUG3 )

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team:

**Comment by yaelberger-commits** [comment]
@jzbahrai is this still relevant after the incident?
