### ISSUE TITLE
Change incorrect link on Notify SLA

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#1024]
The current path management link in our public SLA is in our internal CDS Github. 

Article #14: Patching security vulnerabilities in a timely manner, based on our  determination of the level of threat. We patch major vulnerabilities as soon as possible but no more than a month after we find the root cause. To learn more, read  [CDS Patch Management Guide](https://github.com/cds-snc/platform-sre-security-support/wiki/Patch-management).

We should change patch management guideline link to the public one at https://articles.alpha.canada.ca/cds-intranet-employee-guide/security-at-cds/patch-management-guideline/ 

- [x] Submit to translation
- [x] Receive translation and update the intranet link so that it can toggle languages
- [x] Update the link on Notify SLA
- [x] Update the link on Notify Security statement

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1024?planning-poker) with Zenhub @sharlychan-cds

**Comment by sharlychan-cds** [comment]
Good catch! Let me ask and see

**Comment by sharlychan-cds** [comment]
Submitted to translation

**Comment by YedidaZalik** [comment]
Changed link in EN new draft SLA here: https://docs.google.com/document/d/16uovHkvS9dHhF7_PQf7wb_xs_LY6dPZQaRs8IUDCsTg/edit#heading=h.n5fvimnreee5

**Comment by yaelberger-commits** [comment]
@YedidaZalik does this need review or translation next?

**Comment by sastels** [comment]
waiting for Josh's review

**Comment by sastels** [comment]
corrected and off to translation.

**Comment by YedidaZalik** [comment]
Yael to QA.
Link to google doc.

**Comment by yaelberger-commits** [comment]
Yael QA'd in both EN and FR and checked that all links worked properly
