### ISSUE TITLE
Change SQLAlchemy logging to remove sensitive information

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1025]
## Describe the bug 

SQL Alchemy is logging too much, i.e. do not print PII information in the console log.

SEV-4 Low

## To Reproduce

1. Cause a SQLAlchemy crash
2. look at the logs

## Expected behavior

Less logging

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1025?planning-poker) with Zenhub @sastels @jzbahrai @smcmurtry @andrewleith @whabanks

**Comment by jimleroyer** [comment]
Configuration of SQLAlchemy allows us to define sensitive fields.

**Comment by jimleroyer** [comment]
In progress: Steve checking if things break with newest changes.

**Comment by sastels** [comment]
ready for review: https://github.com/cds-snc/notification-api/pull/1703

**Comment by sastels** [comment]
For QA, I would say
- [ ] verify on staging or prod that you can still see PII in the admin (ie recipients and personalisation)
- [ ] when we do get these database errors in the future (and we get a couple a week on prod) we should see in the logs that we're still logging the notification, but the `to`, `normalised_to`, and `_personalisation` are now `*********`.

**Comment by jimleroyer** [comment]
Steve M. to QA this task.

**Comment by smcmurtry** [comment]
I have done this:  verify on staging or prod that you can still see PII in the admin (ie recipients and personalisation)
I thought about it a bit and I'm not sure how to trigger a DB error that will result in the log we want to see. I will take Steve As suggestion above and wait until one comes up naturally in prod, and then report back on if the PII is redacted.

**Comment by jimleroyer** [comment]
It seems this error didn't trigger yet in the past days. Waiting to see where that happens.

**Comment by yaelberger-commits** [comment]
Still waiting for a database error to happen

**Comment by YedidaZalik** [comment]
Waiting for database error to verify
Steve A check today to see if we got one

**Comment by yaelberger-commits** [comment]
Still no errors

**Comment by yaelberger-commits** [comment]
Maybe we're not getting errors anymore after some upgrades?

**Comment by yaelberger-commits** [comment]
Steve A checked and works now as expected
