### ISSUE TITLE
trial -> live sets daily limit to under 10K

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1029]
## Describe the bug 

If the daily limit is adjusted when a service is in trial, it will not be changed when it goes live (even if it's under our go-live limit of 10K).

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-4

## To Reproduce

1. Make a new trial service.
2. Change the daily limit to 200.
3. Go live.
4. See that the daily limit is still 200.

## Expected behavior

if limit is less than 10K it gets bumped up to 10K.

## Impact

confusing to service owners, requires them to ask for a limit increase after they go live.

## Additional context

https://cds-snc.freshdesk.com/a/tickets/9837

**Comment by whabanks** [comment]
[Related work from the past](https://github.com/cds-snc/notification-admin/pull/935)

**Comment by yaelberger-commits** [comment]
Been fixed, Steve A tested, should be merged. Check if it's ready for today's release

**Comment by yaelberger-commits** [comment]
@andrewleith will QA
Will found a PR so you could lower daily limit to less than 10,000 on go-live but maybe we don't need that anymore.

**Comment by jimleroyer** [comment]
The intent of that functionality is explained in that Trello card, an older issue tracker for Notify:
https://trello.com/c/vS357Jw7/364-be-able-to-customize-message-limit-before-turning-live

**Comment by andrewleith** [comment]
✅  QA complete, the limit correctly goes back to `10,000` even if it was changed in trial mode.
