### ISSUE TITLE
Create blazer queries to track newly created/updated templates to detect priority lane

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#1033]
# Description

As an ops lead, 
I want to identify new or updated templates with a query in blazer,
So that I can monitor the priorities of these templates on a weekly basis.

## WHY are we building?

Configure the templates in proper priority template.

## WHAT are we building?

A blazer query that provides information on:

* Recently created or updated templates.
* Surge of traffic for each of these templates, i.e. what was the max send in a minute by the service on a daily basis?
* Total daily traffic over the period of time.

## VALUE created by our solution

Have proper intelligence to decide on which templates should fall in appropriate priority lane.

# Acceptance Criteria** (Definition of done) 

- [ ] A blazer query is written that can filter by period of time and volume threshold (# daily notifications sent).

# QA Steps

- [ ] Tested by a non-developer, to make sure anyone can have the necessary information to decide on priority level.

**Comment by jimleroyer** [comment]
Query ready in blazer and will be reviewed by @sastels .

**Comment by YedidaZalik** [comment]
@whabanks has implemented @sastels suggestions
One review is sufficient and will be QA'd
