### ISSUE TITLE
Investigate registering SMS sender ID with Singapore authorities

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#1034]
# Description

As a user of Notify,
I would like to send SMS to Singapore phone numbers,
So that I can reach out recipients with no Canadian phone numbers.

Unknowns:
- Is a Sender ID needed for sending to a Singapore phone number, or just any number within Singapore?
- Could we shift the burden and responsibility to the sender to register for the ID and then if they have one, they can share it with us and we can send using it?

[Documentation](https://docs.google.com/document/d/1eWzI40rAaPd1ySfrxw8a__UcyDbGzrfU0kYfilQcX34/edit?pli=1) from GDS re: International SMS

## WHY are we building?

Increase international phone support (or keep it in this case).

## WHAT are we building?

* Register ourselves with Singapore authorities before January 31st.
* Send a sender ID when sending to Singapore destinations.

## VALUE created by our solution

Better international phone numbers support.

# Acceptance Criteria** (Definition of done) 

- [ ] GCNotify is registered with Singapore authorities.
- [ ] GCNotify has a sender ID configured when sending SMS to Singapore phone numbers.

# QA Steps

- [ ] Send to a test message to a Singapore phone number; checks if we identify with a sender ID.
- [ ] Send to a test message to a Singapore phone number after January when legislation is in place.

# AWS warning

> You are receiving this notice because you have sent at least one SMS message to a Singapore phone number in the last 90 days. If you are currently not sending SMS to Singapore and/or do not plan to send SMS further, you do not need to take any further action.

> If you are currently sending or plan to start sending SMS messages to Singapore phone numbers, you must start using a Sender ID and register it with both AWS and Singapore SMS Sender ID Registry (SSIR) prior to January 31, 2023. A Sender ID is an alphanumeric originator that identifies the sender of an SMS message, e.g. “AMAZON”. If you do not take this action prior to January 31, 2023, your SMS messages to Singapore will be impacted. You are required to take this action to comply with new regulations announced by Singapore regulator Infocomm Media Development Authority (IMDA). Starting January 31, 2023 we will start replacing all unregistered Sender IDs and generic ones such as “NOTICE” or “Secure” with “Likely-SCAM” when sending SMS to Singapore, as per IMDA requirement. Six months from January 31, 2023, we will start blocking all SMS traffic to Singapore with generic or unregistered Sender IDs, as per IMDA requirement. If you use Sender IDs already registered with Singapore SSIR and AWS, you do not need to take any further action.

> We want to emphasize that you will need to register your Singapore Sender ID(s) with both AWS and SSIR. We will make a Sender ID registration form available in the AWS Console in January 2023 to enable you to complete your AWS portion of the registration. We will send additional announcements on the date of availability of this registration form.

> At this time we ask that you obtain a Singapore unique entity number (“UEN”) if you don’t already have one. You will need this UEN to register your Sender ID(s) with both AWS and SSIR. You can review if your company has a UEN by using the following public search [1]. If you are a business located outside Singapore, you can still obtain a UEN by registering with Singapore’s Accounting and Corporate Regulatory Authority (“ACRA”). Depending on your situation, getting a UEN with ACRA can take a few weeks, so we strongly recommend that you start now. While you need to register your Sender ID(s) with SSIR as well, we ask that you do NOT register with SSIR until you register with AWS first. Registering with SSIR without a corresponding registration with AWS in place, can lead to your SMS messages getting blocked.

> If you require further assistance, reach out to AWS Support [2].
> [1] https://www.uen.gov.sg/ueninternet/faces/pages/uenSrch.jspx
> [2] https://aws.amazon.com/support

**Comment by jzbahrai** [comment]
Going to put this into blocked until @yaelberger-commits comes back

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1034?planning-poker) with Zenhub @sharlychan-cds @jimleroyer

**Comment by yaelberger-commits** [comment]
Read documentation from GDS who have an international SMS service they use who registered their Sender ID for them

**Comment by yaelberger-commits** [comment]
I'm going to close this card and we'll move ahead with #1065 instead to get guidance from AWS

**Comment by jimleroyer** [comment]
I will contact directly Siddesh, the person responsible for my ticket, as the last reply got me a bit confused. We'll clear it out in person.

> Thank you for responding back and requesting further clarification.
> 
> When a message is sent using a Long Code, there is no Sender ID associated with it. The message will have just the procured Long Code as Origination Identity on the SMS messages. The new process change applies to our customers that are already or want to use a Sender ID as Origination Identity to send SMS messages to Singapore.
> 
> If a Company is using Sender ID as Origination Identity they need to register the Sender ID before using it as Origination Identity by  2023–01–30 (1).
> 
> If you are using procured Long Code by AWS as Origination Identity, AWS will not associate this with any Sender ID and Long Code will be the Origination Identity to be used when you send SMS messages.
> 
> If you need further clarification on this, we can jump on a call and go over this further. I work from Tuesday to Saturday 9am to 6pm PST, please share your availability and phone number to call. Please feel free to reach out to me if you have any further queries and I will be more than happy to help.

**Comment by jimleroyer** [comment]
I replied to Siddesh with my phone number. He should call me today or tomorrow to clear out in person any confusion.
