### ISSUE TITLE
Missing translation for "Message has been accepted by phone"

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1035]
## Describe the bug 

After sending text message template. In bulk, but maybe as a single notification too. The success screens shows the sending status and progress. In the table, we show a column for "État", and one of the possible "État" is not translated and shows in English.

Missing translation: "Message has been accepted by phone" should be translated

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV 4

## To Reproduce

1. Switch to FR interface
1. Send a text message to many recipients
2. Monitor the status page after send. 
3. Each "État" switches from "Envoyé" to "Message has been accepted by phone" after a few seconds.

## Expected behavior

A translated label

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: Missing translation for FR users. Frustration or inability to understand what is going on. 

Impact on Recipients: none

Impact on Notify team: none

## Screenshots

[Uploading... Capture d’écran, le 2022-12-13 à 09.07.22.png]

**Comment by jzbahrai** [comment]
@andrewleith to follow up on this ticket.
