### ISSUE TITLE
Incorrect statistics are displayed on job page, for jobs older than 5 days [bug-bogue]

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1037]
## Describe the bug 

When a CSV sending job is a few days old, the "job" page (`https://notification.canada.ca/services/<service_id>/jobs/<job_id>`) becomes wrong and contradicts the stats shown on the service dashboard.

Service dashboard:
![Screen Shot 2022-12-14 at 3.26.33 PM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/8d68cded-93f9-4cac-8a45-6026444edf62)

Job page:
![Screen Shot 2022-12-14 at 3.22.01 PM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/c72ad7f4-bd69-4566-88d7-80c41595ae3d)

Here, all notifications show up as "sending" on the job page, with 0 delivered and 0 failed. On the dashboard they show us as 96 delivered and 5 failed, with 0 sending.

To see this example, search for a live service with "Upcoming" in the name on the admin console (there is only one service that matches this as of the time of writing). Then look at some of the older CSV sending jobs that are a few days old to observe the bug.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor
This is buggy and confusing. This would affect all services that send bulk jobs. But the data on the dashboard is correct, just not on the "job" page. 

## To Reproduce

1. Log into GC Notify as Admin
2. Search for a live service with "Upcoming" in the name
3. Scroll down to see the bulk/CSV sending jobs
4. Find a job that is more than 5 days old and click on the filename to get to the "job" page
5. Observe that all messages appear to be still "sending", which contradicts the job stats shown on the dashboard

## Expected behavior

Job sending stats should match the dashboard stats.

## Impact

Impact on Notify users:
This is buggy and confusing. This would affect all services that send bulk jobs. But the data on the dashboard is correct, just not on the "job" page.

**Comment by whabanks** [comment]
This looks like it is related to missing data. For the jobs that are reporting discrepancies there are no rows in the notifications table where the job_id matches the job displaying discrepancies in the UI.

**Comment by YedidaZalik** [comment]
Reviewed but not merged yet and Will is on leave for now so will wait.

**Comment by yaelberger-commits** [comment]
@whabanks has this now been merged? Is the review complete?

**Comment by whabanks** [comment]
@yaelberger-commits yes this has been merged.

**Comment by yaelberger-commits** [comment]
Should this now be moved to QA?

**Comment by YedidaZalik** [comment]
PR is up and Will has merged. Paired with Andrew yesterday and will be included in bounce rate work. Moving to QA.

**Comment by smcmurtry** [comment]
I checked on staging and I can't find any services that will allow me to QA this fix. I'll wait until this is in production and then I will be able to QA it more easily.
Also - whenever I move this card to QA, another card moves with it. Not sure why.

**Comment by yaelberger-commits** [comment]
Because it's been "connected" to 1820

**Comment by yaelberger-commits** [comment]
merged

**Comment by yaelberger-commits** [comment]
@smcmurtry will take a look once released in prod, will be easier to QA there

**Comment by smcmurtry** [comment]
This is mostly fixed - jobs older than 7 days are no longer showing all messages in "sending" status on the jobs details page. But I am seeing a weird "off by 1" error. On the details page, failed sends and successfull send counts are always off by from from the main dashboard page. 

Discussed with Will and I will make a bug card for this tomorrow.

**Comment by YedidaZalik** [comment]
Has been QA'd, mostly fixed. Now off by 1 number. May be a separate problem and Steve will make a card for that today.
