### ISSUE TITLE
Inconsistencies in use of GC Notification and Notification GC 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1043]
## Inconsistencies in use of GC Notification and Notification GC 

Inconsistent use of GC Notification and Notification GC in French on the public website and admin pages, possibly in other documentation as well. 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation
SEV-2 Not consistent use 

## Acceptance criteria
- [x] ADMIN: All references of `GC Notifcation` have been changed to `Notification GC` in the admin website
   - cds-snc/notification-admin#1467
- [x] DOCS: All references of `GC Notifcation` have been changed to `Notification GC` in the documentation site
   - cds-snc/notification-documentation#112
- [x] All GC Notification service templates that contain `GC Notification` have been changed to `Notification GC` (see below for full list
   - cds-snc/notification-api/pull/1734 
- [x] ARTICLES: All references of `GC Notifcation` have been changed to `Notification GC` in the GC Articles pages 
- [x] ARTICLES Menus: All references of `GC Notifcation` have been changed to `Notification GC` in the GC Articles pages
- [x] URLS: Change why notify url in GC articles
     - [x] GCA URLS in Admin have been updated
     - [x] Redirect in place to redirect from old url (`https://notification.canada.ca/pourquoi-gc-notification`) to new url (`https://notification.canada.ca/pourquoi-notification-gc`)
     - [x] WAF rules have been updated
- [x] Support channel
- [x] INTRANET: All references of `GC Notifcation` have been changed to `Notification GC` on the intranet
- [x] CDS website: All references of `GC Notifcation` have been changed to `Notification GC` on the CDS Website
- [x] Service name and sending email address for GC Notify service are changed in PROD
- [x] Service name and sending email address for GC Notify service are changed in STAGING

<details>
  <summary>PROD Templates to update</summary>
  
  - `ece42649-22a8-4d06-b87f-d52d5d3f0a27`
  - `36fb0730-6259-4da1-8a80-c8de22ad4246`
  - `8a31520f-4751-4789-8ea1-fe54496725eb`
  - `b3c766e6-be32-4edf-b8db-0f04ef404edc`
  - `fdc43aef-d462-44d6-a59a-ae2c6154fe6d`
  - `618185c6-3636-49cd-b7d2-6f6f5eb3bdde`
  - `eb4d9930-87ab-4aef-9bce-786762687884`
  - `a42f1d17-9404-46d5-a647-d013bdfca3e1`
  - `203566f0-d835-47c5-aa06-932439c86573`
  - `592daf60-d348-433d-857f-c7ebf3f9b740`
  - `4f46df42-f795-4cc4-83bb-65ca312f49cc`
  - `299726d2-dba6-42b8-8209-30e1d66ea164`
  - `c73f1d71-4049-46d5-a647-d013bdeca3f0`
  - `7141ff4f-ae17-4d8c-8a56-3c03c4e07e37`
  - `74ce6046-6b55-4d2e-aab0-b570ed38bf82`
  - `236ecaa5-78a3-462b-ad18-8af730783753`
  - `0880fbb1-a0c6-46f0-9a8e-36c986381ceb`
  - `4293e941-c60e-46bf-9a7d-39107706f81a`
  - `17599286-a754-42bb-9eff-426b2b218d80`
  - `a8efb4a2-baaf-417b-b6a3-f56a994bf170`
  - `d74aa052-8d0a-4d82-b0db-4f8440468240`
  - `474e9242-823b-4f99-813d-ed392e7f1201`
  - `a2a888a8-f527-4138-970e-60b92f913a7d`
  - `13d01e1a-bf9d-450a-bff5-adc6177fff0e`
  - `82114cac-1586-49f6-93e6-3269cba36d17`
  - `689573a5-031d-497e-bb1b-1ad465cc544b`
  - `a3962271-f0b5-4ff4-a85e-a5214d93ac56`
  - `3df96c43-ff2e-47b9-9269-f2c93d10f78e`
  - `e7478d6e-d8ec-462c-a7f5-97b54b8b6adc`
  - `4c697e22-1a2c-4793-bbaf-097746ea8a95`
  - `fd29f796-fcdc-471b-a0d4-0093880d9173`
  - `5d3e4322-4ee6-457a-a710-c48755f6b643`

</details>

## To Reproduce

1. Go to the Notify website in french
2. Click and scroll around and see GC Notification used in some places and Notification GC used in others

## Expected behavior

We need to finalize and decide which version is correct and apply it everywhere consistently
Other CDS products are named as follows:

| Product  | EN | FR |
| ------------- | ------------- | ------------- |
| Forms  | GC Forms  | Formulaires GC |
| Articles  | GC Articles | Articles  GC |

## Impact

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team: 

## Screenshots

![Screen Shot 2022-12-23 at 9.20.38 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/d51c0c41-99fd-49f4-a7c8-ca004b6a4dc0)
## Additional context

- [x] @YedidaZalik will do some research to find out how other teams handle this translation (GC Forms for example, other GoC services)

**Comment by yaelberger-commits** [comment]
Need to make some decisions about which version to use

**Comment by yaelberger-commits** [comment]
Embedded in translation string in code. We can search code for GC Notification and swap and replace for Notification GC or vice versa

**Comment by yaelberger-commits** [comment]
API documentation we can search documentation repo to search and replace

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1043?planning-poker) with Zenhub @YedidaZalik @andrewleith @jimleroyer @jzbahrai @sastels @smcmurtry @whabanks

**Comment by YedidaZalik** [comment]
@YedidaZalik met with Phil and Linguistic Svcs (Simon, Nick and Marie-Sophie).
**Decision taken:** Notification GC
Notify team had already decided:
- Yedida to make the changes on the Notify pages in GC Articles
-Embedded in translation string in code. We can search code for GC Notification and swap and replace for Notification GC or vice versa for hard coded pages, will need to search and replace individually for GC Articles pages
-API documentation we can search documentation repo to search and replace

Phil pointed out we should also check the following:
- GC Notify templates: recent translations (from past year) should be correct but we could do control F and check
- Support channel
- Intranet
- CDS website

**Comment by YedidaZalik** [comment]
Reviewed and edited in GC Articles.  In several cases, both versions "Notification GC" and "GC Notification" are used in different places in the same document. Will review one more time on Friday or Monday to make sure I did not miss any instances.

**Comment by YedidaZalik** [comment]
Reviewed GC Articles pages one more time and updated menu as well.
Did not update URLs as @andrewleith explained that if we do decide to do that we will need to update the admin code as well as it contains these URLs.

**Comment by yaelberger-commits** [comment]
App title is incorrect
Should we change URLs? If we do we need to update WAF rules and ADMIN

**Comment by yaelberger-commits** [comment]
2 PRs approved and going out today for ADMIN and documentation. 
Need to update templates

**Comment by YedidaZalik** [comment]
Keenan ran a check in the Intranet. Found on this page only: https://articles.alpha.canada.ca/cds-intranet-employee-guide/fr/les-equipes-du-snc-2/  
Keenan corrected.

Charlotte checked CDS website. It's correct on most prominent place:https://numerique.canada.ca/suite-de-produits/
Next week Vic will do a sweep of the code in case it's in any older/hidden web pages.

**Comment by YedidaZalik** [comment]
Changed instances in 
https://docs.google.com/document/d/1YsgCp3fBrdK2Sx2y-d0IW0G3GFfHRrLJAvhJY3N6BOc/edit#heading=h.a9i7kdz0qwt3
and
https://docs.google.com/document/d/1b0OKl2r_oqch05tIneOPi5P-XRdKRO66/edit#

Need decision about whether to change service name as could impact emails going into junk if we were safelisted by departments

**Comment by yaelberger-commits** [comment]
Andrew was going to make a PR with migration, but all the new lines. Now trying to export the data out of tables while preserving while adding new lines. 
Hopefully a migration PR this morning
How to handle the downgrade is still a question to discuss

**Comment by yaelberger-commits** [comment]
Yedida will check with Keenen that Intranet is updated.
Yedida and Jimmy P updated all support related things

**Comment by yaelberger-commits** [comment]
Ramya working on solution articles in freshdesk still for support

**Comment by yaelberger-commits** [comment]
Andrew finished migration to update templates last week

**Comment by yaelberger-commits** [comment]
Next up is change URL in GC Articles

**Comment by andrewleith** [comment]
- This should go out today, just need someone from the Articles team to clear the cache

**Comment by yaelberger-commits** [comment]
Went out yesterday. Need team access to clear cache
