### ISSUE TITLE
Remove ZenDesk code from api

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1047]
## Describe the bug 

When a demo request is made, api creates both a FreshDesk ticket and a ZendDesk ticket. However, we don't use ZenDesk anymore, and since the license has expired, api throws an error (that then gets posted to #notification-ops).

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-4 Low

## To Reproduce

1. Make a demo request
2. See the error in the api lambda logs and in the #notification-ops channel

## Expected behavior

We don't call ZenDesk and thus do not generate an error.

## Impact

Just us seeing and dealing with the errors. The ticket still gets generated in FreshDesk, and the user gets the "Thank you for contacting us" page.

## Additional context

https://cds-snc.freshdesk.com/a/tickets/14656

**Comment by patheard** [comment]
I'm planning to work on this after I finish the Salesforce integration, so hopefully it'll be done this week.

**Comment by patheard** [comment]
Zendesk Sell integration has now been removed.  The only remaining Zendesk in API is part of the Letter sending code tasks.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1047?planning-poker) with Zenhub @andrewleith @jzbahrai @whabanks
