### ISSUE TITLE
Discovery Report

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1049]
To do: 
- [x] Finish draft (insights, recommendations, executive summary, etc.)
- [x] Share draft with Josh for feedback
- [x] Share draft with Jimmy for feedback
- [x] Share draft with team for feedback in insights and recommendations 
- [x] Share with Leanne for feedback
- [x] Make final changes and edits
- [x] Send to linguistic services for translation
- [x] @yaelberger-commits and @amazingphilippe meet and see if we can remove EN text from FR images in FR version
- [ ] Share with CDS

DRAFT: https://docs.google.com/document/d/1ZGFAgH2AIR--NWKjwFZQXwdcTivGR1IH8xGvVGY1oC0/edit#heading=h.cdy09xcpxt4w

FR version: https://docs.google.com/document/d/15RX4XpxkucPUCw6jHDCMWYH8GJ2BytXFV8N5TC-DM3o/edit#heading=h.gjdgxs

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1049?planning-poker) with Zenhub @adriannelee

**Comment by yaelberger-commits** [comment]
Finished drafting recommendations. 
Shared initial draft (still in progress) with Jimmy and Josh

**Comment by yaelberger-commits** [comment]
Adrianne incorporating user stories throughout insights following meeting Monday
Adrianne reviewed recommendations as well
Yael can review now
Josh and Jimmy now reviewing as well

**Comment by yaelberger-commits** [comment]
Has been shared with the Notify team for feedback due Friday morning

**Comment by yaelberger-commits** [comment]
Team wrapping up review, Jimmy finishing up today. Yael will flag to Josh today he can move it through next steps

**Comment by andrewleith** [comment]
- Report is with @josh-cds now

**Comment by andrewleith** [comment]
- Will be reviewed this week

**Comment by yaelberger-commits** [comment]
Yael will check with Josh if he will send to Leanne next, or if it's back to the team for edits

**Comment by yaelberger-commits** [comment]
Yael and Adrianne will review with Josh tomorrow

**Comment by yaelberger-commits** [comment]
Shared with Josh to share with Leanne

**Comment by yaelberger-commits** [comment]
Waiting for translation

**Comment by sastels** [comment]
translating presentation for CDS upper management and waiting for translation of report to come back.

**Comment by yaelberger-commits** [comment]
Should be back from translation in the coming days. When it's ready, we will share on Slack EN and FR versions, along with the recording of the presentation

**Comment by yaelberger-commits** [comment]
Translation is back, just need the recording of the presentation to post along with both versions, but might have to wait for Adrianne to return as the recording might be in her inbox

**Comment by YedidaZalik** [comment]
Came back from translation.
We have some images in FR that are still in EN.
Challenging to recreate all charts and graphs but good start.
Waiting for recording of presentation to share out together and recording is in Adrianne's inbox.
Yael and Phil to discuss images.

**Comment by adriannelee** [comment]
Recording link: https://drive.google.com/open?id=1Fjgz7HAC8kLnh0UuNfUXv6EfI9XlbJGt

**Comment by yaelberger-commits** [comment]
@amazingphilippe can you confirm that the FR version of the report is good now with FR images/graphs?

**Comment by amazingphilippe** [comment]
Images in French report were re-labelled to be in French!

**Comment by yaelberger-commits** [comment]
Both versions of the full report and the video recording have now been shared on Slack in the General channel. Moving to Done
