### ISSUE TITLE
Discovery Presentation

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1050]
Beginning draft here: https://docs.google.com/presentation/d/1nHU84BCz6R0w-m0aZNmPpfymGL9hApzET4mmyZsenmM/edit?pli=1#slide=id.p

- [x] prepare deck
- [x] present to Platform management Feb. 8
- [x] present to CDS date TBD
- [x] send deck to linguistic services

FR version https://docs.google.com/presentation/d/1l_Yl5XzxGIFPGtQx7_mBxWuz5JgsPB8pWzPhVKawm-Y/edit#slide=id.p1
EN version https://docs.google.com/presentation/d/1nHU84BCz6R0w-m0aZNmPpfymGL9hApzET4mmyZsenmM/edit#slide=id.g204a7c7bf21_2_1702

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1050?planning-poker) with Zenhub @adriannelee

**Comment by yaelberger-commits** [comment]
Adrianne and Yael meeting today to plan presentation

**Comment by andrewleith** [comment]
- Draft is finished, waiting on @yaelberger-commits's return to continue

**Comment by andrewleith** [comment]
- @adriannelee added more on Friday; waiting for @yaelberger-commits return to review

**Comment by yaelberger-commits** [comment]
With branding services for design

**Comment by yaelberger-commits** [comment]
Dry run yesterday with Yael and Adrianne. 
Today Yael is refining her notes and practicing on her own.

**Comment by YedidaZalik** [comment]
Presenting this afternoon!!
Dry run was done and they're ready.
It's a 40 min presentation so will figure out how to share.

**Comment by smcmurtry** [comment]
We presented to Platform management on Wednesday. Getting async feedback from managers. 
TBD when presentation for all CDS will happen.

**Comment by yaelberger-commits** [comment]
Waiting for translation. 
Next steps are to merge FR content into a bilingual deck and Jimmy will help present to CDS

**Comment by jimleroyer** [comment]
Hope we're having the translations today. 🤞

**Comment by sastels** [comment]
date still TBD awaiting translation of deck.

**Comment by yaelberger-commits** [comment]
Yael will check in with linguistic services today about timeline

**Comment by yaelberger-commits** [comment]
New timeline from translation is end of this week

**Comment by yaelberger-commits** [comment]
Back from translation! I'll be working with Adrianne and Jimmy R to set a date for the optional presentation and prepare the bilingual deck

**Comment by yaelberger-commits** [comment]
Yael, Adrianne and Jimmy presented to CDS on April 14
