### ISSUE TITLE
Contact Us From Changes to prevent Alarms

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1056]
## Description

As a User I need to be able to escalate an urgent issue for immediate response so that I can continue sending notifications from my live service or limit the impact of a security issue.

As a Notify Admin

We want to fix the Contact Us form to NOT allow people to put URGENT and create an alarm
Should we change to email "assistance@cds" directly?

2 paths
- Direct email (not much we can do with rules
- Contact us form (more options to run validation)

4 users
- **Authenticated with live service**
- Authenticated with a trial service
- **Unauthenticated with a live service** 
- Unauthenticated with no live service

Possible 2 iterations
- 1st option could be no UI, have "this is urgent" validated in subject line, not email body (tried, but wasn't possible to do this using Freshdesk rules)
- 2nd iteration could be with UI changes to support form

## Acceptance Criteria** (Definition of done) 

- [x] You can create an URGENT ticket if you are a Notify user. 
- [x] You can create an URGENT security ticket if you are a member of the public.
- [x] Double check "this is urgent" doesn't trigger an opsgenie alarm if it is not in the main email but the reply email

## Additional info

Developers discussed together a potential solution to prevent extra urgent tickets. This is only a suggestion and might have fallbacks of its own:

* Only have authenticated users to be able to trigger urgent tickets.
* For authenticated users, triggering urgent tickets might be done via the support forms with corresponding content that would explain when to raise an urgent ticket.
* Because we do want members of the public to report security issues in an urgent manner, a support form option could be to report a security issue. This would implicitly be tagged as an urgent ticket. Appropriate content would accompany this option to explain what an urgent security issue might be like.

**Comment by yaelberger-commits** [comment]
Trying to fix a bug where if a user replies back and quotes our auto-reply it will have "This is urgent" in the body and it triggered an urgent alarm

**Comment by yaelberger-commits** [comment]
Maybe reconsider use of the word urgent, and instead describe what we consider as urgent, and offer checkboxes as options. Allow users to describe the issue, rather than having them label it as urgent or not

**Comment by yaelberger-commits** [comment]
Can't submit an urgent ticket as a trial service, are we sure we don't have use cases where a trial service would need to submit?

**Comment by yaelberger-commits** [comment]
Bug: If you use the form and you only have a trial service, the reply-to does not include how to escalate as urgent
If your email is not in our database, we _do_ send reply-to with escalation path

**Comment by yaelberger-commits** [comment]
We need to be able to confirm if they are a public servant before allowing them to escalate an urgent ticket

**Comment by yaelberger-commits** [comment]
Could require users to write This is Urgent in bold or caps, give the instructions instead of quoted text to copy/paste

**Comment by yaelberger-commits** [comment]
@jprince-cds changed the rule and added instructions so now a user must write URGENT in all upper case to page OpsGenie. We tested this and it works as expected.

**Comment by jprince-cds** [comment]
Linked to https://github.com/cds-snc/platform-core-services/issues/262
