### ISSUE TITLE
Task: remove snyk from repositories

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1060]
Now that we are using renovate for security patches, we can remove Snyk.  For each repo here are some tasks to check/complete.  Note that not all will apply to all repos:

Tasks:
- [x] notification-utils
   - [x] remove Snyk webhooks in github
   - [x] remove branch protection rules related to Snyk in github
   - [x] remove `.snyk` file at root of repo
   - [x] remove references to snyk in `Dockerfiles`
   - [x] remove Snyk npm package
   - [x] disable the repo in Snyk itself
- [x] notification-admin
   - [ ] remove Snyk webhooks in github
   - [ ] remove branch protection rules related to Snyk in github
   - [ ] remove `.snyk` file at root of repo
   - [ ] remove references to snyk in `Dockerfiles`
   - [ ] remove Snyk npm package
   - [ ] disable the repo in Snyk itself
- [x] notification-api
   - [ ] remove Snyk webhooks in github
   - [ ] remove branch protection rules related to Snyk in github
   - [ ] remove `.snyk` file at root of repo
   - [ ] remove references to snyk in `Dockerfiles`
   - [ ] remove Snyk npm package
   - [ ] disable the repo in Snyk itself
- [x] notification-document-download-api
   - [ ] remove Snyk webhooks in github
   - [ ] remove branch protection rules related to Snyk in github
   - [ ] remove `.snyk` file at root of repo
   - [ ] remove references to snyk in `Dockerfiles`
   - [ ] remove Snyk npm package
   - [ ] disable the repo in Snyk itself
- [x] notification-documentation
   - [ ] remove Snyk webhooks in github
   - [ ] remove branch protection rules related to Snyk in github
   - [ ] remove `.snyk` file at root of repo
   - [ ] remove references to snyk in `Dockerfiles`
   - [ ] remove Snyk npm package
   - [ ] disable the repo in Snyk itself
- [x] notification-manifests
   - [ ] remove Snyk webhooks in github
   - [ ] remove branch protection rules related to Snyk in github
   - [ ] remove `.snyk` file at root of repo
   - [ ] remove references to snyk in `Dockerfiles`
   - [ ] remove Snyk npm package
   - [ ] disable the repo in Snyk itself
- [x] notification-pr-bot
   - [ ] remove Snyk webhooks in github
   - [ ] remove branch protection rules related to Snyk in github
   - [ ] remove `.snyk` file at root of repo
   - [ ] remove references to snyk in `Dockerfiles`
   - [ ] remove Snyk npm package
   - [ ] disable the repo in Snyk itself
- [x] notification-terraform
   - [ ] remove Snyk webhooks in github
   - [ ] remove branch protection rules related to Snyk in github
   - [ ] remove `.snyk` file at root of repo
   - [ ] remove references to snyk in `Dockerfiles`
   - [ ] remove Snyk npm package
   - [ ] disable the repo in Snyk itself

**Comment by yaelberger-commits** [comment]
Take a quick look to check

**Comment by yaelberger-commits** [comment]
we can remove this: https://github.com/search?q=org%3Acds-snc%20synk&type=code

**Comment by andrewleith** [comment]
Snyk is no longer in any of our notify repositories.
