### ISSUE TITLE
Renovate bug bash

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1062]
This card is for focused testing of notify in Staging following minor version bumps. It could be things like, but not limited to, the following:

### API
- [x] Smoke tests
- [x] Send SMS
- [x] Send email
- [x] Send bulk SMS
- [x] Send bulk email

### Admin
- [x] create new user / service / template
- [x] send email
- [x] send sms
- [x] send CSV email
- [x] send CSV SMS
- [x] verify reports
- [x] verify dashboard

### DD-API
- [x] send email notification with file attached, verify it can be downloaded from dd-api

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1062?planning-poker) with Zenhub @andrewleith
