### ISSUE TITLE
Draft new Terms of Use 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1063]
_Draft new Terms of Use _

## Description

As a user, I need to be able to know the terms of use for GC Notify when I onboard and create an account so that I can make sure I comply and so I can inform management or decision makers on my team of the terms of use. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Compare SLA and TOU for duplicate content and attempt [new TOU with relevant SLA content included](https://docs.google.com/document/d/1lUWdRr_XMdFZhrd-gzkCkw-KZi-kpf9VNl2x1YCBmOQ/edit#heading=h.vptr2an12m9) (YZ)
- [x] Add in any new content required for TOU including anything relevant raised by PTM Discovery and previous brainstorms(SC)
- [x] Add language wrt information sharing agreement (SC)
- [x] Check for any info in current TOU that is no longer accurate or relevant (SC)
- [x] Document decisions as we go in a [separate document](https://docs.google.com/document/d/1L4uwQqmuCN_-v_bvTsZTdqrNgaw9atpDfdAVwDTj5ik/edit#heading=h.21l65wbgxc4h)
- [x] Update policy itemization spreadsheet when complete [YZ]

Publish checklist 
- [x] TOU and supporting changes in policy suite docs translated into FR
- [x] new TOU and policy suite docs entered on GC Articles with "New" or "Nouveau" in name
- [x] old TOU archived to a new link in articles, with the word "Archived" in front of the title along with original date of publication
- [x] Remove "New" and "Nouveau" from titles of updated TOU and policy docs, link for those TOU and policy docs changed to current link and link updated at bottom to archived version. Date of publication entered at end of each new policy doc
- [x] Clear the cache
- [x] Initial QA steps: check language toggle on current version, check link to previous version, check language toggle on previous version
- [x] Review: Anik to proof google doc against all published versions in both languages 
- [x] Scan for a11y and fix any found issues
- [x] Add link to new API section once it is online

QA
- [x] Check that all links work in EN and FR versions and that EN links go to EN pages, and FR links go to FR pages

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1063?planning-poker) with Zenhub @sharlychan-cds @YedidaZalik

**Comment by andrewleith** [comment]
- This has been started as of yesterday; there is a question in the team channel for the devs to answer

**Comment by andrewleith** [comment]
- @YedidaZalik working on this today, goal is to bring to content critique on Wednesday

**Comment by yaelberger-commits** [comment]
Going to content critique today and Yedida will meet with Sharly about this today

**Comment by smcmurtry** [comment]
- @YedidaZalik to incorporate some feedback from @sharlychan-cds 
- will demo today

**Comment by yaelberger-commits** [comment]
Yael reviewed content today and left suggestions, comments and edits

**Comment by YedidaZalik** [comment]
Adding a few items

**Comment by smcmurtry** [comment]
Nisa gave some feedback, Sharly and Yedida meeting today to continue work

**Comment by smcmurtry** [comment]
Got some feedback from Anik, Yedida waiting on feedback from Sharly. Sharly meeting with Victoria this aft, which will lead to more changes which will need review.

**Comment by YedidaZalik** [comment]
Here is the documentation for [our decisions on the TOU](https://docs.google.com/document/d/1lUWdRr_XMdFZhrd-gzkCkw-KZi-kpf9VNl2x1YCBmOQ/edit#heading=h.oi9i3vzi6oq5)

**Comment by yaelberger-commits** [comment]
I'm done my review

**Comment by yaelberger-commits** [comment]
Need to consider adding the daily limits and that users need to keep within their daily limits to the TOU as per Josh's feedback

**Comment by smcmurtry** [comment]
Meeting this aft with Yedida, Sharly, Josh.

**Comment by YedidaZalik** [comment]
Attaching first iteration of new TOU [here](https://docs.google.com/document/d/1N8TwAK87J-m-zo1QIPnfpviYiNC54UhOq9uWARy8P9A/edit#heading=h.9q507khl2vp4)

Currently working on redesign of TOU/policy docs [here](https://docs.google.com/document/d/16uovHkvS9dHhF7_PQf7wb_xs_LY6dPZQaRs8IUDCsTg/edit#heading=h.mwsly988uxl0)

**Comment by YedidaZalik** [comment]
Bringing to content critique this morning

**Comment by sastels** [comment]
brought to content critique, have a few comments to review. Adrianne to also give another read over

**Comment by sastels** [comment]
brought to content critique, have a few comments to review. Adrianne to also give another read over

**Comment by yaelberger-commits** [comment]
In review by @josh-cds

**Comment by sastels** [comment]
reviewed by Josh, now at translation.

**Comment by YedidaZalik** [comment]
Linguistic svcs expects translation done by March 24.

**Comment by yaelberger-commits** [comment]
Up in draft form in GC Articles, needs to be reviewed by Anik
Some open questions for @amazingphilippe

**Comment by YedidaZalik** [comment]
Attaching google doc in
[English](https://docs.google.com/document/d/16uovHkvS9dHhF7_PQf7wb_xs_LY6dPZQaRs8IUDCsTg/edit#heading=h.bae9ctpifd6p)
[French](https://docs.google.com/document/d/1KBdPna08JmOo-MNmL1gEwe-pOSc_KVdv0uhpUiFmpl0/edit#heading=h.lb56d9wlmanz)

**Comment by yaelberger-commits** [comment]
@YedidaZalik since this content is now live in En and FR, can we consider this done? 
Is anything left to QA?

**Comment by YedidaZalik** [comment]
@yaelberger-commits Anik reviewed once it was already in GC Articles and I fixed some things Anik's found. I think Phil was going to look at it a final time and I can't remember if that happened yet or not.

**Comment by yaelberger-commits** [comment]
@amazingphilippe have you had a chance to do a final QA on the ToU pages?
