### ISSUE TITLE
Refactor Lambda code and move it to another Repo

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1066]
## Description

While we were getting Blazer ready, we set up a blazer image and pushed it to a new repo "notification-lambda"
Going forward for any lambda we want for notify, we want to store it in this repo https://github.com/cds-snc/notification-lambdas as an image. We will then have a terraform folder with all the information to setup and run the lambda.

## Acceptance Criteria** (Definition of done) 

- [x] Move heartbeat to notification-lambda
- [x] Setup images for notify/ses_receiving_emails, notify/sns_to_sqs_sms_callbacks, notify/ses_to_sqs_email_callbacks
- [x] 'ses_receiving_emails' lambda is run using the  image
- [x] 'sns_to_sqs_sms_callbacks' lambda is run using the image
- [x] 'ses_to_sqs_email_callbacks' lambda is run using the image
- [x] Cleanup the above-existing lambda in terraform which are not run using the images
- [x] Star `*` permissive permissions to be refined to specific resources instead of allowing all, to follow security best practices.

## QA Steps

- [x] Test lambdas manually in staging and see they return the same behaviour as the existing lambdas

## Additional Info

This is follow up work from the VPC private endpoint task:
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/913

**Comment by smcmurtry** [comment]
- @jzbahrai will merge today to test this out

**Comment by smcmurtry** [comment]
95% done, 3rd lambda still needs to be deployed. Jumana working on this today.

**Comment by smcmurtry** [comment]
Jumana out sick today
