### ISSUE TITLE
`TrialServiceTooManyRequestsError` should not trigger an alarm in Ops genie (bug-bogue)

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1072]
## Describe the bug 

On January 25, 2023, Ops Genie alarms were triggered 2 times within an hour because a Trial service had exceeded their daily limit of 50 notifications/day. Although this did help us find a bug (documented here: https://github.com/cds-snc/notification-planning/issues/1071), a trial service going over their daily limit should not be setting off our alarms. Let's fix that. 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

1. Create a trial service
2. Create an API key
3. Send 100 API requests for one-off emails within 1 minute
4. Observe that Ops Genie pages the on call staff

## Expected behavior

Ops Genie should not page the on call staff.

## Impact

Impact on Notify team: 
This impacts whoever is on call for Notify because our highest severity alarm is getting triggered when nothing is wrong.

## Additional context

We could solve this either by:
1. [Modifying the alarm in Cloudwatch](https://github.com/cds-snc/notification-terraform/blob/main/aws/eks/cloudwatch_log.tf#L25)

Or 
2. Modifying notification-api to not raise this error

**Comment by andrewleith** [comment]
- PR up for review, already reviewed!

**Comment by smcmurtry** [comment]
@andrewleith will QA this morning

**Comment by andrewleith** [comment]
Looks good - I can see these messages written to the logs as info messages instead of errors, so opsgenie will no longer be triggered in this case.
