### ISSUE TITLE
Dev Investigation: Look at borrowing new Gov UK Notify code to implement their Improved email branding

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1073]
According to their [Roadmap](https://www.notifications.service.gov.uk/features/roadmap#things-we-have-done), Gov UK has implemented:

> Improved email branding
> When a service team needs to update their email branding, they can now:
> - choose new branding from a set of existing options
> - preview their branding on the Notify website

This could really benefit us. Let's explore borrowing their code for this!
## Links
Forms ideas behind this: forms to see where they are in regards to branding (see if we can link this document here) https://docs.google.com/document/d/1Uu2Zuo5rckBp8xCDFU5flICcF7gdWzbTwDbdgOqUa-k/edit 

## Timeboxed: 
2/3 days

## Acceptance Criteria:
- [x]  Browse through the code to understand how the Brits implemented this and write a document/ or put the info in this ticket.

**Comment by adriannelee** [comment]
Similar to this one! https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/463

**Comment by smcmurtry** [comment]
Started a google doc here: https://docs.google.com/document/d/1t_gOOGZrNLS0smIc1tkc_2kvPYDkipzG5VIPiJculnw/edit

**Comment by yaelberger-commits** [comment]
Yael has set up a meeting with the Forms team to discuss the policy considerations

**Comment by smcmurtry** [comment]
I was able to get some screen recordings of the new branding flows in UK Notify. I added links to the google doc.

**Comment by smcmurtry** [comment]
I have "finished" the google doc. It's ready for review by others on the team.
