### ISSUE TITLE
Test API key sends cause a celery error when a service is over daily limit (bug-bogue)

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1074]
## Describe the bug 

If a service is over their daily limit, API calls using a Test API key will be successful but cause an error in celery.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

Steps to reproduce the behaviour:

1. Set your service's daily limit to 5 notifications/day
2. Send 5 emails using a normal API key or CSV send through admin
3. Create a Test API key
4. Try sending a new email using the Test API key
5. Observe that the API response is 201 but there is an uncaught error in celery: either `app.v2.errors.LiveServiceTooManyRequestsError` or `app.v2.errors.TrialServiceTooManyRequestsError`

## Expected behaviour

Sending with a Test API key should not cause an error in celery, even if the service is over their daily limit.
 
## Impact

Impact on Notify users: This can cause messages sent with a Test key to have a bad status.

Impact on Notify Team: This can cause alarms that we need to investigate

**Comment by andrewleith** [comment]
- PRs have been reviewed

**Comment by smcmurtry** [comment]
@sastels will QA this morning

**Comment by sastels** [comment]
tested on prod, looks good, no celery errors now.
