### ISSUE TITLE
Align policy docs with updated TOU (terms of use)

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1080]
As a user, I need to be able to easily understand the difference between policy docs so that I do not duplicate my reading and can easily find the information I need.
As a user, I need policy docs that do not duplicate information unless it is appropriate to do so, in order to reduce my cognitive load.

WHY are we building?
TOU is being updated to meet current needs. The other policy docs need to align with this new TOU so that we have a coherent whole.
WHAT are we building?
A suite of policy docs that are aligned and complement each other.
VALUE created by our solution
Our suite of policy docs are accessible and helpful to users.

## Acceptance Criteria** (Definition of done) 

Given a user needs to understand the rules that apply in their use of Notify, when they read one of our policy docs, they easily understand if they also need to look at another of our policy docs, and they can easily access that doc.

- [x] Review SLA for discrepancies and overlap with new TOU
- [x] Update SLA to align with new TOU
- [x] Review Privacy notice for discrepancies and overlap with new TOU
- [x] Update Privacy notice to align with new TOU
- [x] Review Security notice for discrepancies and overlap with new TOU
- [x] Update Security notice to align with new TOU
- [x] Review SLOs for discrepancies and overlap with new TOU. Discrepancies/overlap less likely in SLO but we should still check.
- [x] Update SLOs to align with new TOU if necessary

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1080?planning-poker) with Zenhub @YedidaZalik @sharlychan-cds

**Comment by andrewleith** [comment]
- @YedidaZalik heads-down on this; cleaning up other docs in relation to TOU

**Comment by YedidaZalik** [comment]
Almost done docs are [here](https://docs.google.com/document/d/16uovHkvS9dHhF7_PQf7wb_xs_LY6dPZQaRs8IUDCsTg/edit#heading=h.x15imv5gogbr)

**Comment by sastels** [comment]
progressing

**Comment by yaelberger-commits** [comment]
In review by @josh-cds

**Comment by sastels** [comment]
Josh has reviewed, parts are being translated.

**Comment by YedidaZalik** [comment]
Linguistic svcs expects translation done for March 24.

**Comment by yaelberger-commits** [comment]
Draft up in GC Articles, some open questions for @amazingphilippe, then Anik will do a review
