### ISSUE TITLE
CRM - Notify Policy Discussion

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#1082]
Discuss with policy advisor and strategic engagement team about the CRM and the kinds of data they may want to collect

**Comment by sharlychan-cds** [comment]
Had discussion February 9, 2023. Strategic engagement team to discuss further in their own team re: data, privacy, retention. Some notes [here](https://docs.google.com/spreadsheets/d/1tp8G0o4aQ5G7usFgj7IPPmDciVvPQyany9Dj5w6XzaQ/edit#gid=0). Notify will incorporate CRM language when it's ready from their side.

**Comment by yaelberger-commits** [comment]
@sharlychan-cds I think we can move this to done now
