### ISSUE TITLE
Look in notification-api codebase for hard-coded API keys

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1083]
Hard-coding the API key type recently caused this bug: https://github.com/cds-snc/notification-planning/issues/1074

We should look in the API codebase to see if there are any more cases like this that could cause bugs in the future.

- [ ] Cmd F in Notification API for key type

**Comment by jzbahrai** [comment]
I went through this code in notification-api through the best of my ability and couldn't find any API keys that are hardcoded.
