### ISSUE TITLE
Trying to create an API key with a name over 255 characters causes a 500 error [bug-bogue]

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1097]
## Describe the bug 

Trying to create an API key with a name over 255 characters causes a 500 error. We don't have any form validation rules to prevent this.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

1. Go to "API Integration" in Admin
2. Click on 'Create an API Key'
3. Try to create a key with a name that is 260 characters long 
4. The next page will be an "Internal server error"

## Expected behavior

The form should prevent you from submitting a name that is too long.

## Impact

This causes alarms on the Notify team and could be confusing to users.

## Additional context

We discovered this because of an alarm in #notification-ops.

**Comment by smcmurtry** [comment]
Steve A will QA

**Comment by sastels** [comment]
Tested in prod. Names that are too long are truncated (and a key with the truncated name created)
