### ISSUE TITLE
Validating our assumptions about the Privacy Analysis (PIA lite)

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#1103]
Validating our assumptions about the PIA-lite with Federal clients. [Airtable](https://airtable.com/appWwAmHwDLtpIyko/tblIhGi3iDrEc19tC/viwxBRjGHje7Ctnoq/recVUFe1kqqAnweG8?blocks=hide)

- We don't need a full PIA but our clients ask for one. It's also good practice to have one
- Program officer and privacy officers are the main audience for our privacy analysis
- Is the privacy analysis to have for a 'checkbox'? (like do we have ATO) Or do they actually read the analysis?
- What other things should we add to the privacy analysis (more technical? what do clients want to see?)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1103?planning-poker) with Zenhub @adriannelee @mtoutloff
