### ISSUE TITLE
Give guidance to email Senders about bounce rate

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1109]
## Give guidance to email Senders about bounce rate

As a Notify email Sender, I need to be able to understand what a bounce rate is, what affects it, and how I can keep it low.

WHY are we building?
Allows email Senders to educate themselves and get familiar with bounce rate so they can maintain a healthy email distribution list _before_ we suspend a service, gets them used to the idea and have bounce rate be socialized before consequences come in place with warning and suspended emails and user flows.

WHAT are we building?

- A new guidance page to explain:
    - what a bounce rate is
    - how to find hard bounces in Notify
    - tips to keep bounce rates low
- Where in admin will we link to the bounce rate guidance. Links, help cards, new pages. 

VALUE created by our solution
Daily and monthly average bounce rate ↓ 20% over 4 months
Daily bounce rate/service ↓ 20% over 4 months
20% ↓ in ratio of failed emails to successful emails over 4 months and AWS cost savings
1.5x ↑ in maximum daily email limit 

## Acceptance Criteria
Given an user creates a service with an email template, when they create a service and create an email template, then they discover guidance and content to help them achieve a low bounce rate.

- Guidance is presented when a user creates an email template (scoped out of release 1.0)
- [x] Guidance/help can be accessed from the service dashboard (from the new Problem addresses page)
- [x] Guidance for bounce rate can also be found in the "Guidance" section of the public website
- Guidance is referenced or linked in other relevant policy documents (TOU, SLA) (scoped out of release 1.0)
- [x] Guidance content and content on Message delivery status page are aligned
- [x] Guidance landing page is updated to include a path to new guidance page. 
- [x] Images and alt text are created or updated

Publish checklist

- [ ] Bounce rate feature is released in production
- [x] Guidance and supporting changes in other guidance pages are translated to FR
- [x] new guidance pages entered or updated on GC Articles (no need to archive)
- [x] give a heads up to the app-team channel once ready to publish
- [x] Clear the cache on staging, clear cloudfront cache in GCA as needed
- [x] Post new staging pages in Slack for last minute reviews. Time sensitive, production might or might not update. (Its a big mystery box)

QA steps: 
- [x] check language toggle twice, from each language to the other
- [x] Scan for a11y and fix any found issues
- [ ] run the cypress GCA tests

* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## Source documents
- [New guidance in English](https://docs.google.com/document/d/1o78rrx-x977yNypqIhagWUnihkoqVG1PtW2ZQ0P6Smo/edit#)
- [Nouveaux guides en français](https://docs.google.com/document/d/1gVkCTGcWZPNg5RGYPxkV_KcL5Hg6gyPv_xA0dR6kE5U/edit#)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1109?planning-poker) with Zenhub @YedidaZalik @adriannelee

**Comment by YedidaZalik** [comment]
Will work on guidance here to transfer to figma later: https://docs.google.com/document/d/1o78rrx-x977yNypqIhagWUnihkoqVG1PtW2ZQ0P6Smo/edit

**Comment by YedidaZalik** [comment]
Added more content to new guidance page about lists of problem emails, with comments for @adriannelee to review.

Currently working on update to message delivery status page to align with new bounce rate content. Had initially thought these changes would be minor, but finding that there's a lot involved in that work. Hope to finish that page today, take to content critique tomorrow, implement critique feedback and send to Adrianne for review tomorrow afternoon.

**Comment by YedidaZalik** [comment]
Taking new message delivery status page to content critique this morning

**Comment by YedidaZalik** [comment]
Notes on Message delivery status page from today's content critique

Explain sending and delivered in a visual
Interim status between sending and delivery so mention multiple actors
Users feel they’ve sent the message - break down multi steps
Difference between sending and sent - maybe sending isn’t the right word
Loading sending sent delivered
Sending status
Sending, message delivery and failure
Mail/post - in box but has to get picked up - in transit
https://www.canadapost-postescanada.ca/cpc/en/support/receiving/tracking/tracking-statuses.page

Delivery and Failure

Where are they coming from ?
Check with other link is
Could it be on dashboard?

Could presenting status with icon or visually- check box or x

Framing similarly to how experience

Move dashboard down so the explanation of what terms mean comes first

**Comment by YedidaZalik** [comment]
Jumana says think about it like Gmail-  when click sent button, it goes to outbox - not sent yet
In the sending process - we don’t know when to tell user - sending, waiting for delivery receipt, and explain what delivery receipts

**Comment by YedidaZalik** [comment]
Translation done for Guidance and Msg Delivery status pages but after conferring with Marie-Sophie, they will return it next week along with the Figma translation in order to ensure French content is consistent across Guidance/Msg Delivery Status pages and Figma screens.

**Comment by YedidaZalik** [comment]
Phil worked on AC which is mostly the GC Articles work for this new page and Phil added AC with checklist and source docs
Check if can have ready for release tag and should be moved into QA
To be discussed during today's refinement

**Comment by andrewleith** [comment]
@amazingphilippe, when these are published, I can run the cypress GCA tests that will scan them using AXE if you want, just let me know! (I just updated the test suite to add the 2 new routes).

**Comment by yaelberger-commits** [comment]
Consider unlinking in some places while we A/B test
