### ISSUE TITLE
Re-evaluate need for PT data safeguards

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#1123]
Now that we have the proper authorities (FAA amendments and OIC), we should re-evaluate whether we need to put special safeguards for PTs

Why: conducting audits for "personalized variables" takes too long and the benefits don't outweigh the risks (not useful because of data retention)

- Melissa to write briefing note with context
- Discuss with Product policy, Sharly on CORE and Nisa (org wide question of whether PTs should be treated differently)
- Do we need to communicate with existing users telling them that we're stopping the extra safeguards
- Fact: we continue to offer these to clients in general (it's in our security statement)

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1123?planning-poker) with Zenhub @mtoutloff

**Comment by jprince-cds** [comment]
Recent example: [Freshdesk ticket 14874](https://cds-snc.freshdesk.com/a/tickets/14874) Provincial client wanted to download a report but it was past the 3 day retention, but still within 7 days.

**Comment by mtoutloff** [comment]
Prepared a preliminary analysis on this issue so a decision can be made on whether to proceed with this. I will flag this at the next PTM Touchpoint on May 4, but am putting a pin in this for now as Policy has been asked to prepare a broader PTM scoping analysis.

**Comment by yaelberger-commits** [comment]
We will now close this card as we move ahead with policies for PTs
