### ISSUE TITLE
Crashing Celery workers and causing notifications delay (4h+)

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#1124]
## Description

Notify's workers are crashing and potentially delaying notifications by 4+ hours when that happens.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

SEV-2 Major, as we are constantly delaying notifications (of different priorities, including high priority) by many hours (4h+).

## To Reproduce

1. Load test GCNotify by sending many notifications containing multiple file attachments of a certain size (1M, up to 6M total) all at once.

## Expected behavior

Workers do not crash on load of notifications with file attachments.

## Impact

Loss of trust in Notify stability and potential breach of our SLO if we delay too many notifications.

Impact on Notify users: Notifications delayed by 4h+

Impact on Recipients: Notifications delayed by 4h+, with potential key information not arriving on time.

Impact on Notify team: More alerts noise in the ops channel.

## Additional context

We strongly suspect that file attachments are causing memory errors due to the kubernetes pods hosting the Celery workers being at full capacity.

This isn't our first OOM battle
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/591

Some analysis [here](https://docs.google.com/spreadsheets/d/1Z7H1hsYHgHHMG-KGGsWzuvHUujSHpv52uQBI1r6qGy8/edit#gid=818252842).

https://cds-snc.freshdesk.com/a/tickets/14776

if we end up being able to increase the number of file attachments in a notifications we should let the user in that ticket know.

**Comment by sastels** [comment]
@jimleroyer Can we consider this done now that we fixed the OOM issue?

**Comment by jimleroyer** [comment]
@sastels I think so yes.

**Comment by jimleroyer** [comment]
I verified in production that the celery crashes with SIGKILL 9 don't happen anymore and the Kubernetes fix by Ben worked out (to scale the pods based on CPU):
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/9a6299de-c0cd-4bce-a263-fb4b3c48a992)
