### ISSUE TITLE
Remove sms parts feature flags

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1130]
Remove the feature flags created with the sms work now that it released.  

We will need to determine if one or both should be removed:
- `FF_SPIKE_SMS_DAILY_LIMIT`
- `FF_SMS_PARTS_UI`

Repos containing the flags:
- notification-admin
- notification-api
- notification-manifests

**Comment by smcmurtry** [comment]
Jumana - currently in progress.

**Comment by yaelberger-commits** [comment]
Jumana put up a PR, will get reviewed and merged in
