### ISSUE TITLE
Dev task: Add validation for Name fields in the frontend

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1134]
## Add validation for template fields in the frontend

When a Sender creates a template in GC Notify, the name of the template has a character limit of 255.

We need to validate and throw an error around name of a template when a Sender creates the template so that they do not create and save any templates that will fail to send because this fields is too long. 

We got a freshdesk ticket here:https://cds-snc.freshdesk.com/a/tickets/14862

Acceptance Criteria:
- [x] When a Sender creates a template with the Name field longer than 255 characters, they see a validation error when they try to save the template 
- [x] When a Sender creates a template with the Name field longer than 255 characters, an error message tells them that the name of their template is too long, needs to be less than 256 characters. 
- [x] The Sender understands that they will need to create a template name less than 256 characters to be able to save their template
- [x] The error message is available in EN in the EN UI an in FR in the FR UI (Contact @YedidaZalik for any content requirement, tell if there are no changes as well please)
- [x] A Sender cannot save/use a template to send notifications if the name field is longer than 255 characters

**Current State:**
When a user creates a template
... And the name of the template is more than 255 characters
... The user is able to save the template
... When the user goes to send notifications using that template, they get a validation error because the name field is too long. 

**Expected behaviour:**
- A user receives a validation error when they try to _save_ their template if the name field is longer than 255 characters, and they know that they need to shorten the name of the template before they can save. 
- The user never gets to the part of the flow where they can send notifications using a template with a template that has a name longer than 255 characters.

**Comment by smcmurtry** [comment]
Will - put up some draft PRs for this yesterday.

**Comment by whabanks** [comment]
Added French translation, today will finish up writing tests and move draft PR's open and ready for review.

**Comment by whabanks** [comment]
Wrapped up code implementation and tests today. Utils needs a version bump for the API and Admin CI checks to pass then API and Admin PRs will be ready for review.

**Comment by whabanks** [comment]
This work is in staging and ready for QA!

**Comment by yaelberger-commits** [comment]
I can QA this one

**Comment by yaelberger-commits** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUltIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5f5bf2d2ac2641d6110744ec59a13d1e6c481020/Screenshot%202023-08-22%20at%208.19.39%20AM.png)

**Comment by yaelberger-commits** [comment]
QA in Staging now done @whabanks
