### ISSUE TITLE
Support the CRM team with importing existing Notify Services

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1136]
Our "download Trial Service report" feature in platform admin is currently broken (card here: https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1137). So we need to help get a current list of Notify's trial services to the CRM team so they can import it into Salesforce.

**Comment by yaelberger-commits** [comment]
Leaving in progress to wait and see if CRM folks have what they need

**Comment by smcmurtry** [comment]
Provided the CRM team with an export of Trial Services last week, they have gone through the data and are now ready to upload to Salesforce.

**Comment by smcmurtry** [comment]
Provided the CRM team with an export of Trial Services last week, they have gone through the data and are now ready to upload to Salesforce.
