### ISSUE TITLE
Daily fragment limit should not be higher than Daily notification limit

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1141]
## Daily fragment limit should not be higher than Daily notification limit 

If we increase a service's daily SMS fragment limit, we should not be able to increase it more than that service's current daily notification limit because it causes error messages if we do and they try to send more SMS fragments than they have daily notification capacity to send. 

https://cds-snc.freshdesk.com/a/tickets/14886

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

(SEV-2 Major) 

## To Reproduce

1. Go to a service
2. Make the daily SMS fragment limit more than the daily notification limit
3. try to send all SMS daily fragments available to that service

## Expected behavior

Admin sees an error if they try to increase the daily SMS fragment limit above the daily notification limit for a service

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: Users see an error message if they try to send all their SMS fragment capacity when their daily SMS fragment limit is higher than their daily notification limit. At least one user was confused and created a support ticket. Some of their SMS messages did not get sent

Impact on Recipients: None

Impact on Notify team: Time to respond to support ticket

## Screenshots

![I-UbqOqG1nUsgLChBpOJ4FB4OT8nrJWCgw.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/17045d2a-b392-4197-90be-5bae90e4fdcc)

## Additional context

Eventually we want to get rid of the daily notification limit and just have a daily SMS limit and a daily Email limit, so this problem would no longer occur, but until then we run the risk of this issue coming up again without a manual check or an automated validation step when we increase/decrease daily limits.

**Comment by adriannelee** [comment]
For context, we're looking to work on SMS V2 in April. Would it be worthwhile to work on this bug?

**Comment by andrewleith** [comment]
@yaelberger-commits to QA

**Comment by yaelberger-commits** [comment]
QA'd in Prod in both EN and FR and can verify for both Trial and Live services
- [ ] won't allow me to make SMS daily limit higher than total daily limit
- [ ] error message is correct

QA'd in Staging in both EN and FR and can verify for both Trial and Live services
- [ ] won't allow me to make SMS daily limit higher than total daily limit
- [ ] error message is correct

**Comment by yaelberger-commits** [comment]
I think this fixed the bug for services we have yet to change the daily limit for, but if a service had a daily limit before this bug fix, it remains the way it was
