### ISSUE TITLE
Inconsistent padding on "Request to go live" box on Settings page [bug-bogue]

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1145]
## Describe the bug 

For the "request to go live" button on the settings page, there are a number of issues:
- the vertical padding is different from the horizontal padding
- the button becomes very close to the nearby text for small screen widths
- after the request is submitted, the vertical padding in the box change and the top no longer matches the bottom padding

Request to go live:
Vertical padding is different from the horizontal padding
![Screen Shot 2023-03-30 at 10.52.07 AM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/79ce4b18-99ce-4567-9f98-cdc3a29e4b50)

Button very close to the nearby text for certain screen widths:
![Screen Shot 2023-03-30 at 10.54.03 AM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/27dc02e6-2740-4168-ac49-091509cb0803)

Crowded
![Screen Shot 2023-03-30 at 10.54.40 AM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/52b5070a-4dfe-464c-b4fc-d22bfcc18a98)

Request submitted:
Top no longer matches the bottom padding
![Screen Shot 2023-03-30 at 10.59.06 AM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/fff4c6c1-a61b-4e73-b655-fd4c0881ca47)

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-4 Low

## To Reproduce

For a trial service visit the settings page. Observe the box. Submit a go live request and observe the settings page again.

## Expected behavior

More consistent styling/padding.

## Impact

Impact on Notify users: Looks bad

**Comment by andrewleith** [comment]
The vertical padding differs from the horizontal padding because the vertical is depending on the heading element to provide it while the horizontal comes from the container.

**Comment by andrewleith** [comment]
Merged!

**Comment by YedidaZalik** [comment]
has been reviewed, qa'd, merged. move to done.
