### ISSUE TITLE
Notification labels in downloadable report differ from those shown in ADMIN

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1147]
## Describe the bug 

Downloadable notification reports use different logic to label notifications than the UI does.

- Downloadable notification reports labelling:
   - https://github.com/cds-snc/notification-api/blob/main/app/models.py#L1759
- UI notification labelling:
   - https://github.com/cds-snc/notification-admin/blob/main/app/__init__.py#L425

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation
SEV-4 Low

## To Reproduce

1. Go to the **service dashboard**
2. Click on the **emails sent widget**
3. Note the failed notification statuses in the UI
4. Click **Download this report**
5. Note that the failed notification statuses differ from those shown in the UI

## Expected behavior

All labels should be the same

**Comment by jzbahrai** [comment]
this is done!

**Comment by jzbahrai** [comment]
*when we switch on ff_bounce_rate in the API we will see this flow through.
