### ISSUE TITLE
Update email formatting guide to show example of numbered list

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1150]
## Update email formatting guide to show example of numbered list

Related freshdesk ticket: https://cds-snc.freshdesk.com/a/tickets/14908

As a client, I need to be able to know available email formatting so that I can create structured emails that are easy to read. 

WHY are we building?
The email formatting guidance doesn't show everything that is possible. The above ticket mentions nested numbered lists. But we also don't mention single level numbered lists at all. 
WHAT are we building?
- Exact knowledge of what email formatting exists in GC Notify, and how to use formatting
- Extract what we think is relevant and most useful, and update guidance
VALUE created by our solution
- Better team knowledge of the product
- More visibility for clients, less support tickets
- Find bugs

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)
- [ ] Some formatting tricks or hacks don't actually generate accessible html. We should make this clear, and discourage using the most harmful ones. 

* A11y
* Bilingualism
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by amazingphilippe** [comment]
Nested numbered lists have been added to the guides for a while now. Closing
