### ISSUE TITLE
Self Serve Branding: Give Senders logo options to choose from, if they've already been pre-approved

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1157]
## Description

As a Sender who's created a new service and is requesting to go live, I need to be able to choose from a list so that I don't have to send in a branding request and save time. 

As a Sender wanting to change the logo of a service, I need to be able to choose from a list so that I don't have to send in a branding request and save time. 

WHY are we building?
- We manually process logo requests

WHAT are we building?
- A new question at in the 'go live' flow that provides a list of pre-existing logos to choose from limited by your organization, in addition to the generic GC FIP logo
- Navigate to ☝️ in the settings if they want to change it later

VALUE created by our solution
- Support team time
- Reduced time needed from clients to go live

## Documents
- [Miro board](https://miro.com/app/board/uXjVNqNAmeE=/)

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

Release Checklist doc with Acceptance Criteria https://docs.google.com/document/d/1ySZbaazdSUh4H9UxvJfqjEiHX8yyBq-9paCXz2iSoZM/edit

- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [x] Can misuse of this feature cause harm? If yes, create an alert
- [x] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [x] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1157?planning-poker) with Zenhub @amazingphilippe @andrewleith @yaelberger-commits

**Comment by amazingphilippe** [comment]
- Did an inventory of the logos we currently have. 
- Reviewed Steve's investigation
- Drew a map of screens to build:
<img width="725" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmQ1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--839766787d926f0ca866e2951658e581b51b47e2/image.png" alt="image.png" />

**Comment by amazingphilippe** [comment]
Steve M's discovery work: https://docs.google.com/document/d/1t_gOOGZrNLS0smIc1tkc_2kvPYDkipzG5VIPiJculnw/edit#heading=h.9fwuexln0gg

**Comment by amazingphilippe** [comment]
Andrew and Phil worked on the different screens and components to figure out some of the visual and UI decisions to make.

**Comment by YedidaZalik** [comment]
Marie-Sophie and Yedida did content work [in this doc](https://docs.google.com/document/d/1Qe9bFhibB1k6byVN31asebzMDVNHkioD_3uqT-SMXn0/edit)

**Comment by YedidaZalik** [comment]
Phil, Marie-Sophie and Yedida met to update content and review EN content for the 2 new screens
Marie-Sophie to localize the two new screens

**Comment by YedidaZalik** [comment]
Updated new screen content yesterday for Marie-Sophie

**Comment by amazingphilippe** [comment]
Started a screen by screen review of design. Will share during dev-design review. [Figma link](https://www.figma.com/file/a1TQZWGPRijQkAfa7DHWXF/Service-branding-%7C-Image-de-service?type=design&node-id=261-1263&mode=design&t=5mJqe5M0M02MvB7k-4)

**Comment by mtoutloff** [comment]
Design has the content in Figma and there have been some comments from devs, and dev work being done on dev side

**Comment by mtoutloff** [comment]
Andrew going back to add missing tests and will sync with Phil on UI test, and waiting on translation

**Comment by mtoutloff** [comment]
Andrew put up a large PR, will try and start reviewing today
Will running cyprus tests and at a good stage to start merging either today or tomorrow 
Meeting to go over release checklist

**Comment by yaelberger-commits** [comment]
Release Checklist meeting today went well ✅

**Comment by mtoutloff** [comment]
About to be released to production behind feature flag

**Comment by mtoutloff** [comment]
Probably be deployed today
