### ISSUE TITLE
Estimate how large our Redis Cluster should be

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1159]
## Description

As a user, I can see that the redis production cluster is 1GB, has 500MB freeable memory and has a memory usage of 4%. You can follow the discussion here: https://gcdigital.slack.com/archives/CV38DBNVA/p1681499257037859
We need to estimate how large the cluster should be given us going live with bounce rate.

1. Estimate how many services are being used during a peak hour
2. Add in a hard_bounce_service_id sorted set with atleast 500/1000 keys.
3. Add in total_notifications_service_id sorted set with atleast 1000/2000 keys
4. Do this for multiple services

## Acceptance Criteria
- [ ]  Have a way to estimate at peak what our memory usage in redis will look like. This can be incorporated into a performance test for bounce rate in the future.

## QA Steps
- [ ] Tested in staging to estimate what we need to increase the size of the redis cluster

**Comment by jzbahrai** [comment]
This might be helpful link in figuring out how to estimate the size of the cluster: https://stackoverflow.com/questions/34174889/how-to-calculate-redis-memory-used-percentage-on-elasticache#:~:text=FreeableMemory%20%3A%20The%20amount%20of%20free,the%20dataset%2C%20buffers%2C%20etc

**Comment by YedidaZalik** [comment]
Steve made good progress yesterday and has good number for current implementation so will write up and post today.

**Comment by smcmurtry** [comment]
Here is a PR with the Python Notebook I used to make the estimation: https://github.com/cds-snc/notification-attic/pull/31
