### ISSUE TITLE
Align TOU with API content

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1161]
As a developer, I need to be aware of my obligations when using Notify, but as a non-developer, I need a TOU that is easy to read. 

WHY are we building?
To elaborate on key responsibilities of developers so that the TOU can link to that detail in the API documentation.
WHAT are we building?
Some additional content in the API documentation.
VALUE created by our solution
TOU meets needs of both developers and non-developers.

## Acceptance Criteria
Given developers need to be aware of their responsibilities when using GC Notify, the TOU links to relevant content in the API documentation. 

- [x] New content (previously approved by PM and developers) is translated in French
- [x] English and French is reviewed by bilingual content designer Anik
- [ ] New content is entered in API documentation
- [ ]  TOU links to this documentation at relevant point in both languages.

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by YedidaZalik** [comment]
This will be a new section in the API documentation, under the heading "Send a message" but before the sub-heading "Send an email". 
We can give this the subheading "Check status, repair and resend messages".
ENGLISH

**Check status, repair and resend messages**

If your HTTP requests receive a:
(a)  4** class error for an invalid request.  
(b)  5** class error for server failure.
GC Notify treats these errors as unprocessed requests. Requests must receive 2** class success in order for GC Notify to retry until sending is done.
Restrict requests to GC Notify’s API to 1000 per minute. You’ll get a 429 error if you exceed this number.

FRENCH
**Vérifiez l’état du message, corrigez et envoyez à nouveau**

Si vous obtenez pour vos requêtes HTTP :
(a) une erreur de classe 4** correspondant à une requête invalide; ou
(b) une erreur de classe 5** correspondant à un échec du serveur,
Notification GC traite ces erreurs comme des demandes non traitées. Pour que Notification GC puisse réessayer jusqu’à ce que l’envoi soit effectué, les demandes doivent obtenir un succès de classe 2**.
Limitez les requêtes à l’API de Notification GC à 1 000 par minute. Si vous dépassez ce nombre, vous obtiendrez une erreur 429.

**Comment by YedidaZalik** [comment]
To stay in Sprint backlog and can be picked up by whoever has time. Jumana will link to info on how to do this.
If straightforward, Yael can tackle to make PR for change so it doesn't block TOU. 
@jzbahrai

**Comment by jzbahrai** [comment]
I think this was already done. there was another ticket for it. @YedidaZalik can you check: https://documentation.notification.canada.ca/en/

**Comment by YedidaZalik** [comment]
Yes, you're right @jzbahrai 
I've reviewed and I see 2 little items for fixing in both EN and FR
(1) there's a backslash " \ "that should not be there. It's after the word failure in the second bullet.
(2) the subheading "Check status, repair and resend messages" should be an H2 like 
"Sending an email" and appear ahead of "Sending an email" in the side bar (apologies, I should have marked it as H2 in the google doc).

**Comment by YedidaZalik** [comment]
Andrew reviewed. It was merged. So needs to be released.

**Comment by andrewleith** [comment]
This has been released and I just QA'd it in PROD; moving to done.
