### ISSUE TITLE
language toggle not working on Features page

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1162]
## Describe the bug 

The language toggle does not work on
https://notification.canada.ca/features
nor on
https://notification.canada.ca/fonctionnalites

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

1. Go to https://notification.canada.ca/fonctionnalites
2. Click on "English"
3. Nothing happens.

## Expected behavior

Get the page in the other language

## Impact

users can't switch language without going to another page first.

## Additional context

Other pages I tested (including all the other GCA pages I think?) worked.

**Comment by andrewleith** [comment]
Interesting - I would guess that the translation page set for this page in GCA is set to one that no longer exists, so whoever looks into this should start there!

**Comment by andrewleith** [comment]
Interesting - I would guess that the translation page set for this page in GCA is set to one that no longer exists, so whoever looks into this should start there!
