### ISSUE TITLE
Content for password reset message triggered by secrets rotation "You need to create a new password" page

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1163]
As a user, I need to be able to change my password so that I can use Notify.

WHY are we building?
Rotation of secrets will trigger users to change their password.

WHAT are we building?
Content for password reset message

VALUE created by our solution
Password reset message that is consistent with style and phrasing in other parts of Notify, leading to a more seamless UX

## Source documents
[Figma screens](https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?type=design&node-id=701-121)

## Acceptance Criteria
Given that we need to rotate secrets, when the password reset message arrives, the user reads it and easily knows what to do

- [x] Users understand why we need them to create a new password when they next sign in
- [x] Users know how to create a strong password that will be accepted
- [x] A password that does not meet the criteria gets an error message with a reason why it was not accepted
- [x] Consider including content in the UI that if you don't receive the email/confirmation to contact us (suppression list)
- [x] Revision of current password reset message to align with GC Notify's new flow without email notification
- [x] Consult with French content designer
- [x] Consult with Policy Advisor @mtoutloff on language
- [x] Translation 
- [x] Review of translation by French content designer
- [x] Give support team a heads up that we will be rotating secrets and forcing a password reset (some folks may get stuck and need help to get signed back in)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Yedida made good progress this week, getting feedback today
Decision to move to a status page

**Comment by yaelberger-commits** [comment]
Content is back from translation

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1163?planning-poker) with Zenhub @YedidaZalik @mtoutloff
