### ISSUE TITLE
 Increase the likelihood that messages are trusted by recipients and not viewed as spam by AWS and downstream carrier

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1170]
## Possible KRs:

Prototype and test 2 stock email templates for services to use
Prototype and test 2 stock SMS templates for services to use 

## Success measurements: 
Decreased % of failed notifications
Decreased % of complaints against our notifications
Usability testing of our new stock templates with end recipients of government notifications to get a sense if they are helpful or cause any unforeseen harm before releasing them

Resources and Research
https://articles.alpha.canada.ca/forms-formulaires/templates/
https://codeforamerica.org/programs/social-safety-net/texting-playbook/
https://codeforamerica.org/news/shoulder-to-shoulder-connecticut/?_hsmi=264391291&_hsenc=p2ANqtz-8BJixjGe8xKsvCyuarkewDpAom82G_dyDmItY6KyGq5_tgjTr9DWljQKk9r9SCytB8Cx09sNPqN3ZV1N4VBY_Ne7lXGw

**Comment by yaelberger-commits** [comment]
**Text best practices from Code for America** 

How to communicate your texts
are legitimate and not spam
Unfortunately, spam text messages have become much more common. Our government agency partners often ask
us how they can ensure that their texts are perceived as legitimate and not a scam. Incorporating a few best
practices can help distinguish your legitimate messages from the spam.
● Personalize the message by including the message recipientʼs first name. We have found this can
increase response by nearly 25%.
● Identify the sender by including the name of the benefits agency. We have found greater success with our
tax benefits outreach when messages come directly from the benefits agency rather than a third party or
outside group.
● When relevant, reference information about the status of their case (e.g., that they recently submitted
an application).
○ While providing confirmation messages for actions such as application submissions or document
uploads may not have a clear impact on outcomes, it can help build trust and prove that the
messages are legitimate.
● Use links that lead to official agency websites.
● Provide phone numbers for agency offices or call centers (either in the message itself or in an
auto-response as discussed in the question above).
● Use a consistent phone number (ideally, a short code) for sending messages so that messages are
received as part of an ongoing, recognizable thread.

**Comment by yaelberger-commits** [comment]
![Screenshot 2023-07-27 at 8.27.41 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/4ea8b3b8-c2f2-46de-bf68-68656cc278a3)

**Comment by jimleroyer** [comment]
[Further thoughts on this topic](https://gcdigital.slack.com/archives/C03FA4DJCCU/p1698765720789999?thread_ts=1697323353.037179&cid=C03FA4DJCCU):

> Because some folks are uncertain of the validity of what GCNotify sends, we could have a user-friendly facing public documentation that explains that what we send is valid and how so, to establish trust with our service. We can explain how to verify if an email was really sent by us for example by saying that if GMail (50% of our recipients) didn't tag is as phishing and the email comes from the notification.canada.ca domain, this is as solid as it gets. We could cover other popular email clients as well. We can briefly mention DMARC and its mechanisms in user friendly terms to explain that the trust foundation comes from crypto signatures that is very hard to replicate by third parties.
>
> It would be handful to send as a default piece of documentation on support then. We could also recommend to get in touch with the service in question, but that might offload some support on our end, as we'd have a solid reply back as a template.
>
> The potential new cards could be: 1- Provide doc explanation to users on how emails from GCNotify can be trusted, 2- Write support template for email trust and link to doc. Potentially, the doc could be associated with the task around the footer as well.
