### ISSUE TITLE
Investigate Celery worker memory consumption

### ISSUE THREAD

**Issue by whabanks** [cds-snc/notification-planning#1172]
## Describe the bug 

Every day at 4:01AM a celery worker (likely running nightly tasks) receives a `SIGKILL` from the OS's oom-killer. This results in warning alarms going of in both `notification-ops` and `notification-staging-ops` channels daily. 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

* This could lead to potential lost notifications as the Celery workers are unexpectedly shutdown in a non-gracious way.
* Our data retention policy is likely not respected anymore as one of the sms cleaning job task cannot complete normally. Hence jobs more than 3 weeks old are currently still in our database at the time of this writing (2023-05-03).

## Expected behavior

Celery tasks run without consuming excessive amounts of memory in their respective pods.

## Additional context
[Initial discussion thread](https://gcdigital.slack.com/archives/CNWA63606/p1682496109553619)
Initial investigation into the pods running Celery indicates that one worker begins consuming a significant amount of memory relative to the other running workers: 

![image.png](https://images.zenhubusercontent.com/6362cf580029e141b402bb65/afe4e586-f90c-4c3b-9d08-f365f34ea0e3)

The pods running celery workers are set to a limit of 1GB of memory. When we tally up the `rss` column we end up with a total usage of ~1.21GB. As the values in the rss column are in 4kB pages: `(sum(rss column) * 4) / 1048576`

This indicates either a memory leak within Celery itself, or a poorly optimized nightly task.

### Tasks that run around 4 AM and may be culprits:
- `remove_sms_email_jobs`
- `remove_transformed_dvla_files`
- `delete-sms-notifications`

#### Task: remove_sms_email_jobs

That task does not seem to run properly for the past month. It is supposed to clean up data retention for SMS jobs but checking the database, we still have task that are more than 3 weeks old in teh database: 
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/ebb4c732-cf48-465d-8837-0cf9e9eb1868)

This table was generated with this SQL query, which fetches approximately the same data that the task should clean:
```
select j.created_at::timestamp::date as day, count(*)
  from jobs j inner join templates t on t.id = j.template_id
 where t.template_type = 'sms'
   and j.created_at < '2023-04-26 00:00:00'
   and j.archived = 'f'
 group by day
 order by day asc
;
```

### Related cards:
#1084 Investigate optimizations nightly tasks so database is less affected 
#1127 Celery Performance tuning

**Comment by yaelberger-commits** [comment]
Jumana made progress, continuing today

**Comment by yaelberger-commits** [comment]
Discuss handoff after today to Notify Core

**Comment by jzbahrai** [comment]
To replicate:

1. You can download staging_db_2.sql from here: https://drive.google.com/drive/u/0/folders/1hZARZrl35Oj42CvpoonvlWkt8fShSbS3
2. Delete everything from your psql in your dev container `drop schema `public` cascade`
3. Input it locally `psql postgres://postgres:chummy@localhost:5432/notification_api < staging_db_2.sql`
4. Add `poetry add memory-profiler`
5. Add `from memory_profiler import profile` on top of your `nightly_tasks.py` file
6. Add `@profile` to the `remove_sms_email_csv_files`
7. Change the config so that the above jobs runs at the correct time
8. Run celery beat worker
9. Run celery using mprof `mprof run celery --app run_celery worker --pidfile /tmp/celery.pid -l INFO -Q "database-tasks,-priority-database-tasks.fifo,-normal-database-tasks,-bulk-database-tasks,job-tasks,notify-internal-tasks,periodic-tasks,priority-tasks,normal-tasks,bulk-tasks,reporting-tasks,research-mode-tasks,retry-tasks,send-sms-tasks,send-email-tasks,service-callbacks,delivery-receipts"`
10. `poetry add matplotlib`
11. `mprof stop`
12. `mprof plot`

**Comment by jzbahrai** [comment]
![memory_profile.png](https://images.zenhubusercontent.com/6149fdc10c14631b6b9c16dc/1c67e86f-eca8-4326-8241-efe65acd5cb9)

This is one of the graphs I got. I am going to try and do some line profiling

**Comment by jzbahrai** [comment]
![Screenshot 2023-05-10 at 5.23.18 PM.png](https://images.zenhubusercontent.com/6149fdc10c14631b6b9c16dc/edad3310-0fd7-4278-889b-d1275d5746b2)

**Comment by jzbahrai** [comment]
![Screenshot 2023-05-10 at 5.23.07 PM.png](https://images.zenhubusercontent.com/6149fdc10c14631b6b9c16dc/d53e553e-c00e-4c8e-8f7a-efc950f010d3)

**Comment by smcmurtry** [comment]
We tried manually expiring the old jobs in the backlog (there were more than 100k on staging) and the 4am celery errors went away on staging! We then did the same thing on prod and the celery errors have stopped there as well.

There are a couple related fixes we need to merge before this can be considered done.

**Comment by amazingphilippe** [comment]
Some PRs in progress to correct how the csv files are getting expired, sooner than after 7 days, should be in line with service setting.

**Comment by jzbahrai** [comment]
This work is done.

**Comment by jzbahrai** [comment]
@andrewleith going to update the data retention (or @yaelberger-commits) will

**Comment by andrewleith** [comment]
@yaelberger-commits did this earlier today! ✅
