### ISSUE TITLE
Clicking twice on problem email filter does not clear filter during a bulk send

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1177]
## Clicking twice on problem email filter does not clear filter during a bulk send 

This bug occurred on the bulk CSV notifications report page (ie url /services/{id}/jobs/{id})
Update: the filter checkbox doesn’t work at all while the send is in progress due to the page automatically refreshing

On the CSV page, the checkbox filter is part of the dynamic content that is continually being updated by the ajax block, so it keeps getting removed and re-inserted into the DOM.  I'll see if I can refactor this a bit.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major

## To Reproduce

1. Perform a bulk send in ADMIN
2. While the system is processing the bulk send, click the problem address filter 
3. The checkbox unchecks it self when the page refreshes

## Expected behavior

- The checkbox should remain checked after its been checked
- The checkbox should remain unchecked after its been unchecked

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team: 

## Screenshots

![image (30).png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/eb1cc8bc-a1e4-4223-b063-5d5f51ba8edb)

**Comment by andrewleith** [comment]
The fix has been reviewed and merged, ready to be QA'd.

**Comment by andrewleith** [comment]
@adriannelee I think this will fix the bug you saw as well (#1181) - would you mind testing this when you have a chance?

**Comment by andrewleith** [comment]
Repro steps updated in the ticket.

@jimleroyer would you be able to QA this as well?
