### ISSUE TITLE
Problem email addresses and emails sent widgets link to same page

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1178]
## Problem email addresses and emails sent widgets link to same page 

Both widgets link to the notifications report page with no filter.

Ideas:
For problem email link: link to notification reports filtered by problem emails, or
Remove link altogether [PR # 1543](https://github.com/cds-snc/notification-admin/pull/1543)

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-1 Critical 

## To Reproduce

1. On the dashboard
2. Notice both links on big number box go to the same page. 

## Expected behavior

The problem address box was not intended to link somewhere. We expect users to go through the dedicated page to understand what problem addresses mean. 

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: Multiple links to the same screen

Impact on Recipients: None

Impact on Notify team: None

## Screenshots

Screenshots in attached PR

**Comment by amazingphilippe** [comment]
PR ready for review and assigned to app dev team

**Comment by andrewleith** [comment]
Reviewed!  Changes look good, UX feels much better like this.

**Comment by yaelberger-commits** [comment]
Works as expected now, the problem address box doesn't link somewhere. We expect users to go through the dedicated page by clicking the link "review problem addresses" to understand what problem addresses mean.

![Screenshot 2023-05-08 at 1.58.29 PM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/ae9eed50-5675-4927-80ce-613b1c9f9e6a)
