### ISSUE TITLE
Dashboard widgets change color based on different rules

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1180]
## Dashboard widgets change color based on different rules 

The left-hand side widget is based on total failure rate, while the right-hand side widget is based on a minimum threshold and THEN the bounce rate thresholds. 

Both could be in a "failure" state, but one is red the other is green. 

Idea: Use a neutral colour for problem email addresses below the minimum threshold volume.

Slack thread: https://gcdigital.slack.com/archives/C04RU1B0YJ1/p1683042507770619

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major 

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team:

**Comment by jzbahrai** [comment]
PR is up, just needs to be reviewed.

**Comment by jzbahrai** [comment]
This has been fixed, reviewed and deployed.
