### ISSUE TITLE
Filter doesn’t remain checked after you click on it

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1181]
## Filter doesn’t remain checked after you click on it 

- Despite the fact that admin appends a hash to the end of the JS url, that the js is being somehow cached, js isn’t getting automatically 

- It is possible this was the same as #1177 above and not a caching issue

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

Slack thread: https://gcdigital.slack.com/archives/C04RU1B0YJ1/p1683040781980889

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team:

**Comment by adriannelee** [comment]
Looks great! (QA'd on staging)
