### ISSUE TITLE
Implement new content on “You need to create a new password” page

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1184]
## Implement new content on “You need to create a new password” page

As a Notify user, I need to be able to see the new content on the "You need to create a new password" page so that I don't have questions or concerns about why I'm being asked to change my password to sign in. 

WHY are we building?
There is new content written for this page that needs to be implemented

WHAT are we building?
DEV implementation of new content in the UI

VALUE created by our solution
Page is updated with appropriate content that's more general so we don't need to rewrite this UI every time we have to force a password reset

## Documentation and Artifacts

Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given a user tries to sign in after the forced password reset, when they select "Sign in", then they land on the "You need to create a new password" page and it has updated, generic content 

- [x] Content appears in correct language when you toggle EN or FR
- [x] When a user selects "Sign in" they are taken to the updated "You need to create a new password" page 
- [x] When a user enters a new password, it must meet the password validation criteria
- [x] If the password does not meet the criteria for a strong password an error message appears telling the user why they need a better password
- [x] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [x] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Content is back from translation

**Comment by YedidaZalik** [comment]
@jzbahrai 
Here is the [EN content](https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?type=design&node-id=923-3279&t=8TFKki4SFEOn2Rse-0) 
 and here is the [FR content ](https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?type=design&node-id=1020-1101&t=e738zmKc6iizqlpd-0)

This shows the whole flow including the GC Articles page and email templates, for which I will update the content

**Comment by jzbahrai** [comment]
This is done but it isn't merged. We are waiting on the slug for incidents and security to be implemented

**Comment by andrewleith** [comment]
- Plan is to get this onto staging today.

**Comment by jzbahrai** [comment]
This is ready to be deployed to staging but is blocked due to a WAF rule change that hasnt been deployed yet. Once that PR is merged, we will merge this PR.

**Comment by andrewleith** [comment]
- Merged, QA'd, deployed, done!
