### ISSUE TITLE
Create new GC Articles page for status updates 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1185]
## Create new GC Articles page for status updates 

As a Notify user, I need to be able to find additional information on why I need to change my Notify password so that I can brief up, relieve any concerns and answer my questions without having to reach out to Notify Support. 

WHY are we building?
We want users to be able to self-serve more information about security issues, incidents, privacy breaches etc. so that we build a more transparent process

WHAT are we building?
A status page that indicated information about incidents, breaches and downtime 

VALUE created by our solution
Users won't have to contact us for more information and we can avoid having to send emails to all users every time we have information to share about an issue, instead we can include a link to more info on a System Status page

## Documentation and Artifacts

Example from Notify UK
https://status.notifications.service.gov.uk/

## Acceptance Criteria
Given A user lands on the "You need to create a new password" page, when they select the link to more information on our system status, then they land on a new GC Articles page with updates and information about these kinds of security issues etc.

- [ ] Most recent information is at the top
- [ ] Content is drafted along with FR content
- [ ] Content is review by Policy Advisor @mtoutloff 
- [ ] Content is approved by PM
- [ ] Growth team is advised and given an opportunity to review before finalized
- [ ] Content is translated 
- [ ] Content is drafted in GC Articles 
- [ ] Slug is created (FR and EN)
- [ ] Content is published **_(add publishing checklist here)_**
- [ ] Status page is linked from Security Statement in EN and FR
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by YedidaZalik** [comment]
@yaelberger-commits is this a duplicate or could we move to in progress?

**Comment by yaelberger-commits** [comment]
This looks like a duplicate of #1186. Can you combine the two together and close the replica please?

**Comment by YedidaZalik** [comment]
I've added any relevant points from this card to #1186. Closing now as it's a duplicate.
