### ISSUE TITLE
Create new GC Articles page for status updates 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1186]
## Create new GC Articles page for status updates 

As a Notify user, I need to be able to find additional information: 
(1) on why I need to change my Notify password so that I can brief up, relieve any concerns and answer my questions without having to reach out to Notify Support. 
(2) when I come across a system error so that I can brief up, relieve any concerns and answer my questions without having to reach out to Notify Support.

WHY are we building?
We want users to be able to self-serve more information about security issues, incidents, privacy breaches etc. so that we build a more transparent process

WHAT are we building?
- A status page that indicated information about incidents, breaches and downtime, system load status (even if it's not an issue)
- A link from the footer
- A template for status updates for this iteration that's good enough for the forced pw reset. 

VALUE created by our solution
Users won't have to contact us for more information and we can avoid having to send emails to all users every time we have information to share about an issue, instead we can include a link to more info on a System Status page

## Documentation and Artifacts

Example from Notify UK
https://status.notifications.service.gov.uk/
Something else from CDS: https://status-statut.cds-snc.ca/history/gc-notify

## Acceptance Criteria
Given A user lands on the "You need to create a new password" page, when they select the link to more information on our system status, then they land on a new GC Articles page with updates and information about these kinds of security issues etc.

- [x]  The status page is good enough to publish the forced pw reset update
- [x]  Page loads within 200 milliseconds
- [x]  The status page uses labels and categories used in the SLO
- [x] Most recent information is at the top
- [x] Content is drafted along with FR content
- [x] Content is review by Policy Advisor @mtoutloff 
- [x] Content is approved by PM
- [x] Growth team is advised and given an opportunity to review before finalized
- [x] Content is translated 
- [x] Content is drafted in GC Articles 
- [x] Slug is created (FR and EN)
- [ ] Content is published **_(add publishing checklist here)_**
- [ ] Status page is linked from Security Statement in EN and FR
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

**Publish checklist**
 [ ]Create a SLUG for the status page
 [ ] Set WAF rules for new status page.
 [ ] Status page translated to FR
 [ ] Status page created on GC Articles (no need to archive)
  [ ]Give a heads up to the app-team channel once ready to publish
 [ ] Clear the cache through GC Notify's admin panel, clear cloudfront cache in GCA as needed
 [ ] Post new staging pages in Slack for last minute reviews. Time sensitive, production might or might not update.

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Some inspiration:
UK Notify status page https://status.notifications.service.gov.uk/history?page=3
Atlassian Status Page https://www.atlassian.com/software/statuspage

**Comment by amazingphilippe** [comment]
All content has been sent to translation. Expecting 2 days turnaround.

**Comment by yaelberger-commits** [comment]
Content is back from translation

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1186?planning-poker) with Zenhub @YedidaZalik

**Comment by andrewleith** [comment]
These pages are now working in staging.
