### ISSUE TITLE
Regularly audit for new templates that should be in priority queue

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1188]
## Regularly audit for new templates that should be in priority queue

We need to set up a regularly occurring process for checking new templates and moving them to the priority queue if they qualify (password resets, 2fA codes, account confirmation etc.) 

As a Notify Sender, I need to be able to send account related notifications within 60 seconds almost all of the time so that recipients can log in, change passwords and confirm receipt in a timely manner. 

Were we going to have an automated process for this? This feels like we can setup a query in blazer and have a report generated for this.

Could be manual or automated. At least weekly, but ideally in real time as new templates get created. 

## Current process

1. Every 2 weeks a Slack reminder goes off
2. Get into Blazer
3. Run the query
4. Look at the new templates since last audit
5. Re-prioritize any templates that should be higher priority and save those template changes
6. Log new priority in a spreadsheet https://docs.google.com/spreadsheets/d/1wAKNqpas9-57YqGJnd3evmvt_QBk8ubfnTlnvLvatqE/edit#gid=79034960

https://cds-snc.freshdesk.com/a/tickets/15019

### Initial timeframe 
The initial check should be done from *Dec 14, 2022 to today*.

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Documentation and Artifacts

Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Generate appropriate log messages so that executions of this feature can be tracked
- [x] Can misuse of this feature cause harm? If yes, create an alert
- [x] Initial audit from Dec.14 to today
- [x] Templates created after Dec 14, 2022
- [x] Templates sent (at least once) using the API
- [x] Template sent (at least once) NOT as bulk
- [x] process in place to audit any new templates created on a weekly basis

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1188?planning-poker) with Zenhub @andrewleith @smcmurtry @whabanks

**Comment by andrewleith** [comment]
Made some progress on a blazer query to get this info:
- http://localhost:1338/queries/85-wip-template-audit

Right now it shows the highest daily send for a template which I thought would be useful.  Upon reflection though, a high count doesn't necessarily mean it should be considered bulk (i.e. if a template is for 2FA but they just have a lot of logins over the day).

Going to think about this a little more.

**Comment by andrewleith** [comment]
I've put the list of templates to audit into [google drive](https://docs.google.com/spreadsheets/d/1ZXrHE5j1BmfOQtcnd84ddGM_AqBlP-pmPGPjPx7fmhQ/edit#gid=2146159957).  I'll setup a meeting with everyone as optional to go through them as a group, shouldn't take more than 20 minutes!

**Comment by andrewleith** [comment]
- Session booked for today to review and assign priority

**Comment by yaelberger-commits** [comment]
Auditing in progress, notified Notify Core to ask them to monitor queues for any slowdowns

**Comment by yaelberger-commits** [comment]
@jimleroyer and @yaelberger-commits will reach out to Recalls about their expectations regarding SLOs

**Comment by andrewleith** [comment]
Working on having blazer automatically send list of templates to be reviewed to slack.

Outstanding issues:
- Need to add new slack webhook secret into terraform and have it passed down to blazer task
- Need to troubleshoot cron jobs - the message gets posted once but then never again

**Comment by andrewleith** [comment]
After some work on this, it seems the blazer+slack integration isn't really what we're looking for so I will stop pursuing this. Instead I'll add a slackbot reminder to have us check the templates every so often.

**Comment by andrewleith** [comment]
Here are the latest templates created since Jun 1, for review: https://docs.google.com/spreadsheets/d/1rzwQFTjnJCuWINQtLZPXopVYBegPZVWqBmJQWGRwJ0k/edit#gid=1530041278

**Comment by yaelberger-commits** [comment]
Templates have been audited from June 1st - July 24th
I will bring this back into the Sprint backlog and I will add it as a reoccurring task

**Comment by smcmurtry** [comment]
Yael went through the list of new templates yesterday, moved to sprint backlog and turned it into a recurring task. This will be a manual task for the timebeing.

**Comment by yaelberger-commits** [comment]
Done for Aug. 8

**Comment by yaelberger-commits** [comment]
Yael picking this up for Sept 5 today

**Comment by adriannelee** [comment]
Done for Sept 18

**Comment by andrewleith** [comment]
- This will be done today

**Comment by yaelberger-commits** [comment]
Completed 2023-11-29 audit

**Comment by adriannelee** [comment]
Completed 2023-12-11 audit
