### ISSUE TITLE
Analyze A11y validation test May 2023

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1190]
- [x] Clean up and move notes to Miro
- [x] 1st round of tagging
- [ ] 2nd round of tagging
- [x] Group tags + summarize
- [x] Generate insights
- [x] Present to team

**Comment by jzbahrai** [comment]
First round of tagging done. Now grouping the tags + wrapping up the analysis

**Comment by yaelberger-commits** [comment]
@adriannelee is this task now complete?
