### ISSUE TITLE
Bounce rate logs aren’t happening frequently enough

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1191]
##Bounce rate logs aren’t happening frequently enough

We don’t see the log for a one-off send via admin. And we only see the log at the start of a bulk send, where I think we should see the bounce rate getting checked before every email in a bulk send, so that we can suspend a service if their bounce rate goes too high in the middle of a large send.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor 

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team:

**Comment by yaelberger-commits** [comment]
Bounce rate check and logging not happening frequently enough (missing from Admin one off and from before each email is sent in a bug job)

**Comment by amazingphilippe** [comment]
@whabanks should this be moved to done?

**Comment by whabanks** [comment]
[QA'd this in staging](https://gcdigital.slack.com/archives/C04RU1B0YJ1/p1683733708035189?thread_ts=1683733702.552149&cid=C04RU1B0YJ1)
