### ISSUE TITLE
No alarm in notification-staging-ops channel for “over 10%” log message

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1192]
## No alarm in notification-staging-ops channel for “over 10%” log message

A clear and concise description of what the bug is. Include which part of Notify is affected (admin, staging, prod, API, utils, etc.)

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team:

**Comment by yaelberger-commits** [comment]
Alarm in Slack not getting triggered correctly (
@whabanks 
 knows more of the details here - I think we may need to update the cloudwatch query from looking at the k8s logs to look at the api lambda logs)

**Comment by jzbahrai** [comment]
This was tested and fixed by @whabanks
