### ISSUE TITLE
Un-filtering the notifications report clears both layers of filters

### ISSUE THREAD

**Issue by whabanks** [cds-snc/notification-planning#1195]
## Un-filtering the notifications report clears both layers of filters

This bug occurs on the jobs report page. When we check, then uncheck the "Only show problem addresses"  filter checkbox the status query parameter is lost, resulting in all filters on the page being lost.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major

## To Reproduce

1. Navigate to the Dashboard of a service and click on "View Reports"
2. Note in the URL we have something akin to:  `/notifications/email?status=failed`
3. Check the problem address box
4. Now we are on `/notifications/email?status=permanent-failure&pe_filter=true`
5. Uncheck the box
6. We lose the status query param
7. Now we are on `/notifications/email?status=`
8. Observe that the filter nav ribbon no longer has a filter selected

## Expected behavior

Any filters outside the sending status should apply on top. Lets call them sub-filters
Sub filters could be available for any main filter, but could have no effect. (There can't be "problem emails" in "sent")
Sub filters should be identified to users and grouped for better discoverability. We already have a search-bar email address sub filter. But it isn't grouped with this filter. The download link is also squeezed in there, but could be placed below filters. 

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: Poor experience with sub filters. Confusion or frustration when tweaking your reports. 

Impact on Recipients: None

Impact on Notify team: Request for technical support if people can't produce the right report. 

## Screenshots

Should this screen be possible? Note the "delivered" filter, and possibility to sub filter by "problem address"
![image.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/6303f802-ab63-41f7-914d-7e4b19baec4f)

No main filter is selected
![image.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/fce35866-530c-4256-bc9d-c4a305651e42)

## Supporting documentation

[Figma designs for possible solutions](https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?type=design&node-id=1014-12556&t=d8DrnLxMWcAcObWV-4)

## QA Steps

1. Log into Notify staging
2. On your service's dashboard, click "x emails sent" to visit the notifications page
3. Observe that when you click the "Only show problem addresses" checkbox, the "total" tab is highlighted
4. Click the checkbox again to uncheck, and observe that the "total" tab remains highlighted
5. Repeat steps 3 and 4 on the Jobs page.

**Comment by andrewleith** [comment]
- 1 PR merged this morning
- 1 PR to be reviewed

**Comment by smcmurtry** [comment]
Both PRs are now merged. This is ready to QA in staging.

**Comment by whabanks** [comment]
QA'd in staging, looking good!
