### ISSUE TITLE
Notification sent time can be inaccurate under certain conditions

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1197]
## Describe the bug 

When the Notify system is under heavy load, SES event notifications can sometimes be delayed in their processing.  The [code to handle an SES event notification](https://github.com/cds-snc/notification-api/blob/main/app/celery/process_ses_receipts_tasks.py#L61) uses the current time, so even if a message may have been sent out at time `X`, it can be marked as having been sent at time `X` + `delay`, where `delay` is the time between SES telling us the notification was successfully sent, and the time we actually processed this event.
 
## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-4 Low

## Expected behavior

Notifications should be updated to have been sent/failed/etc as per the time SES said the event occurs.

An SES event for delivery contains some information we should use to update the notification (i.e the `timestamp` field):
```
"delivery": {
    "timestamp": "2016-10-19T23:21:04.133Z",
    "processingTimeMillis": 11893,
    "recipients": [
      "recipient@example.com"
    ],
    "smtpResponse": "250 2.6.0 Message received",
    "reportingMTA": "mta.example.com"
  }
```

Simlilarly, bounce and complaint events have a `timestamp` field:
```
"bounce":{
    "bounceType":"Permanent",
    "bounceSubType":"General",
    "bouncedRecipients":[
      {
        "emailAddress":"recipient@example.com",
        "action":"failed",
        "status":"5.1.1",
        "diagnosticCode":"smtp; 550 5.1.1 user unknown"
      }
    ],
    "timestamp":"2017-08-05T00:41:02.669Z",
    "feedbackId":"01000157c44f053b-61b59c11-9236-11e6-8f96-7be8aexample-000000",
    "reportingMTA":"dsn; mta.example.com"
  },

 ... 

"complaint": {
    "complainedRecipients":[
      {
        "emailAddress":"recipient@example.com"
      }
    ],
    "timestamp":"2017-08-05T00:41:02.669Z",
    "feedbackId":"01000157c44f053b-61b59c11-9236-11e6-8f96-7be8aexample-000000",
    "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36",
    "complaintFeedbackType":"abuse",
    "arrivalDate":"2017-08-05T00:41:02.669Z"
  },
```

## Other considerations
Our site shows the `updated_at` field to indicate when a notification was sent, which is a bit semantically incorrect here as we would need to set the `updated_at` field to a time that isn't actually the time we updated the record to make this work properly.  This might be acceptable, but warrants discussion.

## Impact

Impact on Notify users:
- Reporting the incorrect time leads users to believe our system is slower than it actually is

Impact on Recipients:
- None

Impact on Notify team: 
- May increase support calls

## Additional context
Related links:
- https://docs.aws.amazon.com/ses/latest/dg/event-publishing-retrieving-sns-contents.html

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1197?planning-poker) with Zenhub @andrewleith @jzbahrai @whabanks

**Comment by yaelberger-commits** [comment]
@jzbahrai @whabanks @andrewleith need your estimates on this one please

**Comment by andrewleith** [comment]
@jzbahrai and I looked into this and we decided not to do this at this time.  Given the effort to fix this and the fact we have scaled up our celery workers, there is a very low chance of this occurring now so it is not worth it at this time to pursue.
