### ISSUE TITLE
Improve notification status returned by callback api calls

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1199]
## Description

As a Notify user, I need to understand what the statuses of my messages are.

WHY are we building?

- users find the status message returned by an api call confusing.
- In the api call we just dump the status that is in the database but in the reports or admin we translate the database status into more understandable language.  This can cause confusion for users comparing the two. I think it's fair that we don't want the status in the database changing everytime we want to tweak the content. We basically have this documentation to help devs translate. Maybe we should add to that documentation, or even include that link in the api call?
- I think there can be more details that AWS returns that we're not saving anywhere? If so this might be useful to the end users and us.

WHAT are we building?
- improve the status returned by an api call. It should be at least as informative as the status in the admin. Or we could improve the docs and point them towards that in their api call.
- We could even include more technical details since the users of the api calls will likely be developers.

VALUE created by our solution
- users understand what's going on
- users are more self-sufficent

## Acceptance Criteria

- [x] better status returned by api calls
- [x] comparing the status returned by an api call to that displayed in the admin is not confusing to users

## Related

[Support ticket](https://assistance.cds-snc.ca/a/tickets/14816)

## QA Steps
- [x] create messages that were delivered / blocked / no email address / inbox full and compare the statuses returned by api calls to those in the admin
- [x] Notify the user that filed [the support ticket](https://cds-snc.freshdesk.com/a/tickets/14816).

**Comment by jzbahrai** [comment]
Current callback for a bounce failure:
```
{"id": "97e328d2-97e4-40a8-9df6-5b2c1dc1c692", "reference": null, "to": "bounce@simulator.amazonses.com", "status": "permanent-failure", "provider_response": null, "created_at": "2023-05-16T19:16:17.054545Z", "completed_at": "2023-05-16T19:33:26.137307Z", "sent_at": "2023-05-16T19:16:17.630991Z", "notification_type": "email"}
```

We want status = the same thing that is returned on admin

**Comment by whabanks** [comment]
Code has been reviewed and merged into staging. We're ready for QA. Initial test of callbacks is looking good, statuses map to what we display in the UI:

![image.png](https://images.zenhubusercontent.com/6362cf580029e141b402bb65/4bcf8e46-3b27-49d1-86fb-b616185a67b7)

**Comment by andrewleith** [comment]
- PR up has been reviewed, will be merged today.

**Comment by whabanks** [comment]
[Updated the API docs](https://github.com/cds-snc/notification-documentation/pull/126) to reflect the updated statuses. Content needs review and French translations to finalize.

**Comment by andrewleith** [comment]
- code is done and merged, finishing up API docs. should be done today!

**Comment by andrewleith** [comment]
- Ready for QA by @smcmurtry

**Comment by smcmurtry** [comment]
I tested this and found that the new `status_description` data is returned from the `/v2/notifications/{notification_id}` endpoint, but it is not present in the data sent to a callback url. Will and I have co-authored a PR to fix this issue.

**Comment by smcmurtry** [comment]
This is now working as expected in Staging. This will be deployed to production at the next release. Then we can update the user who made the support request.
