### ISSUE TITLE
beta test bounce rate release 1.0 with some services

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1200]
## beta test bounce rate release 1.0 with some services

As the Notify App team, we need to be able to roll out the bounce rate release v1.0 to a few clients first before rolling it out to all, so that we can find issues early and validate our designs with more confidence. 

## Documentation and Artifacts

Tracking spreadsheet
https://docs.google.com/spreadsheets/d/1s9g0gR270K17fBUDZauRQZZ6BhnqKjzI2mSdxhol65k/edit?pli=1#gid=0

## Acceptance Criteria

- [x] We have tested with 3-5 real clients with live services, in Production for a week
- [x] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [x] Add FF_ABTEST_SERVICE_ID env variable to enable A/B testing
- [x] Findings and feedback are added as bugs or tasks for release 1.5 or a decision is made to turn off the feature if there is a showstopper issue

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

**Comment by amazingphilippe** [comment]
@andrewleith and @jzbahrai working on AB testing service setting

**Comment by jzbahrai** [comment]
We will re-evaluate by EOD thursday and then maybe go ahead for all of production is next week.

**Comment by yaelberger-commits** [comment]
No feedback was given. We found and resolved a few additional bugs ourselves. This is done
