### ISSUE TITLE
V1.5 content improvements for Guidance pages

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1201]
## Description
Changes to these 3 pages in GC Articles:

https://notification.canada.ca/guidance
https://notification.canada.ca/delivery-and-failure
https://notification.canada.ca/keep-accurate-contact-information

As a user, I need to be able to easily identify the sections on the guidance pages that are relevant to me so that I can control my bounce rate.

WHY are we building?
For version 1.5, there's content we can easily and efficiently improve. 
We've seen parts that may not work well so we want to make sure we've addressed those issues before testing so that we don't find problems we already know about during testing.

WHAT are we building?
Improvements to the 3 Guidance pages on GC Articles

VALUE created by our solution
Get ready for testing and clarify information architecture prior to release.

## Documentation and Artifacts
https://notification.canada.ca/guidance
https://notification.canada.ca/delivery-and-failure
https://notification.canada.ca/keep-accurate-contact-information

Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given we're releasing 1.5 to everybody, we know the content is as good as it can so that we can test for version 2 and so that less technical support is needed 

- [x] Make it easier for users to identify when they're linking to Guidance. This work is covered in #1193
- [x] Shorten headings so they're easier to scan
- [x] Dev and PM review of the new content
- [x] Support review of the new content
- [x] Translation and FR content review
- [ ] Inventory of places that hyperlink to guidance so that we can update those links with the new titles
- [x] Upload the changes to GC Articles
- [x] Give a heads up to the app-team channel once ready to publish
- [x] Clear the cache on staging, clear cloudfront cache in G

- [ ] Create new hypotheses for user testing? 
- [ ] Consider testing structure for all of the Guidance pages with Fable?

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario
- [ ]  Check language toggle twice, from each language to the other
- [ ] Scan for a11y and fix any found issues
- [ ] run the cypress GCA tests

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1201?planning-poker) with Zenhub @YedidaZalik @adriannelee @amazingphilippe

**Comment by andrewleith** [comment]
- Draft ready, was discussed last week

**Comment by andrewleith** [comment]
- Changes are being made and have been reviewed
- @YedidaZalik waiting on answer on AC

**Comment by YedidaZalik** [comment]
Removed AC to explain delivered status changing to failed as it's dealt with through [this card](https://github.com/cds-snc/notification-planning/issues/1129)

**Comment by YedidaZalik** [comment]
I've implemented the feedback and the document is ready for French.

**Comment by YedidaZalik** [comment]
Document is ready for French content by @msbcsc

**Comment by YedidaZalik** [comment]
Created inventory of pages that hyperlink to guidance as we'll have to update links for those that do

**Comment by YedidaZalik** [comment]
English bounce rate guidance https://docs.google.com/document/d/1EuhmtD71Xe1mwTIAIUi8XHaQZGPesgeySP5G_aFPaNI/edit
French bounce rate guidance
https://docs.google.com/document/d/1iL373wwLgGSvLH12v-V5XHAB7bBDoVNr2WAozTkeCFk/edit#heading=h.gjdgxs

**Comment by smcmurtry** [comment]
Yedida - finished 1st pass at english content is done.

**Comment by yaelberger-commits** [comment]
Published in GC Articles last week, need to go through the AC

**Comment by yaelberger-commits** [comment]
Phil working on a PR to add new URLs to the page. A bit complicated. Working with Andrew on it. WAF rules in TF and new routes in Admin. PR for WAF rules is up for review. Need to maintain our GCA pages and add new URLs too.
