### ISSUE TITLE
Improve the GC Articles page for status updates and create template for page entries

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1205]
As a Notify user, I need to be able to find additional information when I come across a system error so that I can brief up, relieve any concerns and answer my questions without having to reach out to Notify Support.

WHY are we building?
- We want users to be able to self-serve more information about security issues, incidents, privacy breaches etc. so that we build a more transparent process

WHAT are we building?

- A status page that indicates whether Notify is operational and information about incidents, breaches and downtime, system load status (even if it's not an issue)
- A link from the footer
- A link from the contact us page 
- A link from any 500 errors, the API is down, there's a slow down / downtime 
- A template for status updates (title, heading for each entry, entry text, publishing date, newest at the top, first 10 entries shown and pagination, github on the status updates for more information) .

VALUE created by our solution
- Users won't have to contact us for more information and we can avoid having to send emails to all users every time we have information to share about an issue, instead we can include a link to more info on a System Status page

## Documentation and Artifacts
Example from Notify UK
https://status.notifications.service.gov.uk/

Something else from CDS: https://status-statut.cds-snc.ca/history/gc-notify

Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given A user lands on the "You need to create a new password" page, when they select the link to more information on our system status, then they land on the new GC Articles page with updates and information about these kinds of security issues etc.

- [x] Criteria for what qualifies as something we would put on the status page (story mapping or review of past items that we would have posted if a status page existed at the time)
- [x] It's clear what to include in the status update (even if Yedida is not here)
- [x] The status update template is modular, can apply to other Platform teams
- [x] Most recent information is at the top (not pushed down to the bottom when there aren't issues)
- [x] Page loads within 200 milliseconds
- [x] Progressive disclosure - Not too much information is shown at once
- [x] Data that feeds into this page doesn't need to be fed in manually by our team 
- [ ] Policy check for automation has been done 
- [x] The status page uses labels and categories used in the SLO
- [x] SRE to review clean draft
- [x] Improved content is published (add publishing checklist here)
- [x] Status page is linked from Security Statement in EN and FR
- [x] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [x] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- [There is a strong desire for stability and longevity of the system as well as continued support in the form of regular updates to the system. Concerns around whether or not the system would survive changes to the elected political party.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwtsq6Gy7TDVGL36/rec0gd9HjAp1lpyaz?blocks=hide)

## QA Steps
- [x] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1205?planning-poker) with Zenhub @yaelberger-commits @adriannelee @amazingphilippe @YedidaZalik

**Comment by YedidaZalik** [comment]
Shared initial [review of policy docs for items requiring entries on system status page](https://docs.google.com/document/d/1sIdSQF1eui3R9vINZeCnerqhWdqHRgp1q6HiKBqNkfY/edit). @yaelberger-commits @mtoutloff reviewing.

**Comment by YedidaZalik** [comment]
Took initial [work on modular components to critique](https://docs.google.com/document/d/1B601sAfLpEtpBnih6742-Gc_SZRHIzpoYQbfSx4IKZU/edit#heading=h.g2f28re96y4p) and got very helpful feedback:
Content critique

Way to mitigate how long things get, way to inject that in components
Year, month, day, time - is it time it’s posted, or do this by, 

In context, you must/should might be more appropriate- tell people what do to, especially should but may be difficult for team to compose. That way , team struggles with giving an order, do some boilerplate ones to model, do this

Try to give some reassurance- must/should are less reassuring, just tell people what to do- instructions - strong words in French - be helpful and kind

Action to be taken/We’re taking - may be more than 1 — we discovered something and therefor an action is required- Need to operationalize

Date - use word for month and spell it out - in the past date mix-ups and problems when month comes before date -need to spell month

Curious if dates would be headings - Do titles help make it scannable ?

Title might make it more scannable. Relevant design system work:

https://docs.google.com/document/d/1smhU6CKWwQCmSnYWcRtNltYPlwASilt4lJxaLiJ_Pyo/edit

Titles could be in different colour

Time event occurred and problem and action need to take

Character limits

There may be a way to emphasize when a user should take an action - could we have button link to place where need to take action or way to emphasize in different way as a CTA

How to put in when something is resolved, is there a way to help folks see which are more important/current - do they need more context, when and how resolved

When the issue is being investigated/ tags like investigation/resolved
maybe monitoring also?

What you might call these components to help your colleagues find and select them

Bring back for mega content

**Comment by YedidaZalik** [comment]
Met with Marie-Sophie for initial feedback
Sent r[eorganized criteria page ](https://docs.google.com/document/d/1nQAJbQhCgu2CyG6LA9CAVUmdJ_koO_U9sQImZfRH3qc/edit) for  initial review by Yael and Melissa. I've posed 3 questions using the comments function. There were also 2 questions that I'd included in the original document and I've put those under the heading "Questions" at the very end of the page.

**Comment by andrewleith** [comment]
- Feedback received for initial template; Yedida to work on this today
- Marie-Sophie to review as well
- More meetings for next week to keep this moving along

**Comment by YedidaZalik** [comment]
Yael explained that we should not include the instructions about what users should do due to an incident on the status page, as that could create a security risk. We'll send the instructions via an email.
So I'm also starting to think about the email.
Looked into best practices for subject lines for bilingual emails
Reviewed although some parts are not applicable to GoC email subject lines eg. Emojis
https://mailchimp.com/help/best-practices-for-email-subject-lines/
https://www.campaignmonitor.com/resources/knowledge-base/email-subject-lines-best-practices/
Not relevant after reviewing https://www.contactmonkey.com/blog/multilingual-emails
https://sendgrid.com/en-us/blog/a-tale-of-two-transactional-emails
https://www.campaignmonitor.com/resources/guides/localize-email-campaigns/

Most helpful info on slack thread with content designers https://gcdigital.slack.com/archives/CJGDB0TQV/p1701289007860319

**Comment by YedidaZalik** [comment]
Most recent work on criteria
https://docs.google.com/document/d/1nQAJbQhCgu2CyG6LA9CAVUmdJ_koO_U9sQImZfRH3qc/edit

Most recent work on modular components for status page and a start on the email (at very end)
https://docs.google.com/document/d/1-EYdi_NjrDt5s6Iag8l-XZD5gM3QAfOunyFKbh0Qj0g/edit

**Comment by YedidaZalik** [comment]
Resolved comments in criteria document so that some have been moved to card for v3 release and the only ones remaining are the ones that we need to discuss with devs.
Taking modular components for page/email to content critique this morning.

**Comment by YedidaZalik** [comment]
Applied critique ideas and previewed to Adrianne and Phil yesterday.
Showing Yael this morning.
Then criteria meeting, and entering rest of content based on the criteria selected.

**Comment by andrewleith** [comment]
- feedback implemented
- more work being done today then to design for review

**Comment by YedidaZalik** [comment]
Main feedback from Adrianne and Phil after review: combine criteria and template documents
Taking to content critique today for ideas on how to do that and then will continue to implement

**Comment by YedidaZalik** [comment]
Implemented some critique feedback and combined documents using google collapsible headings
Sometimes they don't collapse as well as they should so eventually may need to use a different medium
Still working on it but it's ready for dev design review

**Comment by YedidaZalik** [comment]
Previewed combined doc during dev design review https://docs.google.com/document/d/1issVNUXeQUK7sMMd8rvtBDnGt9vyT5wv-JJdsG3SwR8/edit
We decided folks will have until EOD Monday to look at and give feedback async
Posted in channel

**Comment by jzbahrai** [comment]
Yedida to look at the different options - github, intranet , gcarticles

**Comment by YedidaZalik** [comment]
Jumana checked and Github will not be private so that's not an option
Outreach currently posting position for someone to work on intranet so we may not get that answer before the new year

**Comment by YedidaZalik** [comment]
From Ciara re: intranet

Hi Yedida! Yep for sure, there are a couple options for that:
you could make the page password protected, so only folks in the Notify team would have access to it
or, you could set up a page with some context, and then either link out to content in google drive that's only accessible for Notify team members, or link to a password protected page for Notify folks
Either way, I'd recommend a line providing context (ie: "This content is for Notify team members only, if you need access, please contact X.").
Also- would it be worth considering if there would be any value in having the content available for teams at CDS outside of Notify? If that's the case, you could share links that could be accessed for anyone with access to the CDS shared drives. That might not work for these docs, but just figured I'd share if it's something that might work for your team!

**Comment by YedidaZalik** [comment]
Discussed with Phil - only certain parts of the document could be hosted on GC Articles so not ideal

**Comment by adriannelee** [comment]
The Intranet didn't really solve the problems with the document. Discussed with Yael some of the solutions. Decision: These improvements will be a future iteration. Melissa to take a look at the formatting.

Now looking for a review from the SRE team, in the new year. 

Some parts need translation - for discussion in the new year.

**Comment by mtoutloff** [comment]
Meeting with Yedida on January 8 to help with the formatting

**Comment by YedidaZalik** [comment]
New iteration featuring great improvements from @mtoutloff 
[System status page posting instructions and templates](https://docs.google.com/document/d/1Y636QM_tmN1Q5KjoONSizTvcmAgJMeD293QPmN7KFBY/edit#heading=h.igfg49qfvoi2)

**Comment by YedidaZalik** [comment]
Posted in security/privacy requesting meeting to walk them through the document prior to review
https://gcdigital.slack.com/archives/C9XPCMVN0/p1704819135931739

**Comment by YedidaZalik** [comment]
Walkthrough with Security/SRE reviewers scheduled for 2pm today

**Comment by YedidaZalik** [comment]
@mtoutloff and I met with Security/SRE folk to walkthrough the document
They say they can review by end of week
They will enter comments in the google doc
When I'm off on Thursday/Friday, Melissa will field any questions from them
Slack thread about this https://gcdigital.slack.com/archives/C9XPCMVN0/p1704914282479669?thread_ts=1704819135.931739&cid=C9XPCMVN0

**Comment by YedidaZalik** [comment]
Melissa is reviewing the comments

**Comment by YedidaZalik** [comment]
Guide now in this folder https://drive.google.com/drive/folders/10Z6o8_OWQNcOHlg7GA5sONwfiw5AYunp that's in the Security and Support folder

**Comment by YedidaZalik** [comment]
I think we were deciding whether to translate @mtoutloff @yaelberger-commits ?

**Comment by YedidaZalik** [comment]
Slack threads about translation
https://gcdigital.slack.com/archives/C04TQMJCXEW/p1705506762610279
https://gcdigital.slack.com/archives/C04TQMJCXEW/p1705420766147689?thread_ts=1705354167.798729&cid=C04TQMJCXEW

**Comment by foudamo** [comment]
Action items:
- Archive the many different iterations of document, and link to the newest document
- Check on the translation requirement (from Melissa's message) https://gcdigital.slack.com/archives/C04TQMJCXEW/p1705420766147689?thread_ts=1705354167.798729&cid=C04TQMJCXEW  
- - Update from Mohamed: we don't need to, unless someone specifically asks for accommodation
