### ISSUE TITLE
Problem email address percentage displays incorrectly for low bounce rates

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1206]
## Describe the bug 

When a service's bounce rate is lower than 0.0% the widget is displayed incorrectly.

![image.png](https://images.zenhubusercontent.com/558ca3104f7a08fbb7f36ec0/7a326f50-bb4f-41d2-b7bb-85993e46bab5)

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-3 Minor

## To Reproduce

1. Send 1100 good emails and one bad email
2. Observe the dashboard

## Expected behavior
- Dashboard should display correctly 

## Impact

Impact on Notify users:
- Could cause users to mistrust the dashboard

Impact on Recipients:
- None
Impact on Notify team: 
- Increased support tickets

**Comment by whabanks** [comment]
QA'd on staging, looks good!

**Comment by yaelberger-commits** [comment]
It's tough to test again after there has already been some volume, but Will tested, so all good! Looks like this is Done!
