### ISSUE TITLE
Problem email percentage reported incorrectly for sends using multiple templates

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1211]
## Describe the bug 

When a service does bulk sends with 2 or more templates, the dashboard incorrectly displays the total problem emails from the last template used instead of the sum of problem emails from all of the templates.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-3 Minor

## To Reproduce

1. Do 2 bulk sends with bad email addresses using 2 different templates
2. Dashboard shows total problem emails from last bulk send only

## Expected behavior
- Dashboard should show total problem emails from both bulk sends

## Impact
Impact on Notify users:
- Incorrect reporting could underestimate total problem emails, causing users to think they have good emails lists when they may not. 

Impact on Recipients:
- None

Impact on Notify team: 
- Potential for increased support calls.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1211?planning-poker) with Zenhub @andrewleith @jzbahrai @whabanks

**Comment by andrewleith** [comment]
Tried to reproduce this but could not.  I sent 6 emails using 3 different templates:
- 2 bad
- 2 good
- 2 bad

Dashboard correctly reports this:
![image](https://github.com/user-attachments/assets/88171a53-7167-400a-bdcb-e22325da16b8)

![image](https://github.com/user-attachments/assets/80d934f8-6d52-44f1-ba8b-208b7945e449)

As does the review email address page:
![image](https://github.com/user-attachments/assets/4fbf68aa-7946-49b6-a725-9db984ba44fe)

I think this has been fixed.
