### ISSUE TITLE
Welcome screen should be displayed if a user has not successfully created a service yet [bug-bogue]

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1213]
## Describe the bug 

This is a small part of the card #679

If a user does not complete the steps to set up their first service before logging out, GC Notify does not show the Welcome screen when they log back in.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

1. Create a new user account
2. Verify your email address and mobile number
3. Observe that you see the Welcome screen
4. Log out without creating a service
5. Log back in
6. Observe that you do not see the Welcome screen, just a blank page with a button to create a service

## Expected behavior

At step 6 above, you should see the Welcome screen again.

## Impact

Impact on Notify users:
Users who do not complete the step to create their first service are not able to see our guidance about what a service is, etc when they log back in and try to create a service again.

Impact on Notify team: 
This makes usability testing more difficult. Since usability tests may be done with an account that was already created, but that has no services, participants need to be sent the link to the Welcome screen rather than seeing it automatically when they log in.

**Comment by smcmurtry** [comment]
Reviewed by @adriannelee and @whabanks. Now merged and deployed in Staging. Ready to be QA'd.

**Comment by andrewleith** [comment]
- Needs a QA'er - @andrewleith can QA

**Comment by andrewleith** [comment]
Looks good following repro steps.  Outside the scope here, but should the `/accounts` route (the `Your services` menu item) redirect here too when a user has no services?

**Comment by smcmurtry** [comment]
Good question - I've added that question to the larger card around improving this experience: https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/679
