### ISSUE TITLE
Clarify when daily limits reset

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1221]
As a user, I need to be able to understand when my daily limits reset so that I can stay within those limits or request an increase if necessary 

WHY are we building?
Daily limits impact Notify users but the timeframe for the limit may depend on the users time zone.

WHAT are we building?
Clarity around when the timeframe for a day starts to run and when it stops.

VALUE created by our solution
Users will easily understand how these time frames and limits apply to them.

## Documentation and Artifacts
Review work on COVID Alert QR timeframes and possibly consult Ioana to check how we solved for this.

Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given I need to understand a daily timeframe, I know when my day starts to run and when it stops for GC Notify.

- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
@YedidaZalik wouldn't this be the same as #935

**Comment by YedidaZalik** [comment]
Yes, apologies that I missed that.
I will copy the more detailed user story from this card into the other card and archive this one.
