### ISSUE TITLE
'About your service' dropdown

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1223]
## Description

As a CDS CRM manager, I need new clients to log in the right field when they can't find their department on the dropdown so that I can keep the data clean without a lot of manual work.

As a francophone client, I need the "No search results" to be in English.

As screen magnifier user, I need to be able to read what I've selected when using a dropdown. [Video clip](https://docs.google.com/presentation/d/1Rm8MSOnjLB08WW1spb5pitx56WO9eyEcNtl5Cat_akU/edit#slide=id.g245d729d97d_0_15)

As a screen reader user, I need to press 'Enter' on a dropdown selection without submitting the form so that I can review what else is on the page before I submit.

WHY are we building / VALUE?
- Users are comfortable using the product in either official language
- Clean data
- Providing accessible elements means that a higher diversity of public servants are supported for their job.
- Prevent accidental form submission

WHAT are we building?
- Design fix to figure out where people should enter the department/org not on the list
- Other fixes to the dropdown

## Documentation and Artifacts
![image.png](https://images.zenhubusercontent.com/61267d15419dc0a24aa009dd/f0044a8d-ee87-4b28-92c4-4f54477c83f5)

## Acceptance Criteria
- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] When the page is in French, "No search results" is in French
- [ ] When the department/org is not on the list, the user doesn't enter it in 'Enter any other names for your group'
- [ ] Using a screen magnification tool (Firefox issue?) text doesn't overlap when a selection is made and the user click on the dropdown again
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- [Submitting the 'About your Service' form is surprising. Pressing 'enter' on the dropdown submits the form - there's no confirmation](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recdMcEmRxUKLKd2J?blocks=hide)
- [Overlapping of text on dropdown & not clear how to delete an entry](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recQ6GlaKjLhrjebX?blocks=hide)
- [Would enter dept not on list to "Other names" field. ](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recLOGNPdBXoYcPM5?blocks=hide)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by amazingphilippe** [comment]
A bit more investigation on the overlapping text. This screenshot shows that the autocomplete input and suggestion don't quite align. Also noting that the color contrast of that suggestion backdrop probably doesn't pass 7:1, or even 4.5:1. One idea could be to remove it. I'm not sure we need it?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmx6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1daaf5bc1062fdf0629e0f1b3a01eec3c306b048/Capture%20d%E2%80%99e%CC%81cran%2C%20le%202023-09-06%20a%CC%80%2014.49.20.png)

**Comment by amazingphilippe** [comment]
There is also a focus trap introduced by this component:

[Uploading... Enregistrement d’écran, le 2023-09-06 à 14.54.44.mov]

**Comment by amazingphilippe** [comment]
[Fable testers confirmed](https://cds-snc.dovetailapp.com/insights/3ljy9QYKrsKVwnc7beMCBS) the same bugs we have found.

**Comment by amazingphilippe** [comment]
Possible native way of doing this: https://www.htmhell.dev/adventcalendar/2023/2/#datalist-a-native-autosuggest

**Comment by YedidaZalik** [comment]
Adding to Ally stmt

**Comment by YedidaZalik** [comment]
Andrew will review
