### ISSUE TITLE
"Email address field is in English when reviewing a template in French

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1226]
![11. Preview template.png](https://images.zenhubusercontent.com/61267d15419dc0a24aa009dd/38354e2c-29d2-4b2c-9fc1-08ebbd4b0c65)

**Comment by jzbahrai** [comment]
Bilingual column names might be the solution here.

**Comment by andrewleith** [comment]
Looks like the same thing happens for "phone number" when sending an SMS.  Will fix both.

**Comment by smcmurtry** [comment]
Steve to review.

**Comment by yaelberger-commits** [comment]
Andrew waiting for PR review. Jumana can review
