### ISSUE TITLE
DEV: System status page is linked in EN and FR from other Notify pages identified as relevant 

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1231]
## Description

As a user, I need to be able to able to easily move between the system status page and other relevant pages so that I'm aware of incidents impacting security and service interruptions and can link them to Notify's practice of continuous security and our SLO's.

WHY are we building?
Users reading the security statement should be able to review current and previous incidents. Users reading the SLA should be able to easily find the system status page. Users on the SLO and Contact us page should be able to link to the system status page to determine whether to ask for support.

WHAT are we building?
Content to link the following pages to the status page:
- Security statement
- SLA
- SLOs
- Contact us

VALUE created by our solution
Notify users can easily link between the pages that have content related to the system status page.

## Documentation and Artifacts
[System status page - possible links from other pages  including policy doc review](https://docs.google.com/document/d/1Bl_I5bmDX9nVscP5IleOMzk66hMBXczGGYkkUuIb75Y/edit)
Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given I'm reading about Notify's security and status, when I want to review the history of security related incidents and service interruptions, then I can easily find that information. 
Given I'm on the SLO or contact us page and deciding whether to request support, I can easily link to the status page to know whether Notify is already aware of/ working on my issue.

- [x] Create content to link the relevant pages to the system status page
- [x] Content localized to FR
- [x] Content and menus updated in GC Articles. Using publication checklist
- [x] Content updated in notification-admin (footer)
- [x] Content updated in Security Statement EN/FR and _last updated_ is updated
- [x] Content updated in SLA EN/FR and _last updated_ is updated
- [x] Content updated in SLO EN/FR and _last updated_ is updated
- [x] Content updated in notification-admin (Contact Us page EN/FR) 
~~- [ ] New feature update for status page (maybe)~~

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by YedidaZalik** [comment]
Reviewed pages including policy docs to assess where to link to status page: https://docs.google.com/document/d/1Bl_I5bmDX9nVscP5IleOMzk66hMBXczGGYkkUuIb75Y/edit

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1231?planning-poker) with Zenhub @YedidaZalik @adriannelee @amazingphilippe

**Comment by YedidaZalik** [comment]
Discussed accessibility recommendations for hyperlinks during design sync.
Prepared link content (in purpled) for Melissa's review:
https://docs.google.com/document/d/1Bl_I5bmDX9nVscP5IleOMzk66hMBXczGGYkkUuIb75Y/edit

**Comment by YedidaZalik** [comment]
@mtoutloff reviewed and have now sent to @mariesophiebezert for localization review
After that will share with team

**Comment by amazingphilippe** [comment]
From the contact page, content will be added above the form. 
In the footer, the link will go under the contact form link, in the "support" section.

[Figma prototype](https://www.figma.com/file/GAh6VlA5SQGeZwO6LHtZr8/System-status---%C3%89tat-du-syst%C3%A8me?type=design&node-id=80-2981&mode=design&t=pjQsCGT3IiuHEf3H-4), but I don't think we'll need a dev-design review for this. Its pretty simple.

**Comment by YedidaZalik** [comment]
Marie-Sophie made some suggestions which I incorporated.
Yael reviewed and said it could go to translation.
Marie Sophie can use this page: https://docs.google.com/document/d/1FBBMq5F88tqlZuVCsSb0JFPpdW-tTbqJWcTOJ-4bwFc/edit

**Comment by yaelberger-commits** [comment]
<img width="1638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEQ0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--211886991624300d3e14a293629c87a681442a0e/Screenshot%202024-01-24%20at%204.01.19%E2%80%AFPM.png" alt="Screenshot 2024-01-24 at 4.01.19 PM.png" />

<img width="1672" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEg0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a74e104f022365d7eafbb282a3ebb9d2b84fc389/Screenshot%202024-01-24%20at%204.02.11%E2%80%AFPM.png" alt="Screenshot 2024-01-24 at 4.02.11 PM.png" />

**Comment by yaelberger-commits** [comment]
Updates with links to System Status page made to Security page, Service Level Agreement, and SLO page in both EN and FR and _last _updated__ date has been changed. Contact Us page still needs new content with link, and this card will need QA by someone other than me next

**Comment by amazingphilippe** [comment]
Looked at all the pages and made tiny changes
- A leading space was hyperlinked in French links. 
- Fixed the list numbering on the SLA pages. 

Otherwise looks good on the GCA pages.

For the contact us page, [the translated screens are in Figma](https://www.figma.com/file/GAh6VlA5SQGeZwO6LHtZr8/System-status---%C3%89tat-du-syst%C3%A8me?type=design&node-id=80-2981&mode=design&t=VUpbDdBc1s5ssMu6-4)

We can tag the dev team to continue this story.

**Comment by amazingphilippe** [comment]
In staging, waiting for release, andrew QA'd

**Comment by yaelberger-commits** [comment]
Released this morning
Yael QA'd in production
