### ISSUE TITLE
Upload list of recipients. Using deprecated html element <acronym> for abbreviations. 

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#124]
### Description of issue

We provide expanded definitions using the acronym html element.
Further, we do not provide ways to pronounce acronyms correctly. ODS with voice over in French is pronounced "Oh!" 

> <img width="1129" alt="Capture d’écran, le 2021-10-19 à 13 16 07" src="https://user-images.githubusercontent.com/5230720/137961512-a007fb13-7a18-4023-b127-6d961595fca3.png">

### Potential fix
- Compose the sentence with the expanded form of the abbreviation
- Visually hide the expanded form with `class="sr-only"`
- Add abbreviations and use role="presentation" to hide them to screen readers. 

Example:

``` html
<p>
Enregistrez votre fichier comme tableur, en format 
<span role="presentation">CSV</span>
<span class="sr-only> (Valeurs séparées par des virgules) </span>
</p>
```

### Resources
Don't use https://developer.mozilla.org/en-US/docs/Web/HTML/Element/acronym

**Comment by amazingphilippe** [comment]
@EliseKa Je t'ai taggé pour voir ce que tu ferais pour "Open Document Spreadsheet" en français.

**Comment by EliseKa** [comment]
Ok alors OpenDocument, c'est le nom du format (et ça s'écrit collé). Je sais pas si ça cause problème pour VoiceOver? Si non, j'écrirais "feuille de calcul OpenDocument".

**Comment by amazingphilippe** [comment]
Ça marche! "OpenDocument" est reconnu par voiceover.
