### ISSUE TITLE
Ensure redis bounce rate calculations are accurate

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1244]
## Description

As a (notify dev) I need to analyze the bounce rate warning and critical alarms to ensure the system will automatically suspend services at the appropriate thresholds.

Now that we are logging bounce rate information, we can review the alarms to see when the system marks a service as warning and critical, and then do separate queries on the database to ensure all the calculations are working as expected.

For each warning/critical bounce rate alarm, query the database for that service over the previous 24 hours and manually calculate the bounce rate (permanent failures / total sent) to ensure this is being calculated correctly.

## Acceptance Criteria
- [ ] Bounce rate warnings alarms are double-checked against actual notification sends/failures per the same time periods
- [ ] Bounce rate critical alarms are double-checked against actual notification sends/failures per the same time periods

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1244?planning-poker) with Zenhub @andrewleith @smcmurtry @whabanks

**Comment by smcmurtry** [comment]
I did the following test on Staging:
Testing the redis data in the v1.5 dashboard:

- logged in to my service dashboard on Staging (service id: 1dac916a-05b2-49ca-bf75-072231c3f505)
- Sent 1000 emails to "success@simulator.amazonses.com"
- observed that my dashboard showed the correct number of problem addresses and the background colour is green
- started sending emails to "bounce@simulator.amazonses.com", got up to the following totals: 59 problem emails, 1163 successful emails.
- sent one additional problem email
- observed that the background colour turned red, and "5.07% problem addresses are displayed"
- logged into our AWS staging dashboard and found the following log: "Service: 1dac916a-05b2-49ca-bf75-072231c3f505 has met or exceeded a warning bounce rate threshold of 5%. Bounce rate: 0.05073086844368014"
- sent an additional 80 emails to "bounce@simulator.amazonses.com"
- observed that the dashboard is still red and the totals are correct: 1244 total emails, 140 problem emails, 11.25% problem addresses.
- observed 3 instances of the following log in cloudwatch: "Service: 1dac916a-05b2-49ca-bf75-072231c3f505 has met or exceeded a critical bounce rate threshold of 10%. Bounce rate: 0.11021721641190668"
- observed an alarm in the notification-staging-ops channel

One thing that I noticed is that I’m having to refresh the dashboard to see the numbers update. I’m not sure if I’m being impatient or if the auto-update ajax code is broken. I’ll investigate this afternoon.

**Comment by smcmurtry** [comment]
I created a card for the auto-update bug here since that is a separate issue: https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1276

The redis bounce rate data seems correct based on my tests.
