### ISSUE TITLE
Missing translations and punctuation problems in problem-emails screen

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1245]
## Describe the bug 

The problem-emails page contains some missing translations for the following strings:

- `{{ _( ' using template ')}} '{{ notification["template"]["name"] }}'`
- `{{ _( ' in ')}} '{{ job.original_file_name }}'`

Additionally, we are not using the correct quotation marks in french: `«»`. We could fix both problems with some string interpolation. Like we do for some other translations: `"Manage {}","Configurer {}"`

On the same page, and likely elsewhere, the percentage is not formatted properly in French. The decimal point should be a comma, and a non breaking space should be added in between the `%` and the number. 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3

## To Reproduce

1. Navigate with the French UI
1. Go to any service with some bounce rate
3. See the percentage on the dashboard
2. Click to see problem addresses today
3. See the percentage on the problem-emails page
4. See missing translation and formatting in list

## Expected behavior

French content should be translated and properly formatted

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: EN content within a French page

Impact on Recipients: None

Impact on Notify team: A bug to fix!

## Screenshots

![Capture d’écran, le 2023-06-13 à 14.39.16.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/5de6173d-4dd0-40e0-8f0e-0a141a1a9d8b)

![Capture d’écran, le 2023-06-13 à 14.42.10.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/4ccc95d5-21be-4754-be26-077d0841def1)

## Additional context

[Figma frame to track translations](https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?type=design&node-id=1641-14553&mode=design&t=gI9uAg1soq9piN1A-4)

**Comment by yaelberger-commits** [comment]
@amazingphilippe Moved this into the Product backlog as high priority

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1245?planning-poker) with Zenhub @amazingphilippe @msbcsc

**Comment by adriannelee** [comment]
Phil might start working on this today

**Comment by amazingphilippe** [comment]
Draft PR is created https://github.com/cds-snc/notification-admin/pull/1606

**Comment by adriannelee** [comment]
No more time to work on this sprint - but maybe next

**Comment by amazingphilippe** [comment]
Some of this like the dynamic percentage has been fixed. 
The static "Less than 0.1%" still needs a space. And the missing translations in the problem list are still missing, as per the screenshot above.

**Comment by amazingphilippe** [comment]
Created a bug frame in Figma to keep track of this work. https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?type=design&node-id=1641-14553&mode=design&t=gI9uAg1soq9piN1A-4

**Comment by smcmurtry** [comment]
Reviewed, Merged and ready for release

**Comment by smcmurtry** [comment]
QA'd and the changes look good! In the process I found a missing translation on the dashboard - I'll make a quick PR to fix that.

Problem addresses page:
![Screenshot 2023-07-26 at 2.40.55 PM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/d9e79a10-ae6a-4645-857d-33b77e905527)

Dashboard:
![Screenshot 2023-07-26 at 2.40.40 PM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/d70b4259-c035-46ae-93cb-e814e0c449c8)
