### ISSUE TITLE
The problem emails page link to "keep contact info updated" goes to the wrong guide

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1247]
## Describe the bug 

The problem emails page link to "Keep contact info updated" goes to the "Delivery and failures" guide

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

1. Go to https://notification.canada.ca/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/problem-emails
2. Click on "Keep contact information updated"
3. See that you are on the wrong guide.

## Expected behavior

We should land on https://notification.canada.ca/keep-accurate-contact-information

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: Not finding the guide they are looking for

Impact on Recipients: None

Impact on Notify team: Support requests for the actual guides if the users can't find it by themselves.

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1247?planning-poker) with Zenhub @whabanks @andrewleith @smcmurtry

**Comment by jzbahrai** [comment]
tested this on staging! looks good. Will be good to move to prod
