### ISSUE TITLE
Clicking on bulk problem emails doesn't pre-select the 'pe_filter'

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1248]
## Describe the bug 

On the problem emails summary page, links going to a bulk send don't pre-select the `pe_filter=true` and `status=permanent-failure` filters. 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

1. Go to a service with some bounced emails sent in bulk
2. Click on a link to view all problem emails in a bulk send
3. See that you land on the "failed" filter, rather than the special view for problem emails. 

## Expected behavior

Clicking on one of these links should allow you to view problem emails directly, and filter out other types of failures. 

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: Not being able to focus on problem emails directly, although they can enable the filter themselves

Impact on Recipients: None

Impact on Notify team: None?

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1248?planning-poker) with Zenhub @andrewleith @smcmurtry @whabanks

**Comment by andrewleith** [comment]
- @andrewleith started work on this today

**Comment by jzbahrai** [comment]
Tested this on staging! It works.
