### ISSUE TITLE
DEV Implement radio buttons on template creation to indicate template use case category, backend db integration

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1249]
## Description

Following the discussion at Notify 101 today:

We could add radio button question to the template edit page, like:
"Is this a Multifactor Authentication email, or Password reset email?"
Users choose which use case their template falls under

- [ ] Use Growth categories for this

Depending on which use case is selected, and whether it's SMS or Email, in the backend we assign the correct queue/vehicle for the template to be sent through (bulk, normal or high priority) (dedicated long code, pool of long codes, short code)

As a Sender of a message that requires immediate action from the recipient, I need to be able to indicate that my template is for account management (2fa, password reset, confirmation etc) so that I can ensure it will be delivered quickly (60 seconds or less almost all of the time). 

WHY are we building?
Now that we have a short code for generic use, we need to be able to assign which templates will go through the short code and which will go through the pool of long codes
WHAT are we building?
Radio buttons in the UI to choose which use case your new template falls under, that will be captured in the db
VALUE created by our solution
We will be able to assign templates to whichever queue or sending vehicle we want, automatically
We will be able to capture data at the template level of use cases, data we haven't captured before

## Documentation and Artifacts

Notify Use Cases deck from Growth
https://docs.google.com/presentation/d/1rIzQHBlGr13tmL_atg_lxDKX_rWSXvjsW7e0vAZqwCg/edit#slide=id.g2772e8d7530_0_7

## Acceptance Criteria

- [ ] Checkbox added upon template creation in to indicate which use case the template falls under
- [ ] Consult with dev for how to assign this to the appropriate SMS vehicle, and content for info, use Growth use cases (ADR) @yaelberger-commits and @jzbahrai 
- [ ] Check in place to prevent abuse (blazer query with a daily report/ something else)
- [ ] Data about template use cases is sent to CRM

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by jzbahrai** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1249?planning-poker) with Zenhub @smcmurtry @whabanks

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1249?planning-poker) with Zenhub @andrewleith

**Comment by jzbahrai** [comment]
Closing this ticket in favor of other tickets made
