### ISSUE TITLE
Automatically link new services to an existing organisation

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1254]
## Description

As a policy analyst, I need the PT data safeguards to be automatically applied to all new PT services as soon as they are created, so that we are sure we are applying these reliably, to comply with our obligations for handling client data. 

WHY are we building?
To make our PT data safeguards more reliable, and to reduce toil for support staff.

WHAT are we building?
- Automatically link new services to an existing organisation

VALUE created by our solution
- Reduced toil for support staff
- PT data safeguards are always applied as soon as the service is created (these are tied to the PT organisation)

## Documentation and Artifacts

Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria

- [x] if an option is selected from the "Select you department or organisation" dropdown, that organisation is automatically linked to the new trial service and visible on the settings page
- [x] if "Not on list?" was selected when the service was created, no organisation should be linked

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
Try creating a new service on staging and select one of the following organisations from the dropdown:
- Ontario
- Nova Scotia
- BC
- Accessibility Standards Canada
- The Space Agency

After the service is created, the organisation you selected should be already set on the settings page. If you selected a PT organisation, the data retention should be set to 3 days and any templates with variables you create should be redacted.

**Comment by smcmurtry** [comment]
Chatted with Pat and Jumana, I will add a data table to the [gc-organisations repo](https://github.com/cds-snc/gc-organisations) that will map Salesforce organisation IDs to Notify organisation IDs.

**Comment by smcmurtry** [comment]
I added the Notify organisation IDs to the GC Organisations dataset: https://github.com/cds-snc/gc-organisations/pull/47
Pat reviewed the changes.
Next step: make some changes to notification-api to do the auto linking.

**Comment by smcmurtry** [comment]
API PR is ready for review. I will prep a terraform PR to add some existing variables to the API pol and lambda fns.

**Comment by YedidaZalik** [comment]
Will to review

**Comment by smcmurtry** [comment]
Merged and ready to QA on staging. For QAing - I added steps to this card.

**Comment by yaelberger-commits** [comment]
I will QA this today

**Comment by yaelberger-commits** [comment]
QA done with Ontario and Accessibility Standards Canada in Staging as an Admin and everything works as expected.

**Comment by yaelberger-commits** [comment]
@smcmurtry anything left to do on this card before releasing to Prod?

**Comment by smcmurtry** [comment]
@yaelberger-commits Nope I think we are good! This code actually got released to Prod this morning.
