### ISSUE TITLE
Plan User Interview with a service with a high bounce rate

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1257]
## Description

The Notify App Team would like to speak to a Sender from a GC Notify service who regularly sends emails and had frequently had a high bounce rate to learn more about how they use the service dashboard so we can see ways we may be able to improve the problem email addresses feature and help this service reduce their bounce rate moving forward.  

WHY are we building?
We want to iterate on the bounce rate feature and improve the likelihood that a Sender will take action if they have a high bounce rate. 

WHAT are we building?
Research to inform future design changes

VALUE created by our solution
Our next iterations will be better informed by a Sender with a high bounce rate's needs 

## Documentation and Artifacts

https://docs.google.com/document/d/1eDmJUsQ92GvKGkvwxy2Kp6daDqlSjVp8qyV8ushZwIw/edit

## Acceptance Criteria
Given we conduct a research interview with a Sender from a service with a high bounce rate, when we make future design iterations for this feature, then we can include some insights, findings and user needs from the Sender. 

This will also be an opportunity to remind the Sender of the Terms of Use and help them be able to take action to remove problem email addresses from their distribution lists. 

- [x] Privacy statement
- [x] Set up Calendly
- [x] Send out Calendly (June 28-July 7)
- [x] Facilitation guide is drafted
- [x] Facilitation guide is reviewed by @yaelberger-commits @amazingphilippe @YedidaZalik 
- [x] Collect questions for bounce rate, dashboard

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

**Comment by yaelberger-commits** [comment]
@yaelberger-commits  and @adriannelee are putting together a lite interview session with a service to see how they're experience of the dashboard is going

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1257?planning-poker) with Zenhub @adriannelee

**Comment by andrewleith** [comment]
- We'd like to learn about their use/experience of the dashboard and the new features
- This may inform changes to the dashboard holistically
- @adriannelee has started on the facilitation guide
- @yaelberger-commits to refine the card some more

**Comment by yaelberger-commits** [comment]
We have a participant identified from the service in question, next step is to schedule the session.
@adriannelee would you like to schedule that, or would you like me to schedule and invite you as the facilitator? I can take notes.

**Comment by adriannelee** [comment]
Everybody has reviewed. One response to @yaelberger-commits 's comment on the doc
