### ISSUE TITLE
bug-bogue: Email/text messages in the past week pages use "sending" instead of "in transit"

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1258]
In prod, both admin and services, [this page for emails in the past week](https://notification.canada.ca/services/e9b8d628-021b-4e8a-ad3b-88a1bf7611cf/notifications/email?status=sending,delivered,failed) and [this page for text messages in the past week](https://notification.canada.ca/services/e9b8d628-021b-4e8a-ad3b-88a1bf7611cf/notifications/sms?status=sending,delivered,failed) use "sending" instead of "in transit". 

Also on the page for text messages in the past week, consider changing "Only show problem addresses" to "Only show problem phone numbers".

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

## To Reproduce

1. Go to the dashboard for any service
2. Click on emails sent or text messages sent
3. Scroll to the display across the top, and view the second box (after "total")
4. The box shows the word "sending".

## Expected behavior

Instead of "sending", the box should display "in transit"

## Impact

Inconsistent with the rest of Notify and the guidance. 

If applicable

Impact on Notify users: Could cause confusion

Impact on Recipients: None

Impact on Notify team: Could also cause confusion for new team members

## Screenshots

2 screenshots are attached

![Screenshot 2023-06-21 at 9.33.49 AM.png](https://images.zenhubusercontent.com/614b9f22b18cf806c628a310/701f1b64-2da6-45b3-9b54-f9bcd1a25a78)![Screenshot 2023-06-21 at 9.33.35 AM.png](https://images.zenhubusercontent.com/614b9f22b18cf806c628a310/b2f67d16-4c1f-441e-8fcf-09d8d4dfc7d8)

**Comment by yaelberger-commits** [comment]
I can QA this today

**Comment by yaelberger-commits** [comment]
Looks good in Staging for both email and text
