### ISSUE TITLE
Quick fixes: Provide more context on the job status screen

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1262]
## Description

As a sender, I need to be able to navigate the job status screen with clarity so that I can monitor any problems that might happen. 

**WHY are we building?**
- The job status report screen can sometimes lack important information
- The job status page is nearly identical to the notifications report screen
- Numbers in the navigation don't provide enough context, or don't seem clickable to screen readers?

**WHAT are we building?**
- Fixing the screen reader issue with the navigation labels. 
- Giving a title to this page
- Giving a heading to this page
- Ensure that we keep the current h1 content below the new h1. Like the file name or API send title. 
- Test and improve table empty state

**VALUE created by our solution**
- Quick fixes to improve this page's a11y

## Documentation and Artifacts

- Video: [Numbers don't seem clickable](https://docs.google.com/presentation/d/1Rm8MSOnjLB08WW1spb5pitx56WO9eyEcNtl5Cat_akU/edit#slide=id.g245d729d97d_0_87)
- [Figma prototypes](https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?type=design&node-id=1750-11568&mode=design&t=Nc141WIlyillmteF-4)

## Acceptance Criteria
Given a user seeks out information about a bulk send, when they find the notification status screen, then they find themselves at the right place because they understand the purpose of the page. 

- [x] Design a new page title that respects the hierarchy we've established in our information architecture
- [x] Design a h1 that helps the user situate themselves. It should also match the first part of the page title
- [x] Design where the current h1 information could be displayed
- [x] Design an empty state for the table
- [x] Translate any new strings created for this story
- [x] Fix the empty state for the table component
- [x] Fix the markup of the pill navigation so that it works better with screen readers. (We did what we could, but we couldn't find the problem)
- [x] Update the notification report page titles/heaings
- [x] Add empty states to main notification report and jobs pages
- [x] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [x] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)
- [ ] Update #601 to track changes that can be tested again. 

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- [#601](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/601)

## QA Steps
- [x] Test bulk sends through API and admin
- [x] Test while messages are not yet saved in database -> empty state
- [x] Test scheduled job details sends before they get sent. 
- [x] Test cancelling a job
- [x] Test job details with with screen reader
- [x] Toggle FR/EN to make sure translations work properly.

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1262?planning-poker) with Zenhub @andrewleith @YedidaZalik @whabanks @smcmurtry

**Comment by andrewleith** [comment]
AC mentioned above is complete and checked off above!

**Comment by amazingphilippe** [comment]
Started prototyping in [Figma](https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?type=design&node-id=1750-11568&mode=design&t=Nc141WIlyillmteF-4)

**Comment by yaelberger-commits** [comment]
Moved back to the Product Backlog as the team won't have capacity to tackle the work this sprint

**Comment by amazingphilippe** [comment]
Designed an empty states for the notifications table and brainstormed page titles. Also organized a little bit the Figma page.

**Comment by amazingphilippe** [comment]
Had a dev-design review. Handed the Figma back to the team for feedback until end of day today. Will pick this up next week for content critique Thursday morning and hand it back to the devs for implementation

**Comment by amazingphilippe** [comment]
Ready for dev: https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?type=design&node-id=2245-1524&mode=design&t=QJZ1RIKMINsxa5OW-4

**Comment by andrewleith** [comment]
Page titles have been updated and empty states added in cds-snc/notification-admin#1696 and are ready for review!

**Comment by YedidaZalik** [comment]
Replied to some comments yesterday

**Comment by amazingphilippe** [comment]
Sending 2 more screens to Marie Sophie for translation

**Comment by andrewleith** [comment]
All screens have now been implemented. Waiting on translations to finalize.

**Comment by yaelberger-commits** [comment]
Translations are back

**Comment by yaelberger-commits** [comment]
Will completed code review as well, needs another once over and ready to release

**Comment by andrewleith** [comment]
- updated translations in the UI; this is being reviewed

**Comment by amazingphilippe** [comment]
Design reviewed in PR https://github.com/cds-snc/notification-admin/pull/1696

A few changes requested. Almost there!

**Comment by andrewleith** [comment]
- @andrewleith to merge after release this morning. @andrewleith  + @amazingphilippe to review in staging and then sign-off

**Comment by andrewleith** [comment]
- Work complete, in production

**Comment by amazingphilippe** [comment]
Updated QA Steps. I can run through them since I don't even remember the work.
