### ISSUE TITLE
Problem SMS recipients are being counted as part of totals we are calling "problem email addresses"

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1263]
## Describe the bug 

Here is a video demoing the bug: https://www.youtube.com/watch?v=vdhzJS5MBCU

Here is a link to the service dashboard: https://notification.canada.ca/services/e393c88a-ed22-43f7-812a-424f0488e94d

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major

## To Reproduce

Steps to reproduce the behaviour:

1. Go to a service that has sent only SMS, and has some permanent SMS failures in bulk sends such as: https://notification.canada.ca/services/e393c88a-ed22-43f7-812a-424f0488e94d
2. Observe that the dashboard displays "6 problem email addresses" or some number greater than 0 
3. Click on "x% problem addresses"
4. click on "x problem email addresses in `bulk_send_name`"
5. Observe that these "problem email addresses" are actually problem phone numbers

## Expected behaviour

Problem phone numbers should not be labelled as "problem email addresses".

## Impact

Impact on Notify users:
Confusion

## Additional context

This service reached out to us via support - they are somewhat unique in that they have permanent SMS failures but no email failures. 

### Potential issues in code
- [Stats for problem emails page](https://github.com/cds-snc/notification-admin/blob/main/app/main/views/dashboard.py#L102) - `template_type` or `notification_type` should be taken into account here
- [Stats for dashboard](https://github.com/cds-snc/notification-admin/blob/main/app/main/views/dashboard.py#L360) (not using redis) - `template_type` or `notification_type` should be taken into account here

## Acceptance Criteria
-[x] Stats for problem email page is fixed
-[x] Stats for dashboard is fixed

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1263?planning-poker) with Zenhub @andrewleith @jzbahrai @smcmurtry @whabanks

**Comment by adriannelee** [comment]
Jumana will start working on this today

**Comment by jzbahrai** [comment]
This is done, the PR is up for review

**Comment by jzbahrai** [comment]
This was reviwed by Will and has been merged to staging
