### ISSUE TITLE
User interview with a service with a high bounce rate

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1267]
## Description
WHY are we researching? & WHAT are we researching?
[See planning card
](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1257)

VALUE created by the research
- We have **a little bit more** data to inform bigger study on bounce rate in July
- We can nudge this client a little bit on bounce rate
- We can learn **a little bit** about how people use the dashboard

## Documentation and Artifacts
[Facilitation guide](https://docs.google.com/document/d/1sWNMVPE_sUIwz7fBSRCsVnG2aZPLDsn7XwgGFHuA_j4/edit#heading=h.7a3ognz47ewb)
[Interview notes](https://docs.google.com/document/d/1sWNMVPE_sUIwz7fBSRCsVnG2aZPLDsn7XwgGFHuA_j4/edit#heading=h.eujctouil4fw)

## Acceptance Criteria

- [x] Interview conducted (Aug 10)
- [x] Notes are summarized and shared with designers

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

**Comment by yaelberger-commits** [comment]
User is away until August

**Comment by adriannelee** [comment]
Prepared a prototype to share during the interview because they haven't had a high bounce rate in the past 24hrs!

**Comment by adriannelee** [comment]
Rescheduled to tomorrow - Aug 10.

**Comment by yaelberger-commits** [comment]
User interview was completed Aug. 10. 
Notes here: https://docs.google.com/document/d/1sWNMVPE_sUIwz7fBSRCsVnG2aZPLDsn7XwgGFHuA_j4/edit#heading=h.eujctouil4fw

**Comment by yaelberger-commits** [comment]
This can likely be moved to done now. Notes have been shared with the team and summarized
