### ISSUE TITLE
Tracking French issues

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1270]
As a Francophone user, I need to parity with the English experience using Notify.

WHY are we building?
We notice issues in the French from time to time.

WHAT are we building?
A way to track these issues.

VALUE created by our solution
We'll be able to identify the appropriate time to address these issues and their priority.

## Documentation and Artifacts

Good docs, figma mockups, ADRs, screenshots etc.

Tracking document: https://docs.google.com/spreadsheets/d/1qDG7IqWHwhd_85BNHWoh3C-QnrnWFaWymdLBdJLHaLY/edit#gid=0

**Comment by adriannelee** [comment]
@YedidaZalik Would this card be considered done now? Since there is a way to track.

**Comment by yaelberger-commits** [comment]
Closed as we have a way to track
