### ISSUE TITLE
Dev: Email daily limits Implementation

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1273]
## Description

As a user I want to build the MVP for the email daily limits.

## Documentation and Artifacts

TODO: Post new zenhub issue

## Acceptance Criteria

- [x] Determine default daily email limit **10,000**. Put this in as a configuration and one that can be updated. This needs to be on a service level, so it cannot be configured through the usual Config object.
- [x] Honour legacy services with a higher daily limit
- [x] Feature flag to be able to turn this feature on or off
- [x] Global daily notification limit is retired
Use the new designs to retire this limit (hide it behind a feature flag)
- [x] Database column is renamed to email limit from notification limit (not doing this one)
Renaming columns can lock the DB, maybe add a new column. Decide on the most efficient psql option that will not take the site down.
- [x] ~Relocate the daily limit check from the celery to the API entry door like we did for our SMS parts work~
- [x] Move new _email_ daily limit and SMS daily limit in settings under each respective heading (no mockup for this)

**Notes from Story Refinement** https://docs.google.com/document/d/1DRnDodsCiaXHTeVlKVpWDeDtO5wOrp3gMGTTfS_yaIY/edit
## QA
- [x] Tested in Staging
- [ ] You only get email emails when you reach the daily email limit or the 80% threshold, not the SMS email or the global email

**Comment by adriannelee** [comment]
Jumana started working on this, will continue on the last couple of ACs today.

**Comment by smcmurtry** [comment]
PR up for API side, ready for a review. Admin PR - working on fixing tests, may need some more work. Will chat with another dev re: the admin PR today.

**Comment by smcmurtry** [comment]
Jumana - PRs are done, would like to merge to staging. Waiting for a release to happen before merging.
