### ISSUE TITLE
Design: Email daily limit UI

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1274]
## Description

As a user, I need to be able to view my daily email limit, so that I can request more or understand why I get an email when sending many emails. 

WHY are we building?
There is a daily sms limit, a notification limit, but no email daily limit.

WHAT are we building?
Removing the daily notification limit and creating a daily email limit. Aligning email limit with current sms limits. 

VALUE created by our solution
Setting things up to make it easy to track and respect both daily limits.

## Documentation and Artifacts

Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria

Scope 
- [x] Review applicable findings and insights from SMS limits testing (settings page and email warning) and apply to this feature as well
- [x] Design content for the email templates [#935](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/935)
- [x] Make sure translation exists for settings label or create one. 
- [x] Figma designs : Service setting page updates
- [x] Figma designs : Emails are updated with the new content (can work of this PR : https://github.com/cds-snc/notification-api/pull/1954, needs to be updated with template history as well similar to this PR: https://github.com/cds-snc/notification-api/pull/1734/files) 
- [x] Figma designs : Review page updated

**Notes from Story Refinement** https://docs.google.com/document/d/1DRnDodsCiaXHTeVlKVpWDeDtO5wOrp3gMGTTfS_yaIY/edit

## QA
- [ ] Tested in Staging
- [ ] You only get email emails when you reach the daily email limit or the 80% threshold, not the SMS email or the global email

**Comment by YedidaZalik** [comment]
Adapting from SMS limits in a new page called [Email limits (July 2023)](https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?type=design&node-id=1220-9527&mode=design&t=DD2Psu6ZbXbsPfyb-0)

**Comment by YedidaZalik** [comment]
Finished 2nd pass at figma file

**Comment by adriannelee** [comment]
Will review during dev-design review

**Comment by YedidaZalik** [comment]
Marie-Sophie hoping Simon can review the translation today.

**Comment by yaelberger-commits** [comment]
Went through screens in last dev-design review, ready to hand off to devs

**Comment by smcmurtry** [comment]
PR up for the new email content, almost ready for review but I need to sort out a database error first.

**Comment by amazingphilippe** [comment]
Created additional designs with Steve's feedback. We can do a quick review this week or next week.

**Comment by whabanks** [comment]
To figure out if we need translations.

**Comment by amazingphilippe** [comment]
No further translations needed. 
@amazingphilippe to create a unified set of limit screens for future reference.
