### ISSUE TITLE
Dashboard auto update is broken [bug-bogue]

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1276]
## Describe the bug 

The dashboard auto update feature is broken since the release of bounce rate V1.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major

## To Reproduce

Steps to reproduce the behaviour:

1. log in to production or staging
2. visit your service dashboard
3. Send a bulk email job through the API
4. Observe that the total emails sent does not update until you refresh the page

## Expected behaviour

As sends occur, the dashboard should auto-update the total emails sent, total sms sent, etc so that the user does not need to refresh the page. You can observe this feature working by taking the following steps:

1. check out an [older version](https://github.com/cds-snc/notification-admin/commit/cea64cc01746d3a57a515ab205780396ce91e83a) of the admin codebase
2.  set `FF_BOUNCE_RATE_V1 = False` and `API_HOST_NAME=https://api.staging.notification.cdssandbox.xyz` in your .env file
3. start admin, and log in, visit your service dashboard
4. send a bulk email job via api
5. the total emails sent will be updated automatically after a few seconds (4 seconds in my test)

## Impact

Impact on Notify users:
Worse user experience

## Additional context

I discovered this while doing some testing for the bounce rate v1.5 release.

## QA Steps

- Log into Staging, visit your service dashboard, take not of how many emails you have sent this week
- Open a 2nd browser tab with the same service dashboard
- send yourself an email using the 2nd tab
- switch back to the 1st tab, and do not refresh 
- verify that the "email sent" total increases by 1

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1276?planning-poker) with Zenhub @andrewleith @jzbahrai @smcmurtry @whabanks

**Comment by smcmurtry** [comment]
I've investigated some more and I introduced this bug with the layout change PR: https://github.com/cds-snc/notification-admin/commit/f8b9dbd5dbd69b73e163ae283030e189467868b6

**Comment by smcmurtry** [comment]
Reviewed by Jumana, merged and deployed to Prod. Ready to be QA'd.

**Comment by adriannelee** [comment]
QA'd by me, LGTM! Moving to Done.
