### ISSUE TITLE
Product updates MVP

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1279]
## Description
As a Sender, I need to be able to access the history of product updates so that I can update myself when I need to. 

WHY are we building?
- When we make an update to the product our only way of updating our clients is to send out an email. In the past, we've heard from some clients that it is irrelevant information to them.
- However, we know there are also clients who want to be updated about changes to the product.

WHAT are we building?
- GC Articles page where we can post product updates.
- Link to this page from the dashboard

**New Admin page**
- Form for creating, publishing and updating a "new features post" to inform users of recent updates
- Form fields will be stored in the DB. Relationship is 1:1, we will store only the latest "version" of the post in the DB.
- e.g. If a post is created, published, and then edited, we will overwrite the existing post in the DB
- Once published, we want to track and store if the user has dismissed the post on their dashboard or not or not
- Publishing pushes the change to users's dashboards
- Saving will update the content of already published posts and will be reflected on the dashboard for users who have not dismissed the post yet

**Dashboard**
- New section above the H1 on the dashboard will display "New Feature" posts
- Only the most recent "New Feature" post will be displayed to the user
- Dismissing the post is account wide, if the user navigates to another of their services after dismissing they will not see the same update again
- New standalone page to view "New Features" history

VALUE created by our solution
- Annoy fewer users
- Eventually, people can sign up to be notified when there is a new update.

## Documentation and Artifacts
- Story map: https://miro.com/app/board/uXjVO6TPyIs=/?moveToWidget=3458764559294030291&cot=14
- [Figma mockups, flows and annotations](https://www.figma.com/file/vA5P3VrBsiPCZEvVtCoXbc/Product-updates?type=design&node-id=0-1&mode=design)

Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
When we launch a new feature, current clients can find information about it

- [x] Pair with a dev to get a sense of the complexity of our MVP, and then readjust and work through any issue. I’m wondering about how we deal with super infrequent users, for example.
- [ ] For the process: With the current design, we also need to create an image, probably define how long this box shows up, etc. Then I want to have a sense of how we can coordinate dev and design each time we do an update.
- [x] There must also be dev steps to go through and it would be good to create some process flow that we can follow for each update
- [x] Design works for both English and French updates
- [x] The feature is designed with a11y in mind

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Story map looks great so far. I added a few comments to the project context

**Comment by adriannelee** [comment]
Worked on the MVP design a little more and added to the storymap a little more. [Read the article that Yedida shared](https://userpilot.com/blog/product-updates-guide/).

**Comment by adriannelee** [comment]
I reviewed the brainstorm/draft with Yedida and posted for review from Phil and Jimmy P

**Comment by smcmurtry** [comment]
Reviewed by Jimmy P, we'll do a quick review during design/dev this week.

**Comment by smcmurtry** [comment]
Phil has reviewed this
Phil - a few things to think through still
Andrew will join a meeting on this to give some input

**Comment by adriannelee** [comment]
Phil, Andrew, and I met today to go through some more details of the MVP design. We think we landed in a good place to share with the devs at dev-design review next week. I prepared some notes for the demo at Platform Townhall next week and Phil worked on a mockup of the Admin UI (how we would create an update)

**Comment by yaelberger-commits** [comment]
Andrew provided a few stats for Phil and Adrianne. 
Comment from Adrianne in Figma for Andrew

**Comment by adriannelee** [comment]
Prepped the design for dev-design review tomorrow!

**Comment by YedidaZalik** [comment]
No further comments from team. Prepped translation screen. Phil and I will meet Monday morning to make sure I've done it properly and then I'll send to translation.
https://www.figma.com/file/vA5P3VrBsiPCZEvVtCoXbc/New-features-%7C-Nouvelles-fonctionnalit%C3%A9s?type=design&node-id=477-1767&mode=design&t=SAtdpmfFOpRdhQF0-0

**Comment by amazingphilippe** [comment]
Designs handed off to Marie-Sophie for translation (same link as above)

**Comment by amazingphilippe** [comment]
Dev design review surfaced misalignment. [Documented in Figma](https://www.figma.com/file/vA5P3VrBsiPCZEvVtCoXbc/New-features-%7C-Nouvelles-fonctionnalit%C3%A9s?type=design&node-id=533-4662&mode=design&t=yEhl5cn2wZd0vyTd-4)

Will need more refinement, all the devs, designers, PM must be present. Moving back to backlog.

**Comment by yaelberger-commits** [comment]
We have scoped this down further for first release to just GC Articles page, first post, and a spot in the footer for discoverability. We will iterate after this first MVP to improve discoverability following more insights on navigation for Notify
