### ISSUE TITLE
API 500 error when scheduled_for JSON field contains timezone offset

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#1282]
## Describe the bug 

A 500 HTTP response occurs when a user of the API specified a [valid ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) date format for a bulk POST request sent to be scheduled later. While the [example in our documentation works](https://documentation.notification.canada.ca/en/send.html#optional-arguments) with the proper date+time format, it also mentions ISO-8601 is supported but that isn't true when a user declared a time offset to represent the timezone.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

Current dev assessment ranges from a SEV-3 or SEV-4, considering that not many people uses this feature through the API. On the other hand, for users who do use this feature, it is broken if they specify the wrong date time. That said, they should get an error message telling them something went wrong, but with a confusing message that does not explain why. That provides a bad UX on the API front.

## To Reproduce

1. Prepare a bulk POST request through the GCNotify API.
2. For the `scheduled_for` field, specify an ISO formatted date time that has an offset to represent the timezone, such as `2023-07-20T19:37:50-05:00`
3. Send the payload to GCNotify.
4. Check in CloudWatch the  error.

Example of a POST request for sending a bulk which contains a `scheduled_for` field with a timezone offset:

```
{'name': 'send 8',
 'rows': [['email address'],
  ['success@simulator.amazonses.com'],
  ['success@simulator.amazonses.com'],
  ['success@simulator.amazonses.com'],
  ['success@simulator.amazonses.com'],
  ['success@simulator.amazonses.com'],
  ['success@simulator.amazonses.com'],
  ['success@simulator.amazonses.com'],
  ['success@simulator.amazonses.com'],
  ['success@simulator.amazonses.com'],
  ['success@simulator.amazonses.com']],
 'scheduled_for': '2023-07-20T19:37:50-05:00',
 'template_id': '22c4fa4b-5108-4803-aee4-6ef6231c501f'}
```
The unexpected error response from the API call will report a 500 HTTP response, mentioning a type error:

```
FAILED: post to v2/notifications/bulk failed
{'status_code': 500,
 'errors': [{'error': 'TypeError', 'message': 'Internal server error'}]}
```

The CloudWatch logs will report on this TypeError but with more information:

```
TypeError: can't compare offset-naive and offset-aware datetimes
```

## Expected behavior

There are a few options:

a. An error message when a user provides a datetime with hour offset to represent a timezone. We would need to change the documentation though to mention that GCNotify does not actually support ISO-8601 but rather, date time with no timezone provided, but expected to be UTC time.
b. GCNotify accepts datetime with hour offset and handle it gracefully. The bulk API would return a 200 response class success message and properly schedule the bulk notification based on the user provided timezone reported in the `scheduled_for` JSON field.

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: Confusing user experience and potentially unable to use the API until they can figure out the issue.

Impact on Recipients: No messages received as unable to prepare the bulk send through the API.

Impact on Notify team: More support tickets and lower trust in our product.

## Additional context

From the `datetime` Python module perspective which processes the `scheduled_for` field and compare it to the current UTC time, an offset naive date time is one without timezone. Internally, we compare the user-provided timezone date time with one that GCNotify that has none, hence an error occurs.

It is possible to convert from an aware datetime to a naive one as explained in [this StackOverflow post](https://stackoverflow.com/questions/5452555/converting-timezone-aware-datetime-to-local-time-in-python). 

It is recommended to make some research prior to take any route with conversion to make sure that we will properly handle a user provided timezone, if we go this way. For example, the [datetime documentation](https://docs.python.org/3/library/datetime.html) explicitly states:

> With sufficient knowledge of applicable algorithmic and political time adjustments, such as time zone and daylight saving time information, an aware object can locate itself relative to other aware objects. An aware object represents a specific moment in time that is not open to interpretation. 1

> A naive object does not contain enough information to unambiguously locate itself relative to other date/time objects. Whether a naive object represents Coordinated Universal Time (UTC), local time, or time in some other timezone is purely up to the program, just like it is up to the program whether a particular number represents metres, miles, or mass. Naive objects are easy to understand and to work with, at the cost of ignoring some aspects of reality.

A few more resources:

* [What’s naive and dangerous about Python’s Datetime objects?](https://news.ycombinator.com/item?id=22965362) Excellent read on hackernews that mentions pitfalls of datetime, timezone, and using offsets or local "naive" time.
* [Why naïve times are local times in Python](https://blog.ganssle.io/articles/2022/04/naive-local-datetimes.html)
* [Timezone in Python: Offset-naive and Offset-aware datetimes](https://vinta.ws/code/timezone-in-python-offset-naive-and-offset-aware-datetimes.html)
* [datetime — Basic date and time types](https://docs.python.org/3/library/datetime.html)

**Comment by yaelberger-commits** [comment]
From @jimleroyer 
At the moment, our code does not properly support ISO 8601 and this card raises this. Adding to the documentation that we support it for bulk send would raise this issue even more, as the documentation (along with the missing reference) does not align with what we currently support.
A potential fix would be to fix the documentation, but to tell that we do not support ISO 8601, but simply accepts datetime with no time zone information (with hour offset) set at UTC time. Hence an adjustment to the documentation along with a proper error response when a user tries to send a datetime with time zone could be a solution, instead of proper ISO 8601 support.

**Comment by smcmurtry** [comment]
I'll do some work on this card as part of my on-call duties.

**Comment by smcmurtry** [comment]
Reviewed by Will. Merged and deployed in Staging.

**Comment by smcmurtry** [comment]
Andrew to QA.

**Comment by jimleroyer** [comment]
What's the resolution to fix this? Any link to the PR?

**Comment by andrewleith** [comment]
@jimleroyer its https://github.com/cds-snc/notification-api/pull/1942
