### ISSUE TITLE
2023 Update to internal onboarding

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1285]
## Description
As a new team member on Notify, I need to be able to do quickly onboard so that I can get started on the team. 

WHY are we building?
- Docs linked in the Github "[Onboarding] ..." card template were compiled in 2021 and there's some outdated information, especially on the design and policy-side.
- New team members may also be onboarding to CDS and/or government and that is a lot of information.
- Many of the links lead to a list of links, which lead to a list of links.

WHAT are we building?
- New Onboarding card template, focusing on the design and policy docs

VALUE created by our solution
- Less overwhelming for new team members
- Better product work

## Documentation and Artifacts
- [Current card template ](https://github.com/cds-snc/notification-planning/blob/main/.github/ISSUE_TEMPLATE/-onboarding--welcome-a-new-team-member.md)

## Acceptance Criteria
- [ ] The docs remain only accessible to CDS members (since Github is public)
- [ ] There isn't outdated info on the design
- [ ] There isn't outdated info on the policy docs
- [ ] Information (minus the dev info) is consolidated so that there aren't more than 10 docs to review in total. 
- [ ] Refer to information that is public where available so that we're more inclined to keep the public information updated (e.g. Product overview on Github)

**Comment by adriannelee** [comment]
PR is up, asked for reviews from each discipline lead https://github.com/cds-snc/notification-planning/pull/1289/files

Policy 101 doc should be updated by the end of the week

**Comment by yaelberger-commits** [comment]
Yael reviewed

**Comment by yaelberger-commits** [comment]
Phil went through, some design documentation is out of date. Can be updated in the future.

**Comment by yaelberger-commits** [comment]
Jumana reviewed

**Comment by yaelberger-commits** [comment]
Policy 101 deck still in progress, waiting for review by Nisa

**Comment by adriannelee** [comment]
(Moving to Blocked since it's being reviewed by someone external to our team)

**Comment by mtoutloff** [comment]
Notify Policy 101 deck reviewed and updated. Will need to update again soon given the transfer to ESDC
