### ISSUE TITLE
500 error in notification-admin when visiting `/contact?current_step=message` directly [bug-bogue]

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1286]
## Describe the bug 

We got a 500 error in notification-admin when someone visited `/contact?current_step=message` when they were missing some data from their session from the previous step.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

Steps to reproduce the behaviour:

1. open incognito window and visit https://staging.notification.cdssandbox.xyz/contact
2. Fill in name and email
3. paste in the following url and hit enter: https://staging.notification.cdssandbox.xyz/contact?current_step=message

Steps 1 and 2 may not be necessary

## Expected behaviour

Either an error message or the user should be redirected to the 1st step again.

## Impact

Impact on Notify users: This is an edge case but it is not a great UX

Impact on Notify team:  Alarm noise

## Additional context

We have been getting 500 errors around the contact page for quite a while.

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1286?planning-poker) with Zenhub @whabanks

**Comment by whabanks** [comment]
I put up a draft PR for this, the work is mostly done. Tests need to be written and manual testing done to ensure no regressions have been introduced.

**Comment by whabanks** [comment]
Andrew and/or maybe a core team member to review.

**Comment by yaelberger-commits** [comment]
I've asked @jimleroyer if he's able to review for us

**Comment by whabanks** [comment]
@smcmurtry to review.

**Comment by smcmurtry** [comment]
Approved, looks great! This comment describes the testing I performed: https://github.com/cds-snc/notification-admin/pull/1633#pullrequestreview-1599091727

**Comment by yaelberger-commits** [comment]
some observations from QA in Staging
When I ran test 2, and I navigated to /contact/organization-details I was not returned to the /contact page but rather brought to the Set up a demo page

Screenshot 2023-08-29 at 12.10.46 PM.png

All other tests passed as expected when I did them

**Comment by whabanks** [comment]
QA'd by @smcmurtry and @yaelberger-commits
