### ISSUE TITLE
Add confirmation banner when a user successfully changes a setting for their service

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1290]
## Description
As a GC Notify user, I need to be able to know I successfully changed one of my service settings so that I can avoid hitting the back button and trying to resubmit the change, resulting in an error message 

WHY are we building?
Users can get error messages if they try to change their setting again, if they've already changed it 
We don't have any confirmation message when you change a service setting letting the user know they were successful or what to do next. 

we were able to reproduce this on staging:
1. go to your service settings page
2. change your service’s name
3. on the confirm page you enter your password and submit
4. the service name is changed successfully and you are now back on the settings page
5. click the browser back button
6. re-enter your password and submit the form
7. observe that you get a 500 error page “We are experiencing technical difficulties”

WHAT are we building?
Confirmation messages/banner when a user successfully changes a service setting like service name

VALUE created by our solution
Users will get confirmation if they successfully change a service setting and will be less likely to trigger a 500 error page

## Documentation and Artifacts
https://gcdigital.slack.com/archives/CNWA63606/p1690298607066239

## Acceptance Criteria
Given a user changes a setting for their service using the Settings page "Change" option, after they submit their password and confirm the change, then they see a confirmation banner that their change was made successfully. 

- [ ] Confirmation banner added after Service name is changed
- [ ] Confirmation banner added after Sending email address name is changed
- [ ] Confirmation banner added after Sign-in method is changed
- [ ] Design content for generic success message. 
- [ ] 

![Screenshot 2023-07-25 at 3.36.13 PM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/99a49c4a-4cc8-45c4-9499-6101db2ef6c7)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps
- [ ] 1. go to your service settings page
2. change your service’s name
3. on the confirm page you enter your password and submit
4. the service name is changed successfully, you see a confirmation banner that says successfully updated, and you are now back on the settings page

**Comment by yaelberger-commits** [comment]
Yedida provided some content help

**Comment by yaelberger-commits** [comment]
Phil to check if we have a FR version of the content already

**Comment by smcmurtry** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1290?planning-poker) with Zenhub @smcmurtry

**Comment by smcmurtry** [comment]
Merged yesterday, now live. Tested and QAd.
