### ISSUE TITLE
Review problems content Figma

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1292]
## Description
Review problems content Figma

Update content on the “Review problems” screen. The intro content was changed and this has to happen in the code. We added it to the UI changes section, but at this point, we could also tackle it soon after the release with no big risk involved

## Documentation and Artifacts
Dev frame: https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?type=design&node-id=1641-14553&mode=dev

## Acceptance Criteria
- [x] changes made in figma to the intro content are changed in the code

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps
- [x] Changes in En and FR are the same on our pages as they are in Figma

**Comment by yaelberger-commits** [comment]
Phil shared with Andrew, Andrew made a PR, ready for release this morning

**Comment by adriannelee** [comment]
LGTM!
