### ISSUE TITLE
Change the SMS daily limits from fragments back to text messages

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1298]
## Description
As a Sender, I need to be able to track my daily limits without learning a new concept so that it's easy for me to stay under my limit. 

WHY are we building?
[Because ‘daily limits’ is something we need to educate and create awareness around, educating Senders on ‘Fragments’ could make the design more challenging to execute well.](https://airtable.com/appWwAmHwDLtpIyko/tblqw9ekiSqDmMTHa/viwlUUKmOBaY5TWch/recZjWC7xfFhckQLm?blocks=hide)

WHAT are we building?
- Looking through the design (authenticated pages, unauthenticated pages, API documentation, API error messages) to identify where we said 'fragments' and where a change is needed
- Determine what those changes are - tech and design
- Design those changes
- Hand-off to devs

VALUE created by our solution
- Reduce the amount of learning Senders have to do

## Documentation and Artifacts
Good docs, figma mockups, ADRs, screenshots etc.
- [Figma file](https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?type=design&node-id=1559-8505&mode=design&t=wanoGoqIwgjzyawl-0)
- [The work we did to include 'fragments' - especially the table in this doc](https://docs.google.com/document/d/12uyYHv1Z3JY6D7jphCzmIeNA1n2cao04xEuIjr49xLw/edit#) 
- [SMS limits V2 planning notes following research findings](https://docs.google.com/document/d/1lrDvKwHRwtm4gVgF0E-xKoY3J1UWQ-FeUybYEX3AbfU/edit#heading=h.p0fx9wp3omq8)

## Acceptance Criteria
On authenticated pages, unauthenticated pages, API documentation, and API error messages, Senders won't see the word 'fragments'. Their daily SMS limit will be counted using 'text messages'
- [x] Content referencing "fragments" is updated for Authenticated pages, unauthenticated pages, API documentation, and API error messages in English
- [x] Updates to English content are translated for Authenticated pages, unauthenticated pages, API documentation, and API error messages in French
- [ ] Dev implementation
- [ ] Inform Support of these changes (Ramya and Jimmy P)
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

## QA Steps
Ensure messages are updated in the following scenarios:
- [ ] Live service
   - [ ] Email
      - [ ] One off
      - [ ] Bulk
   - [ ] SMS
      - [ ] One off
      - [ ] Bulk
- [ ] Trial service
   - [ ] Email
      - [ ] One off
      - [ ] Bulk
   - [ ] SMS
      - [ ] One off
      - [ ] Bulk

## GC Articles Publish checklist
- [ ]  Supporting feature is released and unflagged
- [ ]  Create or update slug
- [ ]  Page content and slug is translated
- [ ]  Document links to and from the page
- [ ]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [ ]  If new page, add WAF rule
- [ ]  Create new page or update existing page content
- [ ]  Create or update translation to the page
- [ ]  Link translations by choosing an assigned translation
- [ ]  If new page, save as draft
- [ ]  If existing page, update the page
- [ ]  Post page in Slack for last minute reviews
- [ ]  On staging: Clear the cache through GC Notify's admin panel
- [ ]  On staging: Check links, images and language toggle
- [ ]  Give a heads up to the app-team channel once ready to publish
- [ ]  On staging and production: Clear the cache through GC Notify's admin panel
- [ ]  Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by yaelberger-commits** [comment]
Some data:
**Data question I’m hoping a dev can help me answer through a query:
What is the average character length of SMS messages sent through Notify?
How many SMS messages are 600 characters or more?**

- 947 sms templates
- AVG 175 chars
- MAX 612 chars
- MIN 3 chars

**Comment by adriannelee** [comment]
Started working on this today with Yedida and Phil, creating an inventory of the screens that would need to change when "fragments" is removed

**Comment by adriannelee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1298?planning-poker) with Zenhub @adriannelee @amazingphilippe @YedidaZalik

**Comment by adriannelee** [comment]
Yedida worked on the content for removing "Fragments" today and I did (a very quick) review. I think it's good for handoff? (other than translation)

**Comment by yaelberger-commits** [comment]
2 things next
1) Prototype is screenshots and we don't have the FR so will ask if we need to add more screenshots or get translations another way
2) Now using placeholder # for number of text messages (fragments to text messages) devs need to give us the number and number of characters 
1,000 text messages is the new daily limit
612 is the new character limit (to confirm)

**Comment by YedidaZalik** [comment]
Discussed with Marie-Sophie and agreed I'd tag her in Figma where we need French.
That's done now so it's ready for her translation.

**Comment by YedidaZalik** [comment]
Discussed at dev-design review and implemented decisions from the review.
Made the relevant changes to TOU EN and FR in GC Articles as Yael said that could go ahead before dev implementation.
Worked with Phil to tidy up screen for dev implementation.
We need to let Ramya and Jimmy P know that this is changing.

**Comment by yaelberger-commits** [comment]
@jzbahrai can you please update the checklist above so we can see that all AC is met?

**Comment by amazingphilippe** [comment]
Merged recent work about Daily limits and Email limits. [in Figma](https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?type=design&node-id=2044-7807&mode=design&t=PqjpMYZq50AmjN2c-4)

Even this isn't enough. Andrew mapped out all the states and conditions. We missed trial and live
>Ok test cases so far:

- Live service
  - Email
    - One off
    - Bulk
  - SMS
    - One off
    - Bulk
- Trial service
  - Email
    - One off
    - Bulk
  - SMS
    - One off
    - Bulk
    - 

Made a new pattern template to avoid this when working on the sending flows in the future: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbndWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa256967de068873b7b2423baee7aea547e5ffbc/image.png)

Can be found in Notify's Figma component library
