### ISSUE TITLE
Replace delivery status "sending" with "in transit" in API documentation

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1301]
## API documentation uses "sending" in contexts where it should now be "in transit"

Awhile back we changed the name of the delivery status previously called "sending" to "in transit" in the UI. But in the API documentation,  there's at least one instance of "sending" in a context where it should now be "in transit".  

New

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

Steps to reproduce the behavior- there is likely a quicker way to do this but I'm not a dev so I don't know :)

1. Go to 'API documentation.'
2. Search for 'sending'
3. Check whether the word is used to refer to a delivery status. If so, change it to  'in transit'

## Expected behavior

"In transit" replaces "sending" as delivery status in API docs.

## Impact

Consistency in how GC Notify describesdelivery status

If applicable

Impact on Notify users: developers and non-developers will use the same term reducing confusion on teams

Impact on Recipients:n/a

Impact on Notify team: n/a

## Screenshots
![Screenshot 2023-08-01 at 3.20.39 PM.png](https://images.zenhubusercontent.com/614b9f22b18cf806c628a310/3aee9f56-e264-4393-8a68-923660ba8ba2)

**Comment by whabanks** [comment]
@smcmurtry to review.

**Comment by smcmurtry** [comment]
Already reviewed by Jumana, I will QA instead.

**Comment by smcmurtry** [comment]
The change of "Sending" to "In Transit" is actually a change of the `status_description` and not the `status`:  https://github.com/cds-snc/notification-api/blob/main/app/models.py#L1913-L1914

`status_description` is what is displayed in the Admin UI. API users can get both the `status_description` and the `status`, which contains more detail. 

I think we need to change the headings in the documentation table to make this less confusing: the tables explain the "Status Description" not the "Status". I left a comment here: https://github.com/cds-snc/notification-documentation/pull/131#pullrequestreview-1599126513
