### ISSUE TITLE
Trying to send above daily email limit can cause admin to 500

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1302]
## Describe the bug 

When you try to send more emails than you're allowed to (ie more than daily limit), you can get a 500 "having difficulties" screen instead of the red "this will put you over your limit" error

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

Steps to reproduce the behavior (this was done on staging):

1. change your daily limit to 40000
2. send an email ("send to yourself")
3. upload a file of 40000 emails
4. see that admin accepts the file
5. click "send now"
6. see the 500 screen. There will also be a 500 in the admin logs, and a "send too big" error in the api lambda logs

## Expected behavior

admin tells you that the file will put you over your limit

## Impact

users will not know what is wrong and think Notify is down or broken. They will retry and get the same results.

**Comment by andrewleith** [comment]
Admin seems to validate if you are trying to send over your daily limit:
![image](https://github.com/cds-snc/notification-planning/assets/823749/f0dace31-fbc5-4625-9dc4-2528a6768aaa)

But not if you are over the amount left to send for a particular day.
