### ISSUE TITLE
Public site sets expectations about daily/annual limits

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1305]
## Description
As a potential client, I need to be able to understand the max numbers of emails and text messages I can send with Notify so that I can decide to use Notify or not. 

WHY are we building?
- [We'll need to provide education about limits upon/before account creation to increase awareness so that this is information that they look out for when they send messages.](https://airtable.com/appWwAmHwDLtpIyko/tblqw9ekiSqDmMTHa/viwlUUKmOBaY5TWch/recGMaJFY5nPdXVTl?blocks=hide)

WHAT are we building?
- Updates to the public site (unauthenticated) to better communicate that there are daily/annual limits (how many emails, SMS, and how many characters within templates)

VALUE created by our solution
- Better likelihood that Senders have the right expectation when creating an account and using GC Notify. This prevents disappointment and wasted time for Senders.
- Fewer support tickets asking about this from people who don't have an account

## Documentation and Artifacts
https://docs.google.com/document/d/1NunyGV_vldNeYR3HuhjW2HORNtqIxWQdn7aeFp4W2sk/edit

## Acceptance Criteria
When a public servant is trying to evaluate whether GC Notify will be useful for them, they can confirm this information without creating an account or contacting support.

- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- [Daily limits is a blocker they would like to prevent](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recw4wIuZHzch5oRq?blocks=hide)
- [None of the participants considered daily limits as part of their sending process.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recQd6Io3KWeCnqwX?blocks=hide)

## QA Steps
- [ ] Tested in a realistic production scenario

## GC Articles Publish checklist
- [ ]  Supporting feature is released and unflagged
- [ ]  Create or update slug
- [ ]  Page content and slug is translated
- [ ]  Document links to and from the page
- [ ]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [ ]  If new page, add WAF rule
- [ ]  Create new page or update existing page content
- [ ]  Create or update translation to the page
- [ ]  Link translations by choosing an assigned translation
- [ ]  If new page, save as draft
- [ ]  If existing page, update the page
- [ ]  Post page in Slack for last minute reviews
- [ ]  On staging: Clear the cache through GC Notify's admin panel
- [ ]  On staging: Check links, images and language toggle
- [ ]  Give a heads up to the app-team channel once ready to publish
- [ ]  On staging and production: Clear the cache through GC Notify's admin panel
- [ ]  Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by yaelberger-commits** [comment]
I would recommend we try making these changes on the "Features" page as a start

**Comment by YedidaZalik** [comment]
Started content work in [google doc](https://docs.google.com/document/d/1aF28b15uHAirm0s2cVbY-T3Pb1Wujixkq5yOEyxEDQU/edit)

**Comment by yaelberger-commits** [comment]
@yaelberger-commits is reviewing

**Comment by YedidaZalik** [comment]
shared document so Yael can review

**Comment by YedidaZalik** [comment]
Yael reviewed

**Comment by YedidaZalik** [comment]
Ready for localization
https://docs.google.com/document/d/1aF28b15uHAirm0s2cVbY-T3Pb1Wujixkq5yOEyxEDQU/edit?tab=t.0#heading=h.sg8sntkn01ia

**Comment by YedidaZalik** [comment]
YZ to send to MSB as an email

**Comment by andrewleith** [comment]
- Annual limits work is being prioritized by translation team

**Comment by yaelberger-commits** [comment]
We'll release these content changes along with the feature. We'll do a release checklist meeting to prepare and plan

**Comment by YedidaZalik** [comment]
Moving to backlog until we're ready to update public pages for release

**Comment by YedidaZalik** [comment]
Updated content on Home and Why GC Notify pages in French and English
Cleared cache and changes are showing
Was not able to enter bullets on Why GC Notify EN and FR pages and used dashes.
Need help to enter bullets and then need someone to review

**Comment by yaelberger-commits** [comment]
I QA'd both pages EN & FR all good!
