### ISSUE TITLE
Character max for SMS templates is described

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1307]
## Description
As a SMS Sender, I need to be able to know the character limit for SMS templates so that I can prevent running into errors.
(This card excludes describing character limits for emails because the threshold for the character limit is much higher for emails)

WHY are we building?
- We were thinking of a character counter. But, character counting is complicated (variables) and if we're not using 'fragments', it doesn't help solve a known problem. 
- It can still be frustrating for people to run into preventable errors. This can be avoided by at least letting them know what the approximate character count should be (612 characters, including accents and symbols, but excluding variables)

WHAT are we building?
- Hint text at the SMS template creation stage

VALUE created by our solution
- Preventing errors for Senders

## Documentation and Artifacts

- [Figma](https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?type=design&node-id=2115-770&mode=design&t=xJH8TzqIL3FJ6GWd-4)

## Acceptance Criteria
- [x] (English) Hint text is shown for people creating SMS templates.
- [x] (French) Hint text is shown for people creating SMS templates.
- [x] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [x] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- [Not clear if there's a character limit for SMS](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwtsq6Gy7TDVGL36/rechb1zMfsGN4u9CH?blocks=hide)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1307?planning-poker) with Zenhub @adriannelee @amazingphilippe @YedidaZalik

**Comment by amazingphilippe** [comment]
Set up the template screen in Figma using the sending pattern. Ready to work on the content.

**Comment by YedidaZalik** [comment]
Yedida worked on this today and will review on Monday with fresh eyes, make any changes and seek feedback

**Comment by whabanks** [comment]
Phil to sync with Yedida to prepare for Nick.

**Comment by amazingphilippe** [comment]
Received and addressed feedback from Yael and Adrianne. Prepared annotations for the dev design review and hand-off.

**Comment by amazingphilippe** [comment]
Created dev card #1334

**Comment by YedidaZalik** [comment]
Sent to translation today
https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-[…]type=design&node-id=2354-4573&mode=design&t=RoJ26o6tzZUG4U06-4

**Comment by amazingphilippe** [comment]
Translations are integrated in Figma and ready for dev.

**Comment by yaelberger-commits** [comment]
Adrianne will update Airtable today
