### ISSUE TITLE
Daily limit warning email describes how many are left

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1308]
## Description
As a Sender receiving a warning email about my daily limit, I need to be able to know how many more I can send today without doing math so that I can quickly decide if I need to request more. 

WHY are we building?
- Our current warning email describes the total daily limit and doesn't say how many they've sent so far and how many are left.
 
WHAT are we building?
- Email template that gets sent (to everyone in a service team?) when their service reaches 80% of their daily limit.

VALUE created by our solution
- Better UX

## Documentation and Artifacts
Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given a service reaches 80% of their daily limit, the warning email they receive tells them how many more they can send in a day. 
- [x] Bilingual email template is created

**Comment by yaelberger-commits** [comment]
A quick chat with devs during refinement needed to understand the lift involved in grabbing that data for the email

**Comment by yaelberger-commits** [comment]
I recommend we start here for Daily Limits V2 Release 2

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1308?planning-poker) with Zenhub @jzbahrai

**Comment by YedidaZalik** [comment]
Yedida worked on this today and will review on Monday with fresh eyes, make any changes and seek feedback

**Comment by YedidaZalik** [comment]
After several versions each with slightly different content, Phil and I prefer the same one and will likely finalize that one.

**Comment by YedidaZalik** [comment]
With Phil, implemented feedback from Yael and Adrianne. Ready for dev-design review.

**Comment by amazingphilippe** [comment]
Created dev card #1334

**Comment by YedidaZalik** [comment]
Sent to translation today
https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-[…]type=design&node-id=2354-4573&mode=design&t=RoJ26o6tzZUG4U06-4

**Comment by YedidaZalik** [comment]
Nick has translated this and Marie-Sophie will take a look before finalizing.
