### ISSUE TITLE
Broken link to "Updating contact information"

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1309]
## Broken link to "Updating contact information"

When you click on "Updating contact information" link from the Review email addresses page, it leads to a blank untitled page.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major

## To Reproduce

1. Go to the dashboard of a service with some problem emails
2. Click on the Review email addresses link
3. From there, try to click on the "updating contact information link"
4. See a new tab open that is a blank page with "untitled" in the tab

## Expected behavior

When you click on the "Updating contact information" link, it should open this page https://notification.canada.ca/keep-accurate-contact-information?lang=en

## Impact

If applicable

Impact on Notify users: Users can't access the link from within the UI when they need it

Impact on Recipients:

Impact on Notify team:

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1309?planning-poker) with Zenhub @jzbahrai @smcmurtry @andrewleith

**Comment by andrewleith** [comment]
The WAF rules have been updated in PROD and this link is now working.
