### ISSUE TITLE
SPIKE: Explore x-notify and see if we can provide a better end-to-end experience by collaborating 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1311]
## Description
As a GC Notify Sender, I need to be able to create and manage a distribution list, so that I can comply with regulations for subscribing/unsubscribing easily without friction. 

How might we provide a better end-to-end experience for our Senders who manage large distribution lists and require the ability for their users to subscribe and unsubscribe easily from their lists while ensuring their privacy and meeting bilingual and accessibility standards?

WHY are we building?
We have data and feedback that points to some of our Senders already using x-notify, or thinking we're the same service, or needing a way to manage a distribution list of subscribers, but we don't currently offer any solution for this, but we know x-notify exists.
WHAT are we building?
A weeklong time-boxed spike to explore the features of x-notify and see the feasibility of providing a better end-to-end user experience for Senders who manage a distribution list. 
VALUE created by our solution
We could open up more value and a more robust end-to-end offering if we can point to a distribution list management solution that is made in house in the GoC.

## Documentation and Artifacts
Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given we spend a week exploring x-notify, when we wrap up this spike, then we have made contact with the x-notify team, understand their offering and feature set and have an idea of the feasibility and value of collaborating more closely.

- [x] Meeting has taken place
- [ ] Meeting notes are available for the team
- [ ] Action items and any follow-up steps are determined

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

**Comment by yaelberger-commits** [comment]
From @patheard there’s also the List Manager API we (:max:) built a while ago to do distribution list management (subscribe, unsubscribe) and send through Notify.  It’s only used by Articles as far as I know.

**Comment by smcmurtry** [comment]
I started the process to set up x-notify locally. I was able to get it running with docker using these instructions: https://github.com/ServiceCanada/x-notify/blob/master/setup.md

I was able to add myself as a user via the mongo db command line in the docker container. However, I haven't yet been able to log in successfully to the app. I get the login form at this link: http://localhost:8080/api/v1/mailing/login, but submitting with the username and password I added hasn't worked.

**Comment by yaelberger-commits** [comment]
Expecting a meeting to be scheduled soon

**Comment by amazingphilippe** [comment]
Meting happening on Thursday

**Comment by amazingphilippe** [comment]
Jumana, Ioana, Yael and Mario met with x-notify. Learn their process, backlog. Debrief today. And mark this story as done. More work will happen in the future.

**Comment by yaelberger-commits** [comment]
Notes will be shared with the team today
