### ISSUE TITLE
Broken external link on terms page

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1313]
## Describe the bug 

On the terms page ([en](https://notification.canada.ca/terms) , [fr](https://notification.canada.ca/conditions-dutilisation)), there is a broken external link pointing to:
`https://datatracker.ietf.org/doc/html/draft-wilde-sms-uri-20#section-4`

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-4 Low

## Expected behavior

All links should be valid and working.

## Impact

Impact on Notify users:
- May seem unprofessional

Impact on Recipients:
- None

Impact on Notify team: 
- Low possibility of increased support requests

**Comment by andrewleith** [comment]
I think https://datatracker.ietf.org/doc/html/rfc5724#section-4 might be the correct link - could whoever added the link originally please verify? cc: @amazingphilippe  / @YedidaZalik

**Comment by YedidaZalik** [comment]
Yes, that's the correct link. I've updated it in GC Articles for both the English and French version. It's now directly properly on the authenticated pages, but not yet on the unauthenticated pages. Do we need to clear the cache?

**Comment by andrewleith** [comment]
Yes - I'll do that now!

**Comment by andrewleith** [comment]
✅ Done!

**Comment by whabanks** [comment]
Link was updated, cache may need to be cleared for it to show properly.
