### ISSUE TITLE
Prototype suspension (lo-fi)

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1314]
As a Notify client, I need to know when my service is/will be suspended so that I can take steps to recover it/prevent it.

Clients can get suspended from Notify for not complying with the Notify Terms of Use.

Using a very small prototype, we want to learn:
- What kind of language helps clients understand what limitations were placed on them, why, and what can help them prevent being blocked in the future?
- When they understand how to prevent suspension, how doable does it seem considering their circumstance?

# Acceptance criteria
- Prototype in English is drafted by Monday Aug 21
- Prototype in French is drafted by Monday Aug 21
- Prototype helps us learn during testing on the week of Aug 21 

# Docs

The Forms team brainstormed some ideas for suspension previous (no UI changes yet)
- [Adrianne's notes of the Forms Team docs](https://docs.google.com/document/d/1wkAUzAReENMQek9ifr1Grx8MQCu_Fm6M3fKyXWvtvTo/edit)

Docs from Forms:
- [Support documentation](https://docs.google.com/document/d/1mrtlVYWJLWmQXimHSPlBD-ATj0NVN0xHXrULh_cfh0o/edit)
- [Admin interface and notifications](https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=1427-52485&mode=design&t=aI7BvFeO9enyYpWw-0)
- [Tabletop exercise](https://miro.com/app/board/uXjVM2sNUkQ=/)
- [Deactivation flows](https://www.figma.com/file/Rbs7RPSDUhYeT7OCMF4o3G/Locking-out-and-deactivating-users?type=whiteboard&node-id=0-1&t=Y7NCUcTszqjCECRf-0)
- [Escalation path](https://docs.google.com/document/d/1CxfOUivb4tBtD-7Y2BZydM-r3rITgaz-q9OwbNz2_Fk/edit#heading=h.y31ww0fzwp07)
- [Policy guidance](https://docs.google.com/document/d/1uF5wGmh_AOEc7r9cITxRXRph52uA5efKN_Lig0WDLuY/edit#heading=h.ki5wyxlz4a13)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1314?planning-poker) with Zenhub @adriannelee @amazingphilippe @mariesophiebezert @YedidaZalik

**Comment by whabanks** [comment]
Yedida has several different versions for content. Will review and decide which version of content to use in story refinement. Synced with Anik to look at other implementations of account deactivation.

**Comment by adriannelee** [comment]
We landed on this email for the prototype https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?type=design&node-id=1894-180&mode=design&t=UPeKGDJaApiuCYvf-4

Email has been sent to translation
