### ISSUE TITLE
Conduct bounce rate testing

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1315]
Sessions conducted
- [x] EN1
~~- [ ] EN2~~
- [x] EN3
- [x] EN4
- [x] EN5
- [x] EN6
- [x] EN7
- [x] EN8
- [x] FR1
 
Notes tidied up [here](https://gcdigital.slack.com/files/UJ68BHYNA/F05NHFV55J7/29):
- [x] EN1
- [x] EN2
- [x] EN3
- [x] EN4
- [x] EN5
- [x] EN6
- [x] EN7
- [x] EN8
- [x] FR1

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1315?planning-poker) with Zenhub @adriannelee

**Comment by adriannelee** [comment]
First 3 sessions starting today!

**Comment by adriannelee** [comment]
3 completed yesterday, 1 more scheduled today. Will start finalizing notes and moving them to DoveTail today

**Comment by yaelberger-commits** [comment]
Moved to review as the sessions have been completed and now notes are being tidied up and then analyzed

**Comment by adriannelee** [comment]
Notes are all tidied up and I've tagged EN5-8 and FR1. Will continue tagging today.

Also moved the presentation to next Thursday!

**Comment by adriannelee** [comment]
Finished tagging all the notes yesterday. Today I did some sub-grouping for most of the tags and started writing some summaries for each. 😵‍💫

**Comment by adriannelee** [comment]
Separating out the analysis part of this to another card: https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1336
