### ISSUE TITLE
Create an inventory of all GCA pages

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1319]
Create an inventory of all GCA pages, wherever they may be linked to (so we can also scan them with Cypress)

Action item from this [incident on broken links ](https://docs.google.com/document/d/1L6z-ylYje7350PPJ4Jpa1U4pSRrFrAmmRMLVkPNPzdg/edit)

**Comment by whabanks** [comment]
[Inventory](https://docs.google.com/spreadsheets/d/1rvJX9C7M8Plvm0O9pb8n3BBr-TsShDa4rGrz-M7zpn0/edit#gid=794398354) finished during the related incident.

**Comment by yaelberger-commits** [comment]
@amazingphilippe when you have a chance can you review the inventory?

**Comment by amazingphilippe** [comment]
Looks complete! I added the "new-feature" ones in both languages. As a reference, WP is also able to generate a site map similar to this. We can use both to double check. Look for the draft called "Site map" in GCA admin.
