### ISSUE TITLE
Add validation for service name field in the frontend

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1325]
## Add validation for service name field in the frontend
When a Sender creates a service in GC Notify, the name of the service has a character limit of 255.

We need to validate and throw an error around name of a service when a Sender creates the service so that they do not create a service name that will get cut off because this fields is too long.

Acceptance Criteria:

- [x] When a service owner creates a service name with the name field longer than 255 characters, they see a validation error when they try to go to the next step
- [x] When a service owner creates a service with the Name field longer than 255 characters, an error message tells them that the name of their service is too long, needs to be less than 255 characters, and their service was not created.
- [x] The service owner understands that they will need to create a service name less than 255 characters to be able to create their service
- [x] The error message is available in EN in the EN UI an in FR in the FR UI (Contact @YedidaZalik for any content requirement, tell if there are no changes as well please)
- [x] A service owner cannot name a service to send notifications if the name field is longer than 255 characters
Current State:
When a user names a service
... And the name of the service is more than 255 characters
... The user is able to create that service but the name gets cut off

Expected behaviour:

- [x] A user receives a validation error when they try to name their service if the name field is longer than 255 characters, and they know that they need to shorten the name of the service before they can finish creating their service.
- [x] The user never gets to the part of the flow where they created their service with a service that has a name longer than 255 characters.

**Comment by yaelberger-commits** [comment]
Can use this previously closed card as reference since it was similar validation 
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1134

**Comment by whabanks** [comment]
Looks like we already have validation in place, both when we create a new service and when renaming an existing service.

### Change service name
Back end validation is in place, but there is no character limit on the field itself that prevents inputting more than 255 characters. This can be added.

<img width="638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemI5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab402286c27b8f117f86f4cb346831cff183319d/image.png" alt="image.png" />

### Create a new service
The field has a `255` character limit, preventing any input past that count.

<img width="658" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG45QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8baf2e047ab0820ce87e3ad686bdb1355c888517/image.png" alt="image.png" />

If the `maxlength` attribute is removed from the field, or modified to allow > `255` characters then back end validation catches it and returns a message

<img width="707" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejc5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0080916741aac274ecd26ce2a70ca3485ee2f148/image.png" alt="image.png" />

**Comment by whabanks** [comment]
PR is ready for review:

Before:
<img width="715" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODhDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b06a6be9b11669fd99a173d911287d4ee60488a7/image.png" alt="image.png" />


After:
<img width="632" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b779d41ddb88f8235b896fa79bab20bd15723af9/image.png" alt="image.png" />

**Comment by yaelberger-commits** [comment]
Jumana tested in Staging. Ready to merge
