### ISSUE TITLE
Recurring task: Check blazer queries for API keys monthly on the 1st of very month

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1327]
Recurring task: Check blazer queries for API keys monthly on the 1st of very month

We want to check how many old api keys have been revoked every month and how many still exist so we can track progress towards changing all the old ones over to the new format. 

The blazer queries will also help us update our distribution list for email reminders to clients to change their keys to the new ones.

**Comment by yaelberger-commits** [comment]
@jzbahrai I think we can now move this recurring task to done, because we won't need to monitor old keys once we've revoked all old keys

**Comment by andrewleith** [comment]
- Pretty much done, still a few remaining users; will be done  againtoday
