### ISSUE TITLE
Notify removes some french accents from SMS messages [bug-bogue]

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1330]
## Describe the bug 

For SMS messages, Notify converts many french accented characters to non-accented characters. This is visible both in the SMS message preview, and in the final message that the recipient sees.

Here is the relevant code: https://github.com/cds-snc/notification-utils/blob/main/notifications_utils/sanitise_text.py#L102

This should be a really easy fix, we would just need to add the missing characters to the list of allowed characters.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

SEV-2 Major

## To Reproduce

1. Log in to https://notification.canada.ca/
2. Create a text message template with the following characters: 
```
ç Ç
æ
ÉéÈèÀàÙù
Ëë
```
3. Observe that the preview displays some of the characters without their accents:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHBFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7369b02d0ab448957a6c525ebb4ce85c18964ff0/Screenshot%202023-08-28%20at%202.14.30%20PM.png)

4. Send the SMS to yourself and observe again that some of the accents are missing

## Expected behaviour

Notify should be able to send SMS containing all accented characters commonly used in the French language.

## Impact

Impact on Recipients:
Notify users cannot properly communicate via SMS in French. Accents are missing and this looks unprofessional.

## Acceptance Criteria
- [ ] Non-GSM-7 French characters are not downgraded when sending SMS messages.
- [ ] A Blazer query to monitor responses form SMS messages containing these non-GSM-7 French characters, so that we can know if this change results in an increase in blocked SMS messages

## Additional context

We should just be able to add the missing characters in as an exception, but we will have to do some testing to make sure that works as expected. Since these characters are not in the GSM-7 set of characters (See list here: https://en.wikipedia.org/wiki/GSM_03.38), inclusion of one or more of these characters will mean that the message will be sent using the UCS-2 encoding. UCS-2 SMS fragments have a maximum length of 70 characters. So allowing the use of these could increase costs associated with SMS sending.

Here is a good explanation from Twilio that corroborates some of the info in the GSM wiki article: https://www.twilio.com/docs/glossary/what-sms-character-limit

**Comment by yaelberger-commits** [comment]
Decision made to add the previously unsupported characters

**Comment by smcmurtry** [comment]
I reviewed and approved, ready to be merged after merge conflicts are fixed.

**Comment by yaelberger-commits** [comment]
Some changes to the PR needed to resolve conflicts, then ready for Staging and QA

**Comment by whabanks** [comment]
PR's have been merged and is now in staging. Ready for QA!

**Comment by yaelberger-commits** [comment]
Ready for QA in Staging

**Comment by jzbahrai** [comment]
tested
