### ISSUE TITLE
Notify allows sending of SMS over the 612 character limit if sent via CSV [bug-bogue]

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1331]
## Describe the bug 

When doing a CSV bulk send of text messages via the Admin site, it is possible to send SMS containing more than 612 characters.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

SEV-3 Minor

## To Reproduce

1. Log in to https://staging.notification.cdssandbox.xyz/
2. Create a new text message template containing a single variable: `((var))`
3. Save the template and click to send to many recipients
4. create a csv file like this:
```
phone number,var
your_phone_number,long_string_containing_700_characters
your_phone_number,long_string_containing_700_characters
your_phone_number,long_string_containing_700_characters
```
5. upload the csv file you created and send your messages
6. observe that no error messages are triggered and your phone recieves the sms messages containing more than the allowed number of characters.

## Expected behavior

We should show error messages and prevent the user from sending after the upload the CSV file. We could use error messages that appear on the problematic fields, like we do when an incorrect phone number is included:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakpGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a941022a7feb54fcdc32a8dbeb52ad2cd6773ab4/Screenshot%202023-08-28%20at%201.51.42%20PM.png)

## Impact

Impact on Notify users:
Users can send over the 612 character SMS limit

Impact on Recipients:
Recipients may receive messages that are longer than is appropriate for SMS. 

Impact on Notify team: 
Higher SMS costs than anticipated

**Comment by yaelberger-commits** [comment]
Escalating to high priority following discussions on the team

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1331?planning-poker) with Zenhub @andrewleith @whabanks

**Comment by whabanks** [comment]
Added inline error message for custom variable cells to indicate the message length limit. (Placeholder messages currently).

<img width="1137" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnAxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3d90028972cf6a7efa5de3d4d0863378b217196/image.png" alt="image.png" />

Next up is implementing the logic to validate that the variable length + template content length does not exceed the 612 limit, and maybe show a message indicating how many characters remain for variables. i.e. `612` - `length of their current template content` = `chars remaining for variable content`.

**Comment by whabanks** [comment]
During testing of the initial code, before bringing the PRs out of draft, I ran into an issue where you could still exceed the limit when using multiple variable. 

The code to account for this case is complete but tests still need to be written.

**Comment by whabanks** [comment]
PR's are up and ready for review.

**Comment by whabanks** [comment]
New errors when the length of all variables + template content is greater than the 612 sms limit:

<img width="1129" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ZNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7de5538bbc25be787d96e96cdaef16efbcb4a1aa/image.png" alt="image.png" />

**Comment by mtoutloff** [comment]
Two PRs, one was tested, but not the second, second will be tested after stand-up

**Comment by mtoutloff** [comment]
Still in review for admin PR, needed to make a few adjustments, but ready to be fully reviewed
