### ISSUE TITLE
API key "last used" date is incorrect [bug-bogue]

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1333]
## Describe the bug 

In admin, the "Last used" date listed for API keys can be incorrect for keys that were last used a while ago.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

SEV-3 Minor

## To Reproduce

Steps to reproduce the behaviour:

1. Go to a service that has an API key that was last used 1 year ago (not sure how old it has to be exactly but 1 year should be plenty). For example: https://notification.canada.ca/services/01a0f347-3ecd-44a2-bf83-e1385166fbf5/api/keys
2. Note that the API keys all say: `Last used: Never`
3. Query for keys attached to this service in the DB and observe that they have been used before. They are attached to some notifications in the `notification_history` table

## Expected behaviour

API keys that have been used should have a correct value for "Last used".

## Impact

Impact on Notify users: Confusion

Impact on Notify team: Confusion when dealing with support issues

## Additional context

Here is the bug: https://github.com/cds-snc/notification-api/blob/main/app/dao/fact_notification_status_dao.py#L329-L342

That query only checks the `notifications` table, and not the `notification_history` table.

**Comment by jzbahrai** [comment]
The PR is up and it is ready for review.

**Comment by jzbahrai** [comment]
The PR is up and it is ready for review.
