### ISSUE TITLE
Dev: Implement daily limit v2 designs

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1334]
## Description
As a dev, I need to be able to build the new daily limits v2 so that we can release it. 

WHY are we building?
- To implement designs that have received feedback from team.

WHAT are we building?
- New daily limit counter on dashboard
- New near limit emails
- New hint text for sms templates (character limit)

VALUE created by our solution
- Clarity over daily limits

## Documentation and Artifacts
https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?type=design&node-id=2330-4522&mode=dev

## Acceptance Criteria
- [x] New limits section + widgets are on dashboard
- [ ] SMS near-limit email has been updated with number of remaining emails
- [ ] SMS over-limit email has been updated with number of remaining sms's
- [x] Hint text added to SMS template screen 
- [x] Error message for SMS template too long updated

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1334?planning-poker) with Zenhub @andrewleith @jzbahrai @smcmurtry @whabanks

**Comment by andrewleith** [comment]
Starting work on the component this moring.

**Comment by yaelberger-commits** [comment]
Andrew made a11y changes, if Steve M can take a look.
Still have bug where stats on the dashboard are incorrect time. Hide this until we fix that bug

**Comment by yaelberger-commits** [comment]
Phil to review UI implementation
