### ISSUE TITLE
Notification counter incremented even though notification not created

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1339]
## Describe the bug 

A notification sent through the api that is rejected (ex: using a team key to send to a user not in the team) will still cause the counter to increment. This is a bug since the counter should be equal to the number of (email or sms) notifications for the service in the database, but in this case we are rejecting the POST and not creating the notification.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor - note that valid notifications not affected

## To Reproduce

1. create a team key
2. use the api to send to a non-team member using this key
3. eventually you will get go over your daily limit, but not have any notifications in your dashboard

## Expected behavior

redis counter only incremented if we create a notification in the database

## Impact

confusion for our users, with them possibly trying to debug using an incorrect error message

## Additional context

[Incident channel](https://gcdigital.slack.com/archives/C05QQKFQEF6/p1693585309266019)

**Comment by sastels** [comment]
preliminary work: https://github.com/cds-snc/notification-api/pull/1970

**Comment by smcmurtry** [comment]
PR was tested and reviewed by me, it has been merged to Staging, ready for QA there.

**Comment by andrewleith** [comment]
✅  QA'd both email and sms, redis counter not incremented, correct error displayed.
