### ISSUE TITLE
Remove old feature flags

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#1344]
# Remove old feature flags

Remove from notification-api the following feature flags:
- `FF_EMAIL_DAILY_LIMIT`

Remove unused feature flags from notification-manifests

**Comment by whabanks** [comment]
Manifests PR is ready for review. API PR is up and almost ready for review - wrangling with the last failing unit test.

**Comment by whabanks** [comment]
Fully ready for review!
