### ISSUE TITLE
Help users migrate their Notify access to their own gov email

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1374]
Eliminate the use of shared inboxes by informing users currently using a shared account to log in of this change, migrating their account to individual email address and associating any team members with that service

As a user of Notify, I need to know that I should not share an inbox so that I can maintain Notify's security. 

**WHY are we building?**
We don't want users to log in with a shared inbox. There are security issues with shared inboxes.

**WHAT are we building?**
Communication to Notify users to inform them of new Terms of Use and to tell them to migrate their account to an individual email. 
There may be some other help to provide depending who uses this shared log-in, and how many people need access through this shared log-in. 

**VALUE created by our solution**
No more password sharing.

## Documentation and Artifacts
- [Incident](https://docs.google.com/document/d/1_3Egk7ljIF5lH4z9RXLxElHn14G9LfuZ7z-hHwCsHZI/edit#heading=h.gjdgxs)

## Acceptance Criteria
- [x] We have an up to date list of suspicious users. 
- [x] We have an email to send out to those users
- [x] The support team is ready and prepared to answer questions and help those users migrate their accounts. 
- [x] Email and support materials are translated

* Privacy considerations
  * There may be different use case for shared log-ins. We'll need to help our users understand that more accounts is safer than a shared account. 
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Email is sent as a test before being sent to everyone else.

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1374?planning-poker) with Zenhub @YedidaZalik @mtoutloff

**Comment by yaelberger-commits** [comment]
Yedida will add a salutation and ((name)) variable. Then will need to be handed off to devs

**Comment by YedidaZalik** [comment]
Updated with salutation and name variable. Ready for dev.

**Comment by yaelberger-commits** [comment]
Emails were sent 1pm ET Nov. 7

**Comment by amazingphilippe** [comment]
Support has created a tag to track support tickets related to this (Notify_Usability_SharedMailbox)
