### ISSUE TITLE
Update our ToU with explicit rules forbidding the usage of shared accounts to log into GCNotify

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1375]
## Description
As a user, I need to know the rules for creating an account so that I can contribute to maintaining Notify security. 

As the Notify admins, we need users to avoid creating user accounts in Notify with a shared email inbox, so that passwords and one-time keys are not shared among staff.

WHY are we building?
ToU could provide clearer guidelines to prevent users creating an account with a shared inbox

WHAT are we building?
Adding to the ToU

VALUE created by our solution
Clarity and clearly placing the responsibility onto our users, even if we'll do periodic checks to enforce this rule. 

## Documentation and Artifacts
[Incident](https://docs.google.com/document/d/1_3Egk7ljIF5lH4z9RXLxElHn14G9LfuZ7z-hHwCsHZI/edit)

## Acceptance Criteria
- [x] Updates are drafted in [Notify policy docs](https://docs.google.com/document/d/1UTrvyGwYNBCUGq55UADa6mg1V3F-hcT6ddi0uIjZEuw/edit?pli=1#heading=h.mnkk2wn3tbo2)
- [ ] Updates are translated

## QA Steps
- [ ] Tested in a realistic production scenario

Articles pages to publish in both languages:
1. Update terms of use
2. Create new archived version of terms of use

## GC Articles Publish checklist
- [x]  Page content and slug is translated
- [x]  Document links to and from the page
- [x]  Create new page or update existing page content
- [x]  Create or update translation to the page
- [x]  Link translations by choosing an assigned translation
- [x]  If new page, save as draft
- [x]  If existing page, update the page
- [x]  Post page in Slack for last minute reviews
- [x]  On staging: Clear the cache through GC Notify's admin panel
- [x]  On staging: Check links, images and language toggle
- [x]  Give a heads up to the app-team channel once ready to publish
- [x]  On staging and production: Clear the cache through GC Notify's admin panel
- [x]  Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1375?planning-poker) with Zenhub @YedidaZalik @mtoutloff

**Comment by YedidaZalik** [comment]
Work on the new bullet is in https://docs.google.com/document/d/1UTrvyGwYNBCUGq55UADa6mg1V3F-hcT6ddi0uIjZEuw/edit?pli=1#heading=h.mnkk2wn3tbo2
and https://docs.google.com/document/d/1zX0IrWs0DG8jrYRACZ05ji_vszToOfpU6Jc8pzbHVNA/edit

**Comment by YedidaZalik** [comment]
Translation:

Pour créer votre compte Notification GC, utilisez une adresse courriel professionnelle à laquelle personne d’autre n’a accès. Il est interdit d’utiliser une boîte de réception commune ou de partager vos identifiants ou votre mot de passe, même avec vos collègues.

Discussion about using strong language for translation https://gcdigital.slack.com/archives/C061CCBSULW/p1698762163068969?thread_ts=1698756717.708229&cid=C061CCBSULW

**Comment by YedidaZalik** [comment]
Comms about this https://docs.google.com/document/d/1zSGx9amIBIAS7_a9ay4rihE_hcOi3PBBM-HNj0SgMrM/edit#heading=h.ithu4hpqdoxq

**Comment by YedidaZalik** [comment]
@amazingphilippe updated the TOU in both languages

**Comment by amazingphilippe** [comment]
ToU pages updated and archived versions published on GCA.

1. https://notification.canada.ca/terms
2. https://notification.canada.ca/conditions-dutilisation

Follow links at the bottom for archived versions
