### ISSUE TITLE
Security for API revocation

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1377]
## Description
As a (user), we have a way to revoke API keys through an API:
https://github.com/cds-snc/notification-api/pull/1973/files

We need to set up security for this so that ONLY someone with an SRE auth can do so.

## Acceptance Criteria
This API cannot be called by ADMIN, it can only be called through the SRE bot

## QA Steps
Test by integrating with the SRE bot
Ensure the API cannot be called otherwise

**Comment by yaelberger-commits** [comment]
Was merged

**Comment by yaelberger-commits** [comment]
SRE needs to fix their bot so we don't get paged for auto revocation, just a Slack message to log

**Comment by yaelberger-commits** [comment]
Devs to discuss QA process

**Comment by yaelberger-commits** [comment]
@andrewleith is this still in QA, or has it been released in prod?

**Comment by yaelberger-commits** [comment]
Content for email to notify clients their key has been revoked is now ready. card #1376

**Comment by andrewleith** [comment]
Sorry for the late update, this is now live in PROD.

**Comment by andrewleith** [comment]
SRE tested this last week!
