### ISSUE TITLE
When deciding if a CSV is too big, admin is counting sms while API is counting fragments

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1378]
## Describe the bug 

When deciding if a CSV is too big, admin is counting sms while API is counting fragments. If a user sends 335 text notifications and each is made up of 3 fragments, currently they are being cut off from sending as the CSV would put them over 1000 fragments, but they should be allowed up to 1000 text messages of up to 4 fragments each. 

## SEV 2

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

## To Reproduce

1. Go to a service that sends text messages with 1,000 daily SMS limit
2. Select a text message template that is made up of 3 fragments (120 characters)
3. Select send to many
4. Upload a CSV with 335 recipients 
4. See 500 error

## Expected behavior

A CSV upload with 335 recipients where the template being used is 120 characters or up to 160 characters should not produce a 500 error, it should successfully send if the service has a daily SMS limit of 1000 and hasn't sent any messages yet.

## Impact

If applicable

Impact on Notify users:
Users hitting 500 error and being unable to send text messages when they should be able to. 

Impact on Recipients:
Some SMS messages being blocked from sending means some recipients won't receive notifications

Impact on Notify team: 
Inconsistent application of daily limit between Admin and API

## Additional context

https://gcdigital.slack.com/archives/CV38DBNVA/p1698960023450489

**Comment by sastels** [comment]
You can also see the behaviour (ie counting sms vs fragments) by sending one multifragment sms and looking at the dashboard vs sms redis counter for your service

**Comment by sastels** [comment]
You can also see the behaviour (ie counting sms vs fragments) by sending one multifragment sms and looking at the dashboard vs sms redis counter for your service

**Comment by yaelberger-commits** [comment]
code mostly complete, Will writing some tests today

**Comment by whabanks** [comment]
PR's are up, Andrew left comments on Thursday. Addressed these comments on Friday.

**Comment by andrewleith** [comment]
- Waiting on review - @andrewleith to review this morning

**Comment by andrewleith** [comment]
- review complete; not yet released to production

**Comment by andrewleith** [comment]
- This is now in prod!
