### ISSUE TITLE
Remind users to revoke and replace old API keys

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1379]
## Description
As a Notify user, I need to be able to understand that I must revoke my old API keys before the deadline  so that I can continue sending through the API.

WHY are we building?
API users will not be able to send if they don't replace their old keys.

WHAT are we building?
An email that communicates this clearly, along with the deadline to do so.

VALUE created by our solution
API users replace old keys and continue to have be to send through the API.

## Documentation and Artifacts
Email ready with both EN and FR https://docs.google.com/document/d/1z0WW8h2xsV60hM9ebZbww9pGUvvMZ_i0Yu9PRqiiU3w/edit?pli=1#heading=h.x5yv9a6sqsvr

Earlier iterations are here:https://docs.google.com/document/d/18aiLCuPJkBqhIVx_ZWAQgzJAnG4V3JI35BOpxJMToRs/edit

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Cypress UI tests if needed.
- [x] Generate appropriate log messages so that executions of this feature can be tracked

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Yael and @jzbahrai are meeting Tuesday about next steps for revoking remaining old keys

**Comment by jzbahrai** [comment]
Posting queries I am running on prd:

**Comment by yaelberger-commits** [comment]
Remaining old API keys brought down from 49 to 26 today.
