### ISSUE TITLE
Evaluate sending SMS messages outside of Canada

### ISSUE THREAD

**Issue by stephenyates-gc** [cds-snc/notification-planning#138]
Problem Statement: Some services using GC Notify have strong use cases for using Notify to send SMS outside of Canada, but currently Notify is not set up to reliably send SMS outside Canada/North America. 

GC Notify has been designed and tested for sending SMS messages to recipients in Canada, but it is possible to send messages to recipients in other countries. We will investigate the current limitations and evaluate expanding Notify beyond Canada.

[Related research: IRCC Afghan Notification System - Usability Test](https://docs.google.com/document/d/1Dr-KU5QRfR5RPB7WaqfsfrlUyqNxc-C_1NmFPuMnGvM/edit#) - Page 6

> None of the participants received a confirmation  SMS/text when one was sent, before the end of the session (>10 mins).
> SMS messages sent via calendly to confirm the time of the session were received by at least two participants.
> Communicate limitations of SMS reliability when used outside of North America to clients. Recommend against the use of SMS for critical services unless the issue can be resolved.

**Comment by yaelberger-commits** [comment]
We investigated and documented in an ADR and will pick this back up again as we get new information
