### ISSUE TITLE
Modelling what a "service" means

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1383]
## Description
As a Notify contributor, I need to understand where and how the term "service" is used, so that I can orient and help Notify users that are not familiar with the term or its context. 

WHY are we building?
Because we know "service" does not resonate with our users. We might not be able to change it, but we might be able to make sense of it.

WHAT are we building?
An object oriented model. Which is just a map of words used in the Notify interface, how they connect to adjacent context, how they relate to user interaction.

VALUE created by our solution
We have good design documentation around the word "service". It should help us keep this word, and frame it in a way that makes sense. 

## Documentation and Artifacts
- [Miro](https://miro.com/app/board/uXjVMrLOWJM=/?moveToWidget=3458764569091556354&cot=14)

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] "Service" is mapped on a partial map. 
- [x] Walkthrough the map with the team and make changes where needed

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

**Comment by amazingphilippe** [comment]
Model included in the Miro link above, ready to be used in Story refinement.

**Comment by yaelberger-commits** [comment]
Phil will demo the model on Monday at Notify Demo
