### ISSUE TITLE
Dev: Create an account - adjust hint text to prevent shared inboxes

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1384]
## Description
As a user, I need to know the requirements when I create an account so that I can successfully comply to TOU. 

WHY are we building?
We're not sure users read the terms of use, but more might read hint text.

WHAT are we building?
Specifying "no shared emails" on the email field when users create an account.

VALUE created by our solution
We have another way to ensure the "no shared inboxes" rule can be followed. 

## Documentation and Artifacts
- Forms screens?
- [Incident](https://docs.google.com/document/d/1_3Egk7ljIF5lH4z9RXLxElHn14G9LfuZ7z-hHwCsHZI/edit)
- [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXUxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27a2acd02b1ac5bba118768ae8fbfe3905840d91/Screenshot%202023-11-08%20at%208.42.01%20AM.png)

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] We steal content from Forms
- [x] Content makes sense in Notify context
- [x] We steal or create translations too
- [x] Cypress UI tests if needed.

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1384?planning-poker) with Zenhub @adriannelee @YedidaZalik

**Comment by YedidaZalik** [comment]
Work on hint text here: https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?type=design&node-id=1544-1344&mode=design&t=5MwsqgkcpdCwCMtl-0

**Comment by YedidaZalik** [comment]
Most recent iterations and thinking are here: https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?type=design&node-id=1541-252&mode=design&t=Lwfy6ik0swBTzFFF-0

**Comment by YedidaZalik** [comment]
Out for feedback from team by EOD Friday https://gcdigital.slack.com/archives/C04TQMJCXEW/p1700075166742919

**Comment by YedidaZalik** [comment]
Replied to comment from Phil and also tagged Yael.

**Comment by yaelberger-commits** [comment]
@YedidaZalik I think we can proceed with the error message we agreed on previously

**Comment by YedidaZalik** [comment]
Sent for localization: https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?type=design&node-id=1630-82&mode=design&t=ZJkqgFP5mMCPfh1R-0

**Comment by YedidaZalik** [comment]
With @mariesophiebezert for localization

**Comment by YedidaZalik** [comment]
French hint text and error message ready :https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?type=design&node-id=1664-80&mode=design&t=w5iUuyWxpKJbfLbe-0

**Comment by YedidaZalik** [comment]
Preparing for dev https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?type=design&node-id=1541-252&mode=design&t=w5iUuyWxpKJbfLbe-0

**Comment by amazingphilippe** [comment]
Released with #1262

**Comment by whabanks** [comment]
[PR ready for review](https://github.com/cds-snc/notification-admin/pull/1746)

**Comment by yaelberger-commits** [comment]
<img width="1194" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL29QQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27ddf66bb0bddd025671b6d054488ac2c5073cc8/Screenshot%202024-01-30%20at%2010.17.11%E2%80%AFAM.png" alt="Screenshot 2024-01-30 at 10.17.11 AM.png" />
