### ISSUE TITLE
Triage OCADU a11y audit 

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1385]
## Description
As a Notify contributor, I need to be able to pick up detailed a11y issues so that I can fix them. 

WHY are we building?
We got back a detailed a11y audit

WHAT are we building?
Making sure the issues are part of our backlog, documented, refined, and ready to pick up at any time. 

VALUE created by our solution
Continuously improving a11y is easy.

## Documentation and Artifacts
- Audit when it comes back

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Audit is available for all
- [x] Summary has been demoed or shared with team
- [x] Issues are input in zenhub's new issues column
- [x] Issues are tagged and detailed. 
- [x] Issues are linked to known UX or a11y issues where relevant
- [x] Reach out to OCADU for follow up questions

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1385?planning-poker) with Zenhub @adriannelee @amazingphilippe

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1385?planning-poker) with Zenhub @andrewleith

**Comment by amazingphilippe** [comment]
Audit is ready to review: https://docs.google.com/document/d/1XKh6TMGYFcHMM_iL4DyUs4j67MsJjQOP/edit

**Comment by adriannelee** [comment]
Up for dev-design review today.

**Comment by adriannelee** [comment]
Phil is working on this today.

**Comment by amazingphilippe** [comment]
Linking a11y issues with current stories done. 
Looking over issues that were less clear, and questions we had so far during the audit playback, we could meetup with OCADU and know more about:

- Visually hidden text as a technique to counter visual relationships. 
- Where and how should we use aria-describedby?
- Techniques for marking variables in templates. aria-described by?


Moving this to "review" so that we can brainstorm other topics and book some time with OCADU

**Comment by amazingphilippe** [comment]
Andrew and Phil will meet with OCADU and discuss techniques and strategy for a11y

**Comment by amazingphilippe** [comment]
Notes from OCADU follow up sync: https://docs.google.com/document/d/1QiG9MuM_GVQVISu5Ge8PmP8KyS2eJ4YTEHSvX_JHbFM/edit
