### ISSUE TITLE
Scheduler date preview is stuck in 2020

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1388]
## Describe the bug 

When scheduling an email, the preview shows that the emails will be sent in 2020. The calendar, time and days of the week seem correct. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTJ1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d1bf90761eb920ba8625d657665e61da9852cb0/image.png)

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3

## To Reproduce

1. Go through the sending process
2. On the review screen, select schedule for later
3. See the preview date in the yellow box

## Expected behavior

I should see the correct date and year. 

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

Momentary confusion. The date is correct on the next screen.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlN1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc39d3a84675839910e05c9f9765cf063b4da55f/Capture%20d%E2%80%99e%CC%81cran%2C%20le%202023-11-07%20a%CC%80%2010.30.19.png)

If applicable

Impact on Notify users: yes

Impact on Recipients: no

Impact on Notify team: yes

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1388?planning-poker) with Zenhub @andrewleith @jzbahrai @whabanks

**Comment by yaelberger-commits** [comment]
Did this one get merged into Staging @andrewleith ? I can QA

**Comment by yaelberger-commits** [comment]
<img width="1085" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTN4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bb53cc5676cda3251f3d9a6529365a3dec44571/Screenshot%202024-05-17%20at%202.08.10%E2%80%AFPM.png" alt="Screenshot 2024-05-17 at 2.08.10 PM.png" />
<img width="1215" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS94QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--905f8f73b3001d7b553fe79be842eaeee6c1b142/Screenshot%202024-05-17%20at%202.08.28%E2%80%AFPM.png" alt="Screenshot 2024-05-17 at 2.08.28 PM.png" />

Looks good in staging now!
