### ISSUE TITLE
Update the Notify Privacy Statement to reflect new authorities following our transfer to ESDC 

### ISSUE THREAD

**Issue by mtoutloff** [cds-snc/notification-planning#1391]
## Description
As a user I need to understand what legal authority enables Notify so that I can be assured it is authorized to collect and store my personal information and my recipients' personal information.

WHY are we building?
CDS transferred to ESDC this past summer, which meant that our legal authorities have also changed 

WHAT are we building?
Updates to the Notify Privacy Statement to reflect our current authorities 

VALUE created by our solution
Users will have up to date information about what authorities enable us to collect their personal information and their recipients' personal information, which is also a requirement in the TB Directive on Privacy Practices. 

## Documentation and Artifacts
https://docs.google.com/document/d/1UTrvyGwYNBCUGq55UADa6mg1V3F-hcT6ddi0uIjZEuw/edit#heading=h.mnkk2wn3tbo2

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Update the draft Privacy Statement 
- [x] Content review, if necessary
- [x] Translation 
- [x] Publish updates 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps
- [ ] Verify that the text is updated and translation on the webpage

**Comment by yaelberger-commits** [comment]
Looks good! Thanks @mtoutloff

**Comment by yaelberger-commits** [comment]
Melissa, Phil and Yael will circle back on this tomorrow

**Comment by amazingphilippe** [comment]
## GC Articles Publish checklist
- [x]  Create or update slug for archived policy pages
- [x]  Page content and slug is translated
- [ ]  Document links to and from the page.
- [ ]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [ ]  Update existing page content
- [ ]  Update translation to the page
- [ ]  If existing page, update the page
- [ ]  Post page in Slack for last minute reviews
- [ ]  On staging: Clear the cache through GC Notify's admin panel
- [ ]  On staging: Check links, images and language toggle
- [ ]  Give a heads up to the app-team channel once ready to publish
- [ ]  On staging and production: Clear the cache through GC Notify's admin panel
- [ ]  Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by yaelberger-commits** [comment]
@amazingphilippe will check about clearing the cache in admin panel and Cloudfront
