### ISSUE TITLE
Test a11y of rich text editor

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1393]
We have a couple last minute Fable testing requests that we can use before Nov 15 EOD.

- [x] Create a prototype to share in the request
- [x] Draft request in English
- [x] Draft privacy statement
- [x] @mtoutloff reviews privacy statement
- [x] Translate privacy statement
- [x] Pre-test on Nov 15
- [x] Submit requests

**Comment by amazingphilippe** [comment]
PR is here: https://github.com/cds-snc/notification-admin/pull/1720
Prototype is here: https://r2kd53g7xdqvqw3h5x32mdifhm0xfklh.lambda-url.ca-central-1.on.aws/_rte

**Comment by amazingphilippe** [comment]
There are a few things to review, and dry run before we can submit the Fable request.

**Comment by yaelberger-commits** [comment]
Gets tested tomorrow, Phil and Adrianne will take a look, dry run this afternoon

**Comment by yaelberger-commits** [comment]
Add links to our authorities for privacy statement (likely already translated) @adriannelee and @mtoutloff
