### ISSUE TITLE
Tasks regarding Celery Workers not picking up Jobs

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1397]
## Description
We had an incident where Celery workers were not picking up jobs. We want to do a couple of things to help with this and the underlying issue which was the DST time change.
This is the incident report: https://docs.google.com/document/d/1jTcxO2O09rbWxMfIhA76cqepeHYWmYiU7ZNcg2bnXEk/edit

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Set a Slackbot reminder for Nov. 5 (or last day of work before time change) to ensure we don’t repeat the problem in 2024
- [x] Make an alarm to detect if celery-beat isn't scheduling anything
- [x] Write a process for determining what messages have not been sent and what services have been impacted

**Comment by andrewleith** [comment]
Process for what to do in the event this happens added to tips and tricks: https://docs.google.com/document/d/16LLelZ7WEKrnbocrl0Az74JqkCv5DBZ9QILRBUFJQt8/edit#heading=h.ggprny153f5a

**Comment by jzbahrai** [comment]
read the documentation!
