### ISSUE TITLE
Test and change celery config from DST/ UTC

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1398]
## Description

When the time changes, celery stops picking up jobs for the 1 hr of the DST change.
We had an incident due to this. https://docs.google.com/document/d/1jTcxO2O09rbWxMfIhA76cqepeHYWmYiU7ZNcg2bnXEk/edit

Might need to change this: https://github.com/cds-snc/notification-api/blob/main/app/config.py#L355

# Acceptance Criteria

- [x] Are we using UTC in celery beat as we do everywhere else? https://github.com/alphagov/notifications-api/commit/d336b6ba12ba83297bb5f4bc24aac7462da65de6
- [ ] Test this change to see that it works for existing jobs in the pipeline that have been injested in DST and not UTC

**Comment by whabanks** [comment]
Celery beat uses [UTC by default](https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html#time-zones) but we've enabled and [specified UTC in the beat config](https://github.com/cds-snc/notification-api/pull/2080/files#diff-76936416943346b5f691dac57a64acebc6a1227293820d1d9af4791087c9fb9e) for posterity.
