### ISSUE TITLE
User research in our product privacy statement

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1401]
Our product privacy statement makes it clear that the product team may reach out to them for learning purposes and to improve the product. This would also include other ways we collect user data

- User research (use their usage behaviour and contact information to reach out to them to participate in a research activity
- Use of SaaS tools such as DoveTail, Miro, Google docs to analyze research data

- [x] Google Analytics
- [x] Freshdesk
~~- [ ] Mixpanel~~

Notes about integrating Freshdesk with DoveTail, including question to and answer from Melissa https://docs.google.com/document/d/12BQ-PjPcRvPFA7BZzY44GxlhJNoVzL9NwwFJgJWkWpI/edit

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1401?planning-poker) with Zenhub @adriannelee @mtoutloff

**Comment by mtoutloff** [comment]
@yaelberger-commits I think this one can be closed as this was tacked on to the updates to the Accessibility Statement. Yedida and I made edits to the Privacy Statement, which I believe are currently with translation

**Comment by yaelberger-commits** [comment]
I QA'd the changes in production and they look great!
