### ISSUE TITLE
Archive user accounts logging in from a shared email

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1404]
## Description
As a Notify admin, I need to archive shared email users, so that we can enforce our one-person, one-account policy

WHY are we building?
We have a list of user accounts that are seemingly using a shared email to sign-in to Notify
We need to archive those users, to enforce our one-person, one-account policy

WHAT are we building?
Go through the CSV and archive users
Double check in support channel to make sure archiving is needed

VALUE created by our solution
No more shared email accounts

## Documentation and Artifacts
- [Incident document](https://docs.google.com/document/d/1_3Egk7ljIF5lH4z9RXLxElHn14G9LfuZ7z-hHwCsHZI/edit#heading=h.gjdgxs)
- [Blazer query with shared emails](http://localhost:1338/queries/255-support-new-shared-inboxes). Needs to be manually filtered. Phil has a CSV. 

## Acceptance Criteria
Given we have the list of shared emails, when we set them to archived = True, shared emails can't log in anymore. 
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] We've notified concerned users of account deletion
- [x] We've changed our terms of use
- [ ] We have a canned response in case someone can't log in, and missed the warning.
- [ ] We get in touch with accounts that can't be archived (if they are the only team member on a service) And 
- [ ] Blazer query returns no suspicious unarchived accounts

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1404?planning-poker) with Zenhub @amazingphilippe @yaelberger-commits

**Comment by andrewleith** [comment]
- Yael and Phil removed all but 6 shared emails, 3 need to be contacted due to being the only people on their team (or only one with all permissions), 3 are from CDS

**Comment by andrewleith** [comment]
- Phil to check through Blazer
