### ISSUE TITLE
Missing translation in service creation flow

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1407]
## Describe the bug 

Paragraph 2 of the service name and email detailed example is missing its translation. See screenshot.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2

## To Reproduce

1. Switch to FR app
1. Start by adding a service
2. Make your way to step 2
3. Expand the detail-summary element
4. Notice the missing translation

## Expected behavior

We have a translation for this:

[Figma](https://www.figma.com/file/47FhKMvOXm95IZFL9G8PYN/Creating-bilingual-message-templates-%7C-Creer-des-gabarits-de-message?type=design&node-id=2173-30266&mode=design&t=hTdKAGqmlYp9WjOA-4)

Translation content:

```csv
"In this example, a government service has chosen the name ‘Renew your license’ and the email address ‘renew@notification.canada.ca’:","Dans cet exemple, un service gouvernemental a choisi le nom « Renouveler votre permis » et l’adresse courriel « renouveler@notification.canada.ca » :"
```

## Impact

Service quality is different in FR

If applicable

Impact on Notify users: Misunderstanding the service name and sending address

Impact on Recipients: 

Impact on Notify team: 

## Screenshots

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi8zQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b279625d76d4c67f1c57a4573c90024b25262d6/image.png)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1407?planning-poker) with Zenhub @adriannelee @amazingphilippe @YedidaZalik

**Comment by amazingphilippe** [comment]
This bug was fixed in https://github.com/cds-snc/notification-admin/pull/1736, but I forgot to document it.
