### ISSUE TITLE
Research plan & starting recruitment - Understand conversion

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1409]
One of Notify’s key results for 2023/2024 is to increase the trial-to-live conversion rate by 25%. This OKR is especially important considering the mandate letter mentioning CDS and Notify may see more high impact services. In the previous year, our conversion rate was about 22%. Increasing by 25% would mean a 47% conversion rate. Our current conversion rate is at about 26%.

There's some of this research that exists already. But we want to do more continuous research to understand more broadly and the issues that may be impacting new clients more recently. The product has gone through changes and clients may be undergoing different work contexts, now a few years after the research in 2021.

[Research plan](https://docs.google.com/document/d/10ZjkSxCrVKbspPrwKR3XWImIdy3izGDKX4O9NDj4D8c/edit)

Recruitment to-do's:

- [x] Draft privacy statement
- [x] Share privacy statement with @mtoutloff for review
- [x] Send privacy statement to translation
- [x] Query for list of potential respondents
- [x] Draft invite
- [x] Set up Calendly @adriannelee 
- [x] Set up Calendly @amazingphilippe 
- [x] Send invite to translation
- [x] Send out invite
- [x] Draft facilitation guide
- [x] Get it reviewed by @jeanafrost, Jenn F, @amazingphilippe, @yaelberger-commits 
- [x] Send facilitation guide to translation

**Comment by adriannelee** [comment]
Drafted the first few sections of the plan today and shared with Yael for review.

**Comment by andrewleith** [comment]
- Reviewed by Yael last week, Adrianne will look at this today and decide whether to include in sprint

**Comment by andrewleith** [comment]
- Adrianne to work on this today

**Comment by yaelberger-commits** [comment]
Reviewed! LGTM with the proposed recruitment plan

**Comment by adriannelee** [comment]
Drafted the privacy statement and recruitment email today. Shared both with Melissa and team.

**Comment by adriannelee** [comment]
I'm going to be working on the recruitment email feedback & sending privacy statement to translation.

**Comment by adriannelee** [comment]
Sent docs to translation today and started on working on the query. The results don't look right :/

Looking for query help next week! http://localhost:1338/queries/265-research-recruitment-service-size-not-active?max_team_size=1&min_team_size=1

**Comment by andrewleith** [comment]
- @adriannelee looking for help with blazer query

**Comment by andrewleith** [comment]
- Docs still in transition
- @adriannelee got the list of demo attendees; going to cross-reference against query to make sure we get a good mix of people
- @adriannelee to set up Calendly and including Jeana and Jenn F
- This will be an ongoing, rolling activity

**Comment by adriannelee** [comment]
Will send out the invites in early January. I'll be prepping a few small things today.

**Comment by adriannelee** [comment]
Finished getting the invite text ready with translation and the calendly links today. 

Did some more looking into the invitee list query, after a few suggestions from Jeana on the sampling. There's a bit more cleaning up to do.

**Comment by adriannelee** [comment]
@andrewleith It looks like the query is not excluding services that have sent more than 70 notifications in the last 6 months. For example, this one: 5b01da2d-cebe-4f55-8ed6-ce8db37ec33a

**Comment by adriannelee** [comment]
Responded to a couple of questions from Jeana on the facilitation guide

**Comment by adriannelee** [comment]
Phil and Yael are done reviewing. So I'll take a look today at the feedback.

**Comment by yaelberger-commits** [comment]
I've completed my review of the facilitation guide

**Comment by adriannelee** [comment]
Reviewed comments & created a translation request.

**Comment by adriannelee** [comment]
Worked on the query with Andrew today - to continue tomorrow.

**Comment by jzbahrai** [comment]
Please post blazer query to use here

**Comment by adriannelee** [comment]
Updated AC list and sent out the first batch of invites (38) today. Will monitor sign ups and send out more invites as needed. Moving to done!
