### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/notification-planning#141]
# Description 

We need better data on how people are sending messages so we have better intelligence on how to improve our services. 

How quickly we’re growing, what types of services, business intelligence.

**Comment by yaelberger-commits** [comment]
We don't have meta data on services to track the level of security classification (but it's something we talked and would be good to have).

**Comment by yaelberger-commits** [comment]
I think this is covered by our Airtable and our Service Reporting Spreadsheet. 
Closing
