### ISSUE TITLE
Create new infrastructure for System Status

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1430]
## Description
As a Notify Dev, I need to be able code the system status infrastructure in TF.

## Documentation and Artifacts

- [System status ADR](https://github.com/cds-snc/notification-adr/blob/main/records/2023-11-24.system-status.md)

### back-end
- [x] TF code created for new backend lambda API
- [x] TF code including whatever is needed for our release process
- [x] Need a github action that takes the lambda function and pushes the latest commit to ECR:
```
here’s an example of how we’ve done this in a different repo:
https://github.com/cds-snc/scan-files/blob/main/.github/workflows/build_and_push_staging.yml
this chunk here is a :mohamed: special that checks each dir for changes, and then will only build/push that docker image if there are changes.
the ${{ matrix.image }} ends up being the first part of the dorny path filter (so api or module/s3-scan-object)
``` 
- [x] API is automatically run every 5 minutes (could be TF, or [scheduled events](https://docs.aws.amazon.com/lambda/latest/dg/services-cloudwatchevents-tutorial.html))
- [x] Is the new image, restarting the lambda?
- [x] Add DNS entry for prod`status.notification.canada.ca`
- [x] Add DNS entry for staging `status.staging.notification.cdssandbox.xyz`

### front-end
- [x] TF code created to create staging static site in s3/cloudfront
- [x] TF code created to create staging production site in s3/cloudfront

**Comment by andrewleith** [comment]
- Finished part of the PR
- Concerns about merging right after the infra code freeze, going to speak with core

**Comment by andrewleith** [comment]
- Some pieces are now working in DEV and staging

**Comment by adriannelee** [comment]
Jumana took as far as it could go during the code freeze.

**Comment by adriannelee** [comment]
Will check what's working with the deploy today
