### ISSUE TITLE
Add system status page

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1432]
## Description
Create system status base page

## Documentation and Artifacts

- [System status ADR](https://github.com/cds-snc/notification-adr/blob/main/records/2023-11-24.system-status.md)

#### Design
- [x] Layout/design for main status page
- [x] Layout/design for component statuses (example in ADR)
- [x] Layout/design for where link in admin to system status should be

#### UI 
- [x] System status main page created
   - [x] Latest tailwind used (v3.3.6) along with ported tailwind config from admin
- [x] Component status section created
- [x] Incident and service interruptions list created

#### Interactivity
- [x] Backend data fetched from `.json` file in repo and displayed
- [x] Incident history info fetched from GC Articles and displayed
- [x] Page automatically updates every 5 minutes ([when tab is active](https://github.com/cds-snc/notification-admin/blob/a11y-fable/lexical-prototype/app/assets/javascripts/updateContent.js#L22))
- [x] Page can toggle bilingually

**Comment by amazingphilippe** [comment]
[Figma](https://www.figma.com/file/GAh6VlA5SQGeZwO6LHtZr8/System-status---%C3%89tat-du-syst%C3%A8me?type=design&node-id=50-2898&mode=design&t=6eqsrVKQXmD3u31R-4) for visual design of page. To be reviewed by team. 

The design follows language as defined in the ADR.
