### ISSUE TITLE
Add link to system status from admin

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1433]
## Description
Add link from GC Notify admin to the new system status page

## Documentation and Artifacts

- [System status ADR](https://github.com/cds-snc/notification-adr/blob/main/records/2023-11-24.system-status.md)

## Acceptance Criteria
- [x] Design created for where this should be
- [x] Admin updated with link

**Comment by yaelberger-commits** [comment]
I QA's this morning, links work in EN and FR and send to the correct language
