### ISSUE TITLE
Add new backend API code for system status to lambdas project

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1434]
## Description
Add backend code for system status

## Documentation and Artifacts

- [System status ADR](https://github.com/cds-snc/notification-adr/blob/main/records/2023-11-24.system-status.md)

## Acceptance Criteria
- [x] New lambda created in [notification-lambdas](https://github.com/cds-snc/notification-lambdas) repo
- [x] Response time based status checks run based on HTTP GET's to sites
- [x] Email/sms sending time status check run based on notifications sent by the heartbeat service
- [x] [Component statuses](https://github.com/cds-snc/notification-adr/pull/50) are computed and written to `response.json` in s3 bucket (see notes below for json structure ideas)

 
#### NOTES
- Keep all of the processing logic on the backend: this json file should contain the interpreted values, i.e. "up/down/degraded" instead of reporting response times, etc.

   ##### Example json payload
```
[
    {
        "component": "api",
        "status": "up"
    },
    {
        "component": "admin",
        "status": "down"
    },
    {
        "component": "email",
        "status": "degraded"
    },
    {
        "component": "sms",
        "status": "up"
    }
]
```

**Comment by andrewleith** [comment]
- Pr coming to add heartbeat templates

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1434?planning-poker) with Zenhub @andrewleith @whabanks @jzbahrai

**Comment by adriannelee** [comment]
Few things to test once we merge. Still ongoing.

**Comment by adriannelee** [comment]
Merging today. @jzbahrai will come back to this today
