### ISSUE TITLE
Add new notification types to hearbeat lambda for system status

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1435]
## Description
Add all types/priorities to heartbeat sender lambda

## Documentation and Artifacts

- [System status ADR](https://github.com/cds-snc/notification-adr/blob/main/records/2023-11-24.system-status.md)

### Extended template types
- [x] Extend heartbeat lambda to send all notification types/priorities:
   - [x] Email - Bulk
   - [x] Email - Normal
   - [x] Email - Priority
   - [x] SMS - Bulk
   - [x] SMS - Normal
   - [x] SMS - Priority

### github workflows
- [x] Add building hearbeat lambda to the staging workflow (`docker-build-and-push.yml`)
- [x] Add building heartbeat lambda to the PR workflow (`docker-build.yml`)

**Comment by andrewleith** [comment]
I ended up adding the template IDs into the utility function, so you wont need to do that last AC.  I'll remove it.

**Comment by andrewleith** [comment]
Once [this PR is merged](https://github.com/cds-snc/notification-utils/pull/264/files), you can get the template IDs using:
```
from notifications_utils.system_status import TEMPLATES
```

Let me know if you have any issues or that doesn't make sense.

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1435?planning-poker) with Zenhub @whabanks

**Comment by adriannelee** [comment]
Got started on this, will continue today.

**Comment by adriannelee** [comment]
Jumana has reviewed and will merge this one today.
