### ISSUE TITLE
Add a retry when we fetch from document download

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1436]
## Description
We had an incident: https://docs.google.com/document/d/1VMxe7NgO8zZpopqFuN3bNKzEWnjc9kfWH4toYfZTSW4/edit

where scan files was down, and then document download didn't respond. We should have a retry on this function here:https://github.com/cds-snc/notification-api/blob/128bc50413b55a4392e94452c5be9c6474f5725c/app/delivery/send_to_providers.py#L239-L253 

## Acceptance Criteria

- [x] Add a retry to the call to document-download api (retry from api to the scan-files endpoint/ document download)

**Comment by jzbahrai** [comment]
Comment from slack: 

Yeah there is no retry on the attachment retrieval. I searched if urllib.request.openurl(https://docs.python.org/3/library/urllib.request.html) do it automatically but it does not unfortunately. The version 3 via urllib3 (https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html) has a handy retry mechanism though (unless we want to do it with celery).

**Comment by whabanks** [comment]
[PR](https://github.com/cds-snc/notification-api/pull/2079) is ready for review.

**Comment by whabanks** [comment]
[Possibly related](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1450) to what we should do in the case of an attachment failure.
