### ISSUE TITLE
Incorporating privacy considerations in research plan template 

### ISSUE THREAD

**Issue by mtoutloff** [cds-snc/notification-planning#1437]
## Description
Incorporating privacy considerations into the research to systematize the privacy protocol for the Notify Team. 

WHY are we building?
To embed privacy considerations into research plans

WHAT are we building?
Updated research template with embedded privacy considerations

VALUE created by our solution
Consistency by ensuring privacy considerations are documented in our processes

## Documentation and Artifacts
[Research plan template](https://docs.google.com/document/d/1mClDUMGVZ5MrFVL3ioNQ2lr35CDIdY9WQXWrQwpBWd8/edit#heading=h.bo2orenpl4wn)
[Privacy protocol for conducting research at CDS ](https://docs.google.com/document/d/1fVe9JAFd1LwdRVCIcZcI5VhZMovZ7a8KchlYWIjT-sc/edit#heading=h.a5jjyd7gyk1t)

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Incorporate privacy requirements in research plan template 
- [x] Share with broader research community for feedback 
- [x] Incorporate in training sessions on the privacy protocol 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by mtoutloff** [comment]
Meeting with Adrianne on Dec 12 to discuss where to include privacy considerations in research plan template

**Comment by mtoutloff** [comment]
Adrianne and I met to discuss how we will incorporate privacy considerations in the research plan template. I will add questions for considerations in the document and share with Adrianne for her review.

**Comment by mtoutloff** [comment]
Shared with Adrianne on December 13th. Will reconvene on this in the New Year

**Comment by adriannelee** [comment]
I'll be adding to Melissa's work today.

**Comment by mtoutloff** [comment]
Will be reviewing Adrianne's input today

**Comment by adriannelee** [comment]
Melissa and I synced on this today. A couple of minor edits and we're good to share with the broader research community for feedback.

**Comment by adriannelee** [comment]
Wrapped up our draft and shared with the researchers today.

**Comment by mtoutloff** [comment]
Including information about the Research Plan Template in the Privacy Protocol training deck currently being drafted.

**Comment by mtoutloff** [comment]
Adde placeholder text in the Privacy Protocol training deck and will iterate on how to present the information for the training sessions
