### ISSUE TITLE
Expose the batch saving into a worker: Heartbeat + Implementation of the sub worker

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#144]
We are going to have a heartbeat worker that checks a Redis queue for notifications.
The heartbeat worker will call a sub-worker that will take these notifications and save them to the DB as well as send them to as an email or an SMS.

Please see implementation details in PART 2 of the below google doc:
https://docs.google.com/document/d/1Dnr77GC_gokX8GhV-lW_37UOHAts2s2Cpynj6hW5VVA/edit

Acceptance Criteria:
- [x] Add heartbeat worker that checks if the queue has notifications
- [x] Take the notifications in bulk from the queue (sub worker) and send to the DB to persist the notifications
- [x] Delete the inflight list
- [x] Monitor how the data flows, ensure the implementation works end to end in staging.
- [x] Test the code end to end to ensure the Redis Implementation of Queuing works

**Comment by jzbahrai** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/144?planning-poker) with ZenHub @jimleroyer @sastels @iokpala

**Comment by adriannelee** [comment]
The devs are at the integration point for all their work today.

**Comment by josh-cds** [comment]
@jimleroyer What's the status of this? It says blocked but by a card that's in the done column. Are we safe to clear this out?
