### ISSUE TITLE
Require the full API key to authorize API requests.

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1440]
## Description
Require the full API key to authorize API requests.

## Acceptance Criteria
Side quest: since we only verify the last 36 chars of the api key in a request, it is possible that users only use part of the key and we will allow the request to go through.  It also means it is possible that users store only part of their key in source control, and github secret scanning will not find them.
Additional action items:

- [x] Require the full API key in api-key auth'd requests
- [x] Require that the prefix is specifically part of the key (this will force users to store their full key, including in source control, which means we can detect it when they do)
- [x] Check the service id in the middle of the key to ensure it matches the api key used

Given the incident after we merged:
- [ ] communication to clients and timeline when this will go into effect:
- [x] Dev work to change the error message - (this PR needs to be merged in : https://github.com/cds-snc/notification-api/pull/2099/files#diff-c8affbb3ee7a0717b1fdd6e3254396d7afcc3ecb40a02840b5f252237f478b6a)

We previously allowed clients to only send the last 36 characters in their API key, but now we require the entire API key
https://documentation.notification.canada.ca/en/start.html#headers
<img width="1772" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOElLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16b688bcd6f8d55e7839bb26a30db1309c9336b0/Screenshot%202024-01-29%20at%202.36.47%E2%80%AFPM.png" alt="Screenshot 2024-01-29 at 2.36.47 PM.png" />

**Comment by jzbahrai** [comment]
Need to revert this code back: https://github.com/cds-snc/notification-api/pull/2088

**Comment by jzbahrai** [comment]
Query that gives you email address of all users that have api keys permissions and are active
http://localhost:1338/queries/288-user-list-of-all-individuals-who-have-api-management-permission

**Comment by yaelberger-commits** [comment]
Bringing to Story Refinement today to work on the content for communicating to clients

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1440?planning-poker) with Zenhub @amazingphilippe @yaelberger-commits @jzbahrai @YedidaZalik

**Comment by amazingphilippe** [comment]
Waiting on the email content to be translated, sent and the grace period to be over.
