### ISSUE TITLE
Bug: Daily usage counts on dashboard not accurate

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1443]
## Trial service able to send more than daily limit of emails

In prod, using the API, a trial service is able to send more than their daily limit, according to their dashboard 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major

## To Reproduce

1. Go to a trial service in production that sends using the API
2. Try to continue hitting the API continuously after you've hit the 50 emails daily limit
3. See the number of emails sent in a day in the dashboard go over the 50 daily limit
4. See error alert go off in #notification-ops

## Expected behavior

Once a trial service in prod reaches its daily limit of 50 emails a day, it's no longer able to send more messages. An email gets sent, and if they try to hit the API again they get an error message, but no alert goes off 

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: A service in trial could send more than their daily limit in prod

Impact on Recipients:

Impact on Notify team: Alerts going off 

## Additional context

Additional details can be found [in this thread](https://gcdigital.slack.com/archives/C04TQMJCXEW/p1704976159480579). It looks as though the system is correctly limiting sends but the dashboard is not calculating the numbers properly.

**Comment by jzbahrai** [comment]
This is a relevant freshdesk ticket: https://gcdigital.slack.com/archives/C03FA4DJCCU/p1705443606536949

**Comment by andrewleith** [comment]
I'm going to rename this ticket as the scope isn't limited to just trial services.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1443?planning-poker) with Zenhub @andrewleith @jzbahrai @whabanks

**Comment by amazingphilippe** [comment]
Started investigating. slightly different claculations. and timeframes. Figuring out how we can refactor this.

**Comment by andrewleith** [comment]
PR up for review - planning to test this in staging today after the release

**Comment by amazingphilippe** [comment]
QA'd on Friday. Will check again today to continue to work as expected.
