### ISSUE TITLE
Provide support team with instructions on looking out for shared inboxes

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1446]
## Description
Provide support team proper guidance on go live process when users onboard with a shared inbox. (Same guidance as Forms)

WHY are we building?
- For when services go live

WHAT are we building?
- Adapt forms response
- Get it translated
- Add it to the support team canned responses. 

VALUE created by our solution

## Documentation and Artifacts
Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] Cypress UI tests if needed.
- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

## GC Articles Publish checklist
- [ ]  Supporting feature is released and unflagged
- [ ]  Create or update slug
- [ ]  Page content and slug is translated
- [ ]  Document links to and from the page
- [ ]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [ ]  If new page, add WAF rule
- [ ]  Create new page or update existing page content
- [ ]  Create or update translation to the page
- [ ]  Link translations by choosing an assigned translation
- [ ]  If new page, save as draft
- [ ]  If existing page, update the page
- [ ]  Post page in Slack for last minute reviews
- [ ]  On staging: Clear the cache through GC Notify's admin panel
- [ ]  On staging: Check links, images and language toggle
- [ ]  Give a heads up to the app-team channel once ready to publish
- [ ]  On staging and production: Clear the cache through GC Notify's admin panel
- [ ]  Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1446?planning-poker) with Zenhub @yaelberger-commits @mtoutloff @YedidaZalik

**Comment by yaelberger-commits** [comment]
Canned response from Support Team for Forms regarding shared inboxes 
https://gcdigital.slack.com/archives/C0117FN8G9K/p1705349895540759?thread_ts=1705348800.542169&cid=C0117FN8G9K

**Comment by YedidaZalik** [comment]
Created draft for Notify : C[anned response from Support Team for shared inboxes](https://docs.google.com/document/d/1-WbtKJWLD6xDZEi7-IkxYwqA4zB0E7MU3SpqrlZKLKM/edit)

**Comment by YedidaZalik** [comment]
Incorporated Yael's edits. Approved by Yael and Phil.

**Comment by YedidaZalik** [comment]
We began developing this list during story refinement:

**When service goes live, if you suspect it's using a shared inbox:**
Verify it’s shared 
Inform the Notify team
Send template email to the user
Alllow a 30-day grace period
Inform the Notify team when the 30 days have passed 
Notify team  archives the account

**Comment by YedidaZalik** [comment]
Started the checklists in t[his document ](https://docs.google.com/document/d/1-1vkL5ISj0l_TD1z5AkbFKCbvIRolNYiVQqqd9nqiIc/edit)
