### ISSUE TITLE
Current page indicators

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1451]
SC 1.3.1

The section of the site that the user is in is indicated through a visual cue (a thick underline) in the navigation, but no equivalent is provided programmatically. This can be done by adding an aria-current attribute to links within the navigation, and setting the attribute value to "page" when it is displayed as active. See ARIA 1.2 specification description of aria-current for more information. 

<img width="1120" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0NYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b921aa24490d7e07ecb86fde7459a3c3671d5c7b/image.png" alt="image.png" />

## Potential fix
- Add aria-current attribute for current links

**Comment by andrewleith** [comment]
As discussed, I moved the part about confusing navs to #558.

**Comment by YedidaZalik** [comment]
About to put up PR

**Comment by YedidaZalik** [comment]
Implemented changes
Need some extra Q/A 
Andrew will post for review this morning and Phil will review
