### ISSUE TITLE
Close button label

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1452]
Related issues

#761

Consider using a more descriptive label, such as “close navigation” in mobile navigation view. 

<img width="956" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3FYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--923b581f270d6dee9fb613930c01ff056aaa5785/image.png" alt="image.png" />

**Comment by YedidaZalik** [comment]
2 menus on mobile view 
Waiting for review and will tag people
