### ISSUE TITLE
Template formatting use of special characters. Infos and relationships

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1456]
## Description of issue

Special characters are used to allow users to format notifications and define variables in templates. These characters may not be reliably communicated by screen readers.

Screen readers don’t always communicate special characters such as punctuation. Whether characters are read out or not depends on the screen reader, verbosity settings, and whether the character appears on its own or in context. This may make variables and certain kinds of formatting challenging to use for screen reader users. For example, both parentheses used to indicate variables, and underscores used to indicate section breaks and italics are not consistently communicated by screen readers. For a detailed breakdown of screen reader support for special characters, see How screen readers read special characters: an update. 

## Potential fix

- A rich text editor could help users navigate the content of a template without special characters. It might not fix everything, especially with variable parenthesis. 
- Is there a way to mark and announce variables? Would this be confusing?

## Resources

- [How screen readers read special characters](https://www.elevenways.be/en/articles/screenreaders-special-characters)

**Comment by amazingphilippe** [comment]
I recommend bringing this one up with OCADU to get more ideas on how this can be fixed.

**Comment by amazingphilippe** [comment]
Notes from OCADU follow-up:

Template variables: how to tag words. Nothing really reliable in terms of basic html tags. 
1. Really on characters usually read aloud
2. Pseudo content in CSS before placeholder variables. Careful with i18n. Would only work while previewing templates (not while editing)

**Comment by YedidaZalik** [comment]
Yedida looked and agreed it should wait to reconsider vocab

**Comment by YedidaZalik** [comment]
Need to be merged now that have been reviewed

**Comment by foudamo** [comment]
Waiting for Andrew to review
