### ISSUE TITLE
Incorrect type attributes for 2FA input. Identify input purpose

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1457]
## Description of issue

on the Text Verification page and Check Your Email page, the verification code input has type incorrectly set to "tel". As a result, the input is communicated as a phone number text field. 

<img width="1196" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVNYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d4eb7b290f09a8c90f595fa313e9b6d7151e7e8/Capture%20d%E2%80%99e%CC%81cran%2C%20le%202024-01-03%20a%CC%80%2015.20.52.png" alt="Capture d’écran, le 2024-01-03 à 15.20.52.png" />

## Potential fix

- Use the correct input type
- Add the correct autocomplete attribute

## Resources

- [Better 2FA experiences](https://www.twilio.com/blog/html-attributes-two-factor-authentication-autocomplete)

**Comment by YedidaZalik** [comment]
Merged yesterday moving to done
