### ISSUE TITLE
Account creation. Identify input purpose

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1458]
## Description of issue

SC 1.3.5

on the Account Creation page, the name and email address inputs have an autocomplete attribute but the telephone input does not. While the type="tel" attribute for this field does define the intention of the input and allows some browsers to autofill the data, the Understanding Identify Input Purpose document considers it a definition of a very broad category, and suggests the use of the autcomplete attribute for more fine-grained identification of input purpose to meet the criterion. 

## Potential fix

- Add the correct autocomplete attribute

## Resources

- [Understanding Identify Input Purpose](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html)

**Comment by YedidaZalik** [comment]
To be merged today 
In review currently
