### ISSUE TITLE
Request to go live. Reflow

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1459]
## Description of issue

Table on the request to go live page shows overlapping content when screen width is at 320 pixels. 

<img width="666" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3VYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--752b3bd3c3fdc3123b064a6378e62292504707e8/image.png" alt="image.png" />

## Potential fix

- Use a flexbox layout, so that the layout can switch from horizontal to vertical

**Comment by YedidaZalik** [comment]
Merged and can be moved to done
