### ISSUE TITLE
Copy template. Link purpose

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1462]
## Description of issue

on the Copy an existing template page, template links are described by their name, but it is not clear that the link redirects to a copy template page, rather than the template page. Consider adding a bit of additional context to the accessible link name, such as “copy template name template”. Note that in order to support voice control users, the accessible name should contain the exact string of the visible label in its entirety. 

## Potential fix

- Add some descriptive context to each link. 
- Find out what the link does in interaction design terms. Something like: "Copy template name into service name"
- Add some more general context to this screen, so that the interaction is clear. What gets copied where?

**Comment by amazingphilippe** [comment]
Yedida and Phil are looking into why we can't extend sessions to 20 hours.

**Comment by YedidaZalik** [comment]
Just starting on this

**Comment by foudamo** [comment]
William will review
