### ISSUE TITLE
Spike: Test for SQS and batch higher than 10 messages

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#147]
### Spike Question

Does SQS allows for more than 10 messages / second programmatically querying the AWS API?

### Timebox

One day max. but should take less time

### Task outcome

By knowing the answer to the spike's question, we will know if we should use AWS SQS or Redis. The former would be a perfect fit for our batch save queuing mechanism if only for its documented limitations of 10 msg / second revealed to be false. Because if we want to get high throughput from the queue, that will require more logic and code for us to spin up multiple workers that will query 10 messages everytime.

**Comment by jimleroyer** [comment]
## Answer and results

We cannot send more than 10 messages / batch to AWS SQS. After experimenting with the code and reading the documentation, I think it's on purpose for scalability reason, as queue messages might be scattered and retrieving in a small batch maximize the retrieval of these. All operations are restricted to 10 messages including batch insertions as well. \

While we cannot retrieve more than 10 messages per batch call, we can call it multiple times per second. There is a restriction than on how much we can get per second depending on the type of queue we use, i.e. regular or FIFO. [The latter is restricted to 3,000 messages / second](https://aws.amazon.com/sqs/faqs/#:~:text=By%20default%2C%20FIFO%20queues%20support,operations%20per%20second)%20without%20batching.) which should be sufficient for our need. Making multiple calls though would involve a more complex logic in the API to invoke.
