### ISSUE TITLE
DEV: Add link to new demo sign up page from Homepage

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1486]
## Description
As a public servant interested in GC Notify, I need to be able to sign up for a demo from the Homepage, so that I can reduce the number of clicks and steps to get to the sign up for a demo page

WHY are we building?
To increase the likelihood that a public servant will sign up for a demo of GC Notify by making it easier for them to find the link to the sign up page.
 
WHAT are we building?
A link with content on the Homepage directing users to sign up for a demo

VALUE created by our solution
More demo sign ups leading to growth

## Documentation and Artifacts
Example from GC Forms
https://articles.alpha.canada.ca/forms-formulaires/

## Acceptance Criteria
Given a user is on the homepage, when they scroll down to the bottom of the page, then they see a link to sign up for a demo 

- [x] Link to demo sign up page is at the bottom of the Homepage in production as a button "Register for a demo" next to "Try it now" 
- [x] Remove link at the bottom of the Homepage "Want to know more? Get in touch" in both EN/FR pages
- [x] Link on EN page takes you to EN sign up page
- [x] Link on FR page takes you to FR sign up page
- [x] Sign up page loads within 200 milliseconds (dependancy with Growth)
- [x] GC Articles pages are updated 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps
- [x] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1486?planning-poker) with Zenhub @adriannelee @amazingphilippe @YedidaZalik

**Comment by amazingphilippe** [comment]
Figma for demo pages and sections: https://www.figma.com/file/f6QILuxf94EHaStf2ejWJb/Contact-us-%7C-Nous-joindre?type=design&node-id=1338-4945&mode=design

**Comment by amazingphilippe** [comment]
Sent to translation

**Comment by foudamo** [comment]
Translated! @YedidaZalik will add the translation to this card

**Comment by YedidaZalik** [comment]
Translation is back https://www.figma.com/file/f6QILuxf94EHaStf2ejWJb/Contact-us-%7C-Nous-joindre?type=design&node-id=1384-159&mode=design&t=JGfUy2IkLNuoWAFC-0

Do we need annotate ?

**Comment by YedidaZalik** [comment]
Figma screen with both languages
https://www.figma.com/file/f6QILuxf94EHaStf2ejWJb/Contact-us-%7C-Nous-joindre?type=design&node-id=1405-3316&mode=design&t=NeFD3CI8fhMorSr8-0

**Comment by YedidaZalik** [comment]
Created GC articles pages (without images or demo dates yet)
Permalink for EN is register-for-a-demo and for FR is sinscrire-a-une-demo

**Comment by andrewleith** [comment]
Updates have been merged to staging, awaiting QA.
