### ISSUE TITLE
Coded prototype for 'What is a Service'

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1488]
## Description
As a tester for Notify researcher, I need to be able to do complete an interactive task so that I can provide an account of my experience. 

WHY are we building?
- To understand if a live preview helps users understand how their identity will work, we need to create an interactive prototype with code, that reacts to their typing.
- To understand if such an interaction is accessible, we can also use this prototype with Fable testers and find out how we can improve it further.  

WHAT are we building?
- An environment to build experimental features with code
- A first prototype to test the interaction of previewing service name and email. 
- All the screens in this [Figma file](https://www.figma.com/file/1ccAvKpMboyDmnUliunnBY/Onboarding-and-set-up-%7C-Embarquement-et-configuration?type=design&node-id=2438-2665&mode=design&t=KgtXrlFRsFv4lCIL-0)

VALUE created by our solution
- Reduce the complexity of building and testing new features.

## Documentation and Artifacts
- [Figma prototype
](https://www.figma.com/file/1ccAvKpMboyDmnUliunnBY/Onboarding-and-set-up-%7C-Embarquement-et-configuration?type=design&node-id=2438-2665&mode=design)

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Prototyping environment is on Github
- [x] Prototype is hosted somewhere, maybe on Github, or Netlify
- [x] Prototype is built and reviewed by researcher and adjusted as needed. 
- [x] Prototype is translated
- [ ] Prototype is reviewed one random team member, in both languages

**Comment by amazingphilippe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1488?planning-poker) with Zenhub @andrewleith

**Comment by amazingphilippe** [comment]
Andrew and I have been working on a working version. The page is ready, aside from translations. We also need to figure out hosting, so that we can start the reviewing process with the team.

**Comment by andrewleith** [comment]
Prototype is now hosted on github, see slack for URL.

**Comment by amazingphilippe** [comment]
We need one team member to go through prototypes and check if things work properly and match the Figma screens.

**Comment by yaelberger-commits** [comment]
Prototype was demoed to Stakeholders at team demo this morning
