### ISSUE TITLE
DEV: Add functionality for sending email and SMS in Inuktitut

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1489]
## Description
As a public servant delivery public services in Nunavut, I need to be able to send email, and eventually SMS in Inuktitut, so that I can provide notifications in the recipients language of choice. 

WHY are we building?
The Indigenous Languages Act (The Act) received Royal Assent in June 2019. The overall purpose of the Act is to support the efforts of Indigenous Peoples to reclaim, revitalize, maintain, and strengthen Indigenous languages.
We have an opportunity to pilot messages in Inuktitut.

WHAT are we building?
Functionality for GC Notify to send emails and SMS messages in Inuktitut

VALUE created by our solution
Recipients have increased satisfaction with government services because they can receive messages in their language of choice.

## Documentation and Artifacts
https://docs.google.com/document/d/1VMT5HWR4eg6zmPOVqQNjcw-4FGfEu4TUgNOlHWZdEts/edit

## Acceptance Criteria
Given a GC Notify service wants to send an email or SMS message in Inuktitut, when the recipient reads the message, then all characters are rendered properly and in a readable and user friendly fashion and the reliability of the message delivery is just as high as for EN and FR messages sent through GC Notify.

- [x] Test messages can be sent via email
- [x] Test messages can be sent via text 
- [x] Onboard correct character set for Inuktitut letters/characters 
- [x] Test cost for an SMS message in Inuktitut
- [ ] Consult Policy 
- [x] Consult Designers at Story Refinement or Dev/Design Review
- [x] Review by @yaelberger-commits PM 
- [x] Demo to Head of Notify @ioanacontu in Staging
- [x] Enable functionality to send Email to a recipient in Inuktitut that is delivered and displays properly in production
- [x] Enable functionality to send SMS to a recipient in Inuktitut that is delivered and displays properly in production
- [ ] Announce the change in New Features but first meet with @ioanacontu and Lesley

* A11y
* Internationalization
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps
- [x] Email sent to a recipient in Inuktitut is delivered and displays properly
- [x] SMS sent to a recipient in Inuktitut is delivered and displays properly

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1489?planning-poker) with Zenhub @yaelberger-commits @jzbahrai @whabanks @amazingphilippe @andrewleith

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1489?planning-poker) with Zenhub @mtoutloff

**Comment by amazingphilippe** [comment]
Just passing along a typography that might help preview messages in the admin interface: https://fonts.google.com/noto/specimen/Noto+Sans+Canadian+Aboriginal. Our current font does not support the glyphs.

**Comment by yaelberger-commits** [comment]
Email: Language tag feature in FR and EN, but not for other languages 
Font we use may not support there characters

**Comment by yaelberger-commits** [comment]
Email: Language tag feature in FR and EN, but not for other languages 
Font we use may not support there characters

**Comment by jzbahrai** [comment]
Using this: https://www.lexilogos.com/keyboard/inuktitut.htm

**Comment by yaelberger-commits** [comment]
Costs: it isn't an exact calculation. You don't get the 160 characters that you get when you send ascii-english. Some of the characters count for more/ some less.

**Comment by amazingphilippe** [comment]
Will tested on API and admin. Not merged. Merge to staging so more can do tests.

**Comment by amazingphilippe** [comment]
- Demoed for Ioana
- Also works with other languages

Risks discussed:
- Discussed the fonts
- Not yet tested with real users

Someone else will decide:
- Costs we can accept
- Risks we are ok with

**Comment by foudamo** [comment]
This is done! But it hasn't been promoted yet. @mtoutloff will write a policy analysis on it later (but it doesn't hold back the card)
