### ISSUE TITLE
Change the API: The API needs to call the Redis/SQS queue

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#149]
### Task Description

Wire the Redis/SQS queue with the REST API.

### Task Outcome

Change the REST API to call the redis tasks to save the notifications and deal with that interaction.

### Acceptance Criteria

- [x] tests are written against the new code to ensure that POSTS use the redis logic
- [x] A batch saving worker is processing the REST API call.
- [x] Dry code
### Additional Notes

**Comment by jzbahrai** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/149?planning-poker) with ZenHub @iokpala @jimleroyer @sastels

**Comment by adriannelee** [comment]
Steve will update what 'proper' means in the acceptance criteria. But pretty much done
