### ISSUE TITLE
DEV: Update the System Status Page with new definitions

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1490]
## Description
We need to update the system status lambda with new definitions here:
https://docs.google.com/document/d/1FScEoP16Jo1VhnmZugOeMsVjV-K1p8QKMpexxRpaHpc/edit#heading=h.6g6ne23dimk7

## Acceptance Criteria hypotheses on the Research Airtable
- [x] Update the system status lambda with the new definitions
- [x] Add tests that can be run on CI for lambda instead of utils

## QA Steps
- [x] Test in staging

**Comment by foudamo** [comment]
@whabanks @andrewleith whoever is ready to pick it up, can pick it up

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1490?planning-poker) with Zenhub @jzbahrai @whabanks @andrewleith

**Comment by yaelberger-commits** [comment]
Reminder @jzbahrai and @whabanks this card needs your estimates

**Comment by yaelberger-commits** [comment]
Manually changed manifest, need to confirm deployment

**Comment by yaelberger-commits** [comment]
Live in Staging now
