### ISSUE TITLE
SaaS Guidance and Analysis of Quicksight 

### ISSUE THREAD

**Issue by mtoutloff** [cds-snc/notification-planning#1493]
## Description
The Core Team has asked whether they can use Quicksight to analyze Notify user data. We will be using the SaaS guidance tool to determine whether the team can use Quicksight, assess security and privacy risks, and document the assessment and the use of the tool. 

## Acceptance Criteria
When the SaaS Guidance questionnaire is completed, a determination will be made as to whether the tool can be used. 

- [x] Meeting with Security to over SaaS guidance tool.
- [ ] Complete the SaaS Guidance questionnaire 
- [ ] Address any issues that come up in the questionnaire
- [ ] Seek further approvals, if necessary

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

SaaS Guidance tool for Quicksight: https://docs.google.com/document/d/1sTHPKOJa3Lc2AVzZIfl0fBcp_pLR63ok9m0aV6AvTVo/edit

**Comment by amazingphilippe** [comment]
Met with Jimmy and Steve to talk about the assessment.

**Comment by foudamo** [comment]
with Charly at the moment, @mtoutloff will follow up

**Comment by mtoutloff** [comment]
We are waiting on finalizing this assessment, as the organization was going to decide what to do with BI tools (Quicksight may not be what we end up with)
