### ISSUE TITLE
Prototype test: 'Service'

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1502]
To-do: 
- [x] Conduct sessions
- [x] Tag notes
- [x] Analyze the tags
- [x] Prepare presentation
- [x] Present

**Comment by yaelberger-commits** [comment]
Adrianne went through notes from sessions and started synthesis

**Comment by adriannelee** [comment]
Notes have been tagged, and started synthesis yesterday. Will continue synthesis today (but it's a shorter day for me)

**Comment by adriannelee** [comment]
Presenting today!
