### ISSUE TITLE
Research analysis: Conversion

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1504]
[Planning card](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1409)

To-do:
- [x] Conduct sessions
- [x] Tag the notes
- [x] Analyze the tags
- [x] Prepare presentation
- [x] Present

**Comment by adriannelee** [comment]
Finished reviewing notes from other facilitator's sessions and finished tagging the notes. Will continue analysis on Monday.

**Comment by whabanks** [comment]
Meeting with Jeanna to coordinate on analysis and presentation next week
