### ISSUE TITLE
Run performance tests against the batch save

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#151]
### Task Description

Run performance tests against the batch save with feature flag enabled in the staging environment.

### Task Outcome

Comparison performance tests metrics are provided between the feature flag for batch save ENABLED and DISABLED.

### Acceptance Criteria

- [ ] Provide various metrics with feature flag for batch save set to ENABLED: performance tests, Redis/SQS number of messages over time, Redis memory consumption, in-flight mode usage, etc...
- [ ] Provide various metrics with feature flag for batch save set to DISABLED: performance tests, Redis/SQS number of messages over time, Redis memory consumption, in-flight mode usage, etc...

### Additional Notes

We want to know how the overall thing performs. Ideally, **push it to break it**.

**Comment by jimleroyer** [comment]
Moving it back to product backlog, let's re-evaluate this task on next sprint planning.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/151?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by yaelberger-commits** [comment]
We've run performance tests multiple times and feel confident
