### ISSUE TITLE
Offboarding Adrianne

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1517]
# Description 

Here are some tasks to go through and access that needs to be revoked as you offboard from the Notify team.

Present checklist is here to help us track progress and completion of this.

**Done when** :  PM has checked that all access has been revoked and all documentation, responsibilities have been transferred, the [audit document](https://docs.google.com/spreadsheets/d/1nqRmotJvNY_ftNwr5R7_tk2HKrveNRBA-R77kNTU-FM/edit#gid=0) has been updated with new grants and the onboarding task revised with updated roles.

#  Transfer files and meetings 

# Meetings and handoff

- [x] Meet with PM to go over offboarding checklist
~- [ ] Meet with incoming team member, if applicable, for handover~

# Revoke access

- [x] Remove Slack channel access [DM or PM]
- [ ] Remove Google Drive access [DM or PM]
- [ ] Remove Figma access [Designer @amazingphilippe ]
- [x] Remove platform admin access [Dev lead contact: @jimleroyer ]
- [x] Remove GitHub Access [Contact: Slack #sre-and-tech-ops]. Request to be removed from GitHub teams as well
- [x] Remove Zenhub Access [Contact: PM]
- [ ] Remove Airtable Access [Contact: @adriannelee]
- [x] Remove GC Articles Access [Contact: @amazingphilippe]

# Revoke access for Dev  ⌨️

~- [ ] LastPass and shared Notify folders inside of it (Staging and prod credentials, environment variables for running the repo locally) [**Contact**: @jimleroyer ]
- [x] AWS (staging and production accounts) Error log monitoring ; S3 buckets for asset management [ #zendesk-it-support or /zendesk Slack command ]
- [ ] New Relic (Error logging / debugging for production) [ #zendesk-it-support or /zendesk Slack command ]~
- [x] Freshdesk Customer ticket support portal [ #zendesk-it-support or /zendesk Slack command ]
- [ ] Remove from notifications-ops on Google
- [x] Remove platform admin access [Dev lead contact: @jimleroyer ]
~- [ ] Easy Retro **[Contact: Mario]**~

**Comment by mtoutloff** [comment]
Still need to revoke accesses - for Jimmy or Jumana to do
Will wait until April 1 to remove accesses

**Comment by yaelberger-commits** [comment]
Adrianne has left Slack channels and Yael has removed Adrianne from meeting invites (except for Notify Demo)

**Comment by yaelberger-commits** [comment]
Access that needed to be removed has been. Card is done
