### ISSUE TITLE
Email template contains generic text

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1527]
## Description of issue

The template for an email contains a full HTML page structure.  In `<head>` tag, [the template contains](https://github.com/cds-snc/notification-utils/blob/main/notifications_utils/jinja_templates/email/email_template.jinja2#L9):
```
<title>Page Title</title>
```

Although this text is not seen anywhere visually, it is possible that it is read by some assistive tech in some situation. 

## Potential fix
- Replace `Page Title` with the subject of the template being sent.

**Comment by andrewleith** [comment]
@jzbahrai to review.

**Comment by YedidaZalik** [comment]
Just merged, moving to done
