### ISSUE TITLE
Uploading Promo videos to Website

### ISSUE THREAD

**Issue by keenan-wong** [cds-snc/notification-planning#1531]
## Description
As a prospective client or someone who has little or not knowledge of Notify, I need to be able to watch the Notify promo video so that I can achieve get the most important points about the product in 90 seconds.

WHY are we building?
- So that the video appears at the correct touchpoint in the acquisition funnel
- For maximum viewing potential

WHAT are we building?
- Embedding the video on the Why GC Notify and Register for a Demo pages in EN and FR
- Can be uploaded with hardcoded subtitles or with a subtitle file
- Can be embedded from YouTube if that's simpler (dependency on Outreach uploading the videos first)

VALUE created by our solution
- Having the video available on our owned channel adds reputation and ease in viewing it. A video is a succinct and enjoyable way to learn about the product.

## Documentation and Artifacts
Video files available here
EN: https://drive.google.com/drive/folders/1mt4LZ_4PtSIsYqW7u3tG2MguK8D16a-6?usp=sharing
FR: https://drive.google.com/drive/folders/1n-0J0UutEjOy2cZsgWT10RnjEUPLUAxs?usp=drive_link

Described text
EN: https://docs.google.com/document/d/1y14OluTyJxwH_cRt3jaP9TsBli7n_LRlcjf-vva1JaU/edit
FR:

## Acceptance Criteria
Given someone wants to learn more about the value of GC Notify, when they visit the public website, then they can watch a video in EN or FR that is accessible and learn about the main value propositions of GC Notify within 90 seconds. 

- [x] Video loads within 200 milliseconds?
- [ ] Video is WCAG 2.1 AA compliant for accessibility
- [x] Video is available in EN and in FR on each respective page
- [x] Cypress UI tests if needed.
~~- [ ] GA4 metrics set up to track views~~

* A11y
* Bilingualism
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

## GC Articles Publish checklist
- [ ]  Supporting feature is released and unflagged
- [ ]  Create or update slug
- [ ]  Page content and slug is translated
- [ ]  Document links to and from the page
- [ ]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [ ]  If new page, add WAF rule
- [x]  Create new page or update existing page content
- [x]  Create or update translation to the page
- [ ]  Link translations by choosing an assigned translation
- [ ]  If new page, save as draft
- [x]  If existing page, update the page
- [x]  Post page in Slack for last minute reviews
- [ ]  On staging: Clear the cache through GC Notify's admin panel
- [ ]  On staging: Check links, images and language toggle
- [ ]  Give a heads up to the app-team channel once ready to publish
- [x]  On staging and production: Clear the cache through GC Notify's admin panel
- [ ]  Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1531?planning-poker) with Zenhub @amazingphilippe @andrewleith @jzbahrai @whabanks @YedidaZalik

**Comment by yaelberger-commits** [comment]
Having difficulty with the videos and how they're appearing when published so we need to troubleshoot this

**Comment by YedidaZalik** [comment]
Reviewed and made some suggestions using the suggest function in google docs

**Comment by yaelberger-commits** [comment]
The Promo Videos for GC Notify are now live on the public website
https://notification.canada.ca/why-gc-notify
https://notification.canada.ca/pourquoi-notification-gc
https://notification.canada.ca/register-for-a-demo
https://notification.canada.ca/sinscrire-a-une-demo
@Keenan will QA review to make sure everything looks and works as expected
Once we have the translated transcripts with descriptive text, I’ll go in and replace the current transcripts with the new ones.

**Comment by yaelberger-commits** [comment]
We're blocked currently on GA4 for tracking the video engagement

**Comment by yaelberger-commits** [comment]
Decided not to pursue GA4 tracking at this time. Last piece we're waiting on is descriptive text

**Comment by andrewleith** [comment]
- waiting on translation for descriptive text

**Comment by yaelberger-commits** [comment]
Translation due back 1 week from today

**Comment by andrewleith** [comment]
- @yaelberger-commits  to update transcripts today
