### ISSUE TITLE
Sends communication to the user when their callback URL fails

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1535]
## Description
As a Notify user, I need to know when my callback fails so that I can fix it and not lose message receipts.

WHY are we building?
- Callback failures impact Notify by slowing down the system
- Callback failures also impact users as they could not get status updates for their messages

WHAT are we building?
Put a feature in place that automatically notifies system owners when there is a problem with their callback.

VALUE created by our solution
Callbacks will (hopefully) be fixed without Notify support intervention.

## Acceptance Criteria

- [ ] We decide who will be auto-notified.
- [ ] We decide what amount / types of failures warrant service owner notification.
- [ ] code in place that automatically contacts those people when there is sufficient level of failures.
- [ ] Warning send to ops channel when this happens.

## QA Steps
- [ ] Hook up Notify to a working callback. Check that you get the receipt but not a warning email.
- [ ] Hook up Notifiy to a failing callback. Check that you get the warning email.

## Related Incident
[2024-03-28-notify-is-spitting-out-a-bunch-of-errors](https://docs.google.com/document/d/1rmVMVixlTYdMchvUCzKXr2YbcRK1o2vIiMsOK7Eeyvc)

**Comment by whabanks** [comment]
This work is currently in progress as part of: [1564 - Detect incorrectly configured callbacks](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1564)
