### ISSUE TITLE
Validate callback URL when it is provided

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1537]
# Description
When a user adds a callback URL to their service add some validation to check that it works.  Some ideas:
- URL is valid (DNS lookup succeeds)
- POST to callback URL responds within 1000ms 

If the URL is invalid or the ping takes longer than 1000ms, warn the user but still proceed.

## WHY are we building?
To help users identify when they might have a problem with their callback server.

## WHAT are we building?
UI validations to warn the user in certain cases.

## VALUE created by our solution
Users take appropriate action to ensure their callback servers can respond fast enough.

## Documentation and Artifacts
According to new relic data for the past 6 months, here is the breakdown of our current callback response times:
- MIN	`81ms`
- MAX	`2665ms`
- AVG	`557ms`

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] Cypress UI tests if needed.
- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

## GC Articles Publish checklist
- [ ]  Supporting feature is released and unflagged
- [ ]  Create or update slug
- [ ]  Page content and slug is translated
- [ ]  Document links to and from the page
- [ ]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [ ]  If new page, add WAF rule
- [ ]  Create new page or update existing page content
- [ ]  Create or update translation to the page
- [ ]  Link translations by choosing an assigned translation
- [ ]  If new page, save as draft
- [ ]  If existing page, update the page
- [ ]  Post page in Slack for last minute reviews
- [ ]  On staging: Clear the cache through GC Notify's admin panel
- [ ]  On staging: Check links, images and language toggle
- [ ]  Give a heads up to the app-team channel once ready to publish
- [ ]  On staging and production: Clear the cache through GC Notify's admin panel
- [ ]  Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by yaelberger-commits** [comment]
@whabanks is this covered by the work you're currently doing? Should this card also be "In Progress?"

**Comment by whabanks** [comment]
This is currently in progress as part of the work on [1564](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1564). There are some good details in this card about the criteria for pinging their callback service.
We can add these details to 1564 and close this card.

**Comment by yaelberger-commits** [comment]
Merged these notes to #1564 and closing this one now
