### ISSUE TITLE
Design the fields for english and french alt text intake

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1547]
# Description

As an admin user, I need to be able to add/ edit the alt text on the following two screens
https://notification.canada.ca/email-branding/158fdc1c-01ea-4d1c-a208-334d756f3415/edit
https://notification.canada.ca/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/branding-request

## Acceptance Criteria

- [x] Figma Designs to add alt text to the above two screens

**Comment by jzbahrai** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1547?planning-poker) with Zenhub @amazingphilippe

**Comment by amazingphilippe** [comment]
Designed and coded a component for localized inputs. 
- [Figma](https://www.figma.com/file/alnDnSW1Efi3Lae3uHf6Pj/Component-library-%7C-Biblioth%C3%A8que-de-composantes?type=design&node-id=4978-2590&mode=design)
- [PR with the new component macro](https://github.com/cds-snc/notification-admin/pull/1820)

**Comment by yaelberger-commits** [comment]
Is this work done now @amazingphilippe ?

**Comment by amazingphilippe** [comment]
It is now! For documentation's sake: I needed to finish building the component in our figma library so it could be reused in future work.
