### ISSUE TITLE
Review short code terms and conditions

### ISSUE THREAD

**Issue by mtoutloff** [cds-snc/notification-planning#1550]
## Description
GC Notify recently received approval for a general use short code and the terms and conditions will need to be reviewed to make sure we are following all the requirements. 

WHY are we building?
To summarize and understand the terms and conditions for the short code
WHAT are we building?
A plain text summary of the short code terms and conditions
VALUE created by our solution
To create awareness of the requirements 

https://drive.google.com/drive/folders/14godYMcoKiXH0XoTPqCiqx4jit3-Rosq 

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Review short Ts&Cs and draft summary 
- [x] Share with SRE if they need to review 
- [x] Share summary with team

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by mtoutloff** [comment]
Going through Ts&Cs

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1550?planning-poker) with Zenhub @mtoutloff

**Comment by mtoutloff** [comment]
Finished summary and shared with Yael and Jimmy and Calvin to see if someone at SRE should also take a look

**Comment by yaelberger-commits** [comment]
I have reviewed. LGTM

**Comment by mtoutloff** [comment]
Jimmy submitted a ticket with AWS about any short code term limits, per the Ts&Cs

**Comment by mtoutloff** [comment]
Followed up with Guillaume and he mentioned that he has some comments he will share with us shortly

**Comment by mtoutloff** [comment]
Received comments from SRE provided responses and tagged Jimmy and Yael in a couple responses

**Comment by mtoutloff** [comment]
Followed up with Jimmy R to respond to SRE comments

**Comment by mtoutloff** [comment]
Jimmy R provided responses to SRE's comments. Waiting for confirmation from SRE on the responses

**Comment by mtoutloff** [comment]
Followed up with Guillaume (SRE) to see if we can close the loop on this

**Comment by mtoutloff** [comment]
Guillaume reviewed remaining comments, and can close the loop on this.
