### ISSUE TITLE
Broken link on System Status Page (EN only!)

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1553]
## Describe the bug 

We have a broken link on the EN System Status Page: [https://status.notification.canada.ca/security](https://status.notification.canada.ca/security)
This is the security statement linked from the bottom of the status page. Not sure if it meant to link [here](https://notification.canada.ca/security)?

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

1. Go to 'https://status.notification.canada.ca/' (EN page only)
2. Click on 'To learn about GC Notify’s security practices, visit our **Security statement**.'
3. See error: This XML file does not appear to have any style information associated with it. The document tree is shown below.

## Expected behavior

When you choose the link "Security Statement" it should take you to this page https://notification.canada.ca/security

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users: Users who try to choose the Security Statement from the System Status Page in EN will get a broken link

Impact on Recipients: N/A

Impact on Notify team: N/A

## Screenshots

<img width="1481" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUMwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d31c976798a9e83a10bb940b6b0220b32f9d0bd/Screenshot%202024-05-03%20at%2011.08.34%E2%80%AFAM.png" alt="Screenshot 2024-05-03 at 11.08.34 AM.png" />

<img width="1444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUswQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--358812a28593d2fe08ec92d2e59eb00513a061dd/Screenshot%202024-05-03%20at%2011.08.48%E2%80%AFAM.png" alt="Screenshot 2024-05-03 at 11.08.48 AM.png" />

<img width="1992" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU8wQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed02d413cdf18e9fb69b4e3e72c111fcc9e266d0/Screenshot%202024-05-03%20at%2011.09.51%E2%80%AFAM.png" alt="Screenshot 2024-05-03 at 11.09.51 AM.png" />

**Comment by jzbahrai** [comment]
this article was referencing the wrong statement: https://articles.alpha.canada.ca/notification-gc-notify/wp-admin/post.php?post=870&action=edit

I fixed and cleared cache
