### ISSUE TITLE
Detect incorrectly configured callbacks

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1564]
## Description
As a user, I need to be warned if the callback configuration I set for my service is not working, so that I can take steps to fix (or disable) it.

- WHY are we building?
   - To alert service users when their service is incorrectly configured
   - To help users identify when they might have a problem with their callback server.

- WHAT are we building?
Things to build:
   - A notification when callbacks fail 
   - UI validations to warn the user in certain cases.
- VALUE created by our solution
   - The system works as expected from the user's point of view
   - Users take appropriate action to ensure their callback servers can respond fast enough.
Details from other card cc @whabanks 
When a user adds a callback URL to their service add some validation to check that it works. Some ideas:

- URL is valid (DNS lookup succeeds)

- POST to callback URL responds within 1000ms

If the URL is invalid or the ping takes longer than 1000ms, warn the user but still proceed.

## Documentation and Artifacts
There are two things we could try here:
1. Validate the callback when it is setup
2. Alert if the callback fai
3. ls consistently after setup

According to new relic data for the past 6 months, here is the breakdown of our current callback response times:

MIN 81ms
MAX 2665ms
AVG 557ms

### Validate at setup time
When a user initially adds a callback, we could check it for a few things:
- valid hostname
- acceptable response time (I'm not sure if we can actually check this outside of making a true callback though)
- **other things?**
 
### Alert on the fly
Automatically send service users a warning email if:
- A callback is failing consistently (this needs to be defined)
- A callback is consistently taking too long to respond (threshold needs to be defined)
- The callback URL can't be resolved via DNS
- **others things?**

## Acceptance Criteria
- [ ] What is the threshold for alerts? How long should the callbacks be slow and over what period?
- [ ]  Define an SLA 1000ms?(lets look at it)
- [x] Change the config on max retries for callbacks to 1s 
~- [ ] At max retries send an email to the clients letting them know~ ([Part of this work](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1647))
~- [ ] Email must be only sent once a day for slow callbacks (look at the SMS limits)~ ([Part of this work](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1647))
- [ ] Change the content page - to show callbacks testing + let them know about the response time and that we want them to respond within 1s (devs to design this content)
~- [ ] Update API documentation about callback timeouts ()~ (Ppart of this work](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1649))
- [ ] Update product updates with this info as well

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

## GC Articles Publish checklist
- [ ]  Supporting feature is released and unflagged
- [ ]  Create or update slug
- [ ]  Page content and slug is translated
- [ ]  Document links to and from the page
- [ ]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [ ]  If new page, add WAF rule
- [ ]  Create new page or update existing page content
- [ ]  Create or update translation to the page
- [ ]  Link translations by choosing an assigned translation
- [ ]  If new page, save as draft
- [ ]  If existing page, update the page
- [ ]  Post page in Slack for last minute reviews
- [ ]  On staging: Clear the cache through GC Notify's admin panel
- [ ]  On staging: Check links, images and language toggle
- [ ]  Give a heads up to the app-team channel once ready to publish
- [ ]  On staging and production: Clear the cache through GC Notify's admin panel
- [ ]  Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by yaelberger-commits** [comment]
Would there ever be a scenario where all our callbacks are failing because the component or feature is down? If so, maybe we add monitoring of this feature to our System Status Page as well eventually? This would be in addition to notifications to individual services if their own callbacks are misconfigured

**Comment by whabanks** [comment]
[Draft PR](https://github.com/cds-snc/notification-admin/pull/1855) is up with: 
- Validation checks on the URL itself
- Reachability checks to ensure the endpoint can be hit before we create and bind the callback url to the service.
- Placeholder UI error messages (Need actual content + translations)
- Logging to support any alerts we may need to create

Invalid URL:

<img width="844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8493cb444eb7dc41c583d385f5d4e006d0171d59/image.png" alt="image.png" />

Reachable but response indicates failures:

<img width="831" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04dd0136ab62f6a518e5212cb2c9afdd39b65c7a/image.png" alt="image.png" />

Unreachable callback URL:

<img width="838" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f62e33298eda27f0364538a27953e8ec4b1ab15b/image.png" alt="image.png" />



TODO:
- Add dynamic hint text to the field depending on the type of error returned.
- Define a reasonable response time threshold (Currently set to 5 seconds)
- Define a threshold for what we consider "Consistent callback delivery failures" and create alarms to track this
- Craft an email notification to send to users to inform them that their callbacks aren't reliably working
- Implement the email sending

**Comment by YedidaZalik** [comment]
Reviewed doc from Will on the incorrectly configured callback card https://docs.google.com/document/d/1h4NyX0Pe5-Ck949frpfc0osSi5F4c5OOc2-2cIgoVn0/edit#heading=h.tgmnzpe2m78k

Started email draft https://docs.google.com/document/d/1yUgerRyr6bcLu0TyoI__XO2L-m28YHcfp8za5ueTlvw/edit

**Comment by whabanks** [comment]
Added some draft alarms that will need some tweaking once we agree on the thresholds/definition for "consistently failing".

Added the callback failure warning email to API and started work implementing the email sending. Some questions rose around potentially pausing retries while a service is within a certain threshold or not.

Scheduled a meeting for this afternoon to discuss thresholds and whether we want to pause retries or not.

**Comment by andrewleith** [comment]
- with translation now

**Comment by andrewleith** [comment]
- Translation may take longer as other work is prioritized over this
- Still trying to figure out if we can ping services successfully without making a breaking change

**Comment by yaelberger-commits** [comment]
Merged notes from #1537 Validate callback URL when it is provided

**Comment by YedidaZalik** [comment]
MSB is back and working on localizing the email.

**Comment by amazingphilippe** [comment]
Bringing this to story refinement.

**Comment by YedidaZalik** [comment]
Email is ready: https://docs.google.com/document/d/1yUgerRyr6bcLu0TyoI__XO2L-m28YHcfp8za5ueTlvw/edit#heading=h.vslfc8bys6uc

**Comment by mtoutloff** [comment]
Retesting what we had currently and adjusting user experience
Will be reviewed in Dev Design review meeting

**Comment by mtoutloff** [comment]
Team will review

**Comment by mtoutloff** [comment]
@whabanks working on this today

**Comment by jzbahrai** [comment]
I am going to shut this ticket - most of this is covered in other tickets in this epic: https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1644
