### ISSUE TITLE
ADR for short code implementation (App Team)

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1571]
## Description
As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Documentation and Artifacts
https://github.com/cds-snc/notification-adr/pull/69/files?short_path=8287158#diff-828715828f8c151d04893b37ee67484650d9b914d2e1b0abc815422e8b617d74

## Acceptance Criteria

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1571?planning-poker) with Zenhub @jzbahrai

**Comment by andrewleith** [comment]
- Deadline for review is tomorrow! @whabanks has reviewed, @andrewleith to review

**Comment by yaelberger-commits** [comment]
Yael is currently reviewing async. Meeting with Jumana scheduled for Thursday

**Comment by andrewleith** [comment]
- New diagram added to ADR
- Started creating some tickets

**Comment by yaelberger-commits** [comment]
@jzbahrai when it comes time to work through which LLM we might use for assigning template categories to existing 12,600 templates, Jeana is available to join us for a meeting to consult on options. She has done some work with ChatGPT for analyzing/categorizing some data.

**Comment by andrewleith** [comment]
- @jzbahrai started getting LLama working
