### ISSUE TITLE
New Features updates for a11y improvements

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1574]
New post for New Features includes

- [x] Updated A11y Statement
- [x] New Sitemap
- [x] Alt Text for custom logos
- [x] 
DRAFT
https://docs.google.com/document/d/1EA87Wdd1nUdkc0B1fZOOspyg7e64ajcXNJ2ETZn8enc/edit

- [x] Localization/translation
- [x] Published on GC Articles New features with the correct date
- [x] Clear Cache

**Comment by yaelberger-commits** [comment]
Ready for translation

**Comment by yaelberger-commits** [comment]
We will need to link to the Guidance index page once it's released. 
We won't post this until after the guidance page is released

**Comment by yaelberger-commits** [comment]
Ideally we post this before June 1

**Comment by andrewleith** [comment]
- waiting on translation

**Comment by YedidaZalik** [comment]
Translation is back, it follows the English in this document
https://docs.google.com/document/d/1EA87Wdd1nUdkc0B1fZOOspyg7e64ajcXNJ2ETZn8enc/edit#heading=h.m4zehab8xgrl

**Comment by yaelberger-commits** [comment]
Blocked until the Guidance Index page is released to production so we can link to it

**Comment by yaelberger-commits** [comment]
Changes are live 
https://notification.canada.ca/new-features
https://notification.canada.ca/nouvelles-fonctionnalites

**Comment by andrewleith** [comment]
- could thing about writing documentation to make the posting process easier
