### ISSUE TITLE
Produce list of third party vendors interacting with Notify

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#158]
### Task Description

Produce list of third party vendors interacting with Notify. In the context of the ATO, we need to perform a risk assessment of each of these tools, but we need a formal list handed to the security team. 

### Task Outcome

* List of third party vendors under an agreed-upon format discussed with the security team.

### Acceptance Criteria

- [x] Produce and hand the list of vendors to the security team.
- [x] Put a link to the list document [in the risk register](https://docs.google.com/spreadsheets/d/1GSBptkZe1r1GoTNntGesI31B8eZkTQ4ItTdd172eeOw/edit#gid=0).

### Additional Notes

* This is a blocker to the list of action items from the ATO.

**Comment by jimleroyer** [comment]
Produced the following list for @wmoussa-cds :

* AWS
* Freshdesk
* Github
* Heroku
* LastPass
* lgtm.com
* NewRelic
* OpsGenie
* Sentry (in staging only so far)
* Slack?
* Snyk
* Zendesk
* Zenhub

**Comment by yaelberger-commits** [comment]
Need an OK from @wmoussa-cds

**Comment by wmoussa-cds** [comment]
this is good, thanks for providing the list Jimmy
