### ISSUE TITLE
Design + Dev Admin: Add TemplateCategory

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1588]
## Description
As an Admin user I want to add a Template Category
Similar to how we can add Brands, an Admin user can go an add a new TemplateCategory

## Acceptance Criteria

- [x] Design to add a new TemplateCategory
- [x] Design to view all existing TemplateCategory and edit if necessary
- [x] Dev frontend work for adding the design

**Comment by amazingphilippe** [comment]
First round of wireframes and mockups following dev design review:
https://www.figma.com/design/RLcM0JwlQsd2uVK3GJr5qY/Templates-%7C-Gabarits?node-id=2886-3681&t=Yd8TjnISG85PC4gS-4


List of screens for MVP
- Template browser with categories
- Edit/Create template
- Tell us more about "other" category form
- Category list in admin
- Edit/Create category in admin

**Comment by YedidaZalik** [comment]
Entered some suggestions in Figma

**Comment by amazingphilippe** [comment]
Template category admin is live on prod.

**Comment by amazingphilippe** [comment]
Mockups can be translated from [Figma](https://www.figma.com/design/RLcM0JwlQsd2uVK3GJr5qY/Templates-%7C-Gabarits?node-id=3050-1513)

**Comment by amazingphilippe** [comment]
Front end has been merged, in backlog until we can hook up with the back end

**Comment by andrewleith** [comment]
Working on having the platform admin template categories functional today.
