### ISSUE TITLE
Dev: Create TemplateCategory + API TemplateCategory

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1590]
## Description
As a user I need to be able to interact with the TemplateCategory table

## Acceptance Criteria
- [x] Create a TemplateCategory Table with 
         id, name_en, name_fr, description_en, description_fr,(description is not required), sms_process_type, email_process_type, hidden,  
- [x] Add a FK between Template and TemplateCategory
- [x] CRUD API for TemplateCategory Table
- [x] API to update Template table with foreign key for TemplateCategory
- [x] API to update Template process_type if an admin overrides the process_type
- [x] Admin API for above as well
- [x] Tests for the above

**Comment by andrewleith** [comment]
- Work started on this, draft PR up now

**Comment by andrewleith** [comment]
- dao work started, api endpoints started
- @whabanks to continue on this today

**Comment by whabanks** [comment]
Code for the API endpoints and dao is complete. Started writing tests and squashing bugs.

**Comment by whabanks** [comment]
Tests for the new code are complete. Need to fix existing tests that broke with these changes.

**Comment by whabanks** [comment]
Ready for review along with the WAF rule changes. Some of the work done for this card checks off three AC's in [1587](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1587)

**Comment by amazingphilippe** [comment]
@jzbahrai reviewing today
