### ISSUE TITLE
Figure out TemplateCategories for existing Templates

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#1591]
## Description
As a user, I want to know the TemplateCategory for an existing Template

## Acceptance Criteria

- [x] Get buy in from policy about uploading all our production Templates to a paid LLM
- [x] Use the LLM to create a classifier for the production Templates
- [x] Update the Templates table with the TemplateCategory ids of that we get as an output from the classification model
- [x] Apply same model to templates in Staging

**Comment by andrewleith** [comment]
- @jzbahrai starting work on LLama

**Comment by andrewleith** [comment]
- some progress made provision infra for this; need bigger infra to do this work

**Comment by andrewleith** [comment]
- issues working with pod, trying an ec2 instance instead

**Comment by amazingphilippe** [comment]
Spending more time on the model.

**Comment by amazingphilippe** [comment]
Went through the data, we might need more data. Had to manually set some categories.

**Comment by amazingphilippe** [comment]
Cleaning up the data today.

**Comment by amazingphilippe** [comment]
Categories are in the database, ready to be used in staging.

**Comment by jzbahrai** [comment]
Finished updating the templates table in production as well. The data can be found where we were editing.
the code to rerun the model is here: https://github.com/cds-snc/notification-attic/pull/67

**Comment by amazingphilippe** [comment]
Categories can be viewed in Blazer if we need
