### ISSUE TITLE
FR audit and corresponding changes to name of formatting guide

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1592]
## Description
As a user, I need consistency in the names of guidance pages to reduce my cognitive load.

WHY are we building?
One French guidance page has a different naming structure than the rest of the pages: "Guide de mise en forme de courriels" should be "Mettre en forme les courriels"

WHAT are we building?
Audit for every place the name of this page appears and is linked
Change to the new name, and if need be, adjust surrounding content to introduce the page. 
Change url name and update WAF rules
Create redirect to avoid breaking any user's bookmarks

VALUE created by our solution
Consistency in our sentence structure and titles reduces cognitive load and makes it easier for users to find guidance when they need it
Experience for FR users is equal to that of EN users

## Documentation and Artifacts
[Bilingual guidance landing page ](https://docs.google.com/document/d/1toUmd02vv32h3wipRxBSZMTLYdk-ik171Q0_sCJPWtM/edit#heading=h.v9qokhnubrqc)

## Acceptance Criteria
Given users need guidance on formatting emails, when a Francophone user needs such guidance they can easily find it without an increase to their cognitive load.

- [x] Audit for every place the name of this page appears and is linked
- [x] Change to the new name, and if need be, adjust surrounding content to introduce the page.
- [x] Change url name and update WAF rules
- [ ] Create redirect to avoid breaking any user's bookmarks
- [x] Run Cypress UI tests for broken links
- [x] Does the feature change our Information Architecture? If so, update the Sitemap in En/Fr

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

GC Articles Publish checklist
-[ ] Supporting feature is released and unflagged
-[ ] Create or update slug
-[ ] Page content and slug is translated
-[ ] Document links to and from the page
-[ ] Add page slug and title to inventory
-[ ] If new page, add WAF rule
-[ ] Create new page or update existing page content
-[ ] Create or update translation to the page
-[ ] Link translations by choosing an assigned translation
 -[ ]If new page, save as draft
-[ ] If existing page, update the page
-[ ] Post page in Slack for last minute reviews
-[ ] On staging: Clear the cache through GC Notify's admin panel
 -[ ]On staging: Check links, images and language toggle
 -[ ]Give a heads up to the app-team channel once ready to publish
 -[ ]On staging and production: Clear the cache through GC Notify's admin panel
-[ ] Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by andrewleith** [comment]
- @YedidaZalik to begin this today

**Comment by YedidaZalik** [comment]
Finished auditing GC articles pages [here ](https://docs.google.com/spreadsheets/d/19wyE99q1-A2cNeM-1UmZoQqYITEC5SFLfTjrl5GsgNk/edit#gid=0)
Only 2 pages may need changes

Will ask whether to use sitemap for prod audit or if there's a way to search for the link

**Comment by YedidaZalik** [comment]
Andrew was able to audit on app so we now have the full list as:
**In the App and no localization needed**
- The sitemap (link text: Formatting emails / Guide de mise en forme de courriels)
- When you edit/create a template (link text: Guide: Insert email formatting / Guide : Mise en forme des courriels)

**On GC Articles and does not need localization** 
- /reference-guidance (soon to be /guidance)

**On GC Articles and needs localization as in a sentence**
- /features 
- /guidance (soon to be /getting-started

**Comment by amazingphilippe** [comment]
Waiting on translations.

**Comment by YedidaZalik** [comment]
Updating GC Articles and added update to the title of the actual guidance page.
Checking with MSB whether the translation she sent works for the Features page.

**Comment by YedidaZalik** [comment]
MSB advises to follow same form as other links on Fonctionnalités use "Découvrez comment mettre en forme les courriels"
Updated in GC Articles

**Comment by amazingphilippe** [comment]
Cahnges also made in code : https://github.com/cds-snc/notification-admin/pull/1886
 Awaiting review before merging to staging

**Comment by yaelberger-commits** [comment]
Take conversation about redirect offline

**Comment by andrewleith** [comment]
Looking at this page I think this is what we have left to do here in this order:
- Update the WAF rules to allow `/mettre-en-forme-les-courriels` (terraform PR)
- Update the [articles routing in admin](https://github.com/cds-snc/notification-admin/blob/main/app/articles/routing.py#L0-L1) to the new french URL
- Rename the slug on https://notification.canada.ca/guide-mise-en-forme to `mettre-en-forme-les-courriels` (GC Articles)
- Clear the cloudfront cache
- Clear the articles cache in admin

The WAF rule change should be merged up to prod first, then we can merge the change in admin, and finally, immediately after the admin change is live, we can update the slug in GC articles and clear the cache.

**Comment by andrewleith** [comment]
@YedidaZalik is that your understanding as well, that the french formatting guide page url should change to match the page's new title?

**Comment by mtoutloff** [comment]
Needs reviews
Once WAF rules are merged, it can be reviewed

**Comment by whabanks** [comment]
The WAF rules have been updated and deployed.
"Update the articles routing in admin to the new french URL" - PR was merged to staging, once the release is complete Tuesday morning we can update the GCArticles slug and clear the caches.

**Comment by whabanks** [comment]
Changes have been deployed, WAF rules updated, and redirects configured in Articles.

**Comment by amazingphilippe** [comment]
- Links updated on guidance index page
- Slug updated and tested
- Language toggle works
- GCA cache cleared in prod.

**Comment by mtoutloff** [comment]
Will and Phil did QA yesterday. @YedidaZalik will take a second look, and after it can be moved to done

**Comment by YedidaZalik** [comment]
Checked and it's working for both authenticated and public pages
Will move to done now
