### ISSUE TITLE
Allow recipients to opt back in to receiving SMS by texting the keyword

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1598]
## Description
As a recipient of a GC Notify text message, I need to be able to opt back into receiving messages using a keyword so that I have control over what messages I receive from the GoC and so that I don't have to reach out to support and can self-serve opting back in.

WHY are we building?
We want to empower recipients to control their own preferences for receiving text messages from the GoC and give them an easy-to-use, self-serve path for opting back in to receiving messages without having to reach out for support.
OPT IN, OPT OUT messages for the recipient
Documentation for GC Notify clients about how opt in/opt out works since this is a question that gets asked
WHAT are we building?
The flow and supporting content and design for using the OPT IN keyword 
VALUE created by our solution
Fewer SMS sent to opted out numbers

Related ticket https://cds-snc.freshdesk.com/a/tickets/20350

## Documentation and Artifacts
Good docs, figma mockups, ADRs, screenshots etc.
https://docs.aws.amazon.com/sms-voice/latest/userguide/phone-numbers-keywords.html
https://docs.aws.amazon.com/sms-voice/latest/userguide/phone-numbers-opt-out-list.html#phone-numbers-manage-opt-out-list-managed

Slack thread https://gcdigital.slack.com/archives/C03FA4DJCCU/p1721850141606839?thread_ts=1721848371.020129&cid=C03FA4DJCCU

## Acceptance Criteria
Given an SMS recipient has opted out of receiving SMS from a GoC program, when they want to opt back in, they have the content and information to know how to use the keyword OPT IN without contacting support, then they are opted back into receiving messages from GC Notify

- [ ] Cypress UI tests if needed.
- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)
- [ ] Does the feature change our Information Architecture? If so, update the Sitemap in En/Fr

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1598?planning-poker) with Zenhub @amazingphilippe @YedidaZalik

**Comment by yaelberger-commits** [comment]
Keep @mtoutloff in the loop for policy considerations

**Comment by YedidaZalik** [comment]
Initial notes and questions in [google doc](https://docs.google.com/document/d/1ApBXvJ9GnD9qg6IAoK5lspd9qFRaf2Jg0d1ekS0-95k/edit)

Started [flow in figma](https://www.figma.com/design/jLbAwtzlRfSl8fGjcMfyoU/Recipient-Emails-%7C-Courriels-destinataires?node-id=3477-92&node-type=canvas&t=Kg0yFvzRV4eeSdM8-0)

[Slack thread with questions and answers](url)

**Comment by YedidaZalik** [comment]
Continued on EN flow and content yesterday.
This may be a situation in which we need to do FR first as START works well for EN but Jimmy says COMMENCER does not work in FR.

**Comment by YedidaZalik** [comment]
Met with Team
Decided to go with START for EN and ABONNER for French

Need to decide which text messages to include here

**Comment by YedidaZalik** [comment]
Slack thread on FR characters and character limits https://gcdigital.slack.com/archives/C011SV2PM1B/p1729003311659929

**Comment by yaelberger-commits** [comment]
Moved to Blacked until we have FR content capacity

**Comment by amazingphilippe** [comment]
Booked time with MSB this morning. If not, will push the meeting

**Comment by YedidaZalik** [comment]
Discussed with MSB and moved meeting to Wednesday when she may have time to work on this content

**Comment by yaelberger-commits** [comment]
Will see if MSB has time today to take on localization

**Comment by YedidaZalik** [comment]
Updated Figma then met with MSB:  Discussed possibility of typos
Will raise at Dev/design review

**Comment by YedidaZalik** [comment]
Marie-Sophie pointed out that since we've shortened the opt out content, then EN for both opt out and opt in could use "Standard message and data rates apply" instead of "Std msg & data rates apply".
Maybe we want to stick with the abbreviated version for consistency if the short version is needed in future messages. That being said, Marie-Sophie cannot abbreviate the words in FR. So while this could help with shortening future EN messages, it won't help with the corresponding FR, which is usually longer.

Checked with Yael: Let’s spell it out fully so it’s consistent in EN and FR

**Comment by amazingphilippe** [comment]
Translations are back, Yedida will put everything together for dev hand-off

**Comment by YedidaZalik** [comment]
English and French are ready [in Figma](https://www.figma.com/design/jLbAwtzlRfSl8fGjcMfyoU/Recipient-Emails-and-SMS%7C-Courriels-et-sms-destinataires?node-id=3477-92&node-type=canvas&m=dev)
I'm having trouble linking to the latest iteration, it's the lowest one on the page, with the heading "CONTENT FOR TESTING" and outlined in red.

I've included the character count from https://messente.com/sms-length-calculator as a screenshot beside each message. I've also included a list for each keyword of alternatives we would like to be accepted in case of typos. Marie-Sophie has some priorities within those, so if there are too many, we can remove some.

**Comment by yaelberger-commits** [comment]
Handing over to Notify Core Team today for implementation cc @sastels @YedidaZalik

**Comment by YedidaZalik** [comment]
Tested all the word variations and all work.

Proofread text messages and sent screenshots of French messages to Marie-Sophie. All good.

**Comment by YedidaZalik** [comment]
Tested on prod with SMS that aren't from short code and all word variations work
English and French both proofread (FR by MSB)

There's a problem changing the keywords for shortcode and Steve A has put in a ticket with AWS support.

**Comment by YedidaZalik** [comment]
AWS resolved shortcode issue.
Tested all word variations using shortcode and MSB proofed the FR.
All in order, informed Steve A.
