### ISSUE TITLE
Publish reports from automated load testing

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/notification-planning#16]
### Task Description

In order to measure our performance improvements and be proactive on performance issues, we need to expand on our automated load testing. Because we want to track our performance history, we'd need to keep records generated between automated runs and publish these to they are accessible to the team (e.g. S3 bucket would be sufficient).

### Task Outcome

We can track the performance history from an accessible location available to the team.

### Acceptance Criteria

- [x] Save and publish reports into S3 buckets or other means to have these available to the team.

**Comment by jimleroyer** [comment]
I see the test results published in the performance test bucket in S3, all good on that side.

On the other hand, I see failures on the reported errors on the file handles:

```
POST,/v2/notifications/email,"HTTPSConnectionPool(host='api.staging.notification.cdssandbox.xyz', port=443): Max retries exceeded with url: /v2/notifications/email (Caused by SSLError(OSError(24, 'No file descriptors available')))",1
```

That means we could not increase the test capacity without encountering more of these. We'd need to increase the file descriptors on the OS/docker image. Omar encountered the same error when he worked on setting an EC2 instances; we could ask him to expedite it but googling works too, it's an easy fix per se.

**Comment by iokpala** [comment]
@jimleroyer I believe you are referring to using the nofile type on the ulimit flag.. I will take a look at that especially for AWS

**Comment by jimleroyer** [comment]
The exact steps to increase the limit file descriptors would depend on the image we rely upon to run the performance tests. Steps might be similar to [something like this](https://www.linuxtechi.com/set-ulimit-file-descriptors-limit-linux-servers/).

**Comment by jimleroyer** [comment]
@iokpala We can close this issue and open a new one for this bug, as the acceptance criteria has been met for this card, but we found a potential issue with scalability of the performance tests with the docker image setup (hence a bug).
