### ISSUE TITLE
Test edit template reveal radio button list, filters for templates with Fable tests

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1608]
## Description

After introducing a new disclosire pattern for radio lists, we should test the new form component with Fable and assitive tech.

WHY are we building?
- need for a compact list form field, where each item has a label and a description.

WHAT are we building?
- Running some Fable tests to get an idea of the UX with AT

VALUE created by our solution
- Not introduce new a11y issues. 

## Documentation and Artifacts
https://github.com/cds-snc/notification-admin/pull/1928 

## Acceptance Criteria
Given we introduce a new form component

- [x] Build a prototype that can be accessed without authentication
- [x] We run QA tests with Fable
- [x] We follow up with testers if they report difficulties

**Comment by mtoutloff** [comment]
Will try to set up demo page and review app to start testing

**Comment by yaelberger-commits** [comment]
@amazingphilippe please add your estimate to this card

**Comment by mtoutloff** [comment]
@amazingphilippe will set up test for Fable
Still have 5 requests until Sept 30 and can also think of other things to test

**Comment by amazingphilippe** [comment]
Sent out a compatibility test request. Will follow up with QA tests if needed with specific technologies.

**Comment by amazingphilippe** [comment]
No issues reported through Fable 🎉The collapsible form component was easy to use for the testers: Screen readers, alt nav and screen magnification.
