### ISSUE TITLE
Missing FR translation bug-bogue

### ISSUE THREAD

**Issue by keenan-wong** [cds-snc/notification-planning#1611]
## Describe the bug 

Two missing FR translations on the Add a new logo screen, and on the About your service screen

## [Bug Severity]

SEV-4 Low

## Expected behavior

Add a new logo
- Subheading for Alternative text, and subtext should both be in French

About your service
- Parent Organization name should be in French

## Impact

Increase trust and credibility with Francophone users.

## Screenshots

<img width="954" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2075ac7953ebfa476be7d04bc4a602498bf5db85/Screenshot%202024-07-11%20at%2010.07.22%E2%80%AFAM.png" alt="Screenshot 2024-07-11 at 10.07.22 AM.png" />

<img width="954" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eda18ec5badb05e14d9cdbbbd9501f22dd95fd9d/Screenshot%202024-07-11%20at%209.51.22%E2%80%AFAM.png" alt="Screenshot 2024-07-11 at 9.51.22 AM.png" />

## Additional context

I'll be demo-ing the FR product in front of a Francophone audience on July 25th. Ideally we get this uploaded before then.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1611?planning-poker) with Zenhub @YedidaZalik @mariesophiebezert

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1611?planning-poker) with Zenhub @jzbahrai

**Comment by YedidaZalik** [comment]
MSB provided the French:

Alternative text: Texte de remplacement

Provide an accessible description of your logo: Fournissez une description accessible de votre logo

Name of parent organization: Nom de l'organisme parent
