### ISSUE TITLE
Improve French content on template creation page in admin

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1613]
## Description
As an admin user I need to clear and consistent content around priority lanes to avoid confusion. 

WHY are we building?
French content for priority lanes on template creation page in admin is inaccurate.  This may be fixed by work curently being done.

WHAT are we building?
(1) Content that is consistent with our new content on template categories.
(2) Correct translation for "priority queue". Currently we have "Sélectionnez une file de sécurité" but it should be "file de priorité"
(3)"Par défaut" could confuse users as it's not clear whether it is referring to a default template category or a default priority lane.

VALUE created by our solution
Clear consistent content in French admin. 

## Documentation and Artifacts
Good docs, figma mockups, ADRs, screenshots etc.
https://www.figma.com/design/RLcM0JwlQsd2uVK3GJr5qY/Templates-%7C-Gabarits?node-id=2870-755&t=mqIfnucRsuGE59Qw-0

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] Cypress UI tests if needed.
- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)
- [ ] Does the feature change our Information Architecture? If so, update the Sitemap in En/Fr

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
@jzbahrai is this now done? Has it been QA'd by @mariesophiebezert?

**Comment by whabanks** [comment]
To be QA'd

**Comment by whabanks** [comment]
Yael to review when ready.

**Comment by mariesophiebezert** [comment]
The screens where changed were made to the names of the priority queues are: "Create templates as admin", "Categories admin", "Update category"

**Comment by amazingphilippe** [comment]
QAing this PR: https://github.com/cds-snc/notification-admin/pull/1906

**Comment by amazingphilippe** [comment]
Found some more out of sync content. Writing a PR to fix all of it. Needed a bit more code acrobatics. https://github.com/cds-snc/notification-admin/pull/1914

**Comment by whabanks** [comment]
PR ready for review @jzbahrai
