### ISSUE TITLE
Let clients know about template categories feature 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1614]
## Description
As a GC Notify client, I need to know about the template categories feature so that I can filter my templates by category, set my template category for new templates and review or edit my template category. 

WHY are we building?
To build awareness of this new feature among clients
WHAT are we building?
A new post (EN/FR) in New Features
VALUE created by our solution
Better success rate for GC Notify clients on tasks related to template categories 
## Documentation and Artifacts
Good docs, figma mockups, ADRs, screenshots etc.

DRAFT https://docs.google.com/document/d/1iksKf9uMcbmhB92jOpTi3wPTDFapfXRBGhXl_eO1iX8/edit

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

## GC Articles Publish checklist
- [ ]  Supporting feature is released and unflagged
- [ ]  Create or update slug
- [ ]  Page content and slug is translated
- [ ]  Document links to and from the page
- [ ]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [ ]  If new page, add WAF rule
- [x]  Create new page or update existing page content
- [ ]  Create or update translation to the page
- [ ]  Link translations by choosing an assigned translation
- [ ]  If new page, save as draft
- [x]  If existing page, update the page
- [x]  Post page in Slack for last minute reviews
- [ ]  On staging: Clear the cache through GC Notify's admin panel
- [ ]  On staging: Check links, images and language toggle
- [ ]  Give a heads up to the app-team channel once ready to publish
- [x]  On staging and production: Clear the cache through GC Notify's admin panel

**Comment by YedidaZalik** [comment]
Yael worked on this last week
Draft attached to card for review by Yedida and Keenan

**Comment by YedidaZalik** [comment]
Used the suggest feature to give some feedback

**Comment by yaelberger-commits** [comment]
Growth is reviewing

**Comment by yaelberger-commits** [comment]
Reviewed. Ready for translation

**Comment by YedidaZalik** [comment]
Document for translation : https://docs.google.com/document/d/1iksKf9uMcbmhB92jOpTi3wPTDFapfXRBGhXl_eO1iX8/edit?tab=t.0#heading=h.lbd3qa8x4d0n

**Comment by YedidaZalik** [comment]
Translated and awaiting proofreading.

**Comment by YedidaZalik** [comment]
French is back https://docs.google.com/document/d/1vSXJFCCe3alot-4S8BfzhT-oTFA6MFH8Jd9AYc09Sek/edit?tab=t.0#heading=h.30j0zll

**Comment by YedidaZalik** [comment]
Fixed pages following Yael and Phil's instructions
Cleared cache and both EN and FR lgtm
Tagging @yaelberger-commits for review

**Comment by andrewleith** [comment]
- Instructions for posting new features page updated as part of this process
- Page needs one more review before posting

**Comment by yaelberger-commits** [comment]
Looks good in both EN and FR
