### ISSUE TITLE
Dovetail SaaS Privacy and Security Assessment

### ISSUE THREAD

**Issue by mtoutloff** [cds-snc/notification-planning#1615]
## Description
SaaS Privacy and Security Assessment Guidance questionnaire for Dovetail. 

WHY are we building?
To document the use of Dovetail for user research analysis 
WHAT are we building?
A completed Security Assessment Guidance questionnaire
VALUE created by our solution
Supports ongoing efforts to document the use of third party SaaS tools 

https://docs.google.com/document/d/1IrialT3Ujo71_7goCYaa0xjLDh70-cGMQHODL01wqJk/edit 

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] First draft checklist
- [ ] Reviewed by Product Manager
- [x] Shared with security-privacy channel for review 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by mtoutloff** [comment]
Completed draft checklist, with @amazingphilippe for review

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1615?planning-poker) with Zenhub @mtoutloff @amazingphilippe

**Comment by mtoutloff** [comment]
Phil reviewed and provided comments. I will go through the comments this week and provide responses and finalize the draft

**Comment by mtoutloff** [comment]
Reviewed Phil's comments and provided responses. Almost ready to share with Security

**Comment by mtoutloff** [comment]
SaaS questionnaire has been shared with the security-privacy channel.

**Comment by mtoutloff** [comment]
Reviewed by Security, moving to done
