### ISSUE TITLE
Template Categories Metrics

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1616]
## Description
Once we release template categories we'll want to measure a few things in Quicksight:

- [x] How many templates are there per template category? Which category is most popular? Which is least? This should be able to be viewed in real time and we should start thinking about how we might get this data over to the CRM eventually.

- [x] How many templates have had their template category edited since we released the feature? What category are these templates being moved to most often?

**Comment by whabanks** [comment]
@whabanks @jzbahrai @andrewleith Estimates

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1616?planning-poker) with Zenhub @andrewleith @jzbahrai @whabanks

**Comment by whabanks** [comment]
PR to get quicksight in staging merged. Will compare Blazer to Quicksight today.

**Comment by andrewleith** [comment]
Quicksight dashboard created in staging, one PR left to get one new dataset required into PROD.

**Comment by mtoutloff** [comment]
Pr up to get new dataset in, once merged needs to recreate analysis

**Comment by mtoutloff** [comment]
PR waiting for Core to review

**Comment by yaelberger-commits** [comment]
Need to ping Core to merge, then recreate the dashboard in Prod and this will be done

**Comment by yaelberger-commits** [comment]
@andrewleith will continue on this one this morning

**Comment by yaelberger-commits** [comment]
Now a dataset in Quicksight
