### ISSUE TITLE
Discovery: Research on best practices for drafting email and text message content

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1617]
## Description
As a recipient,  I need to receive messages that I understand and trust so that the government provides me with services to which I am entitled. 

WHY are we building?
We have an assumption that users would appreciate stock templates and/or guidance to help them send more effective messages more efficiently. We know some best practices to prevent messages getting flagged as spam, and some constraints (length) that we could pass along to users more easily and make the right thing the easy thing for them to do.

WHAT are we building?
Literature review and a powerpoint presentation summarizing and analyzing the findings and applying them to the Canadian and Notify context.

VALUE created by our solution
We can move forward based on existing knowledge and understand what areas are not covered by existing research such that we may need to conduct design research in those areas; potential example is bilingual stock templates.

## Documentation and Artifacts
Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given that there's existing research on effective government messages, we have reviewed that research and applied it to the Canadian context.

- [ ] Cypress UI tests if needed.
- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)
- [ ] Does the feature change our Information Architecture? If so, update the Sitemap in En/Fr

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by YedidaZalik** [comment]
I've been finding and reviewing research as side of desk work and now as we move toward this OKR, Yael advised to make this card

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1617?planning-poker) with Zenhub @YedidaZalik

**Comment by YedidaZalik** [comment]
Will prioritize as prep for October demo

**Comment by YedidaZalik** [comment]
Will continue today

**Comment by YedidaZalik** [comment]
Hope to finish reviewing resources today and start analysis next week

**Comment by mtoutloff** [comment]
Yedida will start on analysis this week

**Comment by YedidaZalik** [comment]
Heard back from content designers in Wales and Austin, Texas, but no specific info yet

**Comment by YedidaZalik** [comment]
Continuing on organizing/analyzing research, may bring a few questions to Notify 101 today

**Comment by YedidaZalik** [comment]
Discussed with Phil and Yael whether to do written report or powerpoint
Decided on powerpoint

**Comment by YedidaZalik** [comment]
Found earlier Notify work by Anik on this topic
[Sample notifications by other gov orgs](https://www.figma.com/design/uerfGAwA8MqaZ65Ep8oeXl/Guides?node-id=2430-1901&node-type=canvas&t=uN0d5shL0qQH32mt-0)
[Beginnings of draft guidance based on UK guidance](https://docs.google.com/document/d/1-_iIKNlqO64KtXYtXVbz2cKp1Sq5mXkuysbLu4CD2vc/edit#heading=h.2ize10xpyjlc)

**Comment by YedidaZalik** [comment]
Cleaning up deck and checking policy issue with Melissa and bringing bilingualism issues to critique today

**Comment by YedidaZalik** [comment]
Melissa and content critique helped with some sticky points.
Completed [deck](https://docs.google.com/presentation/d/1XNbxbN9yr0q5cAeK8_4d3OinF8ESVJOWtyYjcwEh2sM/edit#slide=id.g2bcac7083ba_0_5892) and sent to Yael and Phil for review
Deck is long, but not all slides need to be presented. While they don't all need to be presented, it's useful to include all the slides for helpful context and reference when designing guidance and stock templates.

**Comment by yaelberger-commits** [comment]
I completed my review of the deck and added some comments

**Comment by yaelberger-commits** [comment]
Yedida will present at Story Refinement on Wed. Oct 2

**Comment by YedidaZalik** [comment]
Resolved most of Yael's comments in ppt and replied to a couple of them.
Prepping to present today.

**Comment by YedidaZalik** [comment]
Presented to team and added 2 slides based on team discussion
