### ISSUE TITLE
Refactor smoke / perf tests

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#162]
We should refactor the smoke and performance test code with respect to
- the directory structures
- functions they can have in common
- using common environment variables / services / templates
- moving it all to the attic (Note that having the stress tests in api stops us from using the latest version of `locust`)

**Comment by yaelberger-commits** [comment]
@jimleroyer Is this one still relevant? Is the team already doing some of this? Should we refine this card and prioritize it in the Product backlog?

**Comment by jimleroyer** [comment]
Yes I'd think it is still valid. @sastels What do you think? (as you created the task)

**Comment by sastels** [comment]
I think so. They're a bit cumbersome to use right now (to the point of people asking during an incident "does anyone know how to run the perf tests?"). Cleaning things up, moving to the attic, and adding some more docs would make them easier for us to use and maintain.
