### ISSUE TITLE
Terms of Use intervention metrics (baselining)

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1629]
Baseline metrics for Terms of Use

- [x] Monthly page visits historically 
- [x] Average time spent on page historicially
- [x] Support tickets with questions about Limits historically 

https://docs.google.com/document/d/1McM5itEJiCacVkyDoZofv7JAewSoIlMlnD-T-IrIsco/edit

**Comment by mtoutloff** [comment]
Getting baseline for 2023 calendar year, and metrics for this year, and average time spent on page, and support tickets with questions about limits 
Putting together a small doc so when we release TOU interventions we can measure if this goes up or down
