### ISSUE TITLE
Default process type is not being set correctly under certain conditions

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1631]
## Describe the bug 

When a template is created with `FF_TEMPLATE_CATEGORY=false`, its `process_type` should be defaulted to `BULK`.  With template categories (i.e. `FF_TEMPLATE_CATEGORY=true`, the new default will be `NULL`, since a template will inherit its `process_type` from the category.  

In some cases with the feature flag on (can someone add some specifics here?), the template priority is not being set correctly.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 
SEV-2 Major

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team:

**Comment by whabanks** [comment]
## FF OFF
### Template table state
- Process_type column is not `null`
- Template_category_id is `null`
### Admin user
1. Override the process_type -> new process type should be saved for an existing template
2. Make a new template -> process type should be `bulk`
## Non-Admin
1. Edit a template with <> bulk priority -> should save with the same priority
2. Make a new template -> process type should be `bulk`

## FF ON

### Template 1  state
- Process_type column is `null`
- Template_category_id is not `null`
### Template 2 state
- Process_type column is `bulk`
- Template_category_id is not `null`
### Admin user
1. Override the process_type -> new process type should be saved for an existing template (different from the template category priority)
2. Make a new template -> process type should be `null` and the priority from the category should be in effect
3. Edit template 2 -> "use template category" -> process type should change to `null` in db
## Non-Admin
1. Edit a template 1 -> change the category -> different process type returned -> db process_type is `null`
2. Make a new template -> process type should be `null` and the priority from the category should be in effect
3. Edit template 2 -> change the category -> process_type should be `null`

**Comment by mtoutloff** [comment]
Made headway on cyprus tests also added some unit tests

**Comment by whabanks** [comment]
The remaining work and accompanying tests have been merged to staging. @andrewleith and I are testing manually by running through the bug bash scenarios as well as the scenarios in this card to prepare for a release to production tomorrow morning.

**Comment by mtoutloff** [comment]
Deployed to production
