### ISSUE TITLE
Inaccurate Malware Detection

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#1636]
## Describe the bug 

`logs-1-malware-detected-1-minute-warning` is triggered by files known not to contain malware. 

We recently got caught in an alarm loop with GC Forms, where they were retrying to send a form submission after getting called back by GC Notify. They are working on their side of the problem.

In theory, this would be fine, except that the files did not contain malware, they likely contained "Potential Unwanted App" (PUA). For now, our malware detection treats "malicious" and "pua" as the same, therefore returning an inacurate error when attachments contain PUA.

This has happened in the past once. More info in [this thread](https://gcdigital.slack.com/archives/CNWA63606/p1705599907531139). Pat and Jimmy seem to be aware of the problem. They also own the scanning tool. 

Pat referred to it as "PUA false-positives". What are the true positives?

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

## Expected behavior

To be refined

## Impact

False positive alarms

If applicable

Impact on Notify users: inaccurate failure label

Impact on Recipients: messages not transmitted

Impact on Notify team: alarms

## Screenshots

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWxnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--327ac7ba142d8191def949138be2248e2178c3d1/image.png" alt="image.png" />

## Additional context

[This thread with Forms](https://gcdigital.slack.com/archives/C03T4FAE9FV/p1723728078403769)

**Comment by patheard** [comment]
Impacted scan result confirms this was a PUA false-positive for `PUA.Pdf.Trojan.EmbeddedJavaScript`:
```json
{
  "level": "INFO",
  "location": "sns_scan_results:30",
  "message": "message: {scan_id: a0ce369a-1d32-4784-83f8-a5302da25578, av-signature: PUA.Pdf.Trojan.EmbeddedJavaScript-1 FOUND, av-status: malicious, av-timestamp: 2024-08-15T18:34:36.298081}",
  "timestamp": "2024-08-15 18:34:36,312+0000",
  "service": "scan-files-api",
  "correlation_id": "635f2771-ded0-456e-ac3a-42e91cb83c2c",
  "xray_trace_id": "1-66be4a0c-27d86c9f5b5f69d966a1012c"
}

```
More docs can be seen in the [ClamAV PUA FAQ](https://docs.clamav.net/faq/faq-pua.html).  I'll look at removing these scan results since it isn't the first time we've seen them for GC PDFs with embedded scripts.

**Comment by patheard** [comment]
My fix in https://github.com/cds-snc/scan-files/pull/1054 is working as expected and PDFs with script embedded are no longer being marked as malicious.

I'll deploy the fix to Prod later today.
