### ISSUE TITLE
Dev & Design: Add Suspend / resume service callbacks

### ISSUE THREAD

**Issue by whabanks** [cds-snc/notification-planning#1647]
## Description
As a platform admin user, I need to be able to suspend a service's callbacks.

TODO: 
- Do we want to add a button to send the warning email so it's a 1 click : 1 action process?

## Acceptance Criteria
- [x] Design UI to facilitate platform admins suspending & resuming a service's callback functionality
- [x] Dev front end work to implement the design
- [ ] Change the content page - to show callbacks testing + let them know about the response time and that we want them to respond within 1s (devs to design this content) (taken from [1564](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1564))
- [x] Add warning and critical suspension emails to the GCNotify service ( we are not doing this instead we are doing 1645)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1647?planning-poker) with Zenhub @amazingphilippe @andrewleith @jzbahrai @whabanks @YedidaZalik

**Comment by yaelberger-commits** [comment]
Will working on adding a component with ellipses

**Comment by yaelberger-commits** [comment]
Mostly finished, wrapping up today

**Comment by yaelberger-commits** [comment]
@jzbahrai can start reviewing while Will tests

**Comment by yaelberger-commits** [comment]
Yedida reviewed Confirmation messages, working on tests

**Comment by YedidaZalik** [comment]
Draft confirmation messages in the document with the callback email to maintain consistency between those pieces of content
Will tagged to review confirmation messages
https://docs.google.com/document/d/1yUgerRyr6bcLu0TyoI__XO2L-m28YHcfp8za5ueTlvw/edit

**Comment by YedidaZalik** [comment]
Will and Yedida finalized content for the messages
Ready for translation 
Tagged @MSB for when she has time
https://docs.google.com/document/d/1yUgerRyr6bcLu0TyoI__XO2L-m28YHcfp8za5ueTlvw/edit

**Comment by yaelberger-commits** [comment]
Translations for confirmation messages are back from translation ready for you @whabanks

**Comment by YedidaZalik** [comment]
Made slight change to new message for review by Will and Marie-Sophie
