### ISSUE TITLE
Service Mapping for Annual Limits Enforcement

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1654]
## Description
As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Documentation and Artifacts
[Miro All maps](https://miro.com/app/board/uXjVO6TPyIs=/?moveToWidget=3458764598114438178&cot=14)
[Figma screens](https://www.figma.com/design/JGp5noL1kCpiwJzHKL5MHe/Sending-capacity---capacit%C3%A9-d'envoi-(Copy)?node-id=2831-6844)
[Product requirement doc](https://docs.google.com/document/d/1qoqzKzt4mXQh1NPtZE_GBqsN0D87wnTbHVNIBRu75D0/edit)

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] Cypress UI tests if needed.
- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)
- [ ] Does the feature change our Information Architecture? If so, update the Sitemap in En/Fr

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1654?planning-poker) with Zenhub @amazingphilippe

**Comment by yaelberger-commits** [comment]
Reviewing solutions being explored so far this morning

**Comment by jessicalfan** [comment]
Created v1.0 of several solution user flows - beginning light prototyping of visual indicators of annual limits.

**Comment by yaelberger-commits** [comment]
Service mapping, wireframes and screens are all underway
Conversations in Slack about exceptions
Bring to team discussion/Josh

**Comment by yaelberger-commits** [comment]
Bring to Story Refinement today

**Comment by yaelberger-commits** [comment]
@amazingphilippe did some designs/mockups for annual limits on the dashboard.

**Comment by yaelberger-commits** [comment]
Phil and Jessica looked at more service maps for SMS/Emails. Also looked at Figma mockups. Bring this to Dev Design review this morning

**Comment by yaelberger-commits** [comment]
Jessica will share 2 scenarios (hard limit and flex limit) Get input on priority features from the team

**Comment by yaelberger-commits** [comment]
Jessica and Phil to meet this morning following a design jam yesterday

**Comment by yaelberger-commits** [comment]
Phil and Jessica to sync again this morning following sync with Josh yesterday

**Comment by yaelberger-commits** [comment]
Jessica working on Blueprinting 3 scenarios. Can share first one in Story Refinement. Then will work on how we transition existing users to a higher default limit. If time, will help Phil on PRD

**Comment by yaelberger-commits** [comment]
Next Yael and Phill will review the PRD and schedule to review it with the team
Then Yael will create epics and user stories to break down and scope the work to come

**Comment by yaelberger-commits** [comment]
Bringing this to Story Refinement today!

**Comment by yaelberger-commits** [comment]
Reviewed the PRD today with the whole team. Next steps to create MVP EPIC and User Stories
