### ISSUE TITLE
 api lambda: pr-bot changes for release

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#167]
The automated PR in the manifest repo should also release the latest version of the api lambda to production

**Comment by jimleroyer** [comment]
@sastels Is it time to merge latest changes? 🙂 We tested it on a couple of releases so far.

**Comment by sastels** [comment]
The only thing we need to do is ensure that the TOKEN has permission to modify workflows. For personal access tokens you have to set that explicitly. This is not a PAC token though (PACs expire). Possibly we should poke around in the Settings of the pr-bot repo (which I do not have access to). @maxneuvians might have more insights into how / where this token was generated...
