### ISSUE TITLE
Add expectations that clients maintain their callback service to the ToU

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1671]

**Comment by mtoutloff** [comment]
Discussed with @YedidaZalik and will wait to update the TOU until the API documentation has been updated to keep the edits to the terms minimal

**Comment by mtoutloff** [comment]
API documentation has been updated and is with translation. Will update TOU to align with API documentation

**Comment by mtoutloff** [comment]
@whabanks will add a few more points to the API documentation, once that's done, the TOU updates will be finalized

**Comment by mtoutloff** [comment]
Reviewed @YedidaZalik's edits

**Comment by mtoutloff** [comment]
Updates to TOU have been finalized cc'd Yael for review and will send to translation

**Comment by yaelberger-commits** [comment]
Yael reviewed!

**Comment by YedidaZalik** [comment]
Implemented changes in both EN and FR
Cleared cached, changes did not go through

**Comment by YedidaZalik** [comment]
Will fixed link that is in wrong language

**Comment by YedidaZalik** [comment]
Andrew pointed out that TOU is now inside the app not GC Articles so that's the problem

**Comment by YedidaZalik** [comment]
@andrewleith 
Github comment to convert EN sentences to French in the French TOU (note they don't always appear in English. On Chrome I found they were in FR but not in Safari):

- Under heading "Gérer et protéger les renseignements personnels de vos destinataires" one of the bullets is in English

"Respond to requests under the [Access to Information Act](https://laws-lois.justice.gc.ca/eng/acts/A-1/index.html) and [Privacy Act](https://laws-lois.justice.gc.ca/eng/ACTS/P-21/index.html) or similar requests under your jurisdiction’s legislation. For support, [contact us](https://notification.canada.ca/contact)." Please change to 
"Répondez aux demandes en vertu de la [Loi sur l’accès à l’information](https://laws-lois.justice.gc.ca/fra/lois/a-1/index.html) et de la [Loi sur la protection des renseignements personnels](https://laws-lois.justice.gc.ca/fra/lois/p-21/index.html) ou à des demandes similaires en vertu de la législation applicable au sein de votre juridiction. Si vous avez besoin d’aide, [contactez-nous](https://notification.canada.ca/contact)."

- Under heading "Pratiquer la sécurité continue" please change "Follow the [steps in our Security notice](https://notification.canada.ca/security) and report any security breach or vulnerability using the [CDS process](https://digital.canada.ca/security-notice/)." to "Suivez [les étapes détaillées dans notre avis de sécurité](https://notification.canada.ca/securite) et faites-nous part de toute faille de sécurité ou vulnérabilité à l’aide du [processus du SNC](https://numerique.canada.ca/avis-de-securite/)."

Thank you!

**Comment by YedidaZalik** [comment]
@andrewleith 
Github comment to add new EN content to TOU (I'll do FR as a separate comment)

- Heading "Practice continuous security" becomes "Practice continuous security and adequate maintenance of your API"

- The last bullet underneath that heading becomes "Secure your API keys and follow our rules for [API calls and unprocessed requests](https://documentation.notification.canada.ca/en/send.html#check-status-repair-and-resend-messages) as well as  [callbacks](https://documentation.notification.canada.ca/en/callbacks.html). If you cannot meet our callback requirements, we’ll need to suspend callbacks for your service."

- Please also add at the bottom:

"Last updated: October 8, 2024

[Previous version](https://notification.canada.ca/terms-202311)"

Thank you!!

**Comment by YedidaZalik** [comment]
@andrewleith 
Github comment to add new FR content to TOU

- Heading "Pratiquer la sécurité continue" becomes " Pratiquer la sécurité continue et assurer la maintenance adéquate de votre API"

- Last bullet becomes "Sécurisez vos clés API et suivez nos règles concernant [les appels d’API et les demandes non traitée](https://documentation.notification.canada.ca/fr/envoyer.html#verifiez-l-etat-du-message-corrigez-et-envoyez-a-nouveau)s ainsi que les rappels. Si vous n'êtes pas en mesure de respecter nos exigences en matière de rappels, nous devrons suspendre les rappels pour votre service."

- Please also add at the bottom: 

"Dernière mise à jour : 8 octobre 2024

[Lien vers les versions précédentes](https://notification.canada.ca/conditions-dutilisation-202311)"

Merci beaucoup!!

**Comment by andrewleith** [comment]
All set! https://github.com/cds-snc/notification-admin/pull/1981
