### ISSUE TITLE
Add support for attaching `.ICS` files through the API

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1684]
## Description
As a user, I need to be able to attach `.ics` files to my email notifications to make it easier for recipients to save appointments, etc. into their calendars. 

### WHY are we building?
- To make it easier for end users to add events to their calendars with a click.

### WHAT are we building?
- Ability to attach .ics files to email notifications

### VALUE created by our solution
- Notification recipients can add events to their calendars with a single clic,

## Acceptance Criteria
- [x] Security team has been consulted
- [x] .ics files are accepted when attaching a file to a notification

**Comment by YedidaZalik** [comment]
Andrew talked to Security and no issue
Jimmy and Andrew would like to do right away because it's an easy fix and could just do for this particular service
