### ISSUE TITLE
Missing French translation in Service settings

### ISSUE THREAD

**Issue by jprince-cds** [cds-snc/notification-planning#1686]
## Describe the bug 

Sentence is missing a French translation on the screen to "Change your sending email address" in Service settings.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

Potential OL breach.

## To Reproduce

1. Switch your Notify language to French.
2. Click on Paramètres of a service.
3. Click on Modifier next to "Nom de l'adresse courriel d'envoi"
4. See untranslated string: "You may use letters, numbers, dots, dashes or underscores."

## Screenshots

<img width="1043" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmQvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1541987ad740cd40d2485e0832496c59c04fdc3a/image.png" alt="image.png" />

## Additional context

Reported in [Freshdesk Ticket #19708](https://cds-snc.freshdesk.com/a/tickets/19708)

**Comment by YedidaZalik** [comment]
Prepped and emailed to MSB for translation: https://docs.google.com/document/d/1NHRziv9jNAtQFZDjGVQCfFS78d3W4ThGoBxVUPeDxww/edit?tab=t.0

**Comment by amazingphilippe** [comment]
We can probably reuse content from the create-a-service flow

**Comment by amazingphilippe** [comment]
Pull request to fix the issue: https://github.com/cds-snc/notification-admin/pull/1988

**Comment by yaelberger-commits** [comment]
Merged and released
Has been QA'd
