### ISSUE TITLE
Update missing translations

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#1692]
## Describe the bug 

The process to check for missing translations isn't looking in `.html` files.  Because of this we have missed several translations.

Here is a spreadsheet containing all the instances:
https://docs.google.com/spreadsheets/d/1osCm70Hm6PYRoABkR7zOF7p2tMH-tDhksdPw0Yns2Pk/edit?usp=sharing

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-3 Minor

## Impact

App is not bilingual in some places

## Acceptance criteria
- [ ] Each missing translation has been added to the `fr.csv` file
- [ ] `babel.cfg` has been updated to look for translations in `.html` files

**Comment by yaelberger-commits** [comment]
Ran script, Phil QA'ing

**Comment by amazingphilippe** [comment]
PR merged to staging. REady for next release
