### ISSUE TITLE
Not receiving no reply messages

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1707]
Several of us have tried replying to messages from Live Notify services that do not have reply-to addresses set up.
We've tried on both prod and staging. 
We have tried from both cds and personal email addresses.
We have not received any reply.

## To Reproduce

1. Go to a Live service on Notify. 
2. Ensure in settings that the service has not set a reply-to address.
3. Send yourself an email from the service.
4. Reply to the email.
5. Wait for a sufficient amount of time to receive a no-reply message from Notify.

## Expected behavior

You will not receive a no-reply message.

## Impact

Impact on Notify users: Users expect that their recipients receive a no-reply message if they reply to emails sent through Notify. But the recipients are not receiving such a message.

Impact on Recipients: If they reply to a message sent by a Notify service, they expect that the service receives and reads their reply, but that's not happening.

Impact on Notify team: We have prepped new no-reply content that is waiting on localization, but this new content will not be useful if the no-reply function is not working.

## Additional context

This is related to [#752 Update our No Reply message](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/752)

**Comment by jzbahrai** [comment]
Investigation from andrew:
notes on the no reply:
lambda code: https://github.com/cds-snc/notification-lambdas/blob/main/sesreceivingemails/ses_receiving_emails.py#L36
which calls, celery code: https://github.com/cds-snc/notification-api/blob/main/app/celery/tasks.py#L709
:warning: i don't see any lambda named "ses_receiving_emails" in staging

**Comment by jzbahrai** [comment]
The ses_receiving_emails lambda exists in us-east-1 as we can't receive messages in ca-central-1. There was an issue with the deployment where the lambda function could not read the container. I fixed this by redeploying and it worked.
