### ISSUE TITLE
Remove Lastpass from our list of third party services and replace it with 1password, and other changes

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1708]
## Description
As a user ore prospective user, I need to check what third party services Notify uses for my due diligence. 

WHY are we building?
Keep our list of third party services current
WHAT are we building?
New updated version and archived version
VALUE created by our solution
Users can check what third party services are involved 

## GC Articles Publish checklist
- [ ]  Create or update slug
- [ ]  Page content and slug is translated
- [ ]  Document links to and from the page
- [ ]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [ ]  If new page, add WAF rule
- [ ]  Create new page or update existing page content
- [ ]  Create or update translation to the page
- [ ]  Link translations by choosing an assigned translation
- [ ]  If new page, save as draft
- [ ]  If existing page, update the page
- [ ]  Post page in Slack for last minute reviews
- [ ]  On staging: Clear the cache through GC Notify's admin panel
- [ ]  On staging: Check links, images and language toggle
- [ ]  Give a heads up to the app-team channel once ready to publish
- [ ]  On staging and production: Clear the cache through GC Notify's admin panel
- [ ]

**Comment by yaelberger-commits** [comment]
Need to find out if this page is hardcoded or in GC Articles

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1708?planning-poker) with Zenhub @YedidaZalik

**Comment by yaelberger-commits** [comment]
Completed through #1689
