### ISSUE TITLE
Notify legacy clients of new custom limits

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#1711]
As a user with a custom sending limit, I need to know that my current sending limit will continue despite the changes to GC Notify's default limits. 

WHY are we building?
We've communicated that our default sending limits have increased, but we've allowed some users to send above the new default limits for some time.

WHAT are we building?
An email to these specific users to inform them that we'll allow their specific service to continue sending at its current  volume.

VALUE created by our solution
Users will understand what to expect and Support will receive less inquiries about this issue.

## Acceptance Criteria
Given a user with a custom limit needs to understand how their service is impacted by the new defaults, they can find an adequate explanation in our email to them. 
- [ ] Cypress UI tests if needed.
- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)
- [ ] Does the feature change our Information Architecture? If so, update the Sitemap in En/Fr

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by whabanks** [comment]
Draft email going through final tweaks, has been reviewed by Josh, then off to translation.

**Comment by whabanks** [comment]
Translations completed, Yael will create a Notify template and meet with Jumana to set limits for services.

**Comment by yaelberger-commits** [comment]
Spreadsheet updated for FR content and variables
Template updated for FR content and variables 
Waiting on automated template for annual limit increased email notification to be finalized in production. It's been testing in Staging 
Yael and Jumana will coordinate changing the limits and sending the emails at the same time
