### ISSUE TITLE
Bug with report stucked at 99% and not ready

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#187]
### Bug Description

We got a bug filed in [through freshdesk](https://cds-snc.freshdesk.com/a/tickets/8558) with the following:

> Finished a mailout yesterday afternoon (Reminder 2021-11-16) - the report is still not downloadable. Typically I can download at least an early copy within an hour of the mailout - would it be possible to get a copy of this report? I need to do some work with the results today.

The job for that report:
https://notification.canada.ca/services/a17b67a0-2680-45b0-a820-6b7ad3d28902/jobs/81c4b320-84c3-4f7b-bab7-777ae828f54e

### Task Outcome

Know why it is stuck at 99%.

**Comment by sastels** [comment]
Looks like we did not send a notification for one of the rows in the document. That is the phantom sending" email.
https://docs.google.com/spreadsheets/d/1JMZEWNhAfK7T6F8mAeyMNAd1I9VrI3DqrjdMYpi5CL0

**Comment by sastels** [comment]
However, they can download the report anyway at
https://notification.canada.ca/services/a17b67a0-2680-45b0-a820-6b7ad3d28902/jobs/81c4b320-84c3-4f7b-bab7-777ae828f54e.csv

**Comment by sastels** [comment]
@jimleroyer did we ever track down why we lost this email? I didn't do any work on this past what is mentioned in this card.

**Comment by jimleroyer** [comment]
@sastels  There was a row that was skipped in the CSV in the middle of the file. I couldn't get my finger on why. There was no special characters in the line.. although I didn't check for special invisible unicode characters now that I think about it.
