### ISSUE TITLE
Remove expectation of being able to put multiple email addresses into the recipient box

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#189]
__Remove expectation of being able to put multiple email addresses into the recipient box__

**Description**
As a user of Notify, I need to be able to send messages to myself, send to a single recipient and send to a list of recipients so that I can send messages simply and easily and with confidence on my first attempt. 

**WHY are we building?** Users currently have the expectation that they can put multiple addresses into the email recipient box, but they are unable to do so.
**WHAT are we building?** We are removing the expectation that they can add multiple addresses to the email box by making the choice between the 2 more obvious. 
- [x] We are removing the default flow to "send to one recipient". See designs below
- [x] This design was crafted in both official languages
- [x] A11y annotation
- [x] Dev-design review
- [x] Create PR

QA checklist
- [x] A11y automated scanning, screen reader check EN/FR (Elise)
- [x] Design/content/translation check compare figma to prod (Yael)

**VALUE created by our solution and how we know we've ACTUALLY created this value?** This should save the user time and friction by clarifying how to send to one recipient, and how to send a message to many recipients.

**Acceptance Criteria** (Definition of done) 
_To be refined through discussion with the team_

Given I want to send a template, when I choose to add recipients, then I am guided through the correct steps to add one or multiple recipients.

**Comment by amazingphilippe** [comment]
Follow design specs in Figma https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/?node-id=4166%3A19145

**Comment by EliseKa** [comment]
@amazingphilippe, @YedidaZalik and I have designed [options in Figma](https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/?node-id=4166%3A19145)

**Comment by amazingphilippe** [comment]
Being reviewed:
- [x] Content critique (Date?)
- [ ] Team review (Date?)
- [ ] Interaction critique (December 6)

**Comment by amazingphilippe** [comment]
Figma prototype ready for testing with users. 

FR Link: https://www.figma.com/proto/fRVRKm7cM8MUuBWUJbrfgU/Sending-from-web-interface-%7C-Envoyer-par-interface-web?page-id=4474%3A19571&node-id=4513%3A20328&viewport=342%2C48%2C0.3&scaling=scale-down&starting-point-node-id=4513%3A20328&show-proto-sidebar=1

EN Link: https://www.figma.com/proto/fRVRKm7cM8MUuBWUJbrfgU/Sending-from-web-interface-%7C-Envoyer-par-interface-web?page-id=4474%3A19571&node-id=4513%3A20277&viewport=342%2C48%2C0.3&scaling=scale-down&starting-point-node-id=4513%3A20277&show-proto-sidebar=1

**Comment by adriannelee** [comment]
Steve will wrap up this card today

**Comment by yaelberger-commits** [comment]
Currently in prod, merged PR a few days ago

**Comment by yaelberger-commits** [comment]
QA task: 
I compared the content in the [figma file](https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/Sending-from-web-interface-%7C-Envoyer-par-interface-web?node-id=4166%3A19145) with the pages in production for En and FR for Ajouter des destinataires/Add recipients and followed the flows for both one recipient and many in both EN and FR through to the next pages. 
Everything worked as expected, radio buttons worked, content and designs were the same in prod as the Figma.

**Comment by yaelberger-commits** [comment]
@EliseKa would you be able to also do the translation check? I confirmed that the content is the same in Figma as in prod, but I'm not sure if that's the same as a translation check, which would be to ensure the translation is correct.

**Comment by EliseKa** [comment]
A11y check and screen reader check look good! The translation is also good.

I just want to double check: there's a couple of screens with copy changes that were not included in the handoff. Was this intentional? cc @amazingphilippe @yaelberger-commits 

![Capture d’écran, le 2022-03-11 à 15.37.17.png](https://images.zenhubusercontent.com/6140b56b70c730353f1cd567/8c4a7b0d-bf48-40e9-85ba-ea8ddadd03b2)
![Capture d’écran, le 2022-03-11 à 15.25.46.png](https://images.zenhubusercontent.com/6140b56b70c730353f1cd567/5e41e196-de52-401f-b789-59978fd0c674)

**Comment by yaelberger-commits** [comment]
@EliseKa I'm not sure. @amazingphilippe can you provide info on the above copy changes please?

**Comment by amazingphilippe** [comment]
Not intentional, we'll have to include these before we approve the PR.

**Comment by yaelberger-commits** [comment]
Need to review new PR

**Comment by yaelberger-commits** [comment]
Merged a fix
