### ISSUE TITLE
Align language with mental model/expectation/language of users

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#190]
__Align language with mental model/expectation/language of users.__

**Description** 
As a user of Notify, I need to be able to understand the instructions for creating a message template so that I can send my first message to a recipient with confidence on my first try and not make mistakes along the way or embarrass myself or my team. 

**WHY are we building?** _Usability testing with CDS members showed:_ 

- [2/4 FR participants did not know that “Objet” referred to the subject line in the email. They thought it was only for themselves.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recJ4gIPY4NSiziWR?blocks=hide)
- [Explore inconsistent labelling the word "emphasize" for block quotes, users might think it means bold [in formatting guide]](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/rec1vpG3P4nuQejkD?blocks=hide)
- [One person did not understand the use of the word "structure" for formatting an email [in personalisation guide]](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/reclj3LIgw56ayBjM?blocks=hide)

**WHAT are we building?** 
- [x] We will use content design to align the words we use with our users mental models and ensure consistency in the words we use in the service.
- [x] We make changes in both official languages
- [x] We test changes with users

**VALUE created by our solution and how we know we ACTUALLY created that value?** Users will be able to create message templates with ease, so that they can send their first message to a recipient, reducing friction with the service and reducing drop-off rates. 

**Acceptance Criteria** (Definition of done) 
_To be refined through discussion with the team_

Given I am creating a new message template, when I fill in the template fields, then I know where each piece of information will show up and which ones will be visible to recipients.

Given I am drafting a message that needs personalisation and formatting, when I look at the guides, the way the concepts of 'formatting' and 'creating block quotes' are described can only be interpreted in one way.

**Comment by amazingphilippe** [comment]
Figma https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/?node-id=4307%3A19908

**Comment by amazingphilippe** [comment]
Coded and ready for testing with users.

PR: https://github.com/cds-snc/notification-admin/pull/1203

Deployment might wind down by the time we get to do testing. We just need to do a push to the PR branch to re deploy when we are ready.

**Comment by amazingphilippe** [comment]
- [ ] Get the testing PR above ready for review

**Comment by adriannelee** [comment]
Noting that this card needs to be turned into an implementation card

**Comment by amazingphilippe** [comment]
This story is already implemented in the linked PR: https://github.com/cds-snc/notification-admin/pull/1203

**Comment by amazingphilippe** [comment]
QA:
- [ ] Design: check against figma
- [ ] A11y review: (list pages to scan)
- [x] Dev: code reviewed
