### ISSUE TITLE
Make it possible to preview formatting while editing a template

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#191]
_Make it possible to preview formatting while editing a template_

**Description** 
As a newer Notify user who may have little/no experience with markdown, I need to be able to have confidence that I have formatted my email template correctly before I save it so that I can ensure I don't make mistakes or send the wrong thing to recipients. 

WHY are we building? Users aren't confident that they are formatting the messages correctly as the markdown editor does not give formatting feedback.
WHAT are we building?
- [x] A temporary solution that allows users to swap between a preview and a markdown view, before saving a template. 
- [x] Tested with users again. 
- [x] A11y annotation
- [x] Dev-design review
- [x] Create PR
- [x] Test, review and QA
VALUE created by our solution: Users can preview their templates before they commit to saving it. 

**Acceptance Criteria** (Definition of done) 
_To be refined through discussion with the team_

Given that as a user I have created a draft message, when I'm done drafting the message, then I know I'm able to preview the message and edit it again before sending it 

*Make sure it is easy to get back into edit mode after save/preview

**Comment by amazingphilippe** [comment]
Figma iterations in: https://www.figma.com/file/RLcM0JwlQsd2uVK3GJr5qY/?node-id=1253%3A29363

**Comment by amazingphilippe** [comment]
Critiques for this story

- [ ] Interaction critique (December 20)

**Comment by amazingphilippe** [comment]
- [ ] A11y annotation
- [ ] Create PR
- [ ] Test, review and QA

**Comment by adriannelee** [comment]
@yaelberger-commits @amazingphilippe I did some tidying up of the finding about the 'save' and 'preview' buttons and now there is a new finding that might change the design of this slightly: 

[One participant expected to go back to the templates page after clicking 'save'](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recJkHXO7nxatfj7K?blocks=hide)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/191?planning-poker) with ZenHub @amazingphilippe @adriannelee @YedidaZalik

**Comment by amazingphilippe** [comment]
- [ ] Rewriting this card to make this stroy more accurate based on designs and findings
- [ ] Do the PR

**Comment by amazingphilippe** [comment]
Annotated designs: https://www.figma.com/file/RLcM0JwlQsd2uVK3GJr5qY/Drafting-message-templates-%7C-Creer-des-gabarits-de-message?node-id=1365%3A326

**Comment by adriannelee** [comment]
Dev-design review happening today.

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/191?planning-poker) with ZenHub @sastels

**Comment by yaelberger-commits** [comment]
Unit tests need to be refactured to support this

**Comment by yaelberger-commits** [comment]
In Review with the devs, to bring back into this sprint

**Comment by yaelberger-commits** [comment]
Steve reviewing comments from Phil and Jimmy
Phil wants to do some a11y testing but Heroku not working (stuck)
Steve will check Heroku

**Comment by yaelberger-commits** [comment]
Support ticket with link not working
https://cds-snc.freshdesk.com/a/tickets/9060

**Comment by yaelberger-commits** [comment]
Phil completed A11y review

**Comment by yaelberger-commits** [comment]
Jimmy approved PR on dev side
Phil approved it too

**Comment by andrewleith** [comment]
Looks great, preview/edit feature works as expected, passes all a11y checks.

Tested in Chrome and Firefox.
