### ISSUE TITLE
Provide more reassurance for sending bulk messages

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#192]
**Description** 
As a Notify user, I need to be able to confirm that my bulk message is being sent to all the recipients on my list so that I can have confidence I sent my messages to the right number of people. 

WHY are we building? 
[5/9 people not sure when the email would be sent. They wanted to see the preview earlier (the review page).](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recAwBg2WJbGPxSLh?blocks=hide)
[3 / 9 participants were unsure from the preview that the bulk email would go to all the recipients (the preview only shows one email)](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recY1TIoIynqumvVs?blocks=hide)

WHAT are we building? 
- [x] Design indicators that show and preview the bulk message. Content and hierarchy of the preview page should help users understand better what the "send all" button does at the bottom of the page. 
- [x] In both official languages. 
- [x] Test again with users. 
- [x] A11y annotation
- [x] Dev-design review
- [x] Create PR
- [x] Test, review and QA

VALUE created by our solution. 
A clearer screen and users that have confidence when sending bulk messages. 

**Acceptance Criteria** (Definition of done) 
- [ ]  Link research insight back to hypothesis from Epic or Objective in Airtable
- [x]  Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [x]  Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

Given a user has uploaded a list of recipients, when they are about to click the final "send" button, then the user has confidence their messages will be sent to all the recipients on their list.

**Comment by amazingphilippe** [comment]
Follow design specs in Figma https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/?node-id=4165%3A19118

**Comment by EliseKa** [comment]
Phil, Yedida and I started documenting the problem and options yesterday in [FigJam](https://www.figma.com/file/9dYF2fbvySlcGpiaYPlZTg/Notify-Design-Spec?node-id=0%3A1)

**Comment by EliseKa** [comment]
@amazingphilippe, @YedidaZalik and I have designed [options in Figma](https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/?node-id=4165%3A19118)

**Comment by amazingphilippe** [comment]
Ready for team review

**Comment by amazingphilippe** [comment]
Being reviewed:
- [x] Content critique (Date?)
- [ ] Team review (Date?)
- [ ] Interaction critique (December 6)

**Comment by amazingphilippe** [comment]
Figma prototype ready for testing with users. 

FR Link: https://www.figma.com/proto/fRVRKm7cM8MUuBWUJbrfgU/Sending-from-web-interface-%7C-Envoyer-par-interface-web?page-id=4474%3A19571&node-id=4513%3A20328&viewport=342%2C48%2C0.3&scaling=scale-down&starting-point-node-id=4513%3A20328&show-proto-sidebar=1

EN Link: https://www.figma.com/proto/fRVRKm7cM8MUuBWUJbrfgU/Sending-from-web-interface-%7C-Envoyer-par-interface-web?page-id=4474%3A19571&node-id=4513%3A20277&viewport=342%2C48%2C0.3&scaling=scale-down&starting-point-node-id=4513%3A20277&show-proto-sidebar=1

**Comment by adriannelee** [comment]
Noting that this card needs to be turned into an implementation card

**Comment by adriannelee** [comment]
Dev-design review happening today.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/192?planning-poker) with ZenHub @amazingphilippe @sastels

**Comment by yaelberger-commits** [comment]
Review criteria in PR

**Comment by yaelberger-commits** [comment]
Need someone to scan the page for a117 check and check against the figma

**Comment by yaelberger-commits** [comment]
Yael to QA against Figma 
Adrianne to QA for A11y scan

**Comment by adriannelee** [comment]
Reviewed for a11y QA and left a few comments

**Comment by yaelberger-commits** [comment]
QA: https://github.com/cds-snc/notification-admin/pull/1239

To access these templates:

On an email and a sms template
Add multiple recipients and add one of the following csv
A good csv
A csv with bad emails or bad phone numbers
A csv with the wrong headers
Review the pages. List should be limited to the first 10 entries.
If your file is valid, you'll be able to load more entries for preview
If your file is invalid, you wont see a preview
Moving from previous to next preview should be allowed, the first email only has a "next preview" button the last preview only has a "previous preview" button

- [ ] Safari
- [ ] Chrome
- [ ] Firefox

**Comment by yaelberger-commits** [comment]
My QA is done @amazingphilippe 
@adriannelee do we need to add Figma links to Airtable for this one?

**Comment by yaelberger-commits** [comment]
@amazingphilippe is this in prod now?

**Comment by amazingphilippe** [comment]
I need to fix some conflicts and then I can merge this to staging. It will become production the next time we do a release

**Comment by yaelberger-commits** [comment]
Has been merged, ready for next release
