### ISSUE TITLE
Give clear guidance on how to use variables

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#193]
__Give clear guidance on how to use variables__

**Description** 
As a newer or infrequent Notify user creating templates, I need to be able to know how to use variables to customize my templates so that I can send the correct information in messages with confidence on my first try. 

WHY are we building? Users lacked examples for using variables. Especially in how they are used with spreadsheets. 
WHAT are we building? 
- [x] Clearer documentation with better examples. 
- [x] An explanation on how variables can be used when sending with a spreadsheet. 
- [x] In both official languages
- [x] Changes are tested again with users
VALUE created by our solution: Users that work better by reading documentation are better prepared when they need to use variables. 

**Acceptance Criteria** (Definition of done) 
_To be refined through discussion with the team_

Given a new user to Notify, or a user who hasn't used it in a while, needs to draft a message template and personalize it, when they go to the guidance on using variables, then they know they change variables like Given Name, use multiple variables together, they can use a spreadsheet with variables successfully, they can use conditional variables.  

* Consider changing the word "variable" to something else
* Set expectation of what a variable is, before telling the user _how_ to use it
* Some research to figure out what word to use
* Consistency to ensure we use the same word 
* Connect with Forms team about this

**Comment by yaelberger-commits** [comment]
**Just an FYI in the API documentation, we use "Personalisations" not variables**

> Your API call must also include any fields that have been set up as personalisations. Personalisation allows you to change what shows up in a specific message as it gets sent out. You might use personalisation to:
> 
> Address a user by their name
> Provide users with a specific link to click
> Send a unique transaction number as a follow up
> Give users a dynamically generated list of actions they need to take

**Comment by amazingphilippe** [comment]
Work in Figma https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/?node-id=4347%3A19562

**Comment by amazingphilippe** [comment]
- [ ] Get the testing PR above ready for review

**Comment by adriannelee** [comment]
I wonder if this issue can be put into Done?

**Comment by amazingphilippe** [comment]
I need some help with the PR. Same PR as #190 and #192

**Comment by amazingphilippe** [comment]
QA:
- [ ] Design: check against figma
- [ ] A11y review: (list pages to scan)
- [x] Dev: code reviewed
