### ISSUE TITLE
Validate against notification with too big content

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#201]
# Improve validation message on content too large for our technical infrastructure

As a user,
I need to be informed of notification's content that are too large and will not get through Notify,
So that I can get a clear error on the system's limitation and adjust the content of my notification afterward.

# **Acceptance Criteria** (Definition of done) 

Given that our system fails on notifications that are too big, when it receives too large of a message, then a proper validation is returned.

- [x] Switch the status code from the 500 family class (internal error) to a 400 family class (bad request).
- [x] The internal error should be a proactive validation response.
- [x] Explains the limitation of the message content being too big. 

# Additional information

* It's hard to put a hard and precise limit on how big a message should be because the limit is on the SQS queue content and not directly on the message limit itself. The message put on the queue will contain various data such as the recipient's email, and the content itself. Then it depends on the characters encoding in the message as well.

**Comment by yaelberger-commits** [comment]
@jimleroyer flagging that we already have a card for notifications with too large content if you want to build off this card for incident response

**Comment by andrewleith** [comment]
A possible easy win here could be discarding the `personalisation` data when there are no variables in the template.

**Comment by jimleroyer** [comment]
Related PR that puts a constraint of 50kb on overall personalisation data that contains all combined variables:
https://github.com/cds-snc/notification-api/pull/1561

**Comment by amazingphilippe** [comment]
One last sync with Steve

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/201?planning-poker) with ZenHub @jimleroyer

**Comment by jimleroyer** [comment]
I also spoke with Omar and Stevie-Ray from the Forms team to communicate the new variables size limit along with the file attachments number set to 10. They foresee this will be an issue and we'd have to tackle this if we want to provide proper support to Forms team.

I also want to question GDS to know if they ever encountered that issue, if they use AWS SQS for their celery backed queue system which cause this 256k limit issue.

**Comment by jimleroyer** [comment]
The message returned on size too large (by one byte in this case):
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/daec4ea4-0bfd-4d13-a614-574ed835f623)
