### ISSUE TITLE
Manually create ECS instance that will host the performance tests

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#203]
### User story

As a developer of Notify team,
I want to manually create the ECS instance through clicksops in AWS,
So that we validate our approach before automating the process with Terraform
and avoid unnecessary extra work.

### Acceptance Criteria

- [x] The ECS infrastructure is created in the staging environment.
- [x] We increased the number of file descriptors in the ECS container.
- [x] We ran the performance tests successfully with no reported errors on file descriptors limit being reached or too low.

### Additional Notes

Likely approach:
- create an ECS cluster / task / service
- create a repo in ECR and hook it up to the task
- create a bucket in S3 for the reports
- create permissions so that the docker image can write to the S3 bucket

#### Steps as described by Patrick

>Alrighty, here are some pieces that should help you get up and running with an ECS cluster + scheduled task to run performance tests:

> 1. Create the ECS cluster and ECS task definition: https://github.com/cds-snc/gc-articles/blob/main/infrastructure/terragrunt/aws/ecs/ecs.tf#L1-L108
> 2. Create a container definition template used by the ECS task def in step 1: https://github.com/cds-snc/gc-articles/blob/main/infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl (it’s also where you’d set the ulimit ).
> 3. Define a CloudWatch event rule and target to invoke the ECS task on a schedule: https://github.com/cds-snc/covid-alert-metrics-terraform/blob/main/aws/modules/ecs_task/cloudwatch.tf#L1-L27.  The bit that is tricky here is setting up the subnet IDs and security groups for event target.  In your case, you could put the ECS task in any of your public subnets with a security group that allows egress to the internet.

> I can help you get unstuck with any of the above if you decide to go with Terraforming the ECS cluster. (edited)

**Comment by jimleroyer** [comment]
Created the cluster and ECS Task so far in the staging account:
https://ca-central-1.console.aws.amazon.com/ecs/v2/task-definitions/perf-tests/1/containers?region=ca-central-1

Feel free to resume on my effort if you pick up my task (after proper heads up).

**Comment by jimleroyer** [comment]
I put that card back as the ECS task does not trigger on schedule, so I am manually testing the AWS EventBridge configuration to see if I can find the issue with the configuration issued from Terraform and fix it. 🤞

**Comment by jimleroyer** [comment]
Alright, I found the EventBridge configuration config issue and brought some changes to the Terraform [code to fix it hopefully](https://github.com/cds-snc/notification-terraform/pull/334). Putting this task back in Review status for now.

**Comment by yaelberger-commits** [comment]
Waiting until we have whole terraform up and running to validate steps in terraform
