### ISSUE TITLE
[Optional] Make published tests performance reports accessible to public

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#205]
**Description**
As a Notify Team member, I need to be able to access performance reports.

WHY are we building?
This will help the team evaluate / measure the performance over a period of time or post a release 

WHAT are we building?
Exposing the performance reports for easy access

**Acceptance Criteria** (Definition of done) 

- [ ] Notify team members can access performance reports.

**Comment by yaelberger-commits** [comment]
Deciding whether to make public, or keep access limited to the team, how to safely expose performance reports
