### ISSUE TITLE
Connect with other Notify teams

### ISSUE THREAD

**Issue by leannelabelle** [cds-snc/notification-planning#209]
Connect with and organize discussion with UK and Dutch government

We are hoping to share best practices, learn from each other and make connections.

Connect with internal team to discuss how we want to present
Set times and days that work for the team
Record? 
Shared Slack channel?
Explore a regular cadence

**Comment by yaelberger-commits** [comment]
Connected with Novum Dec. 2, 2021

**Comment by yaelberger-commits** [comment]
Connected with UK Notify team Dec. 7, 2021
