### ISSUE TITLE
Validate empty SMS messages

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/notification-planning#21]
## Steps to Reproduce

1) Have a template containing only a variable.
2) Send a text message with the empty variable.
3) The returned HTTP status code should be 200 but the notification status will be in `sending` state for 4 hours, until it switches to a `technical failure`. A celery error should be noticed on every retry of the notification as well.

## Why we should fix that

* We are allowing an invalid message to be sent to AWS.
* We can report on the error earlier to the user.
* Reduce celery errors noise that we get on support.

## Expected Behaviour

* No celery errors should get triggered.
* A warning log should be surfaced for us to notice it on an active search in AWS CloudWatch.
* The status should be reported to the user.

## Actual Behaviour

Celery errors are reported to support channel and 4h late technical failure is reported to the user.

**Comment by jimleroyer** [comment]
Communicated to the client the fix that we brought and deployed last Friday:
https://cds-snc.freshdesk.com/a/tickets/8324
