### ISSUE TITLE
ZenHub workflow

### ISSUE THREAD

**Issue by leannelabelle** [cds-snc/notification-planning#211]
ZenHub workflow

Outline and share the ZenHub workflow with the team so that everyone understands roles and responsibilities. 

1. Review existing flow
2. Determine what's working and what's not
3. Outline new flow, each stage (pipeline), roles and responsibilities
4. Document the process
5. Share with the team

https://docs.google.com/document/d/1_aBW782z_K4ewNnJCguB__99g5RmqD_YEpdQ0Goo-Vk/edit#heading=h.3k2qskj7gakg

https://miro.com/app/board/uXjVOI5pA6A=/

- [x] New Bug report template
- [x] Updates to User Story Template
- [x] New Issues template?

**Comment by yaelberger-commits** [comment]
I can start work Friday on a document to share out the new flow, each stage (pipeline), roles and responsibilities

**Comment by adriannelee** [comment]
[Started documenting the current flow/what each of the columns currently mean](https://docs.google.com/document/d/1_aBW782z_K4ewNnJCguB__99g5RmqD_YEpdQ0Goo-Vk/edit#heading=h.3k2qskj7gakg)

I looked a bit into limitations of Zenhub & how to best use it. Questions:

- @yaelberger-commits have we already explored using 'Milestones' on Zenhub?

**Comment by yaelberger-commits** [comment]
Continuing to make notes in a doc on the columns on our board, roles and responsibilities, discussions with Josh

**Comment by adriannelee** [comment]
Yael continued working on the doc yesterday & convos with Josh. Meeting with me today to put the doc into a FLOW! WHOO!

**Comment by yaelberger-commits** [comment]
@adriannelee I'm not convinced we should create a new template for New Issues, because once they get refined, they become user stories, and we would need to create new cards using the User Story Template at that point. I think I'll just put the instructions for New Issues in a READ ME at the top of the column instead and pin it. Thoughts?

**Comment by adriannelee** [comment]
@yaelberger-commits Hmmmm .. what about one template that has several sections? Like, fill out the "New issues" section of the template to start and complete the rest of the template if it gets to the backlog?

I'm wondering how to keep the elements of the template easy to refer to when completing the card (which is difficult to do if the info is on a separate card)

**Comment by yaelberger-commits** [comment]
Shared a deck on the new workflow for the team to review and provide ongoing feedback https://docs.google.com/presentation/d/1_sPItXDa3q1ixZd3ZVQVQJWWmKn_mgInFMiurnD-ya8/edit#slide=id.g101c13ff337_0_0
