### ISSUE TITLE
Use a dedicated service and template meant for performance tests

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#215]
# Description

As a developer of Notify,
I want a dedicated service and templates for performance tests,
So that if these are compromised, they are not allow hackers to leverage as phishing attack,
And to have a service owned by all and that won't be disabled once a developer leaves.

# Acceptance Criteria

Given that the performance tests will be owned by all, when a developer leaves or if the service is compromised, then we will have a more stable performance tests environment and a more secure one as well.

**Comment by sastels** [comment]
Added Performance Test service and made a few templates:
https://staging.notification.cdssandbox.xyz/services/44c1a3f5-6a11-4952-b6f4-94dd46d009f2
