### ISSUE TITLE
Triggering retention limits and redaction for PTs

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#228]
# Description

We need to track down how many PTs are using Notify to double check from a policy and security side if we triggered the following: 
- Reduce default retention to 3 days
- Enable redaction
- Enable alarms for if the service’s data is accessed

# Acceptance Criteria

- [x] List the amount of PTs using Notify. We will need the links or service IDs.
- [x] Sharly to draft email/ message informing them that we will be changing their settings within X days? to have 3 days retention, redaction, and alarms for if the service's data is accessed. This way, PTs can message us if they have a problem with this
- [x] Yael to review message
- [x] Change service levels by the date specified
- [x] Enable redactions on templates of affected services.
- [x] Add warning alarms 
- [x] write incident

**Comment by jimleroyer** [comment]
For the moment, the warning alarm that is triggered for sensitive services is stored in Terraform and hard-coded in this file:
https://github.com/cds-snc/notification-terraform/blob/e4e778ff0e67e4d3e59d69197d00947f712d0782/aws/eks/cloudwatch_log.tf#L41

**Comment by yaelberger-commits** [comment]
List of P/Ts ID using Notify
* Ontario Notify (1 live service) 
* Nova Scotia (17 live services)
* New Brunswick / Nouveau-Brunswick (1 live service)
* Gov.ab.ca (0 live services)
* British Columbia (5 live services)

**Comment by jimleroyer** [comment]
Hmm there might have been a miscommunication from my part. By service ID, I meant the unique identifier of a service such as `e749373f-5b18-44b4-a566-c7333302f55d` for _Ontario Notify_. This is how we can refer to a service in the code to raise an alarm.

**Comment by sharlychan-cds** [comment]
Here's the list! https://docs.google.com/spreadsheets/d/1FKRRV5-E2t_0MV77sfOr3otygxcAzK0zYM3VU9xJSTA/edit#gid=0

**Comment by yaelberger-commits** [comment]
Thanks @sharlychan-cds 
That was my mistake @jimleroyer I didn't know where to find those so I'll have to do more exploring. Hope you have what you need now

**Comment by jimleroyer** [comment]
Thank you team for providing the list! you're the best.

**Comment by jimleroyer** [comment]
Unfortunately, that will require more effort code wise. Updating the alarm in AWS Cloudwatch can't be done as this needs to query for admin access based on the list of service IDs and there are too many! The query complains that it cannot get past 1024 characters. Hence it will need a code update in Notify. For a quick fix, I am thinking of:

* Providing the service ID list through a configuration file.
* When admin request access to a service, check the service ID list from config and produce a new log statement telling that a sensitive service is accessed by an admin. We already have a log statement for admin access but not for sensitive services. So this will be an additional log triggered on this condition of sensitive service.
* Modify the existing alarm to react on the sensitive service being accessed. No need to filter through the service ID in the query of this alarm as the log will have been triggered on the new log statement that only gets produced for sensitive service this time.

**Comment by jimleroyer** [comment]
The query I used just in case that might be helpful in some ways in the future or if we can make it smaller but I don't see a way for it unfortunately. The query language for CloudWatch logs (i.e. not the same as Cloudwatch Insights) is cumbersome.

```
{$.log = "*Admin API request*" && ($.log = "*432cb269-7c85-4e38-8e42-3828ec7e5799*" || $.log = "*8f706eb0-0a83-4904-beea-e7687d715511*" || $.log = "*dc3a94a7-9aa8-4b8d-b6ae-a84c124dd58d*" || $.log = "*f118cb89-8b82-4c51-a4b6-1c1480f4a6b6*" || $.log = "*8267ba7a-9a67-430f-a50e-08f6637616f2*" || $.log = "*5f9d8139-7765-42c4-ace5-dfb46049fe04*" || $.log = "*1a5d1b65-edd7-445e-9f92-b84c3ac2cfe2*" || $.log = "*74b93a84-4616-4e86-a35b-6a3de99558c0*" || $.log = "*432cb269-7c85-4e38-8e42-3828ec7e5799*" || $.log = "*9de18305-3e0d-4afe-ad38-d89305d48078*" || $.log = "*5e8e1016-d707-465e-a8c8-c7455dbcc543*" || $.log = "*9c323c8d-8d35-4a0d-9dac-0995b7cfd794*" || $.log = "*8d7d27bb-cdd7-422c-9418-fecb170e0296*" || $.log = "*6598a4ce-99e6-4460-82b7-247ea04ac686*" || $.log = "*5502ec87-f8d7-403a-9fa8-13542128a69e*" || $.log = "*d7f464d8-82a4-4a16-91d2-37005bc075e7*" || $.log = "*a6bf86f8-9287-44be-884e-d093e1c6f019*" || $.log = "*6049fc47-c6e6-4ed1-95a4-27971584c52c*" || $.log = "*e749373f-5b18-44b4-a566-c7333302f55d*" || $.log = "*259f597b-5953-4df9-b0dd-3c5f668b4c61*" || $.log = "*b0f64df5-3ee0-48c0-ace8-fcea11f12687*" || $.log = "*88e2e0b1-f986-47a7-a0d5-8b2da05a641d*" || $.log = "*a7ef2e53-42ab-4b16-9a5b-e623fb778074*" || $.log = "*668f44fb-79fa-44ee-9552-0a419c7de925*" || $.log = "*0ce94d17-34d4-45c2-b705-59695233b29d*")}
```

**Comment by jimleroyer** [comment]
@sastels took the programming side of the task and he's almost done with it.

**Comment by sastels** [comment]
warning alarm code merged into staging. Will need to set the `SENSITIVE_SERVICES` environment variable in production and release the code. 

Note that we need to do a terraform release first to catch the new warnings (the new terraform will catch both old and new style warnings)

**Comment by yaelberger-commits** [comment]
@sharlychan-cds I think the incident has been written, right? Can we check off that box up top?

**Comment by yaelberger-commits** [comment]
Is this still blocked? Seems work has continued on this piece this week, no?
