### ISSUE TITLE
Prioritize Security tasks

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#229]
## Description

Prioritize, define and estimate stories for the security risks identified in our Notify risk register and add to Product Backlog

https://docs.google.com/spreadsheets/d/1GSBptkZe1r1GoTNntGesI31B8eZkTQ4ItTdd172eeOw/edit#gid=0

Airtable for planning purposes: https://airtable.com/appABo5w7s1QNwcPP/tbly7xWWiYbftS8u8/viwg0s3dA8xbBpXwg?blocks=hide

# Acceptance Criteria: 

- [x] A prioritization framework for known security issues is created (Yael)
- [x] Airtable with known security issues listed and labeled for discussion (Yael)
- [ ] All tasks and issues have been discussed and placed in a prioritization category (High, Medium, Low) (Yael & Jimmy)
- [ ] All tasks in the Airtable are added to the Zenhub board in the Product Backlog and tagged appropriately (priority, Security, Refined) (Yael)
- [ ] High priority tasks have acceptance criteria and estimates ahead of next sprint (Jimmy and dev team)

**Comment by adriannelee** [comment]
Yael is adding tasks & going over the spreadsheet to add new issues to the board

**Comment by yaelberger-commits** [comment]
40% complete

**Comment by yaelberger-commits** [comment]
Through Team Product Strategy Meeting discussion, security became a higher priority to tackle next sprint so I'm focusing some time this sprint to prepare Security tasks and issues with Jimmy to have them ready.
