### ISSUE TITLE
Add alert to new API Lambda logs

### ISSUE THREAD

**Issue by iokpala** [cds-snc/notification-planning#230]
# Description

As a  Notify Developer, I need to be get updates when 400s and/or 500 errors appear on the new API Lamda logs

WHY are we building?

Timely notification alert when 400s and/or 500s occur

WHAT are we building?

Using Terraform to add the alerts. 

VALUE created by our solution

Helpful and relevant information that would lead to quick issue analysis and resolution

# Acceptance Criteria

- Developers can receive timely and helpful messages when 400s and/or 500s occur.

**Comment by yaelberger-commits** [comment]
Trying to trigger an error that would cause the alert to go off

**Comment by sastels** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/230?planning-poker) with ZenHub @jimleroyer @jzbahrai

**Comment by jzbahrai** [comment]
Tasks left. This is for the new HeartBeat API that was added:

1. Change the heartbeat lambda code to take into account: exit code, better logging indicating what API we are hitting, raising an error if a 500 is hit.
2. Add a cloudwatch alarm for the heartbeat code.
