### ISSUE TITLE
Terraform code for production api canary test

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#231]
# Description

As a developer, I need to be able to canary test our new lambda api so that I can limit the risk as it is slowly rolled out.
As a developer, I need to use terraform to create our infrastructure so that it is easy to understand and modify.

We have moved the Notify api from a server running in our k8s cluster to a stand-alone lambda function. We now need to deploy it to production and replace the k8s version. We have decided on a canary release, where initially the lambda will get a small amount of traffic while most goes to the current k8s api. This will allow us to verify the new system works without the risk of the entire system breaking. As our confidence increases we will ramp up the share of traffic going to the lambda until it reaches 100%.

# Acceptance Criteria

- [ ] terraform code written and successfully applied to production, with 0% of the traffic directed to the lambda.

**Comment by sastels** [comment]
https://github.com/cds-snc/dns/pull/213

**Comment by yaelberger-commits** [comment]
Adding special endpoint for Kubernetes API in staging

**Comment by yaelberger-commits** [comment]
Writing terraform for staging that's analogous to terraform for production that already exists so we can test terraform production changes we want to make in staging.

**Comment by sastels** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/231?planning-poker) with ZenHub @jimleroyer @jzbahrai

**Comment by jimleroyer** [comment]
@sastels Do you think we should move this one to done? As now we have #266 to bring final production touches to the canary release?
