### ISSUE TITLE
Update documentation to reflect api canary test and move to lambda

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#232]
# Description

As a developer, I need to understand where and how the api is running so that I can maintain and improve Notify.
As a manager I need to understand where and how the api is running so I can communicate such to stakeholders.
As someone working on the ATO I need to understand where and how the api is running so I can assess the security risks.

We are moving the api from our k8s cluster to a stand alone lambda function. We should update our documentation to reflect this, including (but not limited to):
- [x]  relevant READMEs
  - at the very least, a small section on changing environment variables might be nice, since with the lambda they're set in the terraform repo secrets.
- [x] [Notify architecture diagram](https://drive.google.com/file/d/1kO_G8QVdF7fSMZlkbOZmZ2_Z3pDbqLoC/view)
- [x] ATO documentation
  - evidence of logs and alarms for lambda and api gateway

# Acceptance Criteria
- [ ] all relevant documentation has been updated to reflect our canary deployment
- [ ] Notify product manager is happy
- [ ] ATO channel folks are happy

**Comment by sastels** [comment]
New diagram: https://drive.google.com/file/d/1R0R2JQNEcITzBu6FzqMBGD0QG-VnTgFt

**Comment by sastels** [comment]
alarms for api lambda at:
https://github.com/cds-snc/notification-terraform/blob/main/aws/lambda-api/cloudwatch_alarms.tf

**Comment by sastels** [comment]
log group `/aws/lambda/api-lambda` at https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fapi-lambda

**Comment by jimleroyer** [comment]
Procedure to release the canary mechanism in to production:
https://drive.google.com/file/d/1R0R2JQNEcITzBu6FzqMBGD0QG-VnTgFt
