### ISSUE TITLE
Implement canary release in staging environment

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#236]
# Description

As a Notify developer, 
I need to manually create a canary release in the staging environment
so that I can test early how to split traffic between the lambda API and EKS
and explore upcoming issues prior to program these in Terraform.

## WHY are we building?

To reduce deployment risk of deploying our lambda API in one slow roll instead of an instant and risk one. It also offers an easy way to rollback our changes if the lambda API deployment proves to be difficult.

## WHAT are we building?

[A canary release](https://martinfowler.com/bliki/CanaryRelease.html), which would allow a slow roll of redirecting traffic from the Kubernetes cluster to the Lambda API.

## VALUE created by our solution

More stable approach for deployment within CDS, also a new technique for the organization (but well known in the industry).

# Acceptance Criteria** (Definition of done) 

Given the Notify application in the staging environment, when it receives traffic, then it should be split between the lambda API and the kubernetes cluster as predefined on a weight mechanism configured in the canary release mechanism.

* Security controls in place
* Measuring success and metrics

- [ ] The traffic is split between the api lambda and the kubernetes cluster, based on a percentage or weight mechanism that provides control for a slow roll.
- [ ] The necessary AWS components have been created in staging, to be replicated by the Terraform task.
- [ ] The manually created components in AWS have been deleted once it has been replicated by Terraform.

**Comment by sastels** [comment]
![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/8df38827-f422-4e9d-8821-e893a9634645)

**Comment by sastels** [comment]
So Pat suggested we actually do this in terraform so that we can test our terraform code before pushing to production. Idea is to just hack some terraform locally (connected to the SRE Tools AWS account where https://api.staging.notification.cdssandbox.xyz/ lives.
Steps:
1) Create the TF to manage the existing k8s A record and import the existing record into the TF state.
2) Modify the TF to create the two weighted records (this will replicate the PR in the DNS repo).

**Comment by sastels** [comment]
This appears to be done. We also believe we have a process for creating the records in production that will not cause a downtime:

1. Update the existing api record in the AWS console to become a weighted record with a value of 255  (all records).
2. Import this new weighted record into the Terraform state.
3. Run terraform plan with the new weighted = 0 record.  Expect to only see that one record created.
terraform apply to create the weighted = 0 record.


Note: the import command that worked (on staging) was:
```
terraform import aws_route53_record.api Z03787061QOM2973GWMV4_api.staging.notification.cdssandbox.xyz_CNAME_loadbalancer
```
Where loadbalancer is the value of the set_identifier property of the aws_route53_record resource.

**Comment by jimleroyer** [comment]
Good work! 🙌
