### ISSUE TITLE
Send a heartbeat to the API lambda

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#237]
# Description

As a system administrator for Notify, 
I need to have a heartbeat mechanism that continually sends a notification to the lambda API
so that I know if Notify will get go down.

## WHY are we building?

We want to make sure that Notify is not going down.

## WHAT are we building?

A heartbeat mechanism sending notifications every minute, which should raise an alarm 

## VALUE created by our solution

Reliability and insurance. 

# Acceptance Criteria** (Definition of done) 

Given a new lambda API, when a heartbeat notification is sent through it, then report of failures should be surfaced when the heartbeat skips.

* Security controls in place
* Measuring success and metrics

**Criteria**

- [ ] The previous lambda is decommissioned.
- [ ] A new heartbeat lambda is in place.
- [ ] If the heartbeat skip a beat, it should surface an alarm.
- [ ] A heartbeat could be in place for both the API and lambda to test individual endpoints and systems.

# Additional Notes

## Existing heartbeat template

Find the heartbeat template named *Errand* [in this service](https://notification.canada.ca/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/templates/0eaacefb-02c1-493e-97b0-33b61f0a01e3). 

Consider cleaning up this service where many templates seem deprecated and non used anymore. We can use the latest [GC Notify production ready service](https://notification.canada.ca/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553) instead.

## Previous lambda, provided by @maxneuvians 

The previous lambda was more of a ad hoc status system in place. We can redefine this in a better fashion for the new one that would hit the lambda API.

```
const nodeFetch = require("node-fetch");
const createToken = require("./auth.js");
const baseUrl = "https://api.notification.alpha.canada.ca";
const path = "/v2/notifications/email";
const endpoint = `${baseUrl}${path}`;
const version = 1;
import { NotifyOptions } from "./interfaces/NotifyOptions";

export const NotifyClient = async (token: string, data: NotifyOptions) => {
  var options = {
    method: "POST",
    uri: endpoint,
    body: JSON.stringify(data),
    headers: {
      Authorization: "Bearer " + createToken(token),
      "User-agent": "CDS-NOTIFY-API-NODE-CLIENT/" + version,
      "Content-Type": "application/json"
    }
  };

  let response: any = {};

  try {
    const result = await nodeFetch(endpoint, options);
    response = await result.json();
  } catch (e) {
    response = { error: e.message };
  }

  return JSON.stringify(response);
};
```

```
var jwt = require("jsonwebtoken");

function createToken(key: string) {
  const secret: string = key.substring(key.length - 36, key.length);
  const client_id: string = key.substring(key.length - 73, key.length - 37);
  return jwt.sign(
    {
      iss: client_id,
      iat: Math.round(Date.now() / 1000)
    },
    secret,
    {
      header: { typ: "JWT", alg: "HS256" }
    }
  );
}

module.exports = createToken;
```

## Elixir and the magic potion

For fun, consider a nod to grand wizard Max and implement the [lambda in Elixir](https://github.com/aws-samples/aws-lambda-elixir-runtime) using [the Elixir Notify client](https://github.com/maxneuvians/ex_notification).

**Comment by jzbahrai** [comment]
done! but need to release this for prd.

**Comment by jimleroyer** [comment]
Keeping this one in QA for now as the current heartbeat might send multiple messages. Let's check and fix if that is the case.
