### ISSUE TITLE
Configure the lambda API for NewRelic

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#238]
# Description

As a Notify system administrator, 
I need to measure Notify performance profiling individually both the lambda & kubernetes
so that I can assess success of the lambda-api compared to the existing kubernetes stack.

## WHY are we building?

To measure success and app performance.

## WHAT are we building?

We will reconfigure NewRelic to have a different application name for the existing API sitting in the Kubernetes cluster and the API lambda.

## VALUE created by our solution

Tracking and monitoring our stack.

# Acceptance Criteria** (Definition of done) 

- [ ] Send email to NewRelic to find out if it's possible to monitor lambda API in NewRelic

Given the new lambda API sitting alongside the kubernetes cluster, 
when traffic occurs to both, 
then we can compare the new and existing solutions side by side with actual metrics.

**Goal**

* Measuring success and metrics

**Criteria**

- [ ] Get comparison metrics for Notify in both lambda API and kubernetes cluster.

# Notes

It should be possible to force name the application name in NewRelic by providing a configuration at [run time in Gunicorn](https://github.com/cds-snc/notification-api/blob/bebd806cad9581101e5cc1d52db2613c1baa1fa9/gunicorn_config.py#L7). [Refer to this documentation for more details](https://docs.newrelic.com/docs/apm/agents/python-agent/installation/python-agent-admin-script-advanced-usage/#run-program). For example, defining the `NEW_RELIC_APP_NAME` environment variable _might_ be sufficient.

**Comment by sastels** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/238?planning-poker) with ZenHub @jimleroyer @jzbahrai

**Comment by jimleroyer** [comment]
Putting the task to block. I pushed some more configuration env variables into the lambda variable but the lambda metrics still do not show into New Relic. There might be some more configuration required on the lambda side or maybe New Relic. I will ask around to see if who installed New Relic initially, we could get some help.

**Comment by iokpala** [comment]
Started looking into the reasons why the Lambda applications were not appearing in our New Relic dashboards.

Initial suspects from the briefing were application.py[1] and gunicorn_config.py[2]. Debugging through did not initially give clue as everything seemed fine.

Went on to look at the Lambda API set and found only `NEW_RELIC_APP_NAME` was defined, which according to the documentation "the only required setting for infrastructure was the license key" so tried updating the ENV variables with `NEW_RELIC_LICENSE_KEY` and it appeared, updating the license key did not seem to provide the Python agent library. Carried out searches on Cloudwatch against the API Lambda log group but no sign of errors, info, or warning messages.

A deeper look into the initialize [4] code (new relic Python agent library) gave further clarification that all that is happening in gunicorn_config.py[2] is instance creation from New Relic configs, Local Environment variables, and defaults.

This suggests that our expectation for the automatic creation and ingest performance data from the Lambda environment application was never going to happen.

Based on further interrogation of the New Relic Python library the creation or activation[5] of an application can be achieved with what appears to be an invocation of `register_application`[6], it is noteworthy to point out that `register_application`[6] isn't called anywhere in our API code. It is noteworthy to mention that the `activate_application`[5] 

This led to the question, how were the already existing APM entities/applications on our dashboard created. Upon review of our New Relic Dashboard, it became clear that there are User, REST API, and Insight or ingester keys.  The key we have been using is an ingester key, which implies even if the `activate_application`[5] were invoked it may likely return a 403.


[1] https://github.com/cds-snc/notification-api/blob/master/application.py
[2] https://github.com/cds-snc/notification-api/blob/master/gunicorn_config.py#L7
[3] https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/cross-product-functions/install-configure/configure-new-relic-agents/
[4] https://github.com/newrelic/newrelic-python-agent/blob/242c51a869b506d4235c8fedf024002251ac502c/newrelic/config.py#L2798
[5] https://github.com/newrelic/newrelic-python-agent/blob/f99da493986f24a588af50e197bbe62f5ad6332a/newrelic/core/agent.py#L298
[6] https://docs.newrelic.com/docs/apm/agents/python-agent/python-agent-api/registerapplication-python-agent-api/

**Comment by iokpala** [comment]
Linking New Relic with AWS Lambda with the help of newrelic-lambda-cli is  sending the staging environment performance data to New Relic. 

Refs:

https://github.com/newrelic/newrelic-lambda-cli#installation

https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking/

https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/monitoring-aws-lambda-serverless-monitoring/

**Comment by jimleroyer** [comment]
Discussed on gather town with Ikenna, next steps:

1. Move New Relic initialization code into the Python lambda handler function.
2. Deploy into staging and see if that works.
3. Regarding the newly created AWS resources following the execution of the pip install command (i.e. `newrelic-lambda integrations install --nr-account-id YOUR_NR_ACCOUNT_ID --nr-api-key YOUR_NEW_RELIC_USER_KEY`, locate and evaluate the resources. See if we can tag these within the AWS account to know if we can easily track these in the future, as it falls outside the control of our normally created resources by Terraform.

**Comment by jimleroyer** [comment]
Any update on that task?

**Comment by jimleroyer** [comment]
Spoke with Ikenna: we will send an email to the NewRelic support to see if we can get the same level of metrics with the AWS lamda as we did with the Kubernetes pods. My guess is we might not be able to track the same metrics becausse NewRelic would leverage a WSGI compliant environment, which the Kubernetes pod has but that the AWS Lambda environment would not.

**Comment by yaelberger-commits** [comment]
High priority to send the email to NewRelic

**Comment by sastels** [comment]
Is this what we're talking about?
https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/monitoring-aws-lambda-serverless-monitoring/

**Comment by jimleroyer** [comment]
@sastels It might be best to sync in person, that would go faster!

**Comment by mohamed-cds** [comment]
Started working with @iokpala to instrument the lambda with the newrelic wrapper and agent. Similar process to how Opentelemetry works. Since we're running our lambda in a container it's not as straight forward as the lambda's that run in zip files due to the use of the lambda runtime interface emulator (RIE)

**Comment by mohamed-cds** [comment]
PR ready for testing once the k8s/lambda sync goes to Production: https://github.com/cds-snc/notification-api/pull/1507

**Comment by jimleroyer** [comment]
Just spoke with @mohamed-cds 

This is ready to be tested but not merged yet. Mohamed worried that an additional change with other concurrent changes around configuration might conflict and increase risk. Especially that merged changes will need to be tested in staging and might hold a release (unless we revert) if it does not work as expected.

Future steps would be:

* Merged the PR in @mohamed-cds comments just above API #1507. 
* Look into NewRelic for the lambda-api in staging environment.
* Mohamed to follow up on issues.

**Comment by mohamed-cds** [comment]
Implemented successfully in staging in https://github.com/cds-snc/notification-api/pull/1507. @jimleroyer when you get the chance can you validate the data matches whats available in the k8s newrelic setup ?

Should be releasing to prod today.

**Comment by mohamed-cds** [comment]
New relic working in production + warning and critical alerts created.

**Comment by patheard** [comment]
This is now reporting data as expected for the staging and prod Lambda API:
![image.png](https://images.zenhubusercontent.com/6141f63cba17b3613a6dcef0/43d21aa1-9cdb-48dd-b14c-928b1ec41db4)
