### ISSUE TITLE
Collect all valid endpoints for document-download-api

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#253]
_Collect all valid endpoints for document-download-api_

# Description

As a developer on Notify, I need to be able to collect all valid endpoints for document-download-api so that I can block any attacks using WAF ACL. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

# Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by jimleroyer** [comment]
Running the `flask routes` comment provide all valid endpoints:

```
> flask routes
2021-12-06T17:25:51 Name flask.app INFO no-request-id "Logging configured" [in \notification-document-download-api\download-api-env\lib\site-packages\notifications_utils\logging.py:78]
Endpoint                    Methods  Rule
--------------------------  -------  --------------------------------------------------------
download.download_document  GET      /services/<uuid:service_id>/documents/<uuid:document_id>
healthcheck.status          GET      /_status
healthcheck.status          GET      /
metrics                     GET      /metrics
static                      GET      /static/<path:filename>
upload.upload_document      POST     /services/<uuid:service_id>/documents
```
