### ISSUE TITLE
Add valid endpoints to WAF rules (API)

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#254]
_Add valid endpoints to WAF rules_

# Description

As a developer on Notify, I need to be able add valid endpoints to WAF rules so that I can block any attacks on Notify endpoints. 

WHY are we building?
Harden the other components on Notify (API & admin) .. AKA putting up wood planks on the doors

WHAT are we building?

VALUE created by our solution
Prevent _some_ endpoints from being exposed

# Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Monitor WAF rules to ensure that valid traffic is not being blocked

**Comment by yaelberger-commits** [comment]
_Add valid endpoints to WAF rules_

# Description

As a developer on Notify, I need to be able add valid endpoints to WAF rules so that I can block any attacks on Notify endpoints. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

# Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by jimleroyer** [comment]
@yaelberger-commits Sorry I should have told you that some tasks exist for the incident action items, I am currently using #251 to implement WAF rules.

**Comment by yaelberger-commits** [comment]
Fuzzing Feb 10, 2020 
Not raising an incident, common scan that hits every service, already have this action item to tackle it

**Comment by yaelberger-commits** [comment]
Fuzzing Feb. 11, 2022
Not raising an incident, common scan like yesterday's. Another good reason to tackle this action item ASAP

**Comment by yaelberger-commits** [comment]
Mohamed Nur:  
the 500 http response code might be the reason this is continuing. Anything that's not a 404 will result in more scanning to confirm previous scans results. This applies to both manual and automated scans.

**Comment by yaelberger-commits** [comment]
Discussing enabling linux rule group from count to BLOCK and validating that theory

**Comment by yaelberger-commits** [comment]
Divide into 2 cards, one for API and one for Admin. GC Articles relies on wildcard paths, so we need to be able to check wildcard paths before sending an error message that it doesn't exist. Admin is a bigger piece. Talk to @mohamed-cds @patheard and @timarney

**Comment by yaelberger-commits** [comment]
Leave for a week on Count before setting it to Block

**Comment by jimleroyer** [comment]
Block mode is deployed in staging. We will test today if that works as expected and following successful results, deploy tomorrow in production.

**Comment by jimleroyer** [comment]
This was deployed in production yesterday. We will monitor for a week before considering it to done.

**Comment by YedidaZalik** [comment]
Keep in QA because observed last week that not blocking as much as we hoped
@jimleroyer working on tests - could go back to in progress

**Comment by jimleroyer** [comment]
Monitored URIs blocked by this new rule and none were valid, so the rule is working as intended.
