### ISSUE TITLE
Create a CDS email account for Notify Testing

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#265]

**Comment by yaelberger-commits** [comment]
Following an incident we want to create a CDS Notify email account so we can use it for testing and change the password on a regular basis, so no personal account is used for usability testing

**Comment by adriannelee** [comment]
accounts created for:
EN - notify-ux-test@cds-snc.ca
FR - notification-ux-test@cds-snc.ca
as Google Groups and invited Yael, Jimmy, Phil, Yedida, myself, and Élise to the group.
