### ISSUE TITLE
MOU Process Definition

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#269]
Need to write an MOU Process for products to follow. Coordinate with TBS Finance about what steps should happen and when, signatories etc.

- [x] Map out user journey of federal service owner (from freshdesk to signing, to billing)
MIRO: https://miro.com/app/board/uXjVONVE-tk=/

Meeting notes: https://docs.google.com/document/d/12YV8OMVqvBFWIckct7ZOy7kEYMf1U9pzIoUR3OhzEwg/edit#heading=h.xay2mnexltn

Outcomes
- [x] Service map that maps what we know so far, gaps, known pain points
- [x] Research questions, hypothesis to test
- [x] Ideal or Happy Path service map

**Comment by yaelberger-commits** [comment]
Sharly meeting with TBS finance Jan. 18

**Comment by adriannelee** [comment]
Sharly will summarize notes, maybe today.

**Comment by yaelberger-commits** [comment]
Need to make a new template with TBS finance

**Comment by sharlychan-cds** [comment]
Started to clean up and make an MOU Guide document [here](https://docs.google.com/document/d/1b08PQ6NK6PN-N_aA7Mjd4tY15UW7Xn5QiTmvBt5nXB4/edit#heading=h.pisyfe2iq1w7) that outlines how the MOU process works for Notify

Undergoing an in-depth review of existing MOU template, making changes, and will send to TBS Finance for review next week

**Comment by sharlychan-cds** [comment]
Taking a service design approach - meeting today to work on how to do this

**Comment by yaelberger-commits** [comment]
Service Design approach to defining this process

**Comment by adriannelee** [comment]
Identify the criteria instead of a current process, since the current process is mostly unknown.

**Comment by sharlychan-cds** [comment]
Need to define/ make a list of questions to send over to TBS (findings from the MOU mapping process)

**Comment by sharlychan-cds** [comment]
Sent questions over to TBS finance, awaiting reply

**Comment by adriannelee** [comment]
Sharly will think about what kind of data we need to bill today.

**Comment by yaelberger-commits** [comment]
Need answers from TBS Finance to move forward. Pick up again early April

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/269?planning-poker) with ZenHub @sharlychan-cds

**Comment by yaelberger-commits** [comment]
@sharlychan-cds Should we close and consider this one done (artifact was the Miro board) and open a new one for the process with TBS Finance?
