### ISSUE TITLE
[Onboarding] Welcome Élise!!!

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#27]
# Description 

Here are some tasks to go through that should help you get to know the team and product better to be able collaborate with the team.

Present checklist is here to help us track progress and completion of this.

**Done when** :  New team member says so ! Should have had the time to digest info, connect with team and the access needed are granted 

#  Read and discover **(the following are suggested in order of priority. Reading all of it is not mandatory)**

- [x] [Overview of Notify product](https://docs.google.com/document/d/1naerXecHaMR6-udeYiny5a_84CvIKwITAlwR8ZwsIZY/edit#) 
- [x] [Notify Scavenger Hunt](https://docs.google.com/document/d/1MmKBZqMNpsLU0TlURGCyOlByZHGfZccteuYdGZ9amwM/edit#heading=h.sxqbcn4k0lmo)🕵️‍♀️
- [x] [Directory of links](https://docs.google.com/document/d/15dk3fz6BwX0_ZwHyCXMDYIWCszXSoFarqydKQNeeyx0/edit)
 - [x] [Design onboarding cheatsheet](https://docs.google.com/document/d/1hWjtCQp1N6_EADquwbBAuJ37ZNdxHvfxMCEDtO1M--g/edit#heading=h.g3c6sgz3eiwh)
- [x] [Design documentation](https://docs.google.com/presentation/d/1gwK4b-R3izYsAh12MVWkFknWDR7URkxTPp1jHU9gULc/edit)
 - [x] [Dev resources](https://docs.google.com/document/d/1Nd3tqUO48oQvc0Vkn6iaCv01w1AkjyWbfOG2ZrKwAtI/edit#heading=h.gsberul37syg)
 - [x] [Notify com 101](https://docs.google.com/document/d/19cdOXloQ0bTZuJUidCuMqvOPD18djA_3CnVJdsecaXE/edit)

# Meet and greet ☕️

- [ ] Demo of the product with @stephenyates-cds  the product manager
- [x] Chat about general team dynamic and organisation with our team leader Leanne Labelle
- [x] Chat with Lead Design @amazingphilippe 
- [x] Chat with Lead Researcher @adriannelee 
- [x] Chat with Notify Dev Lead @jimleroyer 

# Get the access 👀

- [x] Get Slack channel access [DM or PM]
- [x] Get Trello access [DM or PM]
- [x] Get Google Drive access [DM or PM]
- [x] Get Figma access [Designer @amazingphilippe ]
- [x] Get platform admin access [Dev lead contact: @jimleroyer ]
- [x] GitHub Access [Contact: @wmoussa-cds  ]

# Access for Dev  ⌨️

- [x] GitHub Access [Contact: @wmoussa-cds  ]
- [ ] LastPass and shared Notify folders inside of it (Staging and prod credentials, environment variables for running the repo locally) [**Contact**: @jimleroyer ]
- [ ] Snyk (Dependency management) [Contact: @jimleroyer ]
- [ ] Sentry (Error logging / debugging for staging) [Contact: @jimleroyer  ]
- [ ] AWS (staging and production accounts) Error log monitoring ; S3 buckets for asset management [Contact: @maxneuvians ]
- [ ] New Relic (Error logging / debugging for production) [Contact: @jimleroyer ]
- [x] Freshdesk Customer ticket support portal [Contact: @jimleroyer  / François Moisan** ]
- [ ] Add to notifications-ops on Google
- [ ] Get platform admin access [Dev lead contact: @jimleroyer ]
- [ ] Easy Retro **[Contact: Mario]**

**Comment by EliseKa** [comment]
Marking this done - @jimleroyer will help me install the repo locally this week, but other than that I have all the accesses I need

**Comment by EliseKa** [comment]
do we close issues or move them to done? :thinking_face:

**Comment by jimleroyer** [comment]
@EliseKa I'd say we put it to `done` and then on sprint review, we can throw them in the `closed` column.
