### ISSUE TITLE
Fine tune platform-admin-looking-at-sensitive-service-warning 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#282]
_Fine tune platform-admin-looking-at-sensitive-service-warning_

# Description

As a Notify admin, I need to be able to know and log when someone is accessing sensitive info of a Notify service so that I can watch for abusive behaviour in the system and justify any time an admin looks at sensitive info, without triggering the alarm for non-sensitive info. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

# Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 
Given a platform admin is looking at sensitive info for a Notify service, an AWS Cloudwatch alarm will go off.

1.) there needs to be some tuning on that alarm, not all of the information for each service should be considered sensitive and you don't need to alarm on everything.
2.) Any log that has the "Admin API request" string should be sent to the SIEM (Sentinel) for reporting in there as it's a great metric to watch for abusive behaviour in the system
3.) We really should be alerting on more then just that one account.
4.) Admins should be required to justify everytime they look at sensitive information to help us catch abusive behaviour and to build good habits in admins

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by patheard** [comment]
After discussing with @mohamed-cds, my take is that its current form that was removed by cds-snc/notification-terraform#374 was just creating noise without any clear action required.

A few things that could be done to improve this:
1. Only trigger an alarm if it occurs outside of an expected "business" window (e.g. between 6pm - 6am). 
2. Change the CloudWatch metric filter so that it's generic and counts admin request looking at any service, and then alarm if you see more than `x` of these metrics in a given time period (say 5 minutes).  The idea here would be to catch an attacker trying to grab multiple service's data.

**Comment by jimleroyer** [comment]
@patheard 'suggestions are good for a quick reactive action, while lowering the alarm's noise.

I'd also like for us to have a report or a dashboard that tells who accessed which services. We could not take actions quick enough but we would have a bird view of all access, legitimate or not.

**Comment by yaelberger-commits** [comment]
@jimleroyer was this done already? @sastels  tackled some of this during our current sprint right? Now called "log platform admin activity" https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/354

Or is this something else?

**Comment by sastels** [comment]
1) and 3) are done (we turned off the #notification-ops alarm and added more PTs)
I don't think we've done anything with 2) (SIEM)
not sure if 4) is still relevant since we turned off the alarm?

**Comment by patheard** [comment]
Makes sense to me that 4) is no longer relevant.
