### ISSUE TITLE
Create Notify on call support welcome email

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#285]
There were a lot of great docs for On-Call shown during the mock exercises, on CovidAlert we would send this email everytime a person came on call, even if they had seen it before 

https://notification.canada.ca/services/052753c0-1efc-4de4-9fda-481186109000/templates/41893078-4c58-4272-b66e-d01c123ee6cd

it might be useful to do something similar.

**Comment by yaelberger-commits** [comment]
One of the notify devs should be able to get it working using this code.
https://github.com/cds-snc/site-reliability-engineering/tree/main/tools/on-call-checklist
I'm sure @Pat [he/il] could help them

**Comment by yaelberger-commits** [comment]
DRAFT started here https://docs.google.com/document/d/1MVnF-8j8PA2yLCTjD-dGV3ctdt04afD0UBmztliOZvo/edit

**Comment by yaelberger-commits** [comment]
Draft completed, asking Calvin for some feedback, draft has been used to create a template in Notify. Next step is for Notify devs to sync the sending with the on call schedule

**Comment by jzbahrai** [comment]
https://github.com/cds-snc/site-reliability-engineering/pull/374
