### ISSUE TITLE
Organize existing research July 2019 - Dec 2020

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#289]
# Description

As a GC Notify team member, I need to be able to know how to find existing research so that I don't reinvent the wheel. 

Reorganizing the existing [Notify research repository ](https://airtable.com/shrkJfPWYGh4MlH1P) will help anyone on the team quickly search through existing research and conduct additional research without repeating what's been done before.

# Acceptance Criteria
- [x] [Notify research repository ](https://airtable.com/shrkJfPWYGh4MlH1P) is reorganized and information is complete as best as possible
- [x] The new AirTable is reviewed by team, people are aware how to look up information
- [x] Everyone on the team has access to the AirTable
- [x] Insights align with the product vision

**Comment by yaelberger-commits** [comment]
A bit blocked, would be helpful to see designs of the UI of when the study was done to understand the insights, working with @amazingphilippe

**Comment by yaelberger-commits** [comment]
Able to see the UI and get unblocked, cleaning up testing and hypothesis tabs

**Comment by adriannelee** [comment]
Scoped down the card and moved into Done
