### ISSUE TITLE
Re-organize the Terraform DNS configuration

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#292]
# Story

As a developer,
I need to have the Terraform staging DNS configuration in the same repository for both staging and production environments,
so that I can easily control changes, reduce risk of mistakes with DNS configuration spread everywhere -- consider that DNS configuration is super sensitive.

At the moment, the **staging** DNS configuration is not even written in any of our repository. It was created as clickops. We could not reproduce the Notify environment within a Flask if we desired because of this.

## WHY are we building?

DNS configuration is sensitive. This needs to be stored and reproduced easily if our infrastructure goes down.

## WHAT are we building?

1- Write staging DNS configuration into a CDS owned repository.
2- Get both staging and production DNS configurations in the same CDS owned repository. At the moment, the production configuration sits into the [cds/dns repository](https://github.com/cds-snc/dns/).

## VALUE created by our solution

Stability, reproducibility, audits, reviews and change management.

# Acceptance Criteria** (Definition of done) 

Given we have missing and spread DNS configuration for our environments, consolidate into the same repository for reducing overall risk.

**Comment by yaelberger-commits** [comment]
Raise to Pat and Wissam

**Comment by jimleroyer** [comment]
This task has been addressed by recent @ben851 's effort to align both staging and production environments DNS configuration within our own notification-terraform repository.
