### ISSUE TITLE
Decide on whether we want to keep New Relic around or not.

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#294]
New relic is a system monitoring tool Notify uses.

**Comment by yaelberger-commits** [comment]
Could use Notify 101 for this kind of intro training

**Comment by jimleroyer** [comment]
Thanks, I'll close this issue. 

I am not sure how we could replace NewRelic with XRay, as there is close integration with Flask that NewRelic provides and XRay can't for example. But that's up for discussion.

**Comment by jzbahrai** [comment]
We are probably not going to get rid of it
We use it to monitor flask endpoints
Is it easily replaceable with Amazon offerings? (We aren’t sure but no off the top of our heads)
Can use it to get timings / profiling of parts of app
