### ISSUE TITLE
Google Analytics metrics for the public website

### ISSUE THREAD

**Issue by EliseKa** [cds-snc/notification-planning#297]
# Description

In preparation for the set up of Google Analytics, define metrics that will be useful to inform design decisions on the public website. Also consider the future addition of Mixpanel and how we can leverage data from this tool for the public website.

**Comment by EliseKa** [comment]
Miro board: https://miro.com/app/board/uXjVOX2JbeI=/?invite_link_id=423096695969

**Comment by adriannelee** [comment]
Finished reviewing :) Great job and I love the format.
