### ISSUE TITLE
Wordpress rest API

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#299]
_Wordpress rest API_

# Description

One option for integrating content from GC articles into Notify is to use the WordPress API. Using this, we are able to get the content from WordPress, and render it using our current tech. A benefit is that the transition between content pages and application pages is seamless, because there is none. 

As a Notify user, I need to be able to navigate documentation and product pages seamlessly so that I can know that I am always on the same website without any doubt. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

# Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given I'm a user visiting the Notify website, when I navigate to a new page on Notify, then I trust that I am still on the right website, and not on a different one.

* A11y
  * Consistent navigation
* Bilingualism: 
  * Bilingual URL and fetching bilingual content. 
* Security controls in place
  * Caching and fallback for when WordPress is unavailable

**Comment by amazingphilippe** [comment]
Sync with the GC article team:

Key takeaways:
GC articles is doing the following:
- experimenting with the Navigation being pulled from the API
- getting https://highlightjs.org setup for the API docs page --- these pages will have a new template to accommodate wider / more text
- looking at some cache busting (to make sure we see our content updates right away)
- creating a "fetch" helper  + some kind of wildcard route for the primary content pages in notification-admin
- For the homepage + potentially some other pages GC article will experiment with more structured data where we can pull "chunks" into the template vs doing a full page render.  This will allow fine grained control over the layout i.e. locked layout with editable pieces.  Might look at doing the same for "Why Notify". Looking at either ACF or  https://docs.carbonfields.net for handing structured data.

Notify team should look into:
- Figuring out our bilingual routing to help with the fetch helper function
- Looking at the fetched pages from the Notify side and make sure they look nice and responsive. Fix any bugs.
- With an overview of the site, look at possible special content blocks we'll need (like documentation side-by-side, code blocks, column layouts) and make a list of our required blocks.

**Comment by amazingphilippe** [comment]
- Started work for the homepage striped layout
- Demo (January 10)
- Sync between GC Articles and GC Notify devs (January 10) to go a bit more in depth on the progress so far.

**Comment by amazingphilippe** [comment]
Both teams synced on January 10. The wp api approach seems sound to both teams. Notify will focus on reviewing a PR containing "Features" and "Why Notify" pages

Next steps:

- [ ] review process for new content. @EliseKa 
- [ ] Next PRs will focus on: bilingual routes, wildcard routes, other public facing pages

**Comment by EliseKa** [comment]
linking the card I'm working on for the review process: https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/313

**Comment by amazingphilippe** [comment]
Working on more complex layouts like the home page. 

- [ ] Find a better way to safelist WordPress styles with purgeCSS
- [ ] Fixing class-less headings coming from WordPress content
- [ ] Working with color from WordPress? See if this is a desirable editor experience

**Comment by amazingphilippe** [comment]
Currently working on the editor experience by recreating the homepage. I feel we can split this task into another one.

**Comment by amazingphilippe** [comment]
Break away tasks to re-create all the content in GC Articles. Make these tasks dependencies to this larger one.
