### ISSUE TITLE
Manually scan pages

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/notification-planning#3]
### Task Description
Manually scan pages for accessibility issues.

### Task Outcome
We're setting up a methodology to manually scan Notify as part of our standard workflow. Since we can't only rely on automated scanning, we need to be organized and able to scan Notify manually for a11y issues. 

These tests are not meant to replace any of the automated checks, rather to enable us to improve our compliance, best practice and usability coverage.

1. Tests are outlined here in [this sheet](https://docs.google.com/spreadsheets/d/15yyyT0KHb5WZisJ626289CnMdagH8J51LNGL31Y8TZE/edit#gid=0)
2. Workflow for tests are in [this Trello board](https://trello.com/b/Qj96p840/gc-notify-a11y-assessment). Each page or scenario can be checked against 11 categories of tests
3. Issues are logged through [this airtable form](https://airtable.com/shrK0KQqG6vO9hfB4)
4. Issues are organized in [this airtable](https://airtable.com/appXU7GFaiLu73dFQ/tbliNDExyC1Pe39ZH/viwNQUV7C4L1JfzjA?blocks=hide)

### Acceptance Criteria
- [ ] List of what needs to be completed.

**Comment by amazingphilippe** [comment]
Moving this to review since we are progressing towards the hackathon. We have enough a11y issues to work with. The next steps will involve:
1. Expanding our coverage close to 100%, getting ready for an external a11y audit
2. Get an external a11y audit
