### ISSUE TITLE
Increase recipient trust in messages sent by Notify

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#316]
_Trust_

# Description

We want to increase user trust in email and SMS messages sent by GCNotify so that users can get the information they need and feel confident this information is coming from a Government source and not a malicious actor. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

# Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by amazingphilippe** [comment]
Some ideas:

- include creating a footer or a permanent section in all emails. Something like seen on .gov websites:
![image.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/cab14d8c-f562-4641-b4da-f5f228009cb3)
- have a list of valid sender addresses that people can reference on a canada.ca website. 
- think like scammers: 
![image.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/da5fa779-d566-4dd0-a70c-fea0ce023f92)
- consider sending all emails from a .gc.ca second level domain. If we can.

**Comment by yaelberger-commits** [comment]
Duplicate of #1170
