### ISSUE TITLE
[NEEDS VALIDATION] Fix notification status to sending when sending, sent when sent and delivered upon confirmation

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#317]
_Fix notification status to sending when sending, sent when sent and delivered upon confirmation_

# Description

Senders can't necessarily trust the notification status in their dashboards because they have notifications stuck in the "sending" state and want to know why, and those messages have actually been sent. 

A small percent (2-5%?) of messages (emails?) never get a delivery receipt, and without a delivery receipt they stay in the "sending" status. We would like messages that are sent by Notify but do not receive a delivery receipt for whatever reason to be given the "Sent" status. 

This is an email provider to AWS pipeline issue. 

No "Sent" status in the GUI even though we have it in our database.

As a user, I would like to know when the notification has been sent
And when the notification has been confirmed delivered,
So that I can properly track progress of the notifications I bulk send.

WHY are we building?

We want Senders to trust the GC Notify service and the status of messages in their dashboard

WHAT are we building?
More clearly communicate the true status of their notifications and Senders understand the actual status

VALUE created by our solution
Improved trust in the notification status

The notification status indicates that it is in a sending status when it has been sent. It leads to a few support tickets with users asking why the emails are in a sending state when it has been sent but no delivery receipt has been received yet.

# Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

- [x] validate if eventually # of messages in sending eventually goes down to zero and what are the conditions for a message to go from "sending" to "delivered" - run queries of DB to see if anything more than a day old is still in "Sending"
- [x] Run through a user story mapping with team
- [x] Figure out a measurement. Like less support tickets
- [x] Design MVP of this user story
- [x] Implement, review, QA, release

Given some context, when a sender knows their messages were sent, then they don't need to contact us to figure out what is going on. 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

# Related support issues

* https://cds-snc.freshdesk.com/a/tickets/9564

**Comment by yaelberger-commits** [comment]
Prioritize finding out if users have a problem with the dashboard the way it currently is

**Comment by adriannelee** [comment]
I created an interim card as a partial solution for this issue
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/621

**Comment by amazingphilippe** [comment]
This story would benefit from a user story mapping. I added some more details to the AC to get us started.

**Comment by adriannelee** [comment]
Relevant finding:

[Participants liked the option to cancel a scheduled email. However, "sending" and "delivered" were too similar in concept. Several commented noted that “failed” status is very helpful.](https://airtable.com/appWwAmHwDLtpIyko/tblVTvPCVqdet114A/viwJaOndL8PAQhyPt/recquTphLzvMVFcTY?blocks=hide)

**Comment by yaelberger-commits** [comment]
Could run SQL query just for email

**Comment by yaelberger-commits** [comment]
Check at 11PM when most notifications would be done sending to see if any remain in "Sending" status.

**Comment by yaelberger-commits** [comment]
@adriannelee can you please include @ramya-cds on any brainstorming or design sessions related to this user story? She has insights from working on support that could be helpful when exploring solutions/changes, and perhaps including a dev in those sessions as well
Thanks!

**Comment by sastels** [comment]
So we do have some stuck notifications. Here I look for any older than 12 hours
```
select notification_status as status, count(*), max(now() - created_at) as oldest
from notifications
where notification_status not in ('delivered', 'permanent-failure', 'technical-failure')
    and created_at < now() - interval '12 hours'
group by notification_status

```

| status  | count  | oldest  |
|---|---|---|
| sending  | 81  | 3 days 1 hr |
| temporary-failure  | 4017  | 7 days 9 hours  |

**Comment by sastels** [comment]
Added a card to look into this
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/695

**Comment by yaelberger-commits** [comment]
Needs technical exploration and solution before UX designs can be developed

**Comment by jimleroyer** [comment]
I replied the following to [the new card](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/695):

> This is expected behavior unfortunately. I mentioned that to Max in the past and he said that not all emails receive receipts (up to 1%). Since then, this has been confirmed with my observations as well. This is one reason why I initially started the prototype on having more status supported for a better indication.

> We could reach out to AWS to confirm this as part of this card though. I didn't ask the questions to them AFAIK but maybe Max did in the past.

Just want to make sure this is a known limitation and we level our expectations around receipts (these are not perfect).

**Comment by amazingphilippe** [comment]
Should create smaller stories, based on investigation. Is this even fixable at 100%?

Update the card when the investigations are complete. 

@jimleroyer to update with AWS response.

**Comment by YedidaZalik** [comment]
Note that "sending" is now "in transit"

**Comment by jzbahrai** [comment]
We can shut this ticket - we fixed notification statuses as part of  the bounce rate epic
