### ISSUE TITLE
[Onboarding] Welcome [RAMYA]!!!

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#322]
# Description 

Here are some tasks to go through that should help you get to know the team and product better to be able collaborate with the team.

Present checklist is here to help us track progress and completion of this.

**Done when** :  New team member says so ! Should have had the time to digest info, connect with team and the access needed are granted 

#  Read and discover **(the following are suggested in order of priority. Reading all of it is not mandatory)**

- [x] [Overview of Notify product](https://docs.google.com/document/d/1naerXecHaMR6-udeYiny5a_84CvIKwITAlwR8ZwsIZY/edit#) 
- [x] [Notify Scavenger Hunt](https://docs.google.com/document/d/1MmKBZqMNpsLU0TlURGCyOlByZHGfZccteuYdGZ9amwM/edit#heading=h.sxqbcn4k0lmo)🕵️‍♀️
- [x] [Directory of links](https://docs.google.com/document/d/15dk3fz6BwX0_ZwHyCXMDYIWCszXSoFarqydKQNeeyx0/edit)
- [x] [Notify com 101](https://docs.google.com/document/d/19cdOXloQ0bTZuJUidCuMqvOPD18djA_3CnVJdsecaXE/edit)
- [x] [30-something things to know about Notify](https://docs.google.com/document/d/1pNDfw--2kBPBOEx_9EVKCiLD0wTaC0rjticZv1sVtb8)

# Meet and greet ☕️

- [ ] Demo of the product with @stephenyates-cds  the product manager
- [ ] Chat about general team dynamic and organisation with our team leader Leanne Labelle
- [ ] Chat with Lead Design @amazingphilippe 
- [ ] Chat with Lead Researcher @adriannelee 
- [x] Chat with Notify Dev Lead @jimleroyer 

# Get the access 👀

- [x] Get Slack channel access [DM or PM]
- [x] Get ZenHub access [DM or PM]
- [x] Get Google Drive access [DM or PM]
- [x] Get platform admin access [Dev lead contact: @jimleroyer ]
- [x] GitHub Access [Contact: @wmoussa-cds  ]

# Dev Access ⌨️

- [ ] GitHub Access [Contact: @wmoussa-cds  ]
- [ ] New Relic (Error logging / debugging for production) [ #zendesk-it-support or /zendesk Slack command ]
- [ ] Freshdesk Customer ticket support portal [ #zendesk-it-support or /zendesk Slack command ]
- [ ] Zendesk Customer ticket support portal [ #zendesk-it-support or /zendesk Slack command ]
- [ ] Add to notifications-ops distribution list on Google
- [ ] Get platform admin access [Dev lead contact: @jimleroyer ]
- [ ] Easy Retro **[Contact: Mario]**

**Comment by yaelberger-commits** [comment]
@ramya-cds focus on the non-dev related onboarding. Let me know if you have any questions!

**Comment by yaelberger-commits** [comment]
@ramya-cds Have you completed your Notify onboarding?

**Comment by ramya-cds** [comment]
I have a few tasks left under Meet and greet and will complete them over a period of time. I am good to close this one.
