### ISSUE TITLE
Reports Notify admin access to sensitive services in a weekly manner

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#325]
# Description

As a Notify admin or auditor, 
I need to know who accessed sensitive services in a weekly report
so that I can properly assess security risk and unauthorized access.

- [x] Who's going to look at this report on a weekly basis? (Ops Lead)
- [x] Define what folks are supposed to be looking for
- [x] Clarify what steps an auditor should take if they see something unusual
- [x] Where will this report live?

## WHY are we building?

To assess security risk and unauthorized access.

## WHAT are we building?

v1 - Make a dashboard in cloudwatch with the results of an appropriate query.
Possible v2 - A weekly report that will send who accessed which sensitive services. Use variable in database for sensitive services

## VALUE created by our solution

More audits and security.

# Acceptance Criteria** (Definition of done) 

_To be discussed with the team!_

**Comment by sastels** [comment]
I don't know about the sending out part, but I think we could make a dashboard in cloudwatch with the results of an appropriate query.

**Comment by jimleroyer** [comment]
@sastels As a first step, what you propose is a low hanging fruit that would be quick to implement (we could do right now). I was thinking mid term with a notification sent by Notify, for Notify distribution list and without access to AWS, grouped by user names and services.

**Comment by yaelberger-commits** [comment]
Review with Wissam and present plan to Elodie after ATO report is reviewed

**Comment by yaelberger-commits** [comment]
@sharlychan-cds can we meet to discuss this card and if it's still relevant? Thanks

**Comment by yaelberger-commits** [comment]
We would still have sensitive services, but less. Do we want to be able to track it?
We could create a table in the database and make a screen in the admin section, not surfaced to users.
Instead of reports, data is available dynamically when needed in the Admin interface

**Comment by sastels** [comment]
Note that we can query the logs from python using boto
https://stackoverflow.com/questions/59240107/how-to-query-cloudwatch-logs-using-boto3-in-python

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/325?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by yaelberger-commits** [comment]
Confirm with @jimleroyer v1 option for cloudwatch dashboard as a first step

**Comment by sastels** [comment]
quick dashboard showing a couple things we could do
https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#dashboards:name=Temp_admin_views_of_sensitive_services

**Comment by cgye** [comment]
Some questions:

**Comment by YedidaZalik** [comment]
Andrew spoke to security and developed some criteria. Melissa will document process moving forward.

**Comment by yaelberger-commits** [comment]
Yael reviewed Melissa's process doc yesterday

**Comment by andrewleith** [comment]
Ben approved the PR, waiting until monday to merge.

**Comment by yaelberger-commits** [comment]
Some outstanding policy questions Melissa has

**Comment by yaelberger-commits** [comment]
Andrew to create Slack reminder
Thursdays weekly

**Comment by andrewleith** [comment]
Weekly slack reminder created! Moving to done.
