### ISSUE TITLE
Update: Switch from master to main branch

### ISSUE THREAD

**Issue by iokpala** [cds-snc/notification-planning#336]
## Task

Going forward, we are adopting main as our default branch.
this card tracks the updates to the the repos, replacing master with main branch.

## Acceptance criteria

The following repositories have their default branch set to `main` and the github workflow works as expected:

- [x] notification-admin
- [x] notification-api
- [x] notification-utils

**Comment by iokpala** [comment]
@jimleroyer @jroo  This card is currently in progress.. PRs have been raised. Jimmy suggested that this be put in the back-burner and merged after batch saving

**Comment by jimleroyer** [comment]
Moved back this card into the product backlog as we need to set the default branch of notification-utils to `main`, but the branch has been created in there. What remains should be minimal: set the default branch in github configuration to `main` and test the workflow. Fix the workflow if anything issues arise. That project is usually straightforward at that level though.
