### ISSUE TITLE
Research Questions: Get a pool of 100 Canadian longcodes?

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#340]
_Get a pool of 100 Canadian longcodes_

# Description

Improve reliability
Concern from service owners of SMS going through US phone numbers 
Speed for services with non-dedicated long codes
Improve trust because Canadian # 

As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

# Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by yaelberger-commits** [comment]
Redundant

**Comment by yaelberger-commits** [comment]
Redundant

**Comment by yaelberger-commits** [comment]
Iceboxed. We have a pool of longcodes now

**Comment by jimleroyer** [comment]
@yaelberger-commits We could close this issue if you're ok with it.

**Comment by yaelberger-commits** [comment]
@jimleroyer sure, it was in the icebox but I can move to closed
