### ISSUE TITLE
GC Articles editor experience

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#348]
_GC Articles editor experience evaluation _

# Description

As a Notify or growth team member, I need to be able to edit content using GC Articles so that I can keep Notify's public facing pages updated autonomously. 

Doing so, I also need to contribute back to GC Articles by identifying pain points.

WHY are we building? 
WHAT are we building?
VALUE created by our solution: We can achieve our growth goals and contribute to our platform product suite strategy

# Acceptance Criteria** (Definition of done) 

Given that we are using a work-in-progress product, when we use GC Articles to edit the content of Notify's public pages, then we are able to provide feedback to the GC Articles team. 

Our editor experience is defined with this context in mind:
- GC Articles is a work in progress. It is stable but not necessarily ready for release. 
- We are contributing to GC Articles by testing the tech in a live use case.
- We are able to edit content without intervention in our code base most of the time. 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by amazingphilippe** [comment]
Draft PR demonstrating the homepage: https://github.com/cds-snc/notification-admin/pull/1223

A few tweaks to try with the tech:
- [ ] Editing with our colour tokens.
- [ ] Making buttons more semantic (less div)
- [ ] Could tokens be used for font and sizing too?

A few ideas to try with the editor
- [ ] Responsive layouts that are not hidden in the editor

**Comment by yaelberger-commits** [comment]
draft in Github was demo'd on Friday Jan. 21

**Comment by amazingphilippe** [comment]
Color tokens were added to our WordPress Theme. 
- [ ] Meeting with Mario about the future of design tokens. On Feb 2
