### ISSUE TITLE
Strengthen WAF rules / first wave ~~

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#350]
# Description

As a Notify ops guardian, 
I need to block insecure requests through WAF
so that I can get a bonus on the extra safety in Notify. 

## WHY are we building?

Many Kubernetes WAF ACL has its AWS managed rules set to count only. Most of these should be turned on to block and further rules be applied with rate and geo limits.

## WHAT are we building?

Refining our security rules.

## VALUE created by our solution

More security! Reduce alarms and potential incidents

# Acceptance Criteria** (Definition of done) 

- [x] Children tasks have been reviewed, approved and deployed without excluding legitimate traffic getting blocked.

# Notes

Related platform SRE ticket:
https://github.com/cds-snc/platform-sre-security-support/issues/75

**Comment by patheard** [comment]
Using an Athena table loaded from the WAF ACL logs, the following query was used to find the rules that should still be allowed once the managed rule sets are set to `BLOCK`.
```sql
SELECT label.name, httprequest.uri, action, labels, httprequest
FROM 
    "notification_athena"."waf_logs",
    UNNEST(labels) as t(label)

-- Rules that should not be blocked (have valid use within Notify)
-- provided they are restricted to valid paths only
WHERE label.name not in (
    'awswaf:managed:aws:anonymous-ip-list:AnonymousIPList',
    'awswaf:managed:aws:anonymous-ip-list:HostingProviderIPList',
    'awswaf:managed:aws:core-rule-set:CrossSiteScripting_Body',
    'awswaf:managed:aws:core-rule-set:EC2MetaDataSSRF_Body',
    'awswaf:managed:aws:core-rule-set:GenericRFI_Body',
    'awswaf:managed:aws:core-rule-set:NoUserAgent_Header',
    'awswaf:managed:aws:core-rule-set:SizeRestrictions_Body',
)

-- Not considering any bot-control rules
AND label.name not like '%bot-control%'

AND action = 'ALLOW'
ORDER BY label.name, uri;
```

**Comment by jimleroyer** [comment]
Checking on the rules that are currently considered counted based on a query filtering out requests coming from Notify API clients, these are matched with `count`:

```
#	RuleID
1	AWSManagedRulesAnonymousIpList
2	AWSManagedRulesBotControlRuleSet
3	AWSManagedRulesCommonRuleSet
```

This is the used query:

```
select nt_rules.ruleid as RuleID
  from waf_logs, 
       unnest(httprequest.headers) as t(headers),
       unnest(nonterminatingmatchingrules) as t(nt_rules)
 where headers.name = 'User-agent'
   and headers.value like '%NOTIFY-API%'
   and nt_rules.action='COUNT'
 group by nt_rules.ruleid
 order by nt_rules.ruleid
;
```

I'll expand more on this tomorrow to see if we could block some of these rules if the user agent header field excludes the `NOTIFY-API` value, as these are used by the Notify API clients. So still exploring the data at this time.

I also want to modify Pat's query to see which rules are counted but that we could potentially block.

**Comment by patheard** [comment]
When you expand a bit, could you check if we could keep most of the rules in [AWSManagedRulesCommonRuleSet](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-baseline.html#aws-managed-rule-groups-baseline-crs) as `BLOCK`, but exclude certain ones that we need to allow?

These were the sub rules I was seeing in the common rule set that were triggering on valid Notify requests (e.g. they should be excluded):
```
CrossSiteScripting_BODY
GenericRFI_BODY
NoUserAgent_HEADER
SizeRestrictions_BODY
```

**Comment by yaelberger-commits** [comment]
Back to sprint backlog until picked up again

**Comment by adriannelee** [comment]
Jimmy picking this up today, will chat with Steve. PR is already open,. 50% done

**Comment by jimleroyer** [comment]
Two PRs opened to set common and anon ip rulesets to block:

* https://github.com/cds-snc/notification-terraform/pull/498
* https://github.com/cds-snc/notification-terraform/pull/506

**Comment by sastels** [comment]
Want to talk to Jimmy about his analysis before blocking on `GenericRFI_BODY`.
