### ISSUE TITLE
Document ISED use case

### ISSUE THREAD

**Issue by EliseKa** [cds-snc/notification-planning#357]
# Description

ISED rolled out 2FA using Notify for their public service "My Account". Florence and Élise are interviewing them to learn more about their story and use case.

- [x] Prepare [interview questions](https://docs.google.com/document/d/1KqQfHTjOm1yoPxkowqvDT2KXJmnsgKyTmwkv-MDWX5g/edit#)
- [x] Interview (Jan 26)
- [x] Clean notes
- [x] Draft use case

**Comment by EliseKa** [comment]
Interview questions ready for tomorrow.

**Comment by adriannelee** [comment]
@EliseKa will work on today.

**Comment by EliseKa** [comment]
Update from last Thursday, Jan 27
- Added info in the [Leads/Use case spreadsheet](https://docs.google.com/spreadsheets/d/13tom0cXQSAVz0bYy8D1iTO_L9SAd6c3LlxiHj1pbdbw/edit#gid=0) that Florence started
- Created a [spreadsheet for the web applications](https://docs.google.com/spreadsheets/d/1p9HgYisRCdBpBpQLDM_pqtyZTS91xNUmWsdcoFiKJcc/edit#gid=0) under the ISED umbrella

**Comment by EliseKa** [comment]
Started a deck where I'll log the [generic use cases for Notify](https://docs.google.com/presentation/d/1h2Tcp3DmtdbwAr5kp_ltiGE-SWlSTdgYLMzjVj1eBQ0/edit#slide=id.g111504b0fa8_0_182), and I included this 2FA one. I'm thinking about structuring the rest of the info we learned in the interview somewhere else (like the competitor products, their blockers, why they chose Notify, the people involved in decision-making, etc).
