### ISSUE TITLE
Add JSON and XML file to approved list for service

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#358]
https://assistance.cds-snc.ca/a/tickets/8845

**Comment by yaelberger-commits** [comment]
Need to test before sending an update to the client

**Comment by yaelberger-commits** [comment]
Try to upload a JSON or XML file via a specific service via API

**Comment by jimleroyer** [comment]
The remaining task is to test in staging environment if we can send a JSON/XML file through this service:
https://staging.notification.cdssandbox.xyz/services/44d3d6df-8c46-49fe-97b6-7acddc8077ac

Potential steps:

* Generate a new live api key.
* Use the API to send a XML file and verify if it's working.
* Use the API to send a JSON file and verify if it's working.
* Use the API to send a non supported file (a gif should not be allowed) and verify it's not working.

**Comment by jzbahrai** [comment]
Json file cannot be sent:
```
{
	"errors": [
		{
			"error": "BadRequestError",
			"message": "Unsupported document type 'application/json'. Supported types are: ['application/pdf', 'text/csv', 'text/plain', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'image/jpeg', 'image/png', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.apple.numbers']"
		}
	],
	"status_code": 400
}```

XML doesn't work either.

```
{
	"errors": [
		{
			"error": "BadRequestError",
			"message": "Unsupported document type 'text/html'. Supported types are: ['application/pdf', 'text/csv', 'text/plain', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'image/jpeg', 'image/png', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.apple.numbers']"
		}
	],
	"status_code": 400
}
```

Gif won't work either.

**Comment by yaelberger-commits** [comment]
A fix we need to release, but release pipeline is a bit frozen.
Need to get back to them to ask them to test, could work with what they have.

**Comment by jimleroyer** [comment]
The user reported back this week that everything works now! 🎉
