### ISSUE TITLE
Migrate guidance pages to GC Articles

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#360]
_Migrate guidance pages to GC Articles_

# Description

As a Notify team member, I need to be able to input our currently published content into GC Articles so that we can complete the migration to GC Articles.

To do this, log into Notify's GC Articles: https://articles.cdssandbox.xyz/notification-gc-notify/sign-in-se-connecter/

Here is content that needs to be migrated:
- [x] https://notification.canada.ca/format
- [x] https://notification.canada.ca/personalise
- [x] https://notification.canada.ca/messages-status

Doing so, document your experience of using GC Articles. It is likely that your pages won't look exactly the way you want. Think of the following questions when documenting your experience: 

- What are you able to reproduce?
- What are you unable to reproduce?
- What is challenging to reproduce?

---

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by EliseKa** [comment]
Yesterday I created the English page for the formatting guide. Content is all there, but I need to finish documenting the things I can't reproduce.

**Comment by EliseKa** [comment]
Added the French translation for the formatting guide. 

For the formatting guide, I'm unable to reproduce:
* The accessible tables with formatted text inside, and with the vertical bar on the left.
    * I tried creating blocks (such as quotes or headings) inside a table cell, but it's not possible to insert blocks inside a table cell.
    * It's also impossible to change the text size in a cell.
* Headings other than H1. It works in draft mode, but in preview mode, H2 doesn’t appear as H2, only as paragraph text.
* Bullet points. Any kind of list doesn't work in preview, but work in draft mode.
* The block quote under "emphasis". It works in draft mode but not in preview.
* The yellow highlighted variables. There is no highlighting option. Even for text colour, it's not possible to add colour to a single word in a paragraph (it changes the whole paragraph).

For the table-like images, the workaround I used was to create 2 columns. 
* I found out that the "align bottom" option works in draft mode, but not in preview.
* It seems like the column's widths are based on the length of sentences, not where the vertical center of the page is (for 2 columns). Workaround: I specified the width in pixel for each column (I used 400 px, but this is arbitrary, based on trial and error).

**Comment by adriannelee** [comment]
@amazingphilippe will review and try to contribute today

**Comment by adriannelee** [comment]
One last page to review for migration today.

**Comment by EliseKa** [comment]
Personalisation guide

The things I'm unable to reproduce are things I already mentioned for the formatting guide:
- the accessible tables with a vertical border on the left
- the yellow-highlighted variables
- the headings H2 (works in draft mode, not in preview)

**Comment by EliseKa** [comment]
**Message delivery status**

Things I'm unable to reproduce:
- The headings H2 and H3 (works in draft mode, not in preview)
- The bulleted list (works in draft mode, not in preview)
- The image crispness. No matter what I tried (using a larger size image, playing with width), the image doesn't look as crisp as it does on the Notification website. I also had to set the width manually so it has roughly the same width as the paragraphs.

I've been able to add alt text.

**Comment by adriannelee** [comment]
Phil worked on the styles and found a way to get the preview boxes to show. Will create a PR. 

A few pages on the footer that are not on GC Articles. Élise will work on the French homepage. Phil needs new env codes on WP

**Comment by EliseKa** [comment]
The other pages that must be added will be tracked [in this card](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/373)

**Comment by amazingphilippe** [comment]
I converted Élise's list into a checklist, as most of them needed styles to to work properly.
 
For the bottom alignment, this can be done with styles. 
For even columns, you can also use % units. To get 2 even columns: 50%. To get 3 columns: 33%. And so on. 

Ideally, from now on, the best method would be to copy working blocks in WordPress, paste them and edit their contents. This will make sure the correct classes are being applied at the right places. 
- [ ] We can even work on some internal documentation for common patterns.

**Comment by amazingphilippe** [comment]
One thing remaining is getting access to the asset buckets. I believe I once was able to upload assets to our staging bucket, but not the production one. Perhaps for good reasons, but I think it is blocking us from uploading assets in the right place.

**Comment by amazingphilippe** [comment]
New assets are uploaded on the staging bucket.

**Comment by amazingphilippe** [comment]
Draft page serving as a pattern inventory for our team: https://articles.cdssandbox.xyz/notification-gc-notify/wp-admin/post.php?post=597&action=edit
