### ISSUE TITLE
Migrate API documentation pages to GC Articles

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#361]
_Migrate guidance pages to GC Articles_

# Description

As a Notify team member, I need to be able to input our currently published content into GC Articles so that we can complete the migration to GC Articles.

To do this, log into Notify's GC Articles: https://articles.cdssandbox.xyz/notification-gc-notify/sign-in-se-connecter/

Here is content that needs to be migrated:
- [ ] https://documentation.notification.canada.ca/en/
- [ ] https://documentation.notification.canada.ca/en/start.html
- [ ] https://documentation.notification.canada.ca/en/send.html
- [ ] https://documentation.notification.canada.ca/en/status.html
- [ ] https://documentation.notification.canada.ca/en/testing.html
- [ ] https://documentation.notification.canada.ca/en/keys.html
- [ ] https://documentation.notification.canada.ca/en/limits.html
- [ ] https://documentation.notification.canada.ca/en/callbacks.html
- [ ] https://documentation.notification.canada.ca/en/architecture.html
- [ ] https://documentation.notification.canada.ca/en/clients.html

Doing so, document your experience of using GC Articles. It is likely that your pages won't look exactly the way you want. Think of the following questions when documenting your experience: 

- What are you able to reproduce?
- What are you unable to reproduce?
- What is challenging to reproduce?

---

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by adriannelee** [comment]
Bryan already did it (on Alpha, not sandbox)
