### ISSUE TITLE
make dao_fetch_service_by_id just return a service

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#372]
# Description

As a developer, I need to be have the code be predictable and understandable so I can program with minimal errors. 

the `dao_fetch_service_by_id` function returns a tuple if using cache and just a Service if not using cache. We believe that we never use the second part of the tuple, in which case we should have it just return a Service. This will allow us to get rid of code such as
```
        if isinstance(service, tuple):
            service = service[0]
```

# Acceptance Criteria** (Definition of done) 

- [ ] Code refactored and passing smoke tests in staging

**Comment by yaelberger-commits** [comment]
@jimleroyer can you please refine this task and give it a priority?

**Comment by sastels** [comment]
We did this already in https://github.com/cds-snc/notification-api/pull/1452 - @jimleroyer was there anything not done in that PR?

**Comment by jimleroyer** [comment]
@sastels no all good! we can mark this as done.
