### ISSUE TITLE
ADR describing plan to honour notifications priority in the buffer and batch saving queues

### ISSUE THREAD

**Issue by jroo** [cds-snc/notification-planning#375]
# Description

Currently, when a notification is marked as high priority it is not treated as high priority through the whole sending flow, so some high priority messages are taking longer than 1 min to send, violating our SLO. 

As a user of Notify, 
I need to send a SMS under the 1 minute mark 
so that I can send a quick message my own users expecting a high delivery time.

As a developer of Notify,
When I mark a template as high priority it is high priority and it gets sent in under 1 minute without hitting a bottleneck.and we meet our SLO metrics that the team previously defined, so that Notify does not degrade its offering and honor our agreements with users.

## WHY are we building?

To provide a more reliable and faster service for notifications that need high priority processing.

## WHAT are we building?

We can have discussion on the exact implementations once we tackle the card, but pre-analysis would be:

* Provide different priorities lane in the buffer queues.
* Provide different priorities lane in the database save Celery worker or ensure this one has no bottleneck after careful analysis or find some other ways to promote the high priority messages for the Celery worker.

## VALUE created by our solution

More scalable service by offering different prioritization specific on the template natures and goals. 

* High priority notifications should be low volume and risk of not receiving the message quick would be high.
* Normal priority notifications should be normal volume and risk receiving the message within a few minutes to a few hours is tolerable.
* Bulk priority notifications can be high volume and risk of not receiving the message within a few hours is tolerable.

# Acceptance Criteria** (Definition of done) 

Given a notification, when it is sent, it should be received in a timely manner relative to its template priority (bulk vs normal vs high).

What:
- [x] High priority messages can be received within a minute under heavy load.
- [x] Normal priority messages can be received within one hour under heavy load.

How:
- [x] ADR to describe the problem and hypothesis for solutions, weigh pros and cons of options and document decision
- [ ] The feature is functionally tested.
- [ ] The feature is unit tested.

**Comment by yaelberger-commits** [comment]
1) Backend changes that can enable frontend changes in the future
2) Frontend UI changes for discussion in the future

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/375?planning-poker) with ZenHub @jimleroyer @jzbahrai @sastels @patheard @mohamed-cds

**Comment by yaelberger-commits** [comment]
Goal to finish ADR by end of this sprint

**Comment by yaelberger-commits** [comment]
Thanks Jumana. Is the ADR considered done? If so, please link the ADR to the card, thanks!

**Comment by jzbahrai** [comment]
Hey, I would like to keep this open until this epic is done.

**Comment by yaelberger-commits** [comment]
Jimmy has been working on the ADR for the past couple of days. Looking for eyes from the other devs

**Comment by jimleroyer** [comment]
Moved that ADR to done column.
