### ISSUE TITLE
Pattern inventory in GC Articles

### ISSUE THREAD

**Issue by EliseKa** [cds-snc/notification-planning#376]
# Description

As a GC Articles user working on the Notify website, I need to be able to reuse custom design patterns so that I can build web pages without creating new styles. 

WHY are we building?
To allow content designers build web pages without input from front-end developers.

WHAT are we building?
A draft page in GC Articles that will host the design patterns. The patterns can be copied from the List View.

**Comment by EliseKa** [comment]
@amazingphilippe started the inventory draft page: https://articles.cdssandbox.xyz/notification-gc-notify/wp-admin/post.php?post=597&action=edit

**Comment by amazingphilippe** [comment]
Had to migrate the content from the staging Articles WordPress site. This is the content live now: https://notification.canada.ca/preview?id=88&lang=en

You must be logged in to view this page in production. 
This page must remain a draft

**Comment by timarney** [comment]
I haven't looked at that page but happened to see this issue --- might be helpful

Reusable Blocks might be helpful (I haven't used before but I know they exist)
https://youtu.be/zz6ohn1joeI?t=31

**Comment by amazingphilippe** [comment]
Good point! Created blocks for each pattern and gave instructions on how to convert to regular block to edit their contents.
