### ISSUE TITLE
No release necessary to propagate hpa configuration surprisingly

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#379]
# Issue

Changes performed on the configuration files can propagate directly into the production environment without bumping the tagged release. This lead to unexpected and potentially untested changes. This represent a security risk and mitigating it with a more standard release tag bump would help.

# Notes

No release necessary to propagate HPA configuration surprisingly into production. The referenced changes that propagated automatically into production without a release bump: 
https://github.com/cds-snc/notification-manifests/pull/879

**Comment by mohamed-cds** [comment]
Team decision required before moving ahead with changes to how this works. Details included in this draft PR: https://github.com/cds-snc/notification-manifests/pull/889

**Comment by jimleroyer** [comment]
Just commented on the PR. 👍

**Comment by mohamed-cds** [comment]
PR updated with a new deployment strategy that will avoid surprise production deployments in the future.

**Comment by mohamed-cds** [comment]
new changes merged!

**Comment by patheard** [comment]
I double checked what was applied in Prod and it was the expected manifests using the `v0.44.2` bases for Kustomize.  This was confirmed via the absence of the [`BATCH_INSERTION_CHUNK_SIZE` environment var](https://github.com/cds-snc/notification-manifests/compare/v0.44.2...v0.44.10#diff-e10a2451b220584fb6621e62f2d1ee9dfa77dc79d523181c79f12ac1665400c0R48) in the Prod deployments.

This makes sense as the `v0.44.10` tag still uses the old tagged reference to the `bases`:
https://github.com/cds-snc/notification-manifests/blob/v0.44.10/env/production/kustomization.yaml#L2
