### ISSUE TITLE
Redis queue monitoring

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#381]
# Story

As a developer, 
I want to track different metrics around the Redis queue implementation,
So that I know if it works or not,
And how it performs.

# What

* Metrics that will track the Redis list used to power the new buffer queues. Examples to be refined:
  * Lengths of the list
  * Listing of the lists related to buffer queues.

# Acceptance criteria

- [ ] Tracking of Redis queue metrics is enabled.
- [ ] Metrics are reported to AWS and we can build dashboard out of these.

# Notes

* There is an API provided by AWS to publish metrics into CloudWatch.
* We also have statsd metrics plugged to CloudWatch if that would be an easier alternative.

**Comment by mohamed-cds** [comment]
i'm looking into adding an Cloudwatch alarm for evictions and potentially setting an expire when we publish to the redis queue. AWS docs mention elasticache will evict anything with an expired TTL. Testing this out in my scratch account. If this works it'll be a good indicator of items being "stuck" in the queue.
