### ISSUE TITLE
Update security statement to ready it for testing with users

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#385]
The [security statement](https://notification.canada.ca/security) has not been updated in some time.  We need to:

- [x] compare with existing security statements at CDS/ GDS 
- [x] review [Miro on GC Notify business needs and buckets](https://miro.com/app/board/uXjVOTULUyI=/) to determine what should go into the security statement vs in the SLA vs maybe an extra guidance document 
- [x] update to align with the new privacy statement 
- [x] review considerations from @jimleroyer and @sastels for technical guidance to add to the SLA, specifically around sending SMS:
- [x] Update the Security disclosure section to point users to the updated cds security notice instead.  Security team has been receiving vulnerability reports for other departments and trying to narrow down the places that contain the security+securite@cds-snc.ca email
- [x] Review by PM
- [x] Review by SRE team
- [x] Review by Notify devs
- [x] Incorporate any relevant feedback
- [x] Send to linguistic services and translate the statement with input 
- [x] French Content Review by @amazingphilippe 
- [x] Publish new version on GC Articles 
- [x] Clear Cache

#### Jimmy Royer

I will update if I think of more but on top of my head:

* Their options between dedicated vs non-dedicated long code.
* Their rate of SMS / second they can send with (>20 sms/sec) or without a dedicated long code (1 sms / 2 sec).
* If they batch send, they need to be aware of our technical SLA/SLA.
* If they batch send, they need to throttle on their end or they could have their service back into trial mode. This should be in our SLA.
* They need to send notifications to long code that can receive mobile text message else we could have their service back into trial mode if there are too many noise. This should be in our SLA.
* SMS is a faulty technology that can't guarantee delivery. Notify gets receipts for some delivered messages, but not for all delivered messages. There might be carriers failures, it is not an infrastructure maintained by one with the same level of quality across the different networks. We are at their mercy.
SMS is a faulty technology that can't guarantee trust, at least in Canada. Someone else could impersonate your service easily.
* Sending international costs more and would probably reduce the agreed quota of free SMS a service can send through Notify.
* Sending international is less guaranteed delivery or might simply not work.
* One notification is not necessarily equal to one SMS. Sending long text will divide your messages into multipart and count for multiple SMS, hence increasing your usage of free SMS. It is usually 160 7-bit characters limit. Using special characters might translate to more restricted limit, more here to read for example.
* It's possible a number you send to won't receive your notification if another service from Notify sent one and was blocked as a consequence.

#### Steve Astels

There's at least a couple things IMO

* hitting our api too much - they should use the bulk api instead of hitting the single sms api a lot
* SMSs go out slowly (20/s for all of Notify)
* Checking the response they get back from the api to ensure it was accepted
* Following due diligence in verifying their numbers are correct, are mobile, and are removed from their list if they fail.

[Draft](https://docs.google.com/document/d/1BCeEaQQ9lCvLdHZoZ6u-iDX3C5mG7Gs12WequUrW_qI/edit)

**Comment by yaelberger-commits** [comment]
Similar dependency with unified accounts discovery

**Comment by amazingphilippe** [comment]
Link with scoping work done with the team. [Business buckets on Miro](https://miro.com/app/board/uXjVOTULUyI=/?invite_link_id=122847577111)

**Comment by yaelberger-commits** [comment]
Yedida asked questions at Notify 101
Sharly moved some content into terms of use draft doc, rather than Security Statement

**Comment by yaelberger-commits** [comment]
Yedida bringing to content critique this morning for hierarchy and content organization discussion

**Comment by yaelberger-commits** [comment]
Continuing to work on this today

**Comment by yaelberger-commits** [comment]
Draft for @sharlychan-cds to review
Content critique on Wednesday
Some optional content from private sector statements 
Sync Yael, Sharly and Yedida today

**Comment by jimleroyer** [comment]
Refined content and will review to critique this morning.

**Comment by YedidaZalik** [comment]
Draft ready for review by Yael and Sharly.
Will then implement their feedback before asking dev and security folk to review.

**Comment by yaelberger-commits** [comment]
@sharlychan-cds please add your planning poker

**Comment by yaelberger-commits** [comment]
@YedidaZalik I have reviewed. I think it looks great. Nothing further to add or take away from me.

**Comment by adriannelee** [comment]
Yedida will send to translations today

**Comment by jzbahrai** [comment]
still waiting on translations.

**Comment by YedidaZalik** [comment]
Translation just came back:https://docs.google.com/document/d/1LD5usI8T_UdKvoLQdfoIeKyANf_kERxYK5DnZy4E0A4/edit#

One link is not available in French. Currently exploring how to address that.

**Comment by YedidaZalik** [comment]
Issue resolved with help of translation team by indicating document available in English only

**Comment by amazingphilippe** [comment]
Back from translation. Phil can take a quick overview.

Also, ready to post when:
- [ ] We'd like to test privacy and security statement together.
- [ ] Privacy and security statements refer to each other.

**Comment by amazingphilippe** [comment]
Just read the French security statement. Switched around "Notification GC" to "GC Notification" Everything else looks good!

**Comment by amazingphilippe** [comment]
Moving to blocked until we do the testing? #392

**Comment by yaelberger-commits** [comment]
@amazingphilippe nope! We decoupled from testing so we can proceed with next steps to publish the statement

**Comment by yaelberger-commits** [comment]
Reassigned to Yedida to usher this through the publishing process on GC Articles next

**Comment by amazingphilippe** [comment]
We need a reviewer and copy-paster in GC Articles.

**Comment by yaelberger-commits** [comment]
@amazingphilippe could @YedidaZalik be the reviewer and copy-paster?

**Comment by YedidaZalik** [comment]
Security statement now on GC articles at
[EN Security-new](https://articles.alpha.canada.ca/notification-gc-notify/wp-admin/post.php?post=344&action=edit&lang=en)
[FR Securite-new](https://articles.alpha.canada.ca/notification-gc-notify/wp-admin/post.php?post=377&action=edit&lang=fr) 

I've done a check of both docs but they need to be reviewed by a fresh set of eyes.  The original google docs are:
[EN Security](https://docs.google.com/document/d/1BCeEaQQ9lCvLdHZoZ6u-iDX3C5mG7Gs12WequUrW_qI/edit#)
[FR Security](https://docs.google.com/document/d/1LD5usI8T_UdKvoLQdfoIeKyANf_kERxYK5DnZy4E0A4/edit#heading=h.gjdgxs)
Once they pass review, we'll publish at same time as Privacy docs.
Dave S. gives these steps for publishing:
Rename published original to old
Then publish new
Then ask Dave to clear cache

**Comment by amazingphilippe** [comment]
Reviewed and ready for Dave to clear cache on Article's side
