### ISSUE TITLE
Accessibility Research Plan for Fable

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#387]
As part of our Task Authority (Contract) with OCADU and the Inclusive Design Research Centre, we also have access to Fable Labs for accessibility usability testing. 

We need to organize a research plan. Research needs to be conducted before end of March.

Possible approaches: 

- We could use this as an opportunity to test spam prevention for people with disabilities/ people that use assistive technologies.

- We could run the same kind of usability testing activity we did for people new to Notify (sign in, create a service, make a template, format template, create personalization, send a test message, send a bulk message

[Services Fable offers](https://docs.google.com/presentation/d/1diWJJ9bEOMGDGCdAJzb47pZiN3C7xb5m/edit#slide=id.p4)
[Referencing this doc for methodology](https://docs.google.com/document/d/1nJBXF1vf6YTht-8MvF6cjRlLanKWwA-7NYH2XwtNIAI/edit#)
[Research plan](https://docs.google.com/document/d/1L_RcWhRhdwcr2wDvcY1PtSHIwM9CSzbH_sZ_6n2z7VQ/edit#)
[Test task prioritization](https://docs.google.com/document/d/16EGazrPLRh3AJ2QC9VmdSqHhF5DREFWx-BOYD60B3Bk/edit#)
[Request to Fable](https://docs.google.com/document/d/11Sa20MipbkUGzzoGACTChdBPyOajHDtcRtfRzNwbOPk/edit#)

**Comment by adriannelee** [comment]
Moderated user interviews
* Test the same tasks as the last round (the ‘core’ tasks)
* Do moderated instead of unmoderated because we’re not sure how they will work with a spreadsheet. We don’t want them to get stuck during a test.
* They likely won’t be public servants, so we’ll need to consider that in our analysis.

**Comment by adriannelee** [comment]
@amazingphilippe @yaelberger-commits Are the messages going to be evaluated in the audit? I would like the get those tested as well with Fable.

**Comment by adriannelee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/387?planning-poker) with ZenHub @amazingphilippe @yaelberger-commits

**Comment by adriannelee** [comment]
I'll continue drafting the research plan today

**Comment by yaelberger-commits** [comment]
Prioritizing Notify tasks for testing using Adrianne's new Airtable

**Comment by adriannelee** [comment]
Completed prioritizing tasks and preparing a draft for the request to Fable.

**Comment by adriannelee** [comment]
Yael, Phil, and I prioritized tasks for testing.

**Comment by adriannelee** [comment]
Still need to update today to reflect the most recent info
