### ISSUE TITLE
Scope the SLA

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#390]
Using a service design approach, we will determine:

- who reads the SLA (audience) 
- what needs the SLA meets (business needs and user needs)
- at what point in the journey, a user would read the SLA (when)
- where the SLA should live (page location in service)
- whether we need a signature for the SLA, what kind of signature, from whom and any corollary accessibility issues (signature and/or digital alternatives)
- differences between SLA and Terms of use.

Then we will design a draft SLA.

Yael and Sharly have corrected the Notify Alpha SLA as a starting point for these questions.

**Comment by yaelberger-commits** [comment]
Is this still relevant @YedidaZalik? 
Could we publish SLA v1.5 as-is and bring in a new card if/when we have a need to update it? 
https://docs.google.com/document/d/1hi2s1PJsbmo2pquG-WPm67MKKEDc8p60d7hW8E3nJCo/edit?usp=sharing

**Comment by yaelberger-commits** [comment]
@YedidaZalik I think this card covers the content design work you are currently doing on the SLA, is that right? If so, you can bring it into the sprint backlog!

**Comment by YedidaZalik** [comment]
@yaelberger-commits while you were away we were tracking it in [card 359](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/359)
Should we transfer info to this card and/or delete a card as duplicate?

**Comment by yaelberger-commits** [comment]
@YedidaZalik I will archive this one as a duplicate then. Thank you!
