### ISSUE TITLE
Test new Security Statement and privacy Statement content with users

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#392]
_Test new Security Statement and privacy Statement content with users_

# Description

As a Notify content designer and Platform content designer, I need to be able understand if current and future clients and decision makers understand our Privacy and Security Statements so that I can continue iterating on the content to fill in any gaps or clarify any concepts that are not well understood in both official languages. 

Privacy Statement: We are more interested in learning about the experience of individual Notify account holders/senders
Security Statement: We are more interested in learning about the experience of decision makers 

WHY are we testing?
We updated content because our security and privacy policies have changed and created a new Privacy statement specifically for Notify and now we want to ensure that users can easily find all the information they need to make decisions about whether to use Notify, or if there are any gaps or concepts that need clarifying. 
Risks we want to mitigate:
1) That users decide not to use Notify because they do not get the information they need from these policy documents 
2) That users decide to use Notify for a use case that is not a goo fit, considering our privacy and security posture
3) That users do not understand where their responsibilities lie when it comes to privacy and security when using Notify

WHAT are we testing?
Content testing of the [privacy](https://docs.google.com/document/d/1cfKHaY0tdnhG-2so9rrd69KqonCderFk/edit#) and [security](https://docs.google.com/document/d/1BCeEaQQ9lCvLdHZoZ6u-iDX3C5mG7Gs12WequUrW_qI/edit#heading=h.lb2m1ty5fi2t) statements 

VALUE created by our research
We will have more confidence that our content is clear and well understood by our target audience for these policy documents
We will be able to identify any gaps in the content, or missing information 
The content is easy to read and takes less time for our audience to make a decision about whether to use Notify
Fewer support tickets, more self-serve
We have a good and tested template for platform security and privacy statements

# Acceptance Criteria** (Definition of done) 

Participants
- [ ] A couple participants from large department
- [ ] A couple participants from a smaller department
- [ ] 6-8 participants
- [ ] Some FR participants (2+)
- [ ] A decision maker who's not a security expert (ask Sabine) 
- [ ] A security expert
- [ ] A client or potential client at the working level 
- [ ] A developer
- [ ] A non-developer 
- [ ] Notify OCIO PDPD of the survey details for FYI

Testing
- [x] Test both privacy and security statements
- [x] Test both EN and FR content 
- [x] Identify any gaps in content or concepts that need clarification
- [x] Identify any words or terms that are not understood
- [x] Test structure of the documents (headers, links, lists)

* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by yaelberger-commits** [comment]
Need refinement from Yael and Adrianne

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/392?planning-poker) with ZenHub @adriannelee @amazingphilippe @YedidaZalik

**Comment by adriannelee** [comment]
I'm wondering if having moderated sessions will help answer our research questions .. @YedidaZalik what if we sent the privacy statements to some people and asked them to review asynchronously? Especially if they're people who would need to ask their colleagues for more info?

**Comment by YedidaZalik** [comment]
Yeah, I think asynchronous is a great idea for this!
One question though: it means we'll have to prompt them to review it in a timely way. Is there something we can do to encourage that?

**Comment by adriannelee** [comment]
Oh I thought I left a comment on this yesterday 😆

Before today:
- completed the research plan
- drafted the invite email
- sent the invite mail to translations (due by Sept 14th)

Today:
- drafted the privacy statement and sent to translations (due by Sept 15th)
- I also decided to split the emailing into 2 - the first to decision makers, for them to get back to us by Oct 10th. Then when I get back from vaca, I'll email the security and privacy contacts they provided and ask for their feedback, by Oct 24th. I'll start analyzing on the 24th.
- I'll send the first batch of emails Sept 19th or so, before I leave for vaca

**Comment by yaelberger-commits** [comment]
In translation until next week

**Comment by adriannelee** [comment]
The invite came back from translations. Privacy statement will likely come back tomorrow

**Comment by YedidaZalik** [comment]
Some responses are back, compiled in folder 
Only one response included someone else we can ask - @adriannelee will follow up
@adriannelee @sharlychan-cds @YedidaZalik meeting today

**Comment by adriannelee** [comment]
Met with Yedida to go through the responses, left comments for Sharly. 

Sent new batch (just one additional referral) out. Asked for responses by Oct 24.

**Comment by YedidaZalik** [comment]
Sharly reviewed on Thursday
Waiting for new responses to come in

**Comment by adriannelee** [comment]
@sharlychan-cds @YedidaZalik Should this be marked Done now?

**Comment by YedidaZalik** [comment]
I'm not sure. We'd aimed for 6 -8 participants including at least 2 FR participants. 
It looks like we had 4 participants and none were FR.

**Comment by adriannelee** [comment]
@YedidaZalik I think from the responses we got, it didn't seem like there would be much new data (because many of the 4 gave us similar responses). I think we move this to done
