### ISSUE TITLE
Instrumentation and Monitoring for Batch Saving

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#397]
Step 0:
- Can we do the calculation of these metrics manually?

Questions that should be answered by storing data in metrics and displaying in a dashboard:
1. What are the current sizes of the queues?
2. What is the size of the 'INBOX' at any given time?
3. What would a queuing dashboard look like and can we add to that?
4. How do we store the size of a particular datastructure, capture the metric and then display it?
5. How may inflight queues do we have at any given point?
6. If the inflights age is greater than 5 mins - our retry mechanism is failing. Can we capture and display this?

Mohammad and Pat might have idea surrounding instrumentation and monitoring. Talk to them while designing for this ticket.
Research if there is an equivalent to Metric creation and capture in AWS as there is in  datadog.

# Acceptance Criteria

Have a single place of truth where we can see the above metrics that will ensure the health of the system.

- [x] Have metrics reported into AWS CloudWatch.
- [x] Create alarms on arbitrary threshold based on the new metrics.

**Comment by yaelberger-commits** [comment]
PR, continue testing today

**Comment by adriannelee** [comment]
Mo will try to sync with Jimmy as this is dependent on the other batch saving card.

**Comment by adriannelee** [comment]
Jumana will wrap up this card today

**Comment by jimleroyer** [comment]
I added two checkbox acceptance criteria to the card, including one to have alarms for the new metrics in AWS. We need these to know if something goes wrong.

**Comment by mohamed-cds** [comment]
Alarms implemented in https://github.com/cds-snc/notification-terraform/pull/400. All currently set to warning until we confirm the thresholds will not cause alot of false alarms. Once confirmed a PR will be opened to move the critical thresholds to page the on-call individual.
