### ISSUE TITLE
Clean up IRCC seal tags temporary feature

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#40]
### Task Description

Clean up the code that was added to provide IRCC custom seals used in notifications.

### Task Outcome

Because this was meant as a temporary feature and the current code we have is very specific to one service, we want to remove it to get cleaner and more maintainable code.

### Acceptance Criteria

- [x] The custom IRCC seals tags (along with tests) are completely removed as a feature.

### Additional Notes

The pull requests that introduced the seal tags:

* https://github.com/cds-snc/notification-utils/pull/99
* https://github.com/cds-snc/notification-utils/pull/102

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/40?planning-poker) with Zenhub @andrewleith @jzbahrai @smcmurtry @whabanks
