### ISSUE TITLE
The PR bot is not working anymore

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#400]
# Description

The PR bot does not work anymore since [we fixed the Kubernetes configuration changes](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/379) to properly propagate into production, as we slightly changed how the release process with version works.

# To Reproduce

Execute the PR bot manually via its command line invocation or merge a new changes in any of the watched repositories to trigger it automatically.

**Expected**

The PR bot should have opened a new PR in the manifests repository but it won't.

# Additional context

The root cause is that we don't use the base tag in the `kustomization.yaml` file anymore but moved the production into its own `VERSION` file sitting at the root of the manifests repository.

Also, this error is triggered when running the command line locally. It seems the API calls changed via an transitive dependency, even though we didn't change the related library version explicitly and we have it configured to bump it up only on minor changes (so there should be no incompatible API calls but there are unfortunately!).

```
const octokit = new github.GitHub(myToken);
                ^

TypeError: github.GitHub is not a constructor
    at Object.<anonymous> (D:\Projects\cds\notification-pr-bot\github.js:7:17)
```

**Comment by yaelberger-commits** [comment]
Jimmy verified it is working now
