### ISSUE TITLE
Review Privileged Accounts

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#402]
### Acceptance Criteria 

- [x] Spreadsheet for audit trail

**Comment by yaelberger-commits** [comment]
Not needed if we do proper offboarding
We did this once, and that should be enough if we are diligent about offboarding

**Comment by jimleroyer** [comment]
The updated spreadsheet meant for audits:
https://docs.google.com/spreadsheets/d/1nqRmotJvNY_ftNwr5R7_tk2HKrveNRBA-R77kNTU-FM

**Comment by jimleroyer** [comment]
@yaelberger-commits Can you QA check if the spreadsheet would be sufficient for our purposes please? 🙏

**Comment by yaelberger-commits** [comment]
QAing! Thanks for flagging @jimleroyer

**Comment by jimleroyer** [comment]
I added another tab in the spreadsheet for that but didn't add so far the current accounts. I wondered if we wanted to take timestamp snapshots of these or just have the current list of admins? I assume the latter?

**Comment by yaelberger-commits** [comment]
Yael and Jimmy to sync

**Comment by jimleroyer** [comment]
@yaelberger-commits The AWS admins are not up to us though. We can fill something but we'd need the SRE team to maintain it for us.

**Comment by patheard** [comment]
We don't have a doc for it, but I've filled in that [section of the spreadsheet](https://docs.google.com/spreadsheets/d/1nqRmotJvNY_ftNwr5R7_tk2HKrveNRBA-R77kNTU-FM/edit#gid=56962171) based on the current access.  Going forward, when you need to change someone's access (grant/revoke) you can create an [AWS account access issue in the SRE repo](https://github.com/cds-snc/site-reliability-engineering/issues/new?assignees=&labels=AWS&template=aws_account_access.md&title=AWS+account+access).

If you wanted, you could link to the issue in the spreadsheet to give more context as to why a user had specific AWS admin access (here's the one we did for Andrew when he joined cds-snc/site-reliability-engineering#462).
