### ISSUE TITLE
Create better understanding of how to format a spreadsheet.

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#404]
# Description

As a new or first-time Sender using templates with variables or doing bulk manual sending, I need to be able to create a good spreadsheet that matches my template so that I can have confidence about sending many emails. 

WHY are we building?
We learned through usability testing (2022/01) that participants easily created variables, but had trouble linking the variables/template to the spreadsheet.

WHAT are we building?
A map to identify the un/happy paths
Probably iterating on the designs without creating a new feature

VALUE created by our solution
Senders save time and feel capable because they understand how to format a spreadsheet earlier on in the process and they can prepare their spreadsheet once.

# Acceptance Criteria** (Definition of done) 
- [x] We identify what the un/happy paths are from gathering the information to sending a bulk email
- [ ] A design iteration in both English and French addresses the unhappy path
- [ ] Design review (with the team)
- [x] Content & interaction critique (incl. a11y)
- [x] The design iteration helps Senders comply with the Terms of Use items related to the spreadsheet
- [ ] Add story/hypothesis to Research Repo
- [x] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

Given a Sender wants to do a bulk send with variables, when they get to the part in the flow and upload a spreadsheet, they already have a good spreadsheet that matches their template and they don't have to re-do their spreadsheet or they're not surprised. 

[The guide section on variables was clear for some participants and many participants didn't have issues adding the parentheses to create a variable in the template. However, for participants who aren't as experienced in tech or spreadsheets, they wanted to find more information on formatting the spreadsheet and how the variables in the template relate to the spreadsheet.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recKhMerdcHixaXY2?blocks=hide)

[Without information about the spreadsheet on the guide, some initially misunderstood that the recipient information / variables would be input into Notify directly without uploading a spreadsheet. Assembling and formatting the data in a spreadsheet is an additional step that seemed unexpected initially](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recBBpp2E3BdXUEe1?blocks=hide)

[Didn't understand/catch that the name of the variable and the name of the spreadsheet column would need to match.
](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/reckf5VnPp8C04jUO?blocks=hide)

[One participant wondered if there was a limit to how many contacts the mailing list could include.
](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/rec2LB880BPaMGVUX?blocks=hide)

[The table explanation screen aided participants in understanding/confirming their understanding of how the variables apply to a spreadsheet. One participant who was expecting the mailing list to be input into Notify didn't find this page helpful.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/recaeKS1S9DlxH9fl?blocks=hide)

[Participants wondered about potential conflicts between their system and Notify for exporting contact info from their system and importing into GC Notify](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/reccM1dhJUGPgwPnH?blocks=hide)

[Seemed more familiar with Excel than CSV](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/rechjL7Zu95dUEeHU?blocks=hide)

[Participants were able to complete their tasks. For some participants, it wasn't a completely intuitive process, but they were able to complete it.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/rechtcFa7BOpqeP4u?blocks=hide)

[Unclear guidance on how to use “variables.” In the personalization guide, it would be helpful to connect the “variable” section back to the spreadsheet. Make that connection clearer.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/reclsqBrM3842zWMU?blocks=hide)

[Most participants understood they would click 'add recipients' as a next step. However, for participants who weren't clear on how GC Notify was different from their email client, they didn't expect to upload the recipients spreadsheet file when clicking the "Add recipients" button](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/recmzf3LXWYDZEqr4?blocks=hide)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/404?planning-poker) with ZenHub @amazingphilippe @adriannelee

**Comment by adriannelee** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/404?planning-poker) with ZenHub @YedidaZalik

**Comment by adriannelee** [comment]
Moving down in the product backlog to maybe work on in the next sprint (when Yedida is back)

**Comment by yaelberger-commits** [comment]
Back to content critique Tuesday, plan to wrap design up by end of this week for more team feedback next week.

**Comment by yaelberger-commits** [comment]
Yedida implemented feedback from Phil. Handing off to Phil and other members of the team

**Comment by yaelberger-commits** [comment]
To be brought back into Product Backlog once design, FR and annotations are done for dev implementation in a future sprint

**Comment by amazingphilippe** [comment]
Starting French content Today. 
Chat with Adrianne to narrow down better ideas.

**Comment by yaelberger-commits** [comment]
Need a design sync on this one

**Comment by yaelberger-commits** [comment]
Yedida implemented all feedback from Phil & Adrianne
