### ISSUE TITLE
Discovery- Senders have access to writing tools that match their technical abilities

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#406]
_Discovery - Senders have access to writing tools that match their technical abilities_

# Description

As a Sender, I need to have access to writing tools that match my technical abilities so that I can craft quality email messages for my audience. 

WHY are we building?
Some senders that are not familiar with markdown feel less confident when crafting email templates. Rich templates are a good way to craft structured email messages, and the recipients will ultimately benefit from this change. 

WHAT are we building?
- [ ] A comparative list of text editing patterns that could be used alongside markdown. Including for each:
  - [ ] An a11y overview
  - [ ] Technical difficulty to implement
  - [ ] Browser compatibility
  - [ ] Multilingual compatibilities
  - [ ] Extendable/customizable

VALUE created by our solution
When we are ready to tackle this challenge, we are equipped as the Notify team to design and implement a solution for this story. 

# Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

[Participants were able to complete their tasks. For some participants, it wasn't a completely intuitive process, but they were able to complete it.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/rechtcFa7BOpqeP4u?blocks=hide)

[Some participants expected to format text by using a toolbar or by selecting a word and seeing a styling menu (e.g. Word) For these participants, it wasn't good to learn something in order to complete the task. For them, where to find help wasn't obvious, but they successfully clicked the guide links because they didn't see many other options.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/recFD9ZeORJ2aWiIO?blocks=hide)

[Participants noted that Markdown isn't something they/their colleagues have knowledge about. However if they themselves had technical knowledge, they were happy to find markdown as the formatting language.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/recYHJitUFEoplqXJ?blocks=hide)

If this user story emerged from User Research insights:
- [x] Link research insight back to hypothesis from Epic or Objective in Airtable
- [x] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

**Comment by yaelberger-commits** [comment]
Would like this to be a more all-team effort

**Comment by yaelberger-commits** [comment]
Did you stuff similar library such as this?
https://simplemde.com/

**Comment by jimleroyer** [comment]
Potential library candidate (or something similar would be nice):

**Online demo**: https://simplemde.com/
**GitHub repository**: https://github.com/sparksuite/simplemde-markdown-editor

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/6afd558f-0935-4296-ac5f-da451d5b9e4d)

**Comment by jimleroyer** [comment]
Quill seems interesting for its [extension mechanism](https://quilljs.com/guides/building-a-custom-module/). There are [extensions to support markdown](https://cloverhearts.github.io/quilljs-markdown/), but we should make a listing and evaluate support.

**Comment by jimleroyer** [comment]
I was browsing Quill's [issues for markdown support](https://github.com/quilljs/quill/issues/3192) and there was mention of [TipTap](https://tiptap.dev/examples/markdown-shortcuts) (although direct markdown support does not seem possible) and [slate](https://www.slatejs.org/examples/richtext) ([preview here](https://www.slatejs.org/examples/markdown-preview)) which would support it. [CodeMirror](https://codemirror.net/mode/markdown/index.html) was mentioned too but not sure about that one.

**Comment by amazingphilippe** [comment]
We tested Lexical with several Fable participants. the testing wasn't perfect, and we need to test again. Perhaps with a more refined version, like GC Forms. @andrewleith has been doing some work in https://github.com/cds-snc/notification-admin/pull/1666

[Here are findings to keep in mind before we do another round of testing](https://cds-snc.dovetailapp.com/insights/5YbaE1tyFOrgyhkvUgzmZw)

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/406?planning-poker) with Zenhub @andrewleith @adriannelee
