### ISSUE TITLE
Guide on sending messages to users about incidents

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#415]
_Give your user story a simple, clear title_

# Description

Make a guide on how to send a messages about an incident to notify users (e.g. how to make a csv file, how to send out messages, where to store template etc)

https://docs.google.com/document/d/1n2cHlFenqw9r2H8K8v9Cwbm4vXXeK9I7OR6zC5yLqIo/edit?usp=sharing

As a (user), I need to be able to know about incidents so that I can plan my usage of notify.

WHY are we building?
A guide/ documentation about how to send an incident message 

WHAT are we building?
Step-by-step guide with screenshots and detailed

VALUE created by our solution
An easy guide for incident commanders to use (and also for onboarding)

# Acceptance Criteria** (Definition of done) 

- [x] @yaelberger-commits  reviewed
- [x] @sharlychan-cds  reviewed
- [x] Queries added by @sastels 
- [x] FR translation
- [x] FR content review from @amazingphilippe 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by sastels** [comment]
should include queries to find what users to send to.

**Comment by yaelberger-commits** [comment]
@sharlychan-cds Can you please also review? I will be reviewing today as well

**Comment by yaelberger-commits** [comment]
Sharly and Yael completed reviews. Yedida will send doc and templates for translation.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/415?planning-poker) with Zenhub @amazingphilippe @sastels @sharlychan-cds @YedidaZalik

**Comment by YedidaZalik** [comment]
Sent to translation, target return date October 3.

**Comment by YedidaZalik** [comment]
[FR version of guide](https://docs.google.com/document/d/1BwVJ74Nfw2OnoU56Ni9i6K01ehSv6LmHi0ppGkEk7qg/edit#heading=h.gjdgxs) returned last week with a number of issues identified. Communicated with translation team and resolved issues over course of week with help from @sharlychan-cds and @andrewleith 

Guide now ready for review by @amazingphilippe

**Comment by YedidaZalik** [comment]
@amazingphilippe made a few edits.

**Comment by amazingphilippe** [comment]
@sastels to review the part about creating queries. Ping Phil if any changes are made.

**Comment by yaelberger-commits** [comment]
@amazingphilippe Steve added 1 query, not sure if it requires translation etc.
