### ISSUE TITLE
Test page to UI when a session times out

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#417]
_Add page to UI when a session times out_

# Description

As a Notify client, I need to be able to see that my session has timed out, so that I can sign back in. 

*UX side of #727 which makes backend changes to lower session length from 20 hours to 8 hours

WHY are we building?
We're testing because we currently have a session timeout page but we're unsure if it's working correctly and users might not have confidence of why they are signed out, or know next steps to get signed back in. 

WHAT are we building?
We're testing a page in the unauthenticated space for session timeout

VALUE created by our solution
Users have better awareness when they've been signed out and know next steps to get signed back in

- [ ] Page can be in GC articles, but we need to do some backend work to detect when session timeout has occurred to present the page to users
- [ ] design content and page in both EN and FR (check design system for this, or Forms)
- [ ] translate content 
- [ ] Create new page in GC Articles for session timeout
- [ ] Create a URL for session timeout page
- [ ] Review of content in GC Articles as draft
- [ ] Publish pages in EN and FR on GC Articles
- [ ] Clear the cache of GC Articles to push to prod

# Acceptance Criteria** (Definition of done) 

Given it's been 8 hours since a client has signed into GC Notify, when 8 hours has expired, then they are presented with a session timeout page that lets them know their session has timed out and they will need to sign back in.
- [x] Page confirming you've timed out should appear automatically and be forced out when session times out **and** when you log out
- [x] Warning of duration of user activity at the start of a process (make users aware that a session is 8 hours long after being inactive for 8 hours upon log in)
- [ ] **OPTIONAL** warning in 15 minutes you'll be logged out
- [x] WCAG criteria https://www.w3.org/WAI/WCAG21/Understanding/timeouts.html

* A11y
* Bilingualism
* Security controls in place

**Comment by yaelberger-commits** [comment]
Needs to be brought to story refinement soon

**Comment by whabanks** [comment]
Current session timeout page:

![image.png](https://images.zenhubusercontent.com/6362cf580029e141b402bb65/11c5b277-7356-4ddf-8196-dcdcb958ffb1)

**Comment by yaelberger-commits** [comment]
While every cookie has an expiry, this is just the date when the browser should no longer send the cookie to the server. In most cases, this means that after this date the browser will delete the cookie, but it depends on the clean up algorithms in the browser.
If they get deleted, we have no idea they used to be signed in
(or even if it doesn't get sent also we don't know)

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/417?planning-poker) with Zenhub @andrewleith
