### ISSUE TITLE
(RESEARCH) Users should be required to accept terms of use upon login

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#419]
# Description

Users are not required to accept terms of use upon login, leaving CDS open to liability potentially.
Users have questions about how to properly use Notify and end up submitting a support ticket for answers.

**WHY are we building?**
This is a security risk if left unchecked and leaves CDS open to liability.
We're updating all of our Notify policy documentation to better align with current state and set expectations with users, and this is part of the suite 
Terms of Use acts as an information sharing agreement, so this enables organizations to use Notify without needing more authorities and paperwork

**WHAT are we building?**
Implement a system use notification either via banner or landing page upon account creation and require users to click to accept acknowledgement of terms. The notice provided should be supplied or approved by CDS’s legal counsel or other approved party.
Update content in our Terms of Use to better align with current state of Notify

**VALUE created by our solution**
User assumes some risk and understands how to properly use Notify safely and securely in line with our Authority to Operate, in tandem with the new Security and Privacy Statements and SLA

# Acceptance Criteria** (Definition of done) 

Given an individual employee is creating a new account in GC Notify, when they go through the steps, then they must read and acknowledge the Terms of Use before creating their account so they understand their individual responsibilities. 
- [x] Yedida to itemize content for terms of use v privacy statement v security statement, so that we can easily see where there's overlap. 
- [x] Journey mapping when a user encounters the Terms of Use and how they can get back to them
- [x] Speak with @mtoutloff about which terms need to be agreed to at account creation, trial service creation - before a service goes live.
- [x] Upon new account creation, a user is required to scroll through (and presumably read) and then select a button to acknowledge they have read and understand the Terms of Use
- [x] A new dialogue box for Terms of Use in create account flow with new button
- [x] Terms of Use is short summary, bullet points or structured with Headings in EN/FR
- [x] Terms of use that users agree to upon account creation (and/or when going live - dependent on discussion with Melissa) is the same document linked in Terms of use in footer
- [x] Last updated at the bottom with link to previous version
- [x] Send an email to all current users that we have updated our Terms of Use and other documentation, by continuing to use Notify you accept these new terms of use
- [x] Updated Privacy, Security have been published 
- [x] Publish SLA v1.5 (maybe SLO?)
- [x] Designs are translated
- [x] Add a reasonable amount of friction, including when using assistive tech
- [ ] Solution is tested with 3-5 real users in Staging or Figma (at least one in Fr)
- [x] Solution is tested with Fable participants
- [ ] Add to Security Statement about how the added friction adds to security
- [ ] Add a post to New Features about the changes 

## Research checklist
- [ ] tested with 6 EN participants (Yael)
- [ ] tested with 1 FR participant (Phil)
- [ ] Findings analyzed (Yael and Phil)
- [ ] Findings presented to the team (Yael)
- [ ] Findings added to the research repo (Yael)

Documentation and artifacts:
[Research folder for Usability Testing](https://drive.google.com/drive/folders/1K9bX4RFGGxZNy4MSuoN5YTG5XygDjw8v) 

Analysis https://docs.google.com/document/d/1x_AULftkVhmZ8D4uLKeU3Q9KS_HpGqo3HuMSMrkTukY/edit

**Comment by adriannelee** [comment]
Question: Upon sign in for current users and upon sign up for new users?

**Comment by YedidaZalik** [comment]
I'm attaching screenshots of the current process to create an account. I only see the terms of use referenced on screenshot 1, in a link at the end of the page. Would it be worthwhile if the terms were a pop-up? Perhaps we could design so that the user would have to scroll through the pop-up and mark their acceptance of the terms as a step in account creation.

![Screen Shot 1.png](https://ima![Screen Shot 2.png](https://ima![Screen Shot 3.png](https://ima![Screen Shot 4.png](https://images.zenhubusercontent.com/614b9f22b18cf806c628a310/be2db1c6-c659-42a2-a606-aac595aa594c)ges.zenhubusercontent.com/614b9f22b18cf806c628a310/74c21c83-aa87-4f4f-a474-f41eb62eb137)ges.zenhubusercontent.com/614b9f22b18cf806c628a310/cd4b284d-1036-4148-99bf-b9bf4c463348)ges.zenhubusercontent.com/614b9f22b18cf806c628a310/57a3eebd-52f7-4626-b2fc-6e04ef00aa6b)![Screen Shot 5.png](https://images.zenhubusercontent.com/614b9f22b18cf806c628a310/22d1f0b5-6dc9-4ae5-a989-38ead2df3f2d)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/419?planning-poker) with ZenHub @adriannelee @amazingphilippe @sharlychan-cds @YedidaZalik

**Comment by yaelberger-commits** [comment]
![Screen Shot 2022-07-14 at 11.00.05 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/d05f96b1-f10a-4ecf-865e-caa2c5a2eb50)

**Comment by YedidaZalik** [comment]
Suggestions from Content critique Aug 3,2022
Content critique
Intention for notify or across websites
Standardize

If part of flow, could we have a summary of what they agree to

Content model - basic - what are the parts of each of them - eg first part is who we are, 2nd agreeing, etc

Note stylistic differences- tone, terminology
Table not fancy, split up different chunks

Anik document

Janice - legality of summary

Consider settings as place to do this

Generator
Many use Canada.ca terms

Propose for MVP team 

If clear differences between jurisdictions

Follow laws of your own “Department and jurisdiction “

**Comment by amazingphilippe** [comment]
Accepting terms when going live is a very similar experience to what we're proposing here

![Capture d’écran 2022-08-17 à 10.47.46.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/d4e2948d-7a13-4977-9115-904466e27c1b)
![Capture d’écran 2022-08-17 à 10.47.58.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/1991210c-4a5e-4d44-b2c1-8b953e50bee8
)

**Comment by YedidaZalik** [comment]
First pass at [itemizing content in policy docs](https://docs.google.com/spreadsheets/d/1Xs4KlhNkB0Box28nsKU2heexnL1wvTSvcAI4o0bC2no/edit#gid=0). Next, I'll assess/consider other ways to organize this doc.
In meantime, attaching in case it's helpful for current thinking around policy docs (the "Notes" column) @yaelberger-commits @sharlychan-cds 
Pls feel free to edit/change info in this doc, and/or to complete "Compulsory" column if helpful to you
In this iteration, Privacy starts at row 5, Security at row 31, Terms of use row 61, SLA row 76

**Comment by YedidaZalik** [comment]
When we design this we could consider alternative to check box suggested by Adam Silver in this video: https://www.youtube.com/watch?v=nhbd6PxcnKc

**Comment by yaelberger-commits** [comment]
We'll bring this again to Story Refinement to decide details of the user flow and UI

**Comment by yaelberger-commits** [comment]
Title for Forms for every log in is "Know your responsibilities"

**Comment by yaelberger-commits** [comment]
3 places where Users will be forced to interact with ToU
1) Account Creation - full terms of use, users must scroll down, select button to agree
2) Every log in - point form headers of ToU, maybe a modal, users much select agree to leave the modal/page
3) (ALREADY EXISTS) At Request to Go-Live - point form step in the go-live process, no changes needed here

**Comment by jzbahrai** [comment]
@andrewleith to hand off to yedida and phil for content and design

**Comment by yaelberger-commits** [comment]
Feature was reviewed at Dev/Design review by the whole team
Decisions: 
- We'll go with a modal/dialogue 
- We need to have a way to confirm the terms were accepted (validation/confirmation) for a11y and screen readers, so a visual and non-visual cue
- We'll add the ToU as a page in our code so we can adapt it as needed for various steps

**Comment by andrewleith** [comment]
- adding UI tests this morning
- still need to add feature flags
- check to see if new content added
- next steps will be some usability testing + fable testing (@yaelberger-commits / @amazingphilippe )

**Comment by yaelberger-commits** [comment]
Working on setting up research activity with 3-5 users

**Comment by YedidaZalik** [comment]
FR is back with a note from MSB with some choices
FR is below the EN in this document https://docs.google.com/document/d/1Lg5GX8Fu8iPuVSDfMTKmMT2ICmh3cfjQFtAo0Q4sow8/edit

**Comment by YedidaZalik** [comment]
Updated/finalized docs with Yael's suggestion.  
Content ready to be implemented.

**Comment by andrewleith** [comment]
- @yaelberger-commits  drafted documents for research, awaiting comments from team this morning

**Comment by andrewleith** [comment]
- @andrewleith to merge to staging after release this morning

**Comment by amazingphilippe** [comment]
Élise is working on translations. Hoping to have those back soon. Next: send invites

**Comment by amazingphilippe** [comment]
Still one PR to merge in admin.

**Comment by yaelberger-commits** [comment]
translations are back. Sending recruitment emails today

**Comment by yaelberger-commits** [comment]
Invites sent to 8 people

**Comment by amazingphilippe** [comment]
Waiting for responses

**Comment by amazingphilippe** [comment]
@andrewleith implementing the translations today

**Comment by amazingphilippe** [comment]
Merged a PR with a11y and design tweaks.

**Comment by amazingphilippe** [comment]
PR with translations merged last Friday. I found a few missing pieces and will do a PR to fix those. Also noticed some relative and absolute urls in the content. I will review those too. 

Found a few missing pieces on the sign-up form:
<img width="1028" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFN2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74df83e1d6ebda471f84450b0bef78d32b919a22/Capture%20d%E2%80%99e%CC%81cran%2C%20le%202024-07-03%20a%CC%80%2008.55.17.png" alt="Capture d’écran, le 2024-07-03 à 08.55.17.png" />

<img width="830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFd2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ecb9d70a1d5f1a76284179c1872888c5fdc04dd/Capture%20d%E2%80%99e%CC%81cran%2C%20le%202024-07-03%20a%CC%80%2008.54.16.png" alt="Capture d’écran, le 2024-07-03 à 08.54.16.png" />

<img width="408" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGF2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4088be01904ecd6fd6600c8a260631de7745956c/Capture%20d%E2%80%99e%CC%81cran%2C%20le%202024-07-03%20a%CC%80%2008.54.11.png" alt="Capture d’écran, le 2024-07-03 à 08.54.11.png" />

<img width="810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGV2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7c3b4bf52055ca6b8674d0e5f8a7414a4623f54/Capture%20d%E2%80%99e%CC%81cran%2C%20le%202024-07-03%20a%CC%80%2008.54.56.png" alt="Capture d’écran, le 2024-07-03 à 08.54.56.png" />

**Comment by mtoutloff** [comment]
Updated the Research Plan to include privacy section

**Comment by amazingphilippe** [comment]
Yael will send another batch of invites to find some participants.

**Comment by yaelberger-commits** [comment]
A bit blocked at the moment because I don't have Phil's FR calendly link. Will see if I can find it today and send the second batch

**Comment by yaelberger-commits** [comment]
Sent to remaining [invitees](https://docs.google.com/spreadsheets/d/1zl9MPV_kp8Ld3Lz3iFnktXzYcKxxcXz2_CRz62X7nRU/edit?gid=24122710#gid=24122710) today (27 in total)

**Comment by whabanks** [comment]
Phil to send some follow up emails with his Service Canada email

**Comment by yaelberger-commits** [comment]
We have 10 participants signed up for sessions. 
Next steps:
- schedule sessions with notetakers and facilitator
- Create a notetaking document
- Create a spreadsheet with Participant # (no PII) and dates/times/notetaker/facilitator

**Comment by whabanks** [comment]
Completed two sessions so far.

**Comment by yaelberger-commits** [comment]
4 sessions completed so far in EN, 1 in FR

**Comment by whabanks** [comment]
2 more sessions today. More FR recruitment to occur.

**Comment by whabanks** [comment]
Final session today - will end the sessions after today.
