### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#42]
# Key results

- Users can self-serve their own branding configuration and logo uploads.
- Consistent and bug-free experience for branding across Notify.
- The email preview displays **better** the end results for the email.
- Decide if we keep or not the brand text feature which is meant as an accompanying text beside logos. [See the CDS logo usage](https://notification.canada.ca/email-branding/b0ed4a58-fccc-4569-81c7-9211dc5216b3/edit) for a proper usage of this feature.
- Evaluate if we want to push forward organizations. At the current time, there is one branding per organization even though these are not associated with organizations. CDS never pushed for usage of organizations and it might affect us harder the longer we wait.

# Potential tasks

- Self-service to add and modify a branding configuration.
- Self-service to resize and upload image of logo.
- Add an accessibility text field for the logo image because this might be different from the brand name.
- Remove restrictions on image dimensions to let users manage their own look and feel.
- Allow reuse of brandings across multiple services.
- Fix the preview for email where the branding does not appear correctly.
- Fix the branding logo not appearing in certain screens.
- Fix the branding logo not displayed for email sent from the staging environment.

[Discussion notes](https://docs.google.com/document/d/1YXKbXkJpxKmmeoXiVYybSd3p-fjinYQnUIbB1CyjhGY/edit#heading=h.xymon4ybgxwu) from meeting with Forms team

**Comment by yaelberger-commits** [comment]
it would be cool to let users download image templates to aid them in getting the formatting right for custom logo

**Comment by yaelberger-commits** [comment]
[Discussion notes](https://docs.google.com/document/d/1YXKbXkJpxKmmeoXiVYybSd3p-fjinYQnUIbB1CyjhGY/edit#heading=h.xymon4ybgxwu) from meeting with Forms team
