### ISSUE TITLE
Add valid endpoints to WAF rules (Admin)

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#420]
_Add valid endpoints to WAF rules (API)_

# Description

As a developer on Notify, I need to be able add valid endpoints to WAF rules so that I can block any attacks on Notify endpoints. 

WHY are we building?
Harden the other components on Notify (API & admin) .. AKA putting up wood planks on the doors

WHAT are we building?

VALUE created by our solution
Prevent _some_ endpoints from being exposed

# Acceptance Criteria

- [x] Monitor WAF rules in production and ensure legitimate traffic isn't blocked

**Comment by yaelberger-commits** [comment]
GC Articles relies on wildcard paths, so we need to be able to check wildcard paths before sending an error message that it doesn't exist. Admin is a bigger piece. Talk to @mohamed-cds @patheard and @timarney

**Comment by yaelberger-commits** [comment]
@jimleroyer Should we try to tackle this WAF piece along with the other one? I looks a bit more complex given the impact from GC Articles.

**Comment by jzbahrai** [comment]
https://github.com/cds-snc/notification-terraform/pull/512

**Comment by jimleroyer** [comment]
@yaelberger-commits Yes it's more complex. @sastels suggested that we might add the list of valid endpoints for now in the code of admin. So we wouldn't implement anything in GCArticles yet... but that would require a code changes for new pages in GCArticles, hence a required dev intervention but increased security. We can discuss about this next week.

**Comment by jimleroyer** [comment]
Currently in count mode for monitoring until Sept 15th (1 week monitoring period).

**Comment by jimleroyer** [comment]
Block mode is deployed in staging. We will test today if that works as expected and following successful results, deploy tomorrow in production.

**Comment by jimleroyer** [comment]
This was deployed in production yesterday. We will monitor for a week before considering it to done.

**Comment by YedidaZalik** [comment]
@jimleroyer to do final monitoring today

**Comment by jimleroyer** [comment]
Monitored accessed URIs that were blocked and all inspected were invalid, so it's working good.
