### ISSUE TITLE
Complete automation of recent release pipeline changes

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#429]
# Description

As an ops lead, 
I need to release Notify with as few clicks as possible 
and with as much automation possible
so that I can achieve easily release Notify with as few mistakes as possible.

## WHY are we building?

Recently, a change to our release process aligned releases of environment variable changes with coding changes. Previous to this, these two were not coupled and ran the risk of getting misaligned configuration changes with code changes. That was a good change. 

This made a series of repercussions on our release pipeline though where we need to tweak our release with manual steps. This is getting too manual and we lost value in our capacity to release.

## WHAT are we building?

* Refine our release process. It should be more centered around [the `VERSION` file in the manifests repository](https://github.com/cds-snc/notification-manifests/blob/main/VERSION).
* Update the notification-pr-bot to automate the current manual tasks.

## VALUE created by our solution

Automation and risk mitigation.

# Acceptance Criteria** (Definition of done) 

Given we want to release Notify, when a developer clicks the "release button", then Notify is released.

- [ ] Only one pull request is necessary to release the various Notify components of Notify (minus Kubernetes and Terraform infrastructure).
- [ ] The pull request got the changes about to be deployed.

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/429?planning-poker) with ZenHub @patheard @mohamed-cds @jzbahrai

**Comment by yaelberger-commits** [comment]
Initial build, testing thoroughly today

**Comment by mohamed-cds** [comment]
Proposed solution up for review. Updating the [notify release management document](https://docs.google.com/document/d/17kVWBN4OK_mSgTK7h_dTyC1kpjcY_UhXOn1FpolH-GM) to reflect this new release process.

**Comment by mohamed-cds** [comment]
new workflow in-places. Testing with the next prod deployment.

**Comment by patheard** [comment]
🤞🏻

**Comment by mohamed-cds** [comment]
Need one more release to confirm this is working as expected
