### ISSUE TITLE
Prepare to test with people with disabilities (Fable)

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#431]
We're aiming for the sessions to happen between Mar 21 -25. We would like to implement fixes to issues that the external auditor found before theses sessions if possible.

[Research plan](https://docs.google.com/document/d/1L_RcWhRhdwcr2wDvcY1PtSHIwM9CSzbH_sZ_6n2z7VQ/edit#)

- [x] Sync with Fable/Mario on screener criteria and study limitations
- [x] Complete drafting [facilitation guide](https://docs.google.com/document/d/1a5MJppfqrcEoHZDhsK7JGiYbRpmg_1Lp9JwqB-22vVU/edit#) / unmoderated testing tasks
- [x] Figure out a way to let non-gov people to participate in test
- [x] Prepare privacy statement
- [x] Translate guide
- [x] Create note taker templates

**Comment by yaelberger-commits** [comment]
Moved into Product backlog to be tackled next sprint

**Comment by adriannelee** [comment]
I had to do this last week 😅

**Comment by adriannelee** [comment]
Moving to Blocked, as it's in translation right now and the docs have been sent to Fable.
