### ISSUE TITLE
Test core tasks with people with disabilities (Fable)

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#432]
Fable is updating the spreadsheet here with the schedule: https://docs.google.com/spreadsheets/d/1WTYNh9X-Gyxoap4YS_rGv6vD6m0acqFV/edit#gid=1282479540

- [x] Recruit participants
- [x] Schedule participants, facilitators, notetakers
- [x] Conduct sessions
- [x] Clean up notes

**Comment by yaelberger-commits** [comment]
Moved into Product Backlog to be tackled next sprint

**Comment by adriannelee** [comment]
Sessions are booked and notetakers and observers were invited to the sessions today.

**Comment by yaelberger-commits** [comment]
3 EN sessions today

**Comment by yaelberger-commits** [comment]
Adrianne to sync with whoever wants to help clean up notes and add to research repo
