### ISSUE TITLE
Analyze testing with people with disabilities (Fable)

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#435]
- [x] Analyze notes / update Airtable
- [x] Present findings to team

**Comment by yaelberger-commits** [comment]
Bumped up to high priority through discussion between Yael and Josh because analyzing the findings and actioning them is what will create value from the testing. Moved to product backlog to be tackled sprint starting March 28

**Comment by sharlychan-cds** [comment]
we should make a calendar reminder or card to capture everything we need and then delete full transcripts/ recordings after 30 days

**Comment by adriannelee** [comment]
@sharlychan-cds I added this card https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/526
