### ISSUE TITLE
Bug: weighted DNS record for Lambda API returns wrong SSL certificate

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#437]
**Describe the bug**
As part of the switch to using the Lambda API, we created weighted DNS records that would send 95% of `api.notification.canada.ca` requests to the Kubernetes API pod and 5% of requests to the Lambda API.

What we've noticed is occasionally requests that are routed to the Lambda API have the wrong SSL certificate returned.  Instead of getting the main `*.notification.canada.ca` certificate, the API Gateway's execution URL certificate is returned and an `ERR_TLS_CERT_ALTNAME_INVALID` is thrown since the API Gateway SSL cert does not include a "Subject Alternative Name" for `api.notification.canada.ca`.

Below is a correct response:

```bash
❯ openssl s_client -connect api.notification.canada.ca:443 </dev/null 2>/dev/null | \
    openssl x509 -inform pem -text | grep -A1 "Subject Alternative Name"

            X509v3 Subject Alternative Name: 
                DNS:notification.canada.ca, DNS:*.document.notification.canada.ca, DNS:*.notification.canada.ca
```

And this is an incorrect response:

```bash
❯ openssl s_client -connect api.notification.canada.ca:443 </dev/null 2>/dev/null | \
    openssl x509 -inform pem -text | grep -A1 "Subject Alternative Name"

            X509v3 Subject Alternative Name: 
                DNS:*.execute-api.ca-central-1.amazonaws.com
```

**To Reproduce**
No clear ability to reproduce.

**Expected behavior**
The `*.notification.canada.ca` SSL certificate will always be returned.

**Additional context**
Two AWS support cases were opened in the `Notification-Production` account with neither providing a clear explanation of the error:

1. [API Gateway: 9710198151](https://console.aws.amazon.com/support/home?region=ca-central-1#/case/?displayId=9710198151&language=en)
1. [Certificate Manager: 9710133981](https://console.aws.amazon.com/support/home?region=ca-central-1#/case/?displayId=9710133981&language=en)

The support tech suggested opening a third support case against Route53, which will be done as part of the investigation in Staging.

**Comment by adriannelee** [comment]
Mo and Pat working on this today

**Comment by patheard** [comment]
After discussion in [`SRE Tools` support case 9715324171](https://console.aws.amazon.com/support/home#/case/?displayId=9715324171&language=en), it was discovered that API Gateway custom domain names must use an [`ALIAS` type record](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-api-gateway.html).

This change has been made in Staging and appears to be working correctly.

Next is to make the same change to production and then ramp the Lambda API back up to handling 5% of the traffic.

**Comment by patheard** [comment]
More info from the impacted user.  Their error was generated by a NodeJS 14.x Lambda function running the following code:

```js
function emailCode(userName, email, code) {
  return new Promise((resolve, reject) => {
    if (!email) {
      reject(new Error('No email address in request.'));
      return;
    }
    httpRequest.post({
      url: gcNotifyEmailUrl,
      json: true,
      body: {
        email_address: email,
        template_id: emailTemplateId,
        personalisation: {
          email_userName: userName || '',
          email_code: code,
        },
      },
      headers: {
        Authorization: gcNotifyApiKey,
      },
    }, (err, response) => {
      if (err) {
        console.error(err);
        reject(new Error('failed to send email with verification code'));
      } else if (response && response.statusCode !== 201) {
        console.error(response);
        reject(new Error('failed to send email with verification code'));
      } else {
        console.log('email successfully sent');
        resolve(response);
      }
    });
  });
}
```

I'll create a similar test scenario in Staging to see if I can recreate the error now that we've switched the weighted DNS records to ALIAS.

**Comment by patheard** [comment]
Created the following test Lambda function and could not replicate the error:
```js
const https = require("https");

const doPostRequest = () => {

  const apiKey = process.env.API_KEY;
  const domain = process.env.DOMAIN;
  const email = process.env.EMAIL;
  const templateId = process.env.TEMPLATE_ID;

  const data = {
    "email_address": `${email}`,
    "template_id":`${templateId}`,
  };

  return new Promise((resolve, reject) => {
    const options = {
      host: `${domain}`,
      path: "/v2/notifications/email",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `ApiKey-v1 ${apiKey}`
      }
    };

    //create the request object with the callback with the result
    const req = https.request(options, (res) => {
      resolve(JSON.stringify(res.statusCode));
    });

    // handle the possible errors
    req.on("error", (e) => {
      reject(e.message);
    });
    
    //do the request
    req.write(JSON.stringify(data));

    //finish the request
    req.end();
  });
};


exports.handler = async (event) => {
  await doPostRequest()
    .then(result => console.log(`Result: ${result}`))
    .catch(err => console.error(`Error doing the request for the event: ${JSON.stringify(event)} => ${err}`));
};
```
