### ISSUE TITLE
Zendesk pilot

### ISSUE THREAD

**Issue by mohamed-cds** [cds-snc/notification-planning#439]
_Integrate Zendesk into Notify's support portal_

# Description

As a support agent, I need to be able to receive support tickets in Zendesk so that i can compare functionality against Freshdesk. 

There is the possibility that Freshdesk will be sunset, so we'll need an alternative so that Notify can continue to receive requests from users.

The Notify API will be updated so that all support tickets will be sent to both Zendesk and Freshdesk. The main purpose is to be able to compare features.

# **Acceptance Criteria** (Definition of done) 

- [ ] All data received from users through the Notify contact us form should be available in both Zendesk
- [ ] New tickets assigned to the Notify group.
- [x] New tickets create slack messages and email notifications
- [ ] Replies to the the slack message should be available in Zendesk as a internal/private message

**Comment by yaelberger-commits** [comment]
@mohamed-cds will you be continuing the work on this pilot this sprint?

**Comment by mohamed-cds** [comment]
This is now mirroring successfully in production. Bulk of the work will be on @ramya-cds side to compare the features between zendesk & freshdesk.

**Comment by yaelberger-commits** [comment]
@mohamed-cds do we still need to track this task on the Notify-planning board? Or are you tracking those one with SRE/Support?

**Comment by yaelberger-commits** [comment]
@ramya-cds @mohamed-cds Can we close this now that a decision has been made re: Zendesk and Freshdesk?

**Comment by mohamed-cds** [comment]
@yaelberger-commits absolutely. 

Reference: https://gcdigital.slack.com/files/T2G2S06PM/F03EZH2GBC3
