### ISSUE TITLE
Can't send notifications when service in trial

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#443]
# Describe the bug

Onboarding users cannot send notifications through the API when their service is in trial mode and making a CSV bulk upload through the UI or using the API (using a team key).

Reported by Jimmy as:

> We might have a bug with notifications not getting created and sent for services in trial mode using a team API key. We have **three** onboarding users to the API who noticed it in the same day [here](https://cds-snc.freshdesk.com/a/tickets/8971) and [there](https://cds-snc.freshdesk.com/a/tickets/8977) and [here](https://cds-snc.freshdesk.com/a/tickets/8981). This might be medium/high priority because it prevents potential new users to test the API and onboard properly. This is also against our own documentation of how Notify works. For now, I recommend to these users to turn their service live as it works once it is, as I can't see how they can go through without a fix and testing the API.

# To Reproduce

1. Create a new service or reuse one and keep it in trial mode.
2. Create a team key.
3. Send a notification through the API to someone in your safe list or team.

1. Create a new service or reuse one and keep it in trial mode.
2. Make a CSV bulk upload through the UI.

# Expected behavior

The notification(s) should have been sent but it seems the API request or the CSV bulk upload were successful and marking these as success, when no notifications are actually sent or recorded in the database.

# Impact

Onboarding users trying out Notify for the first time in production, seeing Notify not working. We got three users in the same day affected when we discovered this bug so far.

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/443?planning-poker) with ZenHub @jzbahrai @sastels

**Comment by jimleroyer** [comment]
The bug is more serious than we thought, it might affect the CSV bulk upload through the UI as well. I updated the card on jump on this tomorrow to help bring a fix. At this point it should be higher priority IMO.

**Comment by yaelberger-commits** [comment]
High severity, affecting new users in trial mode

**Comment by yaelberger-commits** [comment]
Won't work if user logged into the UI within the past hour

**Comment by yaelberger-commits** [comment]
Jumana continuing to test, hoping to get PR merged and continue testing
