### ISSUE TITLE
Put the research privacy statement online

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#453]
For research participants, it may be difficult for them to access a Google/Word doc to read about their privacy rights before participating in a research session.

Providing the privacy information on a website will provide the research participant easier-to-access information, especially if they're signing up for a session on a vendor's website (e.g. Fable). 

Example: https://articles.alpha.canada.ca/forms-formulaires/privacy-statement/

Privacy statement English draft: https://docs.google.com/document/d/1_QjO1uM_YEFBDKHJgycIY8q5hYgBjclhc6PbMCXbiDI/edit

Privacy statement French draft - https://docs.google.com/document/d/1DPqTq_WzdK1Xh3p6-C2TdioyHlMiEzhfoYoNFh1TBqc/edit#heading=h.gjdgxs

## Acceptance criteria

- [x] Is online
- [x] Is available in both EN and FR
- [x] Is accessible
- [x] Is compliant with CDS user research privacy policies
- [x] Send ENG FR Research Privacy Statement to TBS ATIP
- [x] Is reviewed by ATIP

**Comment by yaelberger-commits** [comment]
Options for platform to publish privacy statement
GC Articles (pros, can route to Notify URL)
Github
CDS website

**Comment by adriannelee** [comment]
- Finalized and sent to translations
- I requested an account to GC Articles so we can start with the English version.

**Comment by jzbahrai** [comment]
Waiting for translations to come back but the english one is live!

**Comment by yaelberger-commits** [comment]
Skip to main content link is not translated on FR page

**Comment by adriannelee** [comment]
@yaelberger-commits @sharlychan-cds Should we move this to done since we're likely not going to hear back from ATIP soon? Or does it go to Blocked?
