### ISSUE TITLE
Lambda API and Kubernetes API configuration is not in sync

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#458]
## Describe the bug 

The Lambda API and Kubernetes API pods have slightly different configuration.  This was discovered after deploying cds-snc/notification-api#1501 to Production.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-2/SEV-3: more investigation required to determine exact impact. 

## To Reproduce

`n/a` - the configuration mismatch is a result of the `.env` file differing from the Terraform Lambda configuraiton.

To view the config in CloudWatch log insights:

```sh
# Kubernetes
fields @timestamp, @message
| filter @message like /Notify config/
| filter kubernetes.container_name like /api/
| sort @timestamp desc
| limit 20

# Lambda API
fields @timestamp, @message
| filter @message like /Notify config/
| sort @timestamp desc
| limit 20
```

## Expected behavior

The Lambda API and Kubernetes API pods should have the same configuration.

## Impact

Users may have different API behaviour depending on if their request is served by the Lambda API or k8s API pods.

If applicable

Impact on Notify users:
Users may experience differing behaviour depending on how their API request is handled.

Impact on Notify team: 
API behaviour will be different depending on how the API request is handled, which will make troubleshooting more difficult.

## Additional context

The following configuration items differ:
```diff
$ diff api-lambda-config-prod.json api-pod-config-prod.json 
3c3
<     "ADMIN_BASE_URL": "http://localhost:6012",
---
>     "ADMIN_BASE_URL": "https://notification.canada.ca",
7c7,8
<         "ALLOW_HTML_SERVICE_IDS": ""
---
>         "ALLOW_HTML_SERVICE_IDS": [
>         "<sensitive>",
>         "<sensitive>"
>         ]
10c11
<     "API_HOST_NAME": "None",
---
>     "API_HOST_NAME": "http://api.notification-canada-ca.svc.cluster.local:6011",
17c18
<     "AWS_ROUTE53_ZONE": "<sensitive>",
---
>     "AWS_ROUTE53_ZONE": "<sensitive>",
21,22c22,23
<     "AWS_US_TOLL_FREE_NUMBER": "None",
<     "BATCH_INSERTION_CHUNK_SIZE": 500,
---
>     "AWS_US_TOLL_FREE_NUMBER": "<sensitive>",
>     "BATCH_INSERTION_CHUNK_SIZE": 10,
206c207
<     "CLOUDWATCH_AGENT_ENDPOINT": "tcp://None:25888",
---
>     "CLOUDWATCH_AGENT_ENDPOINT": "tcp://ip-<sensitive>.ca-central-1.compute.internal:25888",
218c219
<     "DOCUMENT_DOWNLOAD_API_HOST": "https://api.document.notification.canada.ca",
---
>     "DOCUMENT_DOWNLOAD_API_HOST": "http://document-download-api.notification-canada-ca.svc.cluster.local:7000",
235,236c236,237
<     "FRESH_DESK_API_URL": "None",
<     "FRESH_DESK_PRODUCT_ID": "None",
---
>     "FRESH_DESK_API_URL": "<sensitive>",
>     "FRESH_DESK_PRODUCT_ID": "<sensitive>",
238,239c239,240
<     "HC_EN_SERVICE_ID": "",
<     "HC_FR_SERVICE_ID": "",
---
>     "HC_EN_SERVICE_ID": "<sensitive>",
>     "HC_FR_SERVICE_ID": "<sensitive>",
299,300c300,301
<     "STATSD_ENABLED": false,
<     "STATSD_HOST": "None",
---
>     "STATSD_ENABLED": true,
>     "STATSD_HOST": "ip-<sensitive>.ca-central-1.compute.internal",
311c312
<     "ZENDESK_API_URL": "None",
---
>     "ZENDESK_API_URL": "<sensitive>",
313c314
<     "ZENDESK_SELL_API_URL": "None"
---
>     "ZENDESK_SELL_API_URL": "<sensitive>"
```

**Comment by patheard** [comment]
The following commands can be used to compare the environment variables:
```sh
# k8s
kubectl get deployment api \
    -n notification-canada-ca \
    -o jsonpath='{.spec.template.spec.containers[?(@.name == "api")].env}' \
        | jq -r '.[].name' \
        | uniq | sort

# Lambda
aws lambda get-function-configuration --function-name api \
    | jq -r '.Environment.Variables | keys[]' \
    | uniq | sort
```

**Comment by patheard** [comment]
A potential fix to keep things in sync would be to use the AWL cli to update the Lambda's env vars with the encrypted env vars each time the manifests were deployed to prod.  It would be something like so:
```sh
aws lambda update-function-configuration \
   --function-name api-lambda \
   --environment Variables="{VAR1=value,VAR2=value}"
```

There are a few gotchas with this approach though:

1. It would mean the Terraform is not standalone and can't be used to build a working environment from scratch.  There would be an external dependency on the encrypted env vars in the `notification-manifests` repo, which is not ideal.

2. Not all the k8s and Lambda API env var values are identical.  There are some that are specific to each environment, so we'd need a list of which env vars should be synced and which need to be hard-coded per environment.

3. We'd need to be cautious about secrets echoing to the GitHub workflow logs in case of errors with the `aws lambda update-function-configuration` operation.

5. We're not planning on keeping this dual configuration state for a long time.  Once the Lambda API is shown to be stable through traffic ramp-up (#438), my understanding is that we'll ditch the k8s API pods.  This brings up two considerations:
   1. We shouldn't invest a tonne of effort in a solution to keep env vars in sync since it'll be short lived.
   2. We need to find a way to have a single source of truth for env vars since there is overlap between what the Lambda API needs and what the other k8s pods need.  Ideally we won't be duplicating env var configuration across two repos.

**Comment by mohamed-cds** [comment]
The manifest repo is now syncing it's secrets to the lambda accessible secretsmanager. cds-snc/notification-terraform/pull/418 refactors the lambda environment variable configuration to now use the environment variables from the manifest repo as a base and to override anything that requires a different value.

**Comment by mohamed-cds** [comment]
Secretsmanager wasn't able to accomodate the size of the environment variable file, so we've migrated to parameter store. This solution will be compared against other options and documented in a ADR.

Staging is stable and contains all the expected lambda environment variables that were originally missing when the sync issue was first detected.

**Comment by patheard** [comment]
The fix has been deployed to prod by cds-snc/notification-terraform#430 and validated.  Lambda API and k8s environment variables are now in sync.
