### ISSUE TITLE
Fixing Organization names in Notify Admin

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#461]
_Give your user story a simple, clear title_

## Description

When we make a service go live, there’s no conventional naming code for organizations and it is confusing to look through. It leads to problems like this: IRCC data is categorized under both CIC and IRCC (IRCC used to be known as Citizenship and Immigration Canada (CIC).

List on canada.ca 
https://www.canada.ca/en/government/dept.html

This is related to [Create federal, provincial, and municipal organization types#995](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/995).

## WHY are we building?
If we don't fix the organization names on the Notify Admin panel, the problems permeate into inaccurate reporting and our support ticket response. If we fix this, the Notify Service Reporting Sheet will have correct data and categories.

## WHAT are we building?
Use a consistent naming convention that is bilingual (e.g: ENG acronym - FR acronym= ESDC - EDSC) and change existing organizations on the Notify Admin panel. (Notify CRM is using this format already)

## VALUE created by our solution
As a Notify team member, I need to have standardize organization names to have consistent data on the Notify Admin panel. Solving this problem will allow us to have: 
- accurate metrics to report to upper management and the Minister's office and for growth. names so we can collect data better
- resolve support ticket requests quickly (e.g. is a recipient asks whether an email is legitimate, we can easily find the organization name to help verify this)
## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

If this user story emerged from User Research insights:
- [x] Dropdown list of organizations
- [x] Ability to request an organization be added to the list if it's not on the list
- [x] Use the CRM naming convention (ask Leanne for existing list) it should be based off of [this](https://www.canada.ca/en/government/dept.html) 
- [x] Do some research whether changing the name of an Organization on the Notify Admin backend will cause any dev problems
- [x] Do some research whether moving existing services into another organization will have a problem (e.g. moving IRCC services into CIC)
- [x] Figure out how to delete organizations that have 0 services under them (you can't do this in the Notify Admin Panel, you probably have to do this in the backend) - These have been archived rather than deleted so we don't create db errors 
- [x] Go into Notify Admin and start to change these department names and move services around
- [x] Create excel sheet of department with the new names (taken from CRM) - documentation [here](https://github.com/cds-snc/notification-attic/tree/main/data-analysis/update-organisation-names)
- [x] Create guide/ documentation on this process and any relevant information - documentation [here](https://github.com/cds-snc/notification-attic/tree/main/data-analysis/update-organisation-names)
- [x] explained changes to Ramya and Jimmy

**Comment by sharlychan-cds** [comment]
CRM is now a thing, we can proceed to chatting with them

**Comment by yaelberger-commits** [comment]
Connor and Strategic Engagement team have created their authoritative list for departments/crown corps. Notify will continue to collect organization (more granular) as an optional field

**Comment by smcmurtry** [comment]
We have decided on the format: 
> English name / French name
for example:
> Treasury Board of Canada Secretariat / Secrétariat du Conseil du Trésor du Canada

Next step is to write some SQL to make the updates and have it reviewed by the team.

**Comment by smcmurtry** [comment]
The organisations have been renamed, services have been moved out of duplicate organisations, and unneeded organisations have been archived.

**Comment by yaelberger-commits** [comment]
Someone to go in prod and look to see if the org names look right

**Comment by jzbahrai** [comment]
@smcmurtry this has been tested from my side. But there are still a bunch of tasks left on this ticket, can we clean that up as well?

**Comment by smcmurtry** [comment]
@jzbahrai sounds good, I have edited and checked off the remaining tasks

**Comment by yaelberger-commits** [comment]
I completed my QA in prod. LGTM
