### ISSUE TITLE
Allow users to update branding

### ISSUE THREAD

**Issue by josh-cds** [cds-snc/notification-planning#463]
For discussion: 

Consider allowing users to update branding as a self-serve feature. Currently, the support team does this for a client. 

## Context

https://gds.blog.gov.uk/2023/01/23/how-we-let-gov-uk-notify-users-set-their-own-branding/

Forms solution for branding 

## Related Research
- [When creating a service participants expected to create a custom logo](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/rec7VaBocpNZdPFac?blocks=hide)

**Comment by yaelberger-commits** [comment]
Duplicate card
