### ISSUE TITLE
Recurring Task: Researching UK Notify on a quarterly bases

### ISSUE THREAD

**Issue by josh-cds** [cds-snc/notification-planning#466]
## What

As a user, we should look at the work UK Notify has done on their product and see if we want to implement and action on it for GC Notify

## Acceptance Criteria

- [x] Read the release notes for ideas around product development

**Comment by smcmurtry** [comment]
Here is a good candidate for a feature we would benefit from: 
> Improved email branding
> When a service team needs to update their email branding, they can now:
> choose new branding from a set of existing options
> preview their branding on the Notify website

-https://www.notifications.service.gov.uk/features/roadmap#things-we-have-done
