### ISSUE TITLE
Mark required fields.

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#477]
# Fields

Visibility: 3
Evaluation: Does not support
Success Criteria: 3.3.2: Labels or Instructions
Needs design: 

### Description
There is a mixture of using the [required](about:blank), [aria-required](https://www.w3.org/TR/wai-aria-1.1/#aria-required) or no attribute, across inputs in the system. All required fields must specify the [required](about:blank) attribute; (in which case aria-required is not necessary). Conversely, if an input is not required, it should not contain the required attribute. For example, the search field on the Templates page has a required attribute that isn’t necessary.

![]()

**Comment by amazingphilippe** [comment]
Held up by https://github.com/cds-snc/notification-admin/pull/1242

Once that one is merged, we can go in app/templates/views/templates/choose.html and pass the `required=false` attribute to `live_search`

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/477?planning-poker) with ZenHub @amazingphilippe @jimleroyer @sastels

**Comment by amazingphilippe** [comment]
Went through all fields in the UI and added the aria-required=false attribute where needed. Working on some tests

**Comment by adriannelee** [comment]
Reviewed one tiny thing for a11y! (@andrewleith  had reviewed most of it already ✨)
