### ISSUE TITLE
(File Upload) Multiple Labels.

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#485]
# File Upload, Fields

Visibility: 2
Evaluation: Does not support
Success Criteria: 3.3.2: Labels or Instructions
Needs design: 

### Description
For file upload inputs, there appear to be three <label> elements associated with the input. This may cause confusion for an AT and may result in the label not being reported correctly. There should only be one <label> element used.

![](https://dl.airtable.com/.attachments/331cc16b591fe7ab0e1c67d00d2e5cfe/394d6441/Capturedecranle2022-03-15a13_51_25.png)

**Comment by amazingphilippe** [comment]
- There is an invisible element called "Add recipients" that can be read by a screen reader, just before "Re-upload your file"'
- This element has multiple label elements
- "Re-upload your file" is read twice, once as a button and another time as a text element
- It also seems that the visible button and actual button don't match. One says "Add recipients", while the button shows "Re-upload your file"

**Comment by amazingphilippe** [comment]
And from testing with users: 

https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recPXcsH6t8av9B0M?blocks=hide

> The 'Choose a file' button wasn't recognized as a clickable element (cursor didn't change, it wasn't announced by a screen reader, hover effect was too subtle). Participants using a screen reader were expecting somewhere to upload a file, but they had difficulty finding where to do so. One participant dictation to navigate also couldn't select the button easily.
