### ISSUE TITLE
Tabs do not behave as expected.

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#486]
# Tabs

Visibility: 2
Evaluation: Partially Supports
Success Criteria: 2.4.3: Focus Order
Needs design: 

### Description
In a tab interface, the user should press the “tab” key to move focus to the currently open tab. The arrow keys are used to navigate between tabs. In the current implementation, such as those on the Messages Sent and Templates pages, each tab is in the tab order and are not navigable with the arrow keys.

<https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html>

In addition, some of the tabs behave as links rather than tabs resulting in focus being unexpectedly redirected to the top of the page (see related issue under 3.2.1 on input).

![](https://dl.airtable.com/.attachments/841d99ef127cf3808010b9e1bc23661f/47ba0eaa/Capturedecranle2022-03-15a13_31_39.png)

**Comment by amazingphilippe** [comment]
Fixed at the same time as #498
