### ISSUE TITLE
Create Airtable of Notify use cases 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#493]
_Create Airtable of Notify use cases _

## Description

As a Notify PM/Growth advisor, I need to be able to see quantifiable and qualitatively the top use cases for Notify over time so that I can demonstrate value, make data informed product decisions that meet user needs, and tailor messaging so that it reflects the problems public servants are solving through Notify. 

WHY are we building?
We have gaps in the metrics and data we're collecting about Notify use cases, and a missed opportunity because all of the data we need is being captured, we're just not analyzing it yet. The team often finds ourselves asking how many services would be impacted by a change or a feature or an issue and we don't know because we're not aggregating data on Notify use cases for regular analysis. 

WHAT are we building?
An Airtable that imports in "Requested to go live" tickets from FreshDesk, supplemented by insights from service templates 

VALUE created by our solution
We will be able to quantifiably and qualitatively analyze how Notify users were intending to use Notify when they began their service. This is the first phase towards building out more robust reporting on how Notify users use the product and whether intention matches reality. 

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given the team wants to know the most common Notify use cases of over a given time, when they search the Airtable, then they can sort by most frequent use case and see how many services were created for that use case, what date they were created on and the same data can be reflected in the zendesk CRM. 

- [x] Airtable with all historical requests to go live data imported from FreshDesk
- [ ] Tagging or coding system for labelling use cases in a common way to be able to sort by use case
- [x] Has all tombstone data collected when a service requests to go live
- [ ] Tracking how many templates each service has and the use cases found in each 
- [x] Data in Airtable can be exported to CSV for Leanne to import into Zendesk 
- [x] Service ID is included as a field in the data
- [x] Date of request to go live is included as a field in the data
- [ ] Access to Airtable and CRM is limited for privacy and sensitivity 

*** Nice to have*** Automated way in the future to bring in data from FreshDesk to Airtable in a continuous way to keep the Airtable up to date without manual effort.

**Comment by yaelberger-commits** [comment]
@EliseKa please review description and acceptance criteria when you have a chance! Thanks

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/493?planning-poker) with ZenHub @EliseKa

**Comment by EliseKa** [comment]
Good progress so far. 

Original go-live requests are now sorted into different fields. There's however a lot of information that is not accurate anymore (mostly service names), so I'm currently updating those based on the most recent live services report. I'm also slowly adding conventional department names for better sorting.

[Link to Airtable](https://airtable.com/appCP2c4xvXxQOfhN/tblsVsQjmKv1vY8VK/viw2UcRQKP5Ctm8s6?blocks=hide)

**Comment by EliseKa** [comment]
The go-live requests are now all updated, sorted into proper fields, and the naming convention for departments has been applied.

next steps to discuss: 
- adding the method of sending (interface vs api)
- adding services previous to last year

**Comment by EliseKa** [comment]
Adding previous services and sending method to the table today.

**Comment by EliseKa** [comment]
@yaelberger-commits I leave it to you to mark this card as done if you think it currently meets your needs. I will keep working on it on my side for Growth needs. We'll be tracking it in a new Growth Zenhub that @leannelabelle is setting up.

**Comment by yaelberger-commits** [comment]
@EliseKa I will move this one back into the Product Backlog until the remaining Acceptance Criteria are met. We can sync on this in the next few days.

**Comment by yaelberger-commits** [comment]
@ramya-cds will manually add new go live each week for the next few weeks until integration is ready. Mohamed and Ramya are working on it

@EliseKa Ramya will need access to the Airtable to be able to do this update weekly

**Comment by EliseKa** [comment]
@ramya-cds You now have "creator" permissions on the airtable, which gives you the ability to fully edit the board. Let me know if you encounter any issues!

**Comment by yaelberger-commits** [comment]
@EliseKa is planning a workshop with the team to group and tag use cases
