### ISSUE TITLE
Misapplied ARIA attributes

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#495]
Issue group: Header
Visibility: 3
Evaluation: Partially Supports
Success Criteria: 4.1.2: Name, Role, Value
Needs design: 

### Description
In the mobile navigation there is a `<div>` with aria-label=“language and sign-in”. aria-labels are intended for interactive elements and are not well supported on `<div>s`. This appears to be in an attempt to label the second set of navigation elements; which would be better served by having them in their own `<nav>` element. See comments for 1.3.1.

The “More” navigation submenu link has aria-hidden=“false”, even when its parent is visually hidden. This causes VoiceOver in Safari on macOS to include the “More” link. aria-hidden=“false” should not be used.

![](https://dl.airtable.com/.attachments/563135f10ee828e7011641d10ed14d56/8967efe1/Capturedecranle2022-03-15a14_00_22.png)

**Comment by amazingphilippe** [comment]
Fixed in https://github.com/cds-snc/notification-admin/pull/1302
