### ISSUE TITLE
Missing English and French translations

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#501]
## Describe the bug 

On staging (not production) Templates page is missing English and French content. Just the content tags are there

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-2 ? not on prod, but we're blocked on new releases until we fix this.

## To Reproduce

1. Go to a service
2. Go to the templates page

## Expected behavior

English and French content is there.

## Impact

Prevents us from releasing to prod

## Screenshots

![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/5315ff8d-7cb3-4a2e-b77b-cf901ffb8d10)

## Additional context

problem doesn't appear on production

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/501?planning-poker) with ZenHub @sastels @iokpala @amazingphilippe

**Comment by amazingphilippe** [comment]
> I think it's coming from this

My guess is that we probably use the same technique in different places. If we do a search for `polyglot.t` we get quite a few results.

**Comment by yaelberger-commits** [comment]
Needs discussion with @jimleroyer on priority

**Comment by sastels** [comment]
I believe this has been fixed, at least staging LGTM. @amazingphilippe @jimleroyer ?

**Comment by amazingphilippe** [comment]
Yep! Merged here: https://github.com/cds-snc/notification-admin/pull/1250
