### ISSUE TITLE
Design an accessible privacy statement for usability testing

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#502]
## Problem statement
Participants should feel comfortable participating in their research sessions and understand the terms of the session. Often, this information is not provided in the most accessible way. This means we may be excluding people from our recruitment that we don't want to exclude. This also means we're not ethically conducting the research.

## Hypothesis
A privacy statement that is written with plain language, tested, and provided in an accessible format will increase the diversity of our research participants and will provide more robust research insights. 

## Acceptance criteria
- [x] Privacy statement is drafted in English and French
- [x] Work with ATIP to identify what needs to be included and why
- [x] Document design decisions so that other teams can use the privacy statement
- [x] Design how participants can access the privacy statement before and after their session.

Reference: 
https://articles.alpha.canada.ca/confidentialite-notification-gc-notify-privacy/fable/

**Comment by YedidaZalik** [comment]
@amazingphilippe @yaelberger-commits it's fairly plain language, but if you could give me another time boxed day, I think we could tweak a few things and reorganize a bit.

**Comment by YedidaZalik** [comment]
@yaelberger-commits we've done the bulk of this now

**Comment by yaelberger-commits** [comment]
@YedidaZalik what is left to do?

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/502?planning-poker) with Zenhub @adriannelee @YedidaZalik

**Comment by YedidaZalik** [comment]
@yaelberger-commits I've checked off all the AC except this "Design how participants can access the privacy statement before and after their session." 
Should I add an estimate for how long it took in retrospect?

**Comment by andrewleith** [comment]
- Content part is done
- Discussion needed offline

**Comment by adriannelee** [comment]
The content was for something else. @mtoutloff revised the content a bit for the Fable testing we did this year. Creating another card for testing the content.
