### ISSUE TITLE
Admin should log non-sensitive configuration values on startup

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#503]
## Description

As a developer, 
I want to know the configuration values Notify admin is using when it runs,
so that I can quickly identify service misconfigurations.

## Acceptance Criteria** (Definition of done) 

- [x] Admin logs its non-sensitive configuration values in plaintext to a CloudWatch log group.
- [x] Setting boolean values should be done with explicit `True` and `False` values rather than with a variety of truthy strings.
- [x] Unit tests added to validate the new configuration code.
- [x] Logged configuration values validated in Staging and Production.

## QA
- [x] Check that CloudWatch has config logging for the `admin` service.
- [x] Check that config keys that are sensitive are displayed as `***`.
- [x] Check that `config.py` boolean and integer values are being set using `env.bool` and `env.int` from the environs package.
- [x] Check that unit tests exist for the config logging.

## Related
* #421

**Comment by patheard** [comment]
Admin config logging has been added and validated in Staging.

**Comment by patheard** [comment]
Admin config logging added and validated in Prod.

**Comment by patheard** [comment]
Environs change validated - pre and post change config matches.

**Comment by andrewleith** [comment]
Looks good - QA checks complete.
