### ISSUE TITLE
Put back api lambda to 10%

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#506]
## Description

We disabled the lambda API in production to get through the security incident, as the environment had mismatches. This task is to be done after that mismatch has been resolved.

## Acceptance Criteria** (Definition of done) 

- [x] The API lambda is re-enabled at an agreed rate.
- [x] Make sure lambda works as before in terms of speed and reliability.

**Comment by patheard** [comment]
Lambda API is now back at 10% weight in prod and smoke tests are continuing to pass with good speed.
