### ISSUE TITLE
Syncing NewRelic env vars in the API lambda

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#507]
## Description

We realized yesterday that the New Relic env vars are not perfectly in sync in the API Lambda environment. We are still using the old API key when it should be using the regenerated version.

## Acceptance Criteria** (Definition of done) 

- [x] New Relic env vars are in sync for API lambda environment for staging.
- [x] New Relic env vars are in sync for API lambda environment for production.

**Comment by mohamed-cds** [comment]
Lambda sync complete https://github.com/cds-snc/notification-terraform/pull/431
