### ISSUE TITLE
Delete old NewRelic license key

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#508]
## Description

We regenerated the NewRelic license key and started to roll it out in our k8s and lambda environments. The latter is not complete though as it is blocked with a minor issue. This task is a reminder to delete the old license key once it has been rolled out everywhere.

## Acceptance Criteria** (Definition of done) 

- [x] The API lambda staging/production environments have the new license key rolled out.
- [x] The old NewRelic license key has been deleted.

## QA

- [x] The New Relic key is present in the k8s pods for API and Admin.
- [x] The New Relic key is present in the API lambda environment.

**Comment by jimleroyer** [comment]
I'll take this on as I am partially doing this via #510. 

I'll leave a status I left in there yesterday that would apply here too:

> Regarding the deletion of the initial New Relic license key... New Relic support informed me that they cannot delete these and can only rotate. I asked them to rotate, knowing that I generated a new separate one in the meantime. We got a new key for the main and initial license key which means:

> 1. The initial license leaked key will now be invalid which is good.
> 1. We can rotate the New Relic key again back to the main license key.
> 1. Afterward, we can delete the extra license key I generated 10 days ago which is now be unnecessary.

**Comment by yaelberger-commits** [comment]
Rotate key today
Possible small release for this today

**Comment by jimleroyer** [comment]
We released the new key yesterday evening and I just deleted the temporary license key. @patheard Can you sign off on the QA steps are valid (add more if you want) as I know you already ran the checks yesterday during the release?
