### ISSUE TITLE
Update the manifests with new rotated admin secrets, new relic license key

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#510]
## Description

Propagate new values for rotated secrets into staging and production environments:

* AUTH_TOKENS
* ADMIN_CLIENT_SECRET
* NEW_RELIC_LICENSE_KEY

## Acceptance Criteria** (Definition of done) 

- [x] New values for described env vars are deployed to staging.
- [x] New values for described env vars are deployed to production.

**Comment by jimleroyer** [comment]
Regarding the deletion of the initial New Relic license key... New Relic support informed me that they cannot delete these and can only rotate. I asked them to rotate, knowing that I generated a new separate one in the meantime. We got a new key for the main and initial license key which means:

1. The initial license leaked key will now be invalid which is good.
2. We can rotate the New Relic key again back to the main license key.
3. Afterward, we can delete the extra license key I generated 10 days ago which is now be unnecessary.

CC @mohamed-cds as he followed the action around this one closely.

**Comment by mohamed-cds** [comment]
The NewRelic license key has a specific format. You can find the format in Notify - PBMM - [Production|Staging] Github secrets in LastPass. Once it's updated in GH secrets a TF apply will be required to update secrets manager with the new value.

**Comment by patheard** [comment]
Validated that new secrets have been deployed to staging and production by using the following commands and comparing the values to those in LastPass:

```sh
kubectl describe pod $DOCUMENT_DOWNLOAD_API_POD | grep AUTH_TOKENS
kubectl describe pod $ADMIN_POD | grep ADMIN_CLIENT_SECRET
kubectl describe pod $ADMIN_POD | grep NEW_RELIC_LICENSE_KEY
```
