### ISSUE TITLE
Reviewing Notify admins

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#512]
## Description

Review Notify admins to see if there are any outstanding entries and downgrade/remove obsolete access.

## Acceptance Criteria** (Definition of done) 

- [x] List is reviewed and proper access revisited.
- [x] New reviewed admin list is provided to the team.

## QA

- [x] Review the admin list

**Comment by jimleroyer** [comment]
List of current admins (+ added Patrick Heard yesterday):
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/f9c08aef-7358-4cf3-800b-26e2ea840fab)

**Comment by jimleroyer** [comment]
As an aside, there is a new document that was started for admin audits:
https://docs.google.com/spreadsheets/d/1nqRmotJvNY_ftNwr5R7_tk2HKrveNRBA-R77kNTU-FM

**Comment by yaelberger-commits** [comment]
@jimleroyer Where is the list of admins kept?

**Comment by jimleroyer** [comment]
That was exchanged through Slack with Adrianne when she QA'ed it. I initially left them here but decided to remove these as the board is public and I didn't want to share a list of admins in here.
