### ISSUE TITLE
Delete old github workflow logs 

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#513]
## Description

Delete old github workflow logs.

## Acceptance Criteria** (Definition of done) 

- [x] The workflow logs for the manifests repository is deleted.

## QA
- [ ] Validate that no workflow logs exist for the following `notification-api` and `notification-manifests` workflows from before March 30, 2022.
   - https://github.com/cds-snc/notification-manifests/actions/workflows/merge_to_main_production.yaml
   - https://github.com/cds-snc/notification-api/actions/workflows/lambda_staging.yml

**Comment by patheard** [comment]
This was handled by the following script which will get added to the SRE repo:
```python
from ghapi.all import GhApi
api = GhApi()

owner = "cds-snc"
repo = "notification-manifests"
workflow_name = "Merge to main (Production)"
page = 1

while page < 10:
    runs = api.actions.list_workflow_runs_for_repo(owner=owner, repo=repo, per_page=100, page=page, event="push")
    if not runs:
        break

    for run in runs.workflow_runs:
        if run.name == workflow_name:
            print(f"Deleting {run.id}")
            api.actions.delete_workflow_run_logs(owner, repo, run.id)
    page += 1
```

**Comment by jimleroyer** [comment]
# QA ❌

merge_to_main_production.yaml logs from before March 30, 2022:
https://github.com/cds-snc/notification-manifests/actions/runs/575973620 (Feb 17, 2021)

lambda_staging.yml logs from before March 30, 2022:
https://github.com/cds-snc/notification-api/actions/runs/1504222331 (Nov 5, 2021)
