### ISSUE TITLE
Notify GitHub workflows that use the `aws lambda update*` commands output function configuration

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#514]
## Describe the bug 

When one of the `aws lambda update*` commands is used in a GitHub workflow, it outputs the Lambda function's environment variable configuration to the GitHub logs, which can contain sensitive values in plaintext.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-1

## To Reproduce
1. Create a PR that has a workflow step that invokes a `aws lambda update*` command (e.g. [merge_to_main_production.yaml](https://github.com/cds-snc/notification-manifests/blob/main/.github/workflows/merge_to_main_production.yaml#L64-L68))
1. View the GitHub workflow logs for the run.

## Expected behavior

The Lambda API's environment variable configuration is not visible in the GitHub workflow logs.

## Impact

Leakage of sensitive values. 

## QA
- [x] Find all Notify GitHub workflows that use the `aws lambda update*` command.
- [x] Confirm that they redirect their stdout and stderr to `/dev/null` and no log output is visible in the workflow job step.

**Comment by andrewleith** [comment]
Tested in 4 workflows:
- in `notification-terraform`:
  - `.github/workflows/merge_to_main_production.yaml`
  - `.github/workflows/sync_secrets_production.yaml`
  - `.github/workflows/sync_secrets_staging.yaml`
- in `notification-api`:
  - `.github/workflows/lambda_staging.yml`

The output is not completely removed, but there are only a few keys, and it looks like secrets have been redacted:
```
Run aws lambda update-function-configuration \
  aws lambda update-function-configuration \
    --function-name api-lambda \
    --description $(date -u +"%Y-%m-%dT%H:%M:%SZ") > /dev/null [2](https://github.com/cds-snc/notification-manifests/runs/5979563360?check_suite_focus=true#step:7:2)>&1
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    AWS_DEFAULT_REGION: ca-central-1
    AWS_REGION: ca-central-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    ENV_DIFF: ***
```

@patheard was that the intent?  If so, we are good!
