### ISSUE TITLE
Notification manifests Makefile target `diff-staging` and `diff-production` fail to get previous encrypted `.env` file

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#516]
## Describe the bug 

The Notification manifests Makefile has two targets that are used to compare current and proposed changes to the encrypted `.env` file.

* [diff-staging](https://github.com/cds-snc/notification-manifests/blob/main/Makefile#L45-L47)
* [diff-production](https://github.com/cds-snc/notification-manifests/blob/main/Makefile#L49-L51)

These targets are currently failing attempting to download the current `main` branch copy of the encrypted `.env` file. 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV3

## To Reproduce

1. In the `notification-manifests` repo, run either of the [`diff-$ENV` Makefile targets](https://github.com/cds-snc/notification-manifests/blob/main/Makefile#L45-L51).
1. An error will be thrown stating that the previous encrypted `.env` file cannot be decrypted.

## Expected behavior

A `diff` view between the current and proposed encrypted `.env` file changes will be shown.

## Impact

1. Notify team members are unable to easily compare proposed changes to the encrypted `.env` files.
1. GitHub workflows that rely on these Makefile targets fail.

## QA
- [x] Run `make decrypt-staging`, make a local change to the Staging `.env` file and run `make encrypt-staging`.
- [x] Run `make diff-staging` and expect to see your change.
- [x] Run `make decrypt-production`, make a local change to the Production `.env` file and run `make encrypt-production`.
- [x] Run `make diff-production` and expect to see your change.

**Comment by patheard** [comment]
This was fixed by cds-snc/notification-manifests#1013 which switched to using the `git` project history to get the current `main` branch copy of the encrypted `.env` file.

The underlying failures downloading this raw file from GitHub were not determined, but this removes the chance of this error happening again in the future.

**Comment by yaelberger-commits** [comment]
Works as expected, let's get a second set of eyes from the team
