### ISSUE TITLE
Markdown Email template (Link character mismatch) bug

### ISSUE THREAD

**Issue by iokpala** [cds-snc/notification-planning#519]
# Motivation

Sequel to [1], the Notify user raise the issue of not being able to translate his markdown link properly with dynamic values passed with the markdown link brackets

# Description

As a Notify user, 
I need create dynamic variable value as part of markdown link

## WHY are we fixing this ?

To ensure the propagation of links that are unique to recipient groups or a user

## WHAT are we fixing?

Ensuring that custom or dynamic values pass with mutiple brackets within markdown a link (chracter set) returns the expected link.

## VALUE created by our solution

Will help users create and edit dynamic links with markdown within Notify's template

# Acceptance Criteria** (Definition of done) 

- [ ] Able to create / edit dynamic links with markdown within Notify's email template

**Goal**

* Improved user experience with Notify template

**Criteria**

- [ ] N/A

# Note

An example from the freshdesk ticket is  `(https://www.canada.ca/sign-in?id=(((dropzone_id_trimmed))))` where (((dropzone_id_trimmed)))) is the desired dynamic value which isn't being parse or interpreted properly from Markdown to HTML.

[1] https://cds-snc.freshdesk.com/a/tickets/9060

**Comment by yaelberger-commits** [comment]
Needs more refinement to determine if this is in fact a bug and level of severity

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/519?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels
