### ISSUE TITLE
Communicate with users on the security issues we experienced

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#521]
# Description

As a user of Notify,
I need to be informed of the recent security issue that Notify experienced,
So that I am informed and take appropriate measures according to what happened.

# What

Send a communication letter to the users informing of the events, risk, impact and actions to take.

We could open a special communication channel for that event, as it might triggers many questions (through freshdesk or Slack?).

# Acceptance Criteria** (Definition of done) 

- [x] List of users to send communication to have been collected.
- [x] Letter has been edited and translated with the outreach team.
- [x] Letter has been sent to users.

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/521?planning-poker) with ZenHub @yaelberger-commits @josh-cds @wmoussa-cds

**Comment by yaelberger-commits** [comment]
Content of the email is #2
