### ISSUE TITLE
Communicate end of maintenance window and need to reset password for all users

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#523]
_Communicate end of maintenance window and need to reset password for all users_

# Description

As a Notify admin, 
I need to notify all Notify users that the maintenance window is now over, and that they will need to reset passwords,
So that I can have everyone reenter their password as necessary after regenerating the SALT key.

## WHY are we building?

We need to have all users regenerate their password after the maintenance window

## WHAT are we building?

Sending a notification with password reset link to all users.

## VALUE created by our solution

More security by allowing us to rotate our secret and salt keys.

# Acceptance Criteria** (Definition of done) 

After the secret and salt keys were rolled out to production...

- [x] Draft reviewed
- [x] Email translated
- [ ] Template created 
- [ ] CSV ready (all users)
- [ ] Template reviewed
- [ ] All users received an email that maintenance window is over and to reset their password

**Comment by yaelberger-commits** [comment]
Sent to translation
