### ISSUE TITLE
Notify AWS WAF logs should have the Authorization header redacted

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#525]
## Description

As a user, I do not want the value of the Authorization header in the AWS firewall logs
so that I have confidence that my API key is not exposed.

## Acceptance Criteria** (Definition of done) 

- [x] Authorization header value not visible in AWS WAF ACL logs (both Lambda and k8s WAF ACLs).
- [x] Log redaction configuration is part of the `notification-terraform` project.

**Comment by yaelberger-commits** [comment]
@patheard let me know when you suggest we bring this into a sprint/priority

**Comment by patheard** [comment]
This has already been added to what I'm releasing with the Cloud Based Sensor changes tomorrow as part of cds-snc/notification-terraform#440 since I didn't want any API keys going out in the logs.

**Comment by andrewleith** [comment]
- Verified that the authorization header was redacted from the WAF logs. ✅ 
- Verified that the log redaction configuration was in both the `lambda-api` and `eks` modules in the `notification-terraform` repo ✅
