### ISSUE TITLE
Choose default lang. Images must have alt text

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#53]
## Description
Images for the multiple choices don't have alt text. We should at least describe that this choice will have an impact on the default FIP signature seen by receivers
![image](https://user-images.githubusercontent.com/5230720/135673154-6aff2faa-0e96-4bb6-b40d-fbe6b750e219.png)

## Resources
https://dequeuniversity.com/rules/axe/4.3/image-alt?application=AxeChrome

**Comment by EliseKa** [comment]
@amazingphilippe I'm thinking the alt text could be: 

English: Bilingual logo with "Government of Canada" written first in English, then in French.

French: Logo bilingue affichant « Gouvernement du Canada » d'abord en français, ensuite en anglais.
