### ISSUE TITLE
Entry for CCCS Cloud based sensor for third party data flows

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#530]
## Description

This is an entry for our to the third party data flows documentation [here](https://docs.google.com/document/d/1NT6zGoepvdyTmoUAy-3jHsoActIeTL66lRqPPSPt-K0/edit#). 

**WHY are we building?**
We are hoping to roll this out on Thursday April 7th and start sending our logs for threat protection to CCCS. We will be sending an email to users on Monday April 4th to let them know of this change and what will be included in these logs.  

We need to be able to describe what’s being shared and retained so users can be fully aware and have trust. If we have clear sight on our data flows and document them well, we will be able to have clearer public documentation to share with our users and inspire trust. 

# Acceptance Criteria** (Definition of done) 
- [x] Meeting to fill out technical details about what data is shared in the third party data flows documentation [here](https://docs.google.com/document/d/1NT6zGoepvdyTmoUAy-3jHsoActIeTL66lRqPPSPt-K0/edit#)

- [x] Draft email to send to Notify users letting them know about changes
- [x] Review of [email](https://docs.google.com/document/d/1kwrHDIfK4HFws97moYJthe9cfbd58r9ylCwh4rdcsBE/edit#) by PM and SRE team
- [x] Get email translated to FR

- [x] Ask dev team to get user list
- [ ] ~~Review by outreach~~
- [x] Send email to Notify users
- [x] Roll out on Thursday (by SRE team)

**Comment by sharlychan-cds** [comment]
Will have a meeting with outreach to talk about comms involvement. 
Email sent to all notify users

**Comment by yaelberger-commits** [comment]
@sharlychan-cds this seems done now to me, what do you think?

**Comment by sharlychan-cds** [comment]
Yes! agree
