### ISSUE TITLE
Onboard Notify to CCCS Cloud Based Sensor

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#531]
## Description

As a site reliability engineer, 
I want Notify firewall, load balancer and network flow logs to be sent to the Cloud Based Sensor,
so that Notify gains second line-of-defense analysis from CCCS to help prevent and troubleshoot cyber incidents.

## Acceptance Criteria** (Definition of done) 

- [x] Firewall, load balancer and network flow logs are sent to the Notify account satellite S3 bucket.
- [x] Confirm that Notify logs are replicated to the CloudBasedSensorCentral account.
- [x] Infrastructure changes are made through Terraform

## QA
- [ ] Check that WAF ACL logs, Load Balancer access logs and VPC flow logs are being sent to the Notify satellite S3 bucket in Notify Staging and Production AWS accounts.
- [ ] Check that the same logs are being received ing the `CloudBasedSensorCentral` S3 bucket.
- [ ] Check that the CCCS transport Lambda is being triggered for each of these log types with no errors.

**Comment by yaelberger-commits** [comment]
Testing in staging to make sure API keys are redacted properly in staging

**Comment by yaelberger-commits** [comment]
Jimmy to QA with walkthrough from Pat

**Comment by jimleroyer** [comment]
@patheard showed me the ropes on the CCCS, the Notify part and the SRE team part. It seems to work pretty good.
