### ISSUE TITLE
Update Notify Terraform to pin EKS node AMI

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#535]
## Description

As a developer,
I want to see the exact Amazon Machine Image (AMI) being used by our EKS nodes,
so that I can avoid unexpected behaviour if the `latest` AMI introduces a breaking change,
which will result in Notify being a more stable product.

## Acceptance Criteria** (Definition of done) 

- [x] [EKS node group release_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#release_version) pinned to a specific AMI.
- [x] EC2 instances in the EKS node group updated to that AMI and Notify service smoke-tested to ensure it still functions as expected.

## QA
- [x] Check that the Notification Terraform project has the AMI release version set for [Staging](https://github.com/cds-snc/notification-terraform/blob/main/env/staging/eks/terragrunt.hcl#L71) and [Production](https://github.com/cds-snc/notification-terraform/blob/main/env/production/eks/terragrunt.hcl#L41).
- [x] Check the AWS EKS console to verify that the [node group](https://ca-central-1.console.aws.amazon.com/eks/home?region=ca-central-1#/clusters/notification-canada-ca-production-eks-cluster?selectedTab=cluster-configuration-tab) is using the same AMI release version in the managed node group.

**Comment by patheard** [comment]
Some ideas for how we could be notified of new AMI images:
https://github.com/aws/containers-roadmap/issues/734

Likely the easiest is a GitHub workflow.

**Comment by patheard** [comment]
@jimleroyer could you please validate this one when you've got a chance.

**Comment by jimleroyer** [comment]
# QA Checks ✅

## Staging

### Pinned version in Terraform
https://github.com/cds-snc/notification-terraform/blob/5b60b2f8ea5fab3c0acd5d86fb2acda3344f9618/env/staging/eks/terragrunt.hcl#L71

### AWS EKS node group version in console
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/c2b7e32a-524e-4005-b94f-37be5b9a0b0c)

## Production

### Pinned version in Terraform:
https://github.com/cds-snc/notification-terraform/blob/5b60b2f8ea5fab3c0acd5d86fb2acda3344f9618/env/production/eks/terragrunt.hcl#L41

## AWS EKS node group version in console:
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/5e854215-4a76-4d6d-a0db-b0480ce224f6)
