### ISSUE TITLE
Better logging for the API's `get_notification_by_id` method calls

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#537]
## Description

As a developer,
I want to see more logging information when `app.v2.notifications.get_notifications:get_notification_by_id` fails with a `No row was found for one()`,
so that I can better troubleshoot notification lookup issues.

## Acceptance Criteria** (Definition of done) 

- [x] Logging added for the API `get_notification_by_id` method. 
- [x] Logs are appearing in CloudWatch for the Lambda and k8s API.

**Comment by patheard** [comment]
Over the past day of running with the new logging, we're only seeing two service IDs with this error:
```
fields @timestamp, @message
| filter @message like /Failed to get notification with filter/
| filter @message not like /$MYSTERY_SERVICE_ID/ 
| filter @message not like /$PROD_SMOKE_TEST_SERVICE_ID/ 
| sort @timestamp desc
| limit 20
```

Currently working with other devs to track down what the `$MYSTERY_SERVICE_ID` is connected to.

**Comment by andrewleith** [comment]
Looks good!

- Verified that the logging was added to the `get_notification_by_id ` method ✅ 
- Verified that the messages are appearing in the CloudWatch logs ✅
