### ISSUE TITLE
Create testing environment for usability testing

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#545]
As a GC Notify researcher,
I need to send research participants a test link during moderated or unmoderated testing, and know that I won't waste their time testing aspects of the site that are out of scope for that round (e.g. sign-in, Create a service, Trial)

**Update Sept 14 2023: Devs tried to refine this, requires us to answer a few more questions. If we want to take this on, we want to refine it with Design and Research** 
## Criteria
- [ ] Participant doesn't have to create an account
- [ ] Participant doesn't have to have a government email account
- [ ] (Nice to have) Don't have to reset the account manually after each session.
- [ ] Can't accidentally send out mass messages to the public.
- [ ] Security - Doesn't compromise our ability to check who did what if something goes wrong
- [ ] Security - Doesn't harm public trust in our security practice

## Possible options
- Locked down env where the emails/sms don't get sent (even though the screen shows successful)
- Could have a simple authentication
- Could use shared accounts? But then the accounts would have to be reset each session
- AWS database? But it's pricey
- Heroku & Docker compose? New heroku link for each participant (Destroy the account OR simple scripting to create/delete an account)
- Boka? Script hits the API wipes down anything that's been created. (Github workflow execute the script - "Account vending machine")
- Testing account on staging (doesn't send messages, doesn't do 2FA)
- Database schemas that can be generated. [FactoryBoy](https://factoryboy.readthedocs.io/en/stable/) might be better than Heroku because it creates an isolated env with set conditions. Might be worth it for future uses beyond usability testing.

## Related Issues

[Recreate a Notify environment to guarantee continuity](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/699)

**Comment by adriannelee** [comment]
From Ikenna, re: capabilities of FactoryBoy

https://github.com/ikennaokpala/flask-restful-api-example/blob/95c8485813fa673f3e64a50e0aba9684a5a54cd0/src/main/config/tasks/db.py#L20

https://github.com/ikennaokpala/flask-restful-api-example/blob/develop/src/data/__init__.py

**Comment by yaelberger-commits** [comment]
@amazingphilippe @adriannelee @andrewleith With how we've done the coded prototype for "What is a service" do we now have a test environment that meets the above criteria? Or should we keep this card around?
