### ISSUE TITLE
Trigger reset password and rotate secrets into production

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#546]
# Description

Rotate the secret key and salt in production, handling password reset and API regen in doing so.

## WHY are we building?

Rotate our secrets and reduce security risk.

## WHAT are we building?

Rotate our secrets and regenerating passwords as a side-effect.

## VALUE created by our solution

More secure environment.

# Acceptance Criteria** (Definition of done) 

- [x] Maintenance window has been announced before the reset in production.
- [x] API users have their keys re-signed
- [x] Notifications have their _personalisations re-signed
- [x] Callbacks and callbacks history are re-signed
- [x] Secret keys and salt are rotated.

- [x] Return service down error status (to explore and optional).

# Plan

- [x] 1. Send maintenance window email. @adriannelee 
- [x] 2. Merge manifests changes that rotates the secret key and salt. @jzbahrai 
- [x] 3. Deploy to production the secrets. @jzbahrai 
- [x] 4. Database backup @jimleroyer 
- [x] 5. Remove governmental email addresses from the email suppression list in AWS. Rely on the gov [email domain stored here](https://github.com/cds-snc/notification-admin/blob/9c2683ffe1de8a094944bf62084e5cfa55c52d33/app/email_domains.txt). @jzbahrai 
- [x] 6. Export all API keys locally and prepare a rollback SQL scripts containing UPDATE statements to previous values in case things turn wrong. @sastels (Jimmy & jumana on the call)
- [x] 7. Change the weighting to not have notifications go through. @patheard 
- [x] 8. Update `password_expired` to True for all users in Production @jzbahrai 
- [x] 9. Run script to re-sign the API keys. @sastels 
- [x] 10. Run script to re-sign the notifications. @sastels 
- [x] 11. Run script to re-sign the callbacks and callbacks history. @sastels 
- [x] 12. One of the smoke tests will fail when we rotate the keys, after the API keys are regenerated, rerun this smoke test @jzbahrai 
- [x] 13. Change the weighting back @patheard 
- [x] 14. Run QA tests in production. Team #notify-pw-golive

## If successful

1. Send users communication of the maintenance window over and report successful operations. Provide signal to @adriannelee so she can send the email.
1. Log the recorded downtime into our [tracking document](https://docs.google.com/spreadsheets/d/18XVoSk8HYBs2xppFVIDODlnDBD2vFnstwvoQM_QCbYM/edit#gid=0). @jzbahrai 

## If not successful

1. Revert the changes.
   1. Revert deployed manifest version using [release document](https://docs.google.com/document/d/17kVWBN4OK_mSgTK7h_dTyC1kpjcY_UhXOn1FpolH-GM/edit). @jzbahrai 
   1. Revert tables using previously generated SQL rollback UPDATE scripts together with the original tables. @sastels 
1. Send users communication (if any) of the maintenance window over and report unsuccessful operations. @adriannelee 
1. Log the recorded downtime into our [tracking document](https://docs.google.com/spreadsheets/d/18XVoSk8HYBs2xppFVIDODlnDBD2vFnstwvoQM_QCbYM/edit#gid=0). @jzbahrai 

# QA Steps

- [x] Smoke test account reset. Team
- [x] Smoke test sending a notification through the UI. Team
- [x] Smoke test sending a notification through the API. @sastels 
- [x] run the actual python smoke test script (make smoke test on CI) in API production @jzbahrai 
- [x] verify that all dashboards for a service still work. Team
- [x] send a message on a system with a callback and ensure that the callback still works 
     - https://notification.canada.ca/services/a581e959-c698-46da-8d46-58220ef03fd5 should use bearer token 1111111111 at https://beeceptor.com/console/sja-test @sastels

**Comment by yaelberger-commits** [comment]
April 28, 2022 4-5pm ET

**Comment by wmoussa-cds** [comment]
Downtime started as planned at 4pm

**Comment by wmoussa-cds** [comment]
All changes completed at 4:35pm
