### ISSUE TITLE
Update Document Download API to Python 3.9

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#553]
## Description

As a developer,
I would like to update the Document Dowload API to Python 3.9
so I could have a consistent Python version across services and allow for code re-use and stability.

## Acceptance Criteria** (Definition of done) 

- [ ] Document Download API service Docker image updated to Python 3.9
- [ ] Devcontiainer updated to Python 3.9
- [ ] GitHub workflows updated to Python 3.9

## QA Steps

- [ ] All Document Download API endpoints work as expected.

**Comment by jimleroyer** [comment]
This one is taken care of by @sastels  where he updates the project to Python 3.10.
