### ISSUE TITLE
Text clipped by ellipses

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#559]
Issue group: Tables
Visibility: 2
Evaluation: Partially Supports
Success Criteria: 1.4.10: Reflow
Needs design: Interaction

### Description
On mobile browsing and zoom magnifications on desktop that would trigger the mobile layout, the template information in the various template tables is clipped by ellipses (…). 

![](https://dl.airtable.com/.attachments/723976e41831251bf7fe9254ab951230/2beb6eb6/Capturedecranle2022-03-15a13_28_38.png)

**Comment by yaelberger-commits** [comment]
PR ready for review

**Comment by amazingphilippe** [comment]
Reviewed and merge. QA in the next release

**Comment by YedidaZalik** [comment]
Part of release last week and Phil already checked
