### ISSUE TITLE
Unexpected focus switch

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#562]
Issue group: API
Visibility: 1
Evaluation: Partially Supports
Success Criteria: 3.2.2: On Input
Needs design: Interaction

### Description
When adding additional email address or mobile number inputs to the API integrations safelist, the focus is pushed to the input field instead of remaining on the button. If trying to add multiple new inputs at once, the result is that the form is submitted. The focus should remain on the button. However, it would likely improve the overall interaction if all the inputs were always present.

![](https://dl.airtable.com/.attachments/29a1d4e89091bc6357767e3388dec8e5/08bf6372/Capturedecranle2022-03-15a13_44_39.png)

**Comment by amazingphilippe** [comment]
Fixed in https://github.com/cds-snc/notification-admin/pull/1257
