### ISSUE TITLE
Title attribute should not duplicate the text content

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#564]
Issue group: Your account, Tables
Visibility: 2
Evaluation: Partially Supports
Success Criteria: 1.3.1: Info and Relationships
Needs design: 

### Description
Title attributes used in the table on the Your profile page duplicate the cell text contents. The title attributes can be removed.

![](https://dl.airtable.com/.attachments/fea354afff6d89ec6ef46f22a32cb71b/0d4e674b/Capturedecranle2022-03-15a09_59_01.png)

**Comment by andrewleith** [comment]
Affected pages:
- Review before sending (CSV send)
- Activity on GC Notify (`/activity`)
- Service settings (`/service-settings`)
- User profile (`/user-profile`)
- Callbacks for delivery receipts (`/api/callbacks/delivery-status-callback`)
- Errors page when sending notifications
- Confirmation page when sending notifications
- Email complaints (admin) (`/platform-admin/complaints`)
- Providers (admin) (`/providers`)
- Data retention (service settings) (`/data-retention`)
- Breaking change page (when you change variables in a template)
- Security keys page (user profile) (`/user-profile/security_keys`)

**Comment by whabanks** [comment]
QA'd in prod and looks good! No redundant title attributes in the tables on the affected pages.
