### ISSUE TITLE
Inconsistent identification of inputs

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#566]
Issue group: Templates
Visibility: 2
Evaluation: Partially Supports
Success Criteria: 3.2.4: Consistent Identification
Needs design: Content

### Description
On the Templates page the input to create a template is called “Create template”, on the Dashboard page it’s called “Create a template”.

![](https://dl.airtable.com/.attachments/83c1ee92527495ebdbb7bdb97f19dbcb/98169f5c/Capturedecranle2022-03-15a13_46_24.png)

**Comment by YedidaZalik** [comment]
@YedidaZalik to review

**Comment by YedidaZalik** [comment]
issue was that same button for same action had different label
the buttons that were next to each other needed to be consistent and that's fixed
To be merged

**Comment by adriannelee** [comment]
Not yet merged. Yedida suggested edits. @amazingphilippe will make the edits and merge today

**Comment by amazingphilippe** [comment]
Merged. Waiting for next release to QA one last time.

**Comment by smcmurtry** [comment]
Looks good on prod.
