### ISSUE TITLE
Table structure

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#575]
Issue group: Tables
Visibility: 2
Evaluation: Partially Supports
Success Criteria: 1.3.1: Info and Relationships
Needs design: 

### Description
The example table used on the “Upload a list of recipients” page has an empty `<th>` in the top left corner (first cell). This should either contain appropriate header text or use an empty `<td>`. If the first column is also intended to be a label for the row, the cells should use `<th>` instead of `<td>`.

**Comment by adriannelee** [comment]
Few PRs for this and other a11y issues. @amazingphilippe will link the PRs and move them into Review

**Comment by amazingphilippe** [comment]
This PR fixes the issue with empty table headers. https://github.com/cds-snc/notification-admin/pull/1735
