### ISSUE TITLE
Template select - Context changes on input

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#586]
Issue group: Templates
Visibility: 3
Evaluation: Partially Supports
Success Criteria: 3.2.2: On Input
Needs design: Interaction, Content

### Description
On the templates page, when a checkbox is checked the controls below change from “Create template”, “Copy template”, and “New folder” to “Move” and “Add to new folder”. There is no indication to an AT that the controls have changed. One notable issue is that it’s easy to assume that the checkbox is related to “Copy template”. Consider having all of the controls always visible with the ones related to moving disabled until a selection is made, or providing error feedback if they are triggered without a selection.

![](https://dl.airtable.com/.attachments/c73abf8e558feac3fe49c12f817ce85b/7583a65d/Capturedecranle2022-03-15a13_44_00.png)

### Docs
https://www.figma.com/file/r3GzRBjBDWvL2AwCWq1e1W/Navigating-the-site-%7C-Naviguer-le-site?type=design&node-id=8721-3121&mode=design

**Comment by yaelberger-commits** [comment]
Timeboxed to 1 week, what can we do to improve and make more intuitive in a short time?

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/586?planning-poker) with Zenhub @adriannelee @amazingphilippe @YedidaZalik

**Comment by amazingphilippe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/586?planning-poker) with Zenhub @smcmurtry

**Comment by adriannelee** [comment]
Bringing into dev-design review.

**Comment by amazingphilippe** [comment]
Prototyped some content for aria-live regions in EN and FR.

**Comment by smcmurtry** [comment]
Put together a PR that adds the content from Phil to the aria-live region.
PR: https://github.com/cds-snc/notification-admin/pull/1680
Demo: https://www.youtube.com/watch?v=bfQtLGpI5Xc

**Comment by amazingphilippe** [comment]
Created some content for the live region in both languages. Added it as a comment to the PR https://github.com/cds-snc/notification-admin/pull/1680

**Comment by whabanks** [comment]
Updated the content for live regions, adjusted some JS to prevent redundant speech when selecting templates and fixed an issue that occurred when a user had no templates to display but a label indicating that templates existed was being read. Video comparisons in the PR cds-snc/notification-admin#1680.

**Comment by whabanks** [comment]
PR review finished and merged this morning, ready for QA!
