### ISSUE TITLE
Skipped heading levels 

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#588]
Issue group: Service settings
Visibility: 1
Evaluation: Partially Supports
Success Criteria: 1.3.1: Info and Relationships
Needs design: 

### Description
The Reply-to address page, under Settings, uses `<h3>` headings for each address. This skips the `<h2>` heading level and could cause confusion or difficulty when navigating with an AT. An` <h2>` heading could be added above the `<h3>` headings, the addresses could be bumped up to an `<h2>`, or the structure could be revised to remove the need for the addresses to be headings (e.g., using a list, table, etc.).

![](https://dl.airtable.com/.attachments/f86e3d210d52d6034d117de341df4abb/ea984ea7/Capturedecranle2022-03-15a09_57_25.png)

**Comment by YedidaZalik** [comment]
Already checked and released
