### ISSUE TITLE
Celery process terminated because OutOfMemory (SIGKILL)

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#591]
## Describe the bug 

Since the beginning of April, we've noticed an increased number of `celery` pod errors where a worker process is killed with reason `OutOfMemory`: 

```sh
fields @timestamp, @message
| filter @message like /SIGKILL/
| filter kubernetes.container_name = "celery"
| sort @timestamp desc
| limit 20
```

![image.png](https://images.zenhubusercontent.com/6141f63cba17b3613a6dcef0/b1e16591-38e8-4ffe-a35d-da9f153cbad4)

```	
[2022-04-11 18:48:12,246: ERROR/MainProcess] Process 'ForkPoolWorker-11' pid:2402 exited with 'signal 9 (SIGKILL)'
```

At first it appeared this was linked with a specific notification template attaching multiple files, but the errors have continued intermittently.

We've also noticed an consistent increase in `celery` pod memory since the beginning of April:
![image.png](https://images.zenhubusercontent.com/6141f63cba17b3613a6dcef0/aa54bc13-7be9-484a-9df6-b5fbef294daa)

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-3

## To Reproduce

No easy way to reproduce apart from sending a notification with 10+ file attachments with sizes greater than 300kb each.

To confirm if a `celery` process has been terminated because of `OutOfMemory`:
```sh
kubectl exec $CELERY_POD_NAME -- sh -c "dmesg | grep oom"
```

## Expected behavior

`celery` pods do not have worker processes SIGKILLed with OutOfMemory errors. 

## Impact

Impact on Notify users:
* 4h15m delay in sending notification as it must be retried with a new `celery` worker.

Impact on Recipients:
* 4h15m delay in receiving notification for same reason as above.

Impact on Notify team: 
* Troubleshooting as CloudWatch alarms trigger for `celery` pod errors.

## Additional context
It may be possible to fix this by increasing the `celery` pod resource limits and replica count.  Investigation should be performed to make sure this memory increase is related to higher service volume rather than a chance we've introduced.

**Comment by patheard** [comment]
Troubleshooting with @jimleroyer, we saw that when a notification caused an OOM termination of a celery process, that notification would then need to wait for 4 hours, 15 minutes to be retried.  Examples of two IDs with this pattern:
```
4ada61ae-bae6-4362-a5e8-8ea3d917e9a1
bcbdc368-f5a3-4770-a0a8-53e84215a444
```

**Comment by yaelberger-commits** [comment]
Investigation to ensure all celery errors we saw were related to TC service sending too many attachments, and not another issue with celery also at play.

**Comment by patheard** [comment]
Using the following SQL query, we've traced all SIGKILL celery errors to two services that were stress testing with high volumes of attachments:
```sql
SELECT 
  (sent_at - created_at) as delta, id, service_id, template_id, created_at
FROM
  notifications n
WHERE 
  n.service_id IN ($SERVICE_ID_1, $SERVICE_ID_2)
ORDER BY delta desc, created_at desc;
```

This shows the time delta between when the notification is created and marked as sent.  Notifications that cause a celery SIGKILL end up having to wait 4 hours, 15 minutes to be retried, and then cause the repeated SIGKILL every 15 minutes after.

Then, using CloudWatch log insights, it was possible to associate the notifications with all the SIGKILL celery errors we’ve seen since the beginning of April. This shows the memory spikes and errors was caused by these two services, and will be addressed by #592.  

Related, since these 2 services have stopped testing, we've seen a large drop in pod memory use:
![image](https://user-images.githubusercontent.com/2110107/163239805-2454b702-ad7c-4b6b-9c2e-269a63e56722.png)

**Comment by patheard** [comment]
@jimleroyer if you agree with my analysis in the last comment, I'd say we can mark this bug as `Done`.

**Comment by jimleroyer** [comment]
Analysis is great! but I am unsure of next steps. The bug can reoccur again given high number of attachments. What would you suggest?

**Comment by patheard** [comment]
I would suggest we focus on this in #592 and set attachment limits:

- total number; and/or
- total size

We'd need to do some testing to figure out where the "safe" number is that we want to support.

**Comment by jimleroyer** [comment]
Works with me. Let's consider the output of this card is the analysis and recommendations, now associated with #592.
