### ISSUE TITLE
Notify and Privacy Act Request Flow

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#595]
_Give your user story a simple, clear title_

## Description

We need to make sure that CDS products (and Notify) have a standard / straightforward way for departmental teams to pull their info in response to an ATIP request.

GC Notify needs to document this process if an ATIP request comes in so that we can: 1) understand what information we can/ can't provide, 2) respond to ATIP requests in a timely manner, and 3) Support strategic policy on this ATIP front on how this may change with amendments.

This documentation is due by the end of May.

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] Define what kind of info could be pulled from Notify service 
- [x] Define what kind of info could be pulled related to P/Ts
- [x] Explain how our retention policies impact ATIP requests

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/595?planning-poker) with ZenHub @sharlychan-cds

**Comment by yaelberger-commits** [comment]
Sharly and Sarah working on this today

**Comment by yaelberger-commits** [comment]
Meeting between Sharly and Sarah today

**Comment by yaelberger-commits** [comment]
@sharlychan-cds Needs discussion as to priority level in relation to other P/T priorities. Is other P/T work dependent on this or not?

**Comment by amazingphilippe** [comment]
@sharlychan-cds to fix this card.

**Comment by yaelberger-commits** [comment]
@sharlychan-cds Is this card done or do we need to bring it back in a future sprint?

**Comment by sharlychan-cds** [comment]
This is done! https://docs.google.com/document/d/1LKR30iQynT5K7wVXRwhqv1PgbgXJ9b22vGR4GAiFxrc/edit#heading=h.ywa80xhhhfr5
