### ISSUE TITLE
Create more intuitive concepts for "template"

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#596]
## Problem statement
Senders have to learn several concepts, such as "templates" in order to use GC Notify. This unnecessarily creates a learning curve for many Senders. There is room for misunderstanding, where people who would benefit from using GC Notify don't use it. It also means the product needs to rely on the Growth team to provide demos and the support team to answer questions. This limits the product's potential to scale. 

While the confusing concepts are _possible_ to learn and does not limit someone from completing a task, this issue has come up repeatedly in research findings since GC Notify's Discovery phase (like [this issue](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/rec1ve0GUi0xgmj8W?blocks=hide), and [this issue](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recPixTUxqBrJBt74?blocks=hide)). 

Confusing concepts also impact navigation.

Information can also be more chaotic to people who use assistive technology.

## Hypothesis
1. If we create concepts for "template" that are more intuitive to Senders (and distinguish GC Notify from an email client), then the percentage of new template names that are 'correctly' written will increase by 80% in 1 month of implementation.
2. If we define "template" to our users in different context (first appearance, empty states, guidance, homepage), then users will be more likely to learn the meaning of those words when encountering them for the first time.

* 'Correctly' = Subjective, but let's say "Wouldn't look like a mistake if it was sent out"

## Acceptance criteria
- [x] User story mapping https://miro.com/app/board/uXjVO6TPyIs=/
- [ ] Doesn't confuse existing Senders on GC Notify
- [ ] Ready for concept testing
- [ ] New concepts have potential to solve the related issues (from the Airtable, linked below)

## Research Airtable links
There are a lot, but just linking the ones from the Fable 03/2022 testing
[Link 1](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recIj2vWeS1ePDlZK?blocks=hide)
[Link 2](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recwbnKR8Chrv5NZ9?blocks=hide)
[Link 3](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/rect23i8cb74WiijJ?blocks=hide)
[Link 4](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recWqAvBxmJzLpOFM?blocks=hide)
[Link 5](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recFZNw36oRMcmBy4?blocks=hide)
[Link 6](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recACbmzbxbYh7c3D?blocks=hide)
[Link 7](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recblnDB8SxHeDSz4?blocks=hide)
[Link 8](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recmzf3LXWYDZEqr4?blocks=hide)
[Link 9 ](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/rec2cgxLBQYQhncRN?blocks=hide)

Figma: https://www.figma.com/file/RLcM0JwlQsd2uVK3GJr5qY/Drafting-message-templates-%7C-Creer-des-gabarits-de-message

**Comment by yaelberger-commits** [comment]
CORE team sync needed on this as it relates to unified account management discovery 
Yedida to attend unified account workshop next week

**Comment by yaelberger-commits** [comment]
Split this user story up into two, one for template and one for service

**Comment by yaelberger-commits** [comment]
Edited the user story to scope down to just "Template" concept. New story for "Service" concept is #679

**Comment by yaelberger-commits** [comment]
Include in design sync today, overlap with spreadsheet story

**Comment by amazingphilippe** [comment]
Designs for the dashboard are done. Need annotations.

**Comment by yaelberger-commits** [comment]
@amazingphilippe could you please complete your planning poker vote on this one? Thanks

**Comment by amazingphilippe** [comment]
Annotated and sent to translation.
Also ready for a dev-design review once we have the capacity to implement this.

**Comment by adriannelee** [comment]
Changed the title of this issue from` Create more intuitive concepts for "template"` to `Better explain "template"` because we didn't change what templates are called.
