### ISSUE TITLE
Change language on the email we send after Password Reset. 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#607]
https://gcdigital.slack.com/archives/C03C1V0V9QQ/p1649858859436509

When you get an email, it’s generic and says “you requested” , should say your password has been expired. You can now create a new password for your account
Create a new email template to send in its place
Your link expires after an hour
Do not share or forward this email with anyone 

- [x] Yael and designers to write a new email template/translate it and handoff to devs
- [x] Jumana can be the dev on this one

**Comment by yaelberger-commits** [comment]
Current email:
Hi Stephen Astels,

We received a request to reset your password on GC Notify.

If you didn’t request this email, you can ignore it – your password has not been changed.

To reset your password, click this link:
Password reset

Bonjour Stephen Astels,

Nous avons reçu une demande de réinitialisation de votre mot de passe dans GC Notification.

Si vous n’avez pas demandé ce courriel, vous pouvez l’ignorer – votre mot de passe n’a pas été changé.

Pour réinitialiser votre mot de passe, cliquez sur

**Comment by adriannelee** [comment]
Drafted here https://docs.google.com/document/d/1jYECflaBxyMGG9t9Q2YOF1tdIWm-AqywPZ390yX1Vmw/edit#heading=h.z6vztxl3s198

**Comment by yaelberger-commits** [comment]
@jzbahrai can I get a status update on this one today? Thanks!

**Comment by jzbahrai** [comment]
I am in the process of updating this.

**Comment by jzbahrai** [comment]
@yaelberger-commits this is done and merged into staging.
