### ISSUE TITLE
Password being hard to guess is unclear. Give better guidance on how to create a good pass.

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#608]
Guidance how to make a good, strong password
Match guidance to our password policy in Notify code 
Must be at least 8 characters and hard to guess (list of blocked words)
Goal is to provide better guidance around stronger passwords, change the content but not the code at this time 

- [x] Yael will provide the screen to Jumana to implement 
- [x] Jumana will provide Yael the guidance and be the dev on this 

### Acceptance Criteria

- [x] At least 8 characters—the more characters, the better.
- [x] A mixture of both uppercase and lowercase letters.
- [x] A mixture of letters and numbers.
- [x] Inclusion of at least one special character, e.g., ! @ # ? ]
- [x] + we need a line saying do not use commonly used/ easy to guess passwords (Maybe)

**Comment by yaelberger-commits** [comment]
even though it's not in the code "New Password Security Criteria: 8 characters with at least 1 Upper Case, 1 lower case, and 1 numeric character"

**Comment by yaelberger-commits** [comment]
Current:
Create a new password
You can now create a new password for your account.

Password
Must be at least 8 characters and hard to guess

**Comment by yaelberger-commits** [comment]
Figma EN: https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?node-id=2%3A12

**Comment by yaelberger-commits** [comment]
Being reviewed by @adriannelee and @amazingphilippe

**Comment by yaelberger-commits** [comment]
@jzbahrai Can I get a status update on this one too please today? Thanks!

**Comment by jzbahrai** [comment]
hey this is done but not yet merged, will update when merged.

**Comment by jzbahrai** [comment]
@yaelberger-commits this s done and merged into staging.
