### ISSUE TITLE
No `login_event` record is created in the password reset flow

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#615]
## Describe the bug 

Login history is not properly recorded during the reset password flow.

## To Reproduce

1. As a user with an expired password, login
2. Follow link in reset email
3. Create new password
4. On Sign-in history screen, note that there is no item listed for this login

## Expected behavior

- Sign-in history screen should include the current login.

#### User with `auth_type` = `email_auth`
- [x] Logging in after forced password reset works, login event shown on sign-in history page
- [x] Regular login works, login event shown on sign-in history page
- [x] Changing password from profile page works, with no login event shown on sign-in history page

#### User with `auth_type` = `sms_auth`
- [x] Logging in after forced password reset works, login event shown on sign-in history page
- [x] Regular login works, login event shown on sign-in history page
- [x] Changing password from profile page works, with no login event shown on sign-in history page

## Impact

Impact on Notify users:
- Low

Impact on Recipients:
- None

Impact on Notify team: 
- May make troubleshooting a little harder

**Comment by andrewleith** [comment]
**Notes**
- Sign-in history page uses data from the login_event table
- On normal login (email_auth and sms_auth)
  - :white_check_mark: Entry in login_event table is created when user/pass is submitted (before security code is verified)
  - :white_check_mark: Entry in events table (sucessful_login) is created once code is verified
- On password reset flow (email_auth and  sms_auth)
  - :white_check_mark: Entry in events table (sucessful_login) is created once new password is set
  - :x: No login_event is written

Possible solutions:
1. Ensure both types events are written during the password reset/expired flow
2. Re-work password flow logic based on [OWASP recommendations](https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html) to force user to login after password reset.  The events will be written correctly in this case.

**Comment by andrewleith** [comment]
Finalizing PR's for both api and admin today.

**Comment by sastels** [comment]
I did the QA steps locally on checkout branches. Not sure if that counts or if we should also do it on staging / prod?
