### ISSUE TITLE
Improve usability of option buttons

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#622]
## Problem statement
[The option buttons throughout the site were visually very clear and easy to select (e.g. email vs. text). While they were read well by a screenreader, the labels that were read by a screenreader were repetitive (once on the button and again on the option).](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viw46eeZL8FaJglsC/reclx3UyhElf8S6qP?blocks=hide)

E.g.
- Selecting English or French branding

[Will include a clip of this from the Fable sessions]

**Comment by YedidaZalik** [comment]
Not adding to Ally statement because fixed
