### ISSUE TITLE
Create Notify Admin Pull Request (PR) review environments

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#625]
## Description

As a developer,
I would like review environments to be created for each PR submitted to the `notification-admin` project,
so that my changes can be easily tested and validated by other team members,
which will make it less likely that bugs and errors will be released to Staging.

## Acceptance Criteria** (Definition of done) 

- [x] Each PR submitted to `notification-admin` creates a temporary review environment where the PR branch changes can be reviewed in a browser.
- [x] A comment is posted to the PR with the review environment URL.
- [x] When new commits are pushed to the PR, the review environment is updated with the changes.
- [x] When the PR is closed, the review environment is deleted.
- [x] A scheduled job cleans up review environments that have not been accessed in a long time (~4 weeks).

## QA Steps

- [x] When a PR is submitted to `notification-admin`, a comment is posted on the PR with a link to the review environment.
- [x] The review environment has all the changes from the PR branch.
- [x] Pushing new commits to the PR branch updates the review environment with those changes.
- [x] The review environment is connected to the Staging API and has access to Staging data.
- [x] Closing the PR (either with a merge or close action) deletes the review environment.

**Comment by yaelberger-commits** [comment]
Get Github workflows in place, pat working on this today and tomorrow. Using AWS Lambdas, not Heroku anymore

**Comment by patheard** [comment]
PR review environment is now live, but the following is required:

1. Setup Terraform to create the `notify/admin` ECR and `notify-admin-pr-*` Lambda IAM role.
2. Setup Terraform to allow `notify-admin-pr-*` Lambda to access Redis on Staging.
3. Scheduled job that deletes unused review environments.

**Comment by patheard** [comment]
I'm looking into it, but this might be a limitation of Lambda function URLs being unable to handle a `POST` request with `GET` params.  I've seen a few questions about it, but no definitive solution yet.

**Comment by patheard** [comment]
I've confirmed that an API Gateway `/{proxy+}` integration with a Lambda function works: POST requests with GET parameters are handled properly.

Reaching out to AWS support to see if there are any fixes available for the Lambda function URL.

**Comment by patheard** [comment]
Support case [10020659131](https://us-east-1.console.aws.amazon.com/support/home?region=ca-central-1#/case/?displayId=10020659131&language=en) in `Notification-Staging` opened with AWS.

**Comment by patheard** [comment]
Deployment of the review env in `us-east-1` works correctly, so it looks like this is a known issue with `ca-central-1`.  Since there is no data at rest with the PR review env, and all data is encrypted in transit, it may be an acceptable workaround to deploy to `us-east-1`.

The one gotcha this introduces is that it'll make it more difficult to hook the PR review env up to Redis since it will no longer be possible to directly attach the `us-east-1` function to a `ca-central-1` VPC.  We'd need to use VPC peering as a workaround.

**Comment by andrewleith** [comment]
Did they give any idea how long until they fix the issue in `ca-central-1`? If its short term we may be able to live with the issue. Has anyone else reported any other parts of admin that are affected by this?

**Comment by patheard** [comment]
No timeline yet for a fix.  The only other part of admin that I've noticed not working correctly in the PR review environment is adding a security key to your account.  I didn't test if this worked in `us-east-1` either.

**Comment by andrewleith** [comment]
Adding security key returns a `502`, unlike `/add-service` which returns a `403`.  Also, I don't see any query params for the security key route. Could this be a different issue?

**Comment by patheard** [comment]
Yeah, this one's related to an encoding issue.  I suspect it's because of how the `api_wsgi_handler` is trying to return binary content and not because of the region:
```
[ERROR] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte Traceback (most recent call last):   File "/app/application.py", line 46, in handler     response = apig_wsgi_handler(event, context)   File "/usr/local/lib/python3.9/site-packages/apig_wsgi/__init__.py", line 95, in handler     return response.as_apig_response()   File "/usr/local/lib/python3.9/site-packages/apig_wsgi/__init__.py", line 353, in as_apig_response     response["body"] = self.body.getvalue().decode("utf-8")  

```

**Comment by jimleroyer** [comment]
Putting to block for now: will create a follow up card after rescoping the card and creating a new one with the identified issue.

**Comment by patheard** [comment]
AWS support just reached out to let us know that the fix for the POST + GET query params fix has been deployed in `ca-central-1`.  I tested and everything is working as expected now :tada:

**Comment by patheard** [comment]
I've also created #650 to track the Redis work that would be needed.
