### ISSUE TITLE
Priority Lanes: Batch Saving Updates

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#627]
When we did the initial version of the Batch Saving Implementation we didn't take into account the Notification Process type - 'Normal, Bulk and Priority'.

This Epic encapsulates all the information from this ADR (which is a work in progress):
https://github.com/cds-snc/notification-adr/blob/e777cecfd250181b95d463d99fe02fbab628bb2a/records/2022-03-08.priority-lanes.md

The feature flag for this epic is: FF_PRIORITY_LANES

**Comment by yaelberger-commits** [comment]
@josh-cds I took at look at this new Epic the devs have created to implement the work that came out of the ADR on priority queues the team has been finalizing. I'm approving them moving this also into the current sprint, as we planned to bring this work in next after forced password reset
