### ISSUE TITLE
Change the API to send Notifications to the correct Inbox

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#629]
## Description

Change the API to send the notification to the correct INBOX based on the notification type.

WHAT are we building?
We want each notification to be treated differently based on the process_type. We will send each notification into a different INBOX, based on the type of notification (SMS, email) as well as the process_type of the notification (bulk, priority, normal).

## Acceptance Criteria** (Definition of done) 

- [x] Add a feature flag for the new code path
- [x] Send the notification to the correct INBOX type

## QA Steps

- [x] Add tests

**Comment by jzbahrai** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/629?planning-poker) with ZenHub @andrewleith @iokpala @sastels

**Comment by yaelberger-commits** [comment]
Andrew looking into this, PR up shortly. Good to get some eyes on this

**Comment by jimleroyer** [comment]
Reviewed/merged, ready for QA.

**Comment by yaelberger-commits** [comment]
Jumana QA'd
