### ISSUE TITLE
Metrics and alarms

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#632]
## Description

We currently have metrics in place for batch saving. We need to update these metrics as well as the cloudwatch graphs with the new inboxes/ and new flow.

## Acceptance Criteria** (Definition of done) 

- [x] Metrics and alarms have been captured and updated in code
- [x] Graphs have been updated

**Comment by jzbahrai** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/632?planning-poker) with ZenHub @andrewleith @iokpala @sastels

**Comment by sastels** [comment]
So right now we have email and sms redis queues, but we mix their metrics together, for example we have batch_saving_published metric that has both email and sms data in it.
Do we want to do this for the new priority lanes, for example have priority_batch_saving_published with both emails and sms going into it, or do we want priority_email_batch_saving_published  and priority_sms_batch_saving_published ?

**Comment by sastels** [comment]
As discussed IRL we can add the priority and notification type using dimensions on the metrics

**Comment by yaelberger-commits** [comment]
In discussion with Mohamed, to be merged soon

**Comment by yaelberger-commits** [comment]
PR for alarms based on metrics should be reviewed
Need to first make sure metrics are working as part of Terraform alarms PR

**Comment by yaelberger-commits** [comment]
Everything merged, but haven't QA's yet. Need new dashboards to visualize metrics
