### ISSUE TITLE
Email reminders to Notify users of maintenance window 24 hours before and at start time

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#633]
_Email reminders to Notify users of maintenance window 24 hours before and at start time_

## Description

As a Notify user, I need to be able to know the maintenance window and service outage are coming up so that I can plan for it and know what to expect, and so I don't try to log in or send notifications during that time. 

WHY are we building?
We need a planned 1-hour maintenance window and service outage so we can rotate secrets and expire all passwords, and we need to give everyone ample notice so they know what to expect and aren't surprised or frustrated

WHAT are we building?
2 bilingual bulk emails 

VALUE created by our solution
Users know what to expect and aren't surprised or frustrated by planned service outage

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given the Notify team has a planned service outage on April 28, 2022 at 4PM ET for one hour, when it's 24 hours before, all users are sent a reminder, and when it's the start time of the service outage, all users are notified, then nobody is surprised by the 1 hour of downtime

- [x] Emails are bilingual and have been translated
- [x] CSV is of all current users
- [x] Start time email #4B is sent just before downtime (otherwise we can't send it)

## QA Steps

- [x] Translation is reviewed
- [x] Template is reviewed 
- [x] CSV is cleaned up

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/633?planning-poker) with ZenHub @adriannelee @amazingphilippe

**Comment by yaelberger-commits** [comment]
Adrianne creating templates in GC Notify in prod 
Adrianne will schedule the bulk send with CSV

**Comment by adriannelee** [comment]
Templates are scheduled to be sent with the new spreadsheet
