### ISSUE TITLE
Upgrade Python formatter

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#638]
To format our Python we're using black version 21.5b2 (see https://github.com/cds-snc/notification-admin/blob/main/requirements_for_test.txt) but 22 is out now and we should probably upgrade
> At long last, Black is no longer a beta product! This is the first non-beta release and the first release covered by our new stability policy.

There are style changes but currently only 3 files would be reformatted.

**Comment by yaelberger-commits** [comment]
Closing because we're moving to Ruff and we upgrade our packages now.
