### ISSUE TITLE
Refactor the dao_get_template_by_id function to not return a tuple

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#641]
# Description

The `dao_get_template_by_id` (https://github.com/cds-snc/notification-api/blob/main/app/dao/templates_dao.py#L97) function can return either a class (`Template` or `TemplateHistory`) or a tuple `(Template, dict)` depending on if the cache is used or not. This is very confusing and can lead to code that works if the template is not in the cache but crashes if it is.

# Impact

This complicates our code and actually led to bugs we had to fix.

# Acceptance Criteria

Simplify the function and make it work as before! There is no need to return an either value out of it, just the expected value.

We should refactor the code to just return a `Template` or `TemplateHistory`.

# QA

- [ ] Regression tests work fine. 

# Additional Notes

- the dict is a dictionary version of the `Template`
- the dict is occasionally used in our code - in these cases we will have to switch to using the `Template` instead

**Comment by yaelberger-commits** [comment]
Simplify some code, to avoid issues we've seen in the past. Maybe 1 hour of work

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/641?planning-poker) with ZenHub @jimleroyer @jzbahrai @andrewleith @sastels @iokpala

**Comment by whabanks** [comment]
Completed the code for this yesterday. Ready for review!

**Comment by whabanks** [comment]
Reviewed by @sastels and @jzbahrai. Ready for QA!

**Comment by YedidaZalik** [comment]
Jumana to QA
