### ISSUE TITLE
Allow users to send files through email notifications

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#642]
## Description

As a (user), I need to be able to (send files) so that I can achieve (efficiency in my business processes). 

### WHY are we building?
- To help our users fulfil their mandates and send out meaningful information to their users

### WHAT are we building?
- A mechanism to allow our users to upload attachments and then refer to them as links in email notifications
**NOTE:** This feature already exists in Notify and is in use by GDS:  https://docs.notifications.service.gov.uk/rest-api.html#send-a-file-by-email

### VALUE created by our solution
- Provides our users more options to meet their business needs.

## Acceptance Criteria** (Definition of done) 
- TBD

## QA Steps
- TBD

**Comment by yaelberger-commits** [comment]
Isn't this already possible? @andrewleith

**Comment by andrewleith** [comment]
Lol.. yes. I'm not sure why I created this ticket! Closing...
