### ISSUE TITLE
Upgrade k8s AWS load balancer controller and cert-manager deployments

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#643]
# Summary
In order to upgrade to Kubernetes 1.22, the following needs to be upgraded in the cluster:

- [**AWS load balancer controller**](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html)
Currently v2.0.0, needs to be v2.4.1.  

- [**cert-manager**](https://github.com/cert-manager/cert-manager)
Currently v1.0.2, needs to be at least v1.5.3.

This is required because of the [Kubernetes 1.22 deprecated APIs](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes). 

# Acceptance criteria
- [x] AWS load balancer controller manifest updated to v2.4.1
- [x] cert-manager manifest updated to at least 1.5.3

To validate the acceptance criteria:
```sh
# setup kubeconfig for the given environment
kubectl get deployment.apps/aws-load-balancer-controller -n kube-system -o yaml | grep v2.4.1
kubectl get deployment.apps/cert-manager -n cert-manager -o yaml | grep v1.5.5
```

# Related
- Blocks #555

**Comment by patheard** [comment]
# AWS load balancer controller
Action required:

- [v2.2.0](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0) 
New IAM Permissions needed
- [v2.3.0](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.3.0) 
Included yaml manifests use cert-manager apiversion v1. You need to update cert-manager to v1.5.3 or later
- [v2.4.1](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.4.1) 
If you don't use the [authentication via OIDC IDP feature](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#authentication) for any Ingresses in cluster, no action is needed.

# cert-manager
Action required:

- [v1.5.0](https://github.com/cert-manager/cert-manager/releases/tag/v1.5.0)
Note: cert-manager API versions v1alpha2, v1alpha3 and v1beta1 that were deprecated in 1.4 will no longer be served in 1.6. If your cert-manager deployment was created before 1.0 and/or any cert-manager resources were created using any of the deprecated APIs, please ensure the resources and CRDs are updated before upgrading to 1.6, see [the docs](https://cert-manager.io/docs/installation/upgrading/remove-deprecated-apis/).

**Comment by patheard** [comment]
The cert-manager upgrade will be done first but applying the following minor releases in order:
```sh
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.1.1/cert-manager.yaml
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.2.0/cert-manager.yaml
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.3.3/cert-manager.yaml
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.4.4/cert-manager.yaml
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.5.5/cert-manager.yaml
```

**Comment by patheard** [comment]
Staging cert-manager has now been upgraded to `v1.5.5`.

**Comment by patheard** [comment]
Production cert-manager upgraded to `v1.5.5` as well.

**Comment by patheard** [comment]
Research finished for upgrading the AWS load balancer controller and there is no clear guidance on an upgrade path apart from the [breaking changes listed in each release](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases).

These have been satisfied, so will attempt the Staging upgrade tonight using the [AWS installation guide](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html).

Revert plan will be to re-apply the existing AWS load balancer controller v2.0.0 manifest.

**Comment by patheard** [comment]
The following commands were used to update Staging's AWS load balancer controller:
```sh
# Download v2.4.1 manifest and update with cluster name
curl -Lo v2_4_1_full.yaml https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.4.1/v2_4_1_full.yaml
sed -i.bak -e 's|your-cluster-name|notification-canada-ca-staging-eks-cluster|' ./v2_4_1_full.yaml

# Update CRDs (https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller/crds)
# These are included in v2_4_1_full.yaml, but must be updated before applying the manifest
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"

# Apply v2.4.1
kubectl apply -f v2_4_1_full.yaml
```

**Comment by jimleroyer** [comment]
Jimmy to QA when meeting with Pat.

**Comment by jimleroyer** [comment]
Ran the commands in the QA steps and versions were displayed as advertised in the production environment.
