### ISSUE TITLE
Lambda API gateway does not use provisioned concurrency

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#646]
## Describe the bug 

The Lambda API uses provisioned concurrency to create execution environments that are always available to handle HTTP requests.  However, the API gateway integration with the Lambda API is using the function's `$LATEST` invocation ARN, which means the provisioned concurrency execution environments are never used.

As a result, users may experience slower responses as new `$LATEST` Lambda execution environments need to be cold started.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-4

## To Reproduce

1. Visit the Lambda API in Staging in Production using a browser.
1. Check the [ProvisionedConcurrentExecutions metric](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?ca-central-1&region=ca-central-1#metricsV2:graph=~(metrics~(~(~'AWS*2fLambda~'ProvisionedConcurrentExecutions~'FunctionName~'api-lambda))~period~3600~stat~'Maximum~region~'ca-central-1~start~'2022-03-02T01*3a00*3a00.000Z~end~'2022-05-09T17*3a23*3a00.000Z~view~'timeSeries~stacked~false);query=~'*7bAWS*2fLambda*2cFunctionName*7d;region=us-east-1;forwardXA=no).  No metric will be shown.  

## Expected behavior

The provisioned concurrency execution environments are used to process the API request.

## Impact

Impact on Notify users:
* Potentially slower response times for the Lambda as cold starts may be required for the `$LATEST` Lambda function code.

Impact on Notify:
* Added cost of provisioned concurrency that is not being used.

## Additional context
This can be fixed by updating the API gateway to integrate with the same Lambda alias used by the provisioned concurrency.

**Comment by yaelberger-commits** [comment]
Waiting on AWS support to reply to us

**Comment by patheard** [comment]
We made the change in #478 to have the API gateway invoke the same Lambda function alias as the provisioned concurrency, but we still see invocations of the `$LATEST` lambda function:

### API gateway proxy integration with `api-lambda:latest` alias
![image](https://user-images.githubusercontent.com/2110107/168601726-33cc7ac8-b0e1-465c-a01e-c8ff7554e137.png)

### CloudWatch log groups showing a mix of the function version 30 and `$LATEST` invocations
![image](https://user-images.githubusercontent.com/2110107/168601854-c661f275-b383-4cad-a7a8-aec57fb878b7.png)

There also aren't any [`ProvisionedConcurrencyExecutions` metrics](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#metricsV2:graph=~(metrics~(~(~'AWS*2fLambda~'ProvisionedConcurrentExecutions~'FunctionName~'api-lambda))~view~'timeSeries~stacked~false~region~'ca-central-1~start~'-PT168H~end~'P0D~stat~'Maximum~period~300);query=~'*7bAWS*2fLambda*2cFunctionName*7d*20provisionedconcurrentexecutions) as we would have expected after the change.

A follow-up with AWS support will be needed to get to the bottom of this.

**Comment by yaelberger-commits** [comment]
Meeting with AWS to discuss provisioned concurrency tentative for this afternoon

**Comment by yaelberger-commits** [comment]
Meeting with AWS to discuss provisioned concurrency tentative for this afternoon

**Comment by jimleroyer** [comment]
Pat and I had a meeting with AWS support. The session helped us fix the issue of the provisioned concurrency lambdas to not get called. The fixes were applied manually via the AWS console in the staging environment. The changes performed were to:

* Change the API gateway integration request configuration to target the lambda version from the default of $latest version to the latest alias (which targets the latest version -- subtle and confusing difference).
* Some permissions might have propagated from the previous change which we are not 100% sure which ones.

In terms of TF changes, we think this translates to the following changes:

* Define a qualifier attribute on our `aws_lambda_permission` resource, which is currently missing.

Defining a qualifier allows us to define a specific alias for the lambda to be called with, which is necessary to leverage to introduce the provisioned concurrency configuration. Also, the [qualifier documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_permission#qualifier) mentions that permissions should propagate following its presence:

>  qualifier - (Optional) Query parameter to specify function version or alias name. The permission will then apply to the specific qualified ARN e.g., arn:aws:lambda:aws-region:acct-id:function:function-name:2

**Comment by jimleroyer** [comment]
PR by Pat with these changes:
https://github.com/cds-snc/notification-terraform/pull/481/files

**Comment by yaelberger-commits** [comment]
Provisioned Concurrency does work in AWS dashboard
