### ISSUE TITLE
Update Notify package management

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#658]
# Description

We can backport some changes from GDS and their improved way of doing package management.

CDS documentation on patch management: https://github.com/cds-snc/platform-sre-security-support/wiki/Patch-management

Please look at this thread for discussion:
https://gcdigital.slack.com/archives/CV38DBNVA/p1652794882038499

GDS has introduced some improvements by using pip-tools and pyup that we can also replicate. These would allow for transitive dependencies traces.

There is also [poetry](https://python-poetry.org/) which could an option instead of pip-tools / pyup. To evaluate and consider.

# Acceptance Criteria

Explore in the ADR the following items:

- [x] ADR to see how our tools overlap or integrate and explore alternatives (likely pip-tools or poetry) to our `requirements-app.txt` / `make freeze-requirements` approach.
- [x] Move to Poetry.
- [x] Using Poetry to maintain upgrades and keep track of versioning automatically.
- [x] Check with @mohamed-cds on renovate and how we want to integrate. Don't do the integration now but lay out the future plan and cards necessary to make a migration from snyk to renovate.

# QA

- [x] The Notify API, admin, document-download API (and maybe utils) make use of the updated package management tooling.
- [x] A dependency bump was performed using the new tooling on each component.

# Additional Context

The current Notify setup makes use of a Make target named `freeze-requirements`. This is an in-house GDS target to resolve transitive dependencies based on an intake and desired list of dependencies. The intake currently sits as `requirements-app.txt` file while the resolved dependencies will get resolved as the `requirements.txt` file, sitting at the root of the project.

With the new changes in, the dependency intake would actually be in a [pyproject.toml file instead](https://python-poetry.org/docs/pyproject/) and the resolved dependencies are stored in the [poetry.lock](https://python-poetry.org/docs/basic-usage#installing-without-poetrylock) file.

The pyup tool most likely would not be adopted as we have similar tooling (Renovate) that detects vulnerabilities and automatically opens PRs with potential fixes and Renovate natively supports Poetry. We might want to check if that offers anything new... but also, this might conflict with new solutions being brought in by the SRE team (ask @mohamed-cds ).

The Poetry tool seems quite mature and we [instill best practices](https://python-poetry.org/docs/cli/#lock).

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/658?planning-poker) with ZenHub @andrewleith @iokpala @jimleroyer @jzbahrai @sastels

**Comment by jimleroyer** [comment]
@sastels and @andrewleith Are you OK if we move forward without an ADR and implement the suggestions listed in the acceptance criteria?

**Comment by andrewleith** [comment]
I agree!

**Comment by jimleroyer** [comment]
Sounds good then! @sastels and @andrewleith , if you can estimate on the issue then as-is, not for the ADR but the actual changes, it would be much appreciated. 🙏

**Comment by yaelberger-commits** [comment]
please also see link in description to CDS documentation for patch management

**Comment by mohamed-cds** [comment]
If you want to see the new patch management setup in action take a look at https://github.com/cds-snc/scan-websites/issues/322. This is a dashboard that the new tool "renovate" will maintain to help you keep track of what needs to be patched.

How to add it to you repo (my team can help):
1. Give the Renovate GitHub app permission on the repo; and
1. Submit a PR to the repo to add the [Renovate config](https://github.com/cds-snc/scan-files/blob/main/renovate.json).  This uses a [default config](https://github.com/cds-snc/renovate-config) that was setup for all of CDS.

Here’s the spot in the [GitHub app](https://github.com/organizations/cds-snc/settings/installations/25771251) that you add repos:
![image](https://user-images.githubusercontent.com/85885638/179232641-62cc2dbd-d7b2-4a0f-b1dc-767bfedc308d.png)

**Comment by andrewleith** [comment]
Just a note that we are meeting with SRE this week re:renovate which will hopefully take care of at least a portion of this work.

**Comment by patheard** [comment]
I did some research on Renovate's support for transitive dependency trace comments and it doesn't provide this.  However, it is able to consume a pip-compile `requirements.in` dependency file using the [following config](https://docs.renovatebot.com/modules/manager/pip-compile/#non-configured-filematch):
```javascript
{
  "pip-compile": {
    "fileMatch": ["(^|/)requirements\\.in$"]
  }
}
```

**Comment by yaelberger-commits** [comment]
Some overlap with Renovate dependency tracker

**Comment by whabanks** [comment]
I threw together a quick doc on [Pip-tools vs Poetry](https://docs.google.com/document/d/1f0Sv7NpgHFfYL-eTnIGW9FSxrdrdEXI1AnTzkt3PXi0/edit?usp=sharing) based on my findings thus far.

**Comment by yaelberger-commits** [comment]
Could also look into Renovate as well

**Comment by whabanks** [comment]
Regarding the question: `Can we leverage Renovate in place of Poetry / in conjunction with pip instead of moving to Poetry?`

Renovate has little to no overlap with package managers. It provides DevOps oriented tooling, that notifies us via PR's with suggested version updates for dependencies. 

Renovate does this by reading package files generated by package managers like `poetry`, `pip`, `pip-tools` or `npm` and searches `PyPi` to check if deps listed in the package file are out of date.

All this to say: Renovate cannot do what tools like pip or Poetry do for us and depends on the usage of a package manager in a project to fulfill its function. We can use these tools in conjunction with one another but neither is a replacement for the other.

**Comment by yaelberger-commits** [comment]
Small draft PR with Poetry for anyone who wants to play around with it

**Comment by whabanks** [comment]
Updated the [Pip-tools vs Poetry doc](https://docs.google.com/document/d/1f0Sv7NpgHFfYL-eTnIGW9FSxrdrdEXI1AnTzkt3PXi0/edit#heading=h.2mom37xvoehp) with some comparisons between migrating projects to both Pip-tools and Poetry. Added a short blurb on the level of risk associated with migrating to each tool.

**Comment by yaelberger-commits** [comment]
Andrew working today, did some work on github actions workflows from pip to poetry

**Comment by andrewleith** [comment]
- API is in a stable state; github actions now working; some makefile cleanup needed
- ADMIN is in progress
- DD-API is next

**Comment by andrewleith** [comment]
- Admin/dd-api/api are all using Poetry; github actions updated as well
- @whabanks working on utils today

**Comment by yaelberger-commits** [comment]
Document download API PR is ready to go
Utils API admin still some work to clean up, should be ready today for review

**Comment by smcmurtry** [comment]
- all PRs are up on each repo for the migration
- @jimleroyer reviewed the PR on API, will merge and test that one today before moving on to the others

**Comment by smcmurtry** [comment]
@whabanks could you add an update to this card?

**Comment by smcmurtry** [comment]
Yesterday successfully deployed Admin changes to staging. Hoping to get the notification-api changes deployed today.

**Comment by smcmurtry** [comment]
API ready for another test deployment to staging. Pat identified a compatibility issue with Renovate causing errors. Will troubleshooting that today.

**Comment by whabanks** [comment]
Moving to blocked: 
Renovate is currently broken for Admin and is expected to be broken in API as well. It looks like [until we can self host Renovate to increase the execution timeout](https://github.com/renovatebot/renovate/issues/10769) this issue will persist. This is just a soft block, other work such as deploying and testing API and Utils can still continue.

**Comment by smcmurtry** [comment]
Issues with the lambda API image, looks like we may need to self-host renovate to make it work with Poetry.

**Comment by sastels** [comment]
lambda api issues fixed, poetry PR merged to staging and tested.

**Comment by yaelberger-commits** [comment]
Relevant Slack thread for current state 
https://gcdigital.slack.com/archives/CV38DBNVA/p1677075866073539

**Comment by andrewleith** [comment]
- Still having issues 
- Looking to trying to self-host renovate to get around memory issues

**Comment by patheard** [comment]
The problem is that the `werkzeug` update to `2.2.3` is causing a dependency conflict since `notification-utils` is pinned to `werkzeug==2.2.2`.  This then triggers an infinite loop in Poetry:
- python-poetry/poetry#7398

I chatted with @whabanks and I'm going to submit a Renovate config change to ignore `werkzeug` updates to see if this is the only dependency conflict we're hitting.

Ideally there will be an upstream fix to Poetry that allows it to fail gracefully on conflicts.

**Comment by patheard** [comment]
After having `Werkzeug` ignored by Renovate, things are working again!
![image](https://user-images.githubusercontent.com/2110107/221651993-d0733609-d4f4-4a03-a1e0-7dfbe58008ed.png)

Until Poetry resolves the bug, we'll have to periodically check that Renovate is completing since unfortunately the `temporary-error` on the Renovate side does get surfaced so it's easy to miss that it's happening.

**Comment by andrewleith** [comment]
Great news!  

Will other package bumps that both admin and utils depend on lead to this situation?  There are several that the two projects have that need to stay in sync when doing dep bumps.

**Comment by patheard** [comment]
Yup, it's possible that we'll hit this problem with other products if you're using Poetry to manage the dependencies.
