### ISSUE TITLE
Update API documentation with updated limits of size and # for file attachments

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#659]
# Description

As a consumer of the Notify API, 
I need to know the constraints around the file attachments,
so that I can use it properly without any bad surprise.

## WHY are we building?

Updating our technical documentation to inform our users with Notify's limits.

## WHAT are we building?

Updating the technical documentation.

## VALUE created by our solution

Better informed users and less support tickets.

# Acceptance Criteria** (Definition of done) 

- [x] Update documentation with temporary restriction around overall size of an email notification.
- [x] Update documentation with allowed maximum number of file attachments in an email.
- [x] Content design reviewed the changes.
- [x] ~~Translation team~~ Phil reviewed the changes.

## QA Steps

- [x] Review the changed content under the [review app](https://cds-snc.github.io/notification-documentation/add-file-num-max-and-current-restriction/review-apps/7e49dc) and the [pull request changes](https://github.com/cds-snc/notification-documentation/pull/91).

**Comment by amazingphilippe** [comment]
With a lot of updates, we need to update docs with the new constraints. Some content design involvement? See how it affect the app?

**Comment by amazingphilippe** [comment]
Its about the one variable templates too.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/659?planning-poker) with ZenHub @jimleroyer @sastels @andrewleith @jzbahrai

**Comment by yaelberger-commits** [comment]
@jzbahrai @sastels @jimleroyer @andrewleith please add your estimates before Thursday

**Comment by jimleroyer** [comment]
I made a few changes to the documentation to include initial scope of this card, namely:

* updated limits of overall size of emails
* updated number of max attachments to an email

Head over to the review app link to preview and review:

* [Sending a file by email](https://cds-snc.github.io/notification-documentation/add-file-num-max-and-current-restriction/review-apps/7e49dc/en/send.html#sending-a-file-by-email)
* [Envoyer un fichier par courriel](https://cds-snc.github.io/notification-documentation/add-file-num-max-and-current-restriction/review-apps/7e49dc/fr/envoyer.html#envoyer-un-fichier-par-courriel)

**Comment by yaelberger-commits** [comment]
Left comments on the PR for a small typo fix

**Comment by adriannelee** [comment]
Steve and I to do QA today

**Comment by adriannelee** [comment]
QA'd by me!

**Comment by sastels** [comment]
LGTM too

**Comment by amazingphilippe** [comment]
Some minor suggestions in French. Considering this is already merged, we can choose to do them or not.

**Comment by amazingphilippe** [comment]
Changes appaer correctly on the documentation site. Closing now
