### ISSUE TITLE
manifest make diff-staging, make diff-prod can give wrong results

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#661]
make diff-staging is comparing the branch's encrypted secrets to those in `main`. If your `main` is out of date then you'll get incorrect results.

The problematic line is (for staging) here
https://github.com/cds-snc/notification-manifests/blob/main/Makefile#L21

```
	git cat-file blob main:env/staging/.env.zip.enc.aws > .previous.env.zip.enc.aws &&\
```
There should be a way to force it to go to GitHub, ie use `origin/main` or something.

**Comment by yaelberger-commits** [comment]
Can we just use origin/main?
Ensuring devs aren't breaking things they don't know about.
Ensuring local dev environments are in line with the latest version of what's in Github

**Comment by yaelberger-commits** [comment]
done, merged, deployed!
