### ISSUE TITLE
QA and things left to do for Priority Lanes before go live

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#662]
Here is a list of things to test before go-live:

- [x] Switch on `FF_PRIORITY_LANES` on staging
- [x]  Run a performance test on Staging
- [ ] Run a performance test with Steve's attic script that sends many notifications and few priority and see the performance
   -[ ]no notifications get lost (priority / normal / bulk)
   -[ ]priority ones are not stalled by bulk or normal
   -[ ] normal are not stalled by bulk
- [x] Remake the Queue Dashboard on Staging (and eventually prod)
- [x] Run 1 hr performance test in Staging

**Comment by sastels** [comment]
I think it would be useful to run a perf test for 10 minutes with:
- 2000 POSTS to /email per minute of bulk or normal messages (maybe half and half)
- 100 POSTS per minute of priority
where we capture the POST time in the reference and make sure that the priority ones are not delayed (we could run the priority on their own to get a baseline of best case performance)

We could turn off the FF and run the same test to see what affect the work has had on the times for priority messages

We can also use the POST time, created_at, sent_at and updated_at (after delivery) to get the times in each stage (redis / before sending / waiting for confirmation)
