### ISSUE TITLE
Update and improve "message delivery status" guidance page

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#663]
_Update and improve "message delivery status" guidance page_

## Description

As a Sender, I need to be able to find guidance about message delivery status and how the supression list so O can understand and track delivery of my messages. 

WHY are we building?
The current guidance page for message delivery status is buried and a bit hard to find once signed in. The language on the guidance page could be tighter and more clear

WHAT are we building?
Updated content and navigation for the message delivery status guidance page

VALUE created by our solution
Senders can more easily find and understand the guidance for message delivery status and can better track their message delivery.

Documents
- New Msg delivery status page in [EN](xhttps://docs.google.com/document/d/1o78rrx-x977yNypqIhagWUnihkoqVG1PtW2ZQ0P6Smo/edit#heading=h.e9n2oqpv3y6t) and [FR](https://docs.google.com/document/d/1o78rrx-x977yNypqIhagWUnihkoqVG1PtW2ZQ0P6Smo/edit#heading=h.e9n2oqpv3y6t)
- [Bounce rate release checklist](https://docs.google.com/document/d/1tlb9GfwM4Q_ES0c3JHayb8_8BqPwg1KOtP-znvvnjkw/edit#)

## Acceptance Criteria** (Definition of done) 

Given a Sender is new to Notify or has questions about message delivery status, when (they look for guidance when signed in, then they can find it easily and understand it clearly so they can track status. 

- [x] Msg delivery status page is presented at appropriate point (scoped out of release 1.0)
- [x] Msg delivery status page can be accessed from reports, when clicking  on linked status (mostly when failing)
- [x] Msg delivery status is linked to the new  "Guidance" page on bounce rate
- [x] Guidance content and content on Message delivery status page are aligned
- [x] Images and alt text are created or updated

## Publish checklist

- [ ] Bounce rate feature is released in production. Feature flag on.
- [x] Set WAF rules for new pages. (Descibed in the bounce rate release checklist)
- [x] Msg delivery status page update and supporting changes in other guidance pages are translated to FR
- [x] New Msg delivery status page entered or updated on GC Articles (no need to archive)
- [x] Give a heads up to the app-team channel once ready to publish
- [x] Clear the cache on staging, clear cloudfront cache in GCA as needed
- [x] Post new staging pages in Slack for last minute reviews. Time sensitive, production might or might not update. 

QA steps:

- [x] Check language toggle twice, from each language to the other
- [x] Scan for a11y and fix any found issues
- [ ] run the cypress GCA tests

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/663?planning-poker) with ZenHub @adriannelee @amazingphilippe @YedidaZalik

**Comment by adriannelee** [comment]
@yaelberger-commits it looks like an estimate was accidentally set? I can't add an estimate :)

**Comment by yaelberger-commits** [comment]
@adriannelee hopefully you can add an estimate now! Thanks for flagging

**Comment by YedidaZalik** [comment]
Need to determine if needs  content on file attachments.

**Comment by yaelberger-commits** [comment]
Do we need to include the error message for virus found in file attachment here?

**Comment by YedidaZalik** [comment]
Current error message
EN: Attachment has virus
FR: La pièce jointe contient un virus

**Comment by yaelberger-commits** [comment]
In Translation

**Comment by YedidaZalik** [comment]
Translation is done but after conferring with Marie-Sophie, they will return it next week along with the Figma translation in order to ensure French content is consistent across Guidance/Msg Delivery Status pages and Figma screens.

**Comment by amazingphilippe** [comment]
@andrewleith setting up WAF rules

**Comment by yaelberger-commits** [comment]
Consider unlinking in some places while we A/B test
