### ISSUE TITLE
Observability of Notify

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#664]
# What we want to track

We should be able to answer the following questions under a few minutes after this epic has been done:

1. How much time in average notifications took to get sent for a time period, from reception to actual sending.
1. How much time in average notifications took to get sent for a time period using a specific priority lane, from reception to actual sending.
1. How much time in average notifications took in the different Notify stages (ack / saving / sending) for a time period using a specific priority lane, from reception to actual sending.

# What we want to automate

* Have automated dashboard creations in both staging and production environments defined in Terraform.

# Links
https://airtable.com/invite/l?inviteId=invNLE0xudbdxQLbV&inviteToken=8ba88888b46476[…]email&utm_source=product_team&utm_content=transactional-alerts

Observability board: https://miro.com/app/board/uXjVOwDTC5o=/
Observability notes:
https://docs.google.com/document/d/1Ey8iP8IFw7FSTT4uhrk8LxUbSG_gmUeRCCKu1UIVt-I/edit#heading=h.31ju8fb2w29h

**Comment by yaelberger-commits** [comment]
I like this epic very much!

**Comment by yaelberger-commits** [comment]
@jimleroyer do we now have queries for all these things in Blazer or elsewhere? I think we can close this Epic and it just becomes part of our ways of working!

**Comment by jimleroyer** [comment]
Yeah, we can say we have what we want from Blazer. I was imagining more of a dashboard within GCNotify admin, easy to access for all. But at least the questions defined in this card are covered at the moment.
