### ISSUE TITLE
Put messages before CTA buttons

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#665]
(screen readers will not read the text after the CTA button if the person clicks on the Call-to-Action button)

- Need to find the places where this happens

Found this issue on the Upload a Spreadsheet screen and resolved it. We need to see if there are other places where this happens.

Look into if it's an issue:
- When they create template and they see a CTA to add recipients, they might not go to the elements below the CTA. The elements below the CTA are helping the user review their template before they send. Not sure if this is as bad the Upload a Spreadsheet example
- Upload your own custom branding (after service creation)

**Comment by amazingphilippe** [comment]
Can we add a bit more details or screenshots to know where this is happening?

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/665?planning-poker) with Zenhub @amazingphilippe @YedidaZalik

**Comment by andrewleith** [comment]
Pretty sure we already did this.  I'll scan through the UI and see if there are any more instances of it.

**Comment by andrewleith** [comment]
There is an instance of this on the branding pages, but they are coded in such a way that this is not a problem (the message is actually first in the markup, button second):
![image](https://github.com/user-attachments/assets/ebeab9bb-5d45-4935-8669-c3649d33d343)

**Comment by andrewleith** [comment]
- Couldnt find any more instances of this issue.
