### ISSUE TITLE
Add alarm to detect too many expired inflights

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#668]
We should add alarms to detect if there have been too many expired inflights.

We had a situation on staging where an inflight was being expired every 6 minutes for a week before we noticed it.

A recent check on prod found 6 expired inflights in the past week, so they should be infrequent under normal circumstances.

- [x] Check if we have this alarm already
- [x] We already collect the data when we expire an inflight, so should be a quick job to add an alarm

**High priority to check if we have the alarm, then assess priority of adding it if needed**

**Comment by yaelberger-commits** [comment]
We have a metric but not alarm

**Comment by sastels** [comment]
We can wait till Jumana is back to merge and finish this off
