### ISSUE TITLE
One time snapshot of how many notifications (emails and SMS) we send each day over time

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#670]
_One time snapshot of how many notifications (emails and SMS) we send each day over time_

## Description

As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Acceptance Criteria** (Definition of done) 
- [x] SQL query to run
- [x] Go back as far as a year or further

_To be refined through discussion with the team_

- [x] Snapshot of what daily notifications looks like

Given some context, when (X) action occurs, then (Y) outcome is achieved

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/670?planning-poker) with ZenHub @andrewleith @ikenna-cds @jimleroyer @jzbahrai @sastels

**Comment by jimleroyer** [comment]
Do you need a breakdown by SMS and emails? I can upload a CSV version of it as well.

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/5a2f7da6-d5f2-4706-bdab-ac86fb75efa3)

**Comment by jimleroyer** [comment]
Opened a PR with that new graph. I can change the graph based on feedback:
https://github.com/cds-snc/notification-attic/pull/16

**Comment by jimleroyer** [comment]
Slight variation with stack bar chart of SMS (in blue) and emails (in red):

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/af2e0b1d-415b-4abf-b297-f01d72efa66b)

**Comment by yaelberger-commits** [comment]
This works for me! @josh-cds adding you in for a review to see if this meets our needs.
