### ISSUE TITLE
Add "search by uuid" to admin panel

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#672]
When we find a service / template / notification uuid in the logs it's an annoying process to look at it in the app. It usually involves going to one of our own services, etc and then cut and pasting the new value in. For a notification or template we also need to do a hasura query to find the related service. 

Instead we could add a "search by uuid" to the admin panel which would have a form to enter a uuid, then do a new call to api which would return the related data. admin could then show the data and provide links to the entity.

A prototype of the new api endpoint was created a while ago https://github.com/cds-snc/notification-api/pull/1377

**Comment by yaelberger-commits** [comment]
@sastels seems like you completed this work! Thanks for sharing it at Demo
