### ISSUE TITLE
Add dashboards for priority queues to production

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#676]
Essentially, copy over the ones we've done on staging.

Note that we need to have the priority lanes code running on production first so that we have metric data to add to the dashboards.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/676?planning-poker) with ZenHub @andrewleith @ikenna-cds @jimleroyer @jzbahrai @sastels
