### ISSUE TITLE
Support spreadsheet creation in both official languages

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#677]
As a Notify user, I need to be able to upload a spreadsheet for sending to many recipients with french column headers, so that I don't have to work in English or translate my spreadsheet when I usually work in french, and so that I don't get an error message if I upload a french spreadsheet.

## Description

As a Francophone user, I need to be able to upload a French-only spreadsheet so that I can send messages to many users. 

WHY are we building?
Accessibility for Francophone users
Compliance with official languages legislation
WHAT are we building?
Capability to upload spreadsheets that are completely in French, including the column headers
VALUE created by our solution
Usability and accessibility
Goodwill from Francophone and bilingual PTs and users

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given a Francophone user of Notify needs to send using a spreadsheet, when they upload a spreadsheet with all French content (including column headers), Notify is able to populate templates and send messages

When the Notify UI is set to FR, I want the examples to be in FR, so I can download a FR spreadsheet with the mandatory headers (email or phone number) in FR. 

Dev Work:
- [ ] Sample spreadsheet should be in EN or FR depending on user preference
- [ ] User can upload spreadsheet in either EN or FR depending on user preference

# QA Steps:
### User preference is EN 
- [ ] can send an EMAIL spreadsheet with an EN heading
- [ ] can send an EMAIL spreadsheet with an FR heading
- [ ] can send a SMS spreadsheet with an EN heading
- [ ] can send a SMS spreadsheet with an FR heading
- [ ] send an email without the correct heading - error message should be the EN heading
- [ ] send an SMS without the correct heading - error message should be the EN heading

### User preference is FR
- [ ] can send an EMAIL spreadsheet with an EN heading
- [ ] can  send an EMAIL spreadsheet with an FR heading
- [ ] can send a SMS spreadsheet with an EN heading
- [ ] can send a SMS spreadsheet with an FR heading
- [ ] send an email without the correct heading - error message should be the FR heading
- [ ] send an SMS without the correct heading - error message should be the FR heading

### Other
- [ ] Verify with policy team and Platform BU what the policy is for OL with regards to these elements

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Measuring success and metrics

## QA Steps

- [ ] When in the french UI, follow flow to send to many, and download the sample spreadsheet. The headers should appear in french
- [ ] When uploading a spreadsheet with french headers, the spreadsheet is uploaded successfully and the messages send successfully

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/677?planning-poker) with ZenHub @amazingphilippe @YedidaZalik @andrewleith

**Comment by yaelberger-commits** [comment]
Need to track down frontend places where it would have to be changed to validate and accept en and fr, not a heavy lift

**Comment by yaelberger-commits** [comment]
We already have content in English. We can involve Marie-Sophie when needed, or use existing translations if they are a 1:1 match

**Comment by yaelberger-commits** [comment]
The Official Languages Act says that English and French are the languages of work in institutions and that employees have the right to use either official language in accordance with Part V of the OLA. The Directive on Official Languages for People Management also says that managers and supervisors are responsible for: 6.1.1 (Work instruments) Providing employees in bilingual regions with regularly and widely-used work instruments and electronic systems (work instruments) in both official languages.
So by making spreadsheets available in both French and English in Notify supports our users' choice to use either OL, and their managers in meeting these obligations.

**Comment by jzbahrai** [comment]
I am still working on the example spreadsheet creation. I will update this ticket when that is ready.

**Comment by adriannelee** [comment]
Jumana got most of it done, Andrew tested it, huge portion still needs work.
