### ISSUE TITLE
https://notification.canada.ca/, Exclamation mark after Contact us" footer (English only)

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#682]
On the production site, there’s an exclamation marks after  "Contact us" (just in English)

![Screen Shot 2022-06-02 at 11.02.30 AM.png](https://images.zenhubusercontent.com/614b9f22b18cf806c628a310/05af438f-5337-4c7d-a8dc-5b1951d03707)

## Potential fix

- What change could fix this issue?
- What nuggets of information could help us fix the issue

## Resources

- Links to documentation or articles that could be helpful
- examples: WCAG docs, ARIA docis, web.dev, Deque, Webaim...

**Comment by andrewleith** [comment]
Menu items was incorrectly named in English.  Fixed using our new GC Articles integration!

If anyone is curious, the steps to make these types of changes are outlined here: https://www.notion.so/canadiandigitalservice/GC-Articles-and-GC-Notify-integration-20f14759ced94fd987afd7fd65b943db#8ba1467f26554196b95df4880ed81de6
