### ISSUE TITLE
Celery workers losing current notification processing when shutting down on release deployments

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#688]
# Description

As a developer, 
I need to be able to make a release without affecting notifications during releases
so that I can achieve continuous deployment without much hassle. 

As a sender of notifications,
I want to send all of my notifications right away,
so that I can trust a reliable notification service
and not wait hours to get these delivered.

SEV-2

## WHY are we building?

Have a reliable Notify service that can withstand releases without interrupting notifications.

## WHAT are we building?

Either, partially or all of a) a graceful recovery mechanism for celery works shutdown, b) a Celery system that can retry failed task on workers shutdown and/or c) a reworked recovery notifications from the created notifications that happens earlier than 4h mark.

## VALUE created by our solution

A more reliable Notify experience and capacity to release often without much impact.

# Acceptance Criteria** (Definition of done) 

This will depend on the picked solution. [GDS picked option A](https://gcdigital.slack.com/archives/C02HV53PBC4/p1654527510493769?thread_ts=1654526110.833079&cid=C02HV53PBC4), wondered about B but did not attempt and not doing C.

Given some context, when (X) action occurs, then (Y) outcome is achieved 

# QA Steps

- [x] Deploy in a given environment and check the logs for a gracious stop that don't immediately (within ms) stop but rather waits a bit, potentially a few seconds up to 10.

# Additional notes

From Leo Hemsted from GDS:

> we send a TERM, then wait up to 10 secs for celery to finish gracefully before sending a KILL. think this catches most things, when the main celery process gets a term it stops ingesting and just finishes the tasks it’s grabbed recently.
> we decided agains tacks_late (and got scared off by the warnings on task_reject_on_worker_lost) due to awkward conflicts with visibility timeouts, especially with longer running tasks
> https://github.com/alphagov/notifications-api/blob/master/scripts/run_app_paas.sh#L43-L59
> https://github.com/alphagov/notifications-api/blob/master/scripts/run_multi_worker_app_paas.sh#L44-L59

**Comment by yaelberger-commits** [comment]
Thanks @jimleroyer this user story is very clear. 
I will pull to the top of the Product Backlog as discussed at our meeting with the dev team. 
CC @josh-cds for line of sight, this bug has been ongoing for some time but became more apparent during the recent release of Priority Lanes. Plan to bring it in to the next sprint, after Baselining

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/688?planning-poker) with ZenHub @andrewleith @ikenna-cds @jimleroyer @jzbahrai @sastels

**Comment by yaelberger-commits** [comment]
@jimleroyer Should we timebox this as an investigation to decide which of the above options to take?

**Comment by yaelberger-commits** [comment]
Jumana working on it and exploring what others do in this scenario

**Comment by YedidaZalik** [comment]
Good progress on Thursday.  Possible issue with deployment to Kubernetes - @jzbahrai did another deployment on Thursday night, but still doing more.

**Comment by YedidaZalik** [comment]
@jzbahrai made good progress, now working on Kubernetes to confirm if actually working
Will keep working on it 
Will discuss with @sastels

**Comment by YedidaZalik** [comment]
work in progress 
would like to test reliably but difficult - following GDS solution but it may not work

**Comment by YedidaZalik** [comment]
@jzbahrai will demo today
Not merged yet

**Comment by YedidaZalik** [comment]
@jimleroyer will review

**Comment by adriannelee** [comment]
Next time we do a prod release, we'll check if the new behaviour is there. We need the traffic to check.

Whoever is deploying can QA

**Comment by sastels** [comment]
We did a release on Oct 25 - we can check the logs to see if they look ok.

**Comment by adriannelee** [comment]
@sastels and @jzbahrai will check the logs, but probably tomorrow.

**Comment by adriannelee** [comment]
@jzbahrai will pair with whoever is releasing today (@jimleroyer ?)

**Comment by jimleroyer** [comment]
The QA tests are good. 👍

I checked the Celery logs when the release happened on November 1, ~11h38 EST using this query:

```
fields @timestamp, log, kubernetes.labels.app as app, kubernetes.pod_name as pod_name, @logStream
| filter kubernetes.labels.app like /^celery/
| filter @message like /shutdown/
| sort @timestamp desc
| limit 100
```

I observed the following for the 4 pods that were up and running:

[Pod 1 logs](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Fcontainerinsights$252Fnotification-canada-ca-production-eks-cluster$252Fapplication/log-events/celery-696dcc4497-g2p56_notification-canada-ca_celery-202169b71099cedca713ccf299d2ab8f5d7914781a3e4a57deaa69162dd01a23$3Fstart$3D2022-11-01T15$253A37$253A57.079Z)
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/886b7099-e9a0-4714-bf4d-61c46953489e)

[Pod 2 logs](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Fcontainerinsights$252Fnotification-canada-ca-production-eks-cluster$252Fapplication/log-events/celery-696dcc4497-r8bsx_notification-canada-ca_celery-9f1614592e70bf5db0f6d4f7347af46934ab5efdcf442d7d5a9cd6b7bfc16d7c$3Fstart$3D2022-11-01T15$253A32$253A11.937Z)
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/c476c544-3846-457a-801f-aa9ec6c3ced4)

[Pod 3 logs](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Fcontainerinsights$252Fnotification-canada-ca-production-eks-cluster$252Fapplication/log-events/celery-696dcc4497-gf4zl_notification-canada-ca_celery-668f2496ea66c2e50e3710e359bc3c5ca1203a3e51bbce34a3316136526a5033$3Fstart$3D2022-11-01T15$253A37$253A53.955Z)
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/6b74d421-1b50-498b-be26-4570dcb4559d)

[Pod 4 logs](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Fcontainerinsights$252Fnotification-canada-ca-production-eks-cluster$252Fapplication/log-events/celery-696dcc4497-8k7cs_notification-canada-ca_celery-7e28995ff03b6d42a18fa85339d04f227e41457e27ce97580f94b3bfc90568e0$3Fstart$3D2022-11-01T15$253A38$253A02.858Z)
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/8b39a1df-39a2-4c51-b36a-115cc7c3002a)

This shows the expected behavior where the main Celery process receives a warm shutdown and in the following seconds, which usually ranges between 1 to 8 seconds, the Celery workers shutdown. Contrary to before behavior, these don't shutdown immediately as before but actually takes proper time to graciously stop. This is what we want.

**Comment by andrewleith** [comment]
Nice work, @jzbahrai! 🎉
