### ISSUE TITLE
Order a short code

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#69]
Must be submitted by Oct 28

### Task Description

This will allow us to get past several technical limitations with SMS sending such as the limit per second and establishing more trust from our users.  Sync with @bryanmwilley as we might just have to copy/paste the request he made last year, except for one additional modification to satisfy a missing policy that got our demand rejected last year.

### Task Outcome

* Decision on either ordering a short code or not.
* Potentially a short code!

### Acceptance Criteria

- [x] [ADR that describes context](https://github.com/cds-snc/notification-adr/pull/4), decision and the workflow if we do go forward with a short code.
- [x] Paperwork for getting a short code filled and sent, if we go forward.

### Additional Notes

We met with the AWS team to know more about short codes in Canada. They were confident we could order one if we pass as the government of Canada organization with clearly identified header/footer. 

```
- 1:1 meeting with AWS support on short codes
	- Described our use case to the AWS experts.
	- **Shared** short code is not well seen usually either in US or Canada.
	- One short code per service would be the Canadian legal option.
	- We could offer special service for specific governmental departments that really want and need a short code, ready to pay for the option. They would have to go the same route anyway on their own, but leveraging our platform doing so would be at their advantage.
	- Have not heard of a 10 DLC option in Canada yet but most probably the Canadian carriers will follow through in long term.
	- We probably use dedicated numbers in us-west-2 because we can't use both dedicated long codes and random pool in the same region. The random pool of numbers is a default option for when there are no available numbers to use. Hence we use **us-west-2** for dedicated long codes and **ca-central-1** where we have no long code for the random pool.
	- We could get a **toll free number** that can do 3 SMS / seconds.
		- Slightly more expensive than a long code: 2$ US dollar / month.
		- Not officially supported on AWS but we can ask for it with some special support request. **Contact Brent Breyer who can do it for us** if we go this way.
		- These would need to be in a different region than the pool of random numbers.
	- Can we use 10 DLC in the USA to call into Canada?
		- Unfortunately these can only be sent to a US code recipient.
	- Short code application **should be done before 28th October** as this is the start of a cutoff period until the new year to process all requests.
	- Short code application could be filed under the Government of Canada organisation per AWS expert. The templates we need to fill in with the registration could be examples of the services that would send at high volume, the ones we'd see the most. A tricky part for multi-usage short code is when one send promotional SMS but that should not apply to messages sent by Notify. We should also clearly identify that this is a text from the Government of Canada in our header or/and footer to add credibility to our request and messages.
```

#### From Bryan

Here is the paper work from the last time I did it https://docs.google.com/document/d/1IbBHE_hDtXmV03FJFeB5wRWUekzmEP4Ky2x0a_lDBtg/edit

I had to open a ticket with AWS support to request the short code. I think they cost like $5000/year? I don't know check with AWS.

Phone numbers (long codes) are 7 to 10 digits. Short codes are 3-6
We tried to get the 6 digits that would make CANADA but it was taken by Citibank.

Think of the 6 digits you want first and look them up to see if they aren't taken.

Ideas from the last time:
WINNER = CAN(226)
Others:
GCGCGC
CANCAN
GOVCAN
CANGOV
FEDCAN
GCNOTE
GCTEXT
TEXTGC
OTTAWA
GCSMS
CDSSNC

**Comment by yaelberger-commits** [comment]
Received back another round of edits from AWS. Yael will review and resubmit

**Comment by yaelberger-commits** [comment]
Final application version resubmitted Dec 2, 2021 back to AWS
