### ISSUE TITLE
Create Baseline Notify ADR

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#691]
Create an ADR and gather the data so we can decide what form baselining should take.

Work in progress: https://github.com/cds-snc/notification-adr/pull/22

Also: https://docs.google.com/spreadsheets/d/1cJjCzqC9JOAq005jWg9OjmeYoQvLkPaAFkCaIZTcaWA

**Comment by yaelberger-commits** [comment]
@sastels can you please link to the ADR here? Thanks

**Comment by amazingphilippe** [comment]
Looking at measuring the  SLOs. We've done all that. May not need an ADR anymore. Let Josh and Yael take a look at it. Steve will point to the right document.

**Comment by amazingphilippe** [comment]
Do we need to rescope this card to include Observability.

Observability tasks: https://airtable.com/apptAu30Pui5vTaj6/tblLtDEQdSvg7Szgm/viwsJ2cNCaPYfHjyl?blocks=hide

**Comment by yaelberger-commits** [comment]
@andrewleith here is the baseline ADR where we would write the tests that would run nightly
