### ISSUE TITLE
Run new baseline tests automatically

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#693]
One we have written the new baseline tests, replace the current nightly automated tests with the new ones.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/693?planning-poker) with Zenhub @andrewleith @jimleroyer @jzbahrai @sastels @smcmurtry @whabanks

**Comment by yaelberger-commits** [comment]
@andrewleith I think this is just to run them nightly. We reference writing an ADR in another card, so I think writing the tests is (or should be) another task
