### ISSUE TITLE
Numeric characters with dots in an email template converts into bulleted lists

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#694]
## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-3 - Affecting 1 user that we know of so far through support ticket 

## To Reproduce

1. Go to GC Notify, log in, create email template
2. In the email template, add numbers with dots 07.02
3. Preview or save template
4. See 07.02 as * 1. 02

## Expected behavior

When creating an email template, and adding numbers with dots, we would expect to see the numbers rendered as 07.02, not as a bulleted list

## Impact

So far, just one user is unable to format their [email template ](https://notification.canada.ca/services/44a54d55-19ac-4a10-bce1-c35ca8ab9a26/templates/7e8f7411-1152-4585-b208-ac8b2920eee0)correctly with numbers with dots. They sent a support ticket.

https://cds-snc.freshdesk.com/a/tickets/9265

If applicable

Impact on Notify users: One Sender so far having issues where their numbers with dots are getting rendered as bulleted lists. So far only in trial mode

Impact on Recipients: Recipients would receive confusing and poorly formatted emails. Not being sent to real recipients yet, this service is only in trial mode

Impact on Notify team: Some time spent investigating, with a dev to test

## Screenshots

![Screen Shot 2022-06-08 at 9.44.35 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/68a60916-e8ed-4742-9181-520d07647ebf)

![Screen Shot 2022-06-08 at 9.44.08 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/c4f455d7-e479-41b7-aaf9-c32fa59c9ce6)

## Additional context

We use regex for templates. We need a better markdown parsing or rich text editor.

**Comment by andrewleith** [comment]
As a workaround, you should be able to use the following to get the desired output:

```
07\.02
100\.09\.007
123\.456\.789
```

**Comment by jimleroyer** [comment]
Opened a PR to fix this specific issue:
https://github.com/cds-snc/notification-utils/pull/185

Unfortunately during my tests, there are many other issues with Markdown lists format that I uncovered. I attached a few examples on the pull requests previously mentioned. 

I would advise to create follow task(s) to track these bugs. There are many. We could reset the many customizations we have for Markdown support in our utils package and rather align ourselves with the latest mistune library development (with no special customizations) to have a more stable support of Markdown.

**Comment by YedidaZalik** [comment]
It will be merged and then moved.
Assigning to @jzbahrai

**Comment by jimleroyer** [comment]
@amazingphilippe and I had a meeting to explain current versus future concerns for ordered/unordered list markdown support in GCNotify, and talked of current scope for this very issue to fix though.

**Comment by YedidaZalik** [comment]
Phil & Jimmy met to prep Phil to test. He'll be testing today to check if issue fixed.
Once QA'd, let client in Freshdesk know.

**Comment by YedidaZalik** [comment]
Fix works so Jimmy will merge 
Phil reminded him yesterday and he'll do it today

**Comment by jimleroyer** [comment]
This is currently deployed in staging. Ready to be deployed in production in next release cycle.

**Comment by amazingphilippe** [comment]
@smcmurtry Will QA one last time in production before sending update to client.

**Comment by smcmurtry** [comment]
Looks like the reported issue is fixed! ![Screenshot 2023-05-01 at 2.01.44 PM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/12aa128f-d342-405d-8f8a-fb92d932c326)

**Comment by yaelberger-commits** [comment]
@amazingphilippe we're ready to update the client and ask them to test as well on their end!
