### ISSUE TITLE
Lightweight cost recovery projections for TBS

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#696]
_Lightweight cost recovery projections for TBS_

## Description

As TBS Finance, I need some general estimates of how much money CDS might get through cost recovery from clients of GC Notify based on current services going over limits and projected services that might go over limits in the future, so that I can advise and help develop an MOU and billing process for GC Notify and determine if an MOU process is worthwhile. 

WHY are we building?
WHAT are we building?
https://docs.google.com/spreadsheets/d/13w_PJRNe-n8kBy9g81jKhuI5FlFFivZ9DZEG-5-zxzc/edit#gid=0
https://docs.google.com/document/d/1h8hRpGXZeVAAaSwtaUN5nhWjD6v1Nc9CGjNTELjovxU/edit#heading=h.2fyqkih69sy9
VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
@sharlychan-cds @josh-cds I think we can consider this done. The numbers that Sharly has documented can give TBS an idea of projections for this year as an example.

**Comment by sharlychan-cds** [comment]
Document completed friday with rough estimates, slack channel updated, numbers given to finance!
