### ISSUE TITLE
Going to a template preview page directly causes server error

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#701]
## Describe the bug 

Going to a template preview page directly (ie without coming from the edit page) causes a 500 server error on admin.
This is likely because the required redis data isn't there.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-3 - basically an annoyance

## To Reproduce

1. Go to one of your templates
2. add "/preview" to the end of the url and hit return
3. see the error page.

## Expected behavior

We should discuss this. Possibly redirect back to the template edit page.

## Impact

Can confuse users and cause Notify warnings and alerts.

**Comment by jimleroyer** [comment]
It would be good to build some stats on how often this triggers an alarm/warning in our ops channel to determine priority.

**Comment by andrewleith** [comment]
This issue occurred 14 times so far in June, which (based on my understanding of the alarm) means 14 alarms.

**Comment by smcmurtry** [comment]
This bug does not only occur when you visit the url directly. For me it occurs when I click the "Preview" button: https://youtu.be/EkV8S_e9mDo

**Comment by yaelberger-commits** [comment]
Low hanging fruit

**Comment by andrewleith** [comment]
@sastels will review

**Comment by andrewleith** [comment]
@Pensai to QA

**Comment by Pensai** [comment]
Reviewed both locally and in prod. 
- Can navigate to templates and add `/preview` to the url without a 500 error. 
- Can directly navigate to  `/services/<id>/templates/<id>/preview` from the Dashboard without error.
- `Back`, `Edit` and `Save` buttons work as expected when manually navigating to the preview URL
