### ISSUE TITLE
Redirects cause server error

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#703]
## Describe the bug 

Some redirects are causing a server error on admin.

The redirects were added [in this pr](https://github.com/cds-snc/notification-admin/pull/763/files#diff-ca6770bf7f2bb0d7862e7bc54fdf76185874e504c0582b2b26795d33c8b91649R334-R343):

### Broken redirects
 - https://staging.notification.cdssandbox.xyz/features/templates
 - https://staging.notification.cdssandbox.xyz/features/security
 - https://staging.notification.cdssandbox.xyz/features/terms
 - https://staging.notification.cdssandbox.xyz/features/messages-status
 - https://staging.notification.cdssandbox.xyz/templates

### Working redirects
 - https://staging.notification.cdssandbox.xyz/features/roadmap
 - https://staging.notification.cdssandbox.xyz/features/email
 - https://staging.notification.cdssandbox.xyz/features/sms
 - https://staging.notification.cdssandbox.xyz/features/letters

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-4 - no user data affected

## To Reproduce

1. Go to 'https://staging.notification.cdssandbox.xyz/features/security'

## Expected behavior

Redirects to security page

## Impact

- Server errors can lead to distrust of Notify
- This would mostly be a problem for someone who has bookmarked these old URLs

## Acceptance Criteria:

- [x] Figure out if these redirects are needed.
- [x] Having working redirects for the broken links
- [x] Ensuring the redirects are bi-lingual

## Additional context

redirect is here
https://github.com/cds-snc/notification-admin/blob/main/app/main/views/index.py#L313

Some of the others work while some do not.

This could be related to our move to GCArticles/renaming the URLs

**Comment by andrewleith** [comment]
The way these redirects work depend on having an actual route in the application, so that is why the GCA ones in particular no longer work.  We need to decide if we want to fix these, or just get rid of them altogether.

**Comment by andrewleith** [comment]
41 of these errors so far in June, most coming from bots/web crawlers, but still some (14) from actual users.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/703?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by yaelberger-commits** [comment]
Timeboxed investigation 1-2 days to figure out fix

**Comment by sastels** [comment]
can talk to Max or Brian, the OG Notify folks about why these redirects are there. Can also go look at the PR that added the redirects and see if there's info there.

**Comment by sastels** [comment]
Checked out on prod, no server errors now. This should reduce the clutter on #notification-ops  :tada:
