### ISSUE TITLE
Gather SLO data

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#705]
## Description

As a Notify service owner, I need to be able to evaluate Notify performance so that I can make product decisions. 

Compute all the metrics in our SLO based on historical production data.

## Acceptance Criteria** (Definition of done) 

- [x] compute all SLO metrics

## QA Steps

- [x] Is this what Yael and Josh need?

**Comment by sastels** [comment]
see
https://docs.google.com/spreadsheets/d/1cJjCzqC9JOAq005jWg9OjmeYoQvLkPaAFkCaIZTcaWA

**Comment by yaelberger-commits** [comment]
Thank you! cc @josh-cds
