### ISSUE TITLE
Offboarding a team member

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#706]
# Description 

Here are some tasks to go through and access that needs to be revoked as you offboard from the Notify team.

Present checklist is here to help us track progress and completion of this.

**Done when** :  PM has checked that all access has been revoked and all documentation, respsonsibilities have been transferred 

#  Transfer files and meetings 

No meetings or files to be transferred.

# Meetings and handoff

~~- [ ] Meet with PM to go over offboarding checklist~~
~~- [ ] Meet with incoming team member, if applicable, for handover~~

# Revoke access

- [x] Remove Slack channel access [DM or PM]
- [X] Remove Google Drive access [DM or PM]
- [x] Remove Figma access [Designer @amazingphilippe ]
- [x] Remove platform admin access [Dev lead contact: @jimleroyer ]
- [x] Remove GitHub Access [Contact: Slack #sre-and-tech-ops]. Request to be removed from GitHub teams as well
- [x] Remove Zenhub Access [Contact: PM]

# Revoke access for Dev  ⌨️

- [X] LastPass and shared Notify folders inside of it (Staging and prod credentials, environment variables for running the repo locally) [**Contact**: @jimleroyer ]
- [ ] ~Snyk (Dependency management) [ #zendesk-it-support or /zendesk Slack command ]~
- [x] Sentry (Error logging / debugging for staging) [ #zendesk-it-support or /zendesk Slack command ]
- [X] AWS (staging and production accounts) Error log monitoring ; S3 buckets for asset management [ #zendesk-it-support or /zendesk Slack command ]
- [x] New Relic (Error logging / debugging for production) [ #zendesk-it-support or /zendesk Slack command ]
- [x] Freshdesk Customer ticket support portal [ #zendesk-it-support or /zendesk Slack command ]
- [ ] ~Remove from notifications-ops on Google~
- [x] Remove platform admin access [Dev lead contact: @jimleroyer ]
- [x] Easy Retro **[Contact: Mario]**
- [x] Heroku

**Comment by jimleroyer** [comment]
- [X] Remove from [g/notification-devs](https://groups.google.com/a/cds-snc.ca/g/notification-devs/members)
- [ ] Remove from [notification group](https://groups.google.com/a/cds-snc.ca/g/notification/members)

**Comment by yaelberger-commits** [comment]
We'll need to file a request to remove access with IT support

**Comment by jimleroyer** [comment]
@yaelberger-commits I think the Zenhub access should have been removed by now, as I check the access permissions on the github [access page over there](https://github.com/cds-snc/notification-planning/settings/access).

**Comment by yaelberger-commits** [comment]
I created a Zendesk ticket to remove Freshdesk access

**Comment by jimleroyer** [comment]
@yaelberger-commits I asked Ramya to remove Freshdesk access and it was done. 👍

**Comment by jimleroyer** [comment]
Moved the card to review, as I think most items have been addressed, but we might want to double check for zenhub permissions with @yaelberger-commits just to make sure.

**Comment by yaelberger-commits** [comment]
Yup I can confirm Wissam removed Zenhub permissions
