### ISSUE TITLE
Update SLO document

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#709]
# Description

As a user of Notify,
I need to know what the SLOs of the service are,
So that I can level my expectations
and hit the system within defined constraints.

## WHY are we building?

To tell users what are the constraints of Notify system, to level expectations but also to prevent users from overflowing our service, hence stability and trust.

## WHAT are we building?

Review current baseline values and update [our SLO document](https://docs.google.com/spreadsheets/d/1cJjCzqC9JOAq005jWg9OjmeYoQvLkPaAFkCaIZTcaWA/edit#gid=0).

## VALUE created by our solution

Trust and reliability.

# Acceptance Criteria** (Definition of done) 

- [ ] SLO values are updated in the document.
- [ ] Sign off by Josh and Yael.

## QA Steps

- [ ] Reviewed and sign off by Josh and Yael

**Comment by jimleroyer** [comment]
Closing this task as this is a duplicate of #709

**Comment by yaelberger-commits** [comment]
Reopening as we don't have another card for SLOs
