### ISSUE TITLE
Update security notice page 

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#712]
## Describe the issue 

The security notice page (https://notification.canada.ca/security) contains the email address of the security team.  They are getting reports for sites that fall outside our scope of responsibility.

## Fix
Remove the email address and instead link to the main CDS security notice page (https://digital.canada.ca/legal/security-notice/) which has more detailed instructions.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-4

## Further context
This issue was reported by the security team [here](https://gcdigital.slack.com/archives/CR9E3U95F/p1655495902125729).

# Final content

## English

> ### Security Disclosure
> ...
> 
> Should you suspect a security breach or have discovered a vulnerability in the service, please see the [CDS security notice page](https://digital.canada.ca/legal/security-notice/) for further instructions.

## French
> ### Communications liées à la sécurité
> ...
>
>Si vous soupçonnez une faille de sécurité ou si vous avez découvert une vulnérabilité touchant le service, veuillez consulter [l'avis de sécurité du SNC](https://digital.canada.ca/legal/security-notice/) pour plus d'instructions.

**Comment by andrewleith** [comment]
Current content:

> ## Security Disclosure
> Should an incident happen, we have a comprehensive incident response and customer notification procedures in place.
> 
> Should you suspect a security breach or have discovered a vulnerability in the service, email us at [security-securite@cds-snc.ca](mailto:security-securite@cds-snc.ca) and we’ll investigate immediately.

Possible new content (only the last sentence has changed):
> ## Security Disclosure
> Should an incident happen, we have a comprehensive incident response and customer notification procedures in place.
> 
> Should you suspect a security breach or have discovered a vulnerability in the service, please see the [CDS security notice page](https://digital.canada.ca/legal/security-notice/) for further instructions.

**Comment by yaelberger-commits** [comment]
Small bug to fix in GC Articles in EN and FR

**Comment by jimleroyer** [comment]
LGTM since my only requirement is to have Mohamed happy and he's happy. 👍
