### ISSUE TITLE
Learning about our users’ needs and expectations re: SLOs

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#715]
## Description
**WHY are we researching?**
We have a gap in knowledge about what our users expect from GC Notify with regards to our service levels and we want to surface those expectations before resetting our Service Level Objectives and so we know where we're headed in the future when we're ready to update them again. 

**WHAT questions are we looking to answer?**
How many notifications do you expect your service can send each day? (a maximum) 

**VALUE created by our insights**
Our service provides a level of service that is expected and realistic.

## Acceptance Criteria** (Definition of done) 
- [x] Background research on any insights we already have about users' expectations of the SLOs (freshdesk tickets etc.)
- [x] Comparative market research on SLOs of other messaging services 
- [x] A research plan for an activity with users to gather new insights on SLO expectations 

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* Measuring success and metrics

![Screen Shot 2022-06-21 at 10.26.45 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/be1a0775-15b0-4370-bf0e-cf64dfd94366)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/715?planning-poker) with ZenHub @adriannelee @josh-cds

**Comment by yaelberger-commits** [comment]
I reviewed the plan. LGTM!

**Comment by yaelberger-commits** [comment]
Competitive Analysis and support ticket research today

**Comment by yaelberger-commits** [comment]
Support ticket analysis today
Learnings from comparative analysis

**Comment by jimleroyer** [comment]
Adrianne finished comparative analysis. It should be enough for research plan, will pursue on methodology.

**Comment by adriannelee** [comment]
Had a sync with Yael about the findings from the analyses. Finalized the research plan.
