### ISSUE TITLE
Service report download (jobs) possible in both French and English for users 

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#719]
## Description

As a Francophone user, I need to be able to download a French-only spreadsheet so that I can have my reports in my preferred language. 

WHY are we building?
Accessibility for Francophone users 
Compliance with official languages legislation
WHAT are we building?
Capability to download spreadsheets that are completely in French, including the column headers
VALUE created by our solution
Usability and accessibility
Goodwill from Francophone and bilingual PTs and users

## Acceptance Criteria** (Definition of done) 

- [x] Be able to download the reports here: https://notification.canada.ca/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/notifications/email?status=sending,delivered,failed
- [x] Thing about how it works for backward compatibility
- [x] If you are in EN - download an EN report, if in FR - download a FR one.

Given a Notify user is downloading reports from their service dashboard using the FR interface, when they download their report, then the headers in the downloaded report are in FR

Given a Notify user is downloading reports from the problem email addresses flow using the FR interface, when they download their report, then the headers in the downloaded report are in FR

Given a Notify user is downloading reports from bulk sending flow/by template using the FR interface, when they download their report, then the headers in the downloaded report are in FR

- [x] Verify with policy team and Platform BU what the policy is for OL with regards to these elements, and the API 

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/719?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by yaelberger-commits** [comment]
The Official Languages Act says that English and French are the languages of work in institutions and that employees have the right to use either official language in accordance with Part V of the OLA. The Directive on Official Languages for People Management also says that managers and supervisors are responsible for: 6.1.1 (Work instruments) Providing employees in bilingual regions with regularly and widely-used work instruments and electronic systems (work instruments) in both official languages.
So by making spreadsheets available in both French and English in Notify supports our users' choice to use either OL, and their managers in meeting these obligations.

**Comment by yaelberger-commits** [comment]
We already have content in English. We can involve Marie-Sophie when needed, or use existing translations if they are a 1:1 match

**Comment by yaelberger-commits** [comment]
We already have content in English. We can involve Marie-Sophie when needed, or use existing translations if they are a 1:1 match

**Comment by whabanks** [comment]
Content has been translated and code was reviewed. Addressing comments today.

**Comment by whabanks** [comment]
This is ready for a final review. I added a fix for FR characters not rendering properly in MS Excel. Kudos to @andrewleith for noticing this and suggesting a straight forward solution!

**Comment by whabanks** [comment]
Ready for QA!

**Comment by mtoutloff** [comment]
@adriannelee to QA
