### ISSUE TITLE
Rate limit traffic on the admin / documentation components via WAF

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#722]
# Description

As a Notify stakeholder,
I want to reduce the fuzzy attack on Notfy, 
so that our software is less discoverable with vulnerabilities
and only allow legit traffic to the web application.

## WHY are we building?

Limit the fuzzy attacks on Notify.

## WHAT are we building?

Add additional rules in our AWS WAF firewall to rate limit traffic from same IP and other factors on the admin and documentation components.

## VALUE created by our solution

Less discoverable, less support time spent on fuzzy attacks. WAF endpoint rules won't stop everything, so this would help stop attacks on valid endpoints

# Acceptance Criteria** (Definition of done) 

- [x] Check our data to see what's the threshold for unique IP and valid traffic, as some departments with many of our users might appear in higher number... and compare to these fuzzy attacks and determine a traffic threshold that would be effective.
- [x] Repeated traffic from same IP to the admin should be rate limited.
- [x] Repeated traffic from same IP to the tech documentation website should be rate limited.
- [x] Consider redirecting extra traffic to something fun if possible.

# QA Steps

- [ ] Send many request to the Notify admin URL from the same IP in Canada and wait to get redirected/blocked.
- [ ] Send many request to the Notify admin URL from the same IP outside of Canada (via proxy) and wait to get redirected/blocked.

**Comment by yaelberger-commits** [comment]
@jimleroyer Should part of the QA include testing that legitimate traffic does not accidentally get blocked as well? Are there any risks with accessibility we should keep an eye out for or test for?

**Comment by yaelberger-commits** [comment]
@josh-cds I'm moving this one straight to the Product backlog. It is an action item from a report we would like to tackle soon.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/722?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by jimleroyer** [comment]
Mohammed [provided this example](https://github.com/cds-snc/covid-alert-portal/blob/5ad1d2ad81b13824d913e47383cbaf5f8f25f5c2/config/terraform/aws/waf.tf#L313-L344) to start with, for a scenario where we want to block all traffic from outside of Canada. This can be considered for the API and document download components but we might want a softer rate limiting approach for the admin (to keep it open to other origins).

**Comment by sastels** [comment]
Can also have a general rate limit rule
![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/8658220a-47f4-4142-aa33-86e17cb02774)

**Comment by sastels** [comment]
[This documentation](https://aws.amazon.com/blogs/security/three-most-important-aws-waf-rate-based-rules/) looks useful, in particular the "Set up Athena to analyze AWS WAF logs" section

**Comment by sastels** [comment]
Data to use to set limits
We should be able to set a WAF limit of 400 - 500 hits per 5 minutes on admin

https://docs.google.com/spreadsheets/d/1Na1ybN1WNJzHFiAEkB97neCkpfpCBrfeRYQjfGKa3mI

**Comment by sastels** [comment]
We can also impose stricter rate limits on specific uris. For example, `/sign-in` or `/forgot-password`

**Comment by jimleroyer** [comment]
@sastels +1 on the URL stricter rate limit!

**Comment by jzbahrai** [comment]
There is a PR currently waiting toreview.

**Comment by sastels** [comment]
merged but in "count" for now. Will evaluate in a week to see if we would be blocking valid traffic.

**Comment by sastels** [comment]
so far in COUNT mode would have blocked (part of) a fuzzing attack on documentation.

**Comment by yaelberger-commits** [comment]
Waiting 1 week in QA to monitor

**Comment by jimleroyer** [comment]
Moving to done since this is in production since 2 weeks.

**Comment by yaelberger-commits** [comment]
Run QA tests in Prod

**Comment by jimleroyer** [comment]
Tested rate limit on production admin and it worked:

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/440aca30-5b0c-44de-99e3-e16f287d8f18)

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/846ecf69-6f6f-4f08-8eaa-5a04ecb2d5ee)

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/7460a951-fb6e-45d8-aae3-6f331ee1c036) 

Tested rate limit on documentation website and it worked:

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/044e3148-e3eb-4433-9117-d8f6d6918b23)

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/0d64cde1-cafb-4c0b-8da6-76da9113ea2c)

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/642b6bf8-a7f4-4068-a623-0ff4c09b2601)

**Comment by YedidaZalik** [comment]
@jimleroyer ran tests and can move to done
