### ISSUE TITLE
lower token expiration for client sessions

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#727]
As a Notify admin, I need to be able to limit the client session length so that the client is required to re-authenticate more often, lowering risk of malicious use of their account. 

- [x] How long is our current token expiration? 20 hours
- [ ] How much should we lower expiration by? to 8 hours (ATO recommended)

Do we need to notify users of this change? 
- Might confuse them if we do.
- Users likely don't know the length it is now

info on flask handling of session: 
https://flask.palletsprojects.com/en/2.2.x/config/#SESSION_REFRESH_EACH_REQUEST

##QA
- [ ]Is it 8 hours from when you last signed in? Or 8 hours from when you last touched Notify. Could be 8 hours from when last signed in

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/727?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/727?planning-poker) with Zenhub @whabanks @smcmurtry

**Comment by YedidaZalik** [comment]
PR is up for it and @smcmurtry reviewed so moving to QA

**Comment by jzbahrai** [comment]
It has been QA'd ready to deploy

**Comment by sastels** [comment]
For QA it will suffix to just look at the expiry time on the cookie. Currently:
![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/0740b676-d8f8-4507-a256-e6c3947b90eb)

**Comment by sastels** [comment]
Cookie in prod now expires in 8 hours
![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/41913381-f7d3-4b0d-ab8d-73657e8489c5)
