### ISSUE TITLE
DISCUSSION: Refine the volume limit given to client based on historical usage

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#728]

**Comment by yaelberger-commits** [comment]
Work with SRE/security team

**Comment by patheard** [comment]
This falls in the same category as other service specific metrics (e.g. bounce rate), and adding the ability to trigger alarms/actions based on those metrics.

For the historical use, we'd need to determine what period we wanted to evaluate, and what percentage over that period's use counts as a reasonable threshold for triggering an alarm.   

Perhaps you could start with a few of your well known services that send each week and test if a rolling 7 day evaluation period with a threshold of 20% increase is too noisy.

**Comment by yaelberger-commits** [comment]
We are covering this through daily SMS limits, daily Email limits and Bounce Rate epics
Closing this one
