### ISSUE TITLE
Send CSVs and bulk API as bulk priority

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#734]
_Send CSVs and bulk API as bulk priority_

## Description

As a Notify dev, I need to be able to automatically assign jobs to the Bulk priority lane when they reach a certain threshold of size so that I can ensure that the normal and priority lanes are reserved for notifications that are not bulk messages and need to get through faster. 

WHY are we building?
Review functionality and fill gaps if they exist
The source code reference to this functionality to review:
https://github.com/cds-snc/notification-api/blob/be8db3a360f84a875d4a582c3a0bb71b3b836450/app/celery/tasks.py#L964

WHAT are we building?
Check gaps, see how this behaves right now, look for opportunities to direct more bulk jobs to bulk priority lane

If you send more than 3,000? rows, you go into bulk, review to see where else it could apply

VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
@whabanks can you confirm that now that your changes to bulk priority default have been implemented that this is also now done or irrelevant?

**Comment by whabanks** [comment]
@yaelberger-commits Yes, this [work is complete ](https://github.com/cds-snc/notification-admin/pull/1426). Since we are putting everything in bulk by default now, the considerations around doing so at a threshold are no longer relevant.
