### ISSUE TITLE
Blazer deployment

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#735]
## Description

As a user I want to see what data I can get from database as a dev and user of Notify.
We ran blazer on staging and production, the next steps would be to look at some of its recommendations and make changes

## Acceptance Criteria** (Definition of done) 

- [x] Use terraform to set up blazer
- [x] Deploy blazer staging

Given some context, when (X) action occurs, then (Y) outcome is achieved 

# How to deploy:

- ECS Cluster -> Run it in your notify private subnet. You need a service and task
- Security Group - 3 levels, we will need all 3 - NACL, security group and IAM (vpc.tf) 
   -  most likely wont need a NACL
- Task : 
   - Setup IAM (who can use the role(assume policy), what policies are attached to the role
   - IAM policies around database (to google, a role that only lets it read data)

## QA Steps

- [x] Tested in a realistic production scenario

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/735?planning-poker) with ZenHub @andrewleith @jzbahrai @sastels

**Comment by jzbahrai** [comment]
https://github.com/mohamed-cds/terraform_test_infrastructure/tree/main/ssm_private_subnet/terraform

**Comment by YedidaZalik** [comment]
@jzbahrai to pair with Pat on this and will be making some changes and will continue on this today

**Comment by adriannelee** [comment]
about 5% left. Lots of it is merged. Working through the bugs. @jzbahrai will update the card (title and checklist).

**Comment by adriannelee** [comment]
Pat made a small change, Jumana will review and merge. 

Jumana will continue writing a script so that it's easier for everyone to do this.

**Comment by adriannelee** [comment]
Threat modelling exercise scheduled for Nov 7.

**Comment by andrewleith** [comment]
@jzbahrai working on #913 to unblock this.

We are also waiting on @patheard to vet the blazer image to unblock this.

**Comment by andrewleith** [comment]
Still blocked

**Comment by andrewleith** [comment]
- ADR is still outstanding; @jzbahrai to address comments today
