### ISSUE TITLE
QA: Terraform out of sync with AWS

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#736]
## Description:

Our terraform code has become out of sync with our staging and production accounts.
- in staging, we have made ecr-user and inspec-scanner access keys inactive when rotating these credentials. Merging a terraform PR will make the old ecr-user access key active again.
- in production we manually added WAF rules to block our recent fuzzing attack. Terraform will delete the new rules. This is likely ok, but we might like to keep these rules in place to more easily manually block future attacks
- in staging and production we manually corrected our "API lambda - errors" Cloudwatch Insights query. This fix will be reverted by terraform.

This blocks us from merging new terraform code (into staging or production). We should fix this ASAP.

- it is not good practice to declare access keys in terraform (in particular, it makes it difficult to rotate these credentials). We should:
  - manually rotate the ecr-user and inspect-scanner access keys on production (see https://docs.google.com/document/d/1BkAkz45CVQRGQSNwN018beTebrbTUNpyTpGEaO7Clyc/edit#heading=h.xltlzfpuc5n3)
  - delete the ecr-user and inspect-scanner access keys from terraform. This should delete the old inactive keys from our accounts but leave the new manually rotated keys in place. (verify the terraform plan!)
- after this we can add the new WAF rules and fix the query. This should bring terraform and staging in sync
- then we can do a release and bring terraform and production in sync

## Acceptance Criteria:

- terraform plan only predicts expected and desired changes

## QA
- [x] Look at what the change actually did compared to what it said it would do to check for any surprises
- [x] Wait a day or two after release to see if anything is breaking
- [x] a day or two later make sure the [guardrail scanner ](https://github.com/cds-snc/continuous-guardrail-scanning/tree/master/296255494825)still runs on production (still running; [look here](https://github.com/cds-snc/continuous-guardrail-scanning/blob/master/296255494825/2022-07-13.txt))

**Comment by jimleroyer** [comment]
We can drop the WAF rules. That was meant as a temporary fix to reduce some fuzzy attacks.

**Comment by yaelberger-commits** [comment]
Production release today

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/736?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by adriannelee** [comment]
Steve started on QA list. No release yet. If it works with the next release, it's passed QA.

To test in production (Jimmy) to check it's passed QA (hooked into the new keys)
