### ISSUE TITLE
DEV: Upload new images to S3 bucket

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#738]
_Upload new images_

## Description

Mostly in GC Articles on 2 pages. 
Needs to be done by a developer with access to the S3 bucket for uploading new images.

## Acceptance Criteria** (Definition of done) 

Given a user visits the pages where the images have been changed or added, when they go to those pages, the new images appear on both FR and EN. 

- [x] Images need to be in the Staging and Prod buckets so both environments appear the same 
- [x] Avoid the previous bug related to images in GC Articles ?
- [ ] Asset names and url

## QA Steps

- [ ] Correct images appear in Prod for EN and FR pages
- [ ] Images in prod match images in Figma
- [ ] The bug we saw previously is not happening

**Comment by amazingphilippe** [comment]
Images are on 2 pages. Along with alt text.
1. https://www.figma.com/file/uerfGAwA8MqaZ65Ep8oeXl/Recipients-files-guidance---Guide-fichiers-de-destinataires?node-id=827%3A2583
2. https://www.figma.com/file/uerfGAwA8MqaZ65Ep8oeXl/Recipients-files-guidance---Guide-fichiers-de-destinataires?node-id=827%3A2894

[Uploading... images.zip]

**Comment by yaelberger-commits** [comment]
@amazingphilippe is this blocked by the translation bug?

**Comment by adriannelee** [comment]
Blocked by SRE team/access - not clear exactly

**Comment by yaelberger-commits** [comment]
@amazingphilippe can you please check off the list above? Thanks

**Comment by amazingphilippe** [comment]
In the static folder in both staging and production asset compartments

- features/
    - features-api-en.svg
    - features-api-fr.svg
    - features-branding-en.svg
    - features-branding-fr.svg
    - features-dashboard-en.svg
    - features-dashboard-fr.svg
    - features-personalize-en.svg
    - features-personalize-fr.svg
    - features-recipients-en.svg
    - features-recipients-fr.svg
    - features-scheduler-en.svg
    - features-scheduler-fr.svg
    - features-team-en.svg
    - features-team-fr.svg
    - features-templates-en.svg
    - features-templates-fr.svg
- examples/
    - example-variable-fr.svg
    - example-filter-en.svg
    - example-filter-fr.svg
    - example-headers-en.svg
    - example-headers-fr.svg
    - example-row-en.svg
    - example-row-fr.svg
    - example-variable-en.svg
