### ISSUE TITLE
DESIGN: Update GC articles content (guidance page and new page)

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#739]
_Update GC articles content_

## Description

Translated content https://www.figma.com/file/uerfGAwA8MqaZ65Ep8oeXl/Recipients-files-guidance---Guide-fichiers-de-destinataires?node-id=934%3A2947

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given a user visits the GC Notify website, when they visit the guidance pages, then the updated pages appear and not the old content.

- [x] Make changes to guidance pages to EN and FR
- [x] hyperlink correct pages from guidance 
- [x] create new page for spreadsheet guidance in EN and FR
- [x] Update email formatting guide pages EN and FR
- [x] Update custom content pages EN and FR

## QA Steps

- [x] Content in prod is the same as content in Figma
- [x] Content is correct for EN and FR
- [x] Alt-text appears for all images
- [x] Check that all links between pages in guidance are working correctly and lead to the right pages 
- [x] Manually a11y scan

**Comment by amazingphilippe** [comment]
Spreadsheet guides drafts: (must be logged in to see)
https://notification.canada.ca/preview?id=195&lang=en
https://notification.canada.ca/preview?id=197&lang=en

**Comment by yaelberger-commits** [comment]
I reviewed in both EN and FR for any obvious issues and looks goo to me

**Comment by yaelberger-commits** [comment]
Links also go to the correct guidance pages in EN and Fr for variables

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/739?planning-poker) with ZenHub @adriannelee @amazingphilippe @YedidaZalik

**Comment by amazingphilippe** [comment]
Updates done. looking fro someone not Yedida or Phil to go through the QA steps

**Comment by adriannelee** [comment]
https://notification.canada.ca/guides-reference:

- [ ] Do we want to link to the API documentation on the first paragraph where it mentions it?
- [ ] "Apprenez à" is placed on a new line on Figma, under #2
- [ ] Under #4, the two sentences are on separate lines on Figma

https://notification.canada.ca/guide-mise-en-forme

- [ ] On Figma, "envoyer des messages avec du contenu personnalisé." is the hyperlink
- [ ] On Figma, "send messages with custom content." is the hyperlink
- [ ] The custom content page leads to this page: https://notification.canada.ca/personalisation-guide (should we archive this page?)

https://notification.canada.ca/custom-content

- [ ] The examples under "Use variables for custom content" don't match what's on Figma 
- [ ] The images are also not side by side, as on Figma. Is that ok? (happens on multiple pages)

https://notification.canada.ca/feuille-de-calcul
- [ ] On the first image under "Préparer une feuille de calcul acceptant du contenu personnalisé", there's a missing "à" after "aujourd’hui"

https://notification.canada.ca/fonctionnalites
- [ ] There's a typo: "En savoir plus sur l’utilisation d’une feuille de calcul si votre équipe n’utilise pas l’API*/feuille-de-calcul*"
- [ ] Need to remove "Voyez le nombre de messages envoyés. "

------
Still need to check for links between pages, alt text, a11y

**Comment by amazingphilippe** [comment]
> The custom content page leads to this page: https://notification.canada.ca/personalisation-guide (should we archive this page?)

I did the opposite and kept personalisation-guide to avoid breaking other links in the app.

**Comment by amazingphilippe** [comment]
> The images are also not side by side, as on Figma. Is that ok? (happens on multiple pages)

Some examples will stack for readability on smaller screens!

**Comment by adriannelee** [comment]
> I did the opposite and kept personalisation-guide to avoid breaking other links in the app.

Ahh, ok. But we'd still refer to /custom-content
/custom-content#filter
/custom-content#fill from https://notification.canada.ca/guidance no? Currently, all 3 point to https://notification.canada.ca/personalisation-guide

**Comment by adriannelee** [comment]
Ah, ok - so we want to keep it pointing to https://notification.canada.ca/personalisation-guide? 

The French links now link 👍

> For the formatting examples, I'm not sure what to change to make it more apparent... Another option would be to convert all of the examples into images, but we would lose the responsive layout (stacked on mobile, horizontal on large screens) Which would either make the mages very small to read on mobile, or very large on desktop.
I was thinking maybe we could use content? Like "Example Title" or something?

**Comment by adriannelee** [comment]
New alt-text, examples being looked at today by Phil and Yedida.

I'll continue with the manual testing

**Comment by adriannelee** [comment]
Manually a11y scan

https://notification.canada.ca/guidance
- `API documentation` is missing a hyperlink? I wasn't sure because the Figma also doesn't show hyperlinks. But https://notification.canada.ca/guides-reference there is a hyperlink for this text

✅ https://notification.canada.ca/guides-reference
✅ https://notification.canada.ca/feuille-de-calcul
✅
 https://notification.canada.ca/spreadsheets
✅ https://notification.canada.ca/guide-personnalisation
✅ https://notification.canada.ca/personalisation-guide

Something unrelated I noticed .. our hyperlinks don't meet the colour contrast requirement (3:1) related to the static text that surround the hyperlink text

**Comment by amazingphilippe** [comment]
> our hyperlinks don't meet the colour contrast requirement (3:1) related to the static text that surround the hyperlink text
More info here: https://www.w3.org/TR/WCAG20-TECHS/G183.html
Since we also use underlines, and the underline changes on hover or focus, we are good! This applies only to paragraphs of text.

**Comment by adriannelee** [comment]
https://notification.canada.ca/formatting-guide
- [ ] Should "Titre français", "Texte en français" read in French? (Should the language tag be set to french here?)
https://notification.canada.ca/guide-mise-en-forme
- [ ] Same as for the English page, but for the English text.

I _think_ the QA is done, except for those example headings and the above 2 points?

**Comment by adriannelee** [comment]
Phil will take a look today

**Comment by amazingphilippe** [comment]
Last changes made. Cache needs to be cleared on production site

**Comment by yaelberger-commits** [comment]
Adrianne will take a final look at last 2 checkboxes and then Adrianne can clear cache with help from Phil. Yael to attend too!

**Comment by yaelberger-commits** [comment]
Cached on Aug 8. 
I can also compare what's live to Figma designs and check links etc. in multiple browsers today to help QA this further

**Comment by adriannelee** [comment]
The last two checkboxes (the language tags) have been QA'd again. Looks good!

[A page is still missing a hyperlink](https://gcdigital.slack.com/archives/G010A3CDV5X/p1660055639536799). I'll try to fix it on GC Articles.

**Comment by adriannelee** [comment]
Yedida added the hyperlink on the English page. LGTM! (QA is done by me 😊)

**Comment by yaelberger-commits** [comment]
I think we need to clear cache again, no? To see the change live?

**Comment by yaelberger-commits** [comment]
It seems to be live :) 
@adriannelee is this considered Done now?

**Comment by jzbahrai** [comment]
this ticket is done!
