### ISSUE TITLE
DEV: Reformat help card component

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#740]
_Reformat help card component_

## Description

We need to check if we have, or need to create this component:

![Capture d’écran, le 2022-06-28 à 15.11.17.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/2cf047ad-cc92-4240-ad8e-d1ace3f994f1)

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

- [x] title
- [x] image source
- [x] description
- [x] button url
- [x] button text

Given dev wants to use this component in any current or future designs, then they have the pattern available

## QA Steps
- [x] Find occurence of the pattern
- [x] Make it a component
- [x] Replace instances with new component
- [x] Unit tests?
- [x] Manually a11y scan
- [x] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Might be pulling out Tailwind

**Comment by yaelberger-commits** [comment]
There is already a macro for this, it's there already

**Comment by yaelberger-commits** [comment]
Phil and Jimmy to sync on this to further refine

**Comment by adriannelee** [comment]
Andrew will review this PR today
