### ISSUE TITLE
DEV: Create service dashboard “get started” section

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#743]
_Create service dashboard “get started” section_

## Description

As a new Notify user, I need some guidance on how to use templates, so I can understand what my first steps are after creating or joining a new service. 

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given a user is on the dashboard, when they glance over the get started section, they can find out where to get started

- [x] Add get started section on service dashboard
- [x] Must first update the spreadsheet guidance page so you can link to it from this updated section #739

## QA Steps

- [x] Content and designs match Figma in En and FR
- [x] Manually a11y scan
- [x] link works in both EN and Fr and goes to the right place
- [x] Headings are properly labelled as such for ally

**Comment by amazingphilippe** [comment]
Figma link: https://www.figma.com/file/RLcM0JwlQsd2uVK3GJr5qY/Drafting-message-templates-%7C-Creer-des-gabarits-de-message?node-id=2102%3A11366

**Comment by adriannelee** [comment]
Andrew will/have reviewed this one - he'll doublecheck

**Comment by andrewleith** [comment]
I think the new design is much cleaner and the new component will be nicely reusable.  

I have a concern that users may not know how to initially send a notification when they land on their dashboard, though,  as there is no wording that lets them know specifically what path to "send".  

In order to send a message, a user must first create a template which is explained in the intro paragraph.  Once they have a template, the path to send a notification is to click on the card titled "Reuse a message you’ve already created. - [Choose a template]", and my concern is that it is not immediately clear that this will lead to being able to send a notification. 

Perhaps we should include the word send somewhere for that card, even if the first actual step is choosing the template.

**Comment by yaelberger-commits** [comment]
I think a meeting is needed between design and Andrew, Jimmy and Yael to discuss further Andrew's feedback. While the changes we made improved the experience in many ways, by removing Write and Send we may have introduced some additional confusion. Also we include Edit in the mix as a step that's lumped together with Send. Perhaps there are some further content or design changes we can make before we release this.

**Comment by yaelberger-commits** [comment]
From @YedidaZalik 
Looking at this in more detail, I think it's good feedback and we may not need a meeting to implement it. Offhand, I could see replacing the "Get started" heading with "Write and send messages". Then in the paragraph below, we'd remove "To send a message" and the sentence would begin with "Always".

**Comment by yaelberger-commits** [comment]
PR for the final changes after last week's sync. PR ready for review

**Comment by jzbahrai** [comment]
@jimleroyer will QA

**Comment by yaelberger-commits** [comment]
@jimleroyer I can help QA this one now that it's in prod if you like to check that release matches Figma, all links work etc. in all the browsers

**Comment by yaelberger-commits** [comment]
The word "created" is on the third line when in Figma it's part of the second line
![Screen Shot 2022-08-10 at 8.24.00 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/b1d37a10-dbe7-4cde-a283-3fa5fe31aead)

**Comment by yaelberger-commits** [comment]
Tested all links and content (EN and FR) in Chrome, Safari and Firefox. 
@adriannelee would you be able to do manual a11y scanning on this one?

**Comment by adriannelee** [comment]
Manual a11y testing is done, lgtm! One small thing is that the period after the "prepare a spreadsheet" link gets read twice on Chrome using VoiceOver.

**Comment by andrewleith** [comment]
I took a quick look and the markup is correct, not sure why VoiceOver is reading the period twice.

Looks like we're all done here, moving to done!

**Comment by yaelberger-commits** [comment]
Moved back to QA to see if Phil is able to resolve the two issues, "created" on a third row and VoiceOver reading period twice.

**Comment by amazingphilippe** [comment]
Phil will look at fixes Today
