### ISSUE TITLE
Index of rows don't align when bad data is uploaded with a csv

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#744]
## Describe the bug 

When sending in bulk, and you have validation errors in your csv data. The preview doesn't render the index numbers aligned with the data in each row.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV 3 because impacting some users who upload bad data with CSV

## To Reproduce

1. Upload a csv for an email template
2. Enter a few bad email addresses
3. Trigger the error and see the bug

## Expected behavior

Index number should align with the rest of the row.

Column with numbers is likely assuming each row has only one line of data, but this has 2 lines per row. 
Make this a proper table

## Impact

It is difficult to read the table bc the rows are not aligned. 

## Screenshots

![Capture d’écran, le 2022-03-09 à 10.47.15.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/e0315fc3-ef8c-4213-b723-a3e64cb5ffc7)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/744?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by smcmurtry** [comment]
This bug has also cropped up on the "Review before sending" screen for a CSV send, since we introduced [remove ellipses for a11y reasons](https://github.com/cds-snc/notification-admin/pull/1335).

<img width="1247" alt="Screen Shot 2022-09-22 at 4 47 04 PM" src="https://user-images.githubusercontent.com/5498428/191987723-6f033c37-3cca-4add-a510-dd9c826d1018.png">

**Comment by andrewleith** [comment]
Tested in chrome and firefox, using desktop and mobile viewports.  All works well!
