### ISSUE TITLE
Default to bulk priority for all templates

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#748]
# Description

Have all newly created templates in the bulk priority by default. The templates that need to go faster will go into review and be set to either normal or high priority afterward. This would help us properly prioritize templates and make sure the priority lanes are not clogged.

## WHY are we building?

Redirect most notifications traffic into bulk priority by default. Our biggest traffic at the moment is going through the normal priority, potentially making that one the bulk priority is slowing down notifications that should be in the normal priority lane.

## WHAT are we building?

Moving the default from normal priority to bulk priority upon creation of a template.

## VALUE created by our solution

Unclogging the normal priority lane.

# Acceptance Criteria** (Definition of done) 

- [x] Newly created templates are set to `bulk` priority instead of `normal`.
- [x] Review existing templates in the normal priority and recommend to move some into bulk.

# QA Steps

- [x] Create a new template and verify its priority.

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/748?planning-poker) with Zenhub @jzbahrai @sastels @andrewleith @smcmurtry

**Comment by andrewleith** [comment]
Code should be in place, just need to run the tests and then @Pensai will create a PR.

**Comment by andrewleith** [comment]
Can we get a description to indicate what this change brings.

**Comment by Pensai** [comment]
> Can we get a description to indicate what this change brings.

When a regular non-admin user creates a new template a priority is assigned to the template, currently this priority defaults to "normal". This change will now set the default priority of a template to "bulk" instead.

What does this mean? Newly created templates will be placed into a lower priority "lane", bulk, to free up resources on the normal lane where the majority of notifications are being serviced. The end goal is to reduce traffic on the normal lane and reduce sending delays for normal priority notifications.

We will migrate existing templates from normal to bulk on a case by case basis by analyzing usage metrics and determining their priority. Details on usage thresholds for categorizing a template as bulk rather than normal to come.

**Comment by andrewleith** [comment]
- Code is done, PR is in
- Working on queries for identifying existing templates we can move

**Comment by andrewleith** [comment]
- still working on queries; needs to be optimized

**Comment by andrewleith** [comment]
@whabanks working on queries to determine which services should be in which priority lane Should be done today

**Comment by whabanks** [comment]
[Initial review](https://docs.google.com/spreadsheets/d/1HTWm9X6HGisxrYBgMK5kG7iwPJpn6lsSujaysmU2MjE/edit#gid=1614272103) of high volume template usage complete, suggestions and reviews welcome!

**Comment by sastels** [comment]
I just QAd on staging (made a template and verified its bulk)

**Comment by andrewleith** [comment]
- initial review complete; queries have been tweaked;
- going to create another query to get a more granular look
- @whabanks working on this today

**Comment by jimleroyer** [comment]
Queries and spreadsheets were updated. Looking into recent incident and resulting 403. Fixes is in with the problem.

**Comment by jimleroyer** [comment]
Added more regression tests with previous issue once deployed and worked the fix.

**Comment by jimleroyer** [comment]
PR to review for all.

**Comment by smcmurtry** [comment]
I QAd this in staging and it looks good. Here is what I checked:
- templates created by non-Admin user are "bulk" priority
- old templates that are "normal" priority are editable by non-Admin users, editing does not change the priority
- admin users can create templates of any priority, these are all editable

Looks good!
