### ISSUE TITLE
QA: SQLAlchemy returns unexpected data type from `query` function

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#753]
# Describe the bug 

Recent SQLAlchemy upgrade (1.3.23 to 1.4.37) triggered an issue with the stats section of the landing page.

# [Bug Severity]

(https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
(SEV-1, SEV2, SEV3, SEV-4) 

SEV-1: This is crashing the homepage and blocks our release pipeline.

# To Reproduce

1. Go to the landing page of the deployed application.

# Expected behavior

Landing page should work and deliver stats.

## Impact

The homepage is down.

# Additional context

The SQLAlchemy `query` API now returns a `Row` data type instead of an array as previously. We need to accommodate our codebase sites where this `query` function is called for this new type.

**Comment by jimleroyer** [comment]
Jumana deployed this fix in production on 2022/07/05.

**Comment by jzbahrai** [comment]
This was fixed with this PR: https://github.com/cds-snc/notification-api/pull/1569
It has been deployed to production.
