### ISSUE TITLE
Convert smoke tests to Cypress

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#755]
_ Automated UI test suite, smoke tests focussed on the UI _

## Description

Convert the existing smoke tests to cypress, in order to leverage testing not only the sending of notifications but also their receipt.

Create a UI test suite, smoke tests focussed on the UI to catch any bugs before deployments. 

This is an action item from an incident where the landing page was down and returning 500 errors following a deployment, but staging was unaffected as far as we know
https://docs.google.com/document/d/1YR5_BCEEzQXdD7pZkqOvhfsWkjtb1mS44iFKWfpDIhU/edit#

# Things to think about:
- If the architecture needs to be confirmed - an ADR might be the way to go
- We might need an email to test this

## Acceptance Criteria** (Definition of done) 

If this user story emerged from User Research insights:

- [x] Create a smoke-test suite based on our current smoke tests
- [ ] Add steps to the tests to ensure email notifications are received

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Ramya's list of test use cases for manual testing can provide a roadmap for automated test suite as well.

**Comment by jzbahrai** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/755?planning-poker) with Zenhub @smcmurtry @whabanks

**Comment by yaelberger-commits** [comment]
Decided to close. We can open a new card for testing if AWS is down
