### ISSUE TITLE
Create coded prototype for testing of disclosure and dialog menus for mobile 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#761]
In #582 the audit recommends prototyping 2 navigation patterns for mobile: disclosure and dialog. Right now we have mobile menus that open as overlays. The menus are the main menu and the account menu. 

Creating a prototype of a disclosure navigation will allow us to test both with users and see which pattern is performing better. We should also aim to test with users using assistive technology.

We can follow some aspects of these designs for the prototype: https://www.figma.com/file/r3GzRBjBDWvL2AwCWq1e1W/Navigating-the-site-%7C-Naviguer-le-site?node-id=7778%3A3703

For this prototype, we can leave out the design for:
- the search bar
- removing the priority+ pattern. 

## Description

As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/761?planning-poker) with ZenHub @amazingphilippe @andrewleith @jzbahrai @jimleroyer @sastels

**Comment by yaelberger-commits** [comment]
Blocked due to time and capacity constraints

**Comment by amazingphilippe** [comment]
This has been completed by https://github.com/cds-snc/notification-admin/pull/1814
