### ISSUE TITLE
User research with public servants re: SLOs

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#763]
## Description

As a Notify PM, I need to be able to understand users' needs and expectations around Notify's performance metrics and SLOs so that I can update and publish the product's SLOs with confidence that the product's goals are in line with meeting expectations of our users. 

WHY are we building?
We haven't updated our SLOs since last year and we have never done a user research activity to collect data on what our users expect from Notify. We want to align our service level goals to aim or stretch to meet user needs and expectations, and identify any gaps we currently have with our product.

WHAT are we building?
Survey with public servants currently using GC Notify

VALUE created by our solution
We will know if our SLOs will be too low to meet user needs and where the gaps are between Notify's performance and what our users expect from our service in terms of volume, speed and reliability, and the timeline they need us to meet these expectations.

## Acceptance Criteria** (Definition of done) 

Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] hear from clients who use SMS
- [x] hear from clients who use email
- [x] hear from clients who send small batches (under 1,000) and those who send in bulk (over 1,000)
- [x] Margin of error less than 10%
- [x] hear from Provincial users
- [x] hear from federal users
- [x] Average responses if there are multiple responses per service
- [x] Survey closes Sept 9, 2022

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable

---------------
[Survey draft](https://airtable.com/invite/l?inviteId=invJ3LmGNYZZrRROB&inviteToken=8cc1aa687b23744bdaa842cf2ec18fd95ab4de641eab5d6ebdc81c9741dc4623&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts)

**Comment by yaelberger-commits** [comment]
@adriannelee for refinement and discussion of whether to bring into next sprint. Feel free to add/edit this user story

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/763?planning-poker) with ZenHub @adriannelee @amazingphilippe @sharlychan-cds @YedidaZalik

**Comment by adriannelee** [comment]
Made small edits to the card description & updates to the research plan.

**Comment by jzbahrai** [comment]
Survey has been drafted, and is going to be demo'd today

**Comment by adriannelee** [comment]
Created the survey Qualtrics, it's up for review by Yael, Jimmy, Yedida

I'm going to start on the other materials (privacy, invite email, invite list, etc)

**Comment by adriannelee** [comment]
Privacy and email invite were drafted and sent to translations. 

Incorporated changes to the survey based on feedback - some more changes are pending. I haven't sent to translations yet because I want to make sure the linkage between our database and Qualtrics won't require changes to the questions and answer options.

Working on linking template names from the invite to the survey. Need dev help to have a look at how I'm setting up the linkage from our database to Qualtrics. I'll also need dev help later on to get a list of clients to send the invite to.

We're also thinking of leaving the survey open till Labour Day or so, considering respondents may be away for summer vacation.

**Comment by adriannelee** [comment]
I'll get help from Andrew today

A note that we're decoupling the user research from updating the SLO (for alarms)

**Comment by adriannelee** [comment]
Andrew tried to pull the data - might reach out to Steve for formatting the data.

I'll schedule a sync with Andrew today, and reach out to Jumana as well if needed

**Comment by adriannelee** [comment]
Survey questions and answers have been finalized and the request has gone to translations. I've asked for it back for this Thursday EOD.

**Comment by adriannelee** [comment]
Translations came back - add them in.

Some small things to do before sending out:
- [ ] I realized that some respondents will receive duplicate links (and won't be able to input their unique response - or include a response if someone else on their team has started the survey). So I'm fixing that and doublechecking.
- [ ] Manually add the question numbers because the automatic ones are showing up for the ones that aren't questions (but are just text)
- [ ] text submit a response and check the data

**Comment by adriannelee** [comment]
Survey has launched 🎉 and 20 responses already! (yay!)

Next, I will prepare for analysis so that by Sept 9, the charts are ready to plug into a report.

**Comment by amazingphilippe** [comment]
Looking for help and expertise with spreadsheet setup for results analysis

Survey has 77 responses!!

**Comment by adriannelee** [comment]
Here’s a sample of the responses I’m working with to set up the analysis https://docs.google.com/spreadsheets/d/12PecyzwyO-1I39Jq1t6S5I3vRYNbd1fYkjvcit2KAH0/edit#gid=375595319

the report set up https://docs.google.com/presentation/d/1hdvWDBFWXS4PDMDtjQ7U3Wwh9DDhMMGdTTllLCKW-vA/edit#slide=id.p

**Comment by amazingphilippe** [comment]
Moar responses! Still looking for a spreadsheet guru!

**Comment by yaelberger-commits** [comment]
Adrianne working with devs on which questions we'd like to answer with this data

**Comment by yaelberger-commits** [comment]
157 responses in total. Adrianne will be working with the data and working on the presentation today

**Comment by adriannelee** [comment]
Wrap up working on the presentation and present today! Might do a quick part 2 / update later on for the text analysis.

**Comment by yaelberger-commits** [comment]
Might do an update on free-text comments tomorrow

**Comment by adriannelee** [comment]
Chatted with Andrew and Jeana about how to best calculate the expected volume. 

Decided we need more clarity on the why before we determine the 'how'. Booked a meeting for when both Yael and I are back from vaca. Will put back into the product backlog till then.
