### ISSUE TITLE
Align data retention period to 7 days for uploaded CSVs

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#765]
# Description

As a user of Notify,
I don't want my uploaded CSV to stay more than 7 days,
as the software claims the data retention is no more
and to have my data properly purged for security / privacy purposes.

## WHY are we building?

Align with our advertised data retention policy.

## WHAT are we building?

Bring down the data retention for uploaded CSV from 30 to 7 days.

## VALUE created by our solution

More security / privacy. Alignment with our policies. More trust.

# Acceptance Criteria** (Definition of done) 

- [x] Uploaded CSVs are automatically purged after 7 days.

# QA Steps

- [x] Verify the uploaded CSVs are not stored for 30 days anymore.
- [x] Verify the S3 bucket storing the CSV uploads has a 7 days deletion policy applied to it automatically.
- [x] Verify the uploaded CSVs are purged after 7 days.

**Comment by jzbahrai** [comment]
Ran this query and it returned empty: 
aws s3api list-objects-v2 --bucket notification-canada-ca-production-csv-upload  --query 'Contents[?LastModified<=`2022-07-05`].Key'
