### ISSUE TITLE
Quick fix for service reporting bug

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#766]
# Bug description

The report download link for notifications sent by service is broken in the admin reports panel.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

SEV-3 Minor

## To Reproduce

1. Go to the admin reports section.
2. Click on Monthly notification statuses for live services.
3. Select a time period for the report to generate.

# Expected behavior

The report should download instead of redirecting to an error page.

# Impact

We don't know the Notify usage and we can't have monthly reports to communicate.

**Impact on Notify users:** None

**Impact on Recipients:** None

**Impact on Notify team:** Minor

# Additional context

This card is for a quick fix on fixing the report download. It should take no more than 1 hour to fix. 

Another card exists to look into the root cause of this issue for long term, as other code locations might be affected without our knowledge.

**Comment by jimleroyer** [comment]
PR to fix this bug:
https://github.com/cds-snc/notification-admin/pull/1298

**Comment by adriannelee** [comment]
Has been reviewed - QA is to make sure the change is working.

**Comment by sharlychan-cds** [comment]
tested this morning, not working yet. 

Same error, website says: "Sorry, we’re experiencing technical difficulties. Try again later."

Browser tab says "server error - Notify"
