### ISSUE TITLE
Remove public and service agreements in notify

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#769]
# Description

As a developer,
I want less code to maintain,
so that I can increase development velocity within the dev team.

As a policy person,
I want to review the unused/missing functionality for public and service agreements,
and provide my opinion if we want to keep or if we're good to remove.

## WHY are we ~~building~~ destroying 💥?

To move faster and get rid of the cruft. ☠

## WHAT are we ~~building~~ eradicating?

Two unused components in GCNotify:

* [Public agreement](https://staging.notification.cdssandbox.xyz/agreement/crown)
* [Service agreement](https://staging.notification.cdssandbox.xyz/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/agreement)

## VALUE created by our ~~solution~~ ravage?

Being faster and increasing developer's satisfaction for pure damage. 🧨

# Acceptance Criteria** (Definition of done) 

- [x] Annihilation of the unused components completed
- [x] Useful components intact

# QA Steps
On Staging:
- [x] GCNotify is still up and running.
- [x] These pages should no longer be there: 
- https://staging.notification.cdssandbox.xyz/services/1dac916a-05b2-49ca-bf75-072231c3f505/agreement (or whatever service)
- https://staging.notification.cdssandbox.xyz/agreement/crown

**Comment by yaelberger-commits** [comment]
Question for @sharlychan-cds 
Before we delete any of this code, should we assess if any of it might come in useful if we do ever introduce billing and/or account management? 
@jimleroyer we wouldn't want to delete these pages to just have to recreate them, right? 
cc @amazingphilippe as well

**Comment by jimleroyer** [comment]
We could easily bring back these if we need to. The way that GDS Notify shows their agreements is raising questions from me though. They seem to have one agreement per service and a public agreement (for which we have no link to target to).

We can check or ask GDS what actually these are. It is unsure and we can always add ours in some other ways, effort should be minimal.

**Comment by yaelberger-commits** [comment]
@jimleroyer thanks for explaining that. I'm ok to add their removal to the backlog, but I think it's low priority. Any reason why you think it should be done with more urgency?

**Comment by yaelberger-commits** [comment]
@amazingphilippe @YedidaZalik FYI we have a code path for service agreement... Should we consider reviving this one, or creating it new and deleting this old one?

**Comment by YedidaZalik** [comment]
@yaelberger-commits @amazingphilippe I can see the public agreement but I get a 403 error when I click on the service agreement.   Since we have a code path already, it seems to me we could use it, but I defer to @amazingphilippe .

**Comment by amazingphilippe** [comment]
I think we don't have the right url in the issue above. This works: https://staging.notification.cdssandbox.xyz/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/agreement

**Comment by jimleroyer** [comment]
Note: the way the service agreement URL is setup at the moment is that each service would have their own specific one. It's not a global one for all services.

**Comment by yaelberger-commits** [comment]
Ah thanks @jimleroyer!
Let's get rid of it all then :)

**Comment by smcmurtry** [comment]
The pages are removed, the WAF rule has been updated to block requests to the public agreements page. Ready for QA on Staging.

**Comment by mtoutloff** [comment]
QA: clicked on the links on QA section of the card and for this link it goes to a "page could not be found" page and for this link it opens to a blank tab (page)
