### ISSUE TITLE
Update Kubernetes worker to 1.22.9-20220629

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#770]
# Description

As a stakeholder of Notify,
I want the software kubernetes stack updated to its latest,
So that I have a safe and secure environment.

## WHY are we building?

Security, features, maintenance.

## WHAT are we building?

Updating to the latest version of the kubernetes stack.

## VALUE created by our solution

Security, features, maintenance.

# Acceptance Criteria** (Definition of done) 

- [ ] The kubernetes worker are up to date to version 1.22.9-20220629.

# QA Steps

- [ ] Verify the kubernetes workers are set on version 1.22.9-20220629.

# Additional Context

[Document to update workers](https://docs.google.com/document/d/1zWClyeWL9Ouv7euh_mC0txUy7xXIxQ5kmW3O0dgobzo/edit) (and clusters but not in scope of this).

**Comment by jimleroyer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/770?planning-poker) with ZenHub @patheard

**Comment by adriannelee** [comment]
Jimmy will take a look today

**Comment by jimleroyer** [comment]
This was released on August 3rd!

**Comment by jimleroyer** [comment]
Will need someone to verify that the workers were upgraded. I verified myself but second set of eyes as per our process..

**Comment by jzbahrai** [comment]
@sastels to QA

**Comment by jzbahrai** [comment]
@jimleroyer will deploy today morning with some of the  changes

**Comment by sastels** [comment]
looks good in production!
