### ISSUE TITLE
Admin reports not working correctly

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#773]
## Describe the bug 

Two reports are currently not working properly:
1. [trial services csv report](https://staging.notification.cdssandbox.xyz/platform-admin/reports/trial-report.csv) 
2. [Sending method: services sending via API vs. User Interface](https://staging.notification.cdssandbox.xyz/platform-admin/reports/send-method-stats-by-service)

For each report, instead of data, the row headers are repeated for each row.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-4 Low

## To Reproduce

1. Go [Admin panel -> reports](https://staging.notification.cdssandbox.xyz/platform-admin/reports)
2. Click on [trial services csv report](https://staging.notification.cdssandbox.xyz/platform-admin/reports/trial-report.csv) or [Sending method: services sending via API vs. User Interface](https://staging.notification.cdssandbox.xyz/platform-admin/reports/send-method-stats-by-service)
3. Open file

## Expected behavior

It is expected that the downloaded file contains data instead of repeated row headers.

**Comment by yaelberger-commits** [comment]
@sastels @mohamed-cds is this related to the csp issue?

**Comment by mohamed-cds** [comment]
shouldn't be related. the csp violation relates to the `notification-admin` newrelic integration.

**Comment by smcmurtry** [comment]
All PRs are reviewed and merged to staging. Both reports are showing data again.
