### ISSUE TITLE
Allow a service to send xml files

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#779]
Service `a7ef2e53-42ab-4b16-9a5b-e623fb778074` would like to send kml files (which are really xml)

See https://cds-snc.freshdesk.com/a/tickets/9452

A similar change (for a different service) was done [here](https://github.com/cds-snc/notification-manifests/pull/887)

Requirements:
- [x] new permissions added to prod env vars in manifest repo
- [x] manifest repo released to production
- [x] user notified (via ZenDesk ticket)
- [ ] user reports they can send kml attachments

QA:
- [ ] user reports they can send kml attachments

**Comment by yaelberger-commits** [comment]
Give one more day before closing ticket and marking task as done.

**Comment by amazingphilippe** [comment]
Client will ping us if they can't do this

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/779?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels
