### ISSUE TITLE
SQLAlchemy reports a relationship warning after upgrade

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#782]
# Describe the bug 

Since we upgraded the SQLAlchemy library following the werkzeug 2 upgrade, we started to see relationship warnings related to SQLAlchemy:

```
Field	Value
@ingestionTime	
1658770540832
@log	
296255494825:/aws/lambda/api-lambda
@logStream	
2022/07/25/[36]45401e80db6948cc8d85469331c45187
@message	
/usr/local/lib/python3.9/site-packages/marshmallow_sqlalchemy/convert.py:170: SAWarning: relationship 'ScheduledNotification.notification' will copy column notifications.id to column scheduled_notifications.notification_id, which conflicts with relationship(s): 'Notification.scheduled_notification' (copies notifications.id to scheduled_notifications.notification_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards. To silence this warning, add the parameter 'overlaps="scheduled_notification"' to the 'ScheduledNotification.notification' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
@timestamp	
1658770532666
```

# [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

# Expected behavior

We shouldn't see this error in the logs

# Impact

Unsure what we might be causing/ missing due to this error. This might lead to bugs that we do not perceive yet.

**Comment by yaelberger-commits** [comment]
@jzbahrai Can you provide a bit more info on this error you saw? What part of the system is it affecting? 
What kind of error is it?

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/782?planning-poker) with Zenhub @jzbahrai @sastels @andrewleith

**Comment by jzbahrai** [comment]
this can't be replicated atm. Going to shut it

**Comment by jzbahrai** [comment]
this bug is still relevant
search under API lambda:
```
fields @timestamp, @message, @logStream
| filter @message like /SAWarning/
| sort @timestamp desc
| limit 20
```

**Comment by jzbahrai** [comment]
Tested this! can't find this bug in prd anymore:

fields @timestamp, @message, @logStream
| filter @message like /SAWarning: relationship 'ScheduledNotification.notification'/
| sort @timestamp desc
| limit 20
