### ISSUE TITLE
System status page in Notify Release 2

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#785]
# Description

As a user of Notify,
I need to know its status and maintenance windows,
So that I know if the software works correctly 
and when Notify has planned maintenance.

## WHY are we building?

To improve Notify status communication with our users.

## WHAT are we building?

A status/maintenance page.

## VALUE created by our solution

Better communication and more transparency. Being able to update information in a fast-moving incident more easily. Reduce # of emails sent to client inboxes. More efficient workflow in an incident.

Stakeholders who want to know about an incident but aren't a client will be able to get information

Supports self-serve

# Acceptance Criteria** (Definition of done) 

- [x] Feature request: it would be useful to have hour and not just date for issues on the system status page (and a timestamp on the resolution update)
- [x] Status page is up and running.
- [x] It is easily reachable and advertised through the main website.
- [x] Maintenance windows can be communicated on the status page (future release, covered by #1414)
- [x] Notify components (API / admin) status is communicated on the page.
- [x] Templates for common issues and incidents are created and translated ready to use (separate release, covered by #1205)
- [x] "This page is a work-in-progress" caveat is removed in EN and FR

# QA Steps

- [x] Check reported status fits with actual status of the components.
- [x] Emulate a maintenance window and check on the new status page.
- [x] Emulate a bad component status report on the status page (triggering some errors on purpose).

# Additional Info

- Max and team tried out the upptime library and [deployed it over there](https://github.com/cds-snc/status-statut). [Follow this link to see the Slack conversation that provides a bit more info and context](https://gcdigital.slack.com/archives/C5SGXCMEY/p1659014283064489).
- We could add a banner to the main page when the status page shows something ongoing.
- 
# Related Research
- [Hit an issue and did not know what was causing the problem / how they can fix it](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recBPtDgIffZUR1js?blocks=hide)

**Comment by andrewleith** [comment]
Here's the direct link to the GC Notify uptime page hosted by SRE: https://status-statut.cds-snc.ca/history/gc-notify

**Comment by yaelberger-commits** [comment]
https://gcdigital.slack.com/archives/C04TQMJCXEW/p1683301346299639
Feedback from users during a system backlog due to large bulk send

**Comment by yaelberger-commits** [comment]
We have an MVP and need to iterate and improve it next

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/785?planning-poker) with Zenhub @yaelberger-commits @adriannelee @amazingphilippe @andrewleith @jzbahrai @smcmurtry @whabanks @YedidaZalik

**Comment by mtoutloff** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/785?planning-poker) with Zenhub @mtoutloff
