### ISSUE TITLE
Register the US toll-free number

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#794]
# Description

As a Notify steward,
I need to register the US toll free number that Notify already has,
so that I can keep Notify sending to US based number.

## WHY are we building?

To keep sending to US numbers.

## WHAT are we building?

Complete toll free number registration through AWS.

## VALUE created by our solution

Keep sending to American numbers.

# Acceptance Criteria** (Definition of done) 

- [ ] Have the toll free number registered before end of August.

# QA Steps

- [ ] The toll free number registration is done.

# Additional information

The toll free number is in the us-west-2 region and registration form is accessible through Pinpoint.

[Documentation around this required registration](https://docs.aws.amazon.com/sns/latest/dg/channels-sms-us-requirements.html).

> US mobile carriers have recently changed their regulations, and will require that all toll-free numbers (TFNs) complete a registration process with a regulatory body before September 30, 2022. If you currently have a toll-free number you must register your toll-free number by September 30, 2022 or you will no longer be able to use the toll-free number. You can check the status of your number by going to Toll-free number registration status. For more information about registering your company see Registering your toll-free number.
>
> It can take up to 15 business days for your registration to be processed after it is submitted.

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/794?planning-poker) with ZenHub @jzbahrai @sastels

**Comment by yaelberger-commits** [comment]
@jimleroyer is this a task I can take on with Policy in your absence? Does it require dev capacity? cc @sharlychan-cds

**Comment by jimleroyer** [comment]
@yaelberger-commits Yes feel free to take it! I can show you how to fill the form and you'll need your production account to Notify. No dev capacity required AFAIK.

**Comment by yaelberger-commits** [comment]
Pat also knows how to fill in the form

**Comment by yaelberger-commits** [comment]
Requested AWS pinpoint access for Yael from SRE team to submit the registration form.

**Comment by yaelberger-commits** [comment]
Registration has been submitted.
Doc containing content that was submitted can be found here https://docs.google.com/document/d/1kiouwb4XkZfV7vAI1DOGHQGuzqng7rsF0MgBqyGFSuc/edit?usp=sharing

**Comment by yaelberger-commits** [comment]
Review by AWS and carriers can take up to 15 business days, so this is blocked until we hear back from AWS by end of August
