### ISSUE TITLE
PTMs can request their organization to be added when they're creating a Trial account

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#795]
## Description

As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Option for choosing "other" if department doesn't exist in the list so the client can enter theirs if they don't see it in the list

**Comment by sastels** [comment]
UI part done, data side not yet (passing user data to Freshdesk)

**Comment by sastels** [comment]
data seems to be working in review app.

**Comment by sastels** [comment]
still TBD when we'll merge into staging. Possibly next week.

**Comment by yaelberger-commits** [comment]
Link when "can't find organization in dropdown" 
This is done, can be reviewed

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/795?planning-poker) with Zenhub @smcmurtry

**Comment by yaelberger-commits** [comment]
Adrianne reviewed, Steve M will look at comments. 
Andrew will review today

**Comment by yaelberger-commits** [comment]
Steve M will also write tests for this soon as well

**Comment by YedidaZalik** [comment]
Reviewed and sent to translation.
Attaching the file: https://docs.google.com/document/d/1P_yrq3LMG52qZ20SFAgeLxUaoC0W5R8_n57olPXbTUI/edit#heading=h.datdw06a6vp5

**Comment by yaelberger-commits** [comment]
Main PR, Steve M still has a few pieces left to fix for testing
Ready for Andrew later today
Resolved Adrianne's comments around validation

**Comment by yaelberger-commits** [comment]
Andrew reviewed yesterday, Steve M addressed comments, Adrianne did some a11y, ready to merge and then QA

**Comment by yaelberger-commits** [comment]
QA in Staging with feature flag
Demo of feature Thursday to decide if launching to Prod

**Comment by yaelberger-commits** [comment]
LGTM in QA in Staging 
- [ ] Once I get to step 3 of the create a service flow, I see the option to select "Not on list?" 
- [ ] When I select "Not on list?" I am brought to a new page for step 3 and I can add my own dept in a free text field 
- [ ] Once I enter text and continue, my trial service has been created. 
- [ ] If I don't enter any text, I get an error "enter name to continue"
- [ ] Works in FR UI as well with error message etc.
- [ ] If I enter too many characters into the dept field, I get an error "Désolé, nous éprouvons des difficultés techniques. Veuillez réessayer plus tard." This is expected.
