### ISSUE TITLE
Expire file attachments in link mode

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#797]
# Description

As a Notify user,
I would like my attachments sent in link mode to expire after a certain period of time,
So that I know these files are not at risk of being stored forever by a third party.

## WHY are we building?

To reduce security risk of someone getting access to files that were forever kept in our AWS storage. Increase trust with our users by respecting our data retention policies.

## WHAT are we building?

Apply an automatic expiration on files attachments sent in link mode after a certain period of time.

From indefinite retention to 7 days to align with policies.

## VALUE created by our solution

More secure and aligned with our policies.

# Acceptance Criteria** (Definition of done) 

- [x] Policies defined a time period that is acceptable for files expiration to apply.
- [x] Users are notified by email that the retention period is changing and have 1 week to adjust their content and operations before the change comes into effect
- [x] The file attachments are automatically deleted after the agreed expiration.

# QA Steps

- [x] Verify that no file attachments exist in production after the expiration time limit in the appropriate S3 bucket.

# Additional info

The files in link mode does not currently get deleted from our S3 bucket. But files sent in attach mode gets stored in a `/tmp` folder in the same S3 bucket and do have a 3 days expiration time limit. It's okay to have a low retention period for these as the files are contained in the email itself, but attachments in link mode are hosted by Notify and need a longer period of time to allow users to download these.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/797?planning-poker) with Zenhub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by andrewleith** [comment]
If there is a single, fixed expiry, is this as simple as setting an expiration policy on the bucket or a folder? (https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-expire-general-considerations.html)

**Comment by jimleroyer** [comment]
@andrewleith Yes.

**Comment by yaelberger-commits** [comment]
Steve M picked this one up on Friday

**Comment by yaelberger-commits** [comment]
Some help from Pat yesterday, PR ready for review

**Comment by yaelberger-commits** [comment]
Send comms out when ready, then give a week for users to adjust their operations to the new retention limit. 
Release feature first week of October.

**Comment by yaelberger-commits** [comment]
Email sent out September 23
Feature to be rolled out in prod Oct 3, 2022

**Comment by yaelberger-commits** [comment]
Email sent out September 23
Feature to be rolled out in prod Oct 3, 2022

**Comment by YedidaZalik** [comment]
We need to release documentation and then send out email
@andrewleith to release this morning and then will send email. Then after 1 week will re-enable expire in prod

**Comment by jimleroyer** [comment]
Added Steve A on the card as QA.

**Comment by jimleroyer** [comment]
The changes were just deployed to production:
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/530bb605-98b5-4c53-a4c5-931a1212936c)

**Comment by adriannelee** [comment]
Need to check if the files are deleted - @jimleroyer will update the card

**Comment by jimleroyer** [comment]
Just checked in production if the attachments are getting deleted after 7 days and they do. Will move the card to done.
