### ISSUE TITLE
WAF rules: geo restrict apis

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#800]
## Description

As a Notify stakeholder,
I want to reduce the fuzzy attack on Notfy,
so that our software is less discoverable with vulnerabilities
and only allow legit traffic to the web application.

We want to block users outside Canada from connecting to our apis.

**Note**: We should look at our data to ensure that we don't have traffic with a missing country code.

**Followup**: Looking at our WAF logs, there were 36 requests that had no country code. Some were fuzzing attacks while the rest were just GETing `/`.  Running these through an ip lookup tool found that none were Canadian. It is reasonable to assume that legitimate traffic will have the country code properly marked.

## QA Steps

- spin up a server in AWS / us-east-1 (manually or via [terraform](https://github.com/sastels/learn-AWS-terraform/tree/main/Misc/EC2_in_us_east)) 
- ensure that you're blocked trying to curl
  - https://api.staging.notification.cdssandbox.xyz
  - https://api.document.staging.notification.cdssandbox.xyz/_status
- ensure that you're **not** blocked hitting these from your laptop

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/800?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by amazingphilippe** [comment]
Rule is set to count instead of block. To figure out if we're blocking legitimate traffic. Moving to QA after 2 weeks of monitoring.

**Comment by jimleroyer** [comment]
This was just released to production. I QA'ed using different countries.

The requests hitting the API went through for both Canada and USA.

The requests hitting the API failed for India, UK, China, Belarus.

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/12ccf8f2-0976-4ead-a584-d5fc69682cf8)

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/f687fd3a-869c-4ccd-847e-5db26f52242d)

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/f2e3e4ce-18dd-4092-8c5e-8327c4b75c16)

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/e5a26d9a-72ac-436b-bfd8-026514d5a090)
