### ISSUE TITLE
Detect malicious content on sending of notifications

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#801]
# Description

As an ops lead or incident commander,
I need to know when notifications with malicious content is sent,
So that I can take appropriate actions to secure a compromised Notify.

## Why

To add more security to Notify, protect against phishing attempts.

## What

This card probably is an epic. 

First iteration of this could be around validating links contained within a notification against a list of vetted/trusted sources. For example, a trusted government link would score high trust where as a Facebook link would score low trust.

## Value

More peace of mind to detect security breach in Notify.

# Acceptance Criteria** (Definition of done) 

As this is an epic, the smaller tasks should have the definitive AC. Generally though:

- [ ] Raise alerts (warning or critical) when malicious content is detected.
- [ ] Score sent notifications with a numeric scale of low to high risk.

# QA Steps

As this is an epic, the smaller tasks should have the QA steps.

**Comment by yaelberger-commits** [comment]
Closing, since we're already doing scanning
