### ISSUE TITLE
Infrastructure: update Redis cluster to be multi-AZ

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#803]
# Description

As a developer,
I want to have confidence that a failure in a single availability zone will not bring down the Redis cache,
so that the Notify service is more resilient for end-users.

* Possible candidate for ADR to discuss options.

# Risk

We store our buffer notifications in Redis so if our instance goes down in one availability zone, we risk of losing many notifications and potentially have Notify API down. We need to replicate the nodes in different AZ to avoid this issue.

# Testing on Staging
We tested the migration of the REDIS cluster to the new instance. We will let celery read from the old cluster until the inbox and inflight keys don't exist. At that point we will switch redis to read from the new cluster.

# Production Migration Plan
- [x] Manual backup of old cluster @sastels 
- [x] Clear cache from admin @sastels
- [x] Merge Pr that changes REDIS_PUBLISH_URL in prod @jzbahrai 
- [x] Monitor both Redis instances @jzbahrai 
- [x] Wait upto 5 minutes for inbox and inflights to complete @jzbahrai 
- [x] Have script ready to move keys between both clusters if needed @sastels 
- [x] Merge PR to change REDIS_URL @jzbahrai 
- [x] Run prod smoke tests @sastels 
- [x] check that the old cluster has no inboxes nor inflights

# Acceptance Criteria** (Definition of done) 

- [ ] Redis cluster has nodes in multiple availability zones
- [ ]. Can we do this without bringing down Notify? Might have to turn off Redis, need a way to turn off Redis. Do this during a non-busy time. 

# QA

- [ ] Verify that we have several nodes running across different availability zones.
- [ ] Push a Redis object into one instance and observe if it gets replicated. This can be using the database cache between admin and Redis.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/803?planning-poker) with Zenhub @andrewleith @jimleroyer @jzbahrai @sastels @smcmurtry

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/803?planning-poker) with Zenhub @jzbahrai @sastels @patheard

**Comment by sastels** [comment]
I think we need to add a replication group
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.AddNode.html#AddReplication.CON

Which I think will stop and / or recreate the cluster. So we might lose the information in it...

**Comment by yaelberger-commits** [comment]
Today - Jumana continue working on redis multi zone AZ.. set up a test cluster yesterday in staging, going to look at replication today.

**Comment by jzbahrai** [comment]
There are two issues here:
1. We only have a single node on the cluster - we need read and write replicas
2. We need to make this multi-Az

We need to first add read replicas, and then add the multi -AZ.
We can keep cluster mode disabled for this
[Uploading... Screen Shot 2023-01-12 at 12.38.56 PM.png]

**Comment by jzbahrai** [comment]
Plan of action: https://docs.google.com/document/d/16iBLygzxTPfpoeOqpYYh1TPi_UFgole6zH5HFE0aizo/edit#

**Comment by yaelberger-commits** [comment]
Meeting today to go over plan with the rest of the team

**Comment by andrewleith** [comment]
- Made good progress yesterday with @sastels 
- One idea is to get celery to drain old node while api writes to the new node -> this was confirmed as working yesterday
- Will deploy and test in staging today
- Will discuss prod date soon

**Comment by adriannelee** [comment]
From Phil:
> There might be a simple “Notify is unavailable” page in the code, but we haven’t designed this page in Figma!

**Comment by andrewleith** [comment]
- process has been tested on staging
   - the plan is to write to the new one while reading from the old one
   - once the old one is empty, we will switch to the new one for both read/write
   - system will not need to go down to do this 
- rolling this out tonight at 8pm EST

**Comment by sastels** [comment]
Viewing clusters from jumpbox:

**Old Cluster**
 redis-cli -h notification-canada-ca-production-cluster-cache.y7zahu.0001.cac1.cache.amazonaws.com

**New Cluster**
redis-cli -h notify-production-cluster-cache-az-001.y7zahu.0001.cac1.cache.amazonaws.com

**Comment by sastels** [comment]
Viewing Redis clusters from jumpbox:

Old Cluster:

 redis-cli -h notification-canada-ca-production-cluster-cache.y7zahu.0001.cac1.cache.amazonaws.com

New Cluster:

 redis-cli -h notify-production-cluster-cache-az-001.y7zahu.0001.cac1.cache.amazonaws.com

**Comment by sastels** [comment]
Log into jump box.

Old Cluster:

 redis-cli -h notification-canada-ca-production-cluster-cache.y7zahu.0001.cac1.cache.amazonaws.com

New Cluster:

 redis-cli -h notify-production-cluster-cache-az-001.y7zahu.0001.cac1.cache.amazonaws.com


Inbox:

keys *inbox*

inbox:email:normal

inflights:

keys *flight*

in-flight:email:normal:e850d34e-7678-476f-81b6-975a6ef09c41


Size of inbox:

llen 


Contents of inbox:

lrange  inbox:email:normal 0 100


Dump into a new key

 rpush temp_sja "n 1" "n 2" "n 3"


Delete a key

del temp_sja

**Comment by jzbahrai** [comment]
Log into jump box.

Old Cluster:

redis-cli -h 

New Cluster:

redis-cli -h 

Inbox:

keys inbox

inbox:email:normal

inflights:

keys flight

in-flight:email:normal:e850d34e-7678-476f-81b6-975a6ef09c41


Size of inbox:

llen


Contents of inbox:

lrange inbox:email:normal 0 100


Dump into a new key

rpush temp_sja "n 1" "n 2" "n 3"


Delete a key

del temp_sja
