### ISSUE TITLE
test keys can send to arbitrary users using /bulk endpoint

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#805]
## Describe the bug 

[Test keys](https://documentation.notification.canada.ca/en/keys.html#test) can send to anyone, even for trial services, when sending through the bulk endpoint.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

SEV-3

## To Reproduce

1. go to a service
2. create a test api key
3. POST to /bulk with that api key and any email addresses
4. emails will be sent

## Expected behavior

You get a 201 response but the emails aren't actually sent.

Given a user with a Trial account is sending notifications using a Test API Key with the bulk endpoint, when they send notifications then those notifications return a 201 error and mock sending the messages, but the recipients don't actually receive any notifications.

Given a user with a trial Trial account is sending notifications to people outside of their team members or who are not on their safelist for the Team API Key, they cannot send those notifications.

## Impact

- Services could send emails they don't intend to
- trial services can send to anyone

## Additional context

https://assistance.cds-snc.ca/a/tickets/9501

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/805?planning-poker) with ZenHub @sastels @jzbahrai @andrewleith

**Comment by andrewleith** [comment]
## Code flow investigation
Emails sent via `KEY_TYPE_TEST` keys go through the entire send process (API -> redis -> SQS -> db -> celery send workers) and then stop just before actually being sent, [here](https://github.com/cds-snc/notification-api/blob/main/app/delivery/send_to_providers.py#L214).  This seems to mark the notification as `sending` and then is finished.

Not sure what updates the status from `sending` to `delivered` but my test key notifications are marked as `delivered` in the local db.

**Comment by andrewleith** [comment]
Ok so it appears when we do a post to `/bulk`, we go through `process_rows()` while we are processing the bulk job.  In there, it does not pass the `key_type` when it creates the notifications records, so when celery picks them up to send after that they default back to `KEY_TYPE_NORMAL` and the notifications get sent.

**Comment by amazingphilippe** [comment]
Trying to deploy today

**Comment by sastels** [comment]
QA'd in production
