### ISSUE TITLE
Admin review apps sometimes don't load everything

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#817]
## Describe the bug 

Admin review apps were timing out trying to fetch images and javascript. Just a one character fix.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

SEV-4

## To Reproduce

Steps to reproduce the behaviour:

- load a review app with devtools open and see the 429s (Too Many Requests) (especially with Firefox)

## Expected behaviour

- no 429s

## Impact

hard to review prs when parts of the page don't load.

## Additional context

https://gcdigital.slack.com/archives/CV38DBNVA/p1660594038600859

## QA

- [ ] load review app pages repeatedly and ensure you don't get any 429s

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/817?planning-poker) with ZenHub @amazingphilippe @sastels

**Comment by amazingphilippe** [comment]
I saw only one 429 when I started testing. Then no more. 
I did get a 500 when I tried to upload a CSV file. Probably as expected?

**Comment by amazingphilippe** [comment]
>  I did get a 500 when I tried to upload a CSV file. Probably as expected?
- As expected, but we can fix this. Steve will create another card to fix:

> for some reason, when you upload a csv, admin puts it directly into s3, it doesn't go through api. So it needs creds to our AWS account. probably missing.
(Why doesn't it use our API for this? good question!)

**Comment by amazingphilippe** [comment]
500 error ticket: #826
