### ISSUE TITLE
Properly report multiple SMS sent for billing purposes following a long notification

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/notification-planning#82]
- [x] Assess our code base.
- [x] Investigate what GDS did.
- [x] Make a decision on how to solve and the effort.

# Story

As a user, I want to know how many SMS messages I sent especially when sending long notifications that can lead to multiple sending of SMS messages.

As a Notify system admin, I want to properly bill clients sending long notifications that result in multiple SMS sending so that I stay within my department's budget.

# What?

When a user sends a notification get is long than 140 single byte encoded char, this will send multiple SMS in blocks of the previously mentioned limit. Notify does not count these properly at the current time and there could be no way to properly bill our clients with their usage.

# Why?

Because we are supposed to bill our clients that get past their SMS limit and Notify could not know if they do when they send long notifications.

# Done When

When we can count SMS messages properly for each long notification that Notify sends.

# Tips

Look into the GDS code base to see if they already addressed this issue and see if we should import their code.

**Comment by sastels** [comment]
New query
```
with data as 
(
select service_id, services.name as service_name, extract(year from notification_history.created_at) as year, extract(month from notification_history.created_at) as month, billable_units
from notification_history join services on service_id = services.id
where billable_units > 0
),
final as
(
select service_id, service_name, year, sum(billable_units) as yearly_billable_units
from data
group by service_id, service_name, year
order by year
)
select * from final
where yearly_billable_units > 25000
order by yearly_billable_units desc
```

**Comment by sastels** [comment]
big templates
```
with data as (
select distinct notification_history.service_id, services.name as service_name, template_id, templates.name as template_name, billable_units
from notification_history 
  join services on notification_history.service_id = services.id
  join templates on template_id = templates.id
where billable_units > 1
order by billable_units desc
)
select service_name, template_name, billable_units from data
limit 20
```

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/82?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels @adriannelee @amazingphilippe @YedidaZalik

**Comment by jimleroyer** [comment]
This might be considered done based on @sastels previous comments. Also, if that is a spike, we might not want to estimate this, or maybe provide a low estimation number by default if we want to keep track of some effort into the team's velocity.

**Comment by yaelberger-commits** [comment]
I wouldn't consider it done yet @jimleroyer because we only solved for part of the user story for us as admins, but the user still has no way to know how many messages they've actually sent. 
I think we could create a new card though for surfacing to the Sender how many actual text messages they've sent and then close this one?

**Comment by jimleroyer** [comment]
Ah yes, the user part is not done but seems covered by this card. I guess the remaining item to investigate in this spike then is to see if and how GDS surfaces these. We could keep it open until we know. 👍
