### ISSUE TITLE
Publish v1.5 SLA

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#827]
_Publish v1.5 SLA_

## Description

As a Notify client, I need to be able to understand my responsibilities when using the product, and those of the Notify team, so that I can make a decision whether to use Notify, and use it properly. 

https://docs.google.com/document/d/1hi2s1PJsbmo2pquG-WPm67MKKEDc8p60d7hW8E3nJCo/edit?usp=sharing

WHY are we building?
We want to embrace more of the self-serve model for Notify and allow clients to inform themselves better of what Notify has to offer, but also what their responsibilities are when they create an account and send notifications. 

We want to reduce support tickets and incidents caused by clients not having enough information to make decisions about using Notify. 

WHAT are we building?
Public, published content on GC Articles in both official languages as a first iteration.

VALUE created by our solution
All clients will have access to the same information about shared responsibilities and constraints of using Notify, without having to reach out through our Contact Us form to ask. 

Fewer clients will use Notify incorrectly, resulting in fewer preventable incidents and fewer support tickets. 

## Acceptance Criteria** (Definition of done) 

- [x] Find acceptable spot in the footer for the link to the SLA
- [x] Track any changes for quick FR content reviews by Phil
- [x] Create pages in GC Articles and URLs
- [x] Publish content
- [x] Clear the cache 

Given a client (new or old) wants to know the agreement they are entering into when they create an account and use Notify, when a user goes to the footer to read documents, then they can find the Service Level Agreement there and can read it in either EN or FR.  

(Out of scope for this card is making sure they understand the content and their responsibilities. That will come from Content testing).

* A11y
* Bilingualism
* Measuring success and metrics

## QA Steps

- [x] Test URLs in both EN and FR and working 
- [x] Use screen reader to read the content in both EN and FR
- [x] Manual A11y testing
- [x] Automated A11y scans

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/827?planning-poker) with Zenhub @adriannelee @amazingphilippe @YedidaZalik @sharlychan-cds

**Comment by adriannelee** [comment]
@yaelberger-commits is publishing the SLOs a dependency? Since the SLA v1.5 links to the SLO? (from Yedida)

**Comment by andrewleith** [comment]
PR was merged yesterday to add links to footer.
@amazingphilippe to list links!

@yaelberger-commits will QA

**Comment by amazingphilippe** [comment]
Just to make sure all links work properly. There are links to the SLO from the following pages
- https://notification.canada.ca
- https://notification.canada.ca/why-gc-notify
- https://notification.canada.ca/features
- https://notification.canada.ca/message-delivery-status

**Comment by yaelberger-commits** [comment]
API link on FR page doesn't work
![Screen Shot 2022-11-21 at 9.37.40 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/ac0bb2c0-cc12-43c9-8030-07115e09e549)

**Comment by yaelberger-commits** [comment]
Above issue has been fixed
