### ISSUE TITLE
admin crashes if contact form fails validation

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#829]
## Describe the bug 

- If you fill in the contact us form, you can't submit unless your inputs are valid. 
- However, if an attacker POSTs data directly to the contact-us page, if the data is not valid it can cause admin to crash.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 
SEV-3 : no impact on the product, but a minor impact on the on-call folks asleep.

## To Reproduce

1. POST some bad data to the contact-us form (staging plz)
2. see the server error in #notification-staging-ops

## Expected behavior

Ignore the data and don't crash

## Impact

too many of these (10 in 5 minutes) will a critical alert and OpsGenie pages.

## Additional context

```
"Traceback (most recent call last):
  File \"/usr/local/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File \"/usr/local/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File \"/usr/local/lib/python3.9/site-packages/newrelic/hooks/framework_flask.py\", line 60, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File \"/app/app/main/views/contact.py\", line 66, in contact
    if form_obj[\"next_step\"] is None and form.validate_on_submit():
  File \"/usr/local/lib/python3.9/site-packages/flask_wtf/form.py\", line 86, in validate_on_submit
    return self.is_submitted() and self.validate()
  File \"/usr/local/lib/python3.9/site-packages/wtforms/form.py\", line 329, in validate
    return super().validate(extra)
  File \"/usr/local/lib/python3.9/site-packages/wtforms/form.py\", line 146, in validate
    if not field.validate(self, extra):
  File \"/usr/local/lib/python3.9/site-packages/wtforms/fields/core.py\", line 268, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File \"/usr/local/lib/python3.9/site-packages/wtforms/fields/core.py\", line 288, in _run_validation_chain
    validator(form, self)
  File \"/app/app/main/validators.py\", line 90, in __call__
    validate_email_address(field.data)
  File \"/usr/local/lib/python3.9/site-packages/notifications_utils/recipients.py\", line 419, in validate_email_address
    email_address = strip_and_remove_obscure_whitespace(email_address)
  File \"/usr/local/lib/python3.9/site-packages/notifications_utils/formatters.py\", line 311, in strip_and_remove_obscure_whitespace
    value = value.replace(character, \"\")
AttributeError: 'NoneType' object has no attribute 'replace'"
```

**Comment by yaelberger-commits** [comment]
@sastels is this also resolved through the WAF rules?

**Comment by yaelberger-commits** [comment]
Still in play

**Comment by jzbahrai** [comment]
Going through this:

this is how you replicate it:
Make a post to the below:
https://staging.notification.cdssandbox.xyz/contact
with a bad query string

If you make the post when you are logged out - you get a 200
If you make the post when you are logged in - it throws a 400

Given that the error only happens when you are logged in.. I spent sometime looking at the code but not too long on trying to fix it
We will leave the behaviour as is - the status quo will not cause our site to crash.
