### ISSUE TITLE
Set default daily SMS message part limit per Live service to 1,000

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#837]
_Set default daily SMS message part limit per live service to 1,000_

## Description

As a Notify sender, I need to be able to send many SMS messages in a day to many recipients so that I can notify people about various things. 

As a Notify admin, I need to be able to limit the number of SMS message parts a sender can send in a single day or in a minute, so that I can ensure the stability and reliability of Notify's SMS service as a whole, and control cost of SMS sending to reduce chances of an incident. 

WHY are we building?
We've had issues in the past where a service sending too many SMS/minute or per sec can risk our phone numbers getting flagged as sending spam and being blocked. 

WHAT are we building?
An enforced daily limit of 1,000 SMS message parts per live service per day

VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

Given a new service is created, when they want to send SMS, then they can only send a maximum of 1,000 text message parts per day _by default_ 

- [x] Set the limit to 1000 / day for new services
- [x] Set the limit for current services sending about 1000 / day to something more than they currently send
- [ ] Clients know in the UI at the right places when they go live that they can only send 1,000 SMs per day
- [ ] Clients are stopped by default from being able to send more than 1,000 SMS a day when they go live
- [ ] Clients know that they can request an increase if needed and we will assess

Given some context, when (X) action occurs, then (Y) outcome is achieved 

#Notes

- We might be able to validate their bulk upload or CSV size

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/837?planning-poker) with Zenhub @andrewleith @jimleroyer @jzbahrai @sastels @amazingphilippe

**Comment by sastels** [comment]
Query to find services that have sent more than 1000 message parts in a day
```sql
with data_nh as (
    select n.id, n.created_at::TIMESTAMP::DATE as created_at, n.billable_units as billable_units,
        service_id, s.name as service_name
    from notification_history n join services s on n.service_id = s.id
    where n.notification_type = 'sms' and s.count_as_live
        and n.created_at > '2022-04-01'
),
data_n as (
    select n.id, n.created_at::TIMESTAMP::DATE as created_at, n.billable_units as billable_units,
        service_id, s.name as service_name
    from notifications n join services s on n.service_id = s.id
    where n.notification_type = 'sms' and s.count_as_live
),
data as (
    select * from data_nh
    union
    select * from data_n
),
rollup as (
    select created_at, service_id, service_name, sum(billable_units) as billable_units, count(*) as count
    from data
    group by service_id, service_name, created_at
),
bigger_than_1000 as (
    select * from rollup
    where billable_units > 1000
    order by created_at desc
),
biggest_days as (
    select service_id, service_name, max(billable_units) as max_billable_units
    from bigger_than_1000
    group by service_id, service_name
    order by max_billable_units desc
)
select * from biggest_days
```

Finds 10 services.

**Comment by YedidaZalik** [comment]
Scoped into other cards. Closing for now.
