### ISSUE TITLE
Collect email bounce rate per service

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#842]
# Description

As a ops lead,
I need the bounce rate per service,
So that I can track which service might represent a reliability risk within Notify.

As a service owner,
I need the bounce rate for my service,
to avoid getting shutdown by Notify's admins
and track my distribution list health.

## WHY are we building?

Scale more by allowing services to have bigger limit increase without risking Notify's stability with an emergency break, but we need to collect the bounce rate per service first.

## WHAT are we building?

A way to keep track of bounce rate per service on a daily basis.

## VALUE created by our solution

Enforce bounce rate on service as the same that is imposed on Notify so that we can better scale. Identify Notify's citizens that misbehave.

# Acceptance Criteria** (Definition of done) 

- [x] The bounce rate for each service is provided in real time in the service dashboard
- [x] Alarm in #notification-ops for when a service breaches 10% bounce rate

# QA Steps

- [x] The bounce rate for each service is provided in real time in the service dashboard
- [ ] Alarm in #notification-ops triggers when a service breaches 10% bounce rate

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/842?planning-poker) with Zenhub @sastels @jzbahrai @andrewleith

**Comment by jimleroyer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/842?planning-poker) with Zenhub @smcmurtry

**Comment by sastels** [comment]
in progress

**Comment by sastels** [comment]
work in progress but @jzbahrai is going on call today so a bit up in the air.

**Comment by jimleroyer** [comment]
@andrewleith We had an [offline talk](https://gcdigital.slack.com/archives/C04RU1B0YJ1/p1678385493195259?thread_ts=1678285828.422409&cid=C04RU1B0YJ1) with Andrew, Jumana, Yael about the alarm and decided that the 10% breach would be a warning for the first 2 weeks and not a critical alarm to avoid support paging and have time to assess how many services are actually breaking the 10% bounce rate.
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/30750bf1-388f-4e9e-ae5c-bd062af5d92f)

**Comment by yaelberger-commits** [comment]
Was merged on Tues, caused an issue in Staging and breaking. Deployed Wed, Jumana reverted, on call. On pause until someone else can pick up

**Comment by YedidaZalik** [comment]
Yael moved to in progress because working on last week. Steve has been working on and has simplified implementation. Will expand on more in ADR. Staying in progress.

**Comment by yaelberger-commits** [comment]
I updated the Acceptance Criteria and QA lists to reflect the change to providing the data in real time

**Comment by YedidaZalik** [comment]
Steve worked on it yesterday and some pair programming with Will
Almost done - a few PRs are open which all need to get merged

**Comment by amazingphilippe** [comment]
Passing tests on open PRs: @smcmurtry 
Problems with WAF rules: @whabanks

**Comment by amazingphilippe** [comment]
Tests PRs are merged. More testing. WAF rules solved. Moving to QA

**Comment by amazingphilippe** [comment]
Steve needs a PR review on notification-api to update utils. @Will will review
