### ISSUE TITLE
Surface service bounce rate for emails to users

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#843]
# Description

As a service owner,
I need to know the bounce rate for my service,
to avoid getting shutdown by Notify's admins
and track my distribution list health.

As an ops lead,
I need to know the bounce rate for individual services,
So that I can take proactive actions with service owners before their service gets shutdown.

Related incident https://docs.google.com/document/d/1cUHn1P9UXHuFDrzWw3E1qaxmu9Zz5cu-aPRO4VlIeWY/edit?usp=sharing

## WHY are we building?

Scale more by allowing services to have bigger limit increase without risking Notify's stability with an emergency break, but we need to surface the bounce rate to users first.

## WHAT are we building?

A display of the bounce rate to the service owners (through the dashboard for example).
Healthy bounce rate (below 5%)
Warning bounce rate (between 5% and 9%)
Critical bounce rate (10% and over)

Calculated and shown every 5 mins, rate is calculated over a 24 hour period

![image.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/47548bfd-2073-4007-a879-241a5a95ddff)

## VALUE created by our solution

Inform and educate our users on their service's bounce rate behavior. Potentially increasing Notify's reliability by avoiding Notify being locked out of its ability to send emails if getting past its own bounce rate limit.

# Acceptance Criteria** (Definition of done) 

- [x] The users of each service are able to retrieve the service daily bounce rate by logging in to their account, selecting a service and looking at their service dashboard.
- [x] We know the bounce rate per service in a summary view (such as the live services view in the admin panel) similar to what we currently see for notifications sent in admin panel. (covered by Blazer query for release 1.0)
- [x] Colour changes from green to red to signify change in status
- [x] Status goes from caution to critical when a service's bounce rate rises from below 5%, to between 5-9%, then to 10% or over

## QA Steps

- [x] Target a service with high amount of daily failures and check its daily bounce rate.
- [x] Test in Staging sending a large number of emails to addresses we know will bounce to see if it displays in the dashboard properly by taking a list of emails out of the suppression list or faking a few emails and triggering these to be added.

## Additional Info

Can we send more messages during slow period to help insulate our bounce rate?
Start with emails as those can bring Notify down
Need to determine whether metric is daily or more long term 
Raise calculation to AWS support
Correlate with what we experienced in incident channel

in bounce rate faq:
Q5. Over what period of time is my bounce rate calculated?
We don't calculate your bounce rate based on a fixed period of time, because different senders send at different rates. Instead, we look at a representative volume—an amount of email that represents your typical sending practices. To be fair to both high- and low-volume senders, the representative volume is different for each user and changes as the user's sending patterns change.
https://docs.aws.amazon.com/ses/latest/dg/faqs-enforcement.html

## Dev implementation
- [x] Inaccurate email addresses page
    - [x] New "big number" macro to display inaccurate addresses / emails sent
    - [x] New partial to break down Inaccurate email addresses per csv list
- [x] Dashboard improvements
    - [x] Add inaccurate addresses status block  that links to the Inaccurate email addresses page
    - [x] Link to review addresses page from new status block
    - [x] Enhance failure widget
- [x]  "Review email problems" page
    - [x] Provide guidance
    - [x] Display email problems
- [x] Find and fix problem emails
    - [x] Filter by problem addresses
    - [x] Add review column
- [x] Update status labels
    - [x] In API (downloadable CSV reports)
    - [x] in ADMIN (dashboard, etc.)
- [x] Update translation csv file

## Source documents
- [English content and designs](https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?node-id=680-9816)
- [Français contenu et design](https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?node-id=760-10421)

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/843?planning-poker) with Zenhub @sastels @smcmurtry @jzbahrai @andrewleith

**Comment by YedidaZalik** [comment]
@yaelberger-commits please review esp scoping on this card to just be for emails

**Comment by yaelberger-commits** [comment]
Moving back to Product backlog

**Comment by yaelberger-commits** [comment]
Is there any way in Staging to test sending a large number of emails to addresses we know will bounce to see if it displays in the dashboard properly?

**Comment by jimleroyer** [comment]
@yaelberger-commits That should be feasible, by taking a list of emails out of the suppression list or faking a few emails and triggering these to be added.

**Comment by adriannelee** [comment]
Figma file: https://www.figma.com/file/w1rwZuxuh8D6SGskv0KPaK/Bounce-rate?node-id=17%3A702&t=qckoFP8Yib1WNlDy-1

**Comment by sastels** [comment]
demoing today!

**Comment by sastels** [comment]
iterating on the design. MIght present at SST. Taking to content critique this morning.

**Comment by sastels** [comment]
will demo recent changes today.

**Comment by sastels** [comment]
will demo recent changes today.

**Comment by YedidaZalik** [comment]
Figuring out where to link to new guidance page from new Review screen.

**Comment by sastels** [comment]
Adrianne and Will met to refine design

**Comment by YedidaZalik** [comment]
Have now linked to new guidance page from the screen.

**Comment by yaelberger-commits** [comment]
Thurs Adrianne and Yedida synced about review email addresses screen. Adrianne will demo today
Adrianne mapped out screen and different states

**Comment by yaelberger-commits** [comment]
UI elements for dashboard and review email addresses are complete.
Will now working on message delivery status page

**Comment by yaelberger-commits** [comment]
Adrianne and Yedida are working on including API problem email addresses to the design. Mocked up 2 ideas yesterday. Currently showing stats for last 7 days in dashboard, changed to last 24 hours. Adrianne will sync with devs today to get on the same page about that. 
PM will join
Will the change just be for dashboard or also for reports too?

**Comment by yaelberger-commits** [comment]
Finished design annotations, working on a11y annotations next

**Comment by yaelberger-commits** [comment]
@YedidaZalik has some content to update in Figma (list of statuses)

**Comment by YedidaZalik** [comment]
Attaching the documents that give content for statuses
https://docs.google.com/document/d/1Osm0Qcu6bqJjdTIlFMjOSIQ3opkiCXUh45BzHpxfVlQ/edit#heading=h.j2cmchdsw7qj
https://docs.google.com/document/d/1QeOIdo2tu6AX1Pe1kLA0qMs3eT8RKIhq8U-y7v5Tt0o/edit#heading=h.j2cmchdsw7qj

**Comment by yaelberger-commits** [comment]
@andrewleith working on some UI implementation

**Comment by YedidaZalik** [comment]
Andrew working on this, PR is in draft, he's going to fix some failing tests but functionality is there.

**Comment by yaelberger-commits** [comment]
Still need links to Guidance so we can put those in

**Comment by andrewleith** [comment]
This is in staging, currently being tested.

**Comment by amazingphilippe** [comment]
- Merge into prod with feature flag off
- QA that nothing shows up as expected

@yaelberger-commits 
What to look for:
1. Problem addresses
2. Filter checkbox
2. New column in report table
