### ISSUE TITLE
Write ADR on bounce rate emergency brake

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#845]
# Description

As a Notify developer,
I need to document how the bounce rate will work and apply,
So that I can answer the how and what on the bounce rate emergency break epic.

## WHY

To document and explore our options around bounce rate emergency break.

## WHAT

An [architectural decision record](https://github.com/cds-snc/notification-adr/blob/main/records/20xx-xx-xx.TEMPLATE.md).

## VALUE

Explore, communicate, review and document.

# Acceptance Criteria** (Definition of done) 

- [x] ADR is written, peer reviewed and approved.
- [x]  A few questions are answered *

* These questions:

1. Will the emergency break apply the same on low and high traffic? Can we differentiate these and apply a different algorithm.
2. How can we collect the bounce rate? where do we store it?
3. How can we surface the bounce rate to the user?
4. How can we surface the bounce rate through our AWS metrics dashboards? 
5. How can we keep track of bounce rate per service?

# QA Steps

- [ ] Peer reviewed and approved.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/845?planning-poker) with Zenhub @andrewleith @jimleroyer @jzbahrai @sastels @smcmurtry

**Comment by yaelberger-commits** [comment]
Andrew made some changes, in Draft mode. Ready for dev review

**Comment by smcmurtry** [comment]
- @andrewleith in discussion with @jimleroyer to finalize this
- opened support case with AWS to figure out one part of this

**Comment by yaelberger-commits** [comment]
@yaelberger-commits reviewed the ADR today. LGTM!

**Comment by YedidaZalik** [comment]
Jimmy has reviewed and approved
Can be merged into repo

**Comment by yaelberger-commits** [comment]
Finished part of this, work on another plan to simplify today.

**Comment by yaelberger-commits** [comment]
@jzbahrai this needs updating to align with some recent changes, right? I'll leave it in Review so we can add the new content to the ADR

**Comment by YedidaZalik** [comment]
Yael put in review as reminder to add changes. Since Jumana is away, it will stay here.

**Comment by YedidaZalik** [comment]
Needs further changes so will stay open
