### ISSUE TITLE
Request increase in # of longcodes from AWS

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#846]
_Request increase in # of longcodes from AWS_

## Description

As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
@jimleroyer Is this done? Are we up to 50 now?

**Comment by jimleroyer** [comment]
We have 50 long codes in production ca-central-1 region, but our rate is restricted to 20 messages / second by AWS. I reviewed the daily pattern though and we might not need as high for the time being. I am thinking of potentially asking less and slowly raising the sending capacity on notify side.
