### ISSUE TITLE
Instructions for variables can be confused

### ISSUE THREAD

**Issue by amazingphilippe** [cds-snc/notification-planning#847]
## Describe the bug 

In https://github.com/cds-snc/notification-admin/pull/1316

We introduced instructions for conditional variables that looked like a radio input field. This helps understand and reinforce the concept of conditional variables. 

Unfortunately, nothing prevents you to name a string and conditional variable with the same name. Take this template as an example:
```
((foo)) and ((foo??bar)).
```

The bug: Whichever variable is last in the template will dictate what kind of instructions are displayed. In our example above, a radio field will be displayed, and the value "yes" or "no" will fill variable ((foo)). This will be the result:

```
no.
```

or

```
yes bar.
```

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-4 Low

## To Reproduce

1. Create the example template
2. Send a test to yourself
3. Follow the instructions
4. Switch the variable order
5. Send a test to yourself
6. Follow the instructions and notice how the variable order affects the instructions

## Expected behavior

A simple thing would be to default to the old behaviour, which would be a string field whenever a variable is present as 2 different types. 

## Impact

Impact on Notify users: Seems like a glitch

Impact on Recipients: Probably none

Impact on Notify team: Probably none

## Screenshots

![Capture d’écran, le 2022-09-01 à 09.22.29.png](https://images.zenhubusercontent.com/614b439e980ccd4137400d3e/4d7c707d-e519-4ac7-8acd-16ab2374272b)

**Comment by yaelberger-commits** [comment]
PR up that could use review

**Comment by jimleroyer** [comment]
Released in production, tested and working!
