### ISSUE TITLE
Unable to send to simulated email addresses using TEAM api keys

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#855]
## Describe the bug 

The [docs state](https://documentation.notification.canada.ca/en/testing.html#smoke-testing) that any API key type can be used to send to the simulated addresses but this currently does not work with team keys.

### [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-3 low, the user can generate a TEST key to conduct smoke testing

### To Reproduce
1. From a trial or live service, create a TEAM API key
1. Send an email to simulate-delivered@notification.canada.ca or an SMS to 16132532222

### Expected behavior
1. Email is indicated as sent (201 OK HTTP status code)

### Impact

Impact is low, users can generate a TEST api key in order to do smoke testing.

## Acceptance criteria
- [ ] Emails can be sent to simulated addresses (simulate-delivered@notification.canada.ca", "simulate-delivered-2@notification.canada.ca", "simulate-delivered-3@notification.canada.ca",) using TEAM API key
- [ ] SMSs can be sent to simulated numbers ("+16132532222", "+16132532223", "+16132532224") using TEAM API key
- Client is notified via freshdesk when fix is released (https://cds-snc.freshdesk.com/a/tickets/9587)

**Comment by ramya-cds** [comment]
Freshdesk ticket - https://cds-snc.freshdesk.com/a/tickets/9587
