### ISSUE TITLE
Enforce AWS WAF anonymous ruleset to block

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#857]
# Description

As a Notify stakeholder,
I want to reduce the fuzzy attack on Notify, 
so that our software is less discoverable with vulnerabilities
and only allow legit traffic to the web application.

## WHY are we building?

Limit the fuzzy attacks on Notify.

## WHAT are we building?

Set the [WAF anonymous ruleset](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-ip-rep.html#aws-managed-rule-groups-ip-rep-anonymous) from `count` to `block`.

## VALUE created by our solution

Fuzzy attacked perpetrated by anonymous sources (e.g. Tor or dedicated proxies) will get blocked.

# Acceptance Criteria** (Definition of done) 

- [x] Anonymous IP sources get blocked after enabling the AWS anonymous ruleset.

# QA Steps

- [x] We could try to access Notify through Tor to test it out.

**Comment by YedidaZalik** [comment]
To release this morning and then Jimmy will move to QA

**Comment by YedidaZalik** [comment]
Focus on WAF rules today
@jimleroyer and @andrewleith to sync

**Comment by jimleroyer** [comment]
This is set to be released on the week of Oct 17th. Rules is working as intended in staging.

**Comment by YedidaZalik** [comment]
Hopefully to release this morning.

**Comment by YedidaZalik** [comment]
Needs QA in a week
Deployed in prod
@jimleroyer to monitor

**Comment by adriannelee** [comment]
Not sure for today.

**Comment by jimleroyer** [comment]
Checked traffic in production matched by this rule and there was none. It is a very low low matching rule. We should be good!

**Comment by yaelberger-commits** [comment]
@jimleroyer Can you please check off the items in the checklist and move this to Done if it's complete?

**Comment by adriannelee** [comment]
Up for QA by Andrew

**Comment by jimleroyer** [comment]
Andrew and I QA'ed the rule by accessing the admin via the Tor browser and it worked:
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/14527daf-8b1b-4136-beab-eaecd012e3e0)
