### ISSUE TITLE
Inconsistent notification counts

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#860]
## Describe the bug 

1. When using the admin dashboard, you can get differing notification counts than what a user may expect when using various filters.
2. When using a service dashboard, the count of notifications is different on the dashboard and the details pages.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-3 

### Stats seen via admin of a particular service:
- On the admin dashboard, no filters
![image.png](https://images.zenhubusercontent.com/558ca3104f7a08fbb7f36ec0/e861611b-d4b8-4fb7-9341-ec2e3a627324)
- On the admin dashboard, filtered for the last week:
![image.png](https://images.zenhubusercontent.com/558ca3104f7a08fbb7f36ec0/a7c51445-45e2-4876-b93b-fa3f2496d8b6)
- On the admin dashboard, filtered for the past day:
![image.png](https://images.zenhubusercontent.com/558ca3104f7a08fbb7f36ec0/85936752-7531-4c74-aad8-f7d56c33f989)

### Stats seen via the service dashboard:
- From the services dashboard:
![image.png](https://images.zenhubusercontent.com/558ca3104f7a08fbb7f36ec0/2e976be0-a9d3-4ce5-ac22-b7dcc3355820)
- When you click on the stats in the services dashboard:
![image.png](https://images.zenhubusercontent.com/558ca3104f7a08fbb7f36ec0/8870e5c1-5155-44a5-a424-8b1c1d50f6d0)

## Expected behaviour
- The admin dashboard with no filters should be displaying today's stats, but it is not 
- The admin dashboard should say what period it is displaying for the stats
- Filtering the dashboard by the past week should match the data seen on the services dashboard page
- When clicking on the "sent in the last week" dashboard item, the stats that are displayed should match those on the dashboard page
 
## Impact

- Impact on Notify users:
  - These inconsistencies may lead users to question which stats are correct and if we are tracking stats properly
- Impact on Recipients:
   - None
- Impact on Notify team: 
   - Could cause confusion when troubleshooting

**Comment by whabanks** [comment]
Initial investigation / thoughts:

The admin panel correctly displays the messages for the current day. Verified this on staging and in the code.

According to code comments, on the Service Dashboard we pull messages starting from midnight of `current_time - 7 days` converted to UTC accurate down to the hour. 

If you navigated to the dashboard at `2023-04-03 16:24 UTC`, the resulting time that we'll start looking for messages is: `2023-03-29 04:00 UTC`. 

With the above time example we might be losing about 4 hours worth of messages, as the Admin Dashboard will pull everything starting at `2023-03-29 00:00 UTC` and the Service Dashboard will pull starting at `2023-03-29 04:00 UTC`.  

Further testing to verify this theory is ongoing.

**Comment by whabanks** [comment]
The Admin Dashboard looks to the `ft_notification_status` table to get the per service statistics. This table is [updated every day at 12:30AM EST](https://gcdigital.slack.com/archives/CV38DBNVA/p1680719019072849). Discrepancies between what we see on the admin dashboard vs the service dashboard when we filter down to a time period that includes "today" could just be a result of the nightly task to update `ft_notification_status` not being run yet.

Additionally, in the service dashboard it appears we [filter out "cancelled" notifications from the counts](https://github.com/cds-snc/notification-admin/blob/523da32e2923abe665bfb0eb96c14a02926fc275/app/main/views/dashboard.py#L160) which would create further discrepancies between the admin dashboard and service dashboard.

**Comment by andrewleith** [comment]
- Investigation started, work ongoing

**Comment by YedidaZalik** [comment]
Will to merge when returns.

**Comment by whabanks** [comment]
Paired with @andrewleith and we got to the bottom of this elusive issue! In short, when we ran a query for a certain time window, the upper and lower bounds of the date range were different time zones, resulting in these inconsistent results.
[More details in the thread!](https://gcdigital.slack.com/archives/C04RU1B0YJ1/p1681839803343059?thread_ts=1681833155.377499&cid=C04RU1B0YJ1)

**Comment by whabanks** [comment]
This issue is resolved by: https://github.com/cds-snc/notification-api/pull/1836

**Comment by yaelberger-commits** [comment]
PR up for this, needs review, merge then QA

**Comment by yaelberger-commits** [comment]
@whabanks Has this one been merged? Do you need a volunteer dev to QA it?

**Comment by YedidaZalik** [comment]
Merged 
Andrew to QA

**Comment by andrewleith** [comment]
The stats are certainly closer now but I think we still have other issues causing discrepancies.  Since we will be looking at this again when we update the time period the dashboard uses for bounce rate to be a true 24 hour period, I think we could consider this done and continue on that ticket.  @yaelberger-commits is that ok with you?

**Comment by yaelberger-commits** [comment]
Moving to Done
