### ISSUE TITLE
Design: Make limits more visible

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#865]
_Make limits more visible _

## Description

As a Notify Sender, I need to be able to track how many text messages I've sent today so that I can plan to send more sms messages within my limits.

As a Notify Sender, I need to be able to track how many text messages I have left for the day so that I don't get cut off from sending text message notifications mid-job. 

Respecting our infrastructure capacity.

Show daily and yearly limits on the dashboard page, with warning indicator when >=XX% [ADMIN]

Prototype A (expose fragments) ???
- [ ] design prototype for testing with group A of users
- [ ] expose sms fragments in from notifications table to dashboard 
- [ ] when creating a template, "this template is going to be # fragments long"
- [ ] expose before they send, at the review stage how many fragments you will be sending so users can plan better by having this information earlier in the flow
- [ ] more accurate communication of limits (more limits than Prototype B) and better prediction of limits for us
- [ ] The SMS limit applies but operational on notification fragments.

Prototype B (no fragments)
- [ ] design prototype for testing with group B of users
- [ ] Add character counting (with some limitations) to template editing stage
- [ ] Use SMS character limit of 612 including variables
- [ ] Show tip for the counter: template length will increase once/if variables are added
- [ ] Reject template if it's over 612 characters when saving 
- [ ] If template ends up being larger than 612 characters when ready to send, it will fail and user will get an error message if variables are too long 
- [ ] Dashboard show how many text messages have been sent, how many are left for the day
- [ ] The SMS limit applies but operational on notifications (not fragments).

## Acceptance Criteria** (Definition of done) 

Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] Error message should match character counter

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Update queries to get the data over to ADMIN
Do this today to be able to give data over to Phil

**Comment by yaelberger-commits** [comment]
Need to sync on requested vs delivered
Don't update limits until after notifications have been sent. User might send over their limits

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/865?planning-poker) with Zenhub @andrewleith @sastels @smcmurtry

**Comment by smcmurtry** [comment]
UI work on the dashboard in progress:
![Screen Shot 2022-09-27 at 4.05.39 PM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/78bd9f50-f4a4-4864-bbd6-1a93a6102fb3)

**Comment by yaelberger-commits** [comment]
Steve M has a PR in progress to add numbers to dashboard
Andrew put up a PR this morning to get data from API

**Comment by amazingphilippe** [comment]
Started work in Figma. Link: https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?node-id=129%3A981

**Comment by jimleroyer** [comment]
Some reviews to do this morning and to plan with the team.

**Comment by jimleroyer** [comment]
Waiting for translation.

**Comment by andrewleith** [comment]
- Waiting on translation for one prototype still
