### ISSUE TITLE
Address highest priority SNYK issues

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/notification-planning#87]
Time boxed to one day of work. We will repeat each sprint.

**Comment by jimleroyer** [comment]
That would be a routine maintenance. The list will change as time goes by, but we can drop a list at the time when someone takes care of it.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/87?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by yaelberger-commits** [comment]
@andrewleith Will update summary so we can estimate properly given some have been resolved

**Comment by andrewleith** [comment]
Updated and triaged list here: https://docs.google.com/spreadsheets/d/16CKFnP5Ap3bGwPMkx9Fq7yM2ngL107M008HKOJA0yhY/edit?usp=sharing

**Comment by adriannelee** [comment]
Updated admin. One is a license issue - not a code issue. The other is a library that has no [?]

Doing the scheduler this morning.

**Comment by andrewleith** [comment]
All done. Remaining issues that cannot be fixed:
- License issues (affecting admin and api) - this has been moved into its own card #768 
- 1 high severity issue affecting admin - `flask-caching` library has no remediation available yet

**Comment by adriannelee** [comment]
Have to decide what to do with license issues. Need to talk about extra issues with dev team

**Comment by andrewleith** [comment]
This is complete.  The one remaining issue has been deemed not an actual vulnerability, and we will snooze the other issues so this is now done.
