### ISSUE TITLE
Add support SLOs to Contact Us form confirmation page

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#876]
_Add support SLOs to Contact Us form confirmation page_

## Description

As a Notify user, I need to know how quickly my request, question or issue will be addressed by the Notify team, so that I can update stakeholders, resolve a problem, carry on using Notify etc. 

WHY are we building?
We want to be more explicit with our users about our service levels for support so they know what to expect. 

WHAT are we building?
Content on the Contact us form confirmation page

VALUE created by our solution
Users will know at the time they submit their form how soon they should expect a response
Could reduce the number of support tickets that are duplicates

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given a user submits a support ticket using the Contact Us form, when they hit submit, then they are brought to a confirmation page that says we will respond within 1 business day and to include certain language if it is an urgent issue like a security incident or breach etc. 

- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by amazingphilippe** [comment]
Link to SLOs have been on our contact us page for a while now. Closing.
