### ISSUE TITLE
Upgrade our Redis engine version from 6.2.5 to 6.2.6

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#877]
# Description

As a ops lead of Notify,
I want to upgrade the Redis engine version to the latest,
So that I can avoid hiccups that an automatic upgrade could cause happening during day time if we don't update on our own terms (at appropriate downtime period).

## WHY are we building?

To avoid hiccups on our Redis cluster.

Also, to do and test it ourselves before AWS does it automatically (see [discussion](https://gcdigital.slack.com/archives/CV38DBNVA/p1663849492509289?thread_ts=1663849475.064249&cid=CV38DBNVA))
## WHAT are we building?

Upgrade the Redis engine version.

## VALUE created by our solution

Have our stack running latest Redis version and controlling upgrade schedule to be more reliable.

# Acceptance Criteria** (Definition of done) 

- [ ] The Redis engine version is set at 6.2.6

# QA Steps

- [x] Verify in AWS console for Elasticache that the Redis version is set at 6.2.6.
- [ ] Connect to one of our Redis node and verify the cache still works as expected. (see [Tricks and Tips](https://docs.google.com/document/d/16LLelZ7WEKrnbocrl0Az74JqkCv5DBZ9QILRBUFJQt8/edit#heading=h.48lixzxrgi8k))

**Comment by sastels** [comment]
Will need to have the staging kubectl issue fixed before we can connect to the staging redis.

**Comment by jimleroyer** [comment]
@sastels Hence why I was asking around about this issue. ;) 

But we're good now, we can proceed.

**Comment by YedidaZalik** [comment]
Done - unless someone can check version in prod.
@jzbahrai will take it on.

**Comment by andrewleith** [comment]
#### Staging - output from `INFO` in `redis-cli` ✅ 
```
# Server
redis_version:6.2.6
```

#### Production - output from `INFO` in `redis-cli` ✅ 
```
# Server
redis_version:6.2.6
```
