### ISSUE TITLE
Renovate for notification-utils

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#879]
# Description

As an ops lead,
I want Notify to use renovate,
So that is up to date with latest libraries 
and dependencies management best practices.

## WHY are we building?

Security, best practices, maintenance.

## WHAT are we building?

Integration of renovate within our repository.

## VALUE created by our solution

Security, best practices, maintenance.

# Acceptance Criteria** (Definition of done) 

- [x] Renovate configuration is merged within the repository.
- [x] Renovate dashboard is functional within the repository.
- [x] The Renovate dependencies pinning PR was merged within the repository.
- [x] We can merge PRs of dependency bumps suggested by renovate within the repository.

## QA Steps

- [x] The Renovate dependencies pinning PR was merged.
- [x] A Renovate dependency bump PR was merged within the repository.

**Comment by patheard** [comment]
Now that the Renovate schedule has been expanded to run over the weekend, dependency bump PRs were successfully created.

**Comment by YedidaZalik** [comment]
@jimleroyer  has to test for 4th completion criteria and he's the second set of eyes bc Pat opened

**Comment by YedidaZalik** [comment]
@andrewleith will review

**Comment by YedidaZalik** [comment]
Merged PR but didn't work 
@jimleroyer will continue

**Comment by YedidaZalik** [comment]
Tested, something didn't work, so needs to stay in QA
@jimleroyer will continue

**Comment by adriannelee** [comment]
No time for it today

**Comment by adriannelee** [comment]
@andrewleith will pick up QA

**Comment by jimleroyer** [comment]
We seem to be OK with the github actions properly executing following merges from a Renovate PR changes. We can move this to done if @andrewleith is OK with it (unless he wants to QA it as well).

**Comment by andrewleith** [comment]
Looks good, I merged some of the renovate PR's already (https://github.com/cds-snc/notification-utils/pull/144 and https://github.com/cds-snc/notification-utils/pull/147)
