### ISSUE TITLE
Bug - Our AWS Pull Request Review App throws an error when uploading a CSV 

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#889]
After trying to upload a CSV in our PR review app, I see the "Sorry, we’re experiencing technical difficulties" page.

Sentry logs the following errors:
[ClientError main.send_messages](https://sentry.io/organizations/canadian-digital-service/issues/3420796750/?project=1522933&referrer=slack)
and
[Unable to upload file to S3 bucket notification-canada-ca-staging-csv-upload
](https://sentry.io/organizations/canadian-digital-service/issues/3420796725/?project=1522933&referrer=slack)

This will require fixing the review app's permissions in terraform: https://github.com/cds-snc/notification-terraform/blob/main/aws/lambda-admin-pr/iam.tf

**Comment by yaelberger-commits** [comment]
Works in staging, but would be good to have in review app as well

**Comment by yaelberger-commits** [comment]
Duplicate of #826 closing this one, keeping the other open
