### ISSUE TITLE
api lambda configuration inconsistant

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#890]
api lambda gets most of its configuration from the encrypted variable files in the [manifest repo](https://github.com/cds-snc/notification-manifests), but some comes from the [terraform repo](https://github.com/cds-snc/notification-terraform/blob/main/aws/lambda-api/lambda.tf#L23-L44).

From Pat:

> the way it’s setup, is these take precedence:
https://github.com/cds-snc/notification-terraform/blob/main/aws/lambda-api/lambda.tf#L23-L44
and then values will fall back to whatever is in the ENVIRONMENT_VARIABLES ParameterStore
but it could certainly use some cleanup, and there are a few minor differences in config between the lambda and k8s api
(or at least, there used to be back when I was working on the project in Feb/March)

If we don't clean this up it's likely to come back to haunt us at some point.

**Comment by yaelberger-commits** [comment]
Core is taking care of this, we've changed out configuration since then
