### ISSUE TITLE
Clarify file retention link email and documentation

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#895]

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/895?planning-poker) with Zenhub @amazingphilippe @YedidaZalik @sastels @jimleroyer

**Comment by YedidaZalik** [comment]
Sent content to translation
Will ask folks to review when back and add document. 
Expected back on Weds.

**Comment by YedidaZalik** [comment]
FR back from Translation: https://docs.google.com/document/d/1upoX-P3AYcAYJ2PtuT0A5jsoZi5tM1HU8jkp3JPBErE/edit#heading=h.gjdgxs

Sending to @amazingphilippe for review

**Comment by amazingphilippe** [comment]
[Documentation](https://documentation.notification.canada.ca/fr/envoyer.html#l-envoi-de-fichiers-par-courriel-est-une-fonctionnalite-unique-a-l-api) is also released in both languages

**Comment by YedidaZalik** [comment]
Email sent this afternoon
