### ISSUE TITLE
Redirect api.notification.alpha.canada.ca to official URL

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#896]
# Description

As a (user), I need to be automatically redirected to the primary production notify site if I try to access the old alpha URL.

Use a `CNAME` record to update `api.notification.alpha.canada.ca` to point to to our official URL, `api.notification.canada.ca`.

DNS terraform file for alpha:

- https://github.com/cds-snc/dns/blob/0bd3672835e4cea3a5a5fbb79b91562275714652/terraform/notification.alpha.canada.ca.tf

DNS terraform file for prod:

- https://github.com/cds-snc/dns/blob/0bd3672835e4cea3a5a5fbb79b91562275714652/terraform/notification.canada.ca-zone.tf

## WHY are we building?

- To ensure all users hit the correct instance of our api, even if they use the old URL.
- We can deprecate the API in Kubernetes to only rely on the one in the Lambda space.

## WHAT are we building?

- Updating the DNS record.

## VALUE created by our solution

- Users won't have to change any configuration and will start hitting the correct instance of our API.

# Acceptance Criteria** (Definition of done) 

- [x] No more requests are recorded in the k8s cloudwatch logs 
- [x] No more requests are recorded on the alpha domain through the WAF logs
- [x] SSL certificate remain valid

# QA Steps

- [x] Open cloud watch, check k8s logs for requests after switch over (October 6 @ 12:06 EST)
- [x] Open athena, query WAF logs for host with 'alpha' in it after switch over (October 6 @ 12:06 EST)
- [x] Visit https://api.notification.alpha.canada.ca in chrome,
  - Click lock icon,
  - Click "connection is secure"
  - [x] ensure it says "certificate is valid"
     - click "certificate is valid"
     - [x] ensure common name in cert says `Common Name (CN)	notification.aplha.canada.ca`

# Additional Info

[From Pat in Slack](https://gcdigital.slack.com/archives/C0458SVD7BK/p1664808540763309):

> ok, digging into it, this is why it works with the LB - there’s an alt certificate that has *.notification.alpha.canada.ca set:
https://github.com/cds-snc/notification-terraform/blob/991ddc035de583da5eaa646416f89f0f77281a35/aws/eks/alb.tf#L44-L48
https://github.com/cds-snc/notification-terraform/blob/main/aws/dns/acm.tf#L20-L39
> in the case of this change, it looks like it failed because the API gateway’s execute URL and cert was returned by the weighted DNS record response and doesn’t have a reference to `*.notification.alpha.canada.ca .
> Thinking back on it, this is similar to the problem we had when we initially setup the weighted records and used CNAMEs instead of the alias we have now:
> https://github.com/cds-snc/dns/blob/0bd3672835e4cea3a5a5fbb79b91562275714652/terraform/notification.canada.ca-zone.tf#L34-L66
> my gut feeling on this is that we won’t be able to use a CNAME to the weighted record since we don’t have a way to modify the API gateway’s execution cert.  Easiest fix would be to replace this CNAME record with an alias , but then you do lose the ability to control it via a weighted value.
> Slightly more complicated fix would be to create another weighted record for the api.notification.alpha.canada.ca URL that uses the same pattern of two alias records (1 to LB, 1 to API gateway) and then hoist the weight value out into a variable that’s shared by all weighted records so you only have to update the weighting in one spot.

**Comment by jimleroyer** [comment]
PR https://github.com/cds-snc/dns/pull/276

**Comment by YedidaZalik** [comment]
In progress, Jimmy is working on it

**Comment by jimleroyer** [comment]
We [deployed production changes today](https://github.com/cds-snc/notification-terraform/pull/542) that included additional PRs:

* https://github.com/cds-snc/notification-terraform/pull/539/files
* https://github.com/cds-snc/dns/pull/281

The changes were applied and this time, it worked correctly. We tested if we still receive traffic through the load balancers redirecting to kubernetes with the keyword `alpha` and no result was returned after the deployment time.
