### ISSUE TITLE
Bug: Can still send if would go over sms message part limit

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#897]
## Describe the bug 

Can still send a big text even if it would make you go over the limit

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Low 

## To Reproduce (Staging)

1.  Lower your sms limit to 2
2. Choose a big sms template
3. Click "Send to yourself" 
4. See "You’re about to send 3 text message parts. This exceeds your daily limit." message
5. Click "Send one text message"
6. message sends

## Expected behavior

Can't send it.

## Impact

SMS limits not enforced

## Screenshots

![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/15ea7348-713b-4206-b7f8-a5b6bd63bfdb)

**Comment by sastels** [comment]
Will be handles in #892

**Comment by YedidaZalik** [comment]
@sastels noticed this 2 weeks ago, he will take a look at card to check if it's a duplicate

**Comment by YedidaZalik** [comment]
@sastels will close or promote this card today.

**Comment by sastels** [comment]
Duplicate of https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/910 which has been addressed.
