### ISSUE TITLE
Investigate: Fix Duplicate Issue for Notifications

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#899]
## Description

Seeing duplicate errors when we send notifications through the bulk saving function.

- Change error handling to send notifications to a dead letter queue?
-  We shouldnt have a loop that takes from expired and sends to inbox and back again
- Ticket https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/669 is related
- This ticket is more about investigating the root cause vs finding a solution
- Maybe the handler needs to be fixed as its not handling the duplicate properly

## Acceptance Criteria** (Definition of done) 

If the notification fails on save - we have a process for what happens to a duplicate failure on notification.

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Related to #79, which has been iceboxed because it was created before we did batch saving, so is not as current.

**Comment by jimleroyer** [comment]
@yaelberger-commits #79 would still be current, batch saving wouldn't fix it or change that behavior.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/899?planning-poker) with Zenhub @andrewleith @jzbahrai @smcmurtry @whabanks
