### ISSUE TITLE
Qualtrics survey integration for growth (in staging only)

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#900]
# Description

As a team member from the growth team,
I would like to run a survey with Notify users,
So that I can better address Notify needs in terms of growth.

As a team member of Notify,
I would like to know more about our users in a continuous
and open a communication channel with them,
So that I can set the direction of Notify toward our users' needs.

## WHY are we building?

Help out the growth team helping us.

## WHAT are we building?

Integration of Qualtrics survey into the admin component. We only need to show it in staging as a first iteration. We wouldn't enable in production and show to users yet. We want to offer the integration with the tool first so the growth team can configure it properly while having sandbox.

## VALUE created by our solution

Get to know our users.

# Acceptance Criteria** (Definition of done) 

- [x] Qualtrics survey is integrated in admin.
- [x] Qualtrics survey is only present in staging environment (via a feature flag maybe)
- [x] Qualtrics survey is available in the authenticated pages only, not in the public ones.
- [x] UAC: The growth confirms that they can see the survey button corresponding to their survey configuration.
- [x] Verify how bilingualism will work out; no need to fix but rather raise potential issues (as it's only in staging and first iteration).
- [ ] Policy team to check what data is collected in the cookie and how long retained.

# QA Steps

- [x] Test the survey integration in staging environment.
- [x] Make sure the survey integration is not present in production environment.

# Additional info

Regarding the implementation, that would be similar to integrate Google Analytics, we'd need to cover these steps:

* Add a javascript snippet into the global template for authenticated pages.
* Add an exception HTTP header for CSP policies that allows for qualtrics domain.
* Add feature flag to only enable the survey integration in the staging environment or detect the environment and add only if staging (whatever works and is easier).
 *Explore opt-out for future iterations.

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/900?planning-poker) with Zenhub @jzbahrai @sastels @smcmurtry @andrewleith

**Comment by jimleroyer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/900?planning-poker) with Zenhub @amazingphilippe

**Comment by adriannelee** [comment]
Reviewed and now needs QA. @jimleroyer will refine the QA steps. But need to wait for @jeanafrost to check configuration on Qualtrics
