### ISSUE TITLE
Extract SMS limit dev work for V2 release behind a new feature flag

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#901]
# Description

The goal of this task is to remove V2 work from behind the existing feature flag (`FF_SPIKE_SMS_DAILY_LIMIT`) so that we will be able to isolate the features we want as part of a our V1 SMS limit release.

We can create a new feature flag `FF_SMS_PARTS_UI`.

# To do

- [x] PR to add the new feature flag in notification-manifests similar to [#1248](https://github.com/cds-snc/notification-manifests/pull/1248)
- [x] put the new dashboard section behind this new feature flag
- [x] put the new UI on the "Review before sending" page behind the new flag
- [x] put the updates to the relevant queries in notification-api behind this new flag [PR #1599](https://github.com/cds-snc/notification-api/pull/1599)

# Acceptance criteria
- [x] V1 features visible when `FF_SPIKE_SMS_DAILY_LIMIT = True`, but not when `False`
- [x] V2 features just visible when `FF_SMS_PARTS_UI = True`

# QA by second set of eyes
- [x] V1 features visible when flag on, but not when off
- [x] V2 features just visible with new flag

# Additional Info

## V1 and V2 releases

[Google doc](https://docs.google.com/document/d/12uyYHv1Z3JY6D7jphCzmIeNA1n2cao04xEuIjr49xLw/edit#)

![Screen Shot 2022-10-04 at 4.15.01 PM.png](https://images.zenhubusercontent.com/63176b6f863fa9b22e9eee20/ef546018-97e9-4283-ae6e-2cae9f1b4c19)

**Comment by YedidaZalik** [comment]
PRs to implement this have been merged/released
Moving to done

**Comment by YedidaZalik** [comment]
QA by looking at staging
@sastels to do that
