### ISSUE TITLE
ADMIN caches `None` response from GC Articles under certain conditions

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#903]
# Describe the bug

When the GC Articles cache is due to be refreshed and GC Articles is down at the same time, Notify may cache a None response for the menus, leading to the site crashing on all GCArticles pages.

# [Bug Severity

SEV-2 Major

# To Reproduce

* Manually set the corresponding cache keys for GCArticles menu to `None`.
* Locally run GCNotify admin, rely on internal Redis and block requests to GCArticles upon refresh.

# Expected behavior

When the menus can't be found in the cache, a fresh copy should be picked up from GCA.  If there is a problem doing that, a copy should be taken from the fallback cache instead.

# Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:
- Severe - when this happens, all GCA pages will error out, making the site appear down.

Impact on Recipients:
- None

Impact on Notify team: 
- Increased support requests

# Screenshots

# Additional context

We need a test for this scenario and we need to shore up the menu logic to ensure `None` is never cached.  Additionally, we could instantiate `nav_items` to an empty (or fixed) list so that in the worst case scenario the page could still render.

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/903?planning-poker) with Zenhub @andrewleith @jzbahrai @sastels @smcmurtry

**Comment by yaelberger-commits** [comment]
Need to check if we did any PRs for this item

**Comment by yaelberger-commits** [comment]
Want to have a static page we can refer to if GC Articles doesn't return our page

**Comment by amazingphilippe** [comment]
@andrewleith looking at creating tests

**Comment by andrewleith** [comment]
- Jumana and I met regarding this yesterday; PR has been approved and will be merged shortly.
