### ISSUE TITLE
SMS V1 release - bug bash

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#905]
This card is to track the overall testing of the features that are part of the SMS Limits V1 release. 

- We are testing new restrictions on SMS sending.
- Services can now only send a limited number of SMS messages a day. After that they are blocked with an appropriate error message.
- If you run out of SMS messages, you should still be able to send emails.

- You will need:
    -  a Notify account on our staging service https://staging.notification.cdssandbox.xyz/
    - a service and templates for sending SMS messages
    - to have your SMS daily limit set to a low number
    - after you go over your limit, to test again you’ll need your limit raised
    - **Note:** if you would like to have any settings changed, need help creating services/templates or you want to be made admin yourself, ping @andrewleith for help

Special attention should be paid to find and test corner cases that we may not have covered yet.

## Things to test
- [ ] New trial service gets limit 50
- [ ] Going live bumps up to 1000
- [ ] UI change on settings page
- [ ] changing the sms daily limit triggers the correct email
- /sms:
  - [ ]  Cannot hop over the limit (with proper error message)
  - [ ]  Can go up to the limit and next send is blocked (with proper error message)
- /bulk:  
  - [ ] Cannot hop over the limit (with proper error message)
  - [ ] Can go up to the limit and next send is blocked (with proper error message)
- Admin send to yourself: 
  - [ ] Cannot hop over the limit (with proper error message)
  - [ ] Can go up to the limit and next send is blocked (with proper error message)
- Admin send to one recipient: 
  - [ ] Cannot hop over the limit (with proper error message)
  - [ ] Can go up to the limit and next send is blocked (with proper error message)
- Admin send to many: 
  - [ ] Cannot hop over the limit (with proper error message)
  - [ ] Can go up to the limit and next send is blocked (with proper error message)
- Existing email sending functionality is unchanged - can send emails when over sms limit
  - [ ] /email
  - [ ] /bulk
  - [ ] admin send to yourself
  - [ ] admin send to one recipient
  - [ ] admin send to many recipients
- [ ] Feature flags work as expected
- [ ] receive correct amount of emails based on limits and that the message content is correct (Should get only 1 close to limit and reached limit email but this resets when change limit)
- [ ] Designers to review EN and FN content for typos

## Acceptance critieria
- [x] find bugs and create the bug cards for tracking 
- [x] everyone finished testing and confident working as expected
- [x] invite other CDS teams and create slack channel for tracking and creating cards

## Scope
[Google doc](https://docs.google.com/document/d/12uyYHv1Z3JY6D7jphCzmIeNA1n2cao04xEuIjr49xLw/edit#)

## Results of Bug Bash

1. Content changes
 ![Screen Shot 2022-10-13 at 11.09.01 AM.png](https://images.zenhubusercontent.com/6149fdc10c14631b6b9c16dc/68ecf0f3-2307-47f6-9168-1b36ac8bb625)

2. API Bug: text that reaches the limit is stuck in "sending"
POSTing to /sms
Set limit to 10
Sent 4 2 part sms
Counter 8, Got 80% email
Send another 2 part sms
Counter to 10, sms marked “sending” in admin but not sent
- this will happen to /bulk as well

3.![Screen Shot 2022-10-13 at 11.19.23 AM.png](https://images.zenhubusercontent.com/6149fdc10c14631b6b9c16dc/3aacd158-3ade-45ec-9175-859adcede441)

4. Content change and rewording the content as well
 ![Screen Shot 2022-10-13 at 11.25.52 AM.png](https://images.zenhubusercontent.com/6149fdc10c14631b6b9c16dc/d75cab31-8f77-4ba8-a6eb-d43d1cddb988)

5. Fix the content in the email
![Screen Shot 2022-10-13 at 11.29.19 AM.png](https://images.zenhubusercontent.com/6149fdc10c14631b6b9c16dc/6949f0cb-50c9-414a-8525-0ae98bf91e5c)

**Comment by YedidaZalik** [comment]
Participants
- do they need Notify access
- do they need Admin access
Need instructions we can copy and. paste into channel
Need person to be below msg daily limit - requires admin access

@andrewleith volunteers to be admin
Instructions to be done offline - @sastels to coordinate

**Comment by sastels** [comment]
cards created for bugs

**Comment by yaelberger-commits** [comment]
Is this task completed?
