### ISSUE TITLE
Notify our users about Daily limit V2, Release 2

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#906]
# Description

As a user of Notify,
I would like to know what latest changes around daily limits entail,
So that I can understand better how it applies to me
And reduce potential confusion around these changes.

As a team member of Notify,
I want to share our recent changes around daily limits,
So that I can help users better understand how the new limits will apply
And have a first communication of these changes that includes technical explanations to see how users react to these.

# Acceptance Criteria** (Definition of done) 

- [x] Communication of changes are written.
- [x] Communication of changes are translated.
- [x] Support team is warned of upcoming communication when sent.
- [ ] ~~Communication is sent to all users of active live services via GCNotify.~~
- [x] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

## Related Research Airtable records
- [Finding 378](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/recQd6Io3KWeCnqwX?blocks=hide)

## QA Steps
- [x] Communication is reviewed by developers.
- [x] Communication is reviewed by content.
- [x] Communication is reviewed by support.

## GC Articles Publish checklist
- [x]  Supporting feature is released and unflagged
- [x]  Create or update slug
- [x]  Page content and slug is translated
- [x]  Document links to and from the page
- [x]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [x]  If new page, add WAF rule
- [x]  Create new page or update existing page content
- [x]  Create or update translation to the page
- [x]  Link translations by choosing an assigned translation
- [x]  If new page, save as draft
- [x]  Post page in Slack for last minute reviews
- [x]  On staging: Clear the cache through GC Notify's admin panel
- [x]  On staging: Check links, images and language toggle
- [x]  Give a heads up to the app-team channel once ready to publish
- [x]  On staging and production: Clear the cache through GC Notify's admin panel
- [x]  Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/906?planning-poker) with Zenhub @adriannelee @amazingphilippe @YedidaZalik

**Comment by yaelberger-commits** [comment]
@YedidaZalik I'm curious if we might be able to use an MVP product updates page to notify users about these changes. What do you think?

**Comment by YedidaZalik** [comment]
@yaelberger-commits  I agree we could do an MVP. If we do that, it would be help to first do user story mapping for that feature.

**Comment by adriannelee** [comment]
@YedidaZalik I created a new card to capture the MVP product updates page https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1279 And worked on the story map for that. 

We could choose to complete this card using the MVP product updates page.

**Comment by adriannelee** [comment]
Yedida worked on the content - content is not yet being reviewed but will be closer to release

**Comment by YedidaZalik** [comment]
Worked on content yesterday and Adrianne and Yael left some comments.

**Comment by YedidaZalik** [comment]
No further comments from team. Prepped translation screen. Phil and I will meet Monday morning to make sure I've done it properly and then I'll send to translation.
https://www.figma.com/file/vA5P3VrBsiPCZEvVtCoXbc/New-features-%7C-Nouvelles-fonctionnalit%C3%A9s?type=design&node-id=477-1767&mode=design&t=SAtdpmfFOpRdhQF0-0

**Comment by amazingphilippe** [comment]
Translation for the first update in GCA is translated. Waiting some resolution on #1279.

**Comment by amazingphilippe** [comment]
New features page is created in GCA in both languages and will be linked from the footer.

**Comment by amazingphilippe** [comment]
Assigning @adriannelee to update any research records associated with this story!

**Comment by adriannelee** [comment]
Done!
