### ISSUE TITLE
SMS V1 remaining issues

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#911]
This card is to track remaining issues we find in the SMS Limits V1 release. Also a place you can check if your bug has already been found!

If you find a bug
- add a bug card for it giving details of how to reproduce
- add a checklist item below linking to it

We can check off the bugs as we fix them

## Issues
- [x] Dev: [admin one off sms sending over limits](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/910)
- [x] Dev: [/bulk and /sms endpoints don't always send sms](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/912)
- [x] Dev: [SMS daily limit emails can't be modified
](https://github.com/cds-snc/notification-planning/issues/924)
- [x] Dev: [Extra ")" in sms limit email](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/930)
- [x] Dev: [API users can hop over SMS daily limit](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/931)
- [x] Dev: [Set SMS daily limit appropriately for Trial and Live services](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/945)
- [x] Dev: [Scheduled sends can exceed daily SMS limit.](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/948)
- [x] Dev: [tweak api sms error message](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/920)
- [x] Design / Dev?: [Error message styling bug](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/928)
- [x] Content: [SMS error message confusing if you have small messages](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/927)
- [x] Content: [Inconsistant SMS language in settings](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/929)
- [x] Content: [Create new email templates for daily SMS limit warnings/stoppages](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/868)

Removed from V1:

- Dev: [Daily limit warning emails are sent a bit later than they should be](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/919) Outside scope of V1 - moved to "New Issues"
- Dev: [Automate notifying us if a service goes over their daily SMS limit](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/366) - moved to product backlog for V2

**Comment by YedidaZalik** [comment]
Collector card of bugs, slowly working through.
@sastels will start a thread for styling and content.

**Comment by YedidaZalik** [comment]
@YedidaZalik to add tags

**Comment by YedidaZalik** [comment]
The content is in corresponding sub-cards for:
- Content: SMS error message confusing if you have small messages
- Content: Inconsistant SMS language in settings

For  Content: Create new email templates for daily SMS limit warnings/stoppages, the templates are done and Jumana is going to QA

**Comment by adriannelee** [comment]
Content is done for error messages, but it needs dev implementation. @amazingphilippe will do it.

**Comment by sastels** [comment]
Moving to done, since all issues have been fixed and QA'd. Anything new / remaining can be a new card.
