### ISSUE TITLE
/bulk and /sms endpoints don't always send sms

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#912]
## Describe the bug 

The `/bulk` and `/sms` endpoints create the notification(s) that will bring you to the sms daily limit, but don't actually send them.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2

## To Reproduce

1. Set your limit to 6
2. Send 4 fragments. Can verify that your key in redis is 4.
3. Try to send 2 small sms via `/bulk`. Messages appear in dashboard as "sending" but are not sent (redis key is updated to 6)

Can do a similar process with `/sms`

## Expected behavior

Messages sent

## Impact

messages not sent

**Comment by YedidaZalik** [comment]
PR was reviewed and approved and might fix this also
@sastels will merge into staging and check if fixed

**Comment by sastels** [comment]
There's still a bug here, but it's slightly different... tweaked card description accordingly

**Comment by sastels** [comment]
Ok! it looks like we increment the counter when we create the notification, which is not a bad idea!
https://github.com/cds-snc/notification-api/blob/main/app/notifications/process_notifications.py#L213

But then we check if we're at the limit right again before we send
https://github.com/cds-snc/notification-api/blob/main/app/celery/tasks.py#L292
We should probably not check again. Basically, if we allow the notification to be created, we shouldn't not send it (and note that it will later be found by a task looking for "created" notifications, and sent then anyway)

**Comment by sastels** [comment]
Also, we're doing these checks
https://github.com/cds-snc/notification-api/blob/main/app/celery/tasks.py#L291-L292
using the service of one of the notifications in the batch to decide whether to not send the whole batch.

I'm going to see if we can just delete all these "just before sending" checks and just check when the work comes into api.

**Comment by YedidaZalik** [comment]
Merged on Friday, someone else should QA 
@andrewleith to review
