### ISSUE TITLE
Daily limit warning emails are sent a bit later than they should be

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#919]
## Describe the bug 

It appeared that the sms 80% and at the limit emails were sent not when reaching the threshold, but when trying to go over. This could have just been bad timing but we have to make sure.
 
## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation
SEV-4 Low

## To Reproduce

1. Set your sms limit to 1
2. send a single text ("Send to yourself")
3. Wait 5 minutes and see if you get the emails? Should get both, you went from 0% to 100%
4. If you didn't get them, try to send another sms and see if you get the emails then

## Expected behavior

Get the emails on time

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

Users get to the limits without getting the warning emails.

**Comment by yaelberger-commits** [comment]
@sastels is fixing this a requirement for V1? Seems like it should be? If so I will move it into the backlog

**Comment by sastels** [comment]
This may be fixed now (by some of the sms refactoring we did):
* set limit to 2 fragments
* sent one small text (admin send to yourself)
* sent a second small text (admin send to yourself)
* got 2 emails

Should test csv / api single / api bulk to check those routes. Note that email sends probably still have the bug.

**Comment by smcmurtry** [comment]
I made a test with the CSV send and it worked as expected:
1. Test send of 9 SMS fragments, daily limit of 10. I received the 80% warning email 
2. Test send of 4 SMS fragments, daily limit of 5. I received the 80% warning email

So this is working as expected for CSV sends.
