### ISSUE TITLE
tweak api sms error message

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#920]
## Description

As a Notify API user, I need to be able to understand the api error messages.

Right now if you go over (using the api) you get back an error message of the form "Exceeded sms send limits (6) for today". The "(6)" is confusing, we should get rid of it (for sms and general daily limit errors)

## Acceptance Criteria** (Definition of done) 

- [ ] Error message doesn't have the number in it

## QA Steps

- [ ] Error message doesn't have the number in it

**Comment by yaelberger-commits** [comment]
Take the number in the brackets out for v1

**Comment by adriannelee** [comment]
@sastels will review

**Comment by sastels** [comment]
looks good in staging
