### ISSUE TITLE
Add numbered list documentation to formatting guide

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#921]
## Description

Our markdown engine supports ordered lists, but they aren't explained in our formatting guide.

WHY are we building?
- To help our users understand the supported features of our email templates.

WHAT are we building?
- Adding information to our documentation

VALUE created by our solution
- Allows our users to know about more ways to format their content

## Acceptance Criteria** (Definition of done) 

- [x] Documentation contains examples on how to create numbered lists
- [x] Documentation is produced in French and English

## QA Steps

- Go to [the formatting guide](https://notification.canada.ca/formatting-guide)
   - [ ] Ensure there is a section on numbered lists
-  Switch to french
   - [ ] Ensure there is a section on numbered lists

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/921?planning-poker) with Zenhub @YedidaZalik @amazingphilippe

**Comment by YedidaZalik** [comment]
Started on this last week entering content with the suggest function [here](https://docs.google.com/document/d/1bURk3s8xqBk17flSwp0HwArCzlW-YO6w3SvDjaSlayo/edit#heading=h.r2jhrj4t6qvn)
Could consider reorganizing this guide to make it easier for users to find information within the document

**Comment by YedidaZalik** [comment]
Reviewed and made some changes to last week's content this morning.

**Comment by smcmurtry** [comment]
Yedida and Phil worked on this last week, have some draft content, will review in dev/design review this week. Not yet translated.

**Comment by smcmurtry** [comment]
Yedida's update - writing content / adding an illustration re: numbered lists, some complexity around sub lists that we may leave out.
We have some problems to fix with hyperlinks.

**Comment by smcmurtry** [comment]
Yedida's update - writing content / adding an illustration re: numbered lists, some complexity around sub lists that we may leave out.
We have some problems to fix with hyperlinks.

**Comment by yaelberger-commits** [comment]
Yael reviewed

**Comment by yaelberger-commits** [comment]
Yedida will ask for an update from Marie Sophie today

**Comment by YedidaZalik** [comment]
Translation is back https://docs.google.com/document/d/1HMXj1Rgye-1gvJ64jeDE_uuVECt3YE1AHw34zmQlF3o/edit

**Comment by whabanks** [comment]
Reviewed, just adding finishing touches. Will deploy with today's release.

**Comment by amazingphilippe** [comment]
https://github.com/cds-snc/notification-admin/pull/1648 Merged

**Comment by yaelberger-commits** [comment]
Looks good in both EN and FR! Moving to done

**Comment by yaelberger-commits** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXdVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--22747003ed9a77d11edba3885a2f70838649f307/Screenshot%202023-08-17%20at%202.04.54%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTRVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ff0bca1d540468ba775227bb6e8715c969acedba/Screenshot%202023-08-17%20at%202.05.18%20PM.png)
