### ISSUE TITLE
SMS daily limit email templates cannot be modified

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#924]
## Describe the bug 

As a result of missing data in the `template_redacted ` table, the SMS daily limit templates cannot be edited.

Affected templates:
- `NEAR_DAILY_SMS_LIMIT_TEMPLATE_ID = "a796568f-a89b-468e-b635-8105554301b9"`
- `REACHED_DAILY_SMS_LIMIT_TEMPLATE_ID = "a646e614-c527-4f94-a955-ed7185d577f4"`
- `DAILY_SMS_LIMIT_UPDATED_TEMPLATE_ID = "6ec12dd0-680a-4073-8d58-91d17cc8442f"`

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

1. View one of the affected templates, i.e. https://notification.canada.ca/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/templates/a796568f-a89b-468e-b635-8105554301b9
2. Click on **Edit**
3. Click on **Save**

## Expected behavior

- Template is saved and updated.

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

### Impact on Notify users:
- None yet
### Impact on Recipients:
- None yet
### Impact on Notify team: 
- Unable to continue content updates for this feature

## Fix
To fix this, we need a new migration that adds corresponding rows to the `template_redacted` table.  See [this PR](https://github.com/cds-snc/notification-api/pull/1332) as an example.

**Comment by YedidaZalik** [comment]
2 PRs in - Steve M reviewed. 
To merge once updated to main branch.
