### ISSUE TITLE
Language tags produce HTML with incorrect font in certain cases

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#925]
## Describe the bug 

When using the language tags, text with an incorrect font is produced in the email, but not the preview screen.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-2
Could impact recipient trust and make an email look like spam 

## To Reproduce

1. Create an email template with the following content:
```
[[fr]]
This line will be in the wrong font

This line is in the right font
[[/fr]]

[[en]]
This line will be in the wrong font

This line is in the right font
[[/en]]

[[fr]]
This line will be in the wrong font

This line is in the right font
[[/fr]]
```
2. Send it to yourself

## Expected behavior

All text in the email is in the same font.

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

### Impact on Notify users:
- Could lead to confidence issues in our system if templates don't appear in a professional manner.

### Impact on Recipients:
- Could lead to confidence issues in our system if templates don't appear in a professional manner.

### Impact on Notify team: 
- Potential increase support requests

## Screenshots

![image](https://user-images.githubusercontent.com/823749/195594323-031caf61-7d97-4e99-a1aa-82ae7ba5ae6e.png)

## Work around
A workaround to this issue is to type extra line returns. A user told us they did that to avoid the issue.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/925?planning-poker) with Zenhub @andrewleith @jimleroyer @jzbahrai @sastels @smcmurtry

**Comment by YedidaZalik** [comment]
@andrewleith working on this and will sync with Steve M about bugs

**Comment by adriannelee** [comment]
More bugs than we thought. Esp with headings.

Some more work to be done today.

**Comment by adriannelee** [comment]
Andrew finished working on it. Waiting to be released and to do one last QA

**Comment by yaelberger-commits** [comment]
Now works in both staging and prod
Screenshot from Prod template
font isn't wonky anymore when language tags used

![Screen Shot 2022-10-27 at 11.05.07 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/e35faa08-5538-4b24-abcf-709fdb0e6e58)
