### ISSUE TITLE
SMS error message confusing if you have small messages

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#927]
## Describe the bug 

the error message about your messages being too big is confusing if they're all small. Should have some content around too many messages also getting you over the limit.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-4 Low

## To Reproduce

- send small sms until you're over your sms daily limit

## Expected behavior

Users not confused

## Impact

users confused

## Screenshots

![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/d3c7beeb-2ff3-444b-9515-00b78fb70c04)

**Comment by YedidaZalik** [comment]
@amazingphilippe and  I made this Figma content: https://www.figma.com/file/VRqRRfX7Ko5ssg2VryVVET/Dashboard-%7C-Tableau-de-bord?node-id=1225%3A6102
Does it work to address this?

**Comment by andrewleith** [comment]
@YedidaZalik I find the fragment sentence difficult and in particular the word travel feels out of place.  What if we make the main message a little more concise and prefix the harder to understand part with something like "please note/be advised, etc"?

> ### You've sent too many text messages
>
> Please note that long text messages can count as more than one against your daily limit.
>
> You can send more text messages tomorrow.  To raise  your limit for future sends, contact us.

**Comment by YedidaZalik** [comment]
@andrewleith let's consider that for V2 but leave it as is for now, because this would not be a small change. It would impact all the content we created for v1  (emails and error messages) as well as translation. Plus we're going to test this so then we'll be able to revise based on what we learn.

**Comment by andrewleith** [comment]
👍 no problem, sorry may have been a little late to the party!

**Comment by YedidaZalik** [comment]
We missed you at the last party and will be glad to have you at the next one!

**Comment by yaelberger-commits** [comment]
Merged to Staging
