### ISSUE TITLE
Error message styling bug

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#928]
## Describe the bug 

strange spacing in error message

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-4 Low

## To Reproduce

1. In admin, send more sms than your daily limit
2. See the error message.

## Expected behavior

better spacing

## Impact

looks funny

## Screenshots

![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/8492e288-58f2-4dc1-bb4b-f8afc04f5ca7)

**Comment by YedidaZalik** [comment]
@sastels will QA

**Comment by sastels** [comment]
Other error messages look better now too!
prod:
![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/8f61c781-5fc8-483f-b57c-1826e329e0e2)

staging:
![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/20971f62-f905-4af2-aa02-47b31983235f)
