### ISSUE TITLE
Inconsistant SMS language in settings

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#929]
## Describe the bug 

language inconsistant around SMS / fragments in settings

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-4 Low

## To Reproduce

1. Go to settings, look at the sms settings

## Expected behavior

consistant language

## Impact

confused users

## Screenshots

![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/485c3d44-f4f3-44fb-858a-0ddb56079a90)

**Comment by amazingphilippe** [comment]
- [x] QAd.Content appears as designed in both languages
