### ISSUE TITLE
API users can hop over SMS daily limit

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#931]
## Describe the bug 

Can go over the limit with `/sms` or `/bulk`

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor

## To Reproduce

1. Set your limit to 1
2. Send a 2 part `/sms` or at least 2 fragments worth of sms to `/bulk`
3. POST is accepted with a 201 code

## Expected behavior

Get an error back

## Impact

Users could send too many messages

## Notes

This could be related to https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/897

**Comment by YedidaZalik** [comment]
Merged in staging
@andrewleith to QA
