### ISSUE TITLE
[Onboarding] Welcome Jimmy Prince!!!

### ISSUE THREAD

**Issue by ramya-cds** [cds-snc/notification-planning#932]
# Description 

Here are some tasks to go through that should help you get to know the team and product better to be able collaborate with the team.

Present checklist is here to help us track progress and completion of this.

**Done when** :  New team member says so ! Should have had the time to digest info, connect with team and the access needed are granted 

#  Read and discover **(the following are suggested in order of priority. Reading all of it is not mandatory)**

- [x] [Overview of Notify product](https://docs.google.com/document/d/1naerXecHaMR6-udeYiny5a_84CvIKwITAlwR8ZwsIZY/edit#) 
- [x] [Notify Scavenger Hunt](https://docs.google.com/document/d/1MmKBZqMNpsLU0TlURGCyOlByZHGfZccteuYdGZ9amwM/edit#heading=h.sxqbcn4k0lmo)🕵️‍♀️
- [ ] [Directory of links](https://docs.google.com/document/d/15dk3fz6BwX0_ZwHyCXMDYIWCszXSoFarqydKQNeeyx0/edit)
- [ ] [Design onboarding cheatsheet](https://docs.google.com/document/d/1hWjtCQp1N6_EADquwbBAuJ37ZNdxHvfxMCEDtO1M--g/edit#heading=h.g3c6sgz3eiwh)
- [ ] [Design documentation](https://docs.google.com/presentation/d/1gwK4b-R3izYsAh12MVWkFknWDR7URkxTPp1jHU9gULc/edit)
- [ ] [Dev resources](https://docs.google.com/document/d/1Nd3tqUO48oQvc0Vkn6iaCv01w1AkjyWbfOG2ZrKwAtI/edit#heading=h.gsberul37syg)
- [ ] [Notify com 101](https://docs.google.com/document/d/19cdOXloQ0bTZuJUidCuMqvOPD18djA_3CnVJdsecaXE/edit)
- [ ] [30-something things to know about Notify](https://docs.google.com/document/d/1pNDfw--2kBPBOEx_9EVKCiLD0wTaC0rjticZv1sVtb8)
- [ ] [Story point estimation](https://drive.google.com/file/d/1d2offGEmop4dMZFrCQGPKPqMNoK7n9NW/view)
- [ ] [Notify policy 101](https://docs.google.com/presentation/d/1A_0CAcORZI0vB_if3L53IzEJwr8cr0N8aJ5UmtWXwHc/edit#slide=id.p)

# Meet and greet ☕️

- [x] Demo of the product with @yaelberger-commits the product manager
- [x] Chat about general team dynamic and organisation with our team leader @josh-cds
- [ ] Chat with Lead Design @amazingphilippe 
- [ ] Chat with Lead Researcher @adriannelee 
- [ ] Chat with Notify Dev Lead @jimleroyer 

# Get the access 👀

- [x] Get Slack channel access [DM or PM]
- [x] Get Trello access [DM or PM]
- [x] Get Google Drive access [DM or PM]
- [x] Get Figma access [Designer @amazingphilippe ]
- [x] Get platform admin access [Dev lead contact: @jimleroyer ]
- [x] GitHub Access [Contact: Slack #sre-and-tech-ops]. Request to be added to your GitHub teams as well.

# Access for Dev  ⌨️

- [x] LastPass and shared Notify folders inside of it (Staging and prod credentials, environment variables for running the repo locally) [**Contact**: @jimleroyer ]
- [x] Snyk (Dependency management) [ Contact SRE team on Slack #sre-and-tech-ops channel ]
- [x] Sentry (Error logging / debugging for staging) [ Slack msg @jimleroyer ]
- [x] AWS (staging and production accounts) Error log monitoring ; S3 buckets for asset management [ Contact SRE team on Slack #sre-and-tech-ops channel ]
- [x] [AWS CLI setup](https://docs.google.com/document/d/18w44esbq00JClsvHvlcrSiEnolCIlV5n-YKdVsq6bJk/edit)
- [x] New Relic (Error logging / debugging for production) [ Slack msg @jimleroyer ]
- [x] Freshdesk Customer ticket support portal [ Slack msg Wissam M. or Ramya S. ]
- [x] Add to Notification Google group [ #zendesk-it-support or /zendesk Slack command ]
- [x] Get platform admin access [Dev lead contact: @jimleroyer ]
- [x] Easy Retro **[Contact: Mario]**

**Comment by YedidaZalik** [comment]
It's going well
