### ISSUE TITLE
'Tomorrow' reference in daily limit emails is ambiguous (both email and SMS limit)

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#935]
## Describe the bug 

The word tomorrow is ambiguous in the daily limit emails.  Given that the system uses UTC and the end-users timezone is not known, the user will not know when their limits reset.

As a user, I need to be able to understand when my daily limits reset so that I can stay within those limits or request an increase if necessary

WHY are we building?
Daily limits impact Notify users but the timeframe for the limit may depend on the users time zone.

WHAT are we building?
Clarity around when the timeframe for a day starts to run and when it stops.

VALUE created by our solution
Users will easily understand how these time frames and limits apply to them.

Review work on COVID Alert QR timeframes and possibly consult Ioana to check how we solved for this.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-4 Low

## Acceptance Criteria
- [x] Email content is updated to remove reference to midnight and insert reference to 7pm EST (or 8pm EST depending on daylight savings time) for the following:
   - [x] SMS
      - [x] Near limit email
      - [x] Limit reached email  
   - [x] Email
      - [x] Near limit email
      - [x] Limit reached email

**Comment by yaelberger-commits** [comment]
Limit resets at midnight UTC daily

**Comment by adriannelee** [comment]
@yaelberger-commits we can archive this one?

**Comment by adriannelee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/935?planning-poker) with Zenhub @YedidaZalik @amazingphilippe

**Comment by amazingphilippe** [comment]
Some additional context from Notify 101

When we show time and dates to users, what is the timezone? Is it the server’s timezone, or the client’s time zone, or both?
Set to UTC. Daily limits reset at UTC midnight, so 7am in eastern standard time for example. 
“Tomorrow” story card
UTC in the database, and converted to local time with javascript. 
Follow-up: On screen, we do see local time, converted from UTC. 
For the email, we are using ambiguous words like tomorrow. 
Can’t convert to local time in emails, could do UTC, could do EST for everyone, or use content.

**Comment by YedidaZalik** [comment]
Working in this document to replace "tomorrow" reference and to change combined limit to email limit:
https://docs.google.com/document/d/1wvBXsb7G8LsoBWqHRICYoFdpHS3z9_lwpE4oAnr92e0/edit

**Comment by YedidaZalik** [comment]
Content from document included in figma file

**Comment by adriannelee** [comment]
Will review during dev-design review

**Comment by YedidaZalik** [comment]
Marie-Sophie hoping Simon can review the translation today.

**Comment by smcmurtry** [comment]
Marie-Sophie flagged an issue, Yedida to meet w/ Yael today.

**Comment by yaelberger-commits** [comment]
Back from Anik's review

**Comment by andrewleith** [comment]
https://github.com/cds-snc/notification-api/issues/1957 Takes care of the SMS portion of this card, I've checked off those AC.

**Comment by smcmurtry** [comment]
Here's a PR to address the email portion: https://github.com/cds-snc/notification-api/pull/1959
