### ISSUE TITLE
SMS size limit is not enforced consistently 

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#936]
## Describe the bug 

2 issues relating to this:
1. The validation to check the size of an sms message before send does not take into account the service name which is injected into every message
2. Bulk sends don't do any such check at all

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-4 Low

## To Reproduce

3. Click on '....'
4. Scroll down to '....'
5. See error

## Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team: 

## Additional context
- https://gcdigital.slack.com/archives/C04618WUMU3/p1665605124238919 

## Test scenarios
1. Sending an sms longer than 612 characters through the API should be blocked
2. Sending an sms longer than 612 characters through Admin should be blocked
3. Sending one or more sms longer than 612 characters in a bulk send through API should be blocked
4. Sending one or more sms longer than 612 characters in a CSV send through ADMIN should be blocked

**Comment by andrewleith** [comment]
This is a pre-existing bug about the size of an individual message (outside of any daily limits) and not really related to that work.

**Comment by andrewleith** [comment]
When we validate the message size, we don't take into account the service name which is automatically prepending to the message.  Because of this, we allow sending messages that are larger than 612.

**Comment by andrewleith** [comment]
PR for part 1: cds-snc/notification-api#1724

**Comment by andrewleith** [comment]
Unable to complete the work for test scenario 4 - I'll carve that off into a separate card.

**Comment by andrewleith** [comment]
PR for part 2: https://github.com/cds-snc/notification-api/pull/1725

**Comment by yaelberger-commits** [comment]
Scheduled to be part of today's release

**Comment by yaelberger-commits** [comment]
@sastels to QA once merged

**Comment by sastels** [comment]
QA'd on prod.
