### ISSUE TITLE
Set SMS daily limit appropriately for Trial and Live services

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#945]
## Describe the bug 

New trial services get an sms daily limit of 1000, despite having a general limit of 50 notifications

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor - very confusing for users

## To Reproduce

1. Create a trial service
2. Go to settings and see your limits

## Expected behavior

- set it to 50 for trial services (done in admin)
- set it to 1000 when switched to live (done in api)
- clean this up in api: https://github.com/cds-snc/notification-api/blob/main/app/service/rest.py#L241-L243

## Impact

Confused users

**Comment by YedidaZalik** [comment]
Merged in staging 
@yaelberger-commits will QA

**Comment by yaelberger-commits** [comment]
I will create a trial service, check for daily SMS limit, then request to go live and see bump to 1,000 in staging

**Comment by yaelberger-commits** [comment]
![Screen Shot 2022-10-19 at 9.20.02 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/fcbd5944-adad-4b8d-a33f-e68f06abb65b)

**Comment by yaelberger-commits** [comment]
![Screen Shot 2022-10-19 at 9.23.51 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/3c8b0a4c-b330-4af0-89c8-a6e018af4079)

**Comment by yaelberger-commits** [comment]
![Screen Shot 2022-10-19 at 9.28.54 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/1b4586ce-9458-401c-a590-abc4e70a23c6)
