### ISSUE TITLE
Scheduled sends can exceed daily SMS limit.

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-planning#948]
## Describe the bug 

Scheduled sends can allow a service to exceed their daily SMS limit. 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-4 Low - this doesn't affect anyone yet since the feature is not yet released.

## To Reproduce

Here is what I did:
1. sent 4 sms fragments
2. set my service’s daily sms limit to 8 fragments
3. scheduled a send for half an hour later, sending 4 sms fragments total
4. scheduled 2 more of the same send for the same time

At this point I have sent 4 sms fragments, and have scheduled sends that add up to 12 fragements, and my limit is 8.

What happened? All the scheduled sends went through and I have now managed to send 2x my allowed limit  

## Expected behavior

Sends should be prevented so that the service can not exceed their SMS limit.

## Impact

None until V1 release occurs.

**Comment by YedidaZalik** [comment]
Bug found yesterday and @smcmurtry will work on today

**Comment by adriannelee** [comment]
Steve A reviewed on Friday. Ready for another review

**Comment by sastels** [comment]
Tested on staging, behaviour now the same as for general daily limit.
