### ISSUE TITLE
Extra email when prod users go live

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#949]
## Describe the bug 

Prod users are getting an extra "Daily sending limit updated" email when their service goes line, caused by their sms fragments going to 1000 behind the scenes.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor - confusing new users - then get an email saying they can send 10000 and one saying they can send 1000

## To Reproduce

1. On prod create a service and make it live
2. check your email

**Comment by yaelberger-commits** [comment]
Is one email for overall daily notifications and the other for SMS specifically?

**Comment by adriannelee** [comment]
Steve A fixed on Thurs. 

@yaelberger-commits It is but we haven't fixed up the label for email limits

Have we made content for the email update to Senders? We don't have yet. Steve A will sync with Yedida on the content. 

For QA - @smcmurtry

**Comment by sastels** [comment]
I was incorrect - the email update that is sent on go live informing of the increase in fragment limit is the same email we send when the limits are changed, so we already have the content.

**Comment by smcmurtry** [comment]
I made a service Live on prod and I only received 1 email regarding the daily limit, as expected. Looks good!
