### ISSUE TITLE
Update SLA and ToU to align with SMS v2 language and designs

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-planning#958]

**Comment by YedidaZalik** [comment]
Latest version of SLA uses SMS v1 language ("fragments").  
This language may change significantly once we complete designs for SMS v2.  
To allow for understanding and reduce users' cognitive load, we'll need to revise the sections of the SLA that discuss SMS to align with the v2 language and designs.

**Comment by jzbahrai** [comment]
To be refined when we start doing SMS V2.

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/958?planning-poker) with Zenhub @YedidaZalik @sharlychan-cds

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/958?planning-poker) with Zenhub @mtoutloff @amazingphilippe

**Comment by YedidaZalik** [comment]
Reviewed SLA and TOU: neither refers to fragments anymore.
