### ISSUE TITLE
Notify Security Headers

### ISSUE THREAD

**Issue by mohamed-cds** [cds-snc/notification-planning#96]
notification.canada.ca is missing two key security headers

Referrer-Policy and Strict-Transport-Security, although no links are opening into new tab/windows so Referrer-Policy is less of an issue (though some standardization for projects moving forward will catch this and take the mental load off of devs needing to be sure to include it. If one doesn't already exist!).

Of note Content-Security-Policy also triggers a warning from securityheaders.com. Might be worth looking ahead to see if a fix can be found.

There are also some headers in the browser pipeline worth looking into in order to be prepared for upcoming releases? (Expect-CT, Cross-Origin-Embedder-Policy, Cross-origin-Opener-Policy, Cross-Origin-Resource-Policy).

Attempts to standardize security headers at the API Gateway has failed since proxy integrations cannot have their responses modified. Security headers will have to be set at the application level.

### Next steps

- Implement the ability to send custom http headers in all responses (middleware)
  - [Example python implementation](https://github.com/cds-snc/scan-websites/blob/main/api/api_gateway/middleware/security_headers.py)
- Send HSTS header in all responses (Strict-Transport-Security)
  - Introduce in stages to test impact: [deployment recommendations](https://hstspreload.org/#deployment-recommendations)
- Send referrer policy header in all responses (Referrer-Policy)
  - Recommendation: Referrer-Policy: strict-origin-when-cross-origin
    - Will not allow any information to be sent when a scheme downgrade happens (the user is navigating from HTTPS to HTTP).

## QA

- [x] Are the headers present when I go on Notify?

**Comment by yaelberger-commits** [comment]
We only support HTTPS, so sync with @mohamed-cds on this one

**Comment by mohamed-cds** [comment]
@jimleroyer, @yaelberger-commits both of these recommendations help secure notify against attacks not directly related to the code base. More details below.

[HSTS prevents](https://blog.qualys.com/vulnerabilities-threat-research/2016/03/28/the-importance-of-a-proper-http-strict-transport-security-implementation-on-your-web-server) certain attacks that trick browsers/connections into initiating a http session so that a man-in-the-middle (MITM) can be used against users.

[Referrer policy](https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns) helps maintain privacy and security when links are clicked on Notify that are destined to an outside domain that potentially doesn't enforce HTTPS connections.

**Comment by jimleroyer** [comment]
Just spoke to @mohamed-cds , this attack would still apply to Notify even though Notify only supports HTTPS. Basically, the risk is more on the client side where its connections would get downgraded to HTTP and the attacker would MITM and bridge the secure HTTPS connection back to Notify. So that issue should still be tackled.

**Comment by andrewleith** [comment]
Hey @mohamed-cds let me know if you have some time to sync up on this tomorrow.

**Comment by yaelberger-commits** [comment]
Ikenna will sync with Mo on this. Looking at existing headers and keeping track of how they are already being tested, not just security headers, other kinds of headers too, so taking a holistic approach. Should be done today
