### ISSUE TITLE
Bug: Francais/English toggle of API documentation brings you to start/homepage of FR/EN API documentation

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#961]
## Francais/English toggle of API documentation brings you to start/homepage of FR/EN API documentation

The Francais/English toggle at the top of any page/section of the API documentation doesn't bring you to that section of the documentation in the other language, but brings you to the start/homepage of the API documentation. 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

SEV-3 Minor 

## To Reproduce

1. Go to '[https://documentation.notification.canada.ca/en/](https://documentation.notification.canada.ca/en/)' or go to fr page
2. Click on any section in english or french
3. Find the "Français" or "English" toggle at the top right and click it
4. See that you end up at the start of the documentation in the other language instead of the section you were on

Start in EN API documentation
![Screen Shot 2022-10-28 at 10.29.47 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/062f941d-17a7-4050-9dd0-cd83fb0dfd1a)

Go to any section
![Screen Shot 2022-10-28 at 10.30.12 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/f14de944-e2ab-4944-bf33-88065d283e6f)

Find FR toggle
![Screen Shot 2022-10-28 at 10.30.41 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/ac7676e9-901b-4441-b785-9f7cb7300704)

Takes you to start of EN documentation
![Screen Shot 2022-10-28 at 10.31.10 AM.png](https://images.zenhubusercontent.com/618bd78afce6ad0aa17d429c/196e43d6-e7ef-4513-b301-97ee00638e98)

## Expected behavior

FR/EN toggle should take you to the same section you were on, but in the other langauge

## Impact

Not great for bilingualism and navigation 

If applicable

Impact on Notify users: Small impact on people who want to switch language while reading the API documentation 

Impact on Recipients: None

Impact on Notify team: Small impact on people who want to switch language while reading the API documentation

**Comment by adriannelee** [comment]
Will worked on this yesterday with Steve. PR is up but CI is failing so working on that this morning and then ready for review.

**Comment by whabanks** [comment]
CI is fixed - PR is ready for review!

**Comment by adriannelee** [comment]
QA’d, lgtm
