### ISSUE TITLE
(Week 1) Support ticket analysis

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#964]
### Questions to answer
What are the blockers to PTMs using Notify related to
- the current set of features? (esp. Team/permissions management)
- The current value proposition?
- Forking Notify
- Approvals
- Volume
- Security

[Airtable](https://airtable.com/invite/l?inviteId=invXB6EhTkdag4AGI&inviteToken=501b50af56aee24dd29e2e9addc2e448aa2905b121f6cb0a3f04cb815dfa0fa2&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts)

[Summary Document](https://docs.google.com/document/d/13ULtiBrwRwmbjEtTqRigkkZaTHwV-nqB8AH1HFk4GXo/edit#)

**Comment by yaelberger-commits** [comment]
@smcmurtry @andrewleith 
I will spend an hour this morning creating a spreadsheet in Airtable for us to drop all the info from the P/T tickets we've gotten 

Perhaps we can divide up the provinces/territories and each look at tickets from that PT?

**Comment by yaelberger-commits** [comment]
Yael, Steve M and Andrew tagged and analyzed tickets and summarized in a doc. Ready for review

**Comment by yaelberger-commits** [comment]
Yael will demo today
