### ISSUE TITLE
(Week 1) Stakeholder mapping

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#965]
### Questions to answer
In order for PTM interviews to be helpful, who are the interview respondents with specific roles or decision-making authority?
What bodies could fall under  PTMs?  Could these include administrative tribunals at the provincial level?

**Comment by adriannelee** [comment]
@yaelberger-commits I created this [Miro board](https://miro.com/app/board/uXjVPINEzSk=/?moveToWidget=3458764537963591234&cot=14) Do you think it's too much for answering the questions?

**Comment by yaelberger-commits** [comment]
@adriannelee I'm taking a look!

**Comment by adriannelee** [comment]
Closing - since we already know who we want to speak with and how we'll keep them involved.
