### ISSUE TITLE
(Week 3) Cost analysis

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#967]
### Questions to answer
* Could we afford to cover the costs of more services and is there a cap or upper limit to how much we can spend monthly or annually to run Notify?

**Comment by sastels** [comment]
- Current AWS costs are about $8600 CAD / month, and should scale roughly with usage (for example, SMS is about half the cost currently).

**Comment by andrewleith** [comment]
@sastels created a spreadsheet to calculate costs over the last few months.  It allows us to enter estimates into the sheet and project costs based on those.

**Comment by sastels** [comment]
See https://docs.google.com/spreadsheets/d/1G8XClakRQjY_vQz5FYwqZn3ze8DMS6AYKyxa8A8W8tA

**Comment by sastels** [comment]
We have confirmation from Josh that reasonable increases in costs will be covered if we can justify the increases.

**Comment by yaelberger-commits** [comment]
Moving to Done since this was presented at Demo
