### ISSUE TITLE
(Week 2) Policy inquiries

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#970]
### Questions to answer

- What do we mean by “serve” in “serve more people”? Do we need to define standards for this so that Notify is not used in ways that ignore the needs of members of the public?
- Could we align Notify’s reliability standards with legal guarantees of procedural fairness in administrative processes? Do we need to add disclaimers to our SLA and Terms of Use about this?

**Comment by andrewleith** [comment]
@sharlychan-cds working on a document.  Focusing on Quebec as they require inter-governmental agreements to be signed. This will continue today

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/970?planning-poker) with Zenhub @sharlychan-cds

**Comment by andrewleith** [comment]
- @sharlychan-cds working on this, meeting with platform policy on Wednesday

**Comment by andrewleith** [comment]
@sharlychan-cds will finalize this document to get it ready for review this week

**Comment by andrewleith** [comment]
@sharlychan-cds to finish this today

**Comment by jimleroyer** [comment]
@sharlychan-cds to bring additional fixes. This card also fixed #977.

**Comment by sharlychan-cds** [comment]
https://docs.google.com/document/d/1U4q5GhT4GyJSjEw2ZzqajQjVZMq-PXlFS3JsGydPu_Y/edit#
