### ISSUE TITLE
(Week 2) Desk research - look at language options for existing PTM services

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#971]
### Questions to answer
* What kind of language needs will PTM Recipients have from PTM Senders' perspectives?

**Comment by YedidaZalik** [comment]
Airtable https://airtable.com/app3wqw9YwXen4iBR/tbljYkBuE4e0eHP1i/viwnb6D5WVWfbBjbD?blocks=hide

**Comment by adriannelee** [comment]
Few more to do to get a more holistic view of PT

**Comment by andrewleith** [comment]
Here is an analysis based on 113 provincial, territorial and municipal websites:
![image](https://user-images.githubusercontent.com/823749/201664599-d3cc8f48-39f9-4f1c-a087-eafd4551cec7.png)

**Comment by andrewleith** [comment]
This will be compiled into a summary at the end as well as a set of recommendations for the team.

@andrewleith to make sure the pie chart and data are in the drive folder
