### ISSUE TITLE
(Week 2) Review Sharly's policy doc outlining 3 models for PT structures for using Notify

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#973]
### Questions to answer
* Do PTMs who want to use Notify require approvals? From whom?

[Doc](https://docs.google.com/document/d/1168JUTpIAAAdSDJ1uyaiHvxia6htrVQQYxFHC6DGMHc/edit?usp=drive_web&ouid=113859129089047660316)

**Comment by adriannelee** [comment]
Sharly starting on this today. Will review PTM support tickets summary.

**Comment by adriannelee** [comment]
I reviewed :)

**Comment by YedidaZalik** [comment]
I reviewed, very interesting!!

**Comment by sharlychan-cds** [comment]
Added some updated info!
