### ISSUE TITLE
(Week 2) Review Unified Accounts work on managing bodies

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#974]
### Questions to answer
* Does having no service owner/ managing body for PTs create barriers for PTM teams?
* Would managing bodies block or unblock adoption of Notify? re: our mission for self-serve tools

**Comment by jimleroyer** [comment]
I wrote this document following my reading of the report on unified accounts work. I added a bit more to it following the read, but also, there might be barriers more at the team level than at the user's level, but which will still impact the latter. Feedback is welcome, I am unsure if that is satisfactory.

https://docs.google.com/document/d/1d4IUmlGasxPCKNjkZt-WMQTHVvj6r2kWHmcQbwf8pZc

**Comment by andrewleith** [comment]
Waiting for review from team.

**Comment by yaelberger-commits** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/974?planning-poker) with Zenhub @jimleroyer

**Comment by yaelberger-commits** [comment]
Moving to Done since this was presented at Demo
