### ISSUE TITLE
(Week 2) Desk research - case studies of similar scenarios (lessons learned)

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#975]
### Questions to answer
* What sort of formal documentation would be required for PTMs?
* Historically, what were the outcomes of a similar scenario where a federal product/service was used by another jurisdiction? What are the outcomes?

[Notes](https://docs.google.com/document/d/1xcZ0N52gvgFTekiokUkP59B7PqwGfr4PTH9FzedW8Ms/edit)

**Comment by adriannelee** [comment]
I read through :)

**Comment by yaelberger-commits** [comment]
Answering these through stakeholder Interviews. @adriannelee Did you want to also do desk research to learn more? Or shall we move this to done?

**Comment by andrewleith** [comment]
- this work could help us understand some of the political risks associated
- we could investigate more about examples we heard during interviews
- we may need to tackle this after the discovery and reach out to other departments

**Comment by andrewleith** [comment]
@YedidaZalik is working on this today, hoping to write up the summary today

**Comment by YedidaZalik** [comment]
Attaching the [desk research of lessons learned from similar scenarios](https://docs.google.com/document/d/1xcZ0N52gvgFTekiokUkP59B7PqwGfr4PTH9FzedW8Ms/edit#): "So What" at the top of the document, followed by the Summary of the research, followed by the notes Adrianne made from the interviews and my notes/quotes from websites and reports.

**Comment by jimleroyer** [comment]
Reviewed was done of the task by Yael and Adrianne. Will ping @YedidaZalik for card's updates.
