### ISSUE TITLE
(Week 3) Legislative review? re: existing policy documentation

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#976]
### Questions to answer
* What sort of formal documentation would be required for PTMs?
* Historically, what were the outcomes of a similar scenario where a federal product/service was used by another jurisdiction? What are the outcomes?

**Comment by sharlychan-cds** [comment]
https://docs.google.com/document/d/1U4q5GhT4GyJSjEw2ZzqajQjVZMq-PXlFS3JsGydPu_Y/edit#
