### ISSUE TITLE
(Week 1) Demographic research

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#978]
### Questions to answer
* What kind of access to technology do members of the public within PTMs have? (text vs. email)

[Notes](https://docs.google.com/document/d/1Y4K1jo1WiU4gIVJwglqaVpcx3ExdF-lxrjA11nwtrPI/edit)

**Comment by adriannelee** [comment]
Yedida and Phil compiled lots of research. I tried to summarize. @YedidaZalik and @amazingphilippe Can you add to / review it?

**Comment by YedidaZalik** [comment]
I have a few more items to add still

**Comment by andrewleith** [comment]
This should be wrapped up - @amazingphilippe, @YedidaZalik, @adriannelee writing a summary
There are reports that PTMs know what the notification preferences of their constituents are.  We could dig into these for info.

**Comment by amazingphilippe** [comment]
Synced with Adrianne to wrap up summary of research. Read one last report on smarter cities and finished the summary.

**Comment by andrewleith** [comment]
@adriannelee to review
