### ISSUE TITLE
(Week 1) Estimate of volume for PTMs if we were to open up

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#980]
### Questions to answer
* What's the estimate of volume for PTMs if we were to open up?

**Comment by andrewleith** [comment]
I've started looking into this this morning.  I've added a table to the existing PTM Languages airtable here: https://airtable.com/app3wqw9YwXen4iBR/tbl6sZnMjanht1BvE/viwIzgKQLY1A249sI?blocks=hide

**Comment by yaelberger-commits** [comment]
I can hop in a bit tomorrow morning to add to the airtable for this @andrewleith

**Comment by smcmurtry** [comment]
Here's the doc in progress: https://docs.google.com/document/d/1kPifZqw-WWpw0GKJjpaB-YTE_lKcDGQl-FmrP4EgvpM/edit?usp=sharing

**Comment by smcmurtry** [comment]
I'm taking a different approach than the one originally suggested. I'm looking at historical sending volume data for GC and PTM services in Notify, and then making predictions for some different future scenarios where PTM sending volumes increase.

**Comment by smcmurtry** [comment]
Here's the code used to make the forecasts: https://github.com/cds-snc/notification-attic/pull/24

**Comment by andrewleith** [comment]
If there are any suggestions/comments please slack @smcmurtry.
@sastels also did some queries earlier in the week.  

The two analyses have different numbers for what constitutes PTM vs federal services.  Some work needs to be done to clean up our data and correctly reflect the type of services we have.

@sastels will create a new card should be created to do some data cleanup for services so we can scope it.

**Comment by yaelberger-commits** [comment]
Previous projections from May 2022 
https://docs.google.com/spreadsheets/d/1jK84AMqOxh1mr4XlphZ-cmOss3fySpAqMTD8MHvrkcM/edit#gid=1178940197

**Comment by sastels** [comment]
Cards around cleaning up organizations and linking them to type (ie GoC, PTM): #461, #995

**Comment by yaelberger-commits** [comment]
Moving to Done since this was presented at Demo
