### ISSUE TITLE
(Week 3) Consult with SRE

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#982]
### Questions to answer
* Will introducing more clients lead to increased security risk?

## Notes
https://docs.google.com/document/d/1bsWyvbXD-2p0otOTUvZLvPyW09KvOPiSLMCo5XOLzl0/edit

**Comment by andrewleith** [comment]
@yaelberger-commits to setup a sync

**Comment by yaelberger-commits** [comment]
Had planning meeting last week. Meeting with SRE this week

**Comment by yaelberger-commits** [comment]
Josh reviewing as an FYI
