### ISSUE TITLE
(Week 1) Look at existing PTM services in Notify

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#983]
### Questions to answer
* How important is branding/ customization to a PTM?
* In general, do PTMs have dev teams on staff that can integrate Notify programatically?
* What are the use cases PTMs have in mind for Notify?

**Comment by sastels** [comment]
Current PTM branding and api usage
https://docs.google.com/spreadsheets/d/1Fdsqq-sA2o2IawB29esRRGs5m0m05TA1U32dofAKIcg

**Comment by adriannelee** [comment]
@sastels I put it in [this folder](https://drive.google.com/drive/folders/10mg1PUptaVObDyy7rrw9OdbsIPXtMrIo) btw! (inside the PTM Discovery folder)

**Comment by yaelberger-commits** [comment]
I reviewed and I think this data does a good preliminary job of answering the above research questions. It's a very good starting off point for future post-Discovery work as well. Moving to done
