### ISSUE TITLE
Custom logo not appearing in Outlook on iPhone

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#984]
## Describe the bug 

We have an issue with Notify and custom branding.
This happens only when the recipient is using the Outlook app on their iPhone. The custom logo doesn’t appear, but note that if the default GC logo is used, it appears fine. If they hit Forward on the e-mail, the logo is displayed correctly. Jimmy P. was able to replicate the issue with another custom logo as well.

Theory is maybe a question of logo sizing not handled properly on a smaller screen size. I am attaching the HTML source of the message, and a video of me reproducing the issue. [Freshdesk ticket #9734](https://cds-snc.freshdesk.com/a/tickets/9734)

Any insight would be appreciated. Many public servants use Outlook and iPhones, so it would be important for the custom branding to be displayed properly.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2  Major, affecting some users, or some downstream effects on users. Less urgency but high priority. Work on it as soon as possible.

## Expected behavior

Custom logo should appear at the top of the email in Outlook when viewing on an iPhone

## Impact

Impact on confidence users have that their message will appear as intended. Could have an impact on trust with end recipients that they cannot be sure this is a legitimate email.

Especially would have an impact on emails to public servants who often use government issued iphones to access Outlook.

If applicable

Impact on Notify users: Impact on confidence users have that their message will appear as intended. Especially would have an impact on emails to public servants who often use government issued iphones to access Outlook.

Impact on Recipients: Could have an impact on trust with end recipients that they cannot be sure this is a legitimate email.

Impact on Notify team: 

## Screenshots

https://images.zenhubusercontent.com/409232714/3a3eb0e9-0a02-4d3c-8347-1d179837fa06/outlook_iphone.mp4

**Comment by smcmurtry** [comment]
I have been able to reproduce this. When I send the same image embedded in an email from gmail (not Notify), Outlook does display the image. Here is the difference in the html element:

From gmail, displayed correctly:
```
<img 
src="https://mail.google.com/mail/u/0?ui=2&amp;ik=65cd1b8560&amp;attid=0.1&amp;permmsgid=msg-f:1754739537360670648&amp;th=185a164fedb74fb8&amp;view=fimg&amp;fur=ip&amp;sz=s0-l75-ft&amp;attbid=ANGjdJ8bD0B7MYuwJ9-pMPj9GeF0UpYJ1NXKG3Pla-GzN5SPf37EweG5Pl3Nwt9WfCMSvbzUTedRDKyEfknGfFc4h8_p5Lx9w4ZP0CNc0TEyJS5_TURIkDKvZCwkq3c&amp;disp=emb&amp;realattid=ii_lcrsxh7y0" 
alt="wage_test.png" 
width="542" 
height="97" 
data-image-whitelisted="" 
class="CToWUd" 
data-bit="iit"
>
```

From Notify, not displayed correctly:
```
<img 
src="https://ci5.googleusercontent.com/proxy/6nGdlyHSuS4gU4lAOCOf8AfhVXOQ1Q7XLJoxrs87SAY6ClTGeXnyCug3VJ-p_SV35eBIxKnWh2W4p4_JVyE_bEc3jaxSemxSyXw7Pt1S2EvT_x9VjXx3lYp6wNsDOPd2RxwMyqu9LuWdMHY=s0-d-e1-ft#https://assets.notification.canada.ca/85d3b2cf-85f8-4f50-a7d6-6ef2741cd689-FEGC-WAGE.png" 
style="display:block;border:0" 
height="108" 
alt="FEGC-WAGE" 
class="CToWUd" 
data-bit="iit"
>
```

**Comment by yaelberger-commits** [comment]
@andrewleith started reviewing

**Comment by smcmurtry** [comment]
Andrew approved, this is now merged. But we found a related bug where it's not working if you include text as part of the custom branding. I created a separate card for that: https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1069.
