### ISSUE TITLE
(Week 4) Write user stories from PTM perspective

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#987]
- [x] User stories from the business perspective
- [x] User stories from the PTM perspective
- [ ] User group segmentation

We will use some journey mapping to map problem statements and build user stories from there before segmenting user groups.

Miro: https://miro.com/app/board/uXjVP_eIlSk=/

**Comment by adriannelee** [comment]
Hey @Pensai I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by andrewleith** [comment]
- waiting on interview analysis 
- need a meeting to discuss towards the end of the week (possibly next week)

**Comment by yaelberger-commits** [comment]
A few stakeholders also mentioned in their interviews with us that they would expect to see some segmentation of user groups as well

**Comment by amazingphilippe** [comment]
Miro board for story mapping: https://miro.com/app/board/uXjVP_eIlSk=/?moveToWidget=3458764539854370866&cot=14

**Comment by andrewleith** [comment]
Team will work on this today during journey mapping session.

**Comment by jimleroyer** [comment]
Created some stories based on this task. Tasks are in Miro for journey mapping. This would complete ACs.
