### ISSUE TITLE
Custom branding does not work properly in staging

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#988]
## Describe the bug 

Due to a missing environment variable, custom branding in staging tries to load images from PROD and fails.

To fix, we need to add a environment variable names `ASSET_DOMAIN` with the value `assets.staging.notification.cdssandbox.xyz`.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-4 Low

## To Reproduce

- Add a custom brand to your service
- Send yourself and email
- See broken image in email

## Expected behavior
- The image should load correctly

## Impact

Low, only in staging

**Comment by sastels** [comment]
Fixed in https://github.com/cds-snc/notification-manifests/pull/1513
