### ISSUE TITLE
Warning emails are not re-sent following limit change

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#991]
## Describe the bug 

A warning email will be sent to service users when a service reaches 80% of their daily limit. However, after this point if the limit is then increased the users will not receive a second email when they again reach 80% of their new limit.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
Sev-4 Low

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

## To Reproduce

1. Set service daily overall limit to 10
2. Send 8 emails
3. Ensure warning email received
4. Increase limit to 11
5. Send another email

## Expected behavior
6. Another warning email should be sent

## Impact

Impact on Notify users:
- Less awareness of approaching limits

Impact on Recipients:
- None

Impact on Notify team: 
- Potential increase in support requests

**Comment by andrewleith** [comment]
- no progress yet, will come back to this when incident work is done

**Comment by andrewleith** [comment]
- work has started but not yet complete

**Comment by jzbahrai** [comment]
done: https://github.com/cds-snc/notification-api/pull/2056

**Comment by adriannelee** [comment]
Will to review this today
