### ISSUE TITLE
Fix organisation types

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#995]
## Description

As a Notify team member, I need to be able to classify organizations as federal or PTM so that I can easily determine which services are PTMs.

Organizations can have a "type". Currently we don't use this feature and set all organizations to "central". In the code, types are UK specific (there are three NHS ones) but we could change them to be useful to us (ex: provincial or municipal).

Right now there's a page to set the type but it doesn't work (?) First step on fixing organisations is fixing this.

Note that this is related to [Fixing Organization names in Notify Admin #461](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/461).

## Acceptance Criteria** (Definition of done) 

- [ ] Organisation types can be set through admin.

## QA Steps

- [x] Create a new org and set the type to something
- [x] Verify that the type is correct on the settings page
- [x] Clear organisations from Redis. verify that the type is still correct on the settings page.
- [x] change the type to something else
- [x] verify that the new type is on the settings page
- [x] Clear organisations from Redis. verify that the type is still correct on the settings page.

**Comment by andrewleith** [comment]
This opens up the organization types in the admin panel. 

@jzbahrai will QA
