### ISSUE TITLE
Upgrade fluentd image

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#996]
## Description

As a Notify Dev, we need to update our `fluentd` image because the current one has been deprecated, so that we continue to receive application logs to monitor our systems. Failure to update will have the version of fluentd decommissioned and risk of stopping receiving logs properly or at all.

AWS support recommends migrating to fluent bit instead of `fluentd` as container Insights Support for `fluentd` is now in maintenance mode.

They also note there are significant performance gains with fluent bit over `fluentd`.

Reference links:
- [AWS Support case](https://support.console.aws.amazon.com/support/home?region=ca-central-1#/case/?displayId=11226860111&language=en)
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html 
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs-FluentBit.html#Container-Insights-setup-logs-FluentBit-migrate 
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs-FluentBit.html 

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
https://github.com/cds-snc/notification-manifests/pull/1769 Looks like we replaced fluentd with fluentbit
